ETISS 0.8.0: include/jit/clang_stdlib/__clang_cuda_math_forward_declares.h File Reference
__clang_cuda_math_forward_declares.h File Reference
Macros
#define __DEVICE__ static __inline__ __attribute__((always_inline)) __attribute__((device))
Functions
__DEVICE__ long abs (long)
__DEVICE__ long long abs (long long)
__DEVICE__ double abs (double)
__DEVICE__ float abs (float)
__DEVICE__ int abs (int)
__DEVICE__ double acos (double)
__DEVICE__ float acos (float)
__DEVICE__ double acosh (double)
__DEVICE__ float acosh (float)
__DEVICE__ double asin (double)
__DEVICE__ float asin (float)
__DEVICE__ double asinh (double)
__DEVICE__ float asinh (float)
__DEVICE__ double atan2 (double, double)
__DEVICE__ float atan2 (float, float)
__DEVICE__ double atan (double)
__DEVICE__ float atan (float)
__DEVICE__ double atanh (double)
__DEVICE__ float atanh (float)
__DEVICE__ double cbrt (double)
__DEVICE__ float cbrt (float)
__DEVICE__ double ceil (double)
__DEVICE__ float ceil (float)
__DEVICE__ double copysign (double, double)
__DEVICE__ float copysign (float, float)
__DEVICE__ double cos (double)
__DEVICE__ float cos (float)
__DEVICE__ double cosh (double)
__DEVICE__ float cosh (float)
__DEVICE__ double erfc (double)
__DEVICE__ float erfc (float)
__DEVICE__ double erf (double)
__DEVICE__ float erf (float)
__DEVICE__ double exp2 (double)
__DEVICE__ float exp2 (float)
__DEVICE__ double exp (double)
__DEVICE__ float exp (float)
__DEVICE__ double expm1 (double)
__DEVICE__ float expm1 (float)
__DEVICE__ double fabs (double)
__DEVICE__ float fabs (float)
__DEVICE__ double fdim (double, double)
__DEVICE__ float fdim (float, float)
__DEVICE__ double floor (double)
__DEVICE__ float floor (float)
__DEVICE__ double fma (double, double, double)
__DEVICE__ float fma (float, float, float)
__DEVICE__ double fmax (double, double)
__DEVICE__ float fmax (float, float)
__DEVICE__ double fmin (double, double)
__DEVICE__ float fmin (float, float)
__DEVICE__ double fmod (double, double)
__DEVICE__ float fmod (float, float)
__DEVICE__ int fpclassify (double)
__DEVICE__ int fpclassify (float)
__DEVICE__ double frexp (double, int *)
__DEVICE__ float frexp (float, int *)
__DEVICE__ double hypot (double, double)
__DEVICE__ float hypot (float, float)
__DEVICE__ int ilogb (double)
__DEVICE__ int ilogb (float)
__DEVICE__ bool isfinite (double)
__DEVICE__ bool isfinite (float)
__DEVICE__ bool isgreater (double, double)
__DEVICE__ bool isgreaterequal (double, double)
__DEVICE__ bool isgreaterequal (float, float)
__DEVICE__ bool isgreater (float, float)
__DEVICE__ bool isinf (double)
__DEVICE__ bool isinf (float)
__DEVICE__ bool isless (double, double)
__DEVICE__ bool islessequal (double, double)
__DEVICE__ bool islessequal (float, float)
__DEVICE__ bool isless (float, float)
__DEVICE__ bool islessgreater (double, double)
__DEVICE__ bool islessgreater (float, float)
__DEVICE__ bool isnan (double)
__DEVICE__ bool isnan (float)
__DEVICE__ bool isnormal (double)
__DEVICE__ bool isnormal (float)
__DEVICE__ bool isunordered (double, double)
__DEVICE__ bool isunordered (float, float)
__DEVICE__ long labs (long)
__DEVICE__ double ldexp (double, int)
__DEVICE__ float ldexp (float, int)
__DEVICE__ double lgamma (double)
__DEVICE__ float lgamma (float)
__DEVICE__ long long llabs (long long)
__DEVICE__ long long llrint (double)
__DEVICE__ long long llrint (float)
__DEVICE__ double log10 (double)
__DEVICE__ float log10 (float)
__DEVICE__ double log1p (double)
__DEVICE__ float log1p (float)
__DEVICE__ double log2 (double)
__DEVICE__ float log2 (float)
__DEVICE__ double logb (double)
__DEVICE__ float logb (float)
__DEVICE__ double log (double)
__DEVICE__ float log (float)
__DEVICE__ long lrint (double)
__DEVICE__ long lrint (float)
__DEVICE__ long lround (double)
__DEVICE__ long lround (float)
__DEVICE__ long long llround (float)
__DEVICE__ double modf (double, double *)
__DEVICE__ float modf (float, float *)
__DEVICE__ double nan (const char *)
__DEVICE__ float nanf (const char *)
__DEVICE__ double nearbyint (double)
__DEVICE__ float nearbyint (float)
__DEVICE__ double nextafter (double, double)
__DEVICE__ float nextafter (float, float)
__DEVICE__ double pow (double, double)
__DEVICE__ double pow (double, int)
__DEVICE__ float pow (float, float)
__DEVICE__ float pow (float, int)
__DEVICE__ double remainder (double, double)
__DEVICE__ float remainder (float, float)
__DEVICE__ double remquo (double, double, int *)
__DEVICE__ float remquo (float, float, int *)
__DEVICE__ double rint (double)
__DEVICE__ float rint (float)
__DEVICE__ double round (double)
__DEVICE__ float round (float)
__DEVICE__ double scalbln (double, long)
__DEVICE__ float scalbln (float, long)
__DEVICE__ double scalbn (double, int)
__DEVICE__ float scalbn (float, int)
__DEVICE__ bool signbit (double)
__DEVICE__ bool signbit (float)
__DEVICE__ double sin (double)
__DEVICE__ float sin (float)
__DEVICE__ double sinh (double)
__DEVICE__ float sinh (float)
__DEVICE__ double sqrt (double)
__DEVICE__ float sqrt (float)
__DEVICE__ double tan (double)
__DEVICE__ float tan (float)
__DEVICE__ double tanh (double)
__DEVICE__ float tanh (float)
__DEVICE__ double tgamma (double)
__DEVICE__ float tgamma (float)
__DEVICE__ double trunc (double)
__DEVICE__ float trunc (float)
Macro Definition Documentation
__DEVICE__
#define __DEVICE__ static __inline__ __attribute__((always_inline)) __attribute__((device))
Definition at line 23 of file __clang_cuda_math_forward_declares.h.
Function Documentation
abs() [1/5]
__DEVICE__ double abs (double) inline
Definition at line 44 of file __clang_cuda_cmath.h.
References __x, and fabs().
abs() [2/5]
__DEVICE__ float abs (float) inline
Definition at line 43 of file __clang_cuda_cmath.h.
References __x, and fabsf().
abs() [3/5]
__DEVICE__ int abs (int) inline
Definition at line 56 of file __clang_cuda_math.h.
abs() [4/5]
__DEVICE__ long long abs (long long)
Definition at line 41 of file __clang_cuda_cmath.h.
References llabs().
abs() [5/5]
__DEVICE__ long abs (long)
Definition at line 42 of file __clang_cuda_cmath.h.
acos() [1/2]
__DEVICE__ double acos (double) inline
Definition at line 58 of file __clang_cuda_math.h.
References __a, __nv_acos(), and __x.
acos() [2/2]
__DEVICE__ float acos (float)
Definition at line 45 of file __clang_cuda_cmath.h.
acosh() [1/2]
__DEVICE__ double acosh (double) inline
Definition at line 60 of file __clang_cuda_math.h.
References __a, __nv_acosh(), and __x.
acosh() [2/2]
__DEVICE__ float acosh (float)
asin() [1/2]
__DEVICE__ double asin (double) inline
Definition at line 62 of file __clang_cuda_math.h.
References __a, __nv_asin(), and __x.
asin() [2/2]
__DEVICE__ float asin (float)
Definition at line 46 of file __clang_cuda_cmath.h.
asinh() [1/2]
__DEVICE__ double asinh (double) inline
Definition at line 64 of file __clang_cuda_math.h.
References __a, __nv_asinh(), and __x.
asinh() [2/2]
__DEVICE__ float asinh (float)
atan() [1/2]
__DEVICE__ double atan (double) inline
Definition at line 66 of file __clang_cuda_math.h.
References __a, __nv_atan(), and __x.
atan() [2/2]
__DEVICE__ float atan (float)
Definition at line 47 of file __clang_cuda_cmath.h.
atan2() [1/2]
__DEVICE__ double atan2 (double , double) inline
Definition at line 67 of file __clang_cuda_math.h.
References __a, __b, __nv_atan2(), __x, and __y.
atan2() [2/2]
__DEVICE__ float atan2 (float , float)
Definition at line 48 of file __clang_cuda_cmath.h.
atanh() [1/2]
__DEVICE__ double atanh (double) inline
Definition at line 70 of file __clang_cuda_math.h.
References __a, __nv_atanh(), and __x.
atanh() [2/2]
__DEVICE__ float atanh (float)
cbrt() [1/2]
__DEVICE__ double cbrt (double) inline
Definition at line 72 of file __clang_cuda_math.h.
References __a, __nv_cbrt(), and __x.
cbrt() [2/2]
__DEVICE__ float cbrt (float)
ceil() [1/2]
__DEVICE__ double ceil (double) inline
Definition at line 74 of file __clang_cuda_math.h.
References __a, __nv_ceil(), and __x.
ceil() [2/2]
__DEVICE__ float ceil (float)
Definition at line 49 of file __clang_cuda_cmath.h.
copysign() [1/2]
__DEVICE__ double copysign (double , double) inline
Definition at line 76 of file __clang_cuda_math.h.
References __a, __b, __nv_copysign(), __x, and __y.
copysign() [2/2]
__DEVICE__ float copysign (float , float)
cos() [1/2]
__DEVICE__ double cos (double) inline
Definition at line 82 of file __clang_cuda_math.h.
References __a, __nv_cos(), __ocml_cos_f64(), and __x.
cos() [2/2]
__DEVICE__ float cos (float)
Definition at line 50 of file __clang_cuda_cmath.h.
cosh() [1/2]
__DEVICE__ double cosh (double) inline
Definition at line 86 of file __clang_cuda_math.h.
References __a, __nv_cosh(), and __x.
cosh() [2/2]
__DEVICE__ float cosh (float)
Definition at line 51 of file __clang_cuda_cmath.h.
erf() [1/2]
__DEVICE__ double erf (double) inline
Definition at line 94 of file __clang_cuda_math.h.
References __a, __nv_erf(), and __x.
erf() [2/2]
__DEVICE__ float erf (float)
erfc() [1/2]
__DEVICE__ double erfc (double) inline
Definition at line 95 of file __clang_cuda_math.h.
References __a, __nv_erfc(), and __x.
erfc() [2/2]
__DEVICE__ float erfc (float)
exp() [1/2]
__DEVICE__ double exp (double) inline
Definition at line 104 of file __clang_cuda_math.h.
References __a, __nv_exp(), and __x.
exp() [2/2]
__DEVICE__ float exp (float)
Definition at line 52 of file __clang_cuda_cmath.h.
exp2() [1/2]
__DEVICE__ double exp2 (double) inline
Definition at line 107 of file __clang_cuda_math.h.
References __a, __nv_exp2(), and __x.
exp2() [2/2]
__DEVICE__ float exp2 (float)
expm1() [1/2]
__DEVICE__ double expm1 (double) inline
Definition at line 110 of file __clang_cuda_math.h.
References __a, __nv_expm1(), and __x.
expm1() [2/2]
__DEVICE__ float expm1 (float)
fabs() [1/2]
__DEVICE__ double fabs (double) inline
Definition at line 57 of file __clang_cuda_math.h.
References __a, __nv_fabs(), and __x.
fabs() [2/2]
__DEVICE__ float fabs (float)
Definition at line 53 of file __clang_cuda_cmath.h.
fdim() [1/2]
__DEVICE__ double fdim (double , double) inline
Definition at line 113 of file __clang_cuda_math.h.
References __a, __b, __nv_fdim(), __x, and __y.
fdim() [2/2]
__DEVICE__ float fdim (float , float)
floor() [1/2]
__DEVICE__ double floor (double) inline
Definition at line 123 of file __clang_cuda_math.h.
References __nv_floor(), and __x.
floor() [2/2]
__DEVICE__ float floor (float)
Definition at line 54 of file __clang_cuda_cmath.h.
fma() [1/2]
__DEVICE__ double fma (double , double , double) inline
Definition at line 125 of file __clang_cuda_math.h.
References __a, __b, __c, __nv_fma(), __x, and __y.
fma() [2/2]
__DEVICE__ float fma (float , float , float) inline
Definition at line 1013 of file __clang_hip_math.h.
fmax() [1/2]
__DEVICE__ double fmax (double , double) inline
Definition at line 131 of file __clang_cuda_math.h.
References __a, __b, __nv_fmax(), __x, and __y.
Referenced by max().
fmax() [2/2]
__DEVICE__ float fmax (float , float)
fmin() [1/2]
__DEVICE__ double fmin (double , double) inline
Definition at line 133 of file __clang_cuda_math.h.
References __a, __b, __nv_fmin(), __x, and __y.
Referenced by min().
fmin() [2/2]
__DEVICE__ float fmin (float , float)
fmod() [1/2]
__DEVICE__ double fmod (double , double) inline
Definition at line 135 of file __clang_cuda_math.h.
References __a, __b, __nv_fmod(), __x, and __y.
fmod() [2/2]
__DEVICE__ float fmod (float , float)
Definition at line 55 of file __clang_cuda_cmath.h.
fpclassify() [1/2]
__DEVICE__ int fpclassify (double)
Definition at line 60 of file __clang_cuda_cmath.h.
References __x.
fpclassify() [2/2]
__DEVICE__ int fpclassify (float)
Definition at line 56 of file __clang_cuda_cmath.h.
References __x.
Referenced by convert_number_to_string_special(), and is_nan().
frexp() [1/2]
__DEVICE__ double frexp (double , int *) inline
Definition at line 137 of file __clang_cuda_math.h.
References __a, __b, __nv_frexp(), __ocml_frexp_f64(), and __x.
frexp() [2/2]
__DEVICE__ float frexp (float , int *)
Definition at line 64 of file __clang_cuda_cmath.h.
hypot() [1/2]
__DEVICE__ double hypot (double , double) inline
Definition at line 139 of file __clang_cuda_math.h.
References __a, __b, __nv_hypot(), __x, and __y.
hypot() [2/2]
__DEVICE__ float hypot (float , float)
ilogb() [1/2]
__DEVICE__ int ilogb (double) inline
Definition at line 141 of file __clang_cuda_math.h.
References __a, __nv_ilogb(), and __x.
ilogb() [2/2]
__DEVICE__ int ilogb (float)
isfinite() [1/2]
__DEVICE__ bool isfinite (double) inline
Definition at line 79 of file __clang_cuda_cmath.h.
References __isfinited(), and __x.
isfinite() [2/2]
__DEVICE__ bool isfinite (float) inline
Definition at line 75 of file __clang_cuda_cmath.h.
isgreater() [1/2]
__DEVICE__ bool isgreater (double , double)
Definition at line 87 of file __clang_cuda_cmath.h.
References __x, and __y.
isgreater() [2/2]
__DEVICE__ bool isgreater (float , float)
Definition at line 84 of file __clang_cuda_cmath.h.
isgreaterequal() [1/2]
__DEVICE__ bool isgreaterequal (double , double)
Definition at line 93 of file __clang_cuda_cmath.h.
References __x, and __y.
isgreaterequal() [2/2]
__DEVICE__ bool isgreaterequal (float , float)
Definition at line 90 of file __clang_cuda_cmath.h.
isinf() [1/2]
__DEVICE__ bool isinf (double) inline
Definition at line 74 of file __clang_cuda_cmath.h.
References __isinf(), and __x.
isinf() [2/2]
__DEVICE__ bool isinf (float) inline
Definition at line 73 of file __clang_cuda_cmath.h.
isless() [1/2]
__DEVICE__ bool isless (double , double)
Definition at line 99 of file __clang_cuda_cmath.h.
References __x, and __y.
isless() [2/2]
__DEVICE__ bool isless (float , float)
Definition at line 96 of file __clang_cuda_cmath.h.
islessequal() [1/2]
__DEVICE__ bool islessequal (double , double)
Definition at line 105 of file __clang_cuda_cmath.h.
References __x, and __y.
islessequal() [2/2]
__DEVICE__ bool islessequal (float , float)
Definition at line 102 of file __clang_cuda_cmath.h.
islessgreater() [1/2]
__DEVICE__ bool islessgreater (double , double)
Definition at line 111 of file __clang_cuda_cmath.h.
References __x, and __y.
islessgreater() [2/2]
__DEVICE__ bool islessgreater (float , float)
Definition at line 108 of file __clang_cuda_cmath.h.
isnan() [1/2]
__DEVICE__ bool isnan (double) inline
Definition at line 81 of file __clang_cuda_cmath.h.
References __isnan(), and __x.
isnan() [2/2]
__DEVICE__ bool isnan (float) inline
Definition at line 80 of file __clang_cuda_cmath.h.
isnormal() [1/2]
__DEVICE__ bool isnormal (double)
Definition at line 115 of file __clang_cuda_cmath.h.
References __x.
isnormal() [2/2]
__DEVICE__ bool isnormal (float)
Definition at line 114 of file __clang_cuda_cmath.h.
isunordered() [1/2]
__DEVICE__ bool isunordered (double , double)
Definition at line 119 of file __clang_cuda_cmath.h.
References __x, and __y.
isunordered() [2/2]
__DEVICE__ bool isunordered (float , float)
Definition at line 116 of file __clang_cuda_cmath.h.
labs()
__DEVICE__ long labs (long) inline
Definition at line 152 of file __clang_cuda_math.h.
References __a, __nv_abs(), __x, and CHAR_BIT.
Referenced by abs().
ldexp() [1/2]
__DEVICE__ double ldexp (double , int) inline
Definition at line 154 of file __clang_cuda_math.h.
References __a, __b, __nv_ldexp(), and __x.
ldexp() [2/2]
__DEVICE__ float ldexp (float , int)
Definition at line 122 of file __clang_cuda_cmath.h.
lgamma() [1/2]
__DEVICE__ double lgamma (double) inline
Definition at line 156 of file __clang_cuda_math.h.
References __a, __nv_lgamma(), __ocml_lgamma_f64(), and __x.
lgamma() [2/2]
__DEVICE__ float lgamma (float)
llabs()
__DEVICE__ long long llabs (long long) inline
Definition at line 158 of file __clang_cuda_math.h.
References __a, __nv_llabs(), __x, and CHAR_BIT.
Referenced by abs().
llrint() [1/2]
__DEVICE__ long long llrint (double) inline
Definition at line 165 of file __clang_cuda_math.h.
References __a, __nv_llrint(), and __x.
llrint() [2/2]
__DEVICE__ long long llrint (float)
llround()
__DEVICE__ long long llround (float)
log() [1/2]
__DEVICE__ double log (double) inline
Definition at line 169 of file __clang_cuda_math.h.
References __a, __nv_log(), and __x.
log() [2/2]
__DEVICE__ float log (float)
Definition at line 125 of file __clang_cuda_cmath.h.
log10() [1/2]
__DEVICE__ double log10 (double) inline
Definition at line 170 of file __clang_cuda_math.h.
References __a, __nv_log10(), and __x.
log10() [2/2]
__DEVICE__ float log10 (float)
Definition at line 126 of file __clang_cuda_cmath.h.
log1p() [1/2]
__DEVICE__ double log1p (double) inline
Definition at line 172 of file __clang_cuda_math.h.
References __a, __nv_log1p(), and __x.
log1p() [2/2]
__DEVICE__ float log1p (float)
log2() [1/2]
__DEVICE__ double log2 (double) inline
Definition at line 174 of file __clang_cuda_math.h.
References __a, __nv_log2(), and __x.
log2() [2/2]
__DEVICE__ float log2 (float)
logb() [1/2]
__DEVICE__ double logb (double) inline
Definition at line 178 of file __clang_cuda_math.h.
References __a, __nv_logb(), and __x.
logb() [2/2]
__DEVICE__ float logb (float)
lrint() [1/2]
__DEVICE__ long lrint (double) inline
Definition at line 189 of file __clang_cuda_math.h.
References __a, __x, and rint().
lrint() [2/2]
__DEVICE__ long lrint (float)
lround() [1/2]
__DEVICE__ long lround (double) inline
Definition at line 191 of file __clang_cuda_math.h.
References __a, __x, and round().
lround() [2/2]
__DEVICE__ long lround (float)
modf() [1/2]
__DEVICE__ double modf (double , double *) inline
Definition at line 196 of file __clang_cuda_math.h.
References __a, __b, __nv_modf(), __ocml_modf_f64(), and __x.
modf() [2/2]
__DEVICE__ float modf (float , float *)
Definition at line 127 of file __clang_cuda_cmath.h.
nan()
__DEVICE__ double nan (const char *) inline
Definition at line 703 of file __clang_hip_math.h.
References __make_mantissa(), sign(), and static_assert.
Referenced by fadd_d(), fcmp_d(), fcmp_s(), fconv_d2f(), and fconv_f2d().
nanf()
__DEVICE__ float nanf (const char *) inline
Definition at line 244 of file __clang_hip_math.h.
References __make_mantissa(), sign(), and static_assert.
nearbyint() [1/2]
__DEVICE__ double nearbyint (double) inline
Definition at line 198 of file __clang_cuda_math.h.
References __a, __nv_nearbyint(), and __x.
nearbyint() [2/2]
__DEVICE__ float nearbyint (float)
nextafter() [1/2]
__DEVICE__ double nextafter (double , double) inline
Definition at line 200 of file __clang_cuda_math.h.
References __a, __b, __nv_nextafter(), __x, and __y.
nextafter() [2/2]
__DEVICE__ float nextafter (float , float)
pow() [1/4]
__DEVICE__ double pow (double , double) inline
Definition at line 228 of file __clang_cuda_math.h.
References __a, __b, __nv_pow(), __x, and __y.
pow() [2/4]
__DEVICE__ double pow (double , int)
Definition at line 134 of file __clang_cuda_cmath.h.
References powi().
pow() [3/4]
__DEVICE__ float pow (float , float)
Definition at line 128 of file __clang_cuda_cmath.h.
pow() [4/4]
__DEVICE__ float pow (float , int)
Definition at line 131 of file __clang_cuda_cmath.h.
References powif().
remainder() [1/2]
__DEVICE__ double remainder (double , double) inline
Definition at line 234 of file __clang_cuda_math.h.
References __a, __b, __nv_remainder(), __x, and __y.
remainder() [2/2]
__DEVICE__ float remainder (float , float)
remquo() [1/2]
__DEVICE__ double remquo (double , double , int *) inline
Definition at line 240 of file __clang_cuda_math.h.
References __a, __b, __c, __nv_remquo(), __ocml_remquo_f64(), __x, and __y.
remquo() [2/2]
__DEVICE__ float remquo (float , float , int *)
rint() [1/2]
__DEVICE__ double rint (double) inline
Definition at line 252 of file __clang_cuda_math.h.
References __a, __nv_rint(), and __x.
Referenced by lrint().
rint() [2/2]
__DEVICE__ float rint (float)
round() [1/2]
__DEVICE__ double round (double) inline
Definition at line 272 of file __clang_cuda_math.h.
References __a, __nv_round(), and __x.
Referenced by lround().
round() [2/2]
__DEVICE__ float round (float)
scalbln() [1/2]
__DEVICE__ double scalbln (double , long)
Definition at line 278 of file __clang_cuda_math.h.
References __a, __b, HUGE_VAL, INT_MAX, INT_MIN, and scalbn().
scalbln() [2/2]
__DEVICE__ float scalbln (float , long)
scalbn() [1/2]
__DEVICE__ double scalbn (double , int) inline
Definition at line 276 of file __clang_cuda_math.h.
References __a, __b, __nv_scalbn(), and __x.
Referenced by scalbln().
scalbn() [2/2]
__DEVICE__ float scalbn (float , int)
signbit() [1/2]
__DEVICE__ bool signbit (double) inline
Definition at line 138 of file __clang_cuda_cmath.h.
References __signbitd(), and __x.
signbit() [2/2]
__DEVICE__ bool signbit (float) inline
Definition at line 137 of file __clang_cuda_cmath.h.
sin() [1/2]
__DEVICE__ double sin (double) inline
Definition at line 292 of file __clang_cuda_math.h.
References __a, __nv_sin(), __ocml_sin_f64(), and __x.
sin() [2/2]
__DEVICE__ float sin (float)
Definition at line 139 of file __clang_cuda_cmath.h.
sinh() [1/2]
__DEVICE__ double sinh (double) inline
Definition at line 308 of file __clang_cuda_math.h.
References __a, __nv_sinh(), and __x.
sinh() [2/2]
__DEVICE__ float sinh (float)
Definition at line 140 of file __clang_cuda_cmath.h.
sqrt() [1/2]
__DEVICE__ double sqrt (double) inline
Definition at line 312 of file __clang_cuda_math.h.
References __a, __nv_sqrt(), and __x.
sqrt() [2/2]
__DEVICE__ float sqrt (float)
Definition at line 141 of file __clang_cuda_cmath.h.
tan() [1/2]
__DEVICE__ double tan (double) inline
Definition at line 314 of file __clang_cuda_math.h.
References __a, __nv_tan(), __ocml_tan_f64(), and __x.
tan() [2/2]
__DEVICE__ float tan (float)
Definition at line 142 of file __clang_cuda_cmath.h.
tanh() [1/2]
__DEVICE__ double tanh (double) inline
Definition at line 316 of file __clang_cuda_math.h.
References __a, __nv_tanh(), and __x.
tanh() [2/2]
__DEVICE__ float tanh (float)
Definition at line 143 of file __clang_cuda_cmath.h.
tgamma() [1/2]
__DEVICE__ double tgamma (double) inline
Definition at line 318 of file __clang_cuda_math.h.
References __a, __nv_tgamma(), __ocml_tgamma_f64(), and __x.
tgamma() [2/2]
__DEVICE__ float tgamma (float)
trunc() [1/2]
__DEVICE__ double trunc (double) inline
Definition at line 320 of file __clang_cuda_math.h.
References __a, __nv_trunc(), and __x.
trunc() [2/2]
__DEVICE__ float trunc (float)