ETISS 0.8.0: include/jit/clang_stdlib/__clang_hip_math.h File Reference
__clang_hip_math.h File Reference
#include <algorithm>
#include <limits.h>
#include <limits>
#include <stdint.h>
Classes
struct __hip_enable_if< __B, __T >
struct __hip_enable_if< true, __T >
Macros
#define __DEVICE__ static __device__
#define __RETURN_TYPE bool
#define __HIP_OVERLOAD1(__retty, __fn)
#define __HIP_OVERLOAD2(__retty, __fn)
#define __DEF_FUN1(__retty, __func)
#define __DEF_FUNI(__retty, __func)
#define __DEF_FUN2(__retty, __func)
#define __DEF_FLOAT_FUN2I(__func)
Functions
__DEVICE__ uint64_t __make_mantissa_base8 (const char *__tagp)
__DEVICE__ uint64_t __make_mantissa_base10 (const char *__tagp)
__DEVICE__ uint64_t __make_mantissa_base16 (const char *__tagp)
__DEVICE__ uint64_t __make_mantissa (const char *__tagp)
__DEVICE__ float abs (float __x)
__DEVICE__ float acosf (float __x)
__DEVICE__ float acoshf (float __x)
__DEVICE__ float asinf (float __x)
__DEVICE__ float asinhf (float __x)
__DEVICE__ float atan2f (float __x, float __y)
__DEVICE__ float atanf (float __x)
__DEVICE__ float atanhf (float __x)
__DEVICE__ float cbrtf (float __x)
__DEVICE__ float ceilf (float __x)
__DEVICE__ float copysignf (float __x, float __y)
__DEVICE__ float cosf (float __x)
__DEVICE__ float coshf (float __x)
__DEVICE__ float cospif (float __x)
__DEVICE__ float cyl_bessel_i0f (float __x)
__DEVICE__ float cyl_bessel_i1f (float __x)
__DEVICE__ float erfcf (float __x)
__DEVICE__ float erfcinvf (float __x)
__DEVICE__ float erfcxf (float __x)
__DEVICE__ float erff (float __x)
__DEVICE__ float erfinvf (float __x)
__DEVICE__ float exp10f (float __x)
__DEVICE__ float exp2f (float __x)
__DEVICE__ float expf (float __x)
__DEVICE__ float expm1f (float __x)
__DEVICE__ float fabsf (float __x)
__DEVICE__ float fdimf (float __x, float __y)
__DEVICE__ float fdividef (float __x, float __y)
__DEVICE__ float floorf (float __x)
__DEVICE__ float fmaf (float __x, float __y, float __z)
__DEVICE__ float fmaxf (float __x, float __y)
__DEVICE__ float fminf (float __x, float __y)
__DEVICE__ float fmodf (float __x, float __y)
__DEVICE__ float frexpf (float __x, int *__nptr)
__DEVICE__ float hypotf (float __x, float __y)
__DEVICE__ int ilogbf (float __x)
__DEVICE__ __RETURN_TYPE isfinite (float __x)
Test for finite value.
__DEVICE__ __RETURN_TYPE isinf (float __x)
Test for infinity value (+ve or -ve) .
__DEVICE__ __RETURN_TYPE isnan (float __x)
Test for a NaN.
__DEVICE__ float j0f (float __x)
__DEVICE__ float j1f (float __x)
__DEVICE__ float jnf (int __n, float __x)
__DEVICE__ float ldexpf (float __x, int __e)
__DEVICE__ float lgammaf (float __x)
__DEVICE__ long long int llrintf (float __x)
__DEVICE__ long long int llroundf (float __x)
__DEVICE__ float log10f (float __x)
__DEVICE__ float log1pf (float __x)
__DEVICE__ float log2f (float __x)
__DEVICE__ float logbf (float __x)
__DEVICE__ float logf (float __x)
__DEVICE__ long int lrintf (float __x)
__DEVICE__ long int lroundf (float __x)
__DEVICE__ float modff (float __x, float *__iptr)
__DEVICE__ float nanf (const char *__tagp)
__DEVICE__ float nearbyintf (float __x)
__DEVICE__ float nextafterf (float __x, float __y)
__DEVICE__ float norm3df (float __x, float __y, float __z)
__DEVICE__ float norm4df (float __x, float __y, float __z, float __w)
__DEVICE__ float normcdff (float __x)
__DEVICE__ float normcdfinvf (float __x)
__DEVICE__ float normf (int __dim, const float *__a)
__DEVICE__ float powf (float __x, float __y)
__DEVICE__ float rcbrtf (float __x)
__DEVICE__ float remainderf (float __x, float __y)
__DEVICE__ float remquof (float __x, float __y, int *__quo)
__DEVICE__ float rhypotf (float __x, float __y)
__DEVICE__ float rintf (float __x)
__DEVICE__ float rnorm3df (float __x, float __y, float __z)
__DEVICE__ float rnorm4df (float __x, float __y, float __z, float __w)
__DEVICE__ float rnormf (int __dim, const float *__a)
__DEVICE__ float roundf (float __x)
__DEVICE__ float rsqrtf (float __x)
__DEVICE__ float scalblnf (float __x, long int __n)
__DEVICE__ float scalbnf (float __x, int __n)
__DEVICE__ __RETURN_TYPE signbit (float __x)
Test for sign bit.
__DEVICE__ void sincosf (float __x, float *__sinptr, float *__cosptr)
__DEVICE__ void sincospif (float __x, float *__sinptr, float *__cosptr)
__DEVICE__ float sinf (float __x)
__DEVICE__ float sinhf (float __x)
__DEVICE__ float sinpif (float __x)
__DEVICE__ float sqrtf (float __x)
__DEVICE__ float tanf (float __x)
__DEVICE__ float tanhf (float __x)
__DEVICE__ float tgammaf (float __x)
__DEVICE__ float truncf (float __x)
__DEVICE__ float y0f (float __x)
__DEVICE__ float y1f (float __x)
__DEVICE__ float ynf (int __n, float __x)
__DEVICE__ float __cosf (float __x)
__DEVICE__ float __exp10f (float __x)
__DEVICE__ float __expf (float __x)
__DEVICE__ float __fadd_rn (float __x, float __y)
__DEVICE__ float __fdiv_rn (float __x, float __y)
__DEVICE__ float __fdividef (float __x, float __y)
__DEVICE__ float __fmaf_rn (float __x, float __y, float __z)
__DEVICE__ float __fmul_rn (float __x, float __y)
__DEVICE__ float __frcp_rn (float __x)
__DEVICE__ float __frsqrt_rn (float __x)
__DEVICE__ float __fsqrt_rn (float __x)
__DEVICE__ float __fsub_rn (float __x, float __y)
__DEVICE__ float __log10f (float __x)
__DEVICE__ float __log2f (float __x)
__DEVICE__ float __logf (float __x)
__DEVICE__ float __powf (float __x, float __y)
__DEVICE__ float __saturatef (float __x)
__DEVICE__ void __sincosf (float __x, float *__sinptr, float *__cosptr)
__DEVICE__ float __sinf (float __x)
__DEVICE__ float __tanf (float __x)
__DEVICE__ double abs (double __x)
__DEVICE__ double acos (double __x)
__DEVICE__ double acosh (double __x)
__DEVICE__ double asin (double __x)
__DEVICE__ double asinh (double __x)
__DEVICE__ double atan (double __x)
__DEVICE__ double atan2 (double __x, double __y)
__DEVICE__ double atanh (double __x)
__DEVICE__ double cbrt (double __x)
__DEVICE__ double ceil (double __x)
__DEVICE__ double copysign (double __x, double __y)
__DEVICE__ double cos (double __x)
__DEVICE__ double cosh (double __x)
__DEVICE__ double cospi (double __x)
__DEVICE__ double cyl_bessel_i0 (double __x)
__DEVICE__ double cyl_bessel_i1 (double __x)
__DEVICE__ double erf (double __x)
__DEVICE__ double erfc (double __x)
__DEVICE__ double erfcinv (double __x)
__DEVICE__ double erfcx (double __x)
__DEVICE__ double erfinv (double __x)
__DEVICE__ double exp (double __x)
__DEVICE__ double exp10 (double __x)
__DEVICE__ double exp2 (double __x)
__DEVICE__ double expm1 (double __x)
__DEVICE__ double fabs (double __x)
__DEVICE__ double fdim (double __x, double __y)
__DEVICE__ double floor (double __x)
__DEVICE__ double fma (double __x, double __y, double __z)
__DEVICE__ double fmax (double __x, double __y)
__DEVICE__ double fmin (double __x, double __y)
__DEVICE__ double fmod (double __x, double __y)
__DEVICE__ double frexp (double __x, int *__nptr)
__DEVICE__ double hypot (double __x, double __y)
__DEVICE__ int ilogb (double __x)
__DEVICE__ __RETURN_TYPE isfinite (double __x)
__DEVICE__ __RETURN_TYPE isinf (double __x)
__DEVICE__ __RETURN_TYPE isnan (double __x)
__DEVICE__ double j0 (double __x)
__DEVICE__ double j1 (double __x)
__DEVICE__ double jn (int __n, double __x)
__DEVICE__ double ldexp (double __x, int __e)
__DEVICE__ double lgamma (double __x)
__DEVICE__ long long int llrint (double __x)
__DEVICE__ long long int llround (double __x)
__DEVICE__ double log (double __x)
__DEVICE__ double log10 (double __x)
__DEVICE__ double log1p (double __x)
__DEVICE__ double log2 (double __x)
__DEVICE__ double logb (double __x)
__DEVICE__ long int lrint (double __x)
__DEVICE__ long int lround (double __x)
__DEVICE__ double modf (double __x, double *__iptr)
__DEVICE__ double nan (const char *__tagp)
__DEVICE__ double nearbyint (double __x)
__DEVICE__ double nextafter (double __x, double __y)
__DEVICE__ double norm (int __dim, const double *__a)
__DEVICE__ double norm3d (double __x, double __y, double __z)
__DEVICE__ double norm4d (double __x, double __y, double __z, double __w)
__DEVICE__ double normcdf (double __x)
__DEVICE__ double normcdfinv (double __x)
__DEVICE__ double pow (double __x, double __y)
__DEVICE__ double rcbrt (double __x)
__DEVICE__ double remainder (double __x, double __y)
__DEVICE__ double remquo (double __x, double __y, int *__quo)
__DEVICE__ double rhypot (double __x, double __y)
__DEVICE__ double rint (double __x)
__DEVICE__ double rnorm (int __dim, const double *__a)
__DEVICE__ double rnorm3d (double __x, double __y, double __z)
__DEVICE__ double rnorm4d (double __x, double __y, double __z, double __w)
__DEVICE__ double round (double __x)
__DEVICE__ double rsqrt (double __x)
__DEVICE__ double scalbln (double __x, long int __n)
__DEVICE__ double scalbn (double __x, int __n)
__DEVICE__ __RETURN_TYPE signbit (double __x)
__DEVICE__ double sin (double __x)
__DEVICE__ void sincos (double __x, double *__sinptr, double *__cosptr)
__DEVICE__ void sincospi (double __x, double *__sinptr, double *__cosptr)
__DEVICE__ double sinh (double __x)
__DEVICE__ double sinpi (double __x)
__DEVICE__ double sqrt (double __x)
__DEVICE__ double tan (double __x)
__DEVICE__ double tanh (double __x)
__DEVICE__ double tgamma (double __x)
__DEVICE__ double trunc (double __x)
__DEVICE__ double y0 (double __x)
__DEVICE__ double y1 (double __x)
__DEVICE__ double yn (int __n, double __x)
__DEVICE__ double __dadd_rn (double __x, double __y)
__DEVICE__ double __ddiv_rn (double __x, double __y)
__DEVICE__ double __dmul_rn (double __x, double __y)
__DEVICE__ double __drcp_rn (double __x)
__DEVICE__ double __dsqrt_rn (double __x)
__DEVICE__ double __dsub_rn (double __x, double __y)
__DEVICE__ double __fma_rn (double __x, double __y, double __z)
__DEVICE__ int abs (int __x)
__DEVICE__ long labs (long __x)
__DEVICE__ long long llabs (long long __x)
__DEVICE__ _Float16 fma (_Float16 __x, _Float16 __y, _Float16 __z)
__DEVICE__ float fma (float __x, float __y, float __z)
Returns the correctly rounded floating-point representation of the sum of c with the infinitely precise product of a and b.
__DEF_FUN2 (double, atan2)
__DEF_FUN2 (double, copysign)
__DEF_FUN2 (double, fdim)
__DEF_FUN2 (double, fmax)
__DEF_FUN2 (double, fmin)
__DEF_FUN2 (double, fmod)
__DEF_FUN2 (double, hypot)
__HIP_OVERLOAD2 (bool, isgreater)
__HIP_OVERLOAD2 (bool, isgreaterequal)
__HIP_OVERLOAD1 (bool, isinf)
__HIP_OVERLOAD2 (bool, isless)
__HIP_OVERLOAD2 (bool, islessequal)
__HIP_OVERLOAD2 (bool, islessgreater)
__HIP_OVERLOAD1 (bool, isnan)
__HIP_OVERLOAD2 (bool, isunordered)
__DEF_FUN1 (double, nearbyint)
__DEF_FUN2 (double, nextafter)
__DEF_FUN2 (double, pow)
__DEF_FUN2 (double, remainder)
__DEF_FUN1 (double, rint)
__DEF_FUN1 (double, round)
__DEF_FUN1 (double, trunc)
template<class T >
__DEVICE__ T min (T __arg1, T __arg2)
template<class T >
__DEVICE__ T max (T __arg1, T __arg2)
__DEVICE__ int min (int __arg1, int __arg2)
__DEVICE__ int max (int __arg1, int __arg2)
__DEVICE__ float max (float __x, float __y)
Returns y if x < y, otherwise it returns x.
__DEVICE__ double max (double __x, double __y)
__DEVICE__ float min (float __x, float __y)
Returns y if y < x, otherwise it returns x.
__DEVICE__ double min (double __x, double __y)
Macro Definition Documentation
__DEF_FLOAT_FUN2I
#define __DEF_FLOAT_FUN2I (__func)
Value:
  __DEVICE__                                                                   \
  inline float __func(float __x, int __y) { return __func##f(__x, __y); }
Definition at line 1133 of file __clang_hip_math.h.
__DEF_FUN1
#define __DEF_FUN1 (__retty, __func)
Value:
  __DEVICE__                                                                   \
  inline float __func(float __x) { return __func##f(__x); }                    \
  __HIP_OVERLOAD1(__retty, __func)
Definition at line 1054 of file __clang_hip_math.h.
__DEF_FUN2
#define __DEF_FUN2 (__retty, __func)
Value:
  __DEVICE__                                                                   \
  inline float __func(float __x, float __y) { return __func##f(__x, __y); }    \
  __HIP_OVERLOAD2(__retty, __func)
Definition at line 1066 of file __clang_hip_math.h.
__DEF_FUNI
#define __DEF_FUNI (__retty, __func)
Value:
  __DEVICE__                                                                   \
  inline __retty __func(float __x) { return __func##f(__x); }                  \
  __HIP_OVERLOAD1(__retty, __func)
Definition at line 1060 of file __clang_hip_math.h.
__DEVICE__
#define __DEVICE__ static __device__
Definition at line 22 of file __clang_hip_math.h.
__HIP_OVERLOAD1
#define __HIP_OVERLOAD1 (__retty, __fn)
Value:
  template <typename __T>                                                      \
  __DEVICE__ typename __hip_enable_if<std::numeric_limits<__T>::is_integer,    \
                                      __retty>::type                           \
  __fn(__T __x) {                                                              \
    return ::__fn((double)__x);                                                \
  }
Definition at line 1032 of file __clang_hip_math.h.
__HIP_OVERLOAD2
#define __HIP_OVERLOAD2 (__retty, __fn)
Value:
  template <typename __T1, typename __T2>                                      \
  __DEVICE__                                                                   \
      typename __hip_enable_if<std::numeric_limits<__T1>::is_specialized &&    \
                                   std::numeric_limits<__T2>::is_specialized,  \
                               __retty>::type                                  \
      __fn(__T1 __x, __T2 __y) {                                               \
    return __fn((double)__x, (double)__y);                                     \
  }
Definition at line 1043 of file __clang_hip_math.h.
__RETURN_TYPE
#define __RETURN_TYPE bool
Definition at line 23 of file __clang_hip_math.h.
Function Documentation
__cosf()
__DEVICE__ float __cosf (float __x) inline
Definition at line 412 of file __clang_hip_math.h.
References __ocml_native_cos_f32(), and __x.
__dadd_rn()
__DEVICE__ double __dadd_rn (double __x, double __y) inline
Definition at line 882 of file __clang_hip_math.h.
References __x, and __y.
__ddiv_rn()
__DEVICE__ double __ddiv_rn (double __x, double __y) inline
Definition at line 898 of file __clang_hip_math.h.
References __x, and __y.
__DEF_FUN1() [1/4]
__DEF_FUN1 (double , nearbyint)
__DEF_FUN1() [2/4]
__DEF_FUN1 (double , rint)
__DEF_FUN1() [3/4]
__DEF_FUN1 (double , round)
__DEF_FUN1() [4/4]
__DEF_FUN1 (double , trunc)
__DEF_FUN2() [1/10]
__DEF_FUN2 (double , atan2)
__DEF_FUN2() [2/10]
__DEF_FUN2 (double , copysign)
__DEF_FUN2() [3/10]
__DEF_FUN2 (double , fdim)
__DEF_FUN2() [4/10]
__DEF_FUN2 (double , fmax)
__DEF_FUN2() [5/10]
__DEF_FUN2 (double , fmin)
__DEF_FUN2() [6/10]
__DEF_FUN2 (double , fmod)
__DEF_FUN2() [7/10]
__DEF_FUN2 (double , hypot)
__DEF_FUN2() [8/10]
__DEF_FUN2 (double , nextafter)
__DEF_FUN2() [9/10]
__DEF_FUN2 (double , pow)
__DEF_FUN2() [10/10]
__DEF_FUN2 (double , remainder)
__dmul_rn()
__DEVICE__ double __dmul_rn (double __x, double __y) inline
Definition at line 914 of file __clang_hip_math.h.
References __x, and __y.
__drcp_rn()
__DEVICE__ double __drcp_rn (double __x) inline
Definition at line 928 of file __clang_hip_math.h.
References __x.
__dsqrt_rn()
__DEVICE__ double __dsqrt_rn (double __x) inline
Definition at line 938 of file __clang_hip_math.h.
References __x.
__dsub_rn()
__DEVICE__ double __dsub_rn (double __x, double __y) inline
Definition at line 950 of file __clang_hip_math.h.
References __x, and __y.
__exp10f()
__DEVICE__ float __exp10f (float __x) inline
Definition at line 414 of file __clang_hip_math.h.
References __x.
__expf()
__DEVICE__ float __expf (float __x) inline
Definition at line 416 of file __clang_hip_math.h.
References __x.
__fadd_rn()
__DEVICE__ float __fadd_rn (float __x, float __y) inline
Definition at line 424 of file __clang_hip_math.h.
References __x, and __y.
__fdiv_rn()
__DEVICE__ float __fdiv_rn (float __x, float __y) inline
Definition at line 440 of file __clang_hip_math.h.
References __x, and __y.
__fdividef()
__DEVICE__ float __fdividef (float __x, float __y) inline
Definition at line 452 of file __clang_hip_math.h.
References __x, and __y.
__fma_rn()
__DEVICE__ double __fma_rn (double __x, double __y, double __z) inline
Definition at line 966 of file __clang_hip_math.h.
References __x, and __y.
__fmaf_rn()
__DEVICE__ float __fmaf_rn (float __x, float __y, float __z) inline
Definition at line 460 of file __clang_hip_math.h.
References __x, and __y.
__fmul_rn()
__DEVICE__ float __fmul_rn (float __x, float __y) inline
Definition at line 478 of file __clang_hip_math.h.
References __x, and __y.
__frcp_rn()
__DEVICE__ float __frcp_rn (float __x) inline
Definition at line 492 of file __clang_hip_math.h.
References __x.
__frsqrt_rn()
__DEVICE__ float __frsqrt_rn (float __x) inline
Definition at line 500 of file __clang_hip_math.h.
References __x.
__fsqrt_rn()
__DEVICE__ float __fsqrt_rn (float __x) inline
Definition at line 506 of file __clang_hip_math.h.
References __x.
__fsub_rn()
__DEVICE__ float __fsub_rn (float __x, float __y) inline
Definition at line 518 of file __clang_hip_math.h.
References __x, and __y.
__HIP_OVERLOAD1() [1/2]
__HIP_OVERLOAD1 (bool , isinf)
__HIP_OVERLOAD1() [2/2]
__HIP_OVERLOAD1 (bool , isnan)
__HIP_OVERLOAD2() [1/6]
__HIP_OVERLOAD2 (bool , isgreater)
__HIP_OVERLOAD2() [2/6]
__HIP_OVERLOAD2 (bool , isgreaterequal)
__HIP_OVERLOAD2() [3/6]
__HIP_OVERLOAD2 (bool , isless)
__HIP_OVERLOAD2() [4/6]
__HIP_OVERLOAD2 (bool , islessequal)
__HIP_OVERLOAD2() [5/6]
__HIP_OVERLOAD2 (bool , islessgreater)
__HIP_OVERLOAD2() [6/6]
__HIP_OVERLOAD2 (bool , isunordered)
__log10f()
__DEVICE__ float __log10f (float __x) inline
Definition at line 530 of file __clang_hip_math.h.
References __x.
__log2f()
__DEVICE__ float __log2f (float __x) inline
Definition at line 532 of file __clang_hip_math.h.
References __x.
__logf()
__DEVICE__ float __logf (float __x) inline
Definition at line 534 of file __clang_hip_math.h.
References __x.
__make_mantissa()
__DEVICE__ uint64_t __make_mantissa (const char * __tagp) inline
Definition at line 81 of file __clang_hip_math.h.
References __make_mantissa_base10(), __make_mantissa_base16(), and __make_mantissa_base8().
Referenced by nan(), and nanf().
__make_mantissa_base10()
__DEVICE__ uint64_t __make_mantissa_base10 (const char * __tagp) inline
Definition at line 43 of file __clang_hip_math.h.
Referenced by __make_mantissa().
__make_mantissa_base16()
__DEVICE__ uint64_t __make_mantissa_base16 (const char * __tagp) inline
Definition at line 60 of file __clang_hip_math.h.
Referenced by __make_mantissa().
__make_mantissa_base8()
__DEVICE__ uint64_t __make_mantissa_base8 (const char * __tagp) inline
Definition at line 26 of file __clang_hip_math.h.
Referenced by __make_mantissa().
__powf()
__DEVICE__ float __powf (float __x, float __y) inline
Definition at line 536 of file __clang_hip_math.h.
References __x, and __y.
__saturatef()
__DEVICE__ float __saturatef (float __x) inline
Definition at line 538 of file __clang_hip_math.h.
References __x.
__sincosf()
__DEVICE__ void __sincosf (float __x, float * __sinptr, float * __cosptr) inline
Definition at line 542 of file __clang_hip_math.h.
References __ocml_native_cos_f32(), __ocml_native_sin_f32(), and __x.
__sinf()
__DEVICE__ float __sinf (float __x) inline
Definition at line 547 of file __clang_hip_math.h.
References __ocml_native_sin_f32(), and __x.
__tanf()
__DEVICE__ float __tanf (float __x) inline
Definition at line 549 of file __clang_hip_math.h.
References __ocml_tan_f32(), and __x.
abs() [1/3]
__DEVICE__ double abs (double __x) inline
Definition at line 555 of file __clang_hip_math.h.
References __x, and fabs().
abs() [2/3]
__DEVICE__ float abs (float __x) inline
Definition at line 99 of file __clang_hip_math.h.
References __x, and fabsf().
abs() [3/3]
__DEVICE__ int abs (int __x) inline
Definition at line 984 of file __clang_hip_math.h.
References __a, __nv_abs(), __x, CHAR_BIT, and int.
acos()
__DEVICE__ double acos (double __x) inline
Definition at line 557 of file __clang_hip_math.h.
References __a, __nv_acos(), and __x.
acosf()
__DEVICE__ float acosf (float __x) inline
Definition at line 101 of file __clang_hip_math.h.
References __x.
acosh()
__DEVICE__ double acosh (double __x) inline
Definition at line 559 of file __clang_hip_math.h.
References __a, __nv_acosh(), and __x.
acoshf()
__DEVICE__ float acoshf (float __x) inline
Definition at line 103 of file __clang_hip_math.h.
References __x.
asin()
__DEVICE__ double asin (double __x) inline
Definition at line 561 of file __clang_hip_math.h.
References __a, __nv_asin(), and __x.
asinf()
__DEVICE__ float asinf (float __x) inline
Definition at line 105 of file __clang_hip_math.h.
References __x.
asinh()
__DEVICE__ double asinh (double __x) inline
Definition at line 563 of file __clang_hip_math.h.
References __a, __nv_asinh(), and __x.
asinhf()
__DEVICE__ float asinhf (float __x) inline
Definition at line 107 of file __clang_hip_math.h.
References __x.
atan()
__DEVICE__ double atan (double __x) inline
Definition at line 565 of file __clang_hip_math.h.
References __a, __nv_atan(), and __x.
atan2()
__DEVICE__ double atan2 (double __x, double __y) inline
Definition at line 567 of file __clang_hip_math.h.
References __a, __b, __nv_atan2(), __x, and __y.
atan2f()
__DEVICE__ float atan2f (float __x, float __y) inline
Definition at line 109 of file __clang_hip_math.h.
References __x, and __y.
atanf()
__DEVICE__ float atanf (float __x) inline
Definition at line 111 of file __clang_hip_math.h.
References __x.
atanh()
__DEVICE__ double atanh (double __x) inline
Definition at line 571 of file __clang_hip_math.h.
References __a, __nv_atanh(), and __x.
atanhf()
__DEVICE__ float atanhf (float __x) inline
Definition at line 113 of file __clang_hip_math.h.
References __x.
cbrt()
__DEVICE__ double cbrt (double __x) inline
Definition at line 573 of file __clang_hip_math.h.
References __a, __nv_cbrt(), and __x.
cbrtf()
__DEVICE__ float cbrtf (float __x) inline
Definition at line 115 of file __clang_hip_math.h.
References __x.
ceil()
__DEVICE__ double ceil (double __x) inline
Definition at line 575 of file __clang_hip_math.h.
References __a, __nv_ceil(), and __x.
ceilf()
__DEVICE__ float ceilf (float __x) inline
Definition at line 117 of file __clang_hip_math.h.
References __x.
copysign()
__DEVICE__ double copysign (double __x, double __y) inline
Definition at line 577 of file __clang_hip_math.h.
References __a, __b, __nv_copysign(), __x, and __y.
copysignf()
__DEVICE__ float copysignf (float __x, float __y) inline
Definition at line 119 of file __clang_hip_math.h.
References __x, and __y.
cos()
__DEVICE__ double cos (double __x) inline
Definition at line 581 of file __clang_hip_math.h.
References __a, __nv_cos(), __ocml_cos_f64(), and __x.
cosf()
__DEVICE__ float cosf (float __x) inline
Definition at line 123 of file __clang_hip_math.h.
References __ocml_cos_f32(), and __x.
cosh()
__DEVICE__ double cosh (double __x) inline
Definition at line 583 of file __clang_hip_math.h.
References __a, __nv_cosh(), and __x.
coshf()
__DEVICE__ float coshf (float __x) inline
Definition at line 125 of file __clang_hip_math.h.
References __x.
cospi()
__DEVICE__ double cospi (double __x) inline
Definition at line 585 of file __clang_hip_math.h.
References __ocml_cospi_f64(), and __x.
cospif()
__DEVICE__ float cospif (float __x) inline
Definition at line 127 of file __clang_hip_math.h.
References __ocml_cospi_f32(), and __x.
cyl_bessel_i0()
__DEVICE__ double cyl_bessel_i0 (double __x) inline
Definition at line 587 of file __clang_hip_math.h.
References __ocml_i0_f64(), and __x.
cyl_bessel_i0f()
__DEVICE__ float cyl_bessel_i0f (float __x) inline
Definition at line 129 of file __clang_hip_math.h.
References __ocml_i0_f32(), and __x.
cyl_bessel_i1()
__DEVICE__ double cyl_bessel_i1 (double __x) inline
Definition at line 589 of file __clang_hip_math.h.
References __ocml_i1_f64(), and __x.
cyl_bessel_i1f()
__DEVICE__ float cyl_bessel_i1f (float __x) inline
Definition at line 131 of file __clang_hip_math.h.
References __ocml_i1_f32(), and __x.
erf()
__DEVICE__ double erf (double __x) inline
Definition at line 591 of file __clang_hip_math.h.
References __a, __nv_erf(), and __x.
erfc()
__DEVICE__ double erfc (double __x) inline
Definition at line 593 of file __clang_hip_math.h.
References __a, __nv_erfc(), and __x.
erfcf()
__DEVICE__ float erfcf (float __x) inline
Definition at line 133 of file __clang_hip_math.h.
References __x.
erfcinv()
__DEVICE__ double erfcinv (double __x) inline
Definition at line 595 of file __clang_hip_math.h.
References __x.
erfcinvf()
__DEVICE__ float erfcinvf (float __x) inline
Definition at line 135 of file __clang_hip_math.h.
References __x.
erfcx()
__DEVICE__ double erfcx (double __x) inline
Definition at line 597 of file __clang_hip_math.h.
References __x.
erfcxf()
__DEVICE__ float erfcxf (float __x) inline
Definition at line 137 of file __clang_hip_math.h.
References __x.
erff()
__DEVICE__ float erff (float __x) inline
Definition at line 139 of file __clang_hip_math.h.
References __x.
erfinv()
__DEVICE__ double erfinv (double __x) inline
Definition at line 599 of file __clang_hip_math.h.
References __x.
erfinvf()
__DEVICE__ float erfinvf (float __x) inline
Definition at line 141 of file __clang_hip_math.h.
References __x.
exp()
__DEVICE__ double exp (double __x) inline
Definition at line 601 of file __clang_hip_math.h.
References __a, __nv_exp(), and __x.
exp10()
__DEVICE__ double exp10 (double __x) inline
Definition at line 603 of file __clang_hip_math.h.
References __x.
exp10f()
__DEVICE__ float exp10f (float __x) inline
Definition at line 143 of file __clang_hip_math.h.
References __x.
exp2()
__DEVICE__ double exp2 (double __x) inline
Definition at line 605 of file __clang_hip_math.h.
References __a, __nv_exp2(), and __x.
exp2f()
__DEVICE__ float exp2f (float __x) inline
Definition at line 145 of file __clang_hip_math.h.
References __x.
expf()
__DEVICE__ float expf (float __x) inline
Definition at line 147 of file __clang_hip_math.h.
References __x.
expm1()
__DEVICE__ double expm1 (double __x) inline
Definition at line 607 of file __clang_hip_math.h.
References __a, __nv_expm1(), and __x.
expm1f()
__DEVICE__ float expm1f (float __x) inline
Definition at line 149 of file __clang_hip_math.h.
References __x.
fabs()
__DEVICE__ double fabs (double __x) inline
Definition at line 609 of file __clang_hip_math.h.
References __a, __nv_fabs(), and __x.
fabsf()
__DEVICE__ float fabsf (float __x) inline
Definition at line 151 of file __clang_hip_math.h.
References __x.
fdim()
__DEVICE__ double fdim (double __x, double __y) inline
Definition at line 611 of file __clang_hip_math.h.
References __a, __b, __nv_fdim(), __x, and __y.
fdimf()
__DEVICE__ float fdimf (float __x, float __y) inline
Definition at line 153 of file __clang_hip_math.h.
References __x, and __y.
fdividef()
__DEVICE__ float fdividef (float __x, float __y) inline
Definition at line 155 of file __clang_hip_math.h.
References __x, and __y.
floor()
__DEVICE__ double floor (double __x) inline
Definition at line 613 of file __clang_hip_math.h.
References __nv_floor(), and __x.
floorf()
__DEVICE__ float floorf (float __x) inline
Definition at line 157 of file __clang_hip_math.h.
References __x.
fma() [1/3]
__DEVICE__ _Float16 fma (_Float16 __x, _Float16 __y, _Float16 __z) inline
Definition at line 1008 of file __clang_hip_math.h.
References __x, and __y.
fma() [2/3]
__DEVICE__ double fma (double __x, double __y, double __z) inline
Definition at line 615 of file __clang_hip_math.h.
References __a, __b, __c, __nv_fma(), __x, and __y.
fma() [3/3]
__DEVICE__ float fma (float a, float b, float c) inline
Returns the correctly rounded floating-point representation of the sum of c with the infinitely precise product of a and b.
Rounding of intermediate products shall not occur. Edge case behavior is per the IEEE 754-2008 standard.
Definition at line 1013 of file __clang_hip_math.h.
References __x, __y, and fmaf().
fmaf()
__DEVICE__ float fmaf (float __x, float __y, float __z) inline
Definition at line 159 of file __clang_hip_math.h.
References __x, and __y.
Referenced by fma().
fmax()
__DEVICE__ double fmax (double __x, double __y) inline
Definition at line 619 of file __clang_hip_math.h.
References __a, __b, __nv_fmax(), __x, and __y.
Referenced by max().
fmaxf()
__DEVICE__ float fmaxf (float __x, float __y) inline
Definition at line 163 of file __clang_hip_math.h.
References __x, and __y.
Referenced by max().
fmin()
__DEVICE__ double fmin (double __x, double __y) inline
Definition at line 621 of file __clang_hip_math.h.
References __a, __b, __nv_fmin(), __x, and __y.
Referenced by min().
fminf()
__DEVICE__ float fminf (float __x, float __y) inline
Definition at line 165 of file __clang_hip_math.h.
References __x, and __y.
Referenced by min().
fmod()
__DEVICE__ double fmod (double __x, double __y) inline
Definition at line 623 of file __clang_hip_math.h.
References __a, __b, __nv_fmod(), __x, and __y.
fmodf()
__DEVICE__ float fmodf (float __x, float __y) inline
Definition at line 167 of file __clang_hip_math.h.
References __x, and __y.
frexp()
__DEVICE__ double frexp (double __x, int * __nptr) inline
Definition at line 625 of file __clang_hip_math.h.
References __a, __b, __nv_frexp(), __ocml_frexp_f64(), and __x.
frexpf()
__DEVICE__ float frexpf (float __x, int * __nptr) inline
Definition at line 169 of file __clang_hip_math.h.
References __ocml_frexp_f32(), and __x.
hypot()
__DEVICE__ double hypot (double __x, double __y) inline
Definition at line 634 of file __clang_hip_math.h.
References __a, __b, __nv_hypot(), __x, and __y.
hypotf()
__DEVICE__ float hypotf (float __x, float __y) inline
Definition at line 178 of file __clang_hip_math.h.
References __x, and __y.
ilogb()
__DEVICE__ int ilogb (double __x) inline
Definition at line 638 of file __clang_hip_math.h.
References __a, __nv_ilogb(), and __x.
ilogbf()
__DEVICE__ int ilogbf (float __x) inline
Definition at line 180 of file __clang_hip_math.h.
References __x.
isfinite() [1/2]
__DEVICE__ __RETURN_TYPE isfinite (double __x) inline
Definition at line 640 of file __clang_hip_math.h.
References __isfinited(), and __x.
isfinite() [2/2]
__DEVICE__ __RETURN_TYPE isfinite (float __x) inline
Test for finite value.
Definition at line 182 of file __clang_hip_math.h.
References __finitef(), and __x.
isinf() [1/2]
__DEVICE__ __RETURN_TYPE isinf (double __x) inline
Definition at line 642 of file __clang_hip_math.h.
References __isinf(), and __x.
isinf() [2/2]
__DEVICE__ __RETURN_TYPE isinf (float __x) inline
Test for infinity value (+ve or -ve) .
Definition at line 184 of file __clang_hip_math.h.
References __isinff(), and __x.
isnan() [1/2]
__DEVICE__ __RETURN_TYPE isnan (double __x) inline
Definition at line 644 of file __clang_hip_math.h.
References __isnan(), and __x.
isnan() [2/2]
__DEVICE__ __RETURN_TYPE isnan (float __x) inline
Test for a NaN.
Definition at line 186 of file __clang_hip_math.h.
References __isnanf(), and __x.
j0()
__DEVICE__ double j0 (double __x) inline
Definition at line 646 of file __clang_hip_math.h.
References __ocml_j0_f64(), and __x.
j0f()
__DEVICE__ float j0f (float __x) inline
Definition at line 188 of file __clang_hip_math.h.
References __ocml_j0_f32(), and __x.
Referenced by jn(), jnf(), and yn().
j1()
__DEVICE__ double j1 (double __x) inline
Definition at line 648 of file __clang_hip_math.h.
References __ocml_j1_f64(), and __x.
j1f()
__DEVICE__ float j1f (float __x) inline
Definition at line 190 of file __clang_hip_math.h.
References __ocml_j1_f32(), and __x.
Referenced by jn(), jnf(), and yn().
jn()
__DEVICE__ double jn (int __n, double __x) inline
Definition at line 650 of file __clang_hip_math.h.
References __x, j0f(), and j1f().
jnf()
__DEVICE__ float jnf (int __n, float __x) inline
Definition at line 192 of file __clang_hip_math.h.
References __x, j0f(), and j1f().
labs()
__DEVICE__ long labs (long __x) inline
Definition at line 989 of file __clang_hip_math.h.
References __a, __nv_abs(), __x, and CHAR_BIT.
ldexp()
__DEVICE__ double ldexp (double __x, int __e) inline
Definition at line 672 of file __clang_hip_math.h.
References __a, __b, __nv_ldexp(), and __x.
ldexpf()
__DEVICE__ float ldexpf (float __x, int __e) inline
Definition at line 213 of file __clang_hip_math.h.
References __x.
lgamma()
__DEVICE__ double lgamma (double __x) inline
Definition at line 674 of file __clang_hip_math.h.
References __a, __nv_lgamma(), __ocml_lgamma_f64(), and __x.
lgammaf()
__DEVICE__ float lgammaf (float __x) inline
Definition at line 215 of file __clang_hip_math.h.
References __ocml_lgamma_f32(), and __x.
llabs()
__DEVICE__ long long llabs (long long __x) inline
Definition at line 994 of file __clang_hip_math.h.
References __a, __nv_llabs(), __x, and CHAR_BIT.
llrint()
__DEVICE__ long long int llrint (double __x) inline
Definition at line 676 of file __clang_hip_math.h.
References __a, __nv_llrint(), and __x.
llrintf()
__DEVICE__ long long int llrintf (float __x) inline
Definition at line 217 of file __clang_hip_math.h.
References __x.
llround()
__DEVICE__ long long int llround (double __x) inline
Definition at line 678 of file __clang_hip_math.h.
References __x.
llroundf()
__DEVICE__ long long int llroundf (float __x) inline
Definition at line 219 of file __clang_hip_math.h.
References __x.
log()
__DEVICE__ double log (double __x) inline
Definition at line 680 of file __clang_hip_math.h.
References __a, __nv_log(), and __x.
log10()
__DEVICE__ double log10 (double __x) inline
Definition at line 682 of file __clang_hip_math.h.
References __a, __nv_log10(), and __x.
log10f()
__DEVICE__ float log10f (float __x) inline
Definition at line 221 of file __clang_hip_math.h.
References __x.
log1p()
__DEVICE__ double log1p (double __x) inline
Definition at line 684 of file __clang_hip_math.h.
References __a, __nv_log1p(), and __x.
log1pf()
__DEVICE__ float log1pf (float __x) inline
Definition at line 223 of file __clang_hip_math.h.
References __x.
log2()
__DEVICE__ double log2 (double __x) inline
Definition at line 686 of file __clang_hip_math.h.
References __a, __nv_log2(), and __x.
log2f()
__DEVICE__ float log2f (float __x) inline
Definition at line 225 of file __clang_hip_math.h.
References __x.
logb()
__DEVICE__ double logb (double __x) inline
Definition at line 688 of file __clang_hip_math.h.
References __a, __nv_logb(), and __x.
logbf()
__DEVICE__ float logbf (float __x) inline
Definition at line 227 of file __clang_hip_math.h.
References __x.
logf()
__DEVICE__ float logf (float __x) inline
Definition at line 229 of file __clang_hip_math.h.
References __x.
lrint()
__DEVICE__ long int lrint (double __x) inline
Definition at line 690 of file __clang_hip_math.h.
References __a, __x, and rint().
lrintf()
__DEVICE__ long int lrintf (float __x) inline
Definition at line 231 of file __clang_hip_math.h.
References __x.
lround()
__DEVICE__ long int lround (double __x) inline
Definition at line 692 of file __clang_hip_math.h.
References __a, __x, and round().
lroundf()
__DEVICE__ long int lroundf (float __x) inline
Definition at line 233 of file __clang_hip_math.h.
References __x.
max() [1/4]
__DEVICE__ double max (double __x, double __y) inline
Definition at line 1157 of file __clang_hip_math.h.
References __x, __y, and fmax().
max() [2/4]
__DEVICE__ float max (float x, float y) inline
Returns y if x < y, otherwise it returns x.
If x and y are infinite or NaN, the return values are undefined.
Definition at line 1154 of file __clang_hip_math.h.
References __x, __y, and fmaxf().
max() [3/4]
__DEVICE__ int max (int __arg1, int __arg2) inline
Definition at line 1149 of file __clang_hip_math.h.
References __a, __b, and __nv_max().
max() [4/4]
template<class T > __DEVICE__ T max (T __arg1, T __arg2) inline
Definition at line 1142 of file __clang_hip_math.h.
min() [1/4]
__DEVICE__ double min (double __x, double __y) inline
Definition at line 1163 of file __clang_hip_math.h.
References __x, __y, and fmin().
min() [2/4]
__DEVICE__ float min (float x, float y) inline
Returns y if y < x, otherwise it returns x.
If x and y are infinite or NaN, the return values are undefined.
Definition at line 1160 of file __clang_hip_math.h.
References __x, __y, and fminf().
min() [3/4]
__DEVICE__ int min (int __arg1, int __arg2) inline
Definition at line 1146 of file __clang_hip_math.h.
References __a, __b, and __nv_min().
min() [4/4]
template<class T > __DEVICE__ T min (T __arg1, T __arg2) inline
Definition at line 1138 of file __clang_hip_math.h.
modf()
__DEVICE__ double modf (double __x, double * __iptr) inline
Definition at line 694 of file __clang_hip_math.h.
References __a, __b, __nv_modf(), __ocml_modf_f64(), and __x.
modff()
__DEVICE__ float modff (float __x, float * __iptr) inline
Definition at line 235 of file __clang_hip_math.h.
References __ocml_modf_f32(), and __x.
nan()
__DEVICE__ double nan (const char * __tagp) inline
Definition at line 703 of file __clang_hip_math.h.
References __make_mantissa(), sign(), and static_assert.
Referenced by fadd_d(), fcmp_d(), fcmp_s(), fconv_d2f(), and fconv_f2d().
nanf()
__DEVICE__ float nanf (const char * __tagp) inline
Definition at line 244 of file __clang_hip_math.h.
References __make_mantissa(), sign(), and static_assert.
nearbyint()
__DEVICE__ double nearbyint (double __x) inline
Definition at line 730 of file __clang_hip_math.h.
References __a, __nv_nearbyint(), and __x.
nearbyintf()
__DEVICE__ float nearbyintf (float __x) inline
Definition at line 265 of file __clang_hip_math.h.
References __x.
nextafter()
__DEVICE__ double nextafter (double __x, double __y) inline
Definition at line 732 of file __clang_hip_math.h.
References __a, __b, __nv_nextafter(), __x, and __y.
nextafterf()
__DEVICE__ float nextafterf (float __x, float __y) inline
Definition at line 267 of file __clang_hip_math.h.
References __x, and __y.
norm()
__DEVICE__ double norm (int __dim, const double * __a) inline
Definition at line 737 of file __clang_hip_math.h.
References __a.
norm3d()
__DEVICE__ double norm3d (double __x, double __y, double __z) inline
Definition at line 748 of file __clang_hip_math.h.
References __x, and __y.
norm3df()
__DEVICE__ float norm3df (float __x, float __y, float __z) inline
Definition at line 271 of file __clang_hip_math.h.
References __x, and __y.
norm4d()
__DEVICE__ double norm4d (double __x, double __y, double __z, double __w) inline
Definition at line 752 of file __clang_hip_math.h.
References __x, and __y.
norm4df()
__DEVICE__ float norm4df (float __x, float __y, float __z, float __w) inline
Definition at line 275 of file __clang_hip_math.h.
References __x, and __y.
normcdf()
__DEVICE__ double normcdf (double __x) inline
Definition at line 756 of file __clang_hip_math.h.
References __x.
normcdff()
__DEVICE__ float normcdff (float __x) inline
Definition at line 279 of file __clang_hip_math.h.
References __x.
normcdfinv()
__DEVICE__ double normcdfinv (double __x) inline
Definition at line 758 of file __clang_hip_math.h.
References __x.
normcdfinvf()
__DEVICE__ float normcdfinvf (float __x) inline
Definition at line 281 of file __clang_hip_math.h.
References __x.
normf()
__DEVICE__ float normf (int __dim, const float * __a) inline
Definition at line 284 of file __clang_hip_math.h.
References __a.
pow()
__DEVICE__ double pow (double __x, double __y) inline
Definition at line 760 of file __clang_hip_math.h.
References __a, __b, __nv_pow(), __x, and __y.
powf()
__DEVICE__ float powf (float __x, float __y) inline
Definition at line 295 of file __clang_hip_math.h.
References __x, and __y.
rcbrt()
__DEVICE__ double rcbrt (double __x) inline
Definition at line 762 of file __clang_hip_math.h.
References __x.
rcbrtf()
__DEVICE__ float rcbrtf (float __x) inline
Definition at line 297 of file __clang_hip_math.h.
References __x.
remainder()
__DEVICE__ double remainder (double __x, double __y) inline
Definition at line 764 of file __clang_hip_math.h.
References __a, __b, __nv_remainder(), __x, and __y.
remainderf()
__DEVICE__ float remainderf (float __x, float __y) inline
Definition at line 299 of file __clang_hip_math.h.
References __x, and __y.
remquo()
__DEVICE__ double remquo (double __x, double __y, int * __quo) inline
Definition at line 768 of file __clang_hip_math.h.
References __a, __b, __c, __nv_remquo(), __ocml_remquo_f64(), __x, and __y.
remquof()
__DEVICE__ float remquof (float __x, float __y, int * __quo) inline
Definition at line 303 of file __clang_hip_math.h.
References __ocml_remquo_f32(), __x, and __y.
rhypot()
__DEVICE__ double rhypot (double __x, double __y) inline
Definition at line 777 of file __clang_hip_math.h.
References __x, and __y.
rhypotf()
__DEVICE__ float rhypotf (float __x, float __y) inline
Definition at line 312 of file __clang_hip_math.h.
References __x, and __y.
rint()
__DEVICE__ double rint (double __x) inline
Definition at line 781 of file __clang_hip_math.h.
References __a, __nv_rint(), and __x.
rintf()
__DEVICE__ float rintf (float __x) inline
Definition at line 316 of file __clang_hip_math.h.
References __x.
rnorm()
__DEVICE__ double rnorm (int __dim, const double * __a) inline
Definition at line 784 of file __clang_hip_math.h.
References __a.
rnorm3d()
__DEVICE__ double rnorm3d (double __x, double __y, double __z) inline
Definition at line 795 of file __clang_hip_math.h.
References __x, and __y.
rnorm3df()
__DEVICE__ float rnorm3df (float __x, float __y, float __z) inline
Definition at line 318 of file __clang_hip_math.h.
References __x, and __y.
rnorm4d()
__DEVICE__ double rnorm4d (double __x, double __y, double __z, double __w) inline
Definition at line 799 of file __clang_hip_math.h.
References __x, and __y.
rnorm4df()
__DEVICE__ float rnorm4df (float __x, float __y, float __z, float __w) inline
Definition at line 323 of file __clang_hip_math.h.
References __x, and __y.
rnormf()
__DEVICE__ float rnormf (int __dim, const float * __a) inline
Definition at line 328 of file __clang_hip_math.h.
References __a.
round()
__DEVICE__ double round (double __x) inline
Definition at line 803 of file __clang_hip_math.h.
References __a, __nv_round(), and __x.
roundf()
__DEVICE__ float roundf (float __x) inline
Definition at line 339 of file __clang_hip_math.h.
References __x.
rsqrt()
__DEVICE__ double rsqrt (double __x) inline
Definition at line 805 of file __clang_hip_math.h.
References __x.
rsqrtf()
__DEVICE__ float rsqrtf (float __x) inline
Definition at line 341 of file __clang_hip_math.h.
References __x.
scalbln()
__DEVICE__ double scalbln (double __x, long int __n) inline
Definition at line 807 of file __clang_hip_math.h.
References __x, and INT_MAX.
scalblnf()
__DEVICE__ float scalblnf (float __x, long int __n) inline
Definition at line 343 of file __clang_hip_math.h.
References __x, and INT_MAX.
scalbn()
__DEVICE__ double scalbn (double __x, int __n) inline
Definition at line 812 of file __clang_hip_math.h.
References __a, __b, __nv_scalbn(), and __x.
scalbnf()
__DEVICE__ float scalbnf (float __x, int __n) inline
Definition at line 348 of file __clang_hip_math.h.
References __x.
signbit() [1/2]
__DEVICE__ __RETURN_TYPE signbit (double __x) inline
Definition at line 816 of file __clang_hip_math.h.
References __signbitd(), and __x.
signbit() [2/2]
__DEVICE__ __RETURN_TYPE signbit (float) inline
Test for sign bit.
The scalar version of the function returns a 1 if the sign bit in the float is set else returns 0. The vector version of the function returns the following for each component in floatn: a -1 if the sign bit in the float is set else returns 0.
Definition at line 350 of file __clang_hip_math.h.
References __signbitf(), and __x.
sin()
__DEVICE__ double sin (double __x) inline
Definition at line 818 of file __clang_hip_math.h.
References __a, __nv_sin(), __ocml_sin_f64(), and __x.
sincos()
__DEVICE__ void sincos (double __x, double * __sinptr, double * __cosptr) inline
Definition at line 820 of file __clang_hip_math.h.
References __ocml_sincos_f64(), and __x.
sincosf()
__DEVICE__ void sincosf (float __x, float * __sinptr, float * __cosptr) inline
Definition at line 352 of file __clang_hip_math.h.
References __ocml_sincos_f32(), and __x.
sincospi()
__DEVICE__ void sincospi (double __x, double * __sinptr, double * __cosptr) inline
Definition at line 827 of file __clang_hip_math.h.
References __ocml_sincospi_f64(), and __x.
sincospif()
__DEVICE__ void sincospif (float __x, float * __sinptr, float * __cosptr) inline
Definition at line 360 of file __clang_hip_math.h.
References __ocml_sincospi_f32(), and __x.
sinf()
__DEVICE__ float sinf (float __x) inline
Definition at line 368 of file __clang_hip_math.h.
References __ocml_sin_f32(), and __x.
sinh()
__DEVICE__ double sinh (double __x) inline
Definition at line 834 of file __clang_hip_math.h.
References __a, __nv_sinh(), and __x.
sinhf()
__DEVICE__ float sinhf (float __x) inline
Definition at line 370 of file __clang_hip_math.h.
References __x.
sinpi()
__DEVICE__ double sinpi (double __x) inline
Definition at line 836 of file __clang_hip_math.h.
References __ocml_sinpi_f64(), and __x.
sinpif()
__DEVICE__ float sinpif (float __x) inline
Definition at line 372 of file __clang_hip_math.h.
References __ocml_sinpi_f32(), and __x.
sqrt()
__DEVICE__ double sqrt (double __x) inline
Definition at line 838 of file __clang_hip_math.h.
References __a, __nv_sqrt(), and __x.
sqrtf()
__DEVICE__ float sqrtf (float __x) inline
Definition at line 374 of file __clang_hip_math.h.
References __x.
tan()
__DEVICE__ double tan (double __x) inline
Definition at line 840 of file __clang_hip_math.h.
References __a, __nv_tan(), __ocml_tan_f64(), and __x.
tanf()
__DEVICE__ float tanf (float __x) inline
Definition at line 376 of file __clang_hip_math.h.
References __ocml_tan_f32(), and __x.
tanh()
__DEVICE__ double tanh (double __x) inline
Definition at line 842 of file __clang_hip_math.h.
References __a, __nv_tanh(), and __x.
tanhf()
__DEVICE__ float tanhf (float __x) inline
Definition at line 378 of file __clang_hip_math.h.
References __x.
tgamma()
__DEVICE__ double tgamma (double __x) inline
Definition at line 844 of file __clang_hip_math.h.
References __a, __nv_tgamma(), __ocml_tgamma_f64(), and __x.
tgammaf()
__DEVICE__ float tgammaf (float __x) inline
Definition at line 380 of file __clang_hip_math.h.
References __ocml_tgamma_f32(), and __x.
trunc()
__DEVICE__ double trunc (double __x) inline
Definition at line 846 of file __clang_hip_math.h.
References __a, __nv_trunc(), and __x.
truncf()
__DEVICE__ float truncf (float __x) inline
Definition at line 382 of file __clang_hip_math.h.
References __x.
y0()
__DEVICE__ double y0 (double __x) inline
Definition at line 848 of file __clang_hip_math.h.
References __ocml_y0_f64(), and __x.
y0f()
__DEVICE__ float y0f (float __x) inline
Definition at line 384 of file __clang_hip_math.h.
References __ocml_y0_f32(), and __x.
Referenced by ynf().
y1()
__DEVICE__ double y1 (double __x) inline
Definition at line 850 of file __clang_hip_math.h.
References __ocml_y1_f64(), and __x.
y1f()
__DEVICE__ float y1f (float __x) inline
Definition at line 386 of file __clang_hip_math.h.
References __ocml_y1_f32(), and __x.
Referenced by ynf().
yn()
__DEVICE__ double yn (int __n, double __x) inline
Definition at line 852 of file __clang_hip_math.h.
References __x, j0f(), and j1f().
ynf()
__DEVICE__ float ynf (int __n, float __x) inline
Definition at line 388 of file __clang_hip_math.h.
References __x, y0f(), and y1f().