ETISS 0.8.0: include/jit/clang_stdlib/__clang_cuda_libdevice_declares.h File Reference
__clang_cuda_libdevice_declares.h File Reference
Functions
__DEVICE__ int __nv_abs (int __a)
__DEVICE__ double __nv_acos (double __a)
__DEVICE__ float __nv_acosf (float __a)
__DEVICE__ double __nv_acosh (double __a)
__DEVICE__ float __nv_acoshf (float __a)
__DEVICE__ double __nv_asin (double __a)
__DEVICE__ float __nv_asinf (float __a)
__DEVICE__ double __nv_asinh (double __a)
__DEVICE__ float __nv_asinhf (float __a)
__DEVICE__ double __nv_atan2 (double __a, double __b)
__DEVICE__ float __nv_atan2f (float __a, float __b)
__DEVICE__ double __nv_atan (double __a)
__DEVICE__ float __nv_atanf (float __a)
__DEVICE__ double __nv_atanh (double __a)
__DEVICE__ float __nv_atanhf (float __a)
__DEVICE__ int __nv_brev (int __a)
__DEVICE__ long long __nv_brevll (long long __a)
__DEVICE__ int __nv_byte_perm (int __a, int __b, int __c)
__DEVICE__ double __nv_cbrt (double __a)
__DEVICE__ float __nv_cbrtf (float __a)
__DEVICE__ double __nv_ceil (double __a)
__DEVICE__ float __nv_ceilf (float __a)
__DEVICE__ int __nv_clz (int __a)
__DEVICE__ int __nv_clzll (long long __a)
__DEVICE__ double __nv_copysign (double __a, double __b)
__DEVICE__ float __nv_copysignf (float __a, float __b)
__DEVICE__ double __nv_cos (double __a)
__DEVICE__ float __nv_cosf (float __a)
__DEVICE__ double __nv_cosh (double __a)
__DEVICE__ float __nv_coshf (float __a)
__DEVICE__ double __nv_cospi (double __a)
__DEVICE__ float __nv_cospif (float __a)
__DEVICE__ double __nv_cyl_bessel_i0 (double __a)
__DEVICE__ float __nv_cyl_bessel_i0f (float __a)
__DEVICE__ double __nv_cyl_bessel_i1 (double __a)
__DEVICE__ float __nv_cyl_bessel_i1f (float __a)
__DEVICE__ double __nv_dadd_rd (double __a, double __b)
__DEVICE__ double __nv_dadd_rn (double __a, double __b)
__DEVICE__ double __nv_dadd_ru (double __a, double __b)
__DEVICE__ double __nv_dadd_rz (double __a, double __b)
__DEVICE__ double __nv_ddiv_rd (double __a, double __b)
__DEVICE__ double __nv_ddiv_rn (double __a, double __b)
__DEVICE__ double __nv_ddiv_ru (double __a, double __b)
__DEVICE__ double __nv_ddiv_rz (double __a, double __b)
__DEVICE__ double __nv_dmul_rd (double __a, double __b)
__DEVICE__ double __nv_dmul_rn (double __a, double __b)
__DEVICE__ double __nv_dmul_ru (double __a, double __b)
__DEVICE__ double __nv_dmul_rz (double __a, double __b)
__DEVICE__ float __nv_double2float_rd (double __a)
__DEVICE__ float __nv_double2float_rn (double __a)
__DEVICE__ float __nv_double2float_ru (double __a)
__DEVICE__ float __nv_double2float_rz (double __a)
__DEVICE__ int __nv_double2hiint (double __a)
__DEVICE__ int __nv_double2int_rd (double __a)
__DEVICE__ int __nv_double2int_rn (double __a)
__DEVICE__ int __nv_double2int_ru (double __a)
__DEVICE__ int __nv_double2int_rz (double __a)
__DEVICE__ long long __nv_double2ll_rd (double __a)
__DEVICE__ long long __nv_double2ll_rn (double __a)
__DEVICE__ long long __nv_double2ll_ru (double __a)
__DEVICE__ long long __nv_double2ll_rz (double __a)
__DEVICE__ int __nv_double2loint (double __a)
__DEVICE__ unsigned int __nv_double2uint_rd (double __a)
__DEVICE__ unsigned int __nv_double2uint_rn (double __a)
__DEVICE__ unsigned int __nv_double2uint_ru (double __a)
__DEVICE__ unsigned int __nv_double2uint_rz (double __a)
__DEVICE__ unsigned long long __nv_double2ull_rd (double __a)
__DEVICE__ unsigned long long __nv_double2ull_rn (double __a)
__DEVICE__ unsigned long long __nv_double2ull_ru (double __a)
__DEVICE__ unsigned long long __nv_double2ull_rz (double __a)
__DEVICE__ unsigned long long __nv_double_as_longlong (double __a)
__DEVICE__ double __nv_drcp_rd (double __a)
__DEVICE__ double __nv_drcp_rn (double __a)
__DEVICE__ double __nv_drcp_ru (double __a)
__DEVICE__ double __nv_drcp_rz (double __a)
__DEVICE__ double __nv_dsqrt_rd (double __a)
__DEVICE__ double __nv_dsqrt_rn (double __a)
__DEVICE__ double __nv_dsqrt_ru (double __a)
__DEVICE__ double __nv_dsqrt_rz (double __a)
__DEVICE__ double __nv_dsub_rd (double __a, double __b)
__DEVICE__ double __nv_dsub_rn (double __a, double __b)
__DEVICE__ double __nv_dsub_ru (double __a, double __b)
__DEVICE__ double __nv_dsub_rz (double __a, double __b)
__DEVICE__ double __nv_erfc (double __a)
__DEVICE__ float __nv_erfcf (float __a)
__DEVICE__ double __nv_erfcinv (double __a)
__DEVICE__ float __nv_erfcinvf (float __a)
__DEVICE__ double __nv_erfcx (double __a)
__DEVICE__ float __nv_erfcxf (float __a)
__DEVICE__ double __nv_erf (double __a)
__DEVICE__ float __nv_erff (float __a)
__DEVICE__ double __nv_erfinv (double __a)
__DEVICE__ float __nv_erfinvf (float __a)
__DEVICE__ double __nv_exp10 (double __a)
__DEVICE__ float __nv_exp10f (float __a)
__DEVICE__ double __nv_exp2 (double __a)
__DEVICE__ float __nv_exp2f (float __a)
__DEVICE__ double __nv_exp (double __a)
__DEVICE__ float __nv_expf (float __a)
__DEVICE__ double __nv_expm1 (double __a)
__DEVICE__ float __nv_expm1f (float __a)
__DEVICE__ double __nv_fabs (double __a)
__DEVICE__ float __nv_fabsf (float __a)
__DEVICE__ float __nv_fadd_rd (float __a, float __b)
__DEVICE__ float __nv_fadd_rn (float __a, float __b)
__DEVICE__ float __nv_fadd_ru (float __a, float __b)
__DEVICE__ float __nv_fadd_rz (float __a, float __b)
__DEVICE__ float __nv_fast_cosf (float __a)
__DEVICE__ float __nv_fast_exp10f (float __a)
__DEVICE__ float __nv_fast_expf (float __a)
__DEVICE__ float __nv_fast_fdividef (float __a, float __b)
__DEVICE__ float __nv_fast_log10f (float __a)
__DEVICE__ float __nv_fast_log2f (float __a)
__DEVICE__ float __nv_fast_logf (float __a)
__DEVICE__ float __nv_fast_powf (float __a, float __b)
__DEVICE__ void __nv_fast_sincosf (float __a, float *__s, float *__c)
__DEVICE__ float __nv_fast_sinf (float __a)
__DEVICE__ float __nv_fast_tanf (float __a)
__DEVICE__ double __nv_fdim (double __a, double __b)
__DEVICE__ float __nv_fdimf (float __a, float __b)
__DEVICE__ float __nv_fdiv_rd (float __a, float __b)
__DEVICE__ float __nv_fdiv_rn (float __a, float __b)
__DEVICE__ float __nv_fdiv_ru (float __a, float __b)
__DEVICE__ float __nv_fdiv_rz (float __a, float __b)
__DEVICE__ int __nv_ffs (int __a)
__DEVICE__ int __nv_ffsll (long long __a)
__DEVICE__ int __nv_finitef (float __a)
__DEVICE__ unsigned short __nv_float2half_rn (float __a)
__DEVICE__ int __nv_float2int_rd (float __a)
__DEVICE__ int __nv_float2int_rn (float __a)
__DEVICE__ int __nv_float2int_ru (float __a)
__DEVICE__ int __nv_float2int_rz (float __a)
__DEVICE__ long long __nv_float2ll_rd (float __a)
__DEVICE__ long long __nv_float2ll_rn (float __a)
__DEVICE__ long long __nv_float2ll_ru (float __a)
__DEVICE__ long long __nv_float2ll_rz (float __a)
__DEVICE__ unsigned int __nv_float2uint_rd (float __a)
__DEVICE__ unsigned int __nv_float2uint_rn (float __a)
__DEVICE__ unsigned int __nv_float2uint_ru (float __a)
__DEVICE__ unsigned int __nv_float2uint_rz (float __a)
__DEVICE__ unsigned long long __nv_float2ull_rd (float __a)
__DEVICE__ unsigned long long __nv_float2ull_rn (float __a)
__DEVICE__ unsigned long long __nv_float2ull_ru (float __a)
__DEVICE__ unsigned long long __nv_float2ull_rz (float __a)
__DEVICE__ int __nv_float_as_int (float __a)
__DEVICE__ unsigned int __nv_float_as_uint (float __a)
__DEVICE__ double __nv_floor (double __a)
__DEVICE__ float __nv_floorf (float __a)
__DEVICE__ double __nv_fma (double __a, double __b, double __c)
__DEVICE__ float __nv_fmaf (float __a, float __b, float __c)
__DEVICE__ float __nv_fmaf_ieee_rd (float __a, float __b, float __c)
__DEVICE__ float __nv_fmaf_ieee_rn (float __a, float __b, float __c)
__DEVICE__ float __nv_fmaf_ieee_ru (float __a, float __b, float __c)
__DEVICE__ float __nv_fmaf_ieee_rz (float __a, float __b, float __c)
__DEVICE__ float __nv_fmaf_rd (float __a, float __b, float __c)
__DEVICE__ float __nv_fmaf_rn (float __a, float __b, float __c)
__DEVICE__ float __nv_fmaf_ru (float __a, float __b, float __c)
__DEVICE__ float __nv_fmaf_rz (float __a, float __b, float __c)
__DEVICE__ double __nv_fma_rd (double __a, double __b, double __c)
__DEVICE__ double __nv_fma_rn (double __a, double __b, double __c)
__DEVICE__ double __nv_fma_ru (double __a, double __b, double __c)
__DEVICE__ double __nv_fma_rz (double __a, double __b, double __c)
__DEVICE__ double __nv_fmax (double __a, double __b)
__DEVICE__ float __nv_fmaxf (float __a, float __b)
__DEVICE__ double __nv_fmin (double __a, double __b)
__DEVICE__ float __nv_fminf (float __a, float __b)
__DEVICE__ double __nv_fmod (double __a, double __b)
__DEVICE__ float __nv_fmodf (float __a, float __b)
__DEVICE__ float __nv_fmul_rd (float __a, float __b)
__DEVICE__ float __nv_fmul_rn (float __a, float __b)
__DEVICE__ float __nv_fmul_ru (float __a, float __b)
__DEVICE__ float __nv_fmul_rz (float __a, float __b)
__DEVICE__ float __nv_frcp_rd (float __a)
__DEVICE__ float __nv_frcp_rn (float __a)
__DEVICE__ float __nv_frcp_ru (float __a)
__DEVICE__ float __nv_frcp_rz (float __a)
__DEVICE__ double __nv_frexp (double __a, int *__b)
__DEVICE__ float __nv_frexpf (float __a, int *__b)
__DEVICE__ float __nv_frsqrt_rn (float __a)
__DEVICE__ float __nv_fsqrt_rd (float __a)
__DEVICE__ float __nv_fsqrt_rn (float __a)
__DEVICE__ float __nv_fsqrt_ru (float __a)
__DEVICE__ float __nv_fsqrt_rz (float __a)
__DEVICE__ float __nv_fsub_rd (float __a, float __b)
__DEVICE__ float __nv_fsub_rn (float __a, float __b)
__DEVICE__ float __nv_fsub_ru (float __a, float __b)
__DEVICE__ float __nv_fsub_rz (float __a, float __b)
__DEVICE__ int __nv_hadd (int __a, int __b)
__DEVICE__ float __nv_half2float (unsigned short __h)
__DEVICE__ double __nv_hiloint2double (int __a, int __b)
__DEVICE__ double __nv_hypot (double __a, double __b)
__DEVICE__ float __nv_hypotf (float __a, float __b)
__DEVICE__ int __nv_ilogb (double __a)
__DEVICE__ int __nv_ilogbf (float __a)
__DEVICE__ double __nv_int2double_rn (int __a)
__DEVICE__ float __nv_int2float_rd (int __a)
__DEVICE__ float __nv_int2float_rn (int __a)
__DEVICE__ float __nv_int2float_ru (int __a)
__DEVICE__ float __nv_int2float_rz (int __a)
__DEVICE__ float __nv_int_as_float (int __a)
__DEVICE__ int __nv_isfinited (double __a)
__DEVICE__ int __nv_isinfd (double __a)
__DEVICE__ int __nv_isinff (float __a)
__DEVICE__ int __nv_isnand (double __a)
__DEVICE__ int __nv_isnanf (float __a)
__DEVICE__ double __nv_j0 (double __a)
__DEVICE__ float __nv_j0f (float __a)
__DEVICE__ double __nv_j1 (double __a)
__DEVICE__ float __nv_j1f (float __a)
__DEVICE__ float __nv_jnf (int __a, float __b)
__DEVICE__ double __nv_jn (int __a, double __b)
__DEVICE__ double __nv_ldexp (double __a, int __b)
__DEVICE__ float __nv_ldexpf (float __a, int __b)
__DEVICE__ double __nv_lgamma (double __a)
__DEVICE__ float __nv_lgammaf (float __a)
__DEVICE__ double __nv_ll2double_rd (long long __a)
__DEVICE__ double __nv_ll2double_rn (long long __a)
__DEVICE__ double __nv_ll2double_ru (long long __a)
__DEVICE__ double __nv_ll2double_rz (long long __a)
__DEVICE__ float __nv_ll2float_rd (long long __a)
__DEVICE__ float __nv_ll2float_rn (long long __a)
__DEVICE__ float __nv_ll2float_ru (long long __a)
__DEVICE__ float __nv_ll2float_rz (long long __a)
__DEVICE__ long long __nv_llabs (long long __a)
__DEVICE__ long long __nv_llmax (long long __a, long long __b)
__DEVICE__ long long __nv_llmin (long long __a, long long __b)
__DEVICE__ long long __nv_llrint (double __a)
__DEVICE__ long long __nv_llrintf (float __a)
__DEVICE__ long long __nv_llround (double __a)
__DEVICE__ long long __nv_llroundf (float __a)
__DEVICE__ double __nv_log10 (double __a)
__DEVICE__ float __nv_log10f (float __a)
__DEVICE__ double __nv_log1p (double __a)
__DEVICE__ float __nv_log1pf (float __a)
__DEVICE__ double __nv_log2 (double __a)
__DEVICE__ float __nv_log2f (float __a)
__DEVICE__ double __nv_logb (double __a)
__DEVICE__ float __nv_logbf (float __a)
__DEVICE__ double __nv_log (double __a)
__DEVICE__ float __nv_logf (float __a)
__DEVICE__ double __nv_longlong_as_double (long long __a)
__DEVICE__ int __nv_max (int __a, int __b)
__DEVICE__ int __nv_min (int __a, int __b)
__DEVICE__ double __nv_modf (double __a, double *__b)
__DEVICE__ float __nv_modff (float __a, float *__b)
__DEVICE__ int __nv_mul24 (int __a, int __b)
__DEVICE__ long long __nv_mul64hi (long long __a, long long __b)
__DEVICE__ int __nv_mulhi (int __a, int __b)
__DEVICE__ double __nv_nan (const signed char *__a)
__DEVICE__ float __nv_nanf (const signed char *__a)
__DEVICE__ double __nv_nearbyint (double __a)
__DEVICE__ float __nv_nearbyintf (float __a)
__DEVICE__ double __nv_nextafter (double __a, double __b)
__DEVICE__ float __nv_nextafterf (float __a, float __b)
__DEVICE__ double __nv_norm3d (double __a, double __b, double __c)
__DEVICE__ float __nv_norm3df (float __a, float __b, float __c)
__DEVICE__ double __nv_norm4d (double __a, double __b, double __c, double __d)
__DEVICE__ float __nv_norm4df (float __a, float __b, float __c, float __d)
__DEVICE__ double __nv_normcdf (double __a)
__DEVICE__ float __nv_normcdff (float __a)
__DEVICE__ double __nv_normcdfinv (double __a)
__DEVICE__ float __nv_normcdfinvf (float __a)
__DEVICE__ float __nv_normf (int __a, const float *__b)
__DEVICE__ double __nv_norm (int __a, const double *__b)
__DEVICE__ int __nv_popc (int __a)
__DEVICE__ int __nv_popcll (long long __a)
__DEVICE__ double __nv_pow (double __a, double __b)
__DEVICE__ float __nv_powf (float __a, float __b)
__DEVICE__ double __nv_powi (double __a, int __b)
__DEVICE__ float __nv_powif (float __a, int __b)
__DEVICE__ double __nv_rcbrt (double __a)
__DEVICE__ float __nv_rcbrtf (float __a)
__DEVICE__ double __nv_rcp64h (double __a)
__DEVICE__ double __nv_remainder (double __a, double __b)
__DEVICE__ float __nv_remainderf (float __a, float __b)
__DEVICE__ double __nv_remquo (double __a, double __b, int *__c)
__DEVICE__ float __nv_remquof (float __a, float __b, int *__c)
__DEVICE__ int __nv_rhadd (int __a, int __b)
__DEVICE__ double __nv_rhypot (double __a, double __b)
__DEVICE__ float __nv_rhypotf (float __a, float __b)
__DEVICE__ double __nv_rint (double __a)
__DEVICE__ float __nv_rintf (float __a)
__DEVICE__ double __nv_rnorm3d (double __a, double __b, double __c)
__DEVICE__ float __nv_rnorm3df (float __a, float __b, float __c)
__DEVICE__ double __nv_rnorm4d (double __a, double __b, double __c, double __d)
__DEVICE__ float __nv_rnorm4df (float __a, float __b, float __c, float __d)
__DEVICE__ float __nv_rnormf (int __a, const float *__b)
__DEVICE__ double __nv_rnorm (int __a, const double *__b)
__DEVICE__ double __nv_round (double __a)
__DEVICE__ float __nv_roundf (float __a)
__DEVICE__ double __nv_rsqrt (double __a)
__DEVICE__ float __nv_rsqrtf (float __a)
__DEVICE__ int __nv_sad (int __a, int __b, int __c)
__DEVICE__ float __nv_saturatef (float __a)
__DEVICE__ double __nv_scalbn (double __a, int __b)
__DEVICE__ float __nv_scalbnf (float __a, int __b)
__DEVICE__ int __nv_signbitd (double __a)
__DEVICE__ int __nv_signbitf (float __a)
__DEVICE__ void __nv_sincos (double __a, double *__b, double *__c)
__DEVICE__ void __nv_sincosf (float __a, float *__b, float *__c)
__DEVICE__ void __nv_sincospi (double __a, double *__b, double *__c)
__DEVICE__ void __nv_sincospif (float __a, float *__b, float *__c)
__DEVICE__ double __nv_sin (double __a)
__DEVICE__ float __nv_sinf (float __a)
__DEVICE__ double __nv_sinh (double __a)
__DEVICE__ float __nv_sinhf (float __a)
__DEVICE__ double __nv_sinpi (double __a)
__DEVICE__ float __nv_sinpif (float __a)
__DEVICE__ double __nv_sqrt (double __a)
__DEVICE__ float __nv_sqrtf (float __a)
__DEVICE__ double __nv_tan (double __a)
__DEVICE__ float __nv_tanf (float __a)
__DEVICE__ double __nv_tanh (double __a)
__DEVICE__ float __nv_tanhf (float __a)
__DEVICE__ double __nv_tgamma (double __a)
__DEVICE__ float __nv_tgammaf (float __a)
__DEVICE__ double __nv_trunc (double __a)
__DEVICE__ float __nv_truncf (float __a)
__DEVICE__ int __nv_uhadd (unsigned int __a, unsigned int __b)
__DEVICE__ double __nv_uint2double_rn (unsigned int __i)
__DEVICE__ float __nv_uint2float_rd (unsigned int __a)
__DEVICE__ float __nv_uint2float_rn (unsigned int __a)
__DEVICE__ float __nv_uint2float_ru (unsigned int __a)
__DEVICE__ float __nv_uint2float_rz (unsigned int __a)
__DEVICE__ float __nv_uint_as_float (unsigned int __a)
__DEVICE__ double __nv_ull2double_rd (unsigned long long __a)
__DEVICE__ double __nv_ull2double_rn (unsigned long long __a)
__DEVICE__ double __nv_ull2double_ru (unsigned long long __a)
__DEVICE__ double __nv_ull2double_rz (unsigned long long __a)
__DEVICE__ float __nv_ull2float_rd (unsigned long long __a)
__DEVICE__ float __nv_ull2float_rn (unsigned long long __a)
__DEVICE__ float __nv_ull2float_ru (unsigned long long __a)
__DEVICE__ float __nv_ull2float_rz (unsigned long long __a)
__DEVICE__ unsigned long long __nv_ullmax (unsigned long long __a, unsigned long long __b)
__DEVICE__ unsigned long long __nv_ullmin (unsigned long long __a, unsigned long long __b)
__DEVICE__ unsigned int __nv_umax (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __nv_umin (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __nv_umul24 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned long long __nv_umul64hi (unsigned long long __a, unsigned long long __b)
__DEVICE__ unsigned int __nv_umulhi (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __nv_urhadd (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __nv_usad (unsigned int __a, unsigned int __b, unsigned int __c)
__DEVICE__ double __nv_y0 (double __a)
__DEVICE__ float __nv_y0f (float __a)
__DEVICE__ double __nv_y1 (double __a)
__DEVICE__ float __nv_y1f (float __a)
__DEVICE__ float __nv_ynf (int __a, float __b)
__DEVICE__ double __nv_yn (int __a, double __b)
Function Documentation
__nv_abs()
__DEVICE__ int __nv_abs (int __a)
Referenced by abs(), and labs().
__nv_acos()
__DEVICE__ double __nv_acos (double __a)
Referenced by acos().
__nv_acosf()
__DEVICE__ float __nv_acosf (float __a)
Referenced by acosf().
__nv_acosh()
__DEVICE__ double __nv_acosh (double __a)
Referenced by acosh().
__nv_acoshf()
__DEVICE__ float __nv_acoshf (float __a)
Referenced by acoshf().
__nv_asin()
__DEVICE__ double __nv_asin (double __a)
Referenced by asin().
__nv_asinf()
__DEVICE__ float __nv_asinf (float __a)
Referenced by asinf().
__nv_asinh()
__DEVICE__ double __nv_asinh (double __a)
Referenced by asinh().
__nv_asinhf()
__DEVICE__ float __nv_asinhf (float __a)
Referenced by asinhf().
__nv_atan()
__DEVICE__ double __nv_atan (double __a)
Referenced by atan().
__nv_atan2()
__DEVICE__ double __nv_atan2 (double __a, double __b)
Referenced by atan2().
__nv_atan2f()
__DEVICE__ float __nv_atan2f (float __a, float __b)
Referenced by atan2f().
__nv_atanf()
__DEVICE__ float __nv_atanf (float __a)
Referenced by atanf().
__nv_atanh()
__DEVICE__ double __nv_atanh (double __a)
Referenced by atanh().
__nv_atanhf()
__DEVICE__ float __nv_atanhf (float __a)
Referenced by atanhf().
__nv_brev()
__DEVICE__ int __nv_brev (int __a)
Referenced by __brev().
__nv_brevll()
__DEVICE__ long long __nv_brevll (long long __a)
Referenced by __brevll().
__nv_byte_perm()
__DEVICE__ int __nv_byte_perm (int __a, int __b, int __c)
Referenced by __byte_perm().
__nv_cbrt()
__DEVICE__ double __nv_cbrt (double __a)
Referenced by cbrt().
__nv_cbrtf()
__DEVICE__ float __nv_cbrtf (float __a)
Referenced by cbrtf().
__nv_ceil()
__DEVICE__ double __nv_ceil (double __a)
Referenced by ceil().
__nv_ceilf()
__DEVICE__ float __nv_ceilf (float __a)
Referenced by ceilf().
__nv_clz()
__DEVICE__ int __nv_clz (int __a)
Referenced by __clz().
__nv_clzll()
__DEVICE__ int __nv_clzll (long long __a)
Referenced by __clzll().
__nv_copysign()
__DEVICE__ double __nv_copysign (double __a, double __b)
Referenced by copysign().
__nv_copysignf()
__DEVICE__ float __nv_copysignf (float __a, float __b)
Referenced by copysignf().
__nv_cos()
__DEVICE__ double __nv_cos (double __a)
Referenced by cos().
__nv_cosf()
__DEVICE__ float __nv_cosf (float __a)
Referenced by cosf().
__nv_cosh()
__DEVICE__ double __nv_cosh (double __a)
Referenced by cosh().
__nv_coshf()
__DEVICE__ float __nv_coshf (float __a)
Referenced by coshf().
__nv_cospi()
__DEVICE__ double __nv_cospi (double __a)
Referenced by cospi().
__nv_cospif()
__DEVICE__ float __nv_cospif (float __a)
Referenced by cospif().
__nv_cyl_bessel_i0()
__DEVICE__ double __nv_cyl_bessel_i0 (double __a)
Referenced by cyl_bessel_i0().
__nv_cyl_bessel_i0f()
__DEVICE__ float __nv_cyl_bessel_i0f (float __a)
Referenced by cyl_bessel_i0f().
__nv_cyl_bessel_i1()
__DEVICE__ double __nv_cyl_bessel_i1 (double __a)
Referenced by cyl_bessel_i1().
__nv_cyl_bessel_i1f()
__DEVICE__ float __nv_cyl_bessel_i1f (float __a)
Referenced by cyl_bessel_i1f().
__nv_dadd_rd()
__DEVICE__ double __nv_dadd_rd (double __a, double __b)
Referenced by __dadd_rd().
__nv_dadd_rn()
__DEVICE__ double __nv_dadd_rn (double __a, double __b)
Referenced by __dadd_rn().
__nv_dadd_ru()
__DEVICE__ double __nv_dadd_ru (double __a, double __b)
Referenced by __dadd_ru().
__nv_dadd_rz()
__DEVICE__ double __nv_dadd_rz (double __a, double __b)
Referenced by __dadd_rz().
__nv_ddiv_rd()
__DEVICE__ double __nv_ddiv_rd (double __a, double __b)
Referenced by __ddiv_rd().
__nv_ddiv_rn()
__DEVICE__ double __nv_ddiv_rn (double __a, double __b)
Referenced by __ddiv_rn().
__nv_ddiv_ru()
__DEVICE__ double __nv_ddiv_ru (double __a, double __b)
Referenced by __ddiv_ru().
__nv_ddiv_rz()
__DEVICE__ double __nv_ddiv_rz (double __a, double __b)
Referenced by __ddiv_rz().
__nv_dmul_rd()
__DEVICE__ double __nv_dmul_rd (double __a, double __b)
Referenced by __dmul_rd().
__nv_dmul_rn()
__DEVICE__ double __nv_dmul_rn (double __a, double __b)
Referenced by __dmul_rn().
__nv_dmul_ru()
__DEVICE__ double __nv_dmul_ru (double __a, double __b)
Referenced by __dmul_ru().
__nv_dmul_rz()
__DEVICE__ double __nv_dmul_rz (double __a, double __b)
Referenced by __dmul_rz().
__nv_double2float_rd()
__DEVICE__ float __nv_double2float_rd (double __a)
Referenced by __double2float_rd().
__nv_double2float_rn()
__DEVICE__ float __nv_double2float_rn (double __a)
Referenced by __double2float_rn().
__nv_double2float_ru()
__DEVICE__ float __nv_double2float_ru (double __a)
Referenced by __double2float_ru().
__nv_double2float_rz()
__DEVICE__ float __nv_double2float_rz (double __a)
Referenced by __double2float_rz().
__nv_double2hiint()
__DEVICE__ int __nv_double2hiint (double __a)
Referenced by __double2hiint().
__nv_double2int_rd()
__DEVICE__ int __nv_double2int_rd (double __a)
Referenced by __double2int_rd().
__nv_double2int_rn()
__DEVICE__ int __nv_double2int_rn (double __a)
Referenced by __double2int_rn().
__nv_double2int_ru()
__DEVICE__ int __nv_double2int_ru (double __a)
Referenced by __double2int_ru().
__nv_double2int_rz()
__DEVICE__ int __nv_double2int_rz (double __a)
Referenced by __double2int_rz().
__nv_double2ll_rd()
__DEVICE__ long long __nv_double2ll_rd (double __a)
Referenced by __double2ll_rd().
__nv_double2ll_rn()
__DEVICE__ long long __nv_double2ll_rn (double __a)
Referenced by __double2ll_rn().
__nv_double2ll_ru()
__DEVICE__ long long __nv_double2ll_ru (double __a)
Referenced by __double2ll_ru().
__nv_double2ll_rz()
__DEVICE__ long long __nv_double2ll_rz (double __a)
Referenced by __double2ll_rz().
__nv_double2loint()
__DEVICE__ int __nv_double2loint (double __a)
Referenced by __double2loint().
__nv_double2uint_rd()
__DEVICE__ unsigned int __nv_double2uint_rd (double __a)
Referenced by __double2uint_rd().
__nv_double2uint_rn()
__DEVICE__ unsigned int __nv_double2uint_rn (double __a)
Referenced by __double2uint_rn().
__nv_double2uint_ru()
__DEVICE__ unsigned int __nv_double2uint_ru (double __a)
Referenced by __double2uint_ru().
__nv_double2uint_rz()
__DEVICE__ unsigned int __nv_double2uint_rz (double __a)
Referenced by __double2uint_rz().
__nv_double2ull_rd()
__DEVICE__ unsigned long long __nv_double2ull_rd (double __a)
Referenced by __double2ull_rd().
__nv_double2ull_rn()
__DEVICE__ unsigned long long __nv_double2ull_rn (double __a)
Referenced by __double2ull_rn().
__nv_double2ull_ru()
__DEVICE__ unsigned long long __nv_double2ull_ru (double __a)
Referenced by __double2ull_ru().
__nv_double2ull_rz()
__DEVICE__ unsigned long long __nv_double2ull_rz (double __a)
Referenced by __double2ull_rz().
__nv_double_as_longlong()
__DEVICE__ unsigned long long __nv_double_as_longlong (double __a)
Referenced by __double_as_longlong().
__nv_drcp_rd()
__DEVICE__ double __nv_drcp_rd (double __a)
Referenced by __drcp_rd().
__nv_drcp_rn()
__DEVICE__ double __nv_drcp_rn (double __a)
Referenced by __drcp_rn().
__nv_drcp_ru()
__DEVICE__ double __nv_drcp_ru (double __a)
Referenced by __drcp_ru().
__nv_drcp_rz()
__DEVICE__ double __nv_drcp_rz (double __a)
Referenced by __drcp_rz().
__nv_dsqrt_rd()
__DEVICE__ double __nv_dsqrt_rd (double __a)
Referenced by __dsqrt_rd().
__nv_dsqrt_rn()
__DEVICE__ double __nv_dsqrt_rn (double __a)
Referenced by __dsqrt_rn().
__nv_dsqrt_ru()
__DEVICE__ double __nv_dsqrt_ru (double __a)
Referenced by __dsqrt_ru().
__nv_dsqrt_rz()
__DEVICE__ double __nv_dsqrt_rz (double __a)
Referenced by __dsqrt_rz().
__nv_dsub_rd()
__DEVICE__ double __nv_dsub_rd (double __a, double __b)
Referenced by __dsub_rd().
__nv_dsub_rn()
__DEVICE__ double __nv_dsub_rn (double __a, double __b)
Referenced by __dsub_rn().
__nv_dsub_ru()
__DEVICE__ double __nv_dsub_ru (double __a, double __b)
Referenced by __dsub_ru().
__nv_dsub_rz()
__DEVICE__ double __nv_dsub_rz (double __a, double __b)
Referenced by __dsub_rz().
__nv_erf()
__DEVICE__ double __nv_erf (double __a)
Referenced by erf().
__nv_erfc()
__DEVICE__ double __nv_erfc (double __a)
Referenced by erfc().
__nv_erfcf()
__DEVICE__ float __nv_erfcf (float __a)
Referenced by erfcf().
__nv_erfcinv()
__DEVICE__ double __nv_erfcinv (double __a)
Referenced by erfcinv().
__nv_erfcinvf()
__DEVICE__ float __nv_erfcinvf (float __a)
Referenced by erfcinvf().
__nv_erfcx()
__DEVICE__ double __nv_erfcx (double __a)
Referenced by erfcx().
__nv_erfcxf()
__DEVICE__ float __nv_erfcxf (float __a)
Referenced by erfcxf().
__nv_erff()
__DEVICE__ float __nv_erff (float __a)
Referenced by erff().
__nv_erfinv()
__DEVICE__ double __nv_erfinv (double __a)
Referenced by erfinv().
__nv_erfinvf()
__DEVICE__ float __nv_erfinvf (float __a)
Referenced by erfinvf().
__nv_exp()
__DEVICE__ double __nv_exp (double __a)
Referenced by exp().
__nv_exp10()
__DEVICE__ double __nv_exp10 (double __a)
Referenced by exp10().
__nv_exp10f()
__DEVICE__ float __nv_exp10f (float __a)
Referenced by exp10f().
__nv_exp2()
__DEVICE__ double __nv_exp2 (double __a)
Referenced by exp2().
__nv_exp2f()
__DEVICE__ float __nv_exp2f (float __a)
Referenced by exp2f().
__nv_expf()
__DEVICE__ float __nv_expf (float __a)
Referenced by expf().
__nv_expm1()
__DEVICE__ double __nv_expm1 (double __a)
Referenced by expm1().
__nv_expm1f()
__DEVICE__ float __nv_expm1f (float __a)
Referenced by expm1f().
__nv_fabs()
__DEVICE__ double __nv_fabs (double __a)
Referenced by fabs().
__nv_fabsf()
__DEVICE__ float __nv_fabsf (float __a)
Referenced by fabsf().
__nv_fadd_rd()
__DEVICE__ float __nv_fadd_rd (float __a, float __b)
Referenced by __fadd_rd().
__nv_fadd_rn()
__DEVICE__ float __nv_fadd_rn (float __a, float __b)
Referenced by __fadd_rn().
__nv_fadd_ru()
__DEVICE__ float __nv_fadd_ru (float __a, float __b)
Referenced by __fadd_ru().
__nv_fadd_rz()
__DEVICE__ float __nv_fadd_rz (float __a, float __b)
Referenced by __fadd_rz().
__nv_fast_cosf()
__DEVICE__ float __nv_fast_cosf (float __a)
Referenced by __cosf(), and cosf().
__nv_fast_exp10f()
__DEVICE__ float __nv_fast_exp10f (float __a)
Referenced by __exp10f().
__nv_fast_expf()
__DEVICE__ float __nv_fast_expf (float __a)
Referenced by __expf().
__nv_fast_fdividef()
__DEVICE__ float __nv_fast_fdividef (float __a, float __b)
Referenced by __fdividef(), and fdividef().
__nv_fast_log10f()
__DEVICE__ float __nv_fast_log10f (float __a)
Referenced by __log10f().
__nv_fast_log2f()
__DEVICE__ float __nv_fast_log2f (float __a)
Referenced by __log2f(), and log2f().
__nv_fast_logf()
__DEVICE__ float __nv_fast_logf (float __a)
Referenced by __logf(), and logf().
__nv_fast_powf()
__DEVICE__ float __nv_fast_powf (float __a, float __b)
Referenced by __powf().
__nv_fast_sincosf()
__DEVICE__ void __nv_fast_sincosf (float __a, float * __s, float * __c)
Referenced by __sincosf(), and sincosf().
__nv_fast_sinf()
__DEVICE__ float __nv_fast_sinf (float __a)
Referenced by __sinf(), and sinf().
__nv_fast_tanf()
__DEVICE__ float __nv_fast_tanf (float __a)
Referenced by __tanf().
__nv_fdim()
__DEVICE__ double __nv_fdim (double __a, double __b)
Referenced by fdim().
__nv_fdimf()
__DEVICE__ float __nv_fdimf (float __a, float __b)
Referenced by fdimf().
__nv_fdiv_rd()
__DEVICE__ float __nv_fdiv_rd (float __a, float __b)
Referenced by __fdiv_rd().
__nv_fdiv_rn()
__DEVICE__ float __nv_fdiv_rn (float __a, float __b)
Referenced by __fdiv_rn().
__nv_fdiv_ru()
__DEVICE__ float __nv_fdiv_ru (float __a, float __b)
Referenced by __fdiv_ru().
__nv_fdiv_rz()
__DEVICE__ float __nv_fdiv_rz (float __a, float __b)
Referenced by __fdiv_rz().
__nv_ffs()
__DEVICE__ int __nv_ffs (int __a)
Referenced by __ffs().
__nv_ffsll()
__DEVICE__ int __nv_ffsll (long long __a)
Referenced by __ffsll().
__nv_finitef()
__DEVICE__ int __nv_finitef (float __a)
Referenced by __finitef().
__nv_float2half_rn()
__DEVICE__ unsigned short __nv_float2half_rn (float __a)
__nv_float2int_rd()
__DEVICE__ int __nv_float2int_rd (float __a)
Referenced by __float2int_rd().
__nv_float2int_rn()
__DEVICE__ int __nv_float2int_rn (float __a)
Referenced by __float2int_rn().
__nv_float2int_ru()
__DEVICE__ int __nv_float2int_ru (float __a)
Referenced by __float2int_ru().
__nv_float2int_rz()
__DEVICE__ int __nv_float2int_rz (float __a)
Referenced by __float2int_rz().
__nv_float2ll_rd()
__DEVICE__ long long __nv_float2ll_rd (float __a)
Referenced by __float2ll_rd().
__nv_float2ll_rn()
__DEVICE__ long long __nv_float2ll_rn (float __a)
Referenced by __float2ll_rn().
__nv_float2ll_ru()
__DEVICE__ long long __nv_float2ll_ru (float __a)
Referenced by __float2ll_ru().
__nv_float2ll_rz()
__DEVICE__ long long __nv_float2ll_rz (float __a)
Referenced by __float2ll_rz().
__nv_float2uint_rd()
__DEVICE__ unsigned int __nv_float2uint_rd (float __a)
Referenced by __float2uint_rd().
__nv_float2uint_rn()
__DEVICE__ unsigned int __nv_float2uint_rn (float __a)
Referenced by __float2uint_rn().
__nv_float2uint_ru()
__DEVICE__ unsigned int __nv_float2uint_ru (float __a)
Referenced by __float2uint_ru().
__nv_float2uint_rz()
__DEVICE__ unsigned int __nv_float2uint_rz (float __a)
Referenced by __float2uint_rz().
__nv_float2ull_rd()
__DEVICE__ unsigned long long __nv_float2ull_rd (float __a)
Referenced by __float2ull_rd().
__nv_float2ull_rn()
__DEVICE__ unsigned long long __nv_float2ull_rn (float __a)
Referenced by __float2ull_rn().
__nv_float2ull_ru()
__DEVICE__ unsigned long long __nv_float2ull_ru (float __a)
Referenced by __float2ull_ru().
__nv_float2ull_rz()
__DEVICE__ unsigned long long __nv_float2ull_rz (float __a)
Referenced by __float2ull_rz().
__nv_float_as_int()
__DEVICE__ int __nv_float_as_int (float __a)
Referenced by __fAtomicExch(), __fAtomicExch_block(), __fAtomicExch_system(), and __float_as_int().
__nv_float_as_uint()
__DEVICE__ unsigned int __nv_float_as_uint (float __a)
Referenced by __float_as_uint().
__nv_floor()
__DEVICE__ double __nv_floor (double __a)
Referenced by floor().
__nv_floorf()
__DEVICE__ float __nv_floorf (float __a)
Referenced by floorf().
__nv_fma()
__DEVICE__ double __nv_fma (double __a, double __b, double __c)
Referenced by fma().
__nv_fma_rd()
__DEVICE__ double __nv_fma_rd (double __a, double __b, double __c)
Referenced by __fma_rd().
__nv_fma_rn()
__DEVICE__ double __nv_fma_rn (double __a, double __b, double __c)
Referenced by __fma_rn().
__nv_fma_ru()
__DEVICE__ double __nv_fma_ru (double __a, double __b, double __c)
Referenced by __fma_ru().
__nv_fma_rz()
__DEVICE__ double __nv_fma_rz (double __a, double __b, double __c)
Referenced by __fma_rz().
__nv_fmaf()
__DEVICE__ float __nv_fmaf (float __a, float __b, float __c)
Referenced by fmaf().
__nv_fmaf_ieee_rd()
__DEVICE__ float __nv_fmaf_ieee_rd (float __a, float __b, float __c)
Referenced by __fmaf_ieee_rd().
__nv_fmaf_ieee_rn()
__DEVICE__ float __nv_fmaf_ieee_rn (float __a, float __b, float __c)
Referenced by __fmaf_ieee_rn().
__nv_fmaf_ieee_ru()
__DEVICE__ float __nv_fmaf_ieee_ru (float __a, float __b, float __c)
Referenced by __fmaf_ieee_ru().
__nv_fmaf_ieee_rz()
__DEVICE__ float __nv_fmaf_ieee_rz (float __a, float __b, float __c)
Referenced by __fmaf_ieee_rz().
__nv_fmaf_rd()
__DEVICE__ float __nv_fmaf_rd (float __a, float __b, float __c)
Referenced by __fmaf_rd().
__nv_fmaf_rn()
__DEVICE__ float __nv_fmaf_rn (float __a, float __b, float __c)
Referenced by __fmaf_rn().
__nv_fmaf_ru()
__DEVICE__ float __nv_fmaf_ru (float __a, float __b, float __c)
Referenced by __fmaf_ru().
__nv_fmaf_rz()
__DEVICE__ float __nv_fmaf_rz (float __a, float __b, float __c)
Referenced by __fmaf_rz().
__nv_fmax()
__DEVICE__ double __nv_fmax (double __a, double __b)
Referenced by fmax().
__nv_fmaxf()
__DEVICE__ float __nv_fmaxf (float __a, float __b)
Referenced by fmaxf().
__nv_fmin()
__DEVICE__ double __nv_fmin (double __a, double __b)
Referenced by fmin().
__nv_fminf()
__DEVICE__ float __nv_fminf (float __a, float __b)
Referenced by fminf().
__nv_fmod()
__DEVICE__ double __nv_fmod (double __a, double __b)
Referenced by fmod().
__nv_fmodf()
__DEVICE__ float __nv_fmodf (float __a, float __b)
Referenced by fmodf().
__nv_fmul_rd()
__DEVICE__ float __nv_fmul_rd (float __a, float __b)
Referenced by __fmul_rd().
__nv_fmul_rn()
__DEVICE__ float __nv_fmul_rn (float __a, float __b)
Referenced by __fmul_rn().
__nv_fmul_ru()
__DEVICE__ float __nv_fmul_ru (float __a, float __b)
Referenced by __fmul_ru().
__nv_fmul_rz()
__DEVICE__ float __nv_fmul_rz (float __a, float __b)
Referenced by __fmul_rz().
__nv_frcp_rd()
__DEVICE__ float __nv_frcp_rd (float __a)
Referenced by __frcp_rd().
__nv_frcp_rn()
__DEVICE__ float __nv_frcp_rn (float __a)
Referenced by __frcp_rn().
__nv_frcp_ru()
__DEVICE__ float __nv_frcp_ru (float __a)
Referenced by __frcp_ru().
__nv_frcp_rz()
__DEVICE__ float __nv_frcp_rz (float __a)
Referenced by __frcp_rz().
__nv_frexp()
__DEVICE__ double __nv_frexp (double __a, int * __b)
Referenced by frexp().
__nv_frexpf()
__DEVICE__ float __nv_frexpf (float __a, int * __b)
Referenced by frexpf().
__nv_frsqrt_rn()
__DEVICE__ float __nv_frsqrt_rn (float __a)
Referenced by __frsqrt_rn().
__nv_fsqrt_rd()
__DEVICE__ float __nv_fsqrt_rd (float __a)
Referenced by __fsqrt_rd().
__nv_fsqrt_rn()
__DEVICE__ float __nv_fsqrt_rn (float __a)
Referenced by __fsqrt_rn().
__nv_fsqrt_ru()
__DEVICE__ float __nv_fsqrt_ru (float __a)
Referenced by __fsqrt_ru().
__nv_fsqrt_rz()
__DEVICE__ float __nv_fsqrt_rz (float __a)
Referenced by __fsqrt_rz().
__nv_fsub_rd()
__DEVICE__ float __nv_fsub_rd (float __a, float __b)
Referenced by __fsub_rd().
__nv_fsub_rn()
__DEVICE__ float __nv_fsub_rn (float __a, float __b)
Referenced by __fsub_rn().
__nv_fsub_ru()
__DEVICE__ float __nv_fsub_ru (float __a, float __b)
Referenced by __fsub_ru().
__nv_fsub_rz()
__DEVICE__ float __nv_fsub_rz (float __a, float __b)
Referenced by __fsub_rz().
__nv_hadd()
__DEVICE__ int __nv_hadd (int __a, int __b)
Referenced by __hadd().
__nv_half2float()
__DEVICE__ float __nv_half2float (unsigned short __h)
__nv_hiloint2double()
__DEVICE__ double __nv_hiloint2double (int __a, int __b)
Referenced by __hiloint2double().
__nv_hypot()
__DEVICE__ double __nv_hypot (double __a, double __b)
Referenced by hypot().
__nv_hypotf()
__DEVICE__ float __nv_hypotf (float __a, float __b)
Referenced by hypotf().
__nv_ilogb()
__DEVICE__ int __nv_ilogb (double __a)
Referenced by ilogb().
__nv_ilogbf()
__DEVICE__ int __nv_ilogbf (float __a)
Referenced by ilogbf().
__nv_int2double_rn()
__DEVICE__ double __nv_int2double_rn (int __a)
Referenced by __int2double_rn().
__nv_int2float_rd()
__DEVICE__ float __nv_int2float_rd (int __a)
Referenced by __int2float_rd().
__nv_int2float_rn()
__DEVICE__ float __nv_int2float_rn (int __a)
Referenced by __int2float_rn().
__nv_int2float_ru()
__DEVICE__ float __nv_int2float_ru (int __a)
Referenced by __int2float_ru().
__nv_int2float_rz()
__DEVICE__ float __nv_int2float_rz (int __a)
Referenced by __int2float_rz().
__nv_int_as_float()
__DEVICE__ float __nv_int_as_float (int __a)
Referenced by __fAtomicExch(), __fAtomicExch_block(), __fAtomicExch_system(), and __int_as_float().
__nv_isfinited()
__DEVICE__ int __nv_isfinited (double __a)
Referenced by __finite(), and __isfinited().
__nv_isinfd()
__DEVICE__ int __nv_isinfd (double __a)
Referenced by __isinf().
__nv_isinff()
__DEVICE__ int __nv_isinff (float __a)
Referenced by __isinff().
__nv_isnand()
__DEVICE__ int __nv_isnand (double __a)
Referenced by __isnan().
__nv_isnanf()
__DEVICE__ int __nv_isnanf (float __a)
Referenced by __isnanf().
__nv_j0()
__DEVICE__ double __nv_j0 (double __a)
Referenced by j0().
__nv_j0f()
__DEVICE__ float __nv_j0f (float __a)
Referenced by j0f().
__nv_j1()
__DEVICE__ double __nv_j1 (double __a)
Referenced by j1().
__nv_j1f()
__DEVICE__ float __nv_j1f (float __a)
Referenced by j1f().
__nv_jn()
__DEVICE__ double __nv_jn (int __a, double __b)
Referenced by jn().
__nv_jnf()
__DEVICE__ float __nv_jnf (int __a, float __b)
Referenced by jnf().
__nv_ldexp()
__DEVICE__ double __nv_ldexp (double __a, int __b)
Referenced by ldexp().
__nv_ldexpf()
__DEVICE__ float __nv_ldexpf (float __a, int __b)
Referenced by ldexpf().
__nv_lgamma()
__DEVICE__ double __nv_lgamma (double __a)
Referenced by lgamma().
__nv_lgammaf()
__DEVICE__ float __nv_lgammaf (float __a)
Referenced by lgammaf().
__nv_ll2double_rd()
__DEVICE__ double __nv_ll2double_rd (long long __a)
Referenced by __ll2double_rd().
__nv_ll2double_rn()
__DEVICE__ double __nv_ll2double_rn (long long __a)
Referenced by __ll2double_rn().
__nv_ll2double_ru()
__DEVICE__ double __nv_ll2double_ru (long long __a)
Referenced by __ll2double_ru().
__nv_ll2double_rz()
__DEVICE__ double __nv_ll2double_rz (long long __a)
Referenced by __ll2double_rz().
__nv_ll2float_rd()
__DEVICE__ float __nv_ll2float_rd (long long __a)
Referenced by __ll2float_rd().
__nv_ll2float_rn()
__DEVICE__ float __nv_ll2float_rn (long long __a)
Referenced by __ll2float_rn().
__nv_ll2float_ru()
__DEVICE__ float __nv_ll2float_ru (long long __a)
Referenced by __ll2float_ru().
__nv_ll2float_rz()
__DEVICE__ float __nv_ll2float_rz (long long __a)
Referenced by __ll2float_rz().
__nv_llabs()
__DEVICE__ long long __nv_llabs (long long __a)
Referenced by llabs().
__nv_llmax()
__DEVICE__ long long __nv_llmax (long long __a, long long __b)
Referenced by llmax().
__nv_llmin()
__DEVICE__ long long __nv_llmin (long long __a, long long __b)
Referenced by llmin().
__nv_llrint()
__DEVICE__ long long __nv_llrint (double __a)
Referenced by llrint().
__nv_llrintf()
__DEVICE__ long long __nv_llrintf (float __a)
Referenced by llrintf().
__nv_llround()
__DEVICE__ long long __nv_llround (double __a)
Referenced by llround().
__nv_llroundf()
__DEVICE__ long long __nv_llroundf (float __a)
Referenced by llroundf().
__nv_log()
__DEVICE__ double __nv_log (double __a)
Referenced by log().
__nv_log10()
__DEVICE__ double __nv_log10 (double __a)
Referenced by log10().
__nv_log10f()
__DEVICE__ float __nv_log10f (float __a)
Referenced by log10f().
__nv_log1p()
__DEVICE__ double __nv_log1p (double __a)
Referenced by log1p().
__nv_log1pf()
__DEVICE__ float __nv_log1pf (float __a)
Referenced by log1pf().
__nv_log2()
__DEVICE__ double __nv_log2 (double __a)
Referenced by log2().
__nv_log2f()
__DEVICE__ float __nv_log2f (float __a)
Referenced by log2f().
__nv_logb()
__DEVICE__ double __nv_logb (double __a)
Referenced by logb().
__nv_logbf()
__DEVICE__ float __nv_logbf (float __a)
Referenced by logbf().
__nv_logf()
__DEVICE__ float __nv_logf (float __a)
Referenced by logf().
__nv_longlong_as_double()
__DEVICE__ double __nv_longlong_as_double (long long __a)
Referenced by __longlong_as_double().
__nv_max()
__DEVICE__ int __nv_max (int __a, int __b)
Referenced by max().
__nv_min()
__DEVICE__ int __nv_min (int __a, int __b)
Referenced by min().
__nv_modf()
__DEVICE__ double __nv_modf (double __a, double * __b)
Referenced by modf().
__nv_modff()
__DEVICE__ float __nv_modff (float __a, float * __b)
Referenced by modff().
__nv_mul24()
__DEVICE__ int __nv_mul24 (int __a, int __b)
Referenced by __mul24().
__nv_mul64hi()
__DEVICE__ long long __nv_mul64hi (long long __a, long long __b)
Referenced by __mul64hi().
__nv_mulhi()
__DEVICE__ int __nv_mulhi (int __a, int __b)
Referenced by __mulhi().
__nv_nan()
__DEVICE__ double __nv_nan (const signed char * __a)
__nv_nanf()
__DEVICE__ float __nv_nanf (const signed char * __a)
__nv_nearbyint()
__DEVICE__ double __nv_nearbyint (double __a)
Referenced by nearbyint().
__nv_nearbyintf()
__DEVICE__ float __nv_nearbyintf (float __a)
Referenced by nearbyintf().
__nv_nextafter()
__DEVICE__ double __nv_nextafter (double __a, double __b)
Referenced by nextafter().
__nv_nextafterf()
__DEVICE__ float __nv_nextafterf (float __a, float __b)
Referenced by nextafterf().
__nv_norm()
__DEVICE__ double __nv_norm (int __a, const double * __b)
Referenced by norm().
__nv_norm3d()
__DEVICE__ double __nv_norm3d (double __a, double __b, double __c)
Referenced by norm3d().
__nv_norm3df()
__DEVICE__ float __nv_norm3df (float __a, float __b, float __c)
Referenced by norm3df().
__nv_norm4d()
__DEVICE__ double __nv_norm4d (double __a, double __b, double __c, double __d)
Referenced by norm4d().
__nv_norm4df()
__DEVICE__ float __nv_norm4df (float __a, float __b, float __c, float __d)
Referenced by norm4df().
__nv_normcdf()
__DEVICE__ double __nv_normcdf (double __a)
Referenced by normcdf().
__nv_normcdff()
__DEVICE__ float __nv_normcdff (float __a)
Referenced by normcdff().
__nv_normcdfinv()
__DEVICE__ double __nv_normcdfinv (double __a)
Referenced by normcdfinv().
__nv_normcdfinvf()
__DEVICE__ float __nv_normcdfinvf (float __a)
Referenced by normcdfinvf().
__nv_normf()
__DEVICE__ float __nv_normf (int __a, const float * __b)
Referenced by normf().
__nv_popc()
__DEVICE__ int __nv_popc (int __a)
Referenced by __popc().
__nv_popcll()
__DEVICE__ int __nv_popcll (long long __a)
Referenced by __popcll().
__nv_pow()
__DEVICE__ double __nv_pow (double __a, double __b)
Referenced by pow().
__nv_powf()
__DEVICE__ float __nv_powf (float __a, float __b)
Referenced by powf().
__nv_powi()
__DEVICE__ double __nv_powi (double __a, int __b)
Referenced by powi().
__nv_powif()
__DEVICE__ float __nv_powif (float __a, int __b)
Referenced by powif().
__nv_rcbrt()
__DEVICE__ double __nv_rcbrt (double __a)
Referenced by rcbrt().
__nv_rcbrtf()
__DEVICE__ float __nv_rcbrtf (float __a)
Referenced by rcbrtf().
__nv_rcp64h()
__DEVICE__ double __nv_rcp64h (double __a)
__nv_remainder()
__DEVICE__ double __nv_remainder (double __a, double __b)
Referenced by remainder().
__nv_remainderf()
__DEVICE__ float __nv_remainderf (float __a, float __b)
Referenced by remainderf().
__nv_remquo()
__DEVICE__ double __nv_remquo (double __a, double __b, int * __c)
Referenced by remquo().
__nv_remquof()
__DEVICE__ float __nv_remquof (float __a, float __b, int * __c)
Referenced by remquof().
__nv_rhadd()
__DEVICE__ int __nv_rhadd (int __a, int __b)
Referenced by __rhadd().
__nv_rhypot()
__DEVICE__ double __nv_rhypot (double __a, double __b)
Referenced by rhypot().
__nv_rhypotf()
__DEVICE__ float __nv_rhypotf (float __a, float __b)
Referenced by rhypotf().
__nv_rint()
__DEVICE__ double __nv_rint (double __a)
Referenced by rint().
__nv_rintf()
__DEVICE__ float __nv_rintf (float __a)
Referenced by rintf().
__nv_rnorm()
__DEVICE__ double __nv_rnorm (int __a, const double * __b)
Referenced by rnorm().
__nv_rnorm3d()
__DEVICE__ double __nv_rnorm3d (double __a, double __b, double __c)
Referenced by rnorm3d().
__nv_rnorm3df()
__DEVICE__ float __nv_rnorm3df (float __a, float __b, float __c)
Referenced by rnorm3df().
__nv_rnorm4d()
__DEVICE__ double __nv_rnorm4d (double __a, double __b, double __c, double __d)
Referenced by rnorm4d().
__nv_rnorm4df()
__DEVICE__ float __nv_rnorm4df (float __a, float __b, float __c, float __d)
Referenced by rnorm4df().
__nv_rnormf()
__DEVICE__ float __nv_rnormf (int __a, const float * __b)
Referenced by rnormf().
__nv_round()
__DEVICE__ double __nv_round (double __a)
Referenced by round().
__nv_roundf()
__DEVICE__ float __nv_roundf (float __a)
Referenced by roundf().
__nv_rsqrt()
__DEVICE__ double __nv_rsqrt (double __a)
Referenced by rsqrt().
__nv_rsqrtf()
__DEVICE__ float __nv_rsqrtf (float __a)
Referenced by rsqrtf().
__nv_sad()
__DEVICE__ int __nv_sad (int __a, int __b, int __c)
Referenced by __sad().
__nv_saturatef()
__DEVICE__ float __nv_saturatef (float __a)
Referenced by __saturatef().
__nv_scalbn()
__DEVICE__ double __nv_scalbn (double __a, int __b)
Referenced by scalbn().
__nv_scalbnf()
__DEVICE__ float __nv_scalbnf (float __a, int __b)
Referenced by scalbnf().
__nv_signbitd()
__DEVICE__ int __nv_signbitd (double __a)
Referenced by __signbitd().
__nv_signbitf()
__DEVICE__ int __nv_signbitf (float __a)
Referenced by __signbitf().
__nv_sin()
__DEVICE__ double __nv_sin (double __a)
Referenced by sin().
__nv_sincos()
__DEVICE__ void __nv_sincos (double __a, double * __b, double * __c)
Referenced by sincos().
__nv_sincosf()
__DEVICE__ void __nv_sincosf (float __a, float * __b, float * __c)
Referenced by sincosf().
__nv_sincospi()
__DEVICE__ void __nv_sincospi (double __a, double * __b, double * __c)
Referenced by sincospi().
__nv_sincospif()
__DEVICE__ void __nv_sincospif (float __a, float * __b, float * __c)
Referenced by sincospif().
__nv_sinf()
__DEVICE__ float __nv_sinf (float __a)
Referenced by sinf().
__nv_sinh()
__DEVICE__ double __nv_sinh (double __a)
Referenced by sinh().
__nv_sinhf()
__DEVICE__ float __nv_sinhf (float __a)
Referenced by sinhf().
__nv_sinpi()
__DEVICE__ double __nv_sinpi (double __a)
Referenced by sinpi().
__nv_sinpif()
__DEVICE__ float __nv_sinpif (float __a)
Referenced by sinpif().
__nv_sqrt()
__DEVICE__ double __nv_sqrt (double __a)
Referenced by sqrt().
__nv_sqrtf()
__DEVICE__ float __nv_sqrtf (float __a)
Referenced by sqrtf().
__nv_tan()
__DEVICE__ double __nv_tan (double __a)
Referenced by tan().
__nv_tanf()
__DEVICE__ float __nv_tanf (float __a)
Referenced by tanf().
__nv_tanh()
__DEVICE__ double __nv_tanh (double __a)
Referenced by tanh().
__nv_tanhf()
__DEVICE__ float __nv_tanhf (float __a)
Referenced by tanhf().
__nv_tgamma()
__DEVICE__ double __nv_tgamma (double __a)
Referenced by tgamma().
__nv_tgammaf()
__DEVICE__ float __nv_tgammaf (float __a)
Referenced by tgammaf().
__nv_trunc()
__DEVICE__ double __nv_trunc (double __a)
Referenced by trunc().
__nv_truncf()
__DEVICE__ float __nv_truncf (float __a)
Referenced by truncf().
__nv_uhadd()
__DEVICE__ int __nv_uhadd (unsigned int __a, unsigned int __b)
Referenced by __uhadd().
__nv_uint2double_rn()
__DEVICE__ double __nv_uint2double_rn (unsigned int __i)
Referenced by __uint2double_rn().
__nv_uint2float_rd()
__DEVICE__ float __nv_uint2float_rd (unsigned int __a)
Referenced by __uint2float_rd().
__nv_uint2float_rn()
__DEVICE__ float __nv_uint2float_rn (unsigned int __a)
Referenced by __uint2float_rn().
__nv_uint2float_ru()
__DEVICE__ float __nv_uint2float_ru (unsigned int __a)
Referenced by __uint2float_ru().
__nv_uint2float_rz()
__DEVICE__ float __nv_uint2float_rz (unsigned int __a)
Referenced by __uint2float_rz().
__nv_uint_as_float()
__DEVICE__ float __nv_uint_as_float (unsigned int __a)
Referenced by __uint_as_float().
__nv_ull2double_rd()
__DEVICE__ double __nv_ull2double_rd (unsigned long long __a)
Referenced by __ull2double_rd().
__nv_ull2double_rn()
__DEVICE__ double __nv_ull2double_rn (unsigned long long __a)
Referenced by __ull2double_rn().
__nv_ull2double_ru()
__DEVICE__ double __nv_ull2double_ru (unsigned long long __a)
Referenced by __ull2double_ru().
__nv_ull2double_rz()
__DEVICE__ double __nv_ull2double_rz (unsigned long long __a)
Referenced by __ull2double_rz().
__nv_ull2float_rd()
__DEVICE__ float __nv_ull2float_rd (unsigned long long __a)
Referenced by __ull2float_rd().
__nv_ull2float_rn()
__DEVICE__ float __nv_ull2float_rn (unsigned long long __a)
Referenced by __ull2float_rn().
__nv_ull2float_ru()
__DEVICE__ float __nv_ull2float_ru (unsigned long long __a)
Referenced by __ull2float_ru().
__nv_ull2float_rz()
__DEVICE__ float __nv_ull2float_rz (unsigned long long __a)
Referenced by __ull2float_rz().
__nv_ullmax()
__DEVICE__ unsigned long long __nv_ullmax (unsigned long long __a, unsigned long long __b)
Referenced by ullmax().
__nv_ullmin()
__DEVICE__ unsigned long long __nv_ullmin (unsigned long long __a, unsigned long long __b)
Referenced by ullmin().
__nv_umax()
__DEVICE__ unsigned int __nv_umax (unsigned int __a, unsigned int __b)
Referenced by umax().
__nv_umin()
__DEVICE__ unsigned int __nv_umin (unsigned int __a, unsigned int __b)
Referenced by umin().
__nv_umul24()
__DEVICE__ unsigned int __nv_umul24 (unsigned int __a, unsigned int __b)
Referenced by __umul24().
__nv_umul64hi()
__DEVICE__ unsigned long long __nv_umul64hi (unsigned long long __a, unsigned long long __b)
Referenced by __umul64hi().
__nv_umulhi()
__DEVICE__ unsigned int __nv_umulhi (unsigned int __a, unsigned int __b)
Referenced by __umulhi().
__nv_urhadd()
__DEVICE__ unsigned int __nv_urhadd (unsigned int __a, unsigned int __b)
Referenced by __urhadd().
__nv_usad()
__DEVICE__ unsigned int __nv_usad (unsigned int __a, unsigned int __b, unsigned int __c)
Referenced by __usad().
__nv_y0()
__DEVICE__ double __nv_y0 (double __a)
Referenced by y0().
__nv_y0f()
__DEVICE__ float __nv_y0f (float __a)
Referenced by y0f().
__nv_y1()
__DEVICE__ double __nv_y1 (double __a)
Referenced by y1().
__nv_y1f()
__DEVICE__ float __nv_y1f (float __a)
Referenced by y1f().
__nv_yn()
__DEVICE__ double __nv_yn (int __a, double __b)
Referenced by yn().
__nv_ynf()
__DEVICE__ float __nv_ynf (int __a, float __b)
Referenced by ynf().