ETISS 0.8.0: include/jit/clang_stdlib/avx512vlbitalgintrin.h File Reference
avx512vlbitalgintrin.h File Reference
Macros
#define __DEFAULT_FN_ATTRS128 __attribute__((__always_inline__, __nodebug__, __target__("avx512vl,avx512bitalg"), __min_vector_width__(128)))
#define __DEFAULT_FN_ATTRS256 __attribute__((__always_inline__, __nodebug__, __target__("avx512vl,avx512bitalg"), __min_vector_width__(256)))
Functions
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_popcnt_epi16 (__m256i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_popcnt_epi16 (__m256i __A, __mmask16 __U, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_popcnt_epi16 (__mmask16 __U, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_popcnt_epi16 (__m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_popcnt_epi16 (__m128i __A, __mmask8 __U, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_popcnt_epi16 (__mmask8 __U, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_popcnt_epi8 (__m256i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_popcnt_epi8 (__m256i __A, __mmask32 __U, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_popcnt_epi8 (__mmask32 __U, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_popcnt_epi8 (__m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_popcnt_epi8 (__m128i __A, __mmask16 __U, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_popcnt_epi8 (__mmask16 __U, __m128i __B)
static __inline__ __mmask32 __DEFAULT_FN_ATTRS256 _mm256_mask_bitshuffle_epi64_mask (__mmask32 __U, __m256i __A, __m256i __B)
static __inline__ __mmask32 __DEFAULT_FN_ATTRS256 _mm256_bitshuffle_epi64_mask (__m256i __A, __m256i __B)
static __inline__ __mmask16 __DEFAULT_FN_ATTRS128 _mm_mask_bitshuffle_epi64_mask (__mmask16 __U, __m128i __A, __m128i __B)
static __inline__ __mmask16 __DEFAULT_FN_ATTRS128 _mm_bitshuffle_epi64_mask (__m128i __A, __m128i __B)
Macro Definition Documentation
__DEFAULT_FN_ATTRS128
#define __DEFAULT_FN_ATTRS128 __attribute__((__always_inline__, __nodebug__, __target__("avx512vl,avx512bitalg"), __min_vector_width__(128)))
Definition at line 18 of file avx512vlbitalgintrin.h.
__DEFAULT_FN_ATTRS256
#define __DEFAULT_FN_ATTRS256 __attribute__((__always_inline__, __nodebug__, __target__("avx512vl,avx512bitalg"), __min_vector_width__(256)))
Definition at line 19 of file avx512vlbitalgintrin.h.
Function Documentation
_mm256_bitshuffle_epi64_mask()
static __inline__ __mmask32 __DEFAULT_FN_ATTRS256 _mm256_bitshuffle_epi64_mask (__m256i __A, __m256i __B) static
Definition at line 118 of file avx512vlbitalgintrin.h.
References _mm256_mask_bitshuffle_epi64_mask().
_mm256_mask_bitshuffle_epi64_mask()
static __inline__ __mmask32 __DEFAULT_FN_ATTRS256 _mm256_mask_bitshuffle_epi64_mask (__mmask32 __U, __m256i __A, __m256i __B) static
Definition at line 110 of file avx512vlbitalgintrin.h.
Referenced by _mm256_bitshuffle_epi64_mask().
_mm256_mask_popcnt_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_popcnt_epi16 (__m256i __A, __mmask16 __U, __m256i __B) static
Definition at line 28 of file avx512vlbitalgintrin.h.
References _mm256_popcnt_epi16().
Referenced by _mm256_maskz_popcnt_epi16().
_mm256_mask_popcnt_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_popcnt_epi8 (__m256i __A, __mmask32 __U, __m256i __B) static
Definition at line 72 of file avx512vlbitalgintrin.h.
References _mm256_popcnt_epi8().
Referenced by _mm256_maskz_popcnt_epi8().
_mm256_maskz_popcnt_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_popcnt_epi16 (__mmask16 __U, __m256i __B) static
Definition at line 36 of file avx512vlbitalgintrin.h.
References _mm256_mask_popcnt_epi16(), and _mm256_setzero_si256().
_mm256_maskz_popcnt_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_popcnt_epi8 (__mmask32 __U, __m256i __B) static
Definition at line 80 of file avx512vlbitalgintrin.h.
References _mm256_mask_popcnt_epi8(), and _mm256_setzero_si256().
_mm256_popcnt_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_popcnt_epi16 (__m256i __A) static
Definition at line 22 of file avx512vlbitalgintrin.h.
Referenced by _mm256_mask_popcnt_epi16().
_mm256_popcnt_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_popcnt_epi8 (__m256i __A) static
Definition at line 66 of file avx512vlbitalgintrin.h.
Referenced by _mm256_mask_popcnt_epi8().
_mm_bitshuffle_epi64_mask()
static __inline__ __mmask16 __DEFAULT_FN_ATTRS128 _mm_bitshuffle_epi64_mask (__m128i __A, __m128i __B) static
Definition at line 134 of file avx512vlbitalgintrin.h.
References _mm_mask_bitshuffle_epi64_mask().
_mm_mask_bitshuffle_epi64_mask()
static __inline__ __mmask16 __DEFAULT_FN_ATTRS128 _mm_mask_bitshuffle_epi64_mask (__mmask16 __U, __m128i __A, __m128i __B) static
Definition at line 126 of file avx512vlbitalgintrin.h.
Referenced by _mm_bitshuffle_epi64_mask().
_mm_mask_popcnt_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_popcnt_epi16 (__m128i __A, __mmask8 __U, __m128i __B) static
Definition at line 50 of file avx512vlbitalgintrin.h.
References _mm_popcnt_epi16().
Referenced by _mm_maskz_popcnt_epi16().
_mm_mask_popcnt_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_popcnt_epi8 (__m128i __A, __mmask16 __U, __m128i __B) static
Definition at line 94 of file avx512vlbitalgintrin.h.
References _mm_popcnt_epi8().
Referenced by _mm_maskz_popcnt_epi8().
_mm_maskz_popcnt_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_popcnt_epi16 (__mmask8 __U, __m128i __B) static
Definition at line 58 of file avx512vlbitalgintrin.h.
References _mm_mask_popcnt_epi16(), and _mm_setzero_si128().
_mm_maskz_popcnt_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_popcnt_epi8 (__mmask16 __U, __m128i __B) static
Definition at line 102 of file avx512vlbitalgintrin.h.
References _mm_mask_popcnt_epi8(), and _mm_setzero_si128().
_mm_popcnt_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_popcnt_epi16 (__m128i __A) static
Definition at line 44 of file avx512vlbitalgintrin.h.
Referenced by _mm_mask_popcnt_epi16().
_mm_popcnt_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_popcnt_epi8 (__m128i __A) static
Definition at line 88 of file avx512vlbitalgintrin.h.
Referenced by _mm_mask_popcnt_epi8().