ETISS 0.8.0: include/jit/clang_stdlib/avx512vlcdintrin.h File Reference
avx512vlcdintrin.h File Reference
Macros
#define __DEFAULT_FN_ATTRS128 __attribute__((__always_inline__, __nodebug__, __target__("avx512vl,avx512cd"), __min_vector_width__(128)))
#define __DEFAULT_FN_ATTRS256 __attribute__((__always_inline__, __nodebug__, __target__("avx512vl,avx512cd"), __min_vector_width__(256)))
Functions
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_broadcastmb_epi64 (__mmask8 __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_broadcastmb_epi64 (__mmask8 __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_broadcastmw_epi32 (__mmask16 __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_broadcastmw_epi32 (__mmask16 __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_conflict_epi64 (__m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_conflict_epi64 (__m128i __W, __mmask8 __U, __m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_conflict_epi64 (__mmask8 __U, __m128i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_conflict_epi64 (__m256i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_conflict_epi64 (__m256i __W, __mmask8 __U, __m256i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_conflict_epi64 (__mmask8 __U, __m256i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_conflict_epi32 (__m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_conflict_epi32 (__m128i __W, __mmask8 __U, __m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_conflict_epi32 (__mmask8 __U, __m128i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_conflict_epi32 (__m256i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_conflict_epi32 (__m256i __W, __mmask8 __U, __m256i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_conflict_epi32 (__mmask8 __U, __m256i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_lzcnt_epi32 (__m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_lzcnt_epi32 (__m128i __W, __mmask8 __U, __m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_lzcnt_epi32 (__mmask8 __U, __m128i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_lzcnt_epi32 (__m256i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_lzcnt_epi32 (__m256i __W, __mmask8 __U, __m256i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_lzcnt_epi32 (__mmask8 __U, __m256i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_lzcnt_epi64 (__m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_lzcnt_epi64 (__m128i __W, __mmask8 __U, __m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_lzcnt_epi64 (__mmask8 __U, __m128i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_lzcnt_epi64 (__m256i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_lzcnt_epi64 (__m256i __W, __mmask8 __U, __m256i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_lzcnt_epi64 (__mmask8 __U, __m256i __A)
Macro Definition Documentation
__DEFAULT_FN_ATTRS128
#define __DEFAULT_FN_ATTRS128 __attribute__((__always_inline__, __nodebug__, __target__("avx512vl,avx512cd"), __min_vector_width__(128)))
Definition at line 17 of file avx512vlcdintrin.h.
__DEFAULT_FN_ATTRS256
#define __DEFAULT_FN_ATTRS256 __attribute__((__always_inline__, __nodebug__, __target__("avx512vl,avx512cd"), __min_vector_width__(256)))
Definition at line 18 of file avx512vlcdintrin.h.
Function Documentation
_mm256_broadcastmb_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_broadcastmb_epi64 (__mmask8 __A) static
Definition at line 28 of file avx512vlcdintrin.h.
References _mm256_set1_epi64x().
_mm256_broadcastmw_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_broadcastmw_epi32 (__mmask16 __A) static
Definition at line 40 of file avx512vlcdintrin.h.
References _mm256_set1_epi32().
_mm256_conflict_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_conflict_epi32 (__m256i __A) static
Definition at line 113 of file avx512vlcdintrin.h.
Referenced by _mm256_mask_conflict_epi32(), and _mm256_maskz_conflict_epi32().
_mm256_conflict_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_conflict_epi64 (__m256i __A) static
Definition at line 69 of file avx512vlcdintrin.h.
Referenced by _mm256_mask_conflict_epi64(), and _mm256_maskz_conflict_epi64().
_mm256_lzcnt_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_lzcnt_epi32 (__m256i __A) static
Definition at line 157 of file avx512vlcdintrin.h.
Referenced by _mm256_mask_lzcnt_epi32(), and _mm256_maskz_lzcnt_epi32().
_mm256_lzcnt_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_lzcnt_epi64 (__m256i __A) static
Definition at line 201 of file avx512vlcdintrin.h.
Referenced by _mm256_mask_lzcnt_epi64(), and _mm256_maskz_lzcnt_epi64().
_mm256_mask_conflict_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_conflict_epi32 (__m256i __W, __mmask8 __U, __m256i __A) static
Definition at line 119 of file avx512vlcdintrin.h.
References _mm256_conflict_epi32().
_mm256_mask_conflict_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_conflict_epi64 (__m256i __W, __mmask8 __U, __m256i __A) static
Definition at line 75 of file avx512vlcdintrin.h.
References _mm256_conflict_epi64().
_mm256_mask_lzcnt_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_lzcnt_epi32 (__m256i __W, __mmask8 __U, __m256i __A) static
Definition at line 163 of file avx512vlcdintrin.h.
References _mm256_lzcnt_epi32().
_mm256_mask_lzcnt_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_lzcnt_epi64 (__m256i __W, __mmask8 __U, __m256i __A) static
Definition at line 207 of file avx512vlcdintrin.h.
References _mm256_lzcnt_epi64().
_mm256_maskz_conflict_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_conflict_epi32 (__mmask8 __U, __m256i __A) static
Definition at line 127 of file avx512vlcdintrin.h.
References _mm256_conflict_epi32(), and _mm256_setzero_si256().
_mm256_maskz_conflict_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_conflict_epi64 (__mmask8 __U, __m256i __A) static
Definition at line 83 of file avx512vlcdintrin.h.
References _mm256_conflict_epi64(), and _mm256_setzero_si256().
_mm256_maskz_lzcnt_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_lzcnt_epi32 (__mmask8 __U, __m256i __A) static
Definition at line 171 of file avx512vlcdintrin.h.
References _mm256_lzcnt_epi32(), and _mm256_setzero_si256().
_mm256_maskz_lzcnt_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_lzcnt_epi64 (__mmask8 __U, __m256i __A) static
Definition at line 215 of file avx512vlcdintrin.h.
References _mm256_lzcnt_epi64(), and _mm256_setzero_si256().
_mm_broadcastmb_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_broadcastmb_epi64 (__mmask8 __A) static
Definition at line 22 of file avx512vlcdintrin.h.
References _mm_set1_epi64x().
_mm_broadcastmw_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_broadcastmw_epi32 (__mmask16 __A) static
Definition at line 34 of file avx512vlcdintrin.h.
References _mm_set1_epi32().
_mm_conflict_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_conflict_epi32 (__m128i __A) static
Definition at line 91 of file avx512vlcdintrin.h.
Referenced by _mm_mask_conflict_epi32(), and _mm_maskz_conflict_epi32().
_mm_conflict_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_conflict_epi64 (__m128i __A) static
Definition at line 47 of file avx512vlcdintrin.h.
Referenced by _mm_mask_conflict_epi64(), and _mm_maskz_conflict_epi64().
_mm_lzcnt_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_lzcnt_epi32 (__m128i __A) static
Definition at line 135 of file avx512vlcdintrin.h.
Referenced by _mm_mask_lzcnt_epi32(), and _mm_maskz_lzcnt_epi32().
_mm_lzcnt_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_lzcnt_epi64 (__m128i __A) static
Definition at line 179 of file avx512vlcdintrin.h.
Referenced by _mm_mask_lzcnt_epi64(), and _mm_maskz_lzcnt_epi64().
_mm_mask_conflict_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_conflict_epi32 (__m128i __W, __mmask8 __U, __m128i __A) static
Definition at line 97 of file avx512vlcdintrin.h.
References _mm_conflict_epi32().
_mm_mask_conflict_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_conflict_epi64 (__m128i __W, __mmask8 __U, __m128i __A) static
Definition at line 53 of file avx512vlcdintrin.h.
References _mm_conflict_epi64().
_mm_mask_lzcnt_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_lzcnt_epi32 (__m128i __W, __mmask8 __U, __m128i __A) static
Definition at line 141 of file avx512vlcdintrin.h.
References _mm_lzcnt_epi32().
_mm_mask_lzcnt_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_lzcnt_epi64 (__m128i __W, __mmask8 __U, __m128i __A) static
Definition at line 185 of file avx512vlcdintrin.h.
References _mm_lzcnt_epi64().
_mm_maskz_conflict_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_conflict_epi32 (__mmask8 __U, __m128i __A) static
Definition at line 105 of file avx512vlcdintrin.h.
References _mm_conflict_epi32(), and _mm_setzero_si128().
_mm_maskz_conflict_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_conflict_epi64 (__mmask8 __U, __m128i __A) static
Definition at line 61 of file avx512vlcdintrin.h.
References _mm_conflict_epi64(), and _mm_setzero_si128().
_mm_maskz_lzcnt_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_lzcnt_epi32 (__mmask8 __U, __m128i __A) static
Definition at line 149 of file avx512vlcdintrin.h.
References _mm_lzcnt_epi32(), and _mm_setzero_si128().
_mm_maskz_lzcnt_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_lzcnt_epi64 (__mmask8 __U, __m128i __A) static
Definition at line 193 of file avx512vlcdintrin.h.
References _mm_lzcnt_epi64(), and _mm_setzero_si128().