ETISS 0.8.0: include/jit/clang_stdlib/avx512vbmi2intrin.h File Reference
avx512vbmi2intrin.h File Reference
Macros
#define __DEFAULT_FN_ATTRS __attribute__((__always_inline__, __nodebug__, __target__("avx512vbmi2"), __min_vector_width__(512)))
#define _mm512_shldi_epi64(A, B, I)
#define _mm512_mask_shldi_epi64(S, U, A, B, I)
#define _mm512_maskz_shldi_epi64(U, A, B, I)
#define _mm512_shldi_epi32(A, B, I)
#define _mm512_mask_shldi_epi32(S, U, A, B, I)
#define _mm512_maskz_shldi_epi32(U, A, B, I)
#define _mm512_shldi_epi16(A, B, I)
#define _mm512_mask_shldi_epi16(S, U, A, B, I)
#define _mm512_maskz_shldi_epi16(U, A, B, I)
#define _mm512_shrdi_epi64(A, B, I)
#define _mm512_mask_shrdi_epi64(S, U, A, B, I)
#define _mm512_maskz_shrdi_epi64(U, A, B, I)
#define _mm512_shrdi_epi32(A, B, I)
#define _mm512_mask_shrdi_epi32(S, U, A, B, I)
#define _mm512_maskz_shrdi_epi32(U, A, B, I)
#define _mm512_shrdi_epi16(A, B, I)
#define _mm512_mask_shrdi_epi16(S, U, A, B, I)
#define _mm512_maskz_shrdi_epi16(U, A, B, I)
Functions
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_compress_epi16 (__m512i __S, __mmask32 __U, __m512i __D)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_compress_epi16 (__mmask32 __U, __m512i __D)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_compress_epi8 (__m512i __S, __mmask64 __U, __m512i __D)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_compress_epi8 (__mmask64 __U, __m512i __D)
static __inline__ void __DEFAULT_FN_ATTRS _mm512_mask_compressstoreu_epi16 (void *__P, __mmask32 __U, __m512i __D)
static __inline__ void __DEFAULT_FN_ATTRS _mm512_mask_compressstoreu_epi8 (void *__P, __mmask64 __U, __m512i __D)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_expand_epi16 (__m512i __S, __mmask32 __U, __m512i __D)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_expand_epi16 (__mmask32 __U, __m512i __D)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_expand_epi8 (__m512i __S, __mmask64 __U, __m512i __D)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_expand_epi8 (__mmask64 __U, __m512i __D)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_expandloadu_epi16 (__m512i __S, __mmask32 __U, void const *__P)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_expandloadu_epi16 (__mmask32 __U, void const *__P)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_expandloadu_epi8 (__m512i __S, __mmask64 __U, void const *__P)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_expandloadu_epi8 (__mmask64 __U, void const *__P)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_shldv_epi64 (__m512i __A, __m512i __B, __m512i __C)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_shldv_epi64 (__m512i __A, __mmask8 __U, __m512i __B, __m512i __C)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_shldv_epi64 (__mmask8 __U, __m512i __A, __m512i __B, __m512i __C)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_shldv_epi32 (__m512i __A, __m512i __B, __m512i __C)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_shldv_epi32 (__m512i __A, __mmask16 __U, __m512i __B, __m512i __C)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_shldv_epi32 (__mmask16 __U, __m512i __A, __m512i __B, __m512i __C)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_shldv_epi16 (__m512i __A, __m512i __B, __m512i __C)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_shldv_epi16 (__m512i __A, __mmask32 __U, __m512i __B, __m512i __C)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_shldv_epi16 (__mmask32 __U, __m512i __A, __m512i __B, __m512i __C)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_shrdv_epi64 (__m512i __A, __m512i __B, __m512i __C)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_shrdv_epi64 (__m512i __A, __mmask8 __U, __m512i __B, __m512i __C)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_shrdv_epi64 (__mmask8 __U, __m512i __A, __m512i __B, __m512i __C)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_shrdv_epi32 (__m512i __A, __m512i __B, __m512i __C)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_shrdv_epi32 (__m512i __A, __mmask16 __U, __m512i __B, __m512i __C)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_shrdv_epi32 (__mmask16 __U, __m512i __A, __m512i __B, __m512i __C)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_shrdv_epi16 (__m512i __A, __m512i __B, __m512i __C)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_shrdv_epi16 (__m512i __A, __mmask32 __U, __m512i __B, __m512i __C)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_shrdv_epi16 (__mmask32 __U, __m512i __A, __m512i __B, __m512i __C)
Macro Definition Documentation
__DEFAULT_FN_ATTRS
#define __DEFAULT_FN_ATTRS __attribute__((__always_inline__, __nodebug__, __target__("avx512vbmi2"), __min_vector_width__(512)))
Definition at line 18 of file avx512vbmi2intrin.h.
_mm512_mask_shldi_epi16
#define _mm512_mask_shldi_epi16 (S, U, A, B, I)
Value:
  (__m512i)__builtin_ia32_selectw_512((__mmask32)(U), \
                                   (__v32hi)_mm512_shldi_epi16((A), (B), (I)), \
                                   (__v32hi)(__m512i)(S))
Definition at line 163 of file avx512vbmi2intrin.h.
_mm512_mask_shldi_epi32
#define _mm512_mask_shldi_epi32 (S, U, A, B, I)
Value:
  (__m512i)__builtin_ia32_selectd_512((__mmask16)(U), \
                                   (__v16si)_mm512_shldi_epi32((A), (B), (I)), \
                                   (__v16si)(__m512i)(S))
Definition at line 149 of file avx512vbmi2intrin.h.
_mm512_mask_shldi_epi64
#define _mm512_mask_shldi_epi64 (S, U, A, B, I)
Value:
  (__m512i)__builtin_ia32_selectq_512((__mmask8)(U), \
                                    (__v8di)_mm512_shldi_epi64((A), (B), (I)), \
                                    (__v8di)(__m512i)(S))
Definition at line 135 of file avx512vbmi2intrin.h.
_mm512_mask_shrdi_epi16
#define _mm512_mask_shrdi_epi16 (S, U, A, B, I)
Value:
  (__m512i)__builtin_ia32_selectw_512((__mmask32)(U), \
                                   (__v32hi)_mm512_shrdi_epi16((A), (B), (I)), \
                                   (__v32hi)(__m512i)(S))
Definition at line 205 of file avx512vbmi2intrin.h.
_mm512_mask_shrdi_epi32
#define _mm512_mask_shrdi_epi32 (S, U, A, B, I)
Value:
  (__m512i)__builtin_ia32_selectd_512((__mmask16)(U), \
                                   (__v16si)_mm512_shrdi_epi32((A), (B), (I)), \
                                   (__v16si)(__m512i)(S))
Definition at line 191 of file avx512vbmi2intrin.h.
_mm512_mask_shrdi_epi64
#define _mm512_mask_shrdi_epi64 (S, U, A, B, I)
Value:
  (__m512i)__builtin_ia32_selectq_512((__mmask8)(U), \
                                    (__v8di)_mm512_shrdi_epi64((A), (B), (I)), \
                                    (__v8di)(__m512i)(S))
Definition at line 177 of file avx512vbmi2intrin.h.
_mm512_maskz_shldi_epi16
#define _mm512_maskz_shldi_epi16 (U, A, B, I)
Value:
  (__m512i)__builtin_ia32_selectw_512((__mmask32)(U), \
                                   (__v32hi)_mm512_shldi_epi16((A), (B), (I)), \
                                   (__v32hi)_mm512_setzero_si512())
Definition at line 168 of file avx512vbmi2intrin.h.
_mm512_maskz_shldi_epi32
#define _mm512_maskz_shldi_epi32 (U, A, B, I)
Value:
  (__m512i)__builtin_ia32_selectd_512((__mmask16)(U), \
                                   (__v16si)_mm512_shldi_epi32((A), (B), (I)), \
                                   (__v16si)_mm512_setzero_si512())
Definition at line 154 of file avx512vbmi2intrin.h.
_mm512_maskz_shldi_epi64
#define _mm512_maskz_shldi_epi64 (U, A, B, I)
Value:
  (__m512i)__builtin_ia32_selectq_512((__mmask8)(U), \
                                    (__v8di)_mm512_shldi_epi64((A), (B), (I)), \
                                    (__v8di)_mm512_setzero_si512())
Definition at line 140 of file avx512vbmi2intrin.h.
_mm512_maskz_shrdi_epi16
#define _mm512_maskz_shrdi_epi16 (U, A, B, I)
Value:
  (__m512i)__builtin_ia32_selectw_512((__mmask32)(U), \
                                   (__v32hi)_mm512_shrdi_epi16((A), (B), (I)), \
                                   (__v32hi)_mm512_setzero_si512())
Definition at line 210 of file avx512vbmi2intrin.h.
_mm512_maskz_shrdi_epi32
#define _mm512_maskz_shrdi_epi32 (U, A, B, I)
Value:
  (__m512i)__builtin_ia32_selectd_512((__mmask16)(U), \
                                   (__v16si)_mm512_shrdi_epi32((A), (B), (I)), \
                                   (__v16si)_mm512_setzero_si512())
Definition at line 196 of file avx512vbmi2intrin.h.
_mm512_maskz_shrdi_epi64
#define _mm512_maskz_shrdi_epi64 (U, A, B, I)
Value:
  (__m512i)__builtin_ia32_selectq_512((__mmask8)(U), \
                                    (__v8di)_mm512_shrdi_epi64((A), (B), (I)), \
                                    (__v8di)_mm512_setzero_si512())
Definition at line 182 of file avx512vbmi2intrin.h.
_mm512_shldi_epi16
#define _mm512_shldi_epi16 (A, B, I)
Value:
  (__m512i)__builtin_ia32_vpshldw512((__v32hi)(__m512i)(A), \
                                     (__v32hi)(__m512i)(B), (int)(I))
Definition at line 159 of file avx512vbmi2intrin.h.
_mm512_shldi_epi32
#define _mm512_shldi_epi32 (A, B, I)
Value:
  (__m512i)__builtin_ia32_vpshldd512((__v16si)(__m512i)(A), \
                                     (__v16si)(__m512i)(B), (int)(I))
Definition at line 145 of file avx512vbmi2intrin.h.
_mm512_shldi_epi64
#define _mm512_shldi_epi64 (A, B, I)
Value:
  (__m512i)__builtin_ia32_vpshldq512((__v8di)(__m512i)(A), \
                                     (__v8di)(__m512i)(B), (int)(I))
Definition at line 131 of file avx512vbmi2intrin.h.
_mm512_shrdi_epi16
#define _mm512_shrdi_epi16 (A, B, I)
Value:
  (__m512i)__builtin_ia32_vpshrdw512((__v32hi)(__m512i)(A), \
                                     (__v32hi)(__m512i)(B), (int)(I))
Definition at line 201 of file avx512vbmi2intrin.h.
_mm512_shrdi_epi32
#define _mm512_shrdi_epi32 (A, B, I)
Value:
  (__m512i)__builtin_ia32_vpshrdd512((__v16si)(__m512i)(A), \
                                     (__v16si)(__m512i)(B), (int)(I))
Definition at line 187 of file avx512vbmi2intrin.h.
_mm512_shrdi_epi64
#define _mm512_shrdi_epi64 (A, B, I)
Value:
  (__m512i)__builtin_ia32_vpshrdq512((__v8di)(__m512i)(A), \
                                     (__v8di)(__m512i)(B), (int)(I))
Definition at line 173 of file avx512vbmi2intrin.h.
Function Documentation
_mm512_mask_compress_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_compress_epi16 (__m512i __S, __mmask32 __U, __m512i __D) static
Definition at line 22 of file avx512vbmi2intrin.h.
References __D.
_mm512_mask_compress_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_compress_epi8 (__m512i __S, __mmask64 __U, __m512i __D) static
Definition at line 38 of file avx512vbmi2intrin.h.
References __D.
_mm512_mask_compressstoreu_epi16()
static __inline__ void __DEFAULT_FN_ATTRS _mm512_mask_compressstoreu_epi16 (void * __P, __mmask32 __U, __m512i __D) static
Definition at line 54 of file avx512vbmi2intrin.h.
References __D.
_mm512_mask_compressstoreu_epi8()
static __inline__ void __DEFAULT_FN_ATTRS _mm512_mask_compressstoreu_epi8 (void * __P, __mmask64 __U, __m512i __D) static
Definition at line 61 of file avx512vbmi2intrin.h.
References __D.
_mm512_mask_expand_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_expand_epi16 (__m512i __S, __mmask32 __U, __m512i __D) static
Definition at line 68 of file avx512vbmi2intrin.h.
References __D.
_mm512_mask_expand_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_expand_epi8 (__m512i __S, __mmask64 __U, __m512i __D) static
Definition at line 84 of file avx512vbmi2intrin.h.
References __D.
_mm512_mask_expandloadu_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_expandloadu_epi16 (__m512i __S, __mmask32 __U, void const * __P) static
Definition at line 100 of file avx512vbmi2intrin.h.
_mm512_mask_expandloadu_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_expandloadu_epi8 (__m512i __S, __mmask64 __U, void const * __P) static
Definition at line 116 of file avx512vbmi2intrin.h.
_mm512_mask_shldv_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_shldv_epi16 (__m512i __A, __mmask32 __U, __m512i __B, __m512i __C) static
Definition at line 269 of file avx512vbmi2intrin.h.
References __C, and _mm512_shldv_epi16().
_mm512_mask_shldv_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_shldv_epi32 (__m512i __A, __mmask16 __U, __m512i __B, __m512i __C) static
Definition at line 246 of file avx512vbmi2intrin.h.
References __C, and _mm512_shldv_epi32().
_mm512_mask_shldv_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_shldv_epi64 (__m512i __A, __mmask8 __U, __m512i __B, __m512i __C) static
Definition at line 223 of file avx512vbmi2intrin.h.
References __C, and _mm512_shldv_epi64().
_mm512_mask_shrdv_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_shrdv_epi16 (__m512i __A, __mmask32 __U, __m512i __B, __m512i __C) static
Definition at line 338 of file avx512vbmi2intrin.h.
References __C, and _mm512_shrdv_epi16().
_mm512_mask_shrdv_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_shrdv_epi32 (__m512i __A, __mmask16 __U, __m512i __B, __m512i __C) static
Definition at line 315 of file avx512vbmi2intrin.h.
References __C, and _mm512_shrdv_epi32().
_mm512_mask_shrdv_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_shrdv_epi64 (__m512i __A, __mmask8 __U, __m512i __B, __m512i __C) static
Definition at line 292 of file avx512vbmi2intrin.h.
References __C, and _mm512_shrdv_epi64().
_mm512_maskz_compress_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_compress_epi16 (__mmask32 __U, __m512i __D) static
Definition at line 30 of file avx512vbmi2intrin.h.
References __D, and _mm512_setzero_si512().
_mm512_maskz_compress_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_compress_epi8 (__mmask64 __U, __m512i __D) static
Definition at line 46 of file avx512vbmi2intrin.h.
References __D, and _mm512_setzero_si512().
_mm512_maskz_expand_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_expand_epi16 (__mmask32 __U, __m512i __D) static
Definition at line 76 of file avx512vbmi2intrin.h.
References __D, and _mm512_setzero_si512().
_mm512_maskz_expand_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_expand_epi8 (__mmask64 __U, __m512i __D) static
Definition at line 92 of file avx512vbmi2intrin.h.
References __D, and _mm512_setzero_si512().
_mm512_maskz_expandloadu_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_expandloadu_epi16 (__mmask32 __U, void const * __P) static
Definition at line 108 of file avx512vbmi2intrin.h.
References _mm512_setzero_si512().
_mm512_maskz_expandloadu_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_expandloadu_epi8 (__mmask64 __U, void const * __P) static
Definition at line 124 of file avx512vbmi2intrin.h.
References _mm512_setzero_si512().
_mm512_maskz_shldv_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_shldv_epi16 (__mmask32 __U, __m512i __A, __m512i __B, __m512i __C) static
Definition at line 277 of file avx512vbmi2intrin.h.
References __C, _mm512_setzero_si512(), and _mm512_shldv_epi16().
_mm512_maskz_shldv_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_shldv_epi32 (__mmask16 __U, __m512i __A, __m512i __B, __m512i __C) static
Definition at line 254 of file avx512vbmi2intrin.h.
References __C, _mm512_setzero_si512(), and _mm512_shldv_epi32().
_mm512_maskz_shldv_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_shldv_epi64 (__mmask8 __U, __m512i __A, __m512i __B, __m512i __C) static
Definition at line 231 of file avx512vbmi2intrin.h.
References __C, _mm512_setzero_si512(), and _mm512_shldv_epi64().
_mm512_maskz_shrdv_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_shrdv_epi16 (__mmask32 __U, __m512i __A, __m512i __B, __m512i __C) static
Definition at line 346 of file avx512vbmi2intrin.h.
References __C, _mm512_setzero_si512(), and _mm512_shrdv_epi16().
_mm512_maskz_shrdv_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_shrdv_epi32 (__mmask16 __U, __m512i __A, __m512i __B, __m512i __C) static
Definition at line 323 of file avx512vbmi2intrin.h.
References __C, _mm512_setzero_si512(), and _mm512_shrdv_epi32().
_mm512_maskz_shrdv_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_shrdv_epi64 (__mmask8 __U, __m512i __A, __m512i __B, __m512i __C) static
Definition at line 300 of file avx512vbmi2intrin.h.
References __C, _mm512_setzero_si512(), and _mm512_shrdv_epi64().
_mm512_shldv_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_shldv_epi16 (__m512i __A, __m512i __B, __m512i __C) static
Definition at line 262 of file avx512vbmi2intrin.h.
References __C.
Referenced by _mm512_mask_shldv_epi16(), and _mm512_maskz_shldv_epi16().
_mm512_shldv_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_shldv_epi32 (__m512i __A, __m512i __B, __m512i __C) static
Definition at line 239 of file avx512vbmi2intrin.h.
References __C.
Referenced by _mm512_mask_shldv_epi32(), and _mm512_maskz_shldv_epi32().
_mm512_shldv_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_shldv_epi64 (__m512i __A, __m512i __B, __m512i __C) static
Definition at line 216 of file avx512vbmi2intrin.h.
References __C.
Referenced by _mm512_mask_shldv_epi64(), and _mm512_maskz_shldv_epi64().
_mm512_shrdv_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_shrdv_epi16 (__m512i __A, __m512i __B, __m512i __C) static
Definition at line 331 of file avx512vbmi2intrin.h.
References __C.
Referenced by _mm512_mask_shrdv_epi16(), and _mm512_maskz_shrdv_epi16().
_mm512_shrdv_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_shrdv_epi32 (__m512i __A, __m512i __B, __m512i __C) static
Definition at line 308 of file avx512vbmi2intrin.h.
References __C.
Referenced by _mm512_mask_shrdv_epi32(), and _mm512_maskz_shrdv_epi32().
_mm512_shrdv_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_shrdv_epi64 (__m512i __A, __m512i __B, __m512i __C) static
Definition at line 285 of file avx512vbmi2intrin.h.
References __C.
Referenced by _mm512_mask_shrdv_epi64(), and _mm512_maskz_shrdv_epi64().