ETISS 0.8.0: include/jit/clang_stdlib/avx512vnniintrin.h File Reference
avx512vnniintrin.h File Reference
Macros
#define __DEFAULT_FN_ATTRS __attribute__((__always_inline__, __nodebug__, __target__("avx512vnni"), __min_vector_width__(512)))
Functions
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_dpbusd_epi32 (__m512i __S, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_dpbusd_epi32 (__m512i __S, __mmask16 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_dpbusd_epi32 (__mmask16 __U, __m512i __S, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_dpbusds_epi32 (__m512i __S, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_dpbusds_epi32 (__m512i __S, __mmask16 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_dpbusds_epi32 (__mmask16 __U, __m512i __S, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_dpwssd_epi32 (__m512i __S, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_dpwssd_epi32 (__m512i __S, __mmask16 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_dpwssd_epi32 (__mmask16 __U, __m512i __S, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_dpwssds_epi32 (__m512i __S, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_dpwssds_epi32 (__m512i __S, __mmask16 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_dpwssds_epi32 (__mmask16 __U, __m512i __S, __m512i __A, __m512i __B)
Macro Definition Documentation
__DEFAULT_FN_ATTRS
#define __DEFAULT_FN_ATTRS __attribute__((__always_inline__, __nodebug__, __target__("avx512vnni"), __min_vector_width__(512)))
Definition at line 18 of file avx512vnniintrin.h.
Function Documentation
_mm512_dpbusd_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_dpbusd_epi32 (__m512i __S, __m512i __A, __m512i __B) static
Definition at line 22 of file avx512vnniintrin.h.
Referenced by _mm512_mask_dpbusd_epi32(), and _mm512_maskz_dpbusd_epi32().
_mm512_dpbusds_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_dpbusds_epi32 (__m512i __S, __m512i __A, __m512i __B) static
Definition at line 45 of file avx512vnniintrin.h.
Referenced by _mm512_mask_dpbusds_epi32(), and _mm512_maskz_dpbusds_epi32().
_mm512_dpwssd_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_dpwssd_epi32 (__m512i __S, __m512i __A, __m512i __B) static
Definition at line 68 of file avx512vnniintrin.h.
Referenced by _mm512_mask_dpwssd_epi32(), and _mm512_maskz_dpwssd_epi32().
_mm512_dpwssds_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_dpwssds_epi32 (__m512i __S, __m512i __A, __m512i __B) static
Definition at line 91 of file avx512vnniintrin.h.
Referenced by _mm512_mask_dpwssds_epi32(), and _mm512_maskz_dpwssds_epi32().
_mm512_mask_dpbusd_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_dpbusd_epi32 (__m512i __S, __mmask16 __U, __m512i __A, __m512i __B) static
Definition at line 29 of file avx512vnniintrin.h.
References _mm512_dpbusd_epi32().
_mm512_mask_dpbusds_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_dpbusds_epi32 (__m512i __S, __mmask16 __U, __m512i __A, __m512i __B) static
Definition at line 52 of file avx512vnniintrin.h.
References _mm512_dpbusds_epi32().
_mm512_mask_dpwssd_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_dpwssd_epi32 (__m512i __S, __mmask16 __U, __m512i __A, __m512i __B) static
Definition at line 75 of file avx512vnniintrin.h.
References _mm512_dpwssd_epi32().
_mm512_mask_dpwssds_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_dpwssds_epi32 (__m512i __S, __mmask16 __U, __m512i __A, __m512i __B) static
Definition at line 98 of file avx512vnniintrin.h.
References _mm512_dpwssds_epi32().
_mm512_maskz_dpbusd_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_dpbusd_epi32 (__mmask16 __U, __m512i __S, __m512i __A, __m512i __B) static
Definition at line 37 of file avx512vnniintrin.h.
References _mm512_dpbusd_epi32(), and _mm512_setzero_si512().
_mm512_maskz_dpbusds_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_dpbusds_epi32 (__mmask16 __U, __m512i __S, __m512i __A, __m512i __B) static
Definition at line 60 of file avx512vnniintrin.h.
References _mm512_dpbusds_epi32(), and _mm512_setzero_si512().
_mm512_maskz_dpwssd_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_dpwssd_epi32 (__mmask16 __U, __m512i __S, __m512i __A, __m512i __B) static
Definition at line 83 of file avx512vnniintrin.h.
References _mm512_dpwssd_epi32(), and _mm512_setzero_si512().
_mm512_maskz_dpwssds_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_dpwssds_epi32 (__mmask16 __U, __m512i __S, __m512i __A, __m512i __B) static
Definition at line 106 of file avx512vnniintrin.h.
References _mm512_dpwssds_epi32(), and _mm512_setzero_si512().