ETISS 0.8.0: include/jit/clang_stdlib/avx512vlvbmi2intrin.h File Reference
avx512vlvbmi2intrin.h File Reference
Macros
#define __DEFAULT_FN_ATTRS128 __attribute__((__always_inline__, __nodebug__, __target__("avx512vl,avx512vbmi2"), __min_vector_width__(128)))
#define __DEFAULT_FN_ATTRS256 __attribute__((__always_inline__, __nodebug__, __target__("avx512vl,avx512vbmi2"), __min_vector_width__(256)))
#define _mm256_shldi_epi64(A, B, I)
#define _mm256_mask_shldi_epi64(S, U, A, B, I)
#define _mm256_maskz_shldi_epi64(U, A, B, I)
#define _mm_shldi_epi64(A, B, I)
#define _mm_mask_shldi_epi64(S, U, A, B, I)
#define _mm_maskz_shldi_epi64(U, A, B, I)
#define _mm256_shldi_epi32(A, B, I)
#define _mm256_mask_shldi_epi32(S, U, A, B, I)
#define _mm256_maskz_shldi_epi32(U, A, B, I)
#define _mm_shldi_epi32(A, B, I)
#define _mm_mask_shldi_epi32(S, U, A, B, I)
#define _mm_maskz_shldi_epi32(U, A, B, I)
#define _mm256_shldi_epi16(A, B, I)
#define _mm256_mask_shldi_epi16(S, U, A, B, I)
#define _mm256_maskz_shldi_epi16(U, A, B, I)
#define _mm_shldi_epi16(A, B, I)
#define _mm_mask_shldi_epi16(S, U, A, B, I)
#define _mm_maskz_shldi_epi16(U, A, B, I)
#define _mm256_shrdi_epi64(A, B, I)
#define _mm256_mask_shrdi_epi64(S, U, A, B, I)
#define _mm256_maskz_shrdi_epi64(U, A, B, I)
#define _mm_shrdi_epi64(A, B, I)
#define _mm_mask_shrdi_epi64(S, U, A, B, I)
#define _mm_maskz_shrdi_epi64(U, A, B, I)
#define _mm256_shrdi_epi32(A, B, I)
#define _mm256_mask_shrdi_epi32(S, U, A, B, I)
#define _mm256_maskz_shrdi_epi32(U, A, B, I)
#define _mm_shrdi_epi32(A, B, I)
#define _mm_mask_shrdi_epi32(S, U, A, B, I)
#define _mm_maskz_shrdi_epi32(U, A, B, I)
#define _mm256_shrdi_epi16(A, B, I)
#define _mm256_mask_shrdi_epi16(S, U, A, B, I)
#define _mm256_maskz_shrdi_epi16(U, A, B, I)
#define _mm_shrdi_epi16(A, B, I)
#define _mm_mask_shrdi_epi16(S, U, A, B, I)
#define _mm_maskz_shrdi_epi16(U, A, B, I)
Functions
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_compress_epi16 (__m128i __S, __mmask8 __U, __m128i __D)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_compress_epi16 (__mmask8 __U, __m128i __D)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_compress_epi8 (__m128i __S, __mmask16 __U, __m128i __D)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_compress_epi8 (__mmask16 __U, __m128i __D)
static __inline__ void __DEFAULT_FN_ATTRS128 _mm_mask_compressstoreu_epi16 (void *__P, __mmask8 __U, __m128i __D)
static __inline__ void __DEFAULT_FN_ATTRS128 _mm_mask_compressstoreu_epi8 (void *__P, __mmask16 __U, __m128i __D)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_expand_epi16 (__m128i __S, __mmask8 __U, __m128i __D)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_expand_epi16 (__mmask8 __U, __m128i __D)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_expand_epi8 (__m128i __S, __mmask16 __U, __m128i __D)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_expand_epi8 (__mmask16 __U, __m128i __D)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_expandloadu_epi16 (__m128i __S, __mmask8 __U, void const *__P)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_expandloadu_epi16 (__mmask8 __U, void const *__P)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_expandloadu_epi8 (__m128i __S, __mmask16 __U, void const *__P)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_expandloadu_epi8 (__mmask16 __U, void const *__P)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_compress_epi16 (__m256i __S, __mmask16 __U, __m256i __D)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_compress_epi16 (__mmask16 __U, __m256i __D)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_compress_epi8 (__m256i __S, __mmask32 __U, __m256i __D)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_compress_epi8 (__mmask32 __U, __m256i __D)
static __inline__ void __DEFAULT_FN_ATTRS256 _mm256_mask_compressstoreu_epi16 (void *__P, __mmask16 __U, __m256i __D)
static __inline__ void __DEFAULT_FN_ATTRS256 _mm256_mask_compressstoreu_epi8 (void *__P, __mmask32 __U, __m256i __D)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_expand_epi16 (__m256i __S, __mmask16 __U, __m256i __D)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_expand_epi16 (__mmask16 __U, __m256i __D)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_expand_epi8 (__m256i __S, __mmask32 __U, __m256i __D)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_expand_epi8 (__mmask32 __U, __m256i __D)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_expandloadu_epi16 (__m256i __S, __mmask16 __U, void const *__P)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_expandloadu_epi16 (__mmask16 __U, void const *__P)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_expandloadu_epi8 (__m256i __S, __mmask32 __U, void const *__P)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_expandloadu_epi8 (__mmask32 __U, void const *__P)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_shldv_epi64 (__m256i __A, __m256i __B, __m256i __C)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_shldv_epi64 (__m256i __A, __mmask8 __U, __m256i __B, __m256i __C)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_shldv_epi64 (__mmask8 __U, __m256i __A, __m256i __B, __m256i __C)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_shldv_epi64 (__m128i __A, __m128i __B, __m128i __C)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_shldv_epi64 (__m128i __A, __mmask8 __U, __m128i __B, __m128i __C)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_shldv_epi64 (__mmask8 __U, __m128i __A, __m128i __B, __m128i __C)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_shldv_epi32 (__m256i __A, __m256i __B, __m256i __C)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_shldv_epi32 (__m256i __A, __mmask8 __U, __m256i __B, __m256i __C)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_shldv_epi32 (__mmask8 __U, __m256i __A, __m256i __B, __m256i __C)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_shldv_epi32 (__m128i __A, __m128i __B, __m128i __C)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_shldv_epi32 (__m128i __A, __mmask8 __U, __m128i __B, __m128i __C)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_shldv_epi32 (__mmask8 __U, __m128i __A, __m128i __B, __m128i __C)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_shldv_epi16 (__m256i __A, __m256i __B, __m256i __C)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_shldv_epi16 (__m256i __A, __mmask16 __U, __m256i __B, __m256i __C)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_shldv_epi16 (__mmask16 __U, __m256i __A, __m256i __B, __m256i __C)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_shldv_epi16 (__m128i __A, __m128i __B, __m128i __C)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_shldv_epi16 (__m128i __A, __mmask8 __U, __m128i __B, __m128i __C)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_shldv_epi16 (__mmask8 __U, __m128i __A, __m128i __B, __m128i __C)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_shrdv_epi64 (__m256i __A, __m256i __B, __m256i __C)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_shrdv_epi64 (__m256i __A, __mmask8 __U, __m256i __B, __m256i __C)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_shrdv_epi64 (__mmask8 __U, __m256i __A, __m256i __B, __m256i __C)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_shrdv_epi64 (__m128i __A, __m128i __B, __m128i __C)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_shrdv_epi64 (__m128i __A, __mmask8 __U, __m128i __B, __m128i __C)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_shrdv_epi64 (__mmask8 __U, __m128i __A, __m128i __B, __m128i __C)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_shrdv_epi32 (__m256i __A, __m256i __B, __m256i __C)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_shrdv_epi32 (__m256i __A, __mmask8 __U, __m256i __B, __m256i __C)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_shrdv_epi32 (__mmask8 __U, __m256i __A, __m256i __B, __m256i __C)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_shrdv_epi32 (__m128i __A, __m128i __B, __m128i __C)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_shrdv_epi32 (__m128i __A, __mmask8 __U, __m128i __B, __m128i __C)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_shrdv_epi32 (__mmask8 __U, __m128i __A, __m128i __B, __m128i __C)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_shrdv_epi16 (__m256i __A, __m256i __B, __m256i __C)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_shrdv_epi16 (__m256i __A, __mmask16 __U, __m256i __B, __m256i __C)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_shrdv_epi16 (__mmask16 __U, __m256i __A, __m256i __B, __m256i __C)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_shrdv_epi16 (__m128i __A, __m128i __B, __m128i __C)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_shrdv_epi16 (__m128i __A, __mmask8 __U, __m128i __B, __m128i __C)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_shrdv_epi16 (__mmask8 __U, __m128i __A, __m128i __B, __m128i __C)
Macro Definition Documentation
__DEFAULT_FN_ATTRS128
#define __DEFAULT_FN_ATTRS128 __attribute__((__always_inline__, __nodebug__, __target__("avx512vl,avx512vbmi2"), __min_vector_width__(128)))
Definition at line 18 of file avx512vlvbmi2intrin.h.
__DEFAULT_FN_ATTRS256
#define __DEFAULT_FN_ATTRS256 __attribute__((__always_inline__, __nodebug__, __target__("avx512vl,avx512vbmi2"), __min_vector_width__(256)))
Definition at line 19 of file avx512vlvbmi2intrin.h.
_mm256_mask_shldi_epi16
#define _mm256_mask_shldi_epi16 (S, U, A, B, I)
Value:
  (__m256i)__builtin_ia32_selectw_256((__mmask16)(U), \
                                   (__v16hi)_mm256_shldi_epi16((A), (B), (I)), \
                                   (__v16hi)(__m256i)(S))
Definition at line 301 of file avx512vlvbmi2intrin.h.
_mm256_mask_shldi_epi32
#define _mm256_mask_shldi_epi32 (S, U, A, B, I)
Value:
  (__m256i)__builtin_ia32_selectd_256((__mmask8)(U), \
                                    (__v8si)_mm256_shldi_epi32((A), (B), (I)), \
                                    (__v8si)(__m256i)(S))
Definition at line 273 of file avx512vlvbmi2intrin.h.
_mm256_mask_shldi_epi64
#define _mm256_mask_shldi_epi64 (S, U, A, B, I)
Value:
  (__m256i)__builtin_ia32_selectq_256((__mmask8)(U), \
                                    (__v4di)_mm256_shldi_epi64((A), (B), (I)), \
                                    (__v4di)(__m256i)(S))
Definition at line 245 of file avx512vlvbmi2intrin.h.
_mm256_mask_shrdi_epi16
#define _mm256_mask_shrdi_epi16 (S, U, A, B, I)
Value:
  (__m256i)__builtin_ia32_selectw_256((__mmask16)(U), \
                                   (__v16hi)_mm256_shrdi_epi16((A), (B), (I)), \
                                   (__v16hi)(__m256i)(S))
Definition at line 385 of file avx512vlvbmi2intrin.h.
_mm256_mask_shrdi_epi32
#define _mm256_mask_shrdi_epi32 (S, U, A, B, I)
Value:
  (__m256i)__builtin_ia32_selectd_256((__mmask8)(U), \
                                    (__v8si)_mm256_shrdi_epi32((A), (B), (I)), \
                                    (__v8si)(__m256i)(S))
Definition at line 357 of file avx512vlvbmi2intrin.h.
_mm256_mask_shrdi_epi64
#define _mm256_mask_shrdi_epi64 (S, U, A, B, I)
Value:
  (__m256i)__builtin_ia32_selectq_256((__mmask8)(U), \
                                    (__v4di)_mm256_shrdi_epi64((A), (B), (I)), \
                                    (__v4di)(__m256i)(S))
Definition at line 329 of file avx512vlvbmi2intrin.h.
_mm256_maskz_shldi_epi16
#define _mm256_maskz_shldi_epi16 (U, A, B, I)
Value:
  (__m256i)__builtin_ia32_selectw_256((__mmask16)(U), \
                                   (__v16hi)_mm256_shldi_epi16((A), (B), (I)), \
                                   (__v16hi)_mm256_setzero_si256())
Definition at line 306 of file avx512vlvbmi2intrin.h.
_mm256_maskz_shldi_epi32
#define _mm256_maskz_shldi_epi32 (U, A, B, I)
Value:
  (__m256i)__builtin_ia32_selectd_256((__mmask8)(U), \
                                    (__v8si)_mm256_shldi_epi32((A), (B), (I)), \
                                    (__v8si)_mm256_setzero_si256())
Definition at line 278 of file avx512vlvbmi2intrin.h.
_mm256_maskz_shldi_epi64
#define _mm256_maskz_shldi_epi64 (U, A, B, I)
Value:
  (__m256i)__builtin_ia32_selectq_256((__mmask8)(U), \
                                    (__v4di)_mm256_shldi_epi64((A), (B), (I)), \
                                    (__v4di)_mm256_setzero_si256())
Definition at line 250 of file avx512vlvbmi2intrin.h.
_mm256_maskz_shrdi_epi16
#define _mm256_maskz_shrdi_epi16 (U, A, B, I)
Value:
  (__m256i)__builtin_ia32_selectw_256((__mmask16)(U), \
                                   (__v16hi)_mm256_shrdi_epi16((A), (B), (I)), \
                                   (__v16hi)_mm256_setzero_si256())
Definition at line 390 of file avx512vlvbmi2intrin.h.
_mm256_maskz_shrdi_epi32
#define _mm256_maskz_shrdi_epi32 (U, A, B, I)
Value:
  (__m256i)__builtin_ia32_selectd_256((__mmask8)(U), \
                                    (__v8si)_mm256_shrdi_epi32((A), (B), (I)), \
                                    (__v8si)_mm256_setzero_si256())
Definition at line 362 of file avx512vlvbmi2intrin.h.
_mm256_maskz_shrdi_epi64
#define _mm256_maskz_shrdi_epi64 (U, A, B, I)
Value:
  (__m256i)__builtin_ia32_selectq_256((__mmask8)(U), \
                                    (__v4di)_mm256_shrdi_epi64((A), (B), (I)), \
                                    (__v4di)_mm256_setzero_si256())
Definition at line 334 of file avx512vlvbmi2intrin.h.
_mm256_shldi_epi16
#define _mm256_shldi_epi16 (A, B, I)
Value:
  (__m256i)__builtin_ia32_vpshldw256((__v16hi)(__m256i)(A), \
                                     (__v16hi)(__m256i)(B), (int)(I))
Definition at line 297 of file avx512vlvbmi2intrin.h.
_mm256_shldi_epi32
#define _mm256_shldi_epi32 (A, B, I)
Value:
  (__m256i)__builtin_ia32_vpshldd256((__v8si)(__m256i)(A), \
                                     (__v8si)(__m256i)(B), (int)(I))
Definition at line 269 of file avx512vlvbmi2intrin.h.
_mm256_shldi_epi64
#define _mm256_shldi_epi64 (A, B, I)
Value:
  (__m256i)__builtin_ia32_vpshldq256((__v4di)(__m256i)(A), \
                                     (__v4di)(__m256i)(B), (int)(I))
Definition at line 241 of file avx512vlvbmi2intrin.h.
_mm256_shrdi_epi16
#define _mm256_shrdi_epi16 (A, B, I)
Value:
  (__m256i)__builtin_ia32_vpshrdw256((__v16hi)(__m256i)(A), \
                                     (__v16hi)(__m256i)(B), (int)(I))
Definition at line 381 of file avx512vlvbmi2intrin.h.
_mm256_shrdi_epi32
#define _mm256_shrdi_epi32 (A, B, I)
Value:
  (__m256i)__builtin_ia32_vpshrdd256((__v8si)(__m256i)(A), \
                                     (__v8si)(__m256i)(B), (int)(I))
Definition at line 353 of file avx512vlvbmi2intrin.h.
_mm256_shrdi_epi64
#define _mm256_shrdi_epi64 (A, B, I)
Value:
  (__m256i)__builtin_ia32_vpshrdq256((__v4di)(__m256i)(A), \
                                     (__v4di)(__m256i)(B), (int)(I))
Definition at line 325 of file avx512vlvbmi2intrin.h.
_mm_mask_shldi_epi16
#define _mm_mask_shldi_epi16 (S, U, A, B, I)
Value:
  (__m128i)__builtin_ia32_selectw_128((__mmask8)(U), \
                                      (__v8hi)_mm_shldi_epi16((A), (B), (I)), \
                                      (__v8hi)(__m128i)(S))
Definition at line 315 of file avx512vlvbmi2intrin.h.
_mm_mask_shldi_epi32
#define _mm_mask_shldi_epi32 (S, U, A, B, I)
Value:
  (__m128i)__builtin_ia32_selectd_128((__mmask8)(U), \
                                      (__v4si)_mm_shldi_epi32((A), (B), (I)), \
                                      (__v4si)(__m128i)(S))
Definition at line 287 of file avx512vlvbmi2intrin.h.
_mm_mask_shldi_epi64
#define _mm_mask_shldi_epi64 (S, U, A, B, I)
Value:
  (__m128i)__builtin_ia32_selectq_128((__mmask8)(U), \
                                      (__v2di)_mm_shldi_epi64((A), (B), (I)), \
                                      (__v2di)(__m128i)(S))
Definition at line 259 of file avx512vlvbmi2intrin.h.
_mm_mask_shrdi_epi16
#define _mm_mask_shrdi_epi16 (S, U, A, B, I)
Value:
  (__m128i)__builtin_ia32_selectw_128((__mmask8)(U), \
                                      (__v8hi)_mm_shrdi_epi16((A), (B), (I)), \
                                      (__v8hi)(__m128i)(S))
Definition at line 399 of file avx512vlvbmi2intrin.h.
_mm_mask_shrdi_epi32
#define _mm_mask_shrdi_epi32 (S, U, A, B, I)
Value:
  (__m128i)__builtin_ia32_selectd_128((__mmask8)(U), \
                                      (__v4si)_mm_shrdi_epi32((A), (B), (I)), \
                                      (__v4si)(__m128i)(S))
Definition at line 371 of file avx512vlvbmi2intrin.h.
_mm_mask_shrdi_epi64
#define _mm_mask_shrdi_epi64 (S, U, A, B, I)
Value:
  (__m128i)__builtin_ia32_selectq_128((__mmask8)(U), \
                                      (__v2di)_mm_shrdi_epi64((A), (B), (I)), \
                                      (__v2di)(__m128i)(S))
Definition at line 343 of file avx512vlvbmi2intrin.h.
_mm_maskz_shldi_epi16
#define _mm_maskz_shldi_epi16 (U, A, B, I)
Value:
  (__m128i)__builtin_ia32_selectw_128((__mmask8)(U), \
                                      (__v8hi)_mm_shldi_epi16((A), (B), (I)), \
                                      (__v8hi)_mm_setzero_si128())
Definition at line 320 of file avx512vlvbmi2intrin.h.
_mm_maskz_shldi_epi32
#define _mm_maskz_shldi_epi32 (U, A, B, I)
Value:
  (__m128i)__builtin_ia32_selectd_128((__mmask8)(U), \
                                      (__v4si)_mm_shldi_epi32((A), (B), (I)), \
                                      (__v4si)_mm_setzero_si128())
Definition at line 292 of file avx512vlvbmi2intrin.h.
_mm_maskz_shldi_epi64
#define _mm_maskz_shldi_epi64 (U, A, B, I)
Value:
  (__m128i)__builtin_ia32_selectq_128((__mmask8)(U), \
                                      (__v2di)_mm_shldi_epi64((A), (B), (I)), \
                                      (__v2di)_mm_setzero_si128())
Definition at line 264 of file avx512vlvbmi2intrin.h.
_mm_maskz_shrdi_epi16
#define _mm_maskz_shrdi_epi16 (U, A, B, I)
Value:
  (__m128i)__builtin_ia32_selectw_128((__mmask8)(U), \
                                      (__v8hi)_mm_shrdi_epi16((A), (B), (I)), \
                                      (__v8hi)_mm_setzero_si128())
Definition at line 404 of file avx512vlvbmi2intrin.h.
_mm_maskz_shrdi_epi32
#define _mm_maskz_shrdi_epi32 (U, A, B, I)
Value:
  (__m128i)__builtin_ia32_selectd_128((__mmask8)(U), \
                                      (__v4si)_mm_shrdi_epi32((A), (B), (I)), \
                                      (__v4si)_mm_setzero_si128())
Definition at line 376 of file avx512vlvbmi2intrin.h.
_mm_maskz_shrdi_epi64
#define _mm_maskz_shrdi_epi64 (U, A, B, I)
Value:
  (__m128i)__builtin_ia32_selectq_128((__mmask8)(U), \
                                      (__v2di)_mm_shrdi_epi64((A), (B), (I)), \
                                      (__v2di)_mm_setzero_si128())
Definition at line 348 of file avx512vlvbmi2intrin.h.
_mm_shldi_epi16
#define _mm_shldi_epi16 (A, B, I)
Value:
  (__m128i)__builtin_ia32_vpshldw128((__v8hi)(__m128i)(A), \
                                     (__v8hi)(__m128i)(B), (int)(I))
Definition at line 311 of file avx512vlvbmi2intrin.h.
_mm_shldi_epi32
#define _mm_shldi_epi32 (A, B, I)
Value:
  (__m128i)__builtin_ia32_vpshldd128((__v4si)(__m128i)(A), \
                                     (__v4si)(__m128i)(B), (int)(I))
Definition at line 283 of file avx512vlvbmi2intrin.h.
_mm_shldi_epi64
#define _mm_shldi_epi64 (A, B, I)
Value:
  (__m128i)__builtin_ia32_vpshldq128((__v2di)(__m128i)(A), \
                                     (__v2di)(__m128i)(B), (int)(I))
Definition at line 255 of file avx512vlvbmi2intrin.h.
_mm_shrdi_epi16
#define _mm_shrdi_epi16 (A, B, I)
Value:
  (__m128i)__builtin_ia32_vpshrdw128((__v8hi)(__m128i)(A), \
                                     (__v8hi)(__m128i)(B), (int)(I))
Definition at line 395 of file avx512vlvbmi2intrin.h.
_mm_shrdi_epi32
#define _mm_shrdi_epi32 (A, B, I)
Value:
  (__m128i)__builtin_ia32_vpshrdd128((__v4si)(__m128i)(A), \
                                     (__v4si)(__m128i)(B), (int)(I))
Definition at line 367 of file avx512vlvbmi2intrin.h.
_mm_shrdi_epi64
#define _mm_shrdi_epi64 (A, B, I)
Value:
  (__m128i)__builtin_ia32_vpshrdq128((__v2di)(__m128i)(A), \
                                     (__v2di)(__m128i)(B), (int)(I))
Definition at line 339 of file avx512vlvbmi2intrin.h.
Function Documentation
_mm256_mask_compress_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_compress_epi16 (__m256i __S, __mmask16 __U, __m256i __D) static
Definition at line 132 of file avx512vlvbmi2intrin.h.
References __D.
_mm256_mask_compress_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_compress_epi8 (__m256i __S, __mmask32 __U, __m256i __D) static
Definition at line 148 of file avx512vlvbmi2intrin.h.
References __D.
_mm256_mask_compressstoreu_epi16()
static __inline__ void __DEFAULT_FN_ATTRS256 _mm256_mask_compressstoreu_epi16 (void * __P, __mmask16 __U, __m256i __D) static
Definition at line 164 of file avx512vlvbmi2intrin.h.
References __D.
_mm256_mask_compressstoreu_epi8()
static __inline__ void __DEFAULT_FN_ATTRS256 _mm256_mask_compressstoreu_epi8 (void * __P, __mmask32 __U, __m256i __D) static
Definition at line 171 of file avx512vlvbmi2intrin.h.
References __D.
_mm256_mask_expand_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_expand_epi16 (__m256i __S, __mmask16 __U, __m256i __D) static
Definition at line 178 of file avx512vlvbmi2intrin.h.
References __D.
_mm256_mask_expand_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_expand_epi8 (__m256i __S, __mmask32 __U, __m256i __D) static
Definition at line 194 of file avx512vlvbmi2intrin.h.
References __D.
_mm256_mask_expandloadu_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_expandloadu_epi16 (__m256i __S, __mmask16 __U, void const * __P) static
Definition at line 210 of file avx512vlvbmi2intrin.h.
_mm256_mask_expandloadu_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_expandloadu_epi8 (__m256i __S, __mmask32 __U, void const * __P) static
Definition at line 226 of file avx512vlvbmi2intrin.h.
_mm256_mask_shldv_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_shldv_epi16 (__m256i __A, __mmask16 __U, __m256i __B, __m256i __C) static
Definition at line 509 of file avx512vlvbmi2intrin.h.
References __C, and _mm256_shldv_epi16().
_mm256_mask_shldv_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_shldv_epi32 (__m256i __A, __mmask8 __U, __m256i __B, __m256i __C) static
Definition at line 463 of file avx512vlvbmi2intrin.h.
References __C, and _mm256_shldv_epi32().
_mm256_mask_shldv_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_shldv_epi64 (__m256i __A, __mmask8 __U, __m256i __B, __m256i __C) static
Definition at line 417 of file avx512vlvbmi2intrin.h.
References __C, and _mm256_shldv_epi64().
_mm256_mask_shrdv_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_shrdv_epi16 (__m256i __A, __mmask16 __U, __m256i __B, __m256i __C) static
Definition at line 647 of file avx512vlvbmi2intrin.h.
References __C, and _mm256_shrdv_epi16().
_mm256_mask_shrdv_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_shrdv_epi32 (__m256i __A, __mmask8 __U, __m256i __B, __m256i __C) static
Definition at line 601 of file avx512vlvbmi2intrin.h.
References __C, and _mm256_shrdv_epi32().
_mm256_mask_shrdv_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_shrdv_epi64 (__m256i __A, __mmask8 __U, __m256i __B, __m256i __C) static
Definition at line 555 of file avx512vlvbmi2intrin.h.
References __C, and _mm256_shrdv_epi64().
_mm256_maskz_compress_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_compress_epi16 (__mmask16 __U, __m256i __D) static
Definition at line 140 of file avx512vlvbmi2intrin.h.
References __D, and _mm256_setzero_si256().
_mm256_maskz_compress_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_compress_epi8 (__mmask32 __U, __m256i __D) static
Definition at line 156 of file avx512vlvbmi2intrin.h.
References __D, and _mm256_setzero_si256().
_mm256_maskz_expand_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_expand_epi16 (__mmask16 __U, __m256i __D) static
Definition at line 186 of file avx512vlvbmi2intrin.h.
References __D, and _mm256_setzero_si256().
_mm256_maskz_expand_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_expand_epi8 (__mmask32 __U, __m256i __D) static
Definition at line 202 of file avx512vlvbmi2intrin.h.
References __D, and _mm256_setzero_si256().
_mm256_maskz_expandloadu_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_expandloadu_epi16 (__mmask16 __U, void const * __P) static
Definition at line 218 of file avx512vlvbmi2intrin.h.
References _mm256_setzero_si256().
_mm256_maskz_expandloadu_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_expandloadu_epi8 (__mmask32 __U, void const * __P) static
Definition at line 234 of file avx512vlvbmi2intrin.h.
References _mm256_setzero_si256().
_mm256_maskz_shldv_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_shldv_epi16 (__mmask16 __U, __m256i __A, __m256i __B, __m256i __C) static
Definition at line 517 of file avx512vlvbmi2intrin.h.
References __C, _mm256_setzero_si256(), and _mm256_shldv_epi16().
_mm256_maskz_shldv_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_shldv_epi32 (__mmask8 __U, __m256i __A, __m256i __B, __m256i __C) static
Definition at line 471 of file avx512vlvbmi2intrin.h.
References __C, _mm256_setzero_si256(), and _mm256_shldv_epi32().
_mm256_maskz_shldv_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_shldv_epi64 (__mmask8 __U, __m256i __A, __m256i __B, __m256i __C) static
Definition at line 425 of file avx512vlvbmi2intrin.h.
References __C, _mm256_setzero_si256(), and _mm256_shldv_epi64().
_mm256_maskz_shrdv_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_shrdv_epi16 (__mmask16 __U, __m256i __A, __m256i __B, __m256i __C) static
Definition at line 655 of file avx512vlvbmi2intrin.h.
References __C, _mm256_setzero_si256(), and _mm256_shrdv_epi16().
_mm256_maskz_shrdv_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_shrdv_epi32 (__mmask8 __U, __m256i __A, __m256i __B, __m256i __C) static
Definition at line 609 of file avx512vlvbmi2intrin.h.
References __C, _mm256_setzero_si256(), and _mm256_shrdv_epi32().
_mm256_maskz_shrdv_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_shrdv_epi64 (__mmask8 __U, __m256i __A, __m256i __B, __m256i __C) static
Definition at line 563 of file avx512vlvbmi2intrin.h.
References __C, _mm256_setzero_si256(), and _mm256_shrdv_epi64().
_mm256_shldv_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_shldv_epi16 (__m256i __A, __m256i __B, __m256i __C) static
Definition at line 502 of file avx512vlvbmi2intrin.h.
References __C.
Referenced by _mm256_mask_shldv_epi16(), and _mm256_maskz_shldv_epi16().
_mm256_shldv_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_shldv_epi32 (__m256i __A, __m256i __B, __m256i __C) static
Definition at line 456 of file avx512vlvbmi2intrin.h.
References __C.
Referenced by _mm256_mask_shldv_epi32(), and _mm256_maskz_shldv_epi32().
_mm256_shldv_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_shldv_epi64 (__m256i __A, __m256i __B, __m256i __C) static
Definition at line 410 of file avx512vlvbmi2intrin.h.
References __C.
Referenced by _mm256_mask_shldv_epi64(), and _mm256_maskz_shldv_epi64().
_mm256_shrdv_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_shrdv_epi16 (__m256i __A, __m256i __B, __m256i __C) static
Definition at line 640 of file avx512vlvbmi2intrin.h.
References __C.
Referenced by _mm256_mask_shrdv_epi16(), and _mm256_maskz_shrdv_epi16().
_mm256_shrdv_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_shrdv_epi32 (__m256i __A, __m256i __B, __m256i __C) static
Definition at line 594 of file avx512vlvbmi2intrin.h.
References __C.
Referenced by _mm256_mask_shrdv_epi32(), and _mm256_maskz_shrdv_epi32().
_mm256_shrdv_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_shrdv_epi64 (__m256i __A, __m256i __B, __m256i __C) static
Definition at line 548 of file avx512vlvbmi2intrin.h.
References __C.
Referenced by _mm256_mask_shrdv_epi64(), and _mm256_maskz_shrdv_epi64().
_mm_mask_compress_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_compress_epi16 (__m128i __S, __mmask8 __U, __m128i __D) static
Definition at line 22 of file avx512vlvbmi2intrin.h.
References __D.
_mm_mask_compress_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_compress_epi8 (__m128i __S, __mmask16 __U, __m128i __D) static
Definition at line 38 of file avx512vlvbmi2intrin.h.
References __D.
_mm_mask_compressstoreu_epi16()
static __inline__ void __DEFAULT_FN_ATTRS128 _mm_mask_compressstoreu_epi16 (void * __P, __mmask8 __U, __m128i __D) static
Definition at line 54 of file avx512vlvbmi2intrin.h.
References __D.
_mm_mask_compressstoreu_epi8()
static __inline__ void __DEFAULT_FN_ATTRS128 _mm_mask_compressstoreu_epi8 (void * __P, __mmask16 __U, __m128i __D) static
Definition at line 61 of file avx512vlvbmi2intrin.h.
References __D.
_mm_mask_expand_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_expand_epi16 (__m128i __S, __mmask8 __U, __m128i __D) static
Definition at line 68 of file avx512vlvbmi2intrin.h.
References __D.
_mm_mask_expand_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_expand_epi8 (__m128i __S, __mmask16 __U, __m128i __D) static
Definition at line 84 of file avx512vlvbmi2intrin.h.
References __D.
_mm_mask_expandloadu_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_expandloadu_epi16 (__m128i __S, __mmask8 __U, void const * __P) static
Definition at line 100 of file avx512vlvbmi2intrin.h.
_mm_mask_expandloadu_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_expandloadu_epi8 (__m128i __S, __mmask16 __U, void const * __P) static
Definition at line 116 of file avx512vlvbmi2intrin.h.
_mm_mask_shldv_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_shldv_epi16 (__m128i __A, __mmask8 __U, __m128i __B, __m128i __C) static
Definition at line 532 of file avx512vlvbmi2intrin.h.
References __C, and _mm_shldv_epi16().
_mm_mask_shldv_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_shldv_epi32 (__m128i __A, __mmask8 __U, __m128i __B, __m128i __C) static
Definition at line 486 of file avx512vlvbmi2intrin.h.
References __C, and _mm_shldv_epi32().
_mm_mask_shldv_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_shldv_epi64 (__m128i __A, __mmask8 __U, __m128i __B, __m128i __C) static
Definition at line 440 of file avx512vlvbmi2intrin.h.
References __C, and _mm_shldv_epi64().
_mm_mask_shrdv_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_shrdv_epi16 (__m128i __A, __mmask8 __U, __m128i __B, __m128i __C) static
Definition at line 670 of file avx512vlvbmi2intrin.h.
References __C, and _mm_shrdv_epi16().
_mm_mask_shrdv_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_shrdv_epi32 (__m128i __A, __mmask8 __U, __m128i __B, __m128i __C) static
Definition at line 624 of file avx512vlvbmi2intrin.h.
References __C, and _mm_shrdv_epi32().
_mm_mask_shrdv_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_shrdv_epi64 (__m128i __A, __mmask8 __U, __m128i __B, __m128i __C) static
Definition at line 578 of file avx512vlvbmi2intrin.h.
References __C, and _mm_shrdv_epi64().
_mm_maskz_compress_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_compress_epi16 (__mmask8 __U, __m128i __D) static
Definition at line 30 of file avx512vlvbmi2intrin.h.
References __D, and _mm_setzero_si128().
_mm_maskz_compress_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_compress_epi8 (__mmask16 __U, __m128i __D) static
Definition at line 46 of file avx512vlvbmi2intrin.h.
References __D, and _mm_setzero_si128().
_mm_maskz_expand_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_expand_epi16 (__mmask8 __U, __m128i __D) static
Definition at line 76 of file avx512vlvbmi2intrin.h.
References __D, and _mm_setzero_si128().
_mm_maskz_expand_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_expand_epi8 (__mmask16 __U, __m128i __D) static
Definition at line 92 of file avx512vlvbmi2intrin.h.
References __D, and _mm_setzero_si128().
_mm_maskz_expandloadu_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_expandloadu_epi16 (__mmask8 __U, void const * __P) static
Definition at line 108 of file avx512vlvbmi2intrin.h.
References _mm_setzero_si128().
_mm_maskz_expandloadu_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_expandloadu_epi8 (__mmask16 __U, void const * __P) static
Definition at line 124 of file avx512vlvbmi2intrin.h.
References _mm_setzero_si128().
_mm_maskz_shldv_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_shldv_epi16 (__mmask8 __U, __m128i __A, __m128i __B, __m128i __C) static
Definition at line 540 of file avx512vlvbmi2intrin.h.
References __C, _mm_setzero_si128(), and _mm_shldv_epi16().
_mm_maskz_shldv_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_shldv_epi32 (__mmask8 __U, __m128i __A, __m128i __B, __m128i __C) static
Definition at line 494 of file avx512vlvbmi2intrin.h.
References __C, _mm_setzero_si128(), and _mm_shldv_epi32().
_mm_maskz_shldv_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_shldv_epi64 (__mmask8 __U, __m128i __A, __m128i __B, __m128i __C) static
Definition at line 448 of file avx512vlvbmi2intrin.h.
References __C, _mm_setzero_si128(), and _mm_shldv_epi64().
_mm_maskz_shrdv_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_shrdv_epi16 (__mmask8 __U, __m128i __A, __m128i __B, __m128i __C) static
Definition at line 678 of file avx512vlvbmi2intrin.h.
References __C, _mm_setzero_si128(), and _mm_shrdv_epi16().
_mm_maskz_shrdv_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_shrdv_epi32 (__mmask8 __U, __m128i __A, __m128i __B, __m128i __C) static
Definition at line 632 of file avx512vlvbmi2intrin.h.
References __C, _mm_setzero_si128(), and _mm_shrdv_epi32().
_mm_maskz_shrdv_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_shrdv_epi64 (__mmask8 __U, __m128i __A, __m128i __B, __m128i __C) static
Definition at line 586 of file avx512vlvbmi2intrin.h.
References __C, _mm_setzero_si128(), and _mm_shrdv_epi64().
_mm_shldv_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_shldv_epi16 (__m128i __A, __m128i __B, __m128i __C) static
Definition at line 525 of file avx512vlvbmi2intrin.h.
References __C.
Referenced by _mm_mask_shldv_epi16(), and _mm_maskz_shldv_epi16().
_mm_shldv_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_shldv_epi32 (__m128i __A, __m128i __B, __m128i __C) static
Definition at line 479 of file avx512vlvbmi2intrin.h.
References __C.
Referenced by _mm_mask_shldv_epi32(), and _mm_maskz_shldv_epi32().
_mm_shldv_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_shldv_epi64 (__m128i __A, __m128i __B, __m128i __C) static
Definition at line 433 of file avx512vlvbmi2intrin.h.
References __C.
Referenced by _mm_mask_shldv_epi64(), and _mm_maskz_shldv_epi64().
_mm_shrdv_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_shrdv_epi16 (__m128i __A, __m128i __B, __m128i __C) static
Definition at line 663 of file avx512vlvbmi2intrin.h.
References __C.
Referenced by _mm_mask_shrdv_epi16(), and _mm_maskz_shrdv_epi16().
_mm_shrdv_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_shrdv_epi32 (__m128i __A, __m128i __B, __m128i __C) static
Definition at line 617 of file avx512vlvbmi2intrin.h.
References __C.
Referenced by _mm_mask_shrdv_epi32(), and _mm_maskz_shrdv_epi32().
_mm_shrdv_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_shrdv_epi64 (__m128i __A, __m128i __B, __m128i __C) static
Definition at line 571 of file avx512vlvbmi2intrin.h.
References __C.
Referenced by _mm_mask_shrdv_epi64(), and _mm_maskz_shrdv_epi64().