ETISS 0.8.0: include/jit/clang_stdlib/avx512cdintrin.h File Reference
avx512cdintrin.h File Reference
Macros
#define __DEFAULT_FN_ATTRS __attribute__((__always_inline__, __nodebug__, __target__("avx512cd"), __min_vector_width__(512)))
Functions
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_conflict_epi64 (__m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_conflict_epi64 (__m512i __W, __mmask8 __U, __m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_conflict_epi64 (__mmask8 __U, __m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_conflict_epi32 (__m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_conflict_epi32 (__m512i __W, __mmask16 __U, __m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_conflict_epi32 (__mmask16 __U, __m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_lzcnt_epi32 (__m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_lzcnt_epi32 (__m512i __W, __mmask16 __U, __m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_lzcnt_epi32 (__mmask16 __U, __m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_lzcnt_epi64 (__m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_lzcnt_epi64 (__m512i __W, __mmask8 __U, __m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_lzcnt_epi64 (__mmask8 __U, __m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_broadcastmb_epi64 (__mmask8 __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_broadcastmw_epi32 (__mmask16 __A)
Macro Definition Documentation
__DEFAULT_FN_ATTRS
#define __DEFAULT_FN_ATTRS __attribute__((__always_inline__, __nodebug__, __target__("avx512cd"), __min_vector_width__(512)))
Definition at line 18 of file avx512cdintrin.h.
Function Documentation
_mm512_broadcastmb_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_broadcastmb_epi64 (__mmask8 __A) static
Definition at line 109 of file avx512cdintrin.h.
References _mm512_set1_epi64().
_mm512_broadcastmw_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_broadcastmw_epi32 (__mmask16 __A) static
Definition at line 115 of file avx512cdintrin.h.
References _mm512_set1_epi32().
_mm512_conflict_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_conflict_epi32 (__m512i __A) static
Definition at line 43 of file avx512cdintrin.h.
Referenced by _mm512_mask_conflict_epi32(), and _mm512_maskz_conflict_epi32().
_mm512_conflict_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_conflict_epi64 (__m512i __A) static
Definition at line 21 of file avx512cdintrin.h.
Referenced by _mm512_mask_conflict_epi64(), and _mm512_maskz_conflict_epi64().
_mm512_lzcnt_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_lzcnt_epi32 (__m512i __A) static
Definition at line 65 of file avx512cdintrin.h.
Referenced by _mm512_mask_lzcnt_epi32(), and _mm512_maskz_lzcnt_epi32().
_mm512_lzcnt_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_lzcnt_epi64 (__m512i __A) static
Definition at line 87 of file avx512cdintrin.h.
Referenced by _mm512_mask_lzcnt_epi64(), and _mm512_maskz_lzcnt_epi64().
_mm512_mask_conflict_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_conflict_epi32 (__m512i __W, __mmask16 __U, __m512i __A) static
Definition at line 49 of file avx512cdintrin.h.
References _mm512_conflict_epi32().
_mm512_mask_conflict_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_conflict_epi64 (__m512i __W, __mmask8 __U, __m512i __A) static
Definition at line 27 of file avx512cdintrin.h.
References _mm512_conflict_epi64().
_mm512_mask_lzcnt_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_lzcnt_epi32 (__m512i __W, __mmask16 __U, __m512i __A) static
Definition at line 71 of file avx512cdintrin.h.
References _mm512_lzcnt_epi32().
_mm512_mask_lzcnt_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_lzcnt_epi64 (__m512i __W, __mmask8 __U, __m512i __A) static
Definition at line 93 of file avx512cdintrin.h.
References _mm512_lzcnt_epi64().
_mm512_maskz_conflict_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_conflict_epi32 (__mmask16 __U, __m512i __A) static
Definition at line 57 of file avx512cdintrin.h.
References _mm512_conflict_epi32(), and _mm512_setzero_si512().
_mm512_maskz_conflict_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_conflict_epi64 (__mmask8 __U, __m512i __A) static
Definition at line 35 of file avx512cdintrin.h.
References _mm512_conflict_epi64(), and _mm512_setzero_si512().
_mm512_maskz_lzcnt_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_lzcnt_epi32 (__mmask16 __U, __m512i __A) static
Definition at line 79 of file avx512cdintrin.h.
References _mm512_lzcnt_epi32(), and _mm512_setzero_si512().
_mm512_maskz_lzcnt_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_lzcnt_epi64 (__mmask8 __U, __m512i __A) static
Definition at line 101 of file avx512cdintrin.h.
References _mm512_lzcnt_epi64(), and _mm512_setzero_si512().