ETISS 0.8.0: include/jit/clang_stdlib/avx512dqintrin.h File Reference
avx512dqintrin.h File Reference
Macros
#define __DEFAULT_FN_ATTRS512 __attribute__((__always_inline__, __nodebug__, __target__("avx512dq"), __min_vector_width__(512)))
#define __DEFAULT_FN_ATTRS __attribute__((__always_inline__, __nodebug__, __target__("avx512dq")))
#define _kshiftli_mask8(A, I) (__mmask8)__builtin_ia32_kshiftliqi((__mmask8)(A), (unsigned int)(I))
#define _kshiftri_mask8(A, I) (__mmask8)__builtin_ia32_kshiftriqi((__mmask8)(A), (unsigned int)(I))
#define _mm512_cvt_roundpd_epi64(A, R)
#define _mm512_mask_cvt_roundpd_epi64(W, U, A, R)
#define _mm512_maskz_cvt_roundpd_epi64(U, A, R)
#define _mm512_cvt_roundpd_epu64(A, R)
#define _mm512_mask_cvt_roundpd_epu64(W, U, A, R)
#define _mm512_maskz_cvt_roundpd_epu64(U, A, R)
#define _mm512_cvt_roundps_epi64(A, R)
#define _mm512_mask_cvt_roundps_epi64(W, U, A, R)
#define _mm512_maskz_cvt_roundps_epi64(U, A, R)
#define _mm512_cvt_roundps_epu64(A, R)
#define _mm512_mask_cvt_roundps_epu64(W, U, A, R)
#define _mm512_maskz_cvt_roundps_epu64(U, A, R)
#define _mm512_cvt_roundepi64_pd(A, R)
#define _mm512_mask_cvt_roundepi64_pd(W, U, A, R)
#define _mm512_maskz_cvt_roundepi64_pd(U, A, R)
#define _mm512_cvt_roundepi64_ps(A, R)
#define _mm512_mask_cvt_roundepi64_ps(W, U, A, R)
#define _mm512_maskz_cvt_roundepi64_ps(U, A, R)
#define _mm512_cvtt_roundpd_epi64(A, R)
#define _mm512_mask_cvtt_roundpd_epi64(W, U, A, R)
#define _mm512_maskz_cvtt_roundpd_epi64(U, A, R)
#define _mm512_cvtt_roundpd_epu64(A, R)
#define _mm512_mask_cvtt_roundpd_epu64(W, U, A, R)
#define _mm512_maskz_cvtt_roundpd_epu64(U, A, R)
#define _mm512_cvtt_roundps_epi64(A, R)
#define _mm512_mask_cvtt_roundps_epi64(W, U, A, R)
#define _mm512_maskz_cvtt_roundps_epi64(U, A, R)
#define _mm512_cvtt_roundps_epu64(A, R)
#define _mm512_mask_cvtt_roundps_epu64(W, U, A, R)
#define _mm512_maskz_cvtt_roundps_epu64(U, A, R)
#define _mm512_cvt_roundepu64_pd(A, R)
#define _mm512_mask_cvt_roundepu64_pd(W, U, A, R)
#define _mm512_maskz_cvt_roundepu64_pd(U, A, R)
#define _mm512_cvt_roundepu64_ps(A, R)
#define _mm512_mask_cvt_roundepu64_ps(W, U, A, R)
#define _mm512_maskz_cvt_roundepu64_ps(U, A, R)
#define _mm512_range_pd(A, B, C)
#define _mm512_mask_range_pd(W, U, A, B, C)
#define _mm512_maskz_range_pd(U, A, B, C)
#define _mm512_range_round_pd(A, B, C, R)
#define _mm512_mask_range_round_pd(W, U, A, B, C, R)
#define _mm512_maskz_range_round_pd(U, A, B, C, R)
#define _mm512_range_ps(A, B, C)
#define _mm512_mask_range_ps(W, U, A, B, C)
#define _mm512_maskz_range_ps(U, A, B, C)
#define _mm512_range_round_ps(A, B, C, R)
#define _mm512_mask_range_round_ps(W, U, A, B, C, R)
#define _mm512_maskz_range_round_ps(U, A, B, C, R)
#define _mm_range_round_ss(A, B, C, R)
#define _mm_range_ss(A, B, C) _mm_range_round_ss(A, B, C ,_MM_FROUND_CUR_DIRECTION)
#define _mm_mask_range_round_ss(W, U, A, B, C, R)
#define _mm_mask_range_ss(W, U, A, B, C) _mm_mask_range_round_ss(W, U, A, B, C , _MM_FROUND_CUR_DIRECTION)
#define _mm_maskz_range_round_ss(U, A, B, C, R)
#define _mm_maskz_range_ss(U, A, B, C) _mm_maskz_range_round_ss(U, A, B, C ,_MM_FROUND_CUR_DIRECTION)
#define _mm_range_round_sd(A, B, C, R)
#define _mm_range_sd(A, B, C) _mm_range_round_sd(A, B, C ,_MM_FROUND_CUR_DIRECTION)
#define _mm_mask_range_round_sd(W, U, A, B, C, R)
#define _mm_mask_range_sd(W, U, A, B, C) _mm_mask_range_round_sd(W, U, A, B, C ,_MM_FROUND_CUR_DIRECTION)
#define _mm_maskz_range_round_sd(U, A, B, C, R)
#define _mm_maskz_range_sd(U, A, B, C) _mm_maskz_range_round_sd(U, A, B, C ,_MM_FROUND_CUR_DIRECTION)
#define _mm512_reduce_pd(A, B)
#define _mm512_mask_reduce_pd(W, U, A, B)
#define _mm512_maskz_reduce_pd(U, A, B)
#define _mm512_reduce_ps(A, B)
#define _mm512_mask_reduce_ps(W, U, A, B)
#define _mm512_maskz_reduce_ps(U, A, B)
#define _mm512_reduce_round_pd(A, B, R)
#define _mm512_mask_reduce_round_pd(W, U, A, B, R)
#define _mm512_maskz_reduce_round_pd(U, A, B, R)
#define _mm512_reduce_round_ps(A, B, R)
#define _mm512_mask_reduce_round_ps(W, U, A, B, R)
#define _mm512_maskz_reduce_round_ps(U, A, B, R)
#define _mm_reduce_ss(A, B, C)
#define _mm_mask_reduce_ss(W, U, A, B, C)
#define _mm_maskz_reduce_ss(U, A, B, C)
#define _mm_reduce_round_ss(A, B, C, R)
#define _mm_mask_reduce_round_ss(W, U, A, B, C, R)
#define _mm_maskz_reduce_round_ss(U, A, B, C, R)
#define _mm_reduce_sd(A, B, C)
#define _mm_mask_reduce_sd(W, U, A, B, C)
#define _mm_maskz_reduce_sd(U, A, B, C)
#define _mm_reduce_round_sd(A, B, C, R)
#define _mm_mask_reduce_round_sd(W, U, A, B, C, R)
#define _mm_maskz_reduce_round_sd(U, A, B, C, R)
#define _mm512_extractf32x8_ps(A, imm)
#define _mm512_mask_extractf32x8_ps(W, U, A, imm)
#define _mm512_maskz_extractf32x8_ps(U, A, imm)
#define _mm512_extractf64x2_pd(A, imm)
#define _mm512_mask_extractf64x2_pd(W, U, A, imm)
#define _mm512_maskz_extractf64x2_pd(U, A, imm)
#define _mm512_extracti32x8_epi32(A, imm)
#define _mm512_mask_extracti32x8_epi32(W, U, A, imm)
#define _mm512_maskz_extracti32x8_epi32(U, A, imm)
#define _mm512_extracti64x2_epi64(A, imm)
#define _mm512_mask_extracti64x2_epi64(W, U, A, imm)
#define _mm512_maskz_extracti64x2_epi64(U, A, imm)
#define _mm512_insertf32x8(A, B, imm)
#define _mm512_mask_insertf32x8(W, U, A, B, imm)
#define _mm512_maskz_insertf32x8(U, A, B, imm)
#define _mm512_insertf64x2(A, B, imm)
#define _mm512_mask_insertf64x2(W, U, A, B, imm)
#define _mm512_maskz_insertf64x2(U, A, B, imm)
#define _mm512_inserti32x8(A, B, imm)
#define _mm512_mask_inserti32x8(W, U, A, B, imm)
#define _mm512_maskz_inserti32x8(U, A, B, imm)
#define _mm512_inserti64x2(A, B, imm)
#define _mm512_mask_inserti64x2(W, U, A, B, imm)
#define _mm512_maskz_inserti64x2(U, A, B, imm)
#define _mm512_mask_fpclass_ps_mask(U, A, imm)
#define _mm512_fpclass_ps_mask(A, imm)
#define _mm512_mask_fpclass_pd_mask(U, A, imm)
#define _mm512_fpclass_pd_mask(A, imm)
#define _mm_fpclass_sd_mask(A, imm)
#define _mm_mask_fpclass_sd_mask(U, A, imm)
#define _mm_fpclass_ss_mask(A, imm)
#define _mm_mask_fpclass_ss_mask(U, A, imm)
Functions
static __inline __mmask8 __DEFAULT_FN_ATTRS _knot_mask8 (__mmask8 __M)
static __inline__ __mmask8 __DEFAULT_FN_ATTRS _kand_mask8 (__mmask8 __A, __mmask8 __B)
static __inline__ __mmask8 __DEFAULT_FN_ATTRS _kandn_mask8 (__mmask8 __A, __mmask8 __B)
static __inline__ __mmask8 __DEFAULT_FN_ATTRS _kor_mask8 (__mmask8 __A, __mmask8 __B)
static __inline__ __mmask8 __DEFAULT_FN_ATTRS _kxnor_mask8 (__mmask8 __A, __mmask8 __B)
static __inline__ __mmask8 __DEFAULT_FN_ATTRS _kxor_mask8 (__mmask8 __A, __mmask8 __B)
static __inline__ unsigned char __DEFAULT_FN_ATTRS _kortestc_mask8_u8 (__mmask8 __A, __mmask8 __B)
static __inline__ unsigned char __DEFAULT_FN_ATTRS _kortestz_mask8_u8 (__mmask8 __A, __mmask8 __B)
static __inline__ unsigned char __DEFAULT_FN_ATTRS _kortest_mask8_u8 (__mmask8 __A, __mmask8 __B, unsigned char *__C)
static __inline__ unsigned char __DEFAULT_FN_ATTRS _ktestc_mask8_u8 (__mmask8 __A, __mmask8 __B)
static __inline__ unsigned char __DEFAULT_FN_ATTRS _ktestz_mask8_u8 (__mmask8 __A, __mmask8 __B)
static __inline__ unsigned char __DEFAULT_FN_ATTRS _ktest_mask8_u8 (__mmask8 __A, __mmask8 __B, unsigned char *__C)
static __inline__ unsigned char __DEFAULT_FN_ATTRS _ktestc_mask16_u8 (__mmask16 __A, __mmask16 __B)
static __inline__ unsigned char __DEFAULT_FN_ATTRS _ktestz_mask16_u8 (__mmask16 __A, __mmask16 __B)
static __inline__ unsigned char __DEFAULT_FN_ATTRS _ktest_mask16_u8 (__mmask16 __A, __mmask16 __B, unsigned char *__C)
static __inline__ __mmask8 __DEFAULT_FN_ATTRS _kadd_mask8 (__mmask8 __A, __mmask8 __B)
static __inline__ __mmask16 __DEFAULT_FN_ATTRS _kadd_mask16 (__mmask16 __A, __mmask16 __B)
static __inline__ unsigned int __DEFAULT_FN_ATTRS _cvtmask8_u32 (__mmask8 __A)
static __inline__ __mmask8 __DEFAULT_FN_ATTRS _cvtu32_mask8 (unsigned int __A)
static __inline__ __mmask8 __DEFAULT_FN_ATTRS _load_mask8 (__mmask8 *__A)
static __inline__ void __DEFAULT_FN_ATTRS _store_mask8 (__mmask8 *__A, __mmask8 __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mullo_epi64 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_mullo_epi64 (__m512i __W, __mmask8 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_mullo_epi64 (__mmask8 __U, __m512i __A, __m512i __B)
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_xor_pd (__m512d __A, __m512d __B)
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_mask_xor_pd (__m512d __W, __mmask8 __U, __m512d __A, __m512d __B)
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_maskz_xor_pd (__mmask8 __U, __m512d __A, __m512d __B)
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_xor_ps (__m512 __A, __m512 __B)
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_mask_xor_ps (__m512 __W, __mmask16 __U, __m512 __A, __m512 __B)
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_maskz_xor_ps (__mmask16 __U, __m512 __A, __m512 __B)
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_or_pd (__m512d __A, __m512d __B)
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_mask_or_pd (__m512d __W, __mmask8 __U, __m512d __A, __m512d __B)
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_maskz_or_pd (__mmask8 __U, __m512d __A, __m512d __B)
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_or_ps (__m512 __A, __m512 __B)
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_mask_or_ps (__m512 __W, __mmask16 __U, __m512 __A, __m512 __B)
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_maskz_or_ps (__mmask16 __U, __m512 __A, __m512 __B)
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_and_pd (__m512d __A, __m512d __B)
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_mask_and_pd (__m512d __W, __mmask8 __U, __m512d __A, __m512d __B)
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_maskz_and_pd (__mmask8 __U, __m512d __A, __m512d __B)
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_and_ps (__m512 __A, __m512 __B)
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_mask_and_ps (__m512 __W, __mmask16 __U, __m512 __A, __m512 __B)
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_maskz_and_ps (__mmask16 __U, __m512 __A, __m512 __B)
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_andnot_pd (__m512d __A, __m512d __B)
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_mask_andnot_pd (__m512d __W, __mmask8 __U, __m512d __A, __m512d __B)
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_maskz_andnot_pd (__mmask8 __U, __m512d __A, __m512d __B)
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_andnot_ps (__m512 __A, __m512 __B)
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_mask_andnot_ps (__m512 __W, __mmask16 __U, __m512 __A, __m512 __B)
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_maskz_andnot_ps (__mmask16 __U, __m512 __A, __m512 __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvtpd_epi64 (__m512d __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvtpd_epi64 (__m512i __W, __mmask8 __U, __m512d __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtpd_epi64 (__mmask8 __U, __m512d __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvtpd_epu64 (__m512d __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvtpd_epu64 (__m512i __W, __mmask8 __U, __m512d __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtpd_epu64 (__mmask8 __U, __m512d __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvtps_epi64 (__m256 __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvtps_epi64 (__m512i __W, __mmask8 __U, __m256 __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtps_epi64 (__mmask8 __U, __m256 __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvtps_epu64 (__m256 __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvtps_epu64 (__m512i __W, __mmask8 __U, __m256 __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtps_epu64 (__mmask8 __U, __m256 __A)
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_cvtepi64_pd (__m512i __A)
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_mask_cvtepi64_pd (__m512d __W, __mmask8 __U, __m512i __A)
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtepi64_pd (__mmask8 __U, __m512i __A)
static __inline__ __m256 __DEFAULT_FN_ATTRS512 _mm512_cvtepi64_ps (__m512i __A)
static __inline__ __m256 __DEFAULT_FN_ATTRS512 _mm512_mask_cvtepi64_ps (__m256 __W, __mmask8 __U, __m512i __A)
static __inline__ __m256 __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtepi64_ps (__mmask8 __U, __m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvttpd_epi64 (__m512d __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvttpd_epi64 (__m512i __W, __mmask8 __U, __m512d __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvttpd_epi64 (__mmask8 __U, __m512d __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvttpd_epu64 (__m512d __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvttpd_epu64 (__m512i __W, __mmask8 __U, __m512d __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvttpd_epu64 (__mmask8 __U, __m512d __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvttps_epi64 (__m256 __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvttps_epi64 (__m512i __W, __mmask8 __U, __m256 __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvttps_epi64 (__mmask8 __U, __m256 __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvttps_epu64 (__m256 __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvttps_epu64 (__m512i __W, __mmask8 __U, __m256 __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvttps_epu64 (__mmask8 __U, __m256 __A)
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_cvtepu64_pd (__m512i __A)
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_mask_cvtepu64_pd (__m512d __W, __mmask8 __U, __m512i __A)
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtepu64_pd (__mmask8 __U, __m512i __A)
static __inline__ __m256 __DEFAULT_FN_ATTRS512 _mm512_cvtepu64_ps (__m512i __A)
static __inline__ __m256 __DEFAULT_FN_ATTRS512 _mm512_mask_cvtepu64_ps (__m256 __W, __mmask8 __U, __m512i __A)
static __inline__ __m256 __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtepu64_ps (__mmask8 __U, __m512i __A)
static __inline__ __mmask16 __DEFAULT_FN_ATTRS512 _mm512_movepi32_mask (__m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_movm_epi32 (__mmask16 __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_movm_epi64 (__mmask8 __A)
static __inline__ __mmask8 __DEFAULT_FN_ATTRS512 _mm512_movepi64_mask (__m512i __A)
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_broadcast_f32x2 (__m128 __A)
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_mask_broadcast_f32x2 (__m512 __O, __mmask16 __M, __m128 __A)
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_maskz_broadcast_f32x2 (__mmask16 __M, __m128 __A)
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_broadcast_f32x8 (__m256 __A)
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_mask_broadcast_f32x8 (__m512 __O, __mmask16 __M, __m256 __A)
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_maskz_broadcast_f32x8 (__mmask16 __M, __m256 __A)
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_broadcast_f64x2 (__m128d __A)
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_mask_broadcast_f64x2 (__m512d __O, __mmask8 __M, __m128d __A)
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_maskz_broadcast_f64x2 (__mmask8 __M, __m128d __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_broadcast_i32x2 (__m128i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_broadcast_i32x2 (__m512i __O, __mmask16 __M, __m128i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_broadcast_i32x2 (__mmask16 __M, __m128i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_broadcast_i32x8 (__m256i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_broadcast_i32x8 (__m512i __O, __mmask16 __M, __m256i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_broadcast_i32x8 (__mmask16 __M, __m256i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_broadcast_i64x2 (__m128i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_broadcast_i64x2 (__m512i __O, __mmask8 __M, __m128i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_broadcast_i64x2 (__mmask8 __M, __m128i __A)
Macro Definition Documentation
__DEFAULT_FN_ATTRS
#define __DEFAULT_FN_ATTRS __attribute__((__always_inline__, __nodebug__, __target__("avx512dq")))
Definition at line 19 of file avx512dqintrin.h.
__DEFAULT_FN_ATTRS512
#define __DEFAULT_FN_ATTRS512 __attribute__((__always_inline__, __nodebug__, __target__("avx512dq"), __min_vector_width__(512)))
Definition at line 18 of file avx512dqintrin.h.
_kshiftli_mask8
#define _kshiftli_mask8 (A, I) (__mmask8)__builtin_ia32_kshiftliqi((__mmask8)(A), (unsigned int)(I))
Definition at line 123 of file avx512dqintrin.h.
_kshiftri_mask8
#define _kshiftri_mask8 (A, I) (__mmask8)__builtin_ia32_kshiftriqi((__mmask8)(A), (unsigned int)(I))
Definition at line 126 of file avx512dqintrin.h.
_mm512_cvt_roundepi64_pd
#define _mm512_cvt_roundepi64_pd (A, R)
Value:
  (__m512d)__builtin_ia32_cvtqq2pd512_mask((__v8di)(__m512i)(A), \
                                           (__v8df)_mm512_setzero_pd(), \
                                           (__mmask8)-1, (int)(R))
Definition at line 496 of file avx512dqintrin.h.
_mm512_cvt_roundepi64_ps
#define _mm512_cvt_roundepi64_ps (A, R)
Value:
  (__m256)__builtin_ia32_cvtqq2ps512_mask((__v8di)(__m512i)(A), \
                                          (__v8sf)_mm256_setzero_ps(), \
                                          (__mmask8)-1, (int)(R))
Definition at line 535 of file avx512dqintrin.h.
_mm512_cvt_roundepu64_pd
#define _mm512_cvt_roundepu64_pd (A, R)
Value:
  (__m512d)__builtin_ia32_cvtuqq2pd512_mask((__v8di)(__m512i)(A), \
                                            (__v8df)_mm512_setzero_pd(), \
                                            (__mmask8)-1, (int)(R))
Definition at line 726 of file avx512dqintrin.h.
_mm512_cvt_roundepu64_ps
#define _mm512_cvt_roundepu64_ps (A, R)
Value:
  (__m256)__builtin_ia32_cvtuqq2ps512_mask((__v8di)(__m512i)(A), \
                                           (__v8sf)_mm256_setzero_ps(), \
                                           (__mmask8)-1, (int)(R))
Definition at line 767 of file avx512dqintrin.h.
_mm512_cvt_roundpd_epi64
#define _mm512_cvt_roundpd_epi64 (A, R)
Value:
  (__m512i)__builtin_ia32_cvtpd2qq512_mask((__v8df)(__m512d)(A), \
                                           (__v8di)_mm512_setzero_si512(), \
                                           (__mmask8)-1, (int)(R))
Definition at line 344 of file avx512dqintrin.h.
_mm512_cvt_roundpd_epu64
#define _mm512_cvt_roundpd_epu64 (A, R)
Value:
  (__m512i)__builtin_ia32_cvtpd2uqq512_mask((__v8df)(__m512d)(A), \
                                            (__v8di)_mm512_setzero_si512(), \
                                            (__mmask8)-1, (int)(R))
Definition at line 383 of file avx512dqintrin.h.
_mm512_cvt_roundps_epi64
#define _mm512_cvt_roundps_epi64 (A, R)
Value:
  (__m512i)__builtin_ia32_cvtps2qq512_mask((__v8sf)(__m256)(A), \
                                           (__v8di)_mm512_setzero_si512(), \
                                           (__mmask8)-1, (int)(R))
Definition at line 422 of file avx512dqintrin.h.
_mm512_cvt_roundps_epu64
#define _mm512_cvt_roundps_epu64 (A, R)
Value:
  (__m512i)__builtin_ia32_cvtps2uqq512_mask((__v8sf)(__m256)(A), \
                                            (__v8di)_mm512_setzero_si512(), \
                                            (__mmask8)-1, (int)(R))
Definition at line 461 of file avx512dqintrin.h.
_mm512_cvtt_roundpd_epi64
#define _mm512_cvtt_roundpd_epi64 (A, R)
Value:
  (__m512i)__builtin_ia32_cvttpd2qq512_mask((__v8df)(__m512d)(A), \
                                            (__v8di)_mm512_setzero_si512(), \
                                            (__mmask8)-1, (int)(R))
Definition at line 575 of file avx512dqintrin.h.
_mm512_cvtt_roundpd_epu64
#define _mm512_cvtt_roundpd_epu64 (A, R)
Value:
  (__m512i)__builtin_ia32_cvttpd2uqq512_mask((__v8df)(__m512d)(A), \
                                             (__v8di)_mm512_setzero_si512(), \
                                             (__mmask8)-1, (int)(R))
Definition at line 614 of file avx512dqintrin.h.
_mm512_cvtt_roundps_epi64
#define _mm512_cvtt_roundps_epi64 (A, R)
Value:
  (__m512i)__builtin_ia32_cvttps2qq512_mask((__v8sf)(__m256)(A), \
                                            (__v8di)_mm512_setzero_si512(), \
                                            (__mmask8)-1, (int)(R))
Definition at line 653 of file avx512dqintrin.h.
_mm512_cvtt_roundps_epu64
#define _mm512_cvtt_roundps_epu64 (A, R)
Value:
  (__m512i)__builtin_ia32_cvttps2uqq512_mask((__v8sf)(__m256)(A), \
                                             (__v8di)_mm512_setzero_si512(), \
                                             (__mmask8)-1, (int)(R))
Definition at line 692 of file avx512dqintrin.h.
_mm512_extractf32x8_ps
#define _mm512_extractf32x8_ps (A, imm)
Value:
  (__m256)__builtin_ia32_extractf32x8_mask((__v16sf)(__m512)(A), (int)(imm), \
                                           (__v8sf)_mm256_undefined_ps(), \
                                           (__mmask8)-1)
Definition at line 1220 of file avx512dqintrin.h.
_mm512_extractf64x2_pd
#define _mm512_extractf64x2_pd (A, imm)
Value:
  (__m128d)__builtin_ia32_extractf64x2_512_mask((__v8df)(__m512d)(A), \
                                                (int)(imm), \
                                                (__v2df)_mm_undefined_pd(), \
                                                (__mmask8)-1)
Definition at line 1235 of file avx512dqintrin.h.
_mm512_extracti32x8_epi32
#define _mm512_extracti32x8_epi32 (A, imm)
Value:
  (__m256i)__builtin_ia32_extracti32x8_mask((__v16si)(__m512i)(A), (int)(imm), \
                                            (__v8si)_mm256_undefined_si256(), \
                                            (__mmask8)-1)
Definition at line 1253 of file avx512dqintrin.h.
_mm512_extracti64x2_epi64
#define _mm512_extracti64x2_epi64 (A, imm)
Value:
  (__m128i)__builtin_ia32_extracti64x2_512_mask((__v8di)(__m512i)(A), \
                                                (int)(imm), \
                                                (__v2di)_mm_undefined_si128(), \
                                                (__mmask8)-1)
Definition at line 1268 of file avx512dqintrin.h.
_mm512_fpclass_pd_mask
#define _mm512_fpclass_pd_mask (A, imm)
Value:
  (__mmask8)__builtin_ia32_fpclasspd512_mask((__v8df)(__m512d)(A), (int)(imm), \
                                             (__mmask8)-1)
Definition at line 1354 of file avx512dqintrin.h.
_mm512_fpclass_ps_mask
#define _mm512_fpclass_ps_mask (A, imm)
Value:
  (__mmask16)__builtin_ia32_fpclassps512_mask((__v16sf)(__m512)(A), \
                                              (int)(imm), (__mmask16)-1)
Definition at line 1346 of file avx512dqintrin.h.
_mm512_insertf32x8
#define _mm512_insertf32x8 (A, B, imm)
Value:
  (__m512)__builtin_ia32_insertf32x8((__v16sf)(__m512)(A), \
                                     (__v8sf)(__m256)(B), (int)(imm))
Definition at line 1286 of file avx512dqintrin.h.
_mm512_insertf64x2
#define _mm512_insertf64x2 (A, B, imm)
Value:
  (__m512d)__builtin_ia32_insertf64x2_512((__v8df)(__m512d)(A), \
                                          (__v2df)(__m128d)(B), (int)(imm))
Definition at line 1300 of file avx512dqintrin.h.
_mm512_inserti32x8
#define _mm512_inserti32x8 (A, B, imm)
Value:
  (__m512i)__builtin_ia32_inserti32x8((__v16si)(__m512i)(A), \
                                      (__v8si)(__m256i)(B), (int)(imm))
Definition at line 1314 of file avx512dqintrin.h.
_mm512_inserti64x2
#define _mm512_inserti64x2 (A, B, imm)
Value:
  (__m512i)__builtin_ia32_inserti64x2_512((__v8di)(__m512i)(A), \
                                          (__v2di)(__m128i)(B), (int)(imm))
Definition at line 1328 of file avx512dqintrin.h.
_mm512_mask_cvt_roundepi64_pd
#define _mm512_mask_cvt_roundepi64_pd (W, U, A, R)
Value:
  (__m512d)__builtin_ia32_cvtqq2pd512_mask((__v8di)(__m512i)(A), \
                                           (__v8df)(__m512d)(W), \
                                           (__mmask8)(U), (int)(R))
Definition at line 501 of file avx512dqintrin.h.
_mm512_mask_cvt_roundepi64_ps
#define _mm512_mask_cvt_roundepi64_ps (W, U, A, R)
Value:
  (__m256)__builtin_ia32_cvtqq2ps512_mask((__v8di)(__m512i)(A), \
                                          (__v8sf)(__m256)(W), (__mmask8)(U), \
                                          (int)(R))
Definition at line 540 of file avx512dqintrin.h.
_mm512_mask_cvt_roundepu64_pd
#define _mm512_mask_cvt_roundepu64_pd (W, U, A, R)
Value:
  (__m512d)__builtin_ia32_cvtuqq2pd512_mask((__v8di)(__m512i)(A), \
                                            (__v8df)(__m512d)(W), \
                                            (__mmask8)(U), (int)(R))
Definition at line 731 of file avx512dqintrin.h.
_mm512_mask_cvt_roundepu64_ps
#define _mm512_mask_cvt_roundepu64_ps (W, U, A, R)
Value:
  (__m256)__builtin_ia32_cvtuqq2ps512_mask((__v8di)(__m512i)(A), \
                                           (__v8sf)(__m256)(W), (__mmask8)(U), \
                                           (int)(R))
Definition at line 772 of file avx512dqintrin.h.
_mm512_mask_cvt_roundpd_epi64
#define _mm512_mask_cvt_roundpd_epi64 (W, U, A, R)
Value:
  (__m512i)__builtin_ia32_cvtpd2qq512_mask((__v8df)(__m512d)(A), \
                                           (__v8di)(__m512i)(W), \
                                           (__mmask8)(U), (int)(R))
Definition at line 349 of file avx512dqintrin.h.
_mm512_mask_cvt_roundpd_epu64
#define _mm512_mask_cvt_roundpd_epu64 (W, U, A, R)
Value:
  (__m512i)__builtin_ia32_cvtpd2uqq512_mask((__v8df)(__m512d)(A), \
                                            (__v8di)(__m512i)(W), \
                                            (__mmask8)(U), (int)(R))
Definition at line 388 of file avx512dqintrin.h.
_mm512_mask_cvt_roundps_epi64
#define _mm512_mask_cvt_roundps_epi64 (W, U, A, R)
Value:
  (__m512i)__builtin_ia32_cvtps2qq512_mask((__v8sf)(__m256)(A), \
                                           (__v8di)(__m512i)(W), \
                                           (__mmask8)(U), (int)(R))
Definition at line 427 of file avx512dqintrin.h.
_mm512_mask_cvt_roundps_epu64
#define _mm512_mask_cvt_roundps_epu64 (W, U, A, R)
Value:
  (__m512i)__builtin_ia32_cvtps2uqq512_mask((__v8sf)(__m256)(A), \
                                            (__v8di)(__m512i)(W), \
                                            (__mmask8)(U), (int)(R))
Definition at line 466 of file avx512dqintrin.h.
_mm512_mask_cvtt_roundpd_epi64
#define _mm512_mask_cvtt_roundpd_epi64 (W, U, A, R)
Value:
  (__m512i)__builtin_ia32_cvttpd2qq512_mask((__v8df)(__m512d)(A), \
                                            (__v8di)(__m512i)(W), \
                                            (__mmask8)(U), (int)(R))
Definition at line 580 of file avx512dqintrin.h.
_mm512_mask_cvtt_roundpd_epu64
#define _mm512_mask_cvtt_roundpd_epu64 (W, U, A, R)
Value:
  (__m512i)__builtin_ia32_cvttpd2uqq512_mask((__v8df)(__m512d)(A), \
                                             (__v8di)(__m512i)(W), \
                                             (__mmask8)(U), (int)(R))
Definition at line 619 of file avx512dqintrin.h.
_mm512_mask_cvtt_roundps_epi64
#define _mm512_mask_cvtt_roundps_epi64 (W, U, A, R)
Value:
  (__m512i)__builtin_ia32_cvttps2qq512_mask((__v8sf)(__m256)(A), \
                                            (__v8di)(__m512i)(W), \
                                            (__mmask8)(U), (int)(R))
Definition at line 658 of file avx512dqintrin.h.
_mm512_mask_cvtt_roundps_epu64
#define _mm512_mask_cvtt_roundps_epu64 (W, U, A, R)
Value:
  (__m512i)__builtin_ia32_cvttps2uqq512_mask((__v8sf)(__m256)(A), \
                                             (__v8di)(__m512i)(W), \
                                             (__mmask8)(U), (int)(R))
Definition at line 697 of file avx512dqintrin.h.
_mm512_mask_extractf32x8_ps
#define _mm512_mask_extractf32x8_ps (W, U, A, imm)
Value:
  (__m256)__builtin_ia32_extractf32x8_mask((__v16sf)(__m512)(A), (int)(imm), \
                                           (__v8sf)(__m256)(W), \
                                           (__mmask8)(U))
Definition at line 1225 of file avx512dqintrin.h.
_mm512_mask_extractf64x2_pd
#define _mm512_mask_extractf64x2_pd (W, U, A, imm)
Value:
  (__m128d)__builtin_ia32_extractf64x2_512_mask((__v8df)(__m512d)(A), \
                                                (int)(imm), \
                                                (__v2df)(__m128d)(W), \
                                                (__mmask8)(U))
Definition at line 1241 of file avx512dqintrin.h.
_mm512_mask_extracti32x8_epi32
#define _mm512_mask_extracti32x8_epi32 (W, U, A, imm)
Value:
  (__m256i)__builtin_ia32_extracti32x8_mask((__v16si)(__m512i)(A), (int)(imm), \
                                            (__v8si)(__m256i)(W), \
                                            (__mmask8)(U))
Definition at line 1258 of file avx512dqintrin.h.
_mm512_mask_extracti64x2_epi64
#define _mm512_mask_extracti64x2_epi64 (W, U, A, imm)
Value:
  (__m128i)__builtin_ia32_extracti64x2_512_mask((__v8di)(__m512i)(A), \
                                                (int)(imm), \
                                                (__v2di)(__m128i)(W), \
                                                (__mmask8)(U))
Definition at line 1274 of file avx512dqintrin.h.
_mm512_mask_fpclass_pd_mask
#define _mm512_mask_fpclass_pd_mask (U, A, imm)
Value:
  (__mmask8)__builtin_ia32_fpclasspd512_mask((__v8df)(__m512d)(A), (int)(imm), \
                                             (__mmask8)(U))
Definition at line 1350 of file avx512dqintrin.h.
_mm512_mask_fpclass_ps_mask
#define _mm512_mask_fpclass_ps_mask (U, A, imm)
Value:
  (__mmask16)__builtin_ia32_fpclassps512_mask((__v16sf)(__m512)(A), \
                                              (int)(imm), (__mmask16)(U))
Definition at line 1342 of file avx512dqintrin.h.
_mm512_mask_insertf32x8
#define _mm512_mask_insertf32x8 (W, U, A, B, imm)
Value:
  (__m512)__builtin_ia32_selectps_512((__mmask16)(U), \
                                 (__v16sf)_mm512_insertf32x8((A), (B), (imm)), \
                                 (__v16sf)(__m512)(W))
Definition at line 1290 of file avx512dqintrin.h.
_mm512_mask_insertf64x2
#define _mm512_mask_insertf64x2 (W, U, A, B, imm)
Value:
  (__m512d)__builtin_ia32_selectpd_512((__mmask8)(U), \
                                  (__v8df)_mm512_insertf64x2((A), (B), (imm)), \
                                  (__v8df)(__m512d)(W))
Definition at line 1304 of file avx512dqintrin.h.
_mm512_mask_inserti32x8
#define _mm512_mask_inserti32x8 (W, U, A, B, imm)
Value:
  (__m512i)__builtin_ia32_selectd_512((__mmask16)(U), \
                                 (__v16si)_mm512_inserti32x8((A), (B), (imm)), \
                                 (__v16si)(__m512i)(W))
Definition at line 1318 of file avx512dqintrin.h.
_mm512_mask_inserti64x2
#define _mm512_mask_inserti64x2 (W, U, A, B, imm)
Value:
  (__m512i)__builtin_ia32_selectq_512((__mmask8)(U), \
                                  (__v8di)_mm512_inserti64x2((A), (B), (imm)), \
                                  (__v8di)(__m512i)(W))
Definition at line 1332 of file avx512dqintrin.h.
_mm512_mask_range_pd
#define _mm512_mask_range_pd (W, U, A, B, C)
Value:
  (__m512d)__builtin_ia32_rangepd512_mask((__v8df)(__m512d)(A), \
                                          (__v8df)(__m512d)(B), (int)(C), \
                                          (__v8df)(__m512d)(W), (__mmask8)(U), \
                                          _MM_FROUND_CUR_DIRECTION)
Definition at line 789 of file avx512dqintrin.h.
_mm512_mask_range_ps
#define _mm512_mask_range_ps (W, U, A, B, C)
Value:
  (__m512)__builtin_ia32_rangeps512_mask((__v16sf)(__m512)(A), \
                                         (__v16sf)(__m512)(B), (int)(C), \
                                         (__v16sf)(__m512)(W), (__mmask16)(U), \
                                         _MM_FROUND_CUR_DIRECTION)
Definition at line 827 of file avx512dqintrin.h.
_mm512_mask_range_round_pd
#define _mm512_mask_range_round_pd (W, U, A, B, C, R)
Value:
  (__m512d)__builtin_ia32_rangepd512_mask((__v8df)(__m512d)(A), \
                                          (__v8df)(__m512d)(B), (int)(C), \
                                          (__v8df)(__m512d)(W), (__mmask8)(U), \
                                          (int)(R))
Definition at line 808 of file avx512dqintrin.h.
_mm512_mask_range_round_ps
#define _mm512_mask_range_round_ps (W, U, A, B, C, R)
Value:
  (__m512)__builtin_ia32_rangeps512_mask((__v16sf)(__m512)(A), \
                                         (__v16sf)(__m512)(B), (int)(C), \
                                         (__v16sf)(__m512)(W), (__mmask16)(U), \
                                         (int)(R))
Definition at line 846 of file avx512dqintrin.h.
_mm512_mask_reduce_pd
#define _mm512_mask_reduce_pd (W, U, A, B)
Value:
  (__m512d)__builtin_ia32_reducepd512_mask((__v8df)(__m512d)(A), (int)(B), \
                                           (__v8df)(__m512d)(W), \
                                           (__mmask8)(U), \
                                           _MM_FROUND_CUR_DIRECTION)
Definition at line 918 of file avx512dqintrin.h.
_mm512_mask_reduce_ps
#define _mm512_mask_reduce_ps (W, U, A, B)
Value:
  (__m512)__builtin_ia32_reduceps512_mask((__v16sf)(__m512)(A), (int)(B), \
                                          (__v16sf)(__m512)(W), \
                                          (__mmask16)(U), \
                                          _MM_FROUND_CUR_DIRECTION)
Definition at line 936 of file avx512dqintrin.h.
_mm512_mask_reduce_round_pd
#define _mm512_mask_reduce_round_pd (W, U, A, B, R)
Value:
  (__m512d)__builtin_ia32_reducepd512_mask((__v8df)(__m512d)(A), (int)(B), \
                                           (__v8df)(__m512d)(W), \
                                           (__mmask8)(U), (int)(R))
Definition at line 953 of file avx512dqintrin.h.
_mm512_mask_reduce_round_ps
#define _mm512_mask_reduce_round_ps (W, U, A, B, R)
Value:
  (__m512)__builtin_ia32_reduceps512_mask((__v16sf)(__m512)(A), (int)(B), \
                                          (__v16sf)(__m512)(W), \
                                          (__mmask16)(U), (int)(R))
Definition at line 968 of file avx512dqintrin.h.
_mm512_maskz_cvt_roundepi64_pd
#define _mm512_maskz_cvt_roundepi64_pd (U, A, R)
Value:
  (__m512d)__builtin_ia32_cvtqq2pd512_mask((__v8di)(__m512i)(A), \
                                           (__v8df)_mm512_setzero_pd(), \
                                           (__mmask8)(U), (int)(R))
Definition at line 506 of file avx512dqintrin.h.
_mm512_maskz_cvt_roundepi64_ps
#define _mm512_maskz_cvt_roundepi64_ps (U, A, R)
Value:
  (__m256)__builtin_ia32_cvtqq2ps512_mask((__v8di)(__m512i)(A), \
                                          (__v8sf)_mm256_setzero_ps(), \
                                          (__mmask8)(U), (int)(R))
Definition at line 545 of file avx512dqintrin.h.
_mm512_maskz_cvt_roundepu64_pd
#define _mm512_maskz_cvt_roundepu64_pd (U, A, R)
Value:
  (__m512d)__builtin_ia32_cvtuqq2pd512_mask((__v8di)(__m512i)(A), \
                                            (__v8df)_mm512_setzero_pd(), \
                                            (__mmask8)(U), (int)(R))
Definition at line 737 of file avx512dqintrin.h.
_mm512_maskz_cvt_roundepu64_ps
#define _mm512_maskz_cvt_roundepu64_ps (U, A, R)
Value:
  (__m256)__builtin_ia32_cvtuqq2ps512_mask((__v8di)(__m512i)(A), \
                                           (__v8sf)_mm256_setzero_ps(), \
                                           (__mmask8)(U), (int)(R))
Definition at line 777 of file avx512dqintrin.h.
_mm512_maskz_cvt_roundpd_epi64
#define _mm512_maskz_cvt_roundpd_epi64 (U, A, R)
Value:
  (__m512i)__builtin_ia32_cvtpd2qq512_mask((__v8df)(__m512d)(A), \
                                           (__v8di)_mm512_setzero_si512(), \
                                           (__mmask8)(U), (int)(R))
Definition at line 354 of file avx512dqintrin.h.
_mm512_maskz_cvt_roundpd_epu64
#define _mm512_maskz_cvt_roundpd_epu64 (U, A, R)
Value:
  (__m512i)__builtin_ia32_cvtpd2uqq512_mask((__v8df)(__m512d)(A), \
                                            (__v8di)_mm512_setzero_si512(), \
                                            (__mmask8)(U), (int)(R))
Definition at line 393 of file avx512dqintrin.h.
_mm512_maskz_cvt_roundps_epi64
#define _mm512_maskz_cvt_roundps_epi64 (U, A, R)
Value:
  (__m512i)__builtin_ia32_cvtps2qq512_mask((__v8sf)(__m256)(A), \
                                           (__v8di)_mm512_setzero_si512(), \
                                           (__mmask8)(U), (int)(R))
Definition at line 432 of file avx512dqintrin.h.
_mm512_maskz_cvt_roundps_epu64
#define _mm512_maskz_cvt_roundps_epu64 (U, A, R)
Value:
  (__m512i)__builtin_ia32_cvtps2uqq512_mask((__v8sf)(__m256)(A), \
                                            (__v8di)_mm512_setzero_si512(), \
                                            (__mmask8)(U), (int)(R))
Definition at line 471 of file avx512dqintrin.h.
_mm512_maskz_cvtt_roundpd_epi64
#define _mm512_maskz_cvtt_roundpd_epi64 (U, A, R)
Value:
  (__m512i)__builtin_ia32_cvttpd2qq512_mask((__v8df)(__m512d)(A), \
                                            (__v8di)_mm512_setzero_si512(), \
                                            (__mmask8)(U), (int)(R))
Definition at line 585 of file avx512dqintrin.h.
_mm512_maskz_cvtt_roundpd_epu64
#define _mm512_maskz_cvtt_roundpd_epu64 (U, A, R)
Value:
  (__m512i)__builtin_ia32_cvttpd2uqq512_mask((__v8df)(__m512d)(A), \
                                             (__v8di)_mm512_setzero_si512(), \
                                             (__mmask8)(U), (int)(R))
Definition at line 624 of file avx512dqintrin.h.
_mm512_maskz_cvtt_roundps_epi64
#define _mm512_maskz_cvtt_roundps_epi64 (U, A, R)
Value:
  (__m512i)__builtin_ia32_cvttps2qq512_mask((__v8sf)(__m256)(A), \
                                            (__v8di)_mm512_setzero_si512(), \
                                            (__mmask8)(U), (int)(R))
Definition at line 663 of file avx512dqintrin.h.
_mm512_maskz_cvtt_roundps_epu64
#define _mm512_maskz_cvtt_roundps_epu64 (U, A, R)
Value:
  (__m512i)__builtin_ia32_cvttps2uqq512_mask((__v8sf)(__m256)(A), \
                                             (__v8di)_mm512_setzero_si512(), \
                                             (__mmask8)(U), (int)(R))
Definition at line 702 of file avx512dqintrin.h.
_mm512_maskz_extractf32x8_ps
#define _mm512_maskz_extractf32x8_ps (U, A, imm)
Value:
  (__m256)__builtin_ia32_extractf32x8_mask((__v16sf)(__m512)(A), (int)(imm), \
                                           (__v8sf)_mm256_setzero_ps(), \
                                           (__mmask8)(U))
Definition at line 1230 of file avx512dqintrin.h.
_mm512_maskz_extractf64x2_pd
#define _mm512_maskz_extractf64x2_pd (U, A, imm)
Value:
  (__m128d)__builtin_ia32_extractf64x2_512_mask((__v8df)(__m512d)(A), \
                                                (int)(imm), \
                                                (__v2df)_mm_setzero_pd(), \
                                                (__mmask8)(U))
Definition at line 1247 of file avx512dqintrin.h.
_mm512_maskz_extracti32x8_epi32
#define _mm512_maskz_extracti32x8_epi32 (U, A, imm)
Value:
  (__m256i)__builtin_ia32_extracti32x8_mask((__v16si)(__m512i)(A), (int)(imm), \
                                            (__v8si)_mm256_setzero_si256(), \
                                            (__mmask8)(U))
Definition at line 1263 of file avx512dqintrin.h.
_mm512_maskz_extracti64x2_epi64
#define _mm512_maskz_extracti64x2_epi64 (U, A, imm)
Value:
  (__m128i)__builtin_ia32_extracti64x2_512_mask((__v8di)(__m512i)(A), \
                                                (int)(imm), \
                                                (__v2di)_mm_setzero_si128(), \
                                                (__mmask8)(U))
Definition at line 1280 of file avx512dqintrin.h.
_mm512_maskz_insertf32x8
#define _mm512_maskz_insertf32x8 (U, A, B, imm)
Value:
  (__m512)__builtin_ia32_selectps_512((__mmask16)(U), \
                                 (__v16sf)_mm512_insertf32x8((A), (B), (imm)), \
                                 (__v16sf)_mm512_setzero_ps())
Definition at line 1295 of file avx512dqintrin.h.
_mm512_maskz_insertf64x2
#define _mm512_maskz_insertf64x2 (U, A, B, imm)
Value:
  (__m512d)__builtin_ia32_selectpd_512((__mmask8)(U), \
                                  (__v8df)_mm512_insertf64x2((A), (B), (imm)), \
                                  (__v8df)_mm512_setzero_pd())
Definition at line 1309 of file avx512dqintrin.h.
_mm512_maskz_inserti32x8
#define _mm512_maskz_inserti32x8 (U, A, B, imm)
Value:
  (__m512i)__builtin_ia32_selectd_512((__mmask16)(U), \
                                 (__v16si)_mm512_inserti32x8((A), (B), (imm)), \
                                 (__v16si)_mm512_setzero_si512())
Definition at line 1323 of file avx512dqintrin.h.
_mm512_maskz_inserti64x2
#define _mm512_maskz_inserti64x2 (U, A, B, imm)
Value:
  (__m512i)__builtin_ia32_selectq_512((__mmask8)(U), \
                                  (__v8di)_mm512_inserti64x2((A), (B), (imm)), \
                                  (__v8di)_mm512_setzero_si512())
Definition at line 1337 of file avx512dqintrin.h.
_mm512_maskz_range_pd
#define _mm512_maskz_range_pd (U, A, B, C)
Value:
  (__m512d)__builtin_ia32_rangepd512_mask((__v8df)(__m512d)(A), \
                                          (__v8df)(__m512d)(B), (int)(C), \
                                          (__v8df)_mm512_setzero_pd(), \
                                          (__mmask8)(U), \
                                          _MM_FROUND_CUR_DIRECTION)
Definition at line 795 of file avx512dqintrin.h.
_mm512_maskz_range_ps
#define _mm512_maskz_range_ps (U, A, B, C)
Value:
  (__m512)__builtin_ia32_rangeps512_mask((__v16sf)(__m512)(A), \
                                         (__v16sf)(__m512)(B), (int)(C), \
                                         (__v16sf)_mm512_setzero_ps(), \
                                         (__mmask16)(U), \
                                         _MM_FROUND_CUR_DIRECTION)
Definition at line 833 of file avx512dqintrin.h.
_mm512_maskz_range_round_pd
#define _mm512_maskz_range_round_pd (U, A, B, C, R)
Value:
  (__m512d)__builtin_ia32_rangepd512_mask((__v8df)(__m512d)(A), \
                                          (__v8df)(__m512d)(B), (int)(C), \
                                          (__v8df)_mm512_setzero_pd(), \
                                          (__mmask8)(U), (int)(R))
Definition at line 814 of file avx512dqintrin.h.
_mm512_maskz_range_round_ps
#define _mm512_maskz_range_round_ps (U, A, B, C, R)
Value:
  (__m512)__builtin_ia32_rangeps512_mask((__v16sf)(__m512)(A), \
                                         (__v16sf)(__m512)(B), (int)(C), \
                                         (__v16sf)_mm512_setzero_ps(), \
                                         (__mmask16)(U), (int)(R))
Definition at line 852 of file avx512dqintrin.h.
_mm512_maskz_reduce_pd
#define _mm512_maskz_reduce_pd (U, A, B)
Value:
  (__m512d)__builtin_ia32_reducepd512_mask((__v8df)(__m512d)(A), (int)(B), \
                                           (__v8df)_mm512_setzero_pd(), \
                                           (__mmask8)(U), \
                                           _MM_FROUND_CUR_DIRECTION)
Definition at line 924 of file avx512dqintrin.h.
_mm512_maskz_reduce_ps
#define _mm512_maskz_reduce_ps (U, A, B)
Value:
  (__m512)__builtin_ia32_reduceps512_mask((__v16sf)(__m512)(A), (int)(B), \
                                          (__v16sf)_mm512_setzero_ps(), \
                                          (__mmask16)(U), \
                                          _MM_FROUND_CUR_DIRECTION)
Definition at line 942 of file avx512dqintrin.h.
_mm512_maskz_reduce_round_pd
#define _mm512_maskz_reduce_round_pd (U, A, B, R)
Value:
  (__m512d)__builtin_ia32_reducepd512_mask((__v8df)(__m512d)(A), (int)(B), \
                                           (__v8df)_mm512_setzero_pd(), \
                                           (__mmask8)(U), (int)(R))
Definition at line 958 of file avx512dqintrin.h.
_mm512_maskz_reduce_round_ps
#define _mm512_maskz_reduce_round_ps (U, A, B, R)
Value:
  (__m512)__builtin_ia32_reduceps512_mask((__v16sf)(__m512)(A), (int)(B), \
                                          (__v16sf)_mm512_setzero_ps(), \
                                          (__mmask16)(U), (int)(R))
Definition at line 973 of file avx512dqintrin.h.
_mm512_range_pd
#define _mm512_range_pd (A, B, C)
Value:
  (__m512d)__builtin_ia32_rangepd512_mask((__v8df)(__m512d)(A), \
                                          (__v8df)(__m512d)(B), (int)(C), \
                                          (__v8df)_mm512_setzero_pd(), \
                                          (__mmask8)-1, \
                                          _MM_FROUND_CUR_DIRECTION)
Definition at line 782 of file avx512dqintrin.h.
_mm512_range_ps
#define _mm512_range_ps (A, B, C)
Value:
  (__m512)__builtin_ia32_rangeps512_mask((__v16sf)(__m512)(A), \
                                         (__v16sf)(__m512)(B), (int)(C), \
                                         (__v16sf)_mm512_setzero_ps(), \
                                         (__mmask16)-1, \
                                         _MM_FROUND_CUR_DIRECTION)
Definition at line 820 of file avx512dqintrin.h.
_mm512_range_round_pd
#define _mm512_range_round_pd (A, B, C, R)
Value:
  (__m512d)__builtin_ia32_rangepd512_mask((__v8df)(__m512d)(A), \
                                          (__v8df)(__m512d)(B), (int)(C), \
                                          (__v8df)_mm512_setzero_pd(), \
                                          (__mmask8)-1, (int)(R))
Definition at line 802 of file avx512dqintrin.h.
_mm512_range_round_ps
#define _mm512_range_round_ps (A, B, C, R)
Value:
  (__m512)__builtin_ia32_rangeps512_mask((__v16sf)(__m512)(A), \
                                         (__v16sf)(__m512)(B), (int)(C), \
                                         (__v16sf)_mm512_setzero_ps(), \
                                         (__mmask16)-1, (int)(R))
Definition at line 840 of file avx512dqintrin.h.
_mm512_reduce_pd
#define _mm512_reduce_pd (A, B)
Value:
  (__m512d)__builtin_ia32_reducepd512_mask((__v8df)(__m512d)(A), (int)(B), \
                                           (__v8df)_mm512_setzero_pd(), \
                                           (__mmask8)-1, \
                                           _MM_FROUND_CUR_DIRECTION)
Definition at line 912 of file avx512dqintrin.h.
_mm512_reduce_ps
#define _mm512_reduce_ps (A, B)
Value:
  (__m512)__builtin_ia32_reduceps512_mask((__v16sf)(__m512)(A), (int)(B), \
                                          (__v16sf)_mm512_setzero_ps(), \
                                          (__mmask16)-1, \
                                          _MM_FROUND_CUR_DIRECTION)
Definition at line 930 of file avx512dqintrin.h.
_mm512_reduce_round_pd
#define _mm512_reduce_round_pd (A, B, R)
Value:
  (__m512d)__builtin_ia32_reducepd512_mask((__v8df)(__m512d)(A), (int)(B), \
                                           (__v8df)_mm512_setzero_pd(), \
                                           (__mmask8)-1, (int)(R))
Definition at line 948 of file avx512dqintrin.h.
_mm512_reduce_round_ps
#define _mm512_reduce_round_ps (A, B, R)
Value:
  (__m512)__builtin_ia32_reduceps512_mask((__v16sf)(__m512)(A), (int)(B), \
                                          (__v16sf)_mm512_setzero_ps(), \
                                          (__mmask16)-1, (int)(R))
Definition at line 963 of file avx512dqintrin.h.
_mm_fpclass_sd_mask
#define _mm_fpclass_sd_mask (A, imm)
Value:
  (__mmask8)__builtin_ia32_fpclasssd_mask((__v2df)(__m128d)(A), (int)(imm), \
                                          (__mmask8)-1)
Definition at line 1358 of file avx512dqintrin.h.
_mm_fpclass_ss_mask
#define _mm_fpclass_ss_mask (A, imm)
Value:
  (__mmask8)__builtin_ia32_fpclassss_mask((__v4sf)(__m128)(A), (int)(imm), \
                                          (__mmask8)-1)
Definition at line 1366 of file avx512dqintrin.h.
_mm_mask_fpclass_sd_mask
#define _mm_mask_fpclass_sd_mask (U, A, imm)
Value:
  (__mmask8)__builtin_ia32_fpclasssd_mask((__v2df)(__m128d)(A), (int)(imm), \
                                          (__mmask8)(U))
Definition at line 1362 of file avx512dqintrin.h.
_mm_mask_fpclass_ss_mask
#define _mm_mask_fpclass_ss_mask (U, A, imm)
Value:
  (__mmask8)__builtin_ia32_fpclassss_mask((__v4sf)(__m128)(A), (int)(imm), \
                                          (__mmask8)(U))
Definition at line 1370 of file avx512dqintrin.h.
_mm_mask_range_round_sd
#define _mm_mask_range_round_sd (W, U, A, B, C, R)
Value:
  (__m128d)__builtin_ia32_rangesd128_round_mask((__v2df)(__m128d)(A), \
                                                (__v2df)(__m128d)(B), \
                                                (__v2df)(__m128d)(W),\
                                                (__mmask8)(U), (int)(C),\
                                                (int)(R))
Definition at line 894 of file avx512dqintrin.h.
_mm_mask_range_round_ss
#define _mm_mask_range_round_ss (W, U, A, B, C, R)
Value:
  (__m128)__builtin_ia32_rangess128_round_mask((__v4sf)(__m128)(A), \
                                               (__v4sf)(__m128)(B), \
                                               (__v4sf)(__m128)(W),\
                                               (__mmask8)(U), (int)(C),\
                                               (int)(R))
Definition at line 867 of file avx512dqintrin.h.
_mm_mask_range_sd
#define _mm_mask_range_sd (W, U, A, B, C) _mm_mask_range_round_sd(W, U, A, B, C ,_MM_FROUND_CUR_DIRECTION)
Definition at line 901 of file avx512dqintrin.h.
_mm_mask_range_ss
#define _mm_mask_range_ss (W, U, A, B, C) _mm_mask_range_round_ss(W, U, A, B, C , _MM_FROUND_CUR_DIRECTION)
Definition at line 874 of file avx512dqintrin.h.
_mm_mask_reduce_round_sd
#define _mm_mask_reduce_round_sd (W, U, A, B, C, R)
Value:
  (__m128d)__builtin_ia32_reducesd_mask((__v2df)(__m128d)(A), \
                                        (__v2df)(__m128d)(B), \
                                        (__v2df)(__m128d)(W), (__mmask8)(U), \
                                        (int)(C), (int)(R))
Definition at line 1041 of file avx512dqintrin.h.
_mm_mask_reduce_round_ss
#define _mm_mask_reduce_round_ss (W, U, A, B, C, R)
Value:
  (__m128)__builtin_ia32_reducess_mask((__v4sf)(__m128)(A), \
                                       (__v4sf)(__m128)(B), \
                                       (__v4sf)(__m128)(W), (__mmask8)(U), \
                                       (int)(C), (int)(R))
Definition at line 1003 of file avx512dqintrin.h.
_mm_mask_reduce_sd
#define _mm_mask_reduce_sd (W, U, A, B, C)
Value:
  (__m128d)__builtin_ia32_reducesd_mask((__v2df)(__m128d)(A), \
                                        (__v2df)(__m128d)(B), \
                                        (__v2df)(__m128d)(W), (__mmask8)(U), \
                                        (int)(C), _MM_FROUND_CUR_DIRECTION)
Definition at line 1022 of file avx512dqintrin.h.
_mm_mask_reduce_ss
#define _mm_mask_reduce_ss (W, U, A, B, C)
Value:
  (__m128)__builtin_ia32_reducess_mask((__v4sf)(__m128)(A), \
                                       (__v4sf)(__m128)(B), \
                                       (__v4sf)(__m128)(W), (__mmask8)(U), \
                                       (int)(C), _MM_FROUND_CUR_DIRECTION)
Definition at line 984 of file avx512dqintrin.h.
_mm_maskz_range_round_sd
#define _mm_maskz_range_round_sd (U, A, B, C, R)
Value:
  (__m128d)__builtin_ia32_rangesd128_round_mask((__v2df)(__m128d)(A), \
                                                (__v2df)(__m128d)(B), \
                                                (__v2df)_mm_setzero_pd(), \
                                                (__mmask8)(U), (int)(C),\
                                                (int)(R))
Definition at line 903 of file avx512dqintrin.h.
_mm_maskz_range_round_ss
#define _mm_maskz_range_round_ss (U, A, B, C, R)
Value:
  (__m128)__builtin_ia32_rangess128_round_mask((__v4sf)(__m128)(A), \
                                               (__v4sf)(__m128)(B), \
                                               (__v4sf)_mm_setzero_ps(), \
                                               (__mmask8)(U), (int)(C),\
                                               (int)(R))
Definition at line 876 of file avx512dqintrin.h.
_mm_maskz_range_sd
#define _mm_maskz_range_sd (U, A, B, C) _mm_maskz_range_round_sd(U, A, B, C ,_MM_FROUND_CUR_DIRECTION)
Definition at line 910 of file avx512dqintrin.h.
_mm_maskz_range_ss
#define _mm_maskz_range_ss (U, A, B, C) _mm_maskz_range_round_ss(U, A, B, C ,_MM_FROUND_CUR_DIRECTION)
Definition at line 883 of file avx512dqintrin.h.
_mm_maskz_reduce_round_sd
#define _mm_maskz_reduce_round_sd (U, A, B, C, R)
Value:
  (__m128d)__builtin_ia32_reducesd_mask((__v2df)(__m128d)(A), \
                                        (__v2df)(__m128d)(B), \
                                        (__v2df)_mm_setzero_pd(), \
                                        (__mmask8)(U), (int)(C), (int)(R))
Definition at line 1047 of file avx512dqintrin.h.
_mm_maskz_reduce_round_ss
#define _mm_maskz_reduce_round_ss (U, A, B, C, R)
Value:
  (__m128)__builtin_ia32_reducess_mask((__v4sf)(__m128)(A), \
                                       (__v4sf)(__m128)(B), \
                                       (__v4sf)_mm_setzero_ps(), \
                                       (__mmask8)(U), (int)(C), (int)(R))
Definition at line 1009 of file avx512dqintrin.h.
_mm_maskz_reduce_sd
#define _mm_maskz_reduce_sd (U, A, B, C)
Value:
  (__m128d)__builtin_ia32_reducesd_mask((__v2df)(__m128d)(A), \
                                        (__v2df)(__m128d)(B), \
                                        (__v2df)_mm_setzero_pd(), \
                                        (__mmask8)(U), (int)(C), \
                                        _MM_FROUND_CUR_DIRECTION)
Definition at line 1028 of file avx512dqintrin.h.
_mm_maskz_reduce_ss
#define _mm_maskz_reduce_ss (U, A, B, C)
Value:
  (__m128)__builtin_ia32_reducess_mask((__v4sf)(__m128)(A), \
                                       (__v4sf)(__m128)(B), \
                                       (__v4sf)_mm_setzero_ps(), \
                                       (__mmask8)(U), (int)(C), \
                                       _MM_FROUND_CUR_DIRECTION)
Definition at line 990 of file avx512dqintrin.h.
_mm_range_round_sd
#define _mm_range_round_sd (A, B, C, R)
Value:
  (__m128d)__builtin_ia32_rangesd128_round_mask((__v2df)(__m128d)(A), \
                                                (__v2df)(__m128d)(B), \
                                                (__v2df)_mm_setzero_pd(), \
                                                (__mmask8) -1, (int)(C),\
                                                (int)(R))
Definition at line 885 of file avx512dqintrin.h.
_mm_range_round_ss
#define _mm_range_round_ss (A, B, C, R)
Value:
  (__m128)__builtin_ia32_rangess128_round_mask((__v4sf)(__m128)(A), \
                                               (__v4sf)(__m128)(B), \
                                               (__v4sf)_mm_setzero_ps(), \
                                               (__mmask8) -1, (int)(C),\
                                               (int)(R))
Definition at line 858 of file avx512dqintrin.h.
_mm_range_sd
#define _mm_range_sd (A, B, C) _mm_range_round_sd(A, B, C ,_MM_FROUND_CUR_DIRECTION)
Definition at line 892 of file avx512dqintrin.h.
_mm_range_ss
#define _mm_range_ss (A, B, C) _mm_range_round_ss(A, B, C ,_MM_FROUND_CUR_DIRECTION)
Definition at line 865 of file avx512dqintrin.h.
_mm_reduce_round_sd
#define _mm_reduce_round_sd (A, B, C, R)
Value:
  (__m128d)__builtin_ia32_reducesd_mask((__v2df)(__m128d)(A), \
                                        (__v2df)(__m128d)(B), \
                                        (__v2df)_mm_setzero_pd(), \
                                        (__mmask8)-1, (int)(C), (int)(R))
Definition at line 1035 of file avx512dqintrin.h.
_mm_reduce_round_ss
#define _mm_reduce_round_ss (A, B, C, R)
Value:
  (__m128)__builtin_ia32_reducess_mask((__v4sf)(__m128)(A), \
                                       (__v4sf)(__m128)(B), \
                                       (__v4sf)_mm_setzero_ps(), (__mmask8)-1, \
                                       (int)(C), (int)(R))
Definition at line 997 of file avx512dqintrin.h.
_mm_reduce_sd
#define _mm_reduce_sd (A, B, C)
Value:
  (__m128d)__builtin_ia32_reducesd_mask((__v2df)(__m128d)(A), \
                                        (__v2df)(__m128d)(B), \
                                        (__v2df)_mm_setzero_pd(), \
                                        (__mmask8)-1, (int)(C), \
                                        _MM_FROUND_CUR_DIRECTION)
Definition at line 1015 of file avx512dqintrin.h.
_mm_reduce_ss
#define _mm_reduce_ss (A, B, C)
Value:
  (__m128)__builtin_ia32_reducess_mask((__v4sf)(__m128)(A), \
                                       (__v4sf)(__m128)(B), \
                                       (__v4sf)_mm_setzero_ps(), (__mmask8)-1, \
                                       (int)(C), _MM_FROUND_CUR_DIRECTION)
Definition at line 978 of file avx512dqintrin.h.
Function Documentation
_cvtmask8_u32()
static __inline__ unsigned int __DEFAULT_FN_ATTRS _cvtmask8_u32 (__mmask8 __A) static
Definition at line 130 of file avx512dqintrin.h.
_cvtu32_mask8()
static __inline__ __mmask8 __DEFAULT_FN_ATTRS _cvtu32_mask8 (unsigned int __A) static
Definition at line 135 of file avx512dqintrin.h.
_kadd_mask16()
static __inline__ __mmask16 __DEFAULT_FN_ATTRS _kadd_mask16 (__mmask16 __A, __mmask16 __B) static
Definition at line 118 of file avx512dqintrin.h.
_kadd_mask8()
static __inline__ __mmask8 __DEFAULT_FN_ATTRS _kadd_mask8 (__mmask8 __A, __mmask8 __B) static
Definition at line 112 of file avx512dqintrin.h.
_kand_mask8()
static __inline__ __mmask8 __DEFAULT_FN_ATTRS _kand_mask8 (__mmask8 __A, __mmask8 __B) static
Definition at line 28 of file avx512dqintrin.h.
_kandn_mask8()
static __inline__ __mmask8 __DEFAULT_FN_ATTRS _kandn_mask8 (__mmask8 __A, __mmask8 __B) static
Definition at line 34 of file avx512dqintrin.h.
_knot_mask8()
static __inline __mmask8 __DEFAULT_FN_ATTRS _knot_mask8 (__mmask8 __M) static
Definition at line 22 of file avx512dqintrin.h.
_kor_mask8()
static __inline__ __mmask8 __DEFAULT_FN_ATTRS _kor_mask8 (__mmask8 __A, __mmask8 __B) static
Definition at line 40 of file avx512dqintrin.h.
_kortest_mask8_u8()
static __inline__ unsigned char __DEFAULT_FN_ATTRS _kortest_mask8_u8 (__mmask8 __A, __mmask8 __B, unsigned char * __C) static
Definition at line 70 of file avx512dqintrin.h.
References __C.
_kortestc_mask8_u8()
static __inline__ unsigned char __DEFAULT_FN_ATTRS _kortestc_mask8_u8 (__mmask8 __A, __mmask8 __B) static
Definition at line 58 of file avx512dqintrin.h.
_kortestz_mask8_u8()
static __inline__ unsigned char __DEFAULT_FN_ATTRS _kortestz_mask8_u8 (__mmask8 __A, __mmask8 __B) static
Definition at line 64 of file avx512dqintrin.h.
_ktest_mask16_u8()
static __inline__ unsigned char __DEFAULT_FN_ATTRS _ktest_mask16_u8 (__mmask16 __A, __mmask16 __B, unsigned char * __C) static
Definition at line 106 of file avx512dqintrin.h.
References __C.
_ktest_mask8_u8()
static __inline__ unsigned char __DEFAULT_FN_ATTRS _ktest_mask8_u8 (__mmask8 __A, __mmask8 __B, unsigned char * __C) static
Definition at line 88 of file avx512dqintrin.h.
References __C.
_ktestc_mask16_u8()
static __inline__ unsigned char __DEFAULT_FN_ATTRS _ktestc_mask16_u8 (__mmask16 __A, __mmask16 __B) static
Definition at line 94 of file avx512dqintrin.h.
_ktestc_mask8_u8()
static __inline__ unsigned char __DEFAULT_FN_ATTRS _ktestc_mask8_u8 (__mmask8 __A, __mmask8 __B) static
Definition at line 76 of file avx512dqintrin.h.
_ktestz_mask16_u8()
static __inline__ unsigned char __DEFAULT_FN_ATTRS _ktestz_mask16_u8 (__mmask16 __A, __mmask16 __B) static
Definition at line 100 of file avx512dqintrin.h.
_ktestz_mask8_u8()
static __inline__ unsigned char __DEFAULT_FN_ATTRS _ktestz_mask8_u8 (__mmask8 __A, __mmask8 __B) static
Definition at line 82 of file avx512dqintrin.h.
_kxnor_mask8()
static __inline__ __mmask8 __DEFAULT_FN_ATTRS _kxnor_mask8 (__mmask8 __A, __mmask8 __B) static
Definition at line 46 of file avx512dqintrin.h.
_kxor_mask8()
static __inline__ __mmask8 __DEFAULT_FN_ATTRS _kxor_mask8 (__mmask8 __A, __mmask8 __B) static
Definition at line 52 of file avx512dqintrin.h.
_load_mask8()
static __inline__ __mmask8 __DEFAULT_FN_ATTRS _load_mask8 (__mmask8 * __A) static
Definition at line 140 of file avx512dqintrin.h.
_mm512_and_pd()
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_and_pd (__m512d __A, __m512d __B) static
Definition at line 245 of file avx512dqintrin.h.
Referenced by _mm512_mask_and_pd(), and _mm512_maskz_and_pd().
_mm512_and_ps()
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_and_ps (__m512 __A, __m512 __B) static
Definition at line 264 of file avx512dqintrin.h.
Referenced by _mm512_mask_and_ps(), and _mm512_maskz_and_ps().
_mm512_andnot_pd()
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_andnot_pd (__m512d __A, __m512d __B) static
Definition at line 283 of file avx512dqintrin.h.
Referenced by _mm512_mask_andnot_pd(), and _mm512_maskz_andnot_pd().
_mm512_andnot_ps()
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_andnot_ps (__m512 __A, __m512 __B) static
Definition at line 302 of file avx512dqintrin.h.
Referenced by _mm512_mask_andnot_ps(), and _mm512_maskz_andnot_ps().
_mm512_broadcast_f32x2()
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_broadcast_f32x2 (__m128 __A) static
Definition at line 1079 of file avx512dqintrin.h.
Referenced by _mm512_mask_broadcast_f32x2(), and _mm512_maskz_broadcast_f32x2().
_mm512_broadcast_f32x8()
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_broadcast_f32x8 (__m256 __A) static
Definition at line 1103 of file avx512dqintrin.h.
Referenced by _mm512_mask_broadcast_f32x8(), and _mm512_maskz_broadcast_f32x8().
_mm512_broadcast_f64x2()
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_broadcast_f64x2 (__m128d __A) static
Definition at line 1127 of file avx512dqintrin.h.
Referenced by _mm512_mask_broadcast_f64x2(), and _mm512_maskz_broadcast_f64x2().
_mm512_broadcast_i32x2()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_broadcast_i32x2 (__m128i __A) static
Definition at line 1150 of file avx512dqintrin.h.
Referenced by _mm512_mask_broadcast_i32x2(), and _mm512_maskz_broadcast_i32x2().
_mm512_broadcast_i32x8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_broadcast_i32x8 (__m256i __A) static
Definition at line 1174 of file avx512dqintrin.h.
Referenced by _mm512_mask_broadcast_i32x8(), and _mm512_maskz_broadcast_i32x8().
_mm512_broadcast_i64x2()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_broadcast_i64x2 (__m128i __A) static
Definition at line 1198 of file avx512dqintrin.h.
Referenced by _mm512_mask_broadcast_i64x2(), and _mm512_maskz_broadcast_i64x2().
_mm512_cvtepi64_pd()
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_cvtepi64_pd (__m512i __A) static
Definition at line 478 of file avx512dqintrin.h.
Referenced by _mm512_mask_cvtepi64_pd(), and _mm512_maskz_cvtepi64_pd().
_mm512_cvtepi64_ps()
static __inline__ __m256 __DEFAULT_FN_ATTRS512 _mm512_cvtepi64_ps (__m512i __A) static
Definition at line 512 of file avx512dqintrin.h.
References _mm256_setzero_ps(), and _MM_FROUND_CUR_DIRECTION.
_mm512_cvtepu64_pd()
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_cvtepu64_pd (__m512i __A) static
Definition at line 708 of file avx512dqintrin.h.
Referenced by _mm512_mask_cvtepu64_pd(), and _mm512_maskz_cvtepu64_pd().
_mm512_cvtepu64_ps()
static __inline__ __m256 __DEFAULT_FN_ATTRS512 _mm512_cvtepu64_ps (__m512i __A) static
Definition at line 744 of file avx512dqintrin.h.
References _mm256_setzero_ps(), and _MM_FROUND_CUR_DIRECTION.
_mm512_cvtpd_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvtpd_epi64 (__m512d __A) static
Definition at line 321 of file avx512dqintrin.h.
References _mm512_setzero_si512(), and _MM_FROUND_CUR_DIRECTION.
_mm512_cvtpd_epu64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvtpd_epu64 (__m512d __A) static
Definition at line 360 of file avx512dqintrin.h.
References _mm512_setzero_si512(), and _MM_FROUND_CUR_DIRECTION.
_mm512_cvtps_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvtps_epi64 (__m256 __A) static
Definition at line 399 of file avx512dqintrin.h.
References _mm512_setzero_si512(), and _MM_FROUND_CUR_DIRECTION.
_mm512_cvtps_epu64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvtps_epu64 (__m256 __A) static
Definition at line 438 of file avx512dqintrin.h.
References _mm512_setzero_si512(), and _MM_FROUND_CUR_DIRECTION.
_mm512_cvttpd_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvttpd_epi64 (__m512d __A) static
Definition at line 552 of file avx512dqintrin.h.
References _mm512_setzero_si512(), and _MM_FROUND_CUR_DIRECTION.
_mm512_cvttpd_epu64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvttpd_epu64 (__m512d __A) static
Definition at line 591 of file avx512dqintrin.h.
References _mm512_setzero_si512(), and _MM_FROUND_CUR_DIRECTION.
_mm512_cvttps_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvttps_epi64 (__m256 __A) static
Definition at line 630 of file avx512dqintrin.h.
References _mm512_setzero_si512(), and _MM_FROUND_CUR_DIRECTION.
_mm512_cvttps_epu64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvttps_epu64 (__m256 __A) static
Definition at line 669 of file avx512dqintrin.h.
References _mm512_setzero_si512(), and _MM_FROUND_CUR_DIRECTION.
_mm512_mask_and_pd()
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_mask_and_pd (__m512d __W, __mmask8 __U, __m512d __A, __m512d __B) static
Definition at line 250 of file avx512dqintrin.h.
References _mm512_and_pd().
_mm512_mask_and_ps()
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_mask_and_ps (__m512 __W, __mmask16 __U, __m512 __A, __m512 __B) static
Definition at line 269 of file avx512dqintrin.h.
References _mm512_and_ps().
_mm512_mask_andnot_pd()
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_mask_andnot_pd (__m512d __W, __mmask8 __U, __m512d __A, __m512d __B) static
Definition at line 288 of file avx512dqintrin.h.
References _mm512_andnot_pd().
_mm512_mask_andnot_ps()
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_mask_andnot_ps (__m512 __W, __mmask16 __U, __m512 __A, __m512 __B) static
Definition at line 307 of file avx512dqintrin.h.
References _mm512_andnot_ps().
_mm512_mask_broadcast_f32x2()
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_mask_broadcast_f32x2 (__m512 __O, __mmask16 __M, __m128 __A) static
Definition at line 1087 of file avx512dqintrin.h.
References _mm512_broadcast_f32x2().
_mm512_mask_broadcast_f32x8()
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_mask_broadcast_f32x8 (__m512 __O, __mmask16 __M, __m256 __A) static
Definition at line 1111 of file avx512dqintrin.h.
References _mm512_broadcast_f32x8().
_mm512_mask_broadcast_f64x2()
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_mask_broadcast_f64x2 (__m512d __O, __mmask8 __M, __m128d __A) static
Definition at line 1134 of file avx512dqintrin.h.
References _mm512_broadcast_f64x2().
_mm512_mask_broadcast_i32x2()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_broadcast_i32x2 (__m512i __O, __mmask16 __M, __m128i __A) static
Definition at line 1158 of file avx512dqintrin.h.
References _mm512_broadcast_i32x2().
_mm512_mask_broadcast_i32x8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_broadcast_i32x8 (__m512i __O, __mmask16 __M, __m256i __A) static
Definition at line 1182 of file avx512dqintrin.h.
References _mm512_broadcast_i32x8().
_mm512_mask_broadcast_i64x2()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_broadcast_i64x2 (__m512i __O, __mmask8 __M, __m128i __A) static
Definition at line 1205 of file avx512dqintrin.h.
References _mm512_broadcast_i64x2().
_mm512_mask_cvtepi64_pd()
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_mask_cvtepi64_pd (__m512d __W, __mmask8 __U, __m512i __A) static
Definition at line 483 of file avx512dqintrin.h.
References _mm512_cvtepi64_pd().
_mm512_mask_cvtepi64_ps()
static __inline__ __m256 __DEFAULT_FN_ATTRS512 _mm512_mask_cvtepi64_ps (__m256 __W, __mmask8 __U, __m512i __A) static
Definition at line 520 of file avx512dqintrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_cvtepu64_pd()
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_mask_cvtepu64_pd (__m512d __W, __mmask8 __U, __m512i __A) static
Definition at line 713 of file avx512dqintrin.h.
References _mm512_cvtepu64_pd().
_mm512_mask_cvtepu64_ps()
static __inline__ __m256 __DEFAULT_FN_ATTRS512 _mm512_mask_cvtepu64_ps (__m256 __W, __mmask8 __U, __m512i __A) static
Definition at line 752 of file avx512dqintrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_cvtpd_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvtpd_epi64 (__m512i __W, __mmask8 __U, __m512d __A) static
Definition at line 329 of file avx512dqintrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_cvtpd_epu64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvtpd_epu64 (__m512i __W, __mmask8 __U, __m512d __A) static
Definition at line 368 of file avx512dqintrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_cvtps_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvtps_epi64 (__m512i __W, __mmask8 __U, __m256 __A) static
Definition at line 407 of file avx512dqintrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_cvtps_epu64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvtps_epu64 (__m512i __W, __mmask8 __U, __m256 __A) static
Definition at line 446 of file avx512dqintrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_cvttpd_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvttpd_epi64 (__m512i __W, __mmask8 __U, __m512d __A) static
Definition at line 560 of file avx512dqintrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_cvttpd_epu64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvttpd_epu64 (__m512i __W, __mmask8 __U, __m512d __A) static
Definition at line 599 of file avx512dqintrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_cvttps_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvttps_epi64 (__m512i __W, __mmask8 __U, __m256 __A) static
Definition at line 638 of file avx512dqintrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_cvttps_epu64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvttps_epu64 (__m512i __W, __mmask8 __U, __m256 __A) static
Definition at line 677 of file avx512dqintrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_mullo_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_mullo_epi64 (__m512i __W, __mmask8 __U, __m512i __A, __m512i __B) static
Definition at line 155 of file avx512dqintrin.h.
References _mm512_mullo_epi64().
_mm512_mask_or_pd()
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_mask_or_pd (__m512d __W, __mmask8 __U, __m512d __A, __m512d __B) static
Definition at line 212 of file avx512dqintrin.h.
References _mm512_or_pd().
_mm512_mask_or_ps()
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_mask_or_ps (__m512 __W, __mmask16 __U, __m512 __A, __m512 __B) static
Definition at line 231 of file avx512dqintrin.h.
References _mm512_or_ps().
_mm512_mask_xor_pd()
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_mask_xor_pd (__m512d __W, __mmask8 __U, __m512d __A, __m512d __B) static
Definition at line 174 of file avx512dqintrin.h.
References _mm512_xor_pd().
_mm512_mask_xor_ps()
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_mask_xor_ps (__m512 __W, __mmask16 __U, __m512 __A, __m512 __B) static
Definition at line 193 of file avx512dqintrin.h.
References _mm512_xor_ps().
_mm512_maskz_and_pd()
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_maskz_and_pd (__mmask8 __U, __m512d __A, __m512d __B) static
Definition at line 257 of file avx512dqintrin.h.
References _mm512_and_pd(), and _mm512_setzero_pd().
_mm512_maskz_and_ps()
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_maskz_and_ps (__mmask16 __U, __m512 __A, __m512 __B) static
Definition at line 276 of file avx512dqintrin.h.
References _mm512_and_ps(), and _mm512_setzero_ps().
_mm512_maskz_andnot_pd()
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_maskz_andnot_pd (__mmask8 __U, __m512d __A, __m512d __B) static
Definition at line 295 of file avx512dqintrin.h.
References _mm512_andnot_pd(), and _mm512_setzero_pd().
_mm512_maskz_andnot_ps()
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_maskz_andnot_ps (__mmask16 __U, __m512 __A, __m512 __B) static
Definition at line 314 of file avx512dqintrin.h.
References _mm512_andnot_ps(), and _mm512_setzero_ps().
_mm512_maskz_broadcast_f32x2()
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_maskz_broadcast_f32x2 (__mmask16 __M, __m128 __A) static
Definition at line 1095 of file avx512dqintrin.h.
References _mm512_broadcast_f32x2(), and _mm512_setzero_ps().
_mm512_maskz_broadcast_f32x8()
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_maskz_broadcast_f32x8 (__mmask16 __M, __m256 __A) static
Definition at line 1119 of file avx512dqintrin.h.
References _mm512_broadcast_f32x8(), and _mm512_setzero_ps().
_mm512_maskz_broadcast_f64x2()
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_maskz_broadcast_f64x2 (__mmask8 __M, __m128d __A) static
Definition at line 1142 of file avx512dqintrin.h.
References _mm512_broadcast_f64x2(), and _mm512_setzero_pd().
_mm512_maskz_broadcast_i32x2()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_broadcast_i32x2 (__mmask16 __M, __m128i __A) static
Definition at line 1166 of file avx512dqintrin.h.
References _mm512_broadcast_i32x2(), and _mm512_setzero_si512().
_mm512_maskz_broadcast_i32x8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_broadcast_i32x8 (__mmask16 __M, __m256i __A) static
Definition at line 1190 of file avx512dqintrin.h.
References _mm512_broadcast_i32x8(), and _mm512_setzero_si512().
_mm512_maskz_broadcast_i64x2()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_broadcast_i64x2 (__mmask8 __M, __m128i __A) static
Definition at line 1213 of file avx512dqintrin.h.
References _mm512_broadcast_i64x2(), and _mm512_setzero_si512().
_mm512_maskz_cvtepi64_pd()
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtepi64_pd (__mmask8 __U, __m512i __A) static
Definition at line 490 of file avx512dqintrin.h.
References _mm512_cvtepi64_pd(), and _mm512_setzero_pd().
_mm512_maskz_cvtepi64_ps()
static __inline__ __m256 __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtepi64_ps (__mmask8 __U, __m512i __A) static
Definition at line 528 of file avx512dqintrin.h.
References _mm256_setzero_ps(), and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_cvtepu64_pd()
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtepu64_pd (__mmask8 __U, __m512i __A) static
Definition at line 720 of file avx512dqintrin.h.
References _mm512_cvtepu64_pd(), and _mm512_setzero_pd().
_mm512_maskz_cvtepu64_ps()
static __inline__ __m256 __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtepu64_ps (__mmask8 __U, __m512i __A) static
Definition at line 760 of file avx512dqintrin.h.
References _mm256_setzero_ps(), and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_cvtpd_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtpd_epi64 (__mmask8 __U, __m512d __A) static
Definition at line 337 of file avx512dqintrin.h.
References _mm512_setzero_si512(), and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_cvtpd_epu64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtpd_epu64 (__mmask8 __U, __m512d __A) static
Definition at line 376 of file avx512dqintrin.h.
References _mm512_setzero_si512(), and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_cvtps_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtps_epi64 (__mmask8 __U, __m256 __A) static
Definition at line 415 of file avx512dqintrin.h.
References _mm512_setzero_si512(), and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_cvtps_epu64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtps_epu64 (__mmask8 __U, __m256 __A) static
Definition at line 454 of file avx512dqintrin.h.
References _mm512_setzero_si512(), and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_cvttpd_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvttpd_epi64 (__mmask8 __U, __m512d __A) static
Definition at line 568 of file avx512dqintrin.h.
References _mm512_setzero_si512(), and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_cvttpd_epu64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvttpd_epu64 (__mmask8 __U, __m512d __A) static
Definition at line 607 of file avx512dqintrin.h.
References _mm512_setzero_si512(), and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_cvttps_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvttps_epi64 (__mmask8 __U, __m256 __A) static
Definition at line 646 of file avx512dqintrin.h.
References _mm512_setzero_si512(), and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_cvttps_epu64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvttps_epu64 (__mmask8 __U, __m256 __A) static
Definition at line 685 of file avx512dqintrin.h.
References _mm512_setzero_si512(), and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_mullo_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_mullo_epi64 (__mmask8 __U, __m512i __A, __m512i __B) static
Definition at line 162 of file avx512dqintrin.h.
References _mm512_mullo_epi64(), and _mm512_setzero_si512().
_mm512_maskz_or_pd()
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_maskz_or_pd (__mmask8 __U, __m512d __A, __m512d __B) static
Definition at line 219 of file avx512dqintrin.h.
References _mm512_or_pd(), and _mm512_setzero_pd().
_mm512_maskz_or_ps()
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_maskz_or_ps (__mmask16 __U, __m512 __A, __m512 __B) static
Definition at line 238 of file avx512dqintrin.h.
References _mm512_or_ps(), and _mm512_setzero_ps().
_mm512_maskz_xor_pd()
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_maskz_xor_pd (__mmask8 __U, __m512d __A, __m512d __B) static
Definition at line 181 of file avx512dqintrin.h.
References _mm512_setzero_pd(), and _mm512_xor_pd().
_mm512_maskz_xor_ps()
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_maskz_xor_ps (__mmask16 __U, __m512 __A, __m512 __B) static
Definition at line 200 of file avx512dqintrin.h.
References _mm512_setzero_ps(), and _mm512_xor_ps().
_mm512_movepi32_mask()
static __inline__ __mmask16 __DEFAULT_FN_ATTRS512 _mm512_movepi32_mask (__m512i __A) static
Definition at line 1054 of file avx512dqintrin.h.
_mm512_movepi64_mask()
static __inline__ __mmask8 __DEFAULT_FN_ATTRS512 _mm512_movepi64_mask (__m512i __A) static
Definition at line 1072 of file avx512dqintrin.h.
_mm512_movm_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_movm_epi32 (__mmask16 __A) static
Definition at line 1060 of file avx512dqintrin.h.
_mm512_movm_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_movm_epi64 (__mmask8 __A) static
Definition at line 1066 of file avx512dqintrin.h.
_mm512_mullo_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mullo_epi64 (__m512i __A, __m512i __B) static
Definition at line 150 of file avx512dqintrin.h.
Referenced by _mm512_mask_mullo_epi64(), and _mm512_maskz_mullo_epi64().
_mm512_or_pd()
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_or_pd (__m512d __A, __m512d __B) static
Definition at line 207 of file avx512dqintrin.h.
Referenced by _mm512_mask_or_pd(), and _mm512_maskz_or_pd().
_mm512_or_ps()
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_or_ps (__m512 __A, __m512 __B) static
Definition at line 226 of file avx512dqintrin.h.
Referenced by _mm512_mask_or_ps(), and _mm512_maskz_or_ps().
_mm512_xor_pd()
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_xor_pd (__m512d __A, __m512d __B) static
Definition at line 169 of file avx512dqintrin.h.
Referenced by _mm512_mask_xor_pd(), and _mm512_maskz_xor_pd().
_mm512_xor_ps()
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_xor_ps (__m512 __A, __m512 __B) static
Definition at line 188 of file avx512dqintrin.h.
Referenced by _mm512_mask_xor_ps(), and _mm512_maskz_xor_ps().
_store_mask8()
static __inline__ void __DEFAULT_FN_ATTRS _store_mask8 (__mmask8 * __A, __mmask8 __B) static
Definition at line 145 of file avx512dqintrin.h.