ETISS 0.8.0: include/jit/clang_stdlib/avx512vpopcntdqvlintrin.h File Reference
avx512vpopcntdqvlintrin.h File Reference
Macros
#define __DEFAULT_FN_ATTRS128 __attribute__((__always_inline__, __nodebug__, __target__("avx512vpopcntdq,avx512vl"), __min_vector_width__(128)))
#define __DEFAULT_FN_ATTRS256 __attribute__((__always_inline__, __nodebug__, __target__("avx512vpopcntdq,avx512vl"), __min_vector_width__(256)))
Functions
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_popcnt_epi64 (__m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_popcnt_epi64 (__m128i __W, __mmask8 __U, __m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_popcnt_epi64 (__mmask8 __U, __m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_popcnt_epi32 (__m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_popcnt_epi32 (__m128i __W, __mmask8 __U, __m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_popcnt_epi32 (__mmask8 __U, __m128i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_popcnt_epi64 (__m256i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_popcnt_epi64 (__m256i __W, __mmask8 __U, __m256i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_popcnt_epi64 (__mmask8 __U, __m256i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_popcnt_epi32 (__m256i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_popcnt_epi32 (__m256i __W, __mmask8 __U, __m256i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_popcnt_epi32 (__mmask8 __U, __m256i __A)
Macro Definition Documentation
__DEFAULT_FN_ATTRS128
#define __DEFAULT_FN_ATTRS128 __attribute__((__always_inline__, __nodebug__, __target__("avx512vpopcntdq,avx512vl"), __min_vector_width__(128)))
Definition at line 19 of file avx512vpopcntdqvlintrin.h.
__DEFAULT_FN_ATTRS256
#define __DEFAULT_FN_ATTRS256 __attribute__((__always_inline__, __nodebug__, __target__("avx512vpopcntdq,avx512vl"), __min_vector_width__(256)))
Definition at line 21 of file avx512vpopcntdqvlintrin.h.
Function Documentation
_mm256_mask_popcnt_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_popcnt_epi32 (__m256i __W, __mmask8 __U, __m256i __A) static
Definition at line 78 of file avx512vpopcntdqvlintrin.h.
References _mm256_popcnt_epi32().
Referenced by _mm256_maskz_popcnt_epi32().
_mm256_mask_popcnt_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_popcnt_epi64 (__m256i __W, __mmask8 __U, __m256i __A) static
Definition at line 62 of file avx512vpopcntdqvlintrin.h.
References _mm256_popcnt_epi64().
Referenced by _mm256_maskz_popcnt_epi64().
_mm256_maskz_popcnt_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_popcnt_epi32 (__mmask8 __U, __m256i __A) static
Definition at line 84 of file avx512vpopcntdqvlintrin.h.
References _mm256_mask_popcnt_epi32(), and _mm256_setzero_si256().
_mm256_maskz_popcnt_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_popcnt_epi64 (__mmask8 __U, __m256i __A) static
Definition at line 68 of file avx512vpopcntdqvlintrin.h.
References _mm256_mask_popcnt_epi64(), and _mm256_setzero_si256().
_mm256_popcnt_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_popcnt_epi32 (__m256i __A) static
Definition at line 73 of file avx512vpopcntdqvlintrin.h.
Referenced by _mm256_mask_popcnt_epi32().
_mm256_popcnt_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_popcnt_epi64 (__m256i __A) static
Definition at line 57 of file avx512vpopcntdqvlintrin.h.
Referenced by _mm256_mask_popcnt_epi64().
_mm_mask_popcnt_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_popcnt_epi32 (__m128i __W, __mmask8 __U, __m128i __A) static
Definition at line 46 of file avx512vpopcntdqvlintrin.h.
References _mm_popcnt_epi32().
Referenced by _mm_maskz_popcnt_epi32().
_mm_mask_popcnt_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_popcnt_epi64 (__m128i __W, __mmask8 __U, __m128i __A) static
Definition at line 30 of file avx512vpopcntdqvlintrin.h.
References _mm_popcnt_epi64().
Referenced by _mm_maskz_popcnt_epi64().
_mm_maskz_popcnt_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_popcnt_epi32 (__mmask8 __U, __m128i __A) static
Definition at line 52 of file avx512vpopcntdqvlintrin.h.
References _mm_mask_popcnt_epi32(), and _mm_setzero_si128().
_mm_maskz_popcnt_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_popcnt_epi64 (__mmask8 __U, __m128i __A) static
Definition at line 36 of file avx512vpopcntdqvlintrin.h.
References _mm_mask_popcnt_epi64(), and _mm_setzero_si128().
_mm_popcnt_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_popcnt_epi32 (__m128i __A) static
Definition at line 41 of file avx512vpopcntdqvlintrin.h.
Referenced by _mm_mask_popcnt_epi32().
_mm_popcnt_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_popcnt_epi64 (__m128i __A) static
Definition at line 25 of file avx512vpopcntdqvlintrin.h.
Referenced by _mm_mask_popcnt_epi64().