ETISS 0.8.0: include/jit/clang_stdlib/avx512bitalgintrin.h File Reference
avx512bitalgintrin.h File Reference
Macros
#define __DEFAULT_FN_ATTRS __attribute__((__always_inline__, __nodebug__, __target__("avx512bitalg"), __min_vector_width__(512)))
Functions
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_popcnt_epi16 (__m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_popcnt_epi16 (__m512i __A, __mmask32 __U, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_popcnt_epi16 (__mmask32 __U, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_popcnt_epi8 (__m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_popcnt_epi8 (__m512i __A, __mmask64 __U, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_popcnt_epi8 (__mmask64 __U, __m512i __B)
static __inline__ __mmask64 __DEFAULT_FN_ATTRS _mm512_mask_bitshuffle_epi64_mask (__mmask64 __U, __m512i __A, __m512i __B)
static __inline__ __mmask64 __DEFAULT_FN_ATTRS _mm512_bitshuffle_epi64_mask (__m512i __A, __m512i __B)
Macro Definition Documentation
__DEFAULT_FN_ATTRS
#define __DEFAULT_FN_ATTRS __attribute__((__always_inline__, __nodebug__, __target__("avx512bitalg"), __min_vector_width__(512)))
Definition at line 18 of file avx512bitalgintrin.h.
Function Documentation
_mm512_bitshuffle_epi64_mask()
static __inline__ __mmask64 __DEFAULT_FN_ATTRS _mm512_bitshuffle_epi64_mask (__m512i __A, __m512i __B) static
Definition at line 73 of file avx512bitalgintrin.h.
References _mm512_mask_bitshuffle_epi64_mask().
_mm512_mask_bitshuffle_epi64_mask()
static __inline__ __mmask64 __DEFAULT_FN_ATTRS _mm512_mask_bitshuffle_epi64_mask (__mmask64 __U, __m512i __A, __m512i __B) static
Definition at line 65 of file avx512bitalgintrin.h.
Referenced by _mm512_bitshuffle_epi64_mask().
_mm512_mask_popcnt_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_popcnt_epi16 (__m512i __A, __mmask32 __U, __m512i __B) static
Definition at line 27 of file avx512bitalgintrin.h.
References _mm512_popcnt_epi16().
Referenced by _mm512_maskz_popcnt_epi16().
_mm512_mask_popcnt_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_popcnt_epi8 (__m512i __A, __mmask64 __U, __m512i __B) static
Definition at line 49 of file avx512bitalgintrin.h.
References _mm512_popcnt_epi8().
Referenced by _mm512_maskz_popcnt_epi8().
_mm512_maskz_popcnt_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_popcnt_epi16 (__mmask32 __U, __m512i __B) static
Definition at line 35 of file avx512bitalgintrin.h.
References _mm512_mask_popcnt_epi16(), and _mm512_setzero_si512().
_mm512_maskz_popcnt_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_popcnt_epi8 (__mmask64 __U, __m512i __B) static
Definition at line 57 of file avx512bitalgintrin.h.
References _mm512_mask_popcnt_epi8(), and _mm512_setzero_si512().
_mm512_popcnt_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_popcnt_epi16 (__m512i __A) static
Definition at line 21 of file avx512bitalgintrin.h.
Referenced by _mm512_mask_popcnt_epi16().
_mm512_popcnt_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_popcnt_epi8 (__m512i __A) static
Definition at line 43 of file avx512bitalgintrin.h.
Referenced by _mm512_mask_popcnt_epi8().