ETISS 0.8.0: include/etiss/fault/xml/CMakeLists.txt File Reference
include/etiss/fault/xml/CMakeLists.txt File Reference
Functions
unset (LOCAL_SUBDIRS) foreach(subdir $
if (IS_DIRECTORY ${subdir}) add_subdirectory($
endif () endforeach() unset(LOCAL_SOURCE1) unset(LOCAL_SOURCE2) set(ETISS_HEADER $
Function Documentation
endif()
endif ()
Definition at line 42 of file CMakeLists.txt.
Referenced by main().
if()
if (IS_DIRECTORY ${subdir})
Definition at line 40 of file CMakeLists.txt.
Referenced by ETISS_SIGNAL_MMU(), RISCVArch::initInstrSet(), RISCV64Arch::initInstrSet(), OR1KTimer::internal_state_to_TTMR_IP(), and etiss::CPUArchRegListenerInterface::signalChangedRegisterValue().
unset()
unset (LOCAL_SUBDIRS)
Definition at line 37 of file CMakeLists.txt.