ETISS 0.8.0: etiss::plugin::InstructionAccurateCallback Class Reference
etiss::plugin::InstructionAccurateCallback Class Reference
writes the value of a field before each instruction
#include <InstructionAccurateCallback.h>
Public Member Functions
InstructionAccurateCallback ()
virtual ~InstructionAccurateCallback ()
virtual void initCodeBlock (etiss::CodeBlock &block) const
called before instructions are translated for the code block
virtual void finalizeInstrSet (etiss::instr::ModedInstructionSet &) const
called after all instructions have been added to allow last changes
void call ()
InstructionAccurateCallback ()
virtual ~InstructionAccurateCallback ()
virtual void initCodeBlock (etiss::CodeBlock &block) const
called before instructions are translated for the code block
virtual void finalizeInstrSet (etiss::instr::ModedInstructionSet &) const
called after all instructions have been added to allow last changes
void call ()
Public Member Functions inherited from etiss::TranslationPlugin
TranslationPlugin ()
virtual ~TranslationPlugin ()
virtual void initInstrSet (etiss::instr::ModedInstructionSet &) const
called to add instructions to the instruction set
virtual void finalizeCodeBlock (etiss::CodeBlock &) const
called after all instructions have been translated for the code block
virtual void * getPluginHandle ()
called to get the handle that is available in translated code via getPoinerCode(). [default: this]
TranslationPlugin ()
virtual ~TranslationPlugin ()
virtual void initInstrSet (etiss::instr::ModedInstructionSet &) const
called to add instructions to the instruction set
virtual void finalizeCodeBlock (etiss::CodeBlock &) const
called after all instructions have been translated for the code block
virtual void * getPluginHandle ()
called to get the handle that is available in translated code via getPoinerCode(). [default: this]
Public Member Functions inherited from etiss::Plugin
virtual ~Plugin ()
unsigned getType ()
InterruptListenerPlugin * getInterruptListenerPlugin ()
CoroutinePlugin * getCoroutinePlugin ()
SystemWrapperPlugin * getSystemWrapperPlugin ()
RegisterDevicePlugin * getRegisterDevicePlugin ()
TranslationPlugin * getTranslationPlugin ()
std::string getPluginName () const
const std::string & getLastAssignedCoreName ()
std::string toString () const
virtual ~Plugin ()
unsigned getType ()
InterruptListenerPlugin * getInterruptListenerPlugin ()
CoroutinePlugin * getCoroutinePlugin ()
SystemWrapperPlugin * getSystemWrapperPlugin ()
RegisterDevicePlugin * getRegisterDevicePlugin ()
TranslationPlugin * getTranslationPlugin ()
std::string getPluginName () const
const std::string & getLastAssignedCoreName ()
std::string toString () const
Public Member Functions inherited from etiss::ToString
ToString ()
virtual ~ToString ()
ToString ()
virtual ~ToString ()
Protected Member Functions
virtual std::string _getPluginName () const
virtual std::string _getPluginName () const
Protected Member Functions inherited from etiss::TranslationPlugin
std::string getPointerCode () const
returns a C code expression that allows to get or assign a pointer to the variable assigned to this translation plugin.
std::string getPointerCode () const
returns a C code expression that allows to get or assign a pointer to the variable assigned to this translation plugin.
Protected Member Functions inherited from etiss::Plugin
Plugin (unsigned type=0)
virtual void init (ETISS_CPU *cpu, ETISS_System *system, CPUArch *arch)
this function is called before the plugin is used in the cpu execution loop (etiss::CPUCore::execute).
virtual void cleanup ()
this function is called after cpu execution loop (etiss::CPUCore::execute) finished.
void setCorrespondingCPUCoreName (std::string name)
virtual void addedToCPUCore (etiss::CPUCore *core)
called as soon a plugin has been added to its CPUCore.
virtual void removedFromCPUCore (etiss::CPUCore *core)
called as soon a plugin has been removed from its CPUCore.
Plugin (unsigned type=0)
virtual void init (ETISS_CPU *cpu, ETISS_System *system, CPUArch *arch)
this function is called before the plugin is used in the cpu execution loop (etiss::CPUCore::execute).
virtual void cleanup ()
this function is called after cpu execution loop (etiss::CPUCore::execute) finished.
void setCorrespondingCPUCoreName (std::string name)
virtual void addedToCPUCore (etiss::CPUCore *core)
called as soon a plugin has been added to its CPUCore.
virtual void removedFromCPUCore (etiss::CPUCore *core)
called as soon a plugin has been removed from its CPUCore.
Additional Inherited Members
Static Public Attributes inherited from etiss::Plugin
static const unsigned INTERRUPTLISTENER = 1 << 0
access to translated code
static const unsigned COROUTINE = 1 << 1
callback after execution of each translated block
static const unsigned SYSTEMWRAPPER = 1 << 2
can wrap/change ETISS_System structure at execution start
static const unsigned REGISTERDEVICE
gets noticed of changes to special registers (e.g. mmu register etc. [depends on architecture])
static const unsigned TRANSLATION
access to translated code during translation phase or when instruction tree is built
Protected Attributes inherited from etiss::Plugin
ETISS_CPU * plugin_cpu_
holds a pointer to the cpu structure. will be set before init call and after cleanup call
ETISS_System * plugin_system_
holds a pointer to the system structure.
CPUArch * plugin_arch_
holds a pointer to the CPUArch instance. will be set before init call and after cleanup call
CPUCore * plugin_core_
holds a pointer to the associated CPUCore instance.
Detailed Description
writes the value of a field before each instruction
Definition at line 60 of file InstructionAccurateCallback.h.
Constructor & Destructor Documentation
InstructionAccurateCallback() [1/2]
etiss::plugin::InstructionAccurateCallback::InstructionAccurateCallback ()
Definition at line 62 of file InstructionAccurateCallback.cpp.
~InstructionAccurateCallback() [1/2]
etiss::plugin::InstructionAccurateCallback::~InstructionAccurateCallback () virtual
Definition at line 63 of file InstructionAccurateCallback.cpp.
InstructionAccurateCallback() [2/2]
etiss::plugin::InstructionAccurateCallback::InstructionAccurateCallback ()
~InstructionAccurateCallback() [2/2]
virtual etiss::plugin::InstructionAccurateCallback::~InstructionAccurateCallback () virtual
Member Function Documentation
_getPluginName() [1/2]
std::string etiss::plugin::InstructionAccurateCallback::_getPluginName () const protected virtual
Implements etiss::Plugin.
Definition at line 88 of file InstructionAccurateCallback.cpp.
_getPluginName() [2/2]
virtual std::string etiss::plugin::InstructionAccurateCallback::_getPluginName () const protected virtual
Implements etiss::Plugin.
call() [1/2]
void etiss::plugin::InstructionAccurateCallback::call ()
Definition at line 93 of file InstructionAccurateCallback.cpp.
References ETISS_CPU::cpuTime_ps, etiss::CPUCore::getStruct(), etiss::Plugin::plugin_core_, and etiss::Plugin::plugin_cpu_.
Referenced by etiss_plugin_InstructionAccurateCallback().
call() [2/2]
void etiss::plugin::InstructionAccurateCallback::call ()
finalizeInstrSet() [1/2]
void etiss::plugin::InstructionAccurateCallback::finalizeInstrSet (etiss::instr::ModedInstructionSet &) const virtual
called after all instructions have been added to allow last changes
Reimplemented from etiss::TranslationPlugin.
Definition at line 70 of file InstructionAccurateCallback.cpp.
References etiss::instr::Instruction::addCallback(), etiss::CodeSet::append(), etiss::CodePart::code(), etiss::instr::InstructionSet::foreach(), etiss::instr::VariableInstructionSet::foreach(), etiss::instr::ModedInstructionSet::foreach(), etiss::TranslationPlugin::getPointerCode(), etiss::CodePart::getRegisterDependencies(), and etiss::CodePart::INITIALREQUIRED.
finalizeInstrSet() [2/2]
virtual void etiss::plugin::InstructionAccurateCallback::finalizeInstrSet (etiss::instr::ModedInstructionSet &) const virtual
called after all instructions have been added to allow last changes
Reimplemented from etiss::TranslationPlugin.
initCodeBlock() [1/2]
void etiss::plugin::InstructionAccurateCallback::initCodeBlock (etiss::CodeBlock &) const virtual
called before instructions are translated for the code block
Reimplemented from etiss::TranslationPlugin.
Definition at line 65 of file InstructionAccurateCallback.cpp.
References etiss::CodeBlock::fileglobalCode().
initCodeBlock() [2/2]
virtual void etiss::plugin::InstructionAccurateCallback::initCodeBlock (etiss::CodeBlock &) const virtual
called before instructions are translated for the code block
Reimplemented from etiss::TranslationPlugin.
The documentation for this class was generated from the following files:
include/etiss/IntegratedLibrary/InstructionAccurateCallback.h
/home/runner/work/etiss/etiss/src/IntegratedLibrary/InstructionAccurateCallback.cpp