ETISS 0.8.0: etiss::plugin::gdb::GDBCore Class Reference
etiss::plugin::gdb::GDBCore Class Reference
provides to architecture dependent registers as defined by gdb
#include <GDBCore.h>
Public Member Functions
virtual ~GDBCore ()
virtual std::string mapRegister (unsigned index)
the returned string identifies the register at the given index as defined by gdb.
virtual unsigned mapRegister (std::string name)
returns the index of the given register name in the list of registers as defined by gdb.
virtual unsigned mappedRegisterCount ()
returns the number of registers in the gdb defined register list
virtual bool isLittleEndian ()
returns true if the values are expected to be little endian
virtual etiss::uint64 getInstructionPointer (ETISS_CPU *cpu)
allows to calculate the index of the instruction to be executed for breakpoint checks.
virtual ~GDBCore ()
virtual std::string mapRegister (unsigned index)
the returned string identifies the register at the given index as defined by gdb.
virtual unsigned mapRegister (std::string name)
returns the index of the given register name in the list of registers as defined by gdb.
virtual unsigned mappedRegisterCount ()
returns the number of registers in the gdb defined register list
virtual bool isLittleEndian ()
returns true if the values are expected to be little endian
virtual etiss::uint64 getInstructionPointer (ETISS_CPU *cpu)
allows to calculate the index of the instruction to be executed for breakpoint checks.
Static Public Attributes
static const unsigned INVALIDMAPPING = (unsigned)-1
Detailed Description
provides to architecture dependent registers as defined by gdb
gdb requires a predefined archtecture specific list of registers. Information about this list is provided by this class
Definition at line 76 of file GDBCore.h.
Constructor & Destructor Documentation
~GDBCore() [1/2]
GDBCore::~GDBCore () virtual
Definition at line 57 of file GDBCore.cpp.
~GDBCore() [2/2]
virtual etiss::plugin::gdb::GDBCore::~GDBCore () virtual
Member Function Documentation
getInstructionPointer() [1/2]
etiss::uint64 GDBCore::getInstructionPointer (ETISS_CPU * cpu) virtual
allows to calculate the index of the instruction to be executed for breakpoint checks.
returns cpu->instructionPointer by default.
the OR1K architecture uses this to account for an invalid instruction pointer in case of a delay slot instruction
Reimplemented in RISCV64GDBCore, RISCVGDBCore, and OR1KGDBCore.
Definition at line 74 of file GDBCore.cpp.
References ETISS_CPU::instructionPointer.
Referenced by etiss::plugin::gdb::Server::preInstructionCallback().
getInstructionPointer() [2/2]
virtual etiss::uint64 etiss::plugin::gdb::GDBCore::getInstructionPointer (ETISS_CPU * cpu) virtual
allows to calculate the index of the instruction to be executed for breakpoint checks.
returns cpu->instructionPointer by default.
the OR1K architecture uses this to account for an invalid instruction pointer in case of a delay slot instruction
Reimplemented in RISCV64GDBCore, RISCVGDBCore, and OR1KGDBCore.
isLittleEndian() [1/2]
virtual bool etiss::plugin::gdb::GDBCore::isLittleEndian () virtual
returns true if the values are expected to be little endian
Reimplemented in RISCV64GDBCore, and RISCVGDBCore.
isLittleEndian() [2/2]
bool GDBCore::isLittleEndian () virtual
returns true if the values are expected to be little endian
Reimplemented in RISCV64GDBCore, and RISCVGDBCore.
Definition at line 70 of file GDBCore.cpp.
Referenced by etiss::plugin::gdb::Server::handlePacket().
mappedRegisterCount() [1/2]
unsigned GDBCore::mappedRegisterCount () virtual
returns the number of registers in the gdb defined register list
Reimplemented in RISCV64GDBCore, RISCVGDBCore, and OR1KGDBCore.
Definition at line 66 of file GDBCore.cpp.
mappedRegisterCount() [2/2]
virtual unsigned etiss::plugin::gdb::GDBCore::mappedRegisterCount () virtual
returns the number of registers in the gdb defined register list
Reimplemented in RISCV64GDBCore, RISCVGDBCore, and OR1KGDBCore.
mapRegister() [1/4]
virtual unsigned etiss::plugin::gdb::GDBCore::mapRegister (std::string name) virtual
returns the index of the given register name in the list of registers as defined by gdb.
max return INVALIDMAPPING if the passed name is not in the list
Reimplemented in RISCV64GDBCore, RISCVGDBCore, and OR1KGDBCore.
mapRegister() [2/4]
unsigned GDBCore::mapRegister (std::string name) virtual
returns the index of the given register name in the list of registers as defined by gdb.
max return INVALIDMAPPING if the passed name is not in the list
Reimplemented in RISCV64GDBCore, RISCVGDBCore, and OR1KGDBCore.
Definition at line 62 of file GDBCore.cpp.
References INVALIDMAPPING.
mapRegister() [3/4]
std::string GDBCore::mapRegister (unsigned index) virtual
the returned string identifies the register at the given index as defined by gdb.
the returned string must match the get/setRegisterXX() functions of etiss::CPUArch
Reimplemented in RISCVGDBCore, RISCV64GDBCore, and OR1KGDBCore.
Definition at line 58 of file GDBCore.cpp.
Referenced by etiss::plugin::gdb::Server::handlePacket().
mapRegister() [4/4]
virtual std::string etiss::plugin::gdb::GDBCore::mapRegister (unsigned index) virtual
the returned string identifies the register at the given index as defined by gdb.
the returned string must match the get/setRegisterXX() functions of etiss::CPUArch
Reimplemented in RISCVGDBCore, RISCV64GDBCore, and OR1KGDBCore.
Member Data Documentation
INVALIDMAPPING
static const unsigned etiss::plugin::gdb::GDBCore::INVALIDMAPPING = (unsigned)-1 static
Definition at line 107 of file GDBCore.h.
Referenced by OR1KGDBCore::mapRegister(), mapRegister(), RISCVGDBCore::mapRegister(), and RISCV64GDBCore::mapRegister().
The documentation for this class was generated from the following files:
include/etiss/IntegratedLibrary/gdb/GDBCore.h
/home/runner/work/etiss/etiss/src/IntegratedLibrary/gdb/GDBCore.cpp