ETISS 0.8.0: etiss::interfaces::Dot Class Reference
etiss::interfaces::Dot Class Reference
#include <Dot.h>
Classes
class AttrList
class Graph
class Link
class Node
Public Member Functions
~Dot ()
const std::list< Graph * > graphs ()
Graph * createG (std::string name="")
Graph * createG (Graph *parent, std::string name="")
Node * createN (Graph *, const std::string &id, std::string name="")
Node * pcreateN (Graph *g, const void *id, std::string name="")
Link * createE (Node *src, Node *dst, std::string name="")
Node * find (const std::string &id)
Node * lopenN (const std::list< std::string > &labelpath)
travel/creates sub graphs with the given labels until i find/creates a node for the lase label.
virtual void print (std::ostream &out)
~Dot ()
const std::list< Graph * > graphs ()
Graph * createG (std::string name="")
Graph * createG (Graph *parent, std::string name="")
Node * createN (Graph *, const std::string &id, std::string name="")
Node * pcreateN (Graph *g, const void *id, std::string name="")
Link * createE (Node *src, Node *dst, std::string name="")
Node * find (const std::string &id)
Node * lopenN (const std::list< std::string > &labelpath)
travel/creates sub graphs with the given labels until i find/creates a node for the lase label.
virtual void print (std::ostream &out)
Private Attributes
std::list< Graph * > graphs_
std::unordered_map< std::string, Node * > idmap_
Detailed Description
Attention
if an id is a pointer then the pointer must remain valid during the use of that id. otherwise anything may be chosen as an id that doesn't start with "p_"
Definition at line 95 of file Dot.h.
Constructor & Destructor Documentation
~Dot() [1/2]
etiss::interfaces::Dot::~Dot ()
Definition at line 991 of file Dot.cpp.
~Dot() [2/2]
etiss::interfaces::Dot::~Dot ()
Member Function Documentation
createE() [1/2]
Dot::Link * etiss::interfaces::Dot::createE (Dot::Node * src, Dot::Node * dst, std::string name = "")
Definition at line 1024 of file Dot.cpp.
References etiss::interfaces::Dot::AttrList::label_, and name.
createE() [2/2]
Link* etiss::interfaces::Dot::createE (Node * src, Node * dst, std::string name = "")
createG() [1/4]
Graph* etiss::interfaces::Dot::createG (Graph * parent, std::string name = "")
createG() [2/4]
Dot::Graph * etiss::interfaces::Dot::createG (Dot::Graph * parent, std::string name = "")
Definition at line 1006 of file Dot.cpp.
References etiss::interfaces::Dot::AttrList::label_, and name.
createG() [3/4]
Graph* etiss::interfaces::Dot::createG (std::string name = "")
createG() [4/4]
Dot::Graph * etiss::interfaces::Dot::createG (std::string name = "")
Definition at line 999 of file Dot.cpp.
References etiss::interfaces::Dot::AttrList::label_, and name.
createN() [1/2]
Dot::Node * etiss::interfaces::Dot::createN (Dot::Graph * parent, const std::string & id, std::string name = "")
Definition at line 1014 of file Dot.cpp.
References etiss::interfaces::Dot::AttrList::label_, and name.
Referenced by pcreateN().
createN() [2/2]
Node* etiss::interfaces::Dot::createN (Graph * , const std::string & id, std::string name = "")
find() [1/2]
Node* etiss::interfaces::Dot::find (const std::string & id)
find() [2/2]
Dot::Node * etiss::interfaces::Dot::find (const std::string & id)
Definition at line 1033 of file Dot.cpp.
graphs() [1/2]
const std::list<Graph *> etiss::interfaces::Dot::graphs () inline
Definition at line 223 of file Dot.h.
References graphs_.
graphs() [2/2]
const std::list<Graph *> etiss::interfaces::Dot::graphs () inline
Definition at line 223 of file Dot.h.
References graphs_.
lopenN() [1/2]
Node* etiss::interfaces::Dot::lopenN (const std::list< std::string > & labelpath)
travel/creates sub graphs with the given labels until i find/creates a node for the lase label.
ids will be auto created if neccessary
Attention
if labels are not unique then the selected graphs/nodes are undefined
lopenN() [2/2]
Dot::Node * etiss::interfaces::Dot::lopenN (const std::list< std::string > & labelpath)
travel/creates sub graphs with the given labels until i find/creates a node for the lase label.
ids will be auto created if neccessary
Attention
if labels are not unique then the selected graphs/nodes are undefined
Definition at line 1041 of file Dot.cpp.
References etiss::interfaces::Dot::Graph::asGraph(), and etiss::interfaces::Dot::Graph::nodes().
pcreateN() [1/2]
Node* etiss::interfaces::Dot::pcreateN (Graph * g, const void * id, std::string name = "") inline
Definition at line 228 of file Dot.h.
References createN(), name, and etiss::toString().
pcreateN() [2/2]
Node* etiss::interfaces::Dot::pcreateN (Graph * g, const void * id, std::string name = "") inline
Definition at line 228 of file Dot.h.
References createN(), name, and etiss::toString().
print() [1/2]
virtual void etiss::interfaces::Dot::print (std::ostream & out) virtual
print() [2/2]
void etiss::interfaces::Dot::print (std::ostream & out) virtual
Definition at line 978 of file Dot.cpp.
References etiss::ERROR, and etiss_log.
Member Data Documentation
graphs_
std::list< Graph * > etiss::interfaces::Dot::graphs_ private
Definition at line 218 of file Dot.h.
Referenced by graphs(), and etiss::interfaces::Dot::Graph::~Graph().
idmap_
std::unordered_map< std::string, Node * > etiss::interfaces::Dot::idmap_ private
Definition at line 219 of file Dot.h.
Referenced by etiss::interfaces::Dot::Node::~Node().
The documentation for this class was generated from the following files:
include/etiss/interfaces/Dot.h
/home/runner/work/etiss/etiss/src/interfaces/Dot.cpp