ETISS 0.8.0: IntegratedLibrary Class Reference
IntegratedLibrary Class Reference
LibraryInterface implementation for integrated JIT/CPUArch/Plugin implementations.
Public Member Functions
IntegratedLibrary ()
virtual std::string versionInfo ()
simple version info string. intended to present information in a human readable way.
virtual unsigned countPlugins ()
virtual unsigned countCPUArchs ()
virtual unsigned countJITs ()
virtual std::string nameJIT (unsigned index)
virtual std::string namePlugin (unsigned index)
virtual std::string nameCPUArch (unsigned index)
virtual etiss::JIT * createJIT (unsigned index, std::map< std::string, std::string > options)
virtual etiss::CPUArch * createCPUArch (unsigned index, std::map< std::string, std::string > options)
virtual etiss::Plugin * createPlugin (unsigned index, std::map< std::string, std::string > options)
virtual void deleteJIT (etiss::JIT *o)
virtual void deleteCPUArch (etiss::CPUArch *o)
virtual void deletePlugin (etiss::Plugin *o)
Public Member Functions inherited from etiss::LibraryInterface
LibraryInterface (std::string name)
virtual ~LibraryInterface ()
virtual bool isEmpty ()
returns true if this library provides nothing
virtual const std::string & getName ()
LibraryInterface (std::string name)
virtual ~LibraryInterface ()
virtual bool isEmpty ()
returns true if this library provides nothing
virtual const std::string & getName ()
Additional Inherited Members
Static Public Member Functions inherited from etiss::LibraryInterface
static std::shared_ptr< LibraryInterface > openSharedLibrary (std::string path, std::string name)
static std::shared_ptr< LibraryInterface > openIntegratedLibrary ()
static unsigned getCurrentLibraryVersion ()
static std::shared_ptr< LibraryInterface > openSharedLibrary (std::string path, std::string name)
static std::shared_ptr< LibraryInterface > openIntegratedLibrary ()
static unsigned getCurrentLibraryVersion ()
Detailed Description
LibraryInterface implementation for integrated JIT/CPUArch/Plugin implementations.
wraps example implementation of library functions defined by helper/CPUArchLibrary.h,helper/JITLibrary.h,helper/PluginLibrary.h and implemented in IntegratedLibrary.cpp
Definition at line 67 of file IntegratedLibraryHelper.cpp.
Constructor & Destructor Documentation
IntegratedLibrary()
IntegratedLibrary::IntegratedLibrary () inline
Definition at line 70 of file IntegratedLibraryHelper.cpp.
Member Function Documentation
countCPUArchs()
virtual unsigned IntegratedLibrary::countCPUArchs () inline virtual
Reimplemented from etiss::LibraryInterface.
Definition at line 73 of file IntegratedLibraryHelper.cpp.
References ETISSINCLUDED_countCPUArch().
countJITs()
virtual unsigned IntegratedLibrary::countJITs () inline virtual
Reimplemented from etiss::LibraryInterface.
Definition at line 74 of file IntegratedLibraryHelper.cpp.
References ETISSINCLUDED_countJIT().
countPlugins()
virtual unsigned IntegratedLibrary::countPlugins () inline virtual
Reimplemented from etiss::LibraryInterface.
Definition at line 72 of file IntegratedLibraryHelper.cpp.
References ETISSINCLUDED_countPlugin().
createCPUArch()
virtual etiss::CPUArch* IntegratedLibrary::createCPUArch (unsigned index, std::map< std::string, std::string > options) inline virtual
Reimplemented from etiss::LibraryInterface.
Definition at line 108 of file IntegratedLibraryHelper.cpp.
References ETISSINCLUDED_createCPUArch(), and options.
createJIT()
virtual etiss::JIT* IntegratedLibrary::createJIT (unsigned index, std::map< std::string, std::string > options) inline virtual
Reimplemented from etiss::LibraryInterface.
Definition at line 104 of file IntegratedLibraryHelper.cpp.
References ETISSINCLUDED_createJIT(), and options.
createPlugin()
virtual etiss::Plugin* IntegratedLibrary::createPlugin (unsigned index, std::map< std::string, std::string > options) inline virtual
Reimplemented from etiss::LibraryInterface.
Definition at line 112 of file IntegratedLibraryHelper.cpp.
References ETISSINCLUDED_createPlugin(), and options.
deleteCPUArch()
virtual void IntegratedLibrary::deleteCPUArch (etiss::CPUArch * o) inline virtual
Reimplemented from etiss::LibraryInterface.
Definition at line 118 of file IntegratedLibraryHelper.cpp.
deleteJIT()
virtual void IntegratedLibrary::deleteJIT (etiss::JIT * o) inline virtual
Reimplemented from etiss::LibraryInterface.
Definition at line 117 of file IntegratedLibraryHelper.cpp.
deletePlugin()
virtual void IntegratedLibrary::deletePlugin (etiss::Plugin * o) inline virtual
Reimplemented from etiss::LibraryInterface.
Definition at line 119 of file IntegratedLibraryHelper.cpp.
nameCPUArch()
virtual std::string IntegratedLibrary::nameCPUArch (unsigned index) inline virtual
Reimplemented from etiss::LibraryInterface.
Definition at line 94 of file IntegratedLibraryHelper.cpp.
References ETISSINCLUDED_nameCPUArch(), and name.
nameJIT()
virtual std::string IntegratedLibrary::nameJIT (unsigned index) inline virtual
Reimplemented from etiss::LibraryInterface.
Definition at line 76 of file IntegratedLibraryHelper.cpp.
References ETISSINCLUDED_nameJIT(), and name.
namePlugin()
virtual std::string IntegratedLibrary::namePlugin (unsigned index) inline virtual
Reimplemented from etiss::LibraryInterface.
Definition at line 85 of file IntegratedLibraryHelper.cpp.
References ETISSINCLUDED_namePlugin(), and name.
versionInfo()
virtual std::string IntegratedLibrary::versionInfo () inline virtual
simple version info string. intended to present information in a human readable way.
Reimplemented from etiss::LibraryInterface.
Definition at line 71 of file IntegratedLibraryHelper.cpp.
References ETISS_VERSION_FULL.
The documentation for this class was generated from the following file:
/home/runner/work/etiss/etiss/src/IntegratedLibraryHelper.cpp