ETISS 0.8.0: etiss::plugin::VirtualStructMemory Class Reference
etiss::plugin::VirtualStructMemory Class Reference
allows to read/write to a virtual structure as if it is a memory.
#include <VirtualStructMemory.h>
Public Types
typedef std::map< uint64_t, std::pair< etiss::VirtualStruct::Field *, size_t > > mapping_t
typedef std::map< uint64_t, std::pair< etiss::VirtualStruct::Field *, size_t > > mapping_t
Public Member Functions
VirtualStructMemory (const etiss::VirtualStruct &str, std::function< uint64_t(etiss::VirtualStruct::Field *, bool &)> mountPoint, bool littleendian=true)
virtual ~VirtualStructMemory ()
virtual bool read (bool debug, ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
virtual bool write (bool debug, ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
const mapping_t & getMapping ()
returns the internal mapping
std::set< etiss::VirtualStruct::Field * > getMappedFields ()
uint64_t startAddr ()
uint64_t endAddr ()
VirtualStructMemory (const etiss::VirtualStruct &str, std::function< uint64_t(etiss::VirtualStruct::Field *, bool &)> mountPoint, bool littleendian=true)
virtual ~VirtualStructMemory ()
virtual bool read (bool debug, ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
virtual bool write (bool debug, ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
const mapping_t & getMapping ()
returns the internal mapping
std::set< etiss::VirtualStruct::Field * > getMappedFields ()
uint64_t startAddr ()
uint64_t endAddr ()
Public Member Functions inherited from etiss::SimpleSystem
virtual ~SimpleSystem ()
virtual etiss::int32 iread (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint32 len)
Instruction read operation.
virtual etiss::int32 iwrite (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Instruction write operation.
virtual etiss::int32 dread (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Data read operation.
virtual etiss::int32 dwrite (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Data write operation.
virtual etiss::int32 dbg_read (etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Debug read operation.
virtual etiss::int32 dbg_write (etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Debug write operation.
virtual void syncTime (ETISS_CPU *cpu)
Synchronize simulation time.
virtual ~SimpleSystem ()
virtual etiss::int32 iread (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint32 len)
Instruction read operation.
virtual etiss::int32 iwrite (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Instruction write operation.
virtual etiss::int32 dread (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Data read operation.
virtual etiss::int32 dwrite (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Data write operation.
virtual etiss::int32 dbg_read (etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Debug read operation.
virtual etiss::int32 dbg_write (etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Debug write operation.
virtual void syncTime (ETISS_CPU *cpu)
Synchronize simulation time.
Public Member Functions inherited from etiss::System
virtual ~System ()
virtual ~System ()
Public Attributes
const etiss::VirtualStruct & mem_
Private Attributes
uint64_t startaddr_
uint64_t endaddr_
excluded
mapping_t memmap_
std::list< std::shared_ptr< VirtualStruct::Field > > references
Detailed Description
allows to read/write to a virtual structure as if it is a memory.
Any mapped field is addressed as little endian.
Definition at line 58 of file VirtualStructMemory.h.
Member Typedef Documentation
mapping_t [1/2]
typedef std::map<uint64_t, std::pair<etiss::VirtualStruct::Field * , size_t > > etiss::plugin::VirtualStructMemory::mapping_t
Definition at line 77 of file VirtualStructMemory.h.
mapping_t [2/2]
typedef std::map<uint64_t, std::pair<etiss::VirtualStruct::Field * , size_t > > etiss::plugin::VirtualStructMemory::mapping_t
Definition at line 77 of file VirtualStructMemory.h.
Constructor & Destructor Documentation
VirtualStructMemory() [1/2]
etiss::plugin::VirtualStructMemory::VirtualStructMemory (const etiss::VirtualStruct & str, std::function< uint64_t(etiss::VirtualStruct::Field *, bool &)> mountPoint, bool littleendian = true)
~VirtualStructMemory() [1/2]
etiss::plugin::VirtualStructMemory::~VirtualStructMemory () virtual
Definition at line 84 of file VirtualStructMemory.cpp.
VirtualStructMemory() [2/2]
etiss::plugin::VirtualStructMemory::VirtualStructMemory (const etiss::VirtualStruct & str, std::function< uint64_t(etiss::VirtualStruct::Field *, bool &)> mountPoint, bool littleendian = true)
~VirtualStructMemory() [2/2]
virtual etiss::plugin::VirtualStructMemory::~VirtualStructMemory () virtual
Member Function Documentation
endAddr() [1/2]
uint64_t etiss::plugin::VirtualStructMemory::endAddr () inline
Definition at line 88 of file VirtualStructMemory.h.
References endaddr_.
endAddr() [2/2]
uint64_t etiss::plugin::VirtualStructMemory::endAddr () inline
Definition at line 88 of file VirtualStructMemory.h.
References endaddr_.
getMappedFields() [1/2]
std::set<etiss::VirtualStruct::Field *> etiss::plugin::VirtualStructMemory::getMappedFields ()
getMappedFields() [2/2]
std::set< etiss::VirtualStruct::Field * > etiss::plugin::VirtualStructMemory::getMappedFields ()
Definition at line 146 of file VirtualStructMemory.cpp.
References memmap_.
getMapping() [1/2]
const mapping_t& etiss::plugin::VirtualStructMemory::getMapping () inline
returns the internal mapping
Definition at line 81 of file VirtualStructMemory.h.
References memmap_.
getMapping() [2/2]
const mapping_t& etiss::plugin::VirtualStructMemory::getMapping () inline
returns the internal mapping
Definition at line 81 of file VirtualStructMemory.h.
References memmap_.
read() [1/2]
virtual bool etiss::plugin::VirtualStructMemory::read (bool debug, ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Attention
all mapped fields are addressed as little endian
Implements etiss::SimpleSystem.
read() [2/2]
bool etiss::plugin::VirtualStructMemory::read (bool debug, ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Attention
all mapped fields are addressed as little endian
Implements etiss::SimpleSystem.
Definition at line 89 of file VirtualStructMemory.cpp.
References memmap_, and etiss::VirtualStruct::Field::read().
startAddr() [1/2]
uint64_t etiss::plugin::VirtualStructMemory::startAddr () inline
Definition at line 87 of file VirtualStructMemory.h.
References startaddr_.
startAddr() [2/2]
uint64_t etiss::plugin::VirtualStructMemory::startAddr () inline
Definition at line 87 of file VirtualStructMemory.h.
References startaddr_.
write() [1/2]
virtual bool etiss::plugin::VirtualStructMemory::write (bool debug, ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Attention
all mapped fields are addressed as little endian
Implements etiss::SimpleSystem.
write() [2/2]
bool etiss::plugin::VirtualStructMemory::write (bool debug, ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Attention
all mapped fields are addressed as little endian
Implements etiss::SimpleSystem.
Definition at line 111 of file VirtualStructMemory.cpp.
References memmap_, etiss::VirtualStruct::Field::name_, etiss::VirtualStruct::Field::prettyname_, etiss::VirtualStruct::Field::read(), and etiss::VirtualStruct::Field::write().
Member Data Documentation
endaddr_
uint64_t etiss::plugin::VirtualStructMemory::endaddr_ private
excluded
Definition at line 94 of file VirtualStructMemory.h.
Referenced by endAddr().
mem_
const etiss::VirtualStruct & etiss::plugin::VirtualStructMemory::mem_
Definition at line 75 of file VirtualStructMemory.h.
memmap_
mapping_t etiss::plugin::VirtualStructMemory::memmap_ private
Definition at line 95 of file VirtualStructMemory.h.
Referenced by getMappedFields(), getMapping(), read(), and write().
references
std::list< std::shared_ptr< VirtualStruct::Field > > etiss::plugin::VirtualStructMemory::references private
Definition at line 96 of file VirtualStructMemory.h.
startaddr_
uint64_t etiss::plugin::VirtualStructMemory::startaddr_ private
Definition at line 92 of file VirtualStructMemory.h.
Referenced by startAddr().
The documentation for this class was generated from the following files:
include/etiss/IntegratedLibrary/VirtualStructMemory.h
/home/runner/work/etiss/etiss/src/IntegratedLibrary/VirtualStructMemory.cpp