ETISS 0.8.0: etiss::plugin::gdb::BreakpointDB Class Reference
etiss::plugin::gdb::BreakpointDB Class Reference
structure to store breakpoints
#include <GDBServer.h>
Public Types
enum BPType {
BPTYPE_BREAK_MEM = 1, BPTYPE_BREAK_HW = 2, BPTYPE_WATCH_WRITE = 4, BPTYPE_WATCH_READ = 8,
BPTYPE_BREAK_MEM = 1, BPTYPE_BREAK_HW = 2, BPTYPE_WATCH_WRITE = 4, BPTYPE_WATCH_READ = 8
}
enum BPType {
BPTYPE_BREAK_MEM = 1, BPTYPE_BREAK_HW = 2, BPTYPE_WATCH_WRITE = 4, BPTYPE_WATCH_READ = 8,
BPTYPE_BREAK_MEM = 1, BPTYPE_BREAK_HW = 2, BPTYPE_WATCH_WRITE = 4, BPTYPE_WATCH_READ = 8
}
Public Member Functions
BreakpointDB ()
bool isEmpty ()
etiss::uint32 get (etiss::uint64 addr)
void set (etiss::uint64 addr, etiss::uint32 val)
BreakpointDB ()
bool isEmpty ()
etiss::uint32 get (etiss::uint64 addr)
void set (etiss::uint64 addr, etiss::uint32 val)
Private Attributes
etiss::uint32 **** instrbrkpt_
important: index maps are reversed to instruction pointer e.g pointer(0x0102030405060708) [POINTER != ADDRESS] -> instrbrkpt_[0x0708][0x0506][0x0304][0x0201]
Detailed Description
structure to store breakpoints
Definition at line 79 of file GDBServer.h.
Member Enumeration Documentation
BPType [1/2]
enum etiss::plugin::gdb::BreakpointDB::BPType
Enumerator
BPTYPE_BREAK_MEM
BPTYPE_BREAK_HW
BPTYPE_WATCH_WRITE
BPTYPE_WATCH_READ
BPTYPE_BREAK_MEM
BPTYPE_BREAK_HW
BPTYPE_WATCH_WRITE
BPTYPE_WATCH_READ
Definition at line 82 of file GDBServer.h.
BPType [2/2]
enum etiss::plugin::gdb::BreakpointDB::BPType
Enumerator
BPTYPE_BREAK_MEM
BPTYPE_BREAK_HW
BPTYPE_WATCH_WRITE
BPTYPE_WATCH_READ
BPTYPE_BREAK_MEM
BPTYPE_BREAK_HW
BPTYPE_WATCH_WRITE
BPTYPE_WATCH_READ
Definition at line 82 of file GDBServer.h.
Constructor & Destructor Documentation
BreakpointDB() [1/2]
BreakpointDB::BreakpointDB ()
Definition at line 63 of file GDBServer.cpp.
References instrbrkpt_.
BreakpointDB() [2/2]
etiss::plugin::gdb::BreakpointDB::BreakpointDB ()
Member Function Documentation
get() [1/2]
etiss::uint32 etiss::plugin::gdb::BreakpointDB::get (etiss::uint64 addr) inline
Definition at line 92 of file GDBServer.h.
References instrbrkpt_, and unlikely.
Referenced by etiss::plugin::gdb::Server::handlePacket(), etiss::plugin::gdb::Server::preDReadCallback(), etiss::plugin::gdb::Server::preDWriteCallback(), and etiss::plugin::gdb::Server::preInstructionCallback().
get() [2/2]
etiss::uint32 etiss::plugin::gdb::BreakpointDB::get (etiss::uint64 addr) inline
Definition at line 92 of file GDBServer.h.
References instrbrkpt_, and unlikely.
isEmpty() [1/2]
bool etiss::plugin::gdb::BreakpointDB::isEmpty () inline
Definition at line 91 of file GDBServer.h.
References instrbrkpt_.
Referenced by etiss::plugin::gdb::Server::preDReadCallback(), etiss::plugin::gdb::Server::preDWriteCallback(), and etiss::plugin::gdb::Server::preInstructionCallback().
isEmpty() [2/2]
bool etiss::plugin::gdb::BreakpointDB::isEmpty () inline
Definition at line 91 of file GDBServer.h.
References instrbrkpt_.
set() [1/2]
void BreakpointDB::set (etiss::uint64 addr, etiss::uint32 val)
Definition at line 68 of file GDBServer.cpp.
References instrbrkpt_, and memset().
Referenced by etiss::plugin::gdb::Server::handlePacket().
set() [2/2]
void etiss::plugin::gdb::BreakpointDB::set (etiss::uint64 addr, etiss::uint32 val)
Member Data Documentation
instrbrkpt_
etiss::uint32 **** etiss::plugin::gdb::BreakpointDB::instrbrkpt_ private
important: index maps are reversed to instruction pointer e.g pointer(0x0102030405060708) [POINTER != ADDRESS] -> instrbrkpt_[0x0708][0x0506][0x0304][0x0201]
Definition at line 117 of file GDBServer.h.
Referenced by BreakpointDB(), get(), isEmpty(), and set().
The documentation for this class was generated from the following files:
include/etiss/IntegratedLibrary/gdb/GDBServer.h
/home/runner/work/etiss/etiss/src/IntegratedLibrary/gdb/GDBServer.cpp