ETISS 0.8.0: etiss::interfaces::Dot::Graph Class Reference
etiss::interfaces::Dot::Graph Class Reference
#include <Dot.h>
Public Member Functions
virtual ~Graph ()
Graph * asGraph () override
const std::unordered_set< Node * > & nodes ()
void print (std::ostream &out, std::unordered_set< Link * > &icl) override
virtual ~Graph ()
Graph * asGraph () override
const std::unordered_set< Node * > & nodes ()
void print (std::ostream &out, std::unordered_set< Link * > &icl) override
Public Member Functions inherited from etiss::interfaces::Dot::Node
virtual ~Node ()
const std::unordered_set< Link * > & links ()
virtual ~Node ()
const std::unordered_set< Link * > & links ()
Public Member Functions inherited from etiss::interfaces::Dot::AttrList
void print (std::ostream &out, const std::string &appendedattr)
void print (std::ostream &out, const std::string &appendedattr)
Private Member Functions
Graph (Dot *dot, Graph *parent)
Graph (Dot *dot, Graph *parent)
Private Attributes
std::unordered_set< Node * > nodes_
Friends
class etiss::interfaces::Dot
Additional Inherited Members
Public Attributes inherited from etiss::interfaces::Dot::Node
Dot *const dot_
Graph *const parent_
const std::string id_
Public Attributes inherited from etiss::interfaces::Dot::AttrList
std::string label_
std::string color_
Detailed Description
Definition at line 182 of file Dot.h.
Constructor & Destructor Documentation
Graph() [1/2]
etiss::interfaces::Dot::Graph::Graph (Dot * dot, Graph * parent) inline private
Definition at line 187 of file Dot.h.
~Graph() [1/2]
virtual etiss::interfaces::Dot::Graph::~Graph () inline virtual
Definition at line 190 of file Dot.h.
References etiss::interfaces::Dot::Node::dot_, etiss::interfaces::Dot::graphs_, and nodes_.
Graph() [2/2]
etiss::interfaces::Dot::Graph::Graph (Dot * dot, Graph * parent) inline private
Definition at line 187 of file Dot.h.
~Graph() [2/2]
virtual etiss::interfaces::Dot::Graph::~Graph () inline virtual
Definition at line 190 of file Dot.h.
References etiss::interfaces::Dot::Node::dot_, etiss::interfaces::Dot::graphs_, and nodes_.
Member Function Documentation
asGraph() [1/2]
Graph* etiss::interfaces::Dot::Graph::asGraph () inline override virtual
Reimplemented from etiss::interfaces::Dot::Node.
Definition at line 205 of file Dot.h.
Referenced by etiss::interfaces::Dot::lopenN().
asGraph() [2/2]
Graph* etiss::interfaces::Dot::Graph::asGraph () inline override virtual
Reimplemented from etiss::interfaces::Dot::Node.
Definition at line 205 of file Dot.h.
nodes() [1/2]
const std::unordered_set<Node *>& etiss::interfaces::Dot::Graph::nodes () inline
Definition at line 211 of file Dot.h.
References nodes_.
nodes() [2/2]
const std::unordered_set<Node *>& etiss::interfaces::Dot::Graph::nodes () inline
Definition at line 211 of file Dot.h.
References nodes_.
Referenced by etiss::interfaces::Dot::lopenN().
print() [1/2]
void etiss::interfaces::Dot::Graph::print (std::ostream & out, std::unordered_set< Link * > & icl) override virtual
Reimplemented from etiss::interfaces::Dot::Node.
Definition at line 934 of file Dot.cpp.
References etiss::interfaces::depth(), and etiss::interfaces::graph_contains().
print() [2/2]
void etiss::interfaces::Dot::Graph::print (std::ostream & out, std::unordered_set< Link * > & icl) override virtual
Reimplemented from etiss::interfaces::Dot::Node.
Friends And Related Function Documentation
etiss::interfaces::Dot
etiss::interfaces::Dot friend
Definition at line 184 of file Dot.h.
Member Data Documentation
nodes_
std::unordered_set< Node * > etiss::interfaces::Dot::Graph::nodes_ private
Definition at line 208 of file Dot.h.
Referenced by etiss::interfaces::Dot::Node::Node(), nodes(), ~Graph(), and etiss::interfaces::Dot::Node::~Node().
The documentation for this class was generated from the following files:
include/etiss/interfaces/Dot.h
/home/runner/work/etiss/etiss/src/interfaces/Dot.cpp