ETISS 0.8.0: etiss::plugin::Logger Class Reference
etiss::plugin::Logger Class Reference
simple logger implementation.
#include <Logger.h>
Public Member Functions
Logger (uint64_t addr_value, uint64_t addr_mask)
virtual ETISS_System * wrap (ETISS_CPU *cpu, ETISS_System *system)
change/wrap the passed system structure.
virtual ETISS_System * unwrap (ETISS_CPU *cpu, ETISS_System *system)
undo wrap function call this function will be called AFTER etiss::Plugin::cleanup
virtual int32_t log (bool isread, uint64_t local_addr, uint8_t *buf, unsigned len)
this function writes the content of buf with length len to std::cout.
Logger (uint64_t addr_value, uint64_t addr_mask)
virtual ETISS_System * wrap (ETISS_CPU *cpu, ETISS_System *system)
change/wrap the passed system structure.
virtual ETISS_System * unwrap (ETISS_CPU *cpu, ETISS_System *system)
undo wrap function call this function will be called AFTER etiss::Plugin::cleanup
virtual int32_t log (bool isread, uint64_t local_addr, uint8_t *buf, unsigned len)
this function writes the content of buf with length len to std::cout.
Public Member Functions inherited from etiss::SystemWrapperPlugin
SystemWrapperPlugin ()
virtual ~SystemWrapperPlugin ()
SystemWrapperPlugin ()
virtual ~SystemWrapperPlugin ()
Public Member Functions inherited from etiss::Plugin
virtual ~Plugin ()
unsigned getType ()
InterruptListenerPlugin * getInterruptListenerPlugin ()
CoroutinePlugin * getCoroutinePlugin ()
SystemWrapperPlugin * getSystemWrapperPlugin ()
RegisterDevicePlugin * getRegisterDevicePlugin ()
TranslationPlugin * getTranslationPlugin ()
std::string getPluginName () const
const std::string & getLastAssignedCoreName ()
std::string toString () const
virtual ~Plugin ()
unsigned getType ()
InterruptListenerPlugin * getInterruptListenerPlugin ()
CoroutinePlugin * getCoroutinePlugin ()
SystemWrapperPlugin * getSystemWrapperPlugin ()
RegisterDevicePlugin * getRegisterDevicePlugin ()
TranslationPlugin * getTranslationPlugin ()
std::string getPluginName () const
const std::string & getLastAssignedCoreName ()
std::string toString () const
Public Member Functions inherited from etiss::ToString
ToString ()
virtual ~ToString ()
ToString ()
virtual ~ToString ()
Protected Member Functions
virtual std::string _getPluginName () const
virtual std::string _getPluginName () const
Protected Member Functions inherited from etiss::Plugin
Plugin (unsigned type=0)
virtual void init (ETISS_CPU *cpu, ETISS_System *system, CPUArch *arch)
this function is called before the plugin is used in the cpu execution loop (etiss::CPUCore::execute).
virtual void cleanup ()
this function is called after cpu execution loop (etiss::CPUCore::execute) finished.
void setCorrespondingCPUCoreName (std::string name)
virtual void addedToCPUCore (etiss::CPUCore *core)
called as soon a plugin has been added to its CPUCore.
virtual void removedFromCPUCore (etiss::CPUCore *core)
called as soon a plugin has been removed from its CPUCore.
Plugin (unsigned type=0)
virtual void init (ETISS_CPU *cpu, ETISS_System *system, CPUArch *arch)
this function is called before the plugin is used in the cpu execution loop (etiss::CPUCore::execute).
virtual void cleanup ()
this function is called after cpu execution loop (etiss::CPUCore::execute) finished.
void setCorrespondingCPUCoreName (std::string name)
virtual void addedToCPUCore (etiss::CPUCore *core)
called as soon a plugin has been added to its CPUCore.
virtual void removedFromCPUCore (etiss::CPUCore *core)
called as soon a plugin has been removed from its CPUCore.
Private Attributes
uint64_t addr
uint64_t mask
Additional Inherited Members
Static Public Attributes inherited from etiss::Plugin
static const unsigned INTERRUPTLISTENER = 1 << 0
access to translated code
static const unsigned COROUTINE = 1 << 1
callback after execution of each translated block
static const unsigned SYSTEMWRAPPER = 1 << 2
can wrap/change ETISS_System structure at execution start
static const unsigned REGISTERDEVICE
gets noticed of changes to special registers (e.g. mmu register etc. [depends on architecture])
static const unsigned TRANSLATION
access to translated code during translation phase or when instruction tree is built
Protected Attributes inherited from etiss::Plugin
ETISS_CPU * plugin_cpu_
holds a pointer to the cpu structure. will be set before init call and after cleanup call
ETISS_System * plugin_system_
holds a pointer to the system structure.
CPUArch * plugin_arch_
holds a pointer to the CPUArch instance. will be set before init call and after cleanup call
CPUCore * plugin_core_
holds a pointer to the associated CPUCore instance.
Detailed Description
simple logger implementation.
by overriding log it would also be possible to use this as a device mounted to a certain memory address. due to the function call overhead this is only suggested for testing purposes
Definition at line 59 of file Logger.h.
Constructor & Destructor Documentation
Logger() [1/2]
etiss::plugin::Logger::Logger (uint64_t addr_value, uint64_t addr_mask)
Definition at line 146 of file Logger.cpp.
References addr, etiss::log(), mask, and etiss::WARNING.
Logger() [2/2]
etiss::plugin::Logger::Logger (uint64_t addr_value, uint64_t addr_mask)
Member Function Documentation
_getPluginName() [1/2]
virtual std::string etiss::plugin::Logger::_getPluginName () const inline protected virtual
Implements etiss::Plugin.
Definition at line 77 of file Logger.h.
_getPluginName() [2/2]
virtual std::string etiss::plugin::Logger::_getPluginName () const inline protected virtual
Implements etiss::Plugin.
Definition at line 77 of file Logger.h.
log() [1/2]
int32_t etiss::plugin::Logger::log (bool isread, uint64_t local_addr, uint8_t * buf, unsigned len) virtual
this function writes the content of buf with length len to std::cout.
It is called by write functions if the write address is the specified logger address.
Attention
if called by iread then the buf pointer is NULL
Definition at line 190 of file Logger.cpp.
Referenced by etiss::plugin::dbg_read(), etiss::plugin::dbg_write(), etiss::plugin::dwrite(), etiss::plugin::iread(), and etiss::plugin::iwrite().
log() [2/2]
virtual int32_t etiss::plugin::Logger::log (bool isread, uint64_t local_addr, uint8_t * buf, unsigned len) virtual
this function writes the content of buf with length len to std::cout.
It is called by write functions if the write address is the specified logger address.
Attention
if called by iread then the buf pointer is NULL
unwrap() [1/2]
ETISS_System * etiss::plugin::Logger::unwrap (ETISS_CPU * cpu, ETISS_System * system) virtual
undo wrap function call this function will be called AFTER etiss::Plugin::cleanup
Implements etiss::SystemWrapperPlugin.
Definition at line 180 of file Logger.cpp.
unwrap() [2/2]
virtual ETISS_System* etiss::plugin::Logger::unwrap (ETISS_CPU * cpu, ETISS_System * system) virtual
undo wrap function call this function will be called AFTER etiss::Plugin::cleanup
Implements etiss::SystemWrapperPlugin.
wrap() [1/2]
ETISS_System * etiss::plugin::Logger::wrap (ETISS_CPU * cpu, ETISS_System * system) virtual
change/wrap the passed system structure.
the returned value will be used as the current system this function will be called BEFORE etiss::Plugin::init
Implements etiss::SystemWrapperPlugin.
Definition at line 155 of file Logger.cpp.
References etiss::plugin::LoggerSystem::addr, addr, ETISS_System::dbg_read, etiss::plugin::dbg_read(), ETISS_System::dbg_write, etiss::plugin::dbg_write(), ETISS_System::dread, etiss::plugin::dread(), ETISS_System::dwrite, etiss::plugin::dwrite(), ETISS_System::handle, etiss::plugin::iread(), ETISS_System::iread, etiss::plugin::iwrite(), ETISS_System::iwrite, etiss::plugin::LoggerSystem::mask, mask, etiss::plugin::LoggerSystem::orig, ETISS_System::syncTime, etiss::plugin::syncTime(), etiss::plugin::LoggerSystem::sys, and etiss::plugin::LoggerSystem::this_.
wrap() [2/2]
virtual ETISS_System* etiss::plugin::Logger::wrap (ETISS_CPU * cpu, ETISS_System * system) virtual
change/wrap the passed system structure.
the returned value will be used as the current system this function will be called BEFORE etiss::Plugin::init
Implements etiss::SystemWrapperPlugin.
Member Data Documentation
addr
uint64_t etiss::plugin::Logger::addr private
Definition at line 80 of file Logger.h.
Referenced by Logger(), and wrap().
mask
uint64_t etiss::plugin::Logger::mask private
Definition at line 81 of file Logger.h.
Referenced by Logger(), and wrap().
The documentation for this class was generated from the following files:
include/etiss/IntegratedLibrary/Logger.h
/home/runner/work/etiss/etiss/src/IntegratedLibrary/Logger.cpp