ETISS 0.8.0: etiss::fault::Trigger Class Reference
etiss::fault::Trigger Class Reference
#include <Trigger.h>
Public Types
enum Type {
META_COUNTER, VARIABLEVALUE, TIME, TIMERELATIVE,
NOP, META_COUNTER, VARIABLEVALUE, TIME,
TIMERELATIVE, NOP
}
enum Type {
META_COUNTER, VARIABLEVALUE, TIME, TIMERELATIVE,
NOP, META_COUNTER, VARIABLEVALUE, TIME,
TIMERELATIVE, NOP
}
Public Member Functions
Trigger ()
Type: NOP (no operation)
Trigger (const Trigger &sub, uint64_t count)
This Trigger counts with count how often a sub trigger e.g. VRIABLEVALUE trigger fires. When this sub trigger fires the count 'th time, the META_COUNTER trigger fires itself.
Trigger (const InjectorAddress &target_injector, const std::string &field, uint64_t value)
This Trigger fires when variable field has the value value.
Trigger (const InjectorAddress &target_injector, uint64_t time_ps, bool relative=false)
This Trigger fires when a specific runtime has passed.
Trigger (const Trigger &cpy)
Trigger & operator= (const Trigger &cpy)
~Trigger ()
uint64_t getTriggerCount () const
Trigger & getSubTrigger ()
const Trigger & getSubTrigger () const
uint64_t getTriggerTime () const
const InjectorAddress & getInjectorAddress () const
const Injector_ptr & getInjector () const
bool isNOP () const
const std::string & getTriggerField () const
const uint64_t & getTriggerFieldValue () const
Type getType () const
bool fired (uint64_t time_ps, etiss::fault::Injector *target_injector)
this function checks if the Trigger has just fired.
void resolveTime (uint64_t time)
this function calculates in case of a TIMERELATIVE Trigger a constant TIME trigger
bool isResolved () const
returns if the translation from TIMERELATIVE to TIME trigger has taken place
std::string toString () const
operator<< can be used.
Trigger ()
Type: NOP (no operation)
Trigger (const Trigger &sub, uint64_t count)
This Trigger counts with count how often a sub trigger e.g. VRIABLEVALUE trigger fires. When this sub trigger fires the count 'th time, the META_COUNTER trigger fires itself.
Trigger (const InjectorAddress &target_injector, const std::string &field, uint64_t value)
This Trigger fires when variable field has the value value.
Trigger (const InjectorAddress &target_injector, uint64_t time_ps, bool relative=false)
This Trigger fires when a specific runtime has passed.
Trigger (const Trigger &cpy)
Trigger & operator= (const Trigger &cpy)
~Trigger ()
uint64_t getTriggerCount () const
Trigger & getSubTrigger ()
const Trigger & getSubTrigger () const
uint64_t getTriggerTime () const
const InjectorAddress & getInjectorAddress () const
const Injector_ptr & getInjector () const
bool isNOP () const
const std::string & getTriggerField () const
const uint64_t & getTriggerFieldValue () const
Type getType () const
bool fired (uint64_t time_ps, etiss::fault::Injector *target_injector)
this function checks if the Trigger has just fired.
void resolveTime (uint64_t time)
this function calculates in case of a TIMERELATIVE Trigger a constant TIME trigger
bool isResolved () const
returns if the translation from TIMERELATIVE to TIME trigger has taken place
std::string toString () const
operator<< can be used.
Public Member Functions inherited from etiss::ToString
ToString ()
virtual ~ToString ()
ToString ()
virtual ~ToString ()
Private Member Functions
void ensure (Type type) const
void ensure (Type type) const
Private Attributes
Type type_
std::string field_
Trigger * sub_
InjectorAddress inj_
void * fieldptr_
uint64_t param1_
uint64_t param2_
Detailed Description
Definition at line 84 of file Trigger.h.
Member Enumeration Documentation
Type [1/2]
enum etiss::fault::Trigger::Type
Enumerator
META_COUNTER
VARIABLEVALUE
TIME
TIMERELATIVE
needs to be resolved.
this can only be used in connection with an injection action
NOP
META_COUNTER
VARIABLEVALUE
TIME
TIMERELATIVE
needs to be resolved.
this can only be used in connection with an injection action
NOP
Definition at line 87 of file Trigger.h.
Type [2/2]
enum etiss::fault::Trigger::Type
Enumerator
META_COUNTER
VARIABLEVALUE
TIME
TIMERELATIVE
needs to be resolved.
this can only be used in connection with an injection action
NOP
META_COUNTER
VARIABLEVALUE
TIME
TIMERELATIVE
needs to be resolved.
this can only be used in connection with an injection action
NOP
Definition at line 87 of file Trigger.h.
Constructor & Destructor Documentation
Trigger() [1/10]
etiss::fault::Trigger::Trigger ()
Type: NOP (no operation)
Definition at line 70 of file Trigger.cpp.
References etiss::log(), and etiss::VERBOSE.
Referenced by operator=().
Trigger() [2/10]
etiss::fault::Trigger::Trigger (const Trigger & sub, uint64_t count)
This Trigger counts with count how often a sub trigger e.g. VRIABLEVALUE trigger fires. When this sub trigger fires the count 'th time, the META_COUNTER trigger fires itself.
Note
Type: META_COUNTER
Definition at line 74 of file Trigger.cpp.
References etiss::log(), and etiss::VERBOSE.
Trigger() [3/10]
etiss::fault::Trigger::Trigger (const InjectorAddress & target_injector, const std::string & field, uint64_t value)
This Trigger fires when variable field has the value value.
Note
Type: VARIABLEVALUE
Definition at line 79 of file Trigger.cpp.
References etiss::log(), and etiss::VERBOSE.
Trigger() [4/10]
etiss::fault::Trigger::Trigger (const InjectorAddress & target_injector, uint64_t time_ps, bool relative = false)
This Trigger fires when a specific runtime has passed.
Note
Type: TIMERELATIVE or TIME
Definition at line 84 of file Trigger.cpp.
References etiss::log(), and etiss::VERBOSE.
Trigger() [5/10]
etiss::fault::Trigger::Trigger (const Trigger & cpy)
Definition at line 91 of file Trigger.cpp.
~Trigger() [1/2]
etiss::fault::Trigger::~Trigger ()
Definition at line 143 of file Trigger.cpp.
References fieldptr_, etiss::fault::InjectorAddress::getInjector(), inj_, etiss::fault::InjectorAddress::isResolved(), META_COUNTER, sub_, type_, and VARIABLEVALUE.
Trigger() [6/10]
etiss::fault::Trigger::Trigger ()
Type: NOP (no operation)
Trigger() [7/10]
etiss::fault::Trigger::Trigger (const Trigger & sub, uint64_t count)
This Trigger counts with count how often a sub trigger e.g. VRIABLEVALUE trigger fires. When this sub trigger fires the count 'th time, the META_COUNTER trigger fires itself.
Note
Type: META_COUNTER
Trigger() [8/10]
etiss::fault::Trigger::Trigger (const InjectorAddress & target_injector, const std::string & field, uint64_t value)
This Trigger fires when variable field has the value value.
Note
Type: VARIABLEVALUE
Trigger() [9/10]
etiss::fault::Trigger::Trigger (const InjectorAddress & target_injector, uint64_t time_ps, bool relative = false)
This Trigger fires when a specific runtime has passed.
Note
Type: TIMERELATIVE or TIME
Trigger() [10/10]
etiss::fault::Trigger::Trigger (const Trigger & cpy)
~Trigger() [2/2]
etiss::fault::Trigger::~Trigger ()
Member Function Documentation
ensure() [1/2]
void etiss::fault::Trigger::ensure (Type type) const private
Definition at line 60 of file Trigger.cpp.
References etiss::FATALERROR, etiss::log(), and type_.
Referenced by getSubTrigger(), getTriggerCount(), getTriggerField(), getTriggerFieldValue(), and getTriggerTime().
ensure() [2/2]
void etiss::fault::Trigger::ensure (Type type) const private
fired() [1/2]
bool etiss::fault::Trigger::fired (uint64_t time_ps, etiss::fault::Injector * target_injector)
this function checks if the Trigger has just fired.
TODO decide how to handle the case of multiple trigger checks at the same simulation time
Definition at line 156 of file Trigger.cpp.
References etiss::ERROR, etiss::fault::Injector::fastFieldAccessPtr(), field_, fieldptr_, fired(), etiss::fault::InjectorAddress::getInjector(), etiss::fault::InjectorAddress::getInjectorPath(), inj_, etiss::log(), META_COUNTER, NOP, param1_, param2_, sub_, TIME, type_, VARIABLEVALUE, and etiss::VERBOSE.
Referenced by fired().
fired() [2/2]
bool etiss::fault::Trigger::fired (uint64_t time_ps, etiss::fault::Injector * target_injector)
this function checks if the Trigger has just fired.
getInjector() [1/2]
const Injector_ptr& etiss::fault::Trigger::getInjector () const
getInjector() [2/2]
const Injector_ptr & etiss::fault::Trigger::getInjector () const
Definition at line 300 of file Trigger.cpp.
References etiss::fault::InjectorAddress::getInjector(), getInjector(), inj_, META_COUNTER, sub_, and type_.
Referenced by getInjector().
getInjectorAddress() [1/2]
const InjectorAddress& etiss::fault::Trigger::getInjectorAddress () const
getInjectorAddress() [2/2]
const InjectorAddress & etiss::fault::Trigger::getInjectorAddress () const
Definition at line 296 of file Trigger.cpp.
References inj_.
getSubTrigger() [1/4]
Trigger& etiss::fault::Trigger::getSubTrigger ()
getSubTrigger() [2/4]
const Trigger & etiss::fault::Trigger::getSubTrigger ()
Definition at line 270 of file Trigger.cpp.
References ensure(), META_COUNTER, and sub_.
Referenced by getTriggerField(), getTriggerFieldValue(), getTriggerTime(), isResolved(), and resolveTime().
getSubTrigger() [3/4]
const Trigger& etiss::fault::Trigger::getSubTrigger () const
getSubTrigger() [4/4]
const Trigger& etiss::fault::Trigger::getSubTrigger () const
getTriggerCount() [1/2]
uint64_t etiss::fault::Trigger::getTriggerCount () const
getTriggerCount() [2/2]
uint64_t etiss::fault::Trigger::getTriggerCount () const
Definition at line 265 of file Trigger.cpp.
References ensure(), META_COUNTER, and param1_.
getTriggerField() [1/2]
const std::string & etiss::fault::Trigger::getTriggerField () const
Definition at line 322 of file Trigger.cpp.
References ensure(), field_, getSubTrigger(), getTriggerField(), META_COUNTER, type_, and VARIABLEVALUE.
Referenced by getTriggerField().
getTriggerField() [2/2]
const std::string& etiss::fault::Trigger::getTriggerField () const
getTriggerFieldValue() [1/2]
const uint64_t & etiss::fault::Trigger::getTriggerFieldValue () const
Definition at line 332 of file Trigger.cpp.
References ensure(), getSubTrigger(), getTriggerFieldValue(), META_COUNTER, param1_, type_, and VARIABLEVALUE.
Referenced by getTriggerFieldValue().
getTriggerFieldValue() [2/2]
const uint64_t& etiss::fault::Trigger::getTriggerFieldValue () const
getTriggerTime() [1/2]
uint64_t etiss::fault::Trigger::getTriggerTime () const
getTriggerTime() [2/2]
uint64_t etiss::fault::Trigger::getTriggerTime () const
Definition at line 280 of file Trigger.cpp.
References ensure(), getSubTrigger(), getTriggerTime(), META_COUNTER, param1_, TIME, TIMERELATIVE, and type_.
Referenced by getTriggerTime().
getType() [1/2]
Type etiss::fault::Trigger::getType () const
getType() [2/2]
Trigger::Type etiss::fault::Trigger::getType () const
Definition at line 342 of file Trigger.cpp.
References type_.
isNOP() [1/2]
bool etiss::fault::Trigger::isNOP () const
Definition at line 311 of file Trigger.cpp.
References isNOP(), META_COUNTER, NOP, sub_, and type_.
Referenced by isNOP().
isNOP() [2/2]
bool etiss::fault::Trigger::isNOP () const
isResolved() [1/2]
bool etiss::fault::Trigger::isResolved () const
returns if the translation from TIMERELATIVE to TIME trigger has taken place
isResolved() [2/2]
bool etiss::fault::Trigger::isResolved () const
returns if the translation from TIMERELATIVE to TIME trigger has taken place
Definition at line 256 of file Trigger.cpp.
References getSubTrigger(), isResolved(), META_COUNTER, TIMERELATIVE, and type_.
Referenced by isResolved().
operator=() [1/2]
Trigger& etiss::fault::Trigger::operator= (const Trigger & cpy)
operator=() [2/2]
Trigger & etiss::fault::Trigger::operator= (const Trigger & cpy)
Definition at line 95 of file Trigger.cpp.
References field_, fieldptr_, etiss::fault::InjectorAddress::getInjector(), inj_, etiss::fault::InjectorAddress::isResolved(), META_COUNTER, NOP, param1_, param2_, sub_, TIME, Trigger(), type_, and VARIABLEVALUE.
resolveTime() [1/2]
void etiss::fault::Trigger::resolveTime (uint64_t time)
this function calculates in case of a TIMERELATIVE Trigger a constant TIME trigger
resolveTime() [2/2]
void etiss::fault::Trigger::resolveTime (uint64_t time)
this function calculates in case of a TIMERELATIVE Trigger a constant TIME trigger
Definition at line 242 of file Trigger.cpp.
References getSubTrigger(), etiss::log(), META_COUNTER, param1_, resolveTime(), TIME, TIMERELATIVE, type_, and etiss::VERBOSE.
Referenced by resolveTime().
toString() [1/2]
std::string etiss::fault::Trigger::toString () const
operator<< can be used.
Definition at line 347 of file Trigger.cpp.
References field_, META_COUNTER, NOP, param1_, param2_, TIME, type_, and VARIABLEVALUE.
Referenced by etiss::fault::Injector::acceleratedTrigger(), and etiss::fault::Injector::addTrigger().
toString() [2/2]
std::string etiss::fault::Trigger::toString () const
operator<< can be used.
Member Data Documentation
field_
std::string etiss::fault::Trigger::field_ private
Definition at line 164 of file Trigger.h.
Referenced by fired(), getTriggerField(), operator=(), and toString().
fieldptr_
void * etiss::fault::Trigger::fieldptr_ private
Definition at line 167 of file Trigger.h.
Referenced by fired(), operator=(), and ~Trigger().
inj_
InjectorAddress etiss::fault::Trigger::inj_ private
Definition at line 166 of file Trigger.h.
Referenced by fired(), getInjector(), getInjectorAddress(), operator=(), and ~Trigger().
param1_
uint64_t etiss::fault::Trigger::param1_ private
Definition at line 168 of file Trigger.h.
Referenced by fired(), getTriggerCount(), getTriggerFieldValue(), getTriggerTime(), operator=(), resolveTime(), and toString().
param2_
uint64_t etiss::fault::Trigger::param2_ private
Definition at line 169 of file Trigger.h.
Referenced by fired(), operator=(), and toString().
sub_
Trigger * etiss::fault::Trigger::sub_ private
Definition at line 165 of file Trigger.h.
Referenced by fired(), getInjector(), getSubTrigger(), isNOP(), operator=(), and ~Trigger().
type_
Type etiss::fault::Trigger::type_ private
Definition at line 163 of file Trigger.h.
Referenced by ensure(), fired(), getInjector(), getTriggerField(), getTriggerFieldValue(), getTriggerTime(), getType(), isNOP(), isResolved(), operator=(), resolveTime(), toString(), and ~Trigger().
The documentation for this class was generated from the following files:
include/etiss/fault/Trigger.h
/home/runner/work/etiss/etiss/src/fault/Trigger.cpp