ETISS 0.8.0: etiss::plugin::gdb::PacketProtocol Class Reference
etiss::plugin::gdb::PacketProtocol Class Reference
implements gdb's packet protocol
#include <GDBConnection.h>
Public Member Functions
virtual bool available (bool block=false)
virtual std::string rcv (bool &isnotification)
virtual bool snd (std::string answer, bool isnotification)
virtual bool available (bool block=false)
virtual std::string rcv (bool &isnotification)
virtual bool snd (std::string answer, bool isnotification)
Private Member Functions
PacketProtocol (Connection &connection)
virtual bool _available (bool block)
virtual void tryReadPacket ()
PacketProtocol (Connection &connection)
virtual bool _available (bool block)
virtual void tryReadPacket ()
Private Attributes
std::string buffer
std::string command
bool command_isnotification
Connection & con
bool cfg_noack_
Friends
class Connection
Detailed Description
implements gdb's packet protocol
Definition at line 75 of file GDBConnection.h.
Constructor & Destructor Documentation
PacketProtocol() [1/2]
PacketProtocol::PacketProtocol (Connection & connection) private
Definition at line 72 of file GDBConnection.cpp.
References cfg_noack_.
PacketProtocol() [2/2]
etiss::plugin::gdb::PacketProtocol::PacketProtocol (Connection & connection) private
Member Function Documentation
_available() [1/2]
bool PacketProtocol::_available (bool block) private virtual
Definition at line 166 of file GDBConnection.cpp.
References etiss::plugin::gdb::Connection::available(), buffer, command, con, etiss::plugin::gdb::Connection::rcv(), and tryReadPacket().
Referenced by available().
_available() [2/2]
virtual bool etiss::plugin::gdb::PacketProtocol::_available (bool block) private virtual
available() [1/2]
bool PacketProtocol::available (bool block = false) virtual
Definition at line 150 of file GDBConnection.cpp.
References _available(), cfg_noack_, command, and snd().
Referenced by etiss::plugin::gdb::Server::handlePacket(), and rcv().
available() [2/2]
virtual bool etiss::plugin::gdb::PacketProtocol::available (bool block = false) virtual
rcv() [1/2]
std::string PacketProtocol::rcv (bool & isnotification) virtual
Definition at line 297 of file GDBConnection.cpp.
References available(), command, and command_isnotification.
Referenced by etiss::plugin::gdb::Server::handlePacket().
rcv() [2/2]
virtual std::string etiss::plugin::gdb::PacketProtocol::rcv (bool & isnotification) virtual
snd() [1/2]
virtual bool etiss::plugin::gdb::PacketProtocol::snd (std::string answer, bool isnotification) virtual
snd() [2/2]
bool PacketProtocol::snd (std::string answer, bool isnotification) virtual
Definition at line 306 of file GDBConnection.cpp.
References etiss::plugin::gdb::Connection::available(), buffer, cfg_noack_, con, etiss::plugin::gdb::hex::fromByte(), PacketProtocol_findResponse(), etiss::plugin::gdb::Connection::rcv(), etiss::plugin::gdb::Connection::snd(), and stream_code_info.
Referenced by available(), etiss::plugin::gdb::Server::handlePacket(), etiss::plugin::gdb::Server::postMemAccessCallback(), and etiss::plugin::gdb::Server::preInstructionCallback().
tryReadPacket() [1/2]
virtual void etiss::plugin::gdb::PacketProtocol::tryReadPacket () private virtual
tryReadPacket() [2/2]
void PacketProtocol::tryReadPacket () private virtual
Definition at line 186 of file GDBConnection.cpp.
References buffer, etiss::plugin::gdb::Connection::clearBREAK(), command, command_isnotification, con, int, PacketProtocol_findUE(), etiss::plugin::gdb::Connection::pendingBREAK(), etiss::plugin::gdb::Connection::snd(), stream_code_info, and etiss::plugin::gdb::hex::toByte().
Referenced by _available().
Friends And Related Function Documentation
Connection
Connection friend
Definition at line 77 of file GDBConnection.h.
Member Data Documentation
buffer
std::string etiss::plugin::gdb::PacketProtocol::buffer private
Definition at line 90 of file GDBConnection.h.
Referenced by _available(), snd(), and tryReadPacket().
cfg_noack_
bool etiss::plugin::gdb::PacketProtocol::cfg_noack_ private
Definition at line 94 of file GDBConnection.h.
Referenced by available(), PacketProtocol(), and snd().
command
std::string etiss::plugin::gdb::PacketProtocol::command private
Definition at line 91 of file GDBConnection.h.
Referenced by _available(), available(), rcv(), and tryReadPacket().
command_isnotification
bool etiss::plugin::gdb::PacketProtocol::command_isnotification private
Definition at line 92 of file GDBConnection.h.
Referenced by rcv(), and tryReadPacket().
con
Connection & etiss::plugin::gdb::PacketProtocol::con private
Definition at line 93 of file GDBConnection.h.
Referenced by _available(), snd(), and tryReadPacket().
The documentation for this class was generated from the following files:
include/etiss/IntegratedLibrary/gdb/GDBConnection.h
/home/runner/work/etiss/etiss/src/IntegratedLibrary/gdb/GDBConnection.cpp