ETISS 0.8.0: etiss::LLVMJIT Class Reference
etiss::LLVMJIT Class Reference
#include <LLVMJIT.h>
Public Member Functions
LLVMJIT ()
virtual ~LLVMJIT ()
virtual void * translate (std::string code, std::set< std::string > headerpaths, std::set< std::string > librarypaths, std::set< std::string > libraries, std::string &error, bool debug=false)
translate C code to executable code and return a handle/pointer that identifies the compilation result
virtual void * getFunction (void *handle, std::string name, std::string &error)
returns a function pointer to a compiled function from the handle returned by etiss::JIT::translate
virtual void free (void *handle)
clean up handled returned by etiss::JIT::translate
Public Member Functions inherited from etiss::JIT
JIT (std::string name)
virtual ~JIT ()
std::string getName ()
returns the JIT instance name previously passed to the constructor
JIT (std::string name)
virtual ~JIT ()
std::string getName ()
returns the JIT instance name previously passed to the constructor
Private Attributes
llvm::LLVMContext context_
OrcJit * orcJit_ = nullptr
std::unordered_set< std::string > loadedLibs_
Detailed Description
Definition at line 103 of file LLVMJIT.h.
Constructor & Destructor Documentation
LLVMJIT()
LLVMJIT::LLVMJIT ()
Definition at line 174 of file LLVMJIT.cpp.
References OrcJit::Create(), etiss_jit_llvm_init_done_, etiss_jit_llvm_init_mu_, and orcJit_.
~LLVMJIT()
LLVMJIT::~LLVMJIT () virtual
Definition at line 195 of file LLVMJIT.cpp.
References orcJit_.
Member Function Documentation
free()
void LLVMJIT::free (void * handle) virtual
clean up handled returned by etiss::JIT::translate
Implements etiss::JIT.
Definition at line 294 of file LLVMJIT.cpp.
getFunction()
void * LLVMJIT::getFunction (void * handle, std::string name, std::string & error) virtual
returns a function pointer to a compiled function from the handle returned by etiss::JIT::translate
Implements etiss::JIT.
Definition at line 286 of file LLVMJIT.cpp.
References OrcJit::lookup(), name, and orcJit_.
translate()
void * LLVMJIT::translate (std::string code, std::set< std::string > headerpaths, std::set< std::string > librarypaths, std::set< std::string > libraries, std::string & error, bool debug = false) virtual
translate C code to executable code and return a handle/pointer that identifies the compilation result
Parameters
code generated code
headerpaths paths where required header files are located
librarypaths paths where required libraries are located (usually not needed since libraries don't require full linking)
libraries file names of required libraries (usually not needed since libraries don't require full linking)
error string to return additional error information
debug if true then compilation should try to enable gdb to jump into compiled functions
Implements etiss::JIT.
Definition at line 200 of file LLVMJIT.cpp.
References OrcJit::addModule(), OrcJit::getContext(), etiss::jitFiles(), loadedLibs_, OrcJit::loadLib(), and orcJit_.
Member Data Documentation
context_
llvm::LLVMContext etiss::LLVMJIT::context_ private
Definition at line 114 of file LLVMJIT.h.
loadedLibs_
std::unordered_set<std::string> etiss::LLVMJIT::loadedLibs_ private
Definition at line 116 of file LLVMJIT.h.
Referenced by translate().
orcJit_
OrcJit* etiss::LLVMJIT::orcJit_ = nullptr private
Definition at line 115 of file LLVMJIT.h.
Referenced by getFunction(), LLVMJIT(), translate(), and ~LLVMJIT().
The documentation for this class was generated from the following files:
/home/runner/work/etiss/etiss/JITImpl/LLVM/include/LLVMJIT.h
/home/runner/work/etiss/etiss/JITImpl/LLVM/src/LLVMJIT.cpp