ETISS 0.8.0: etiss::fault::Action Class Reference
etiss::fault::Action Class Reference
#include <Action.h>
Public Types
enum Type {
BITFLIP, COMMAND, NOP, INJECTION,
BITFLIP, COMMAND, NOP, INJECTION
}
enum Type {
BITFLIP, COMMAND, NOP, INJECTION,
BITFLIP, COMMAND, NOP, INJECTION
}
Public Member Functions
Action ()
Action (const InjectorAddress &inj, const std::string &command)
abstract string command will be passed to the targeted injector
Action (const InjectorAddress &inj, const std::string &field, unsigned bit)
the bit at the given position of the given field of the given injector will be flipped
Action (const Fault &fault)
injects a fault. this is especially usefull with Triggers of type TIMERELATIVE
Type getType () const
const InjectorAddress & getInjectorAddress () const
const std::string & getCommand () const
COMMAND only.
const std::string & getTargetField () const
BITFLIP only.
unsigned getTargetBit () const
BITFLIP only.
const Fault & getFault () const
INJECTION only.
std::string toString () const
operator<< can be used.
Action ()
Action (const InjectorAddress &inj, const std::string &command)
abstract string command will be passed to the targeted injector
Action (const InjectorAddress &inj, const std::string &field, unsigned bit)
the bit at the given position of the given field of the given injector will be flipped
Action (const Fault &fault)
injects a fault. this is especially usefull with Triggers of type TIMERELATIVE
Type getType () const
const InjectorAddress & getInjectorAddress () const
const std::string & getCommand () const
COMMAND only.
const std::string & getTargetField () const
BITFLIP only.
unsigned getTargetBit () const
const Fault & getFault () const
INJECTION only.
std::string toString () const
operator<< can be used.
Public Member Functions inherited from etiss::ToString
ToString ()
virtual ~ToString ()
ToString ()
virtual ~ToString ()
Private Member Functions
void ensure (Type)
void ensure (Type)
Private Attributes
Type type_
type of the Attribute
InjectorAddress inj_
std::string command_
command e.g. for booting OR1KVCPU
std::string field_
concerning Field (for fault injection)
unsigned bit_
concerning Bit (for fault injection)
std::vector< Fault > fault_
for other injections
Detailed Description
Definition at line 77 of file Action.h.
Member Enumeration Documentation
Type [1/2]
enum etiss::fault::Action::Type
Enumerator
BITFLIP
applies a bit flip to a bit in a specified field
COMMAND
commands are targetet at Injectors, not fields.
in case a command is targetet at a certain field that information must be passed within the command string
NOP
NO Operation. used by default constructor.
INJECTION
an action that injects a fault definition (trigger + actions)
BITFLIP
applies a bit flip to a bit in a specified field
COMMAND
commands are targetet at Injectors, not fields.
in case a command is targetet at a certain field that information must be passed within the command string
NOP
NO Operation. used by default constructor.
INJECTION
an action that injects a fault definition (trigger + actions)
Definition at line 80 of file Action.h.
Type [2/2]
enum etiss::fault::Action::Type
Enumerator
BITFLIP
applies a bit flip to a bit in a specified field
COMMAND
commands are targetet at Injectors, not fields.
in case a command is targetet at a certain field that information must be passed within the command string
NOP
NO Operation. used by default constructor.
INJECTION
an action that injects a fault definition (trigger + actions)
BITFLIP
applies a bit flip to a bit in a specified field
COMMAND
commands are targetet at Injectors, not fields.
in case a command is targetet at a certain field that information must be passed within the command string
NOP
NO Operation. used by default constructor.
INJECTION
an action that injects a fault definition (trigger + actions)
Definition at line 80 of file Action.h.
Constructor & Destructor Documentation
Action() [1/8]
etiss::fault::Action::Action ()
Note
Type: NOP (no operation)
Definition at line 62 of file Action.cpp.
References etiss::log(), and etiss::VERBOSE.
Action() [2/8]
etiss::fault::Action::Action (const InjectorAddress & inj, const std::string & command)
abstract string command will be passed to the targeted injector
Note
Type: Command
Definition at line 67 of file Action.cpp.
References etiss::fault::InjectorAddress::getInjectorPath(), etiss::log(), and etiss::VERBOSE.
Action() [3/8]
etiss::fault::Action::Action (const InjectorAddress & inj, const std::string & field, unsigned bit)
the bit at the given position of the given field of the given injector will be flipped
Note
Type: BitFlip
Definition at line 73 of file Action.cpp.
References etiss::fault::InjectorAddress::getInjectorPath(), etiss::log(), and etiss::VERBOSE.
Action() [4/8]
etiss::fault::Action::Action (const Fault & fault)
injects a fault. this is especially usefull with Triggers of type TIMERELATIVE
Note
Type: Injection
Definition at line 81 of file Action.cpp.
References fault_, etiss::log(), etiss::fault::Fault::toString(), and etiss::VERBOSE.
Action() [5/8]
etiss::fault::Action::Action ()
Note
Type: NOP (no operation)
Action() [6/8]
etiss::fault::Action::Action (const InjectorAddress & inj, const std::string & command)
abstract string command will be passed to the targeted injector
Note
Type: Command
Action() [7/8]
etiss::fault::Action::Action (const InjectorAddress & inj, const std::string & field, unsigned bit)
the bit at the given position of the given field of the given injector will be flipped
Note
Type: BitFlip
Action() [8/8]
etiss::fault::Action::Action (const Fault & fault)
injects a fault. this is especially usefull with Triggers of type TIMERELATIVE
Note
Type: Injection
Member Function Documentation
ensure() [1/2]
void etiss::fault::Action::ensure (Type t) private
Definition at line 56 of file Action.cpp.
References type_.
ensure() [2/2]
void etiss::fault::Action::ensure (Type) private
getCommand() [1/2]
const std::string & etiss::fault::Action::getCommand () const
COMMAND only.
Definition at line 99 of file Action.cpp.
References command_.
getCommand() [2/2]
const std::string& etiss::fault::Action::getCommand () const
COMMAND only.
getFault() [1/2]
const Fault & etiss::fault::Action::getFault () const
INJECTION only.
Definition at line 116 of file Action.cpp.
References fault_, INJECTION, and type_.
getFault() [2/2]
const Fault& etiss::fault::Action::getFault () const
INJECTION only.
getInjectorAddress() [1/2]
const InjectorAddress& etiss::fault::Action::getInjectorAddress () const
getInjectorAddress() [2/2]
const InjectorAddress & etiss::fault::Action::getInjectorAddress () const
Definition at line 93 of file Action.cpp.
References inj_.
getTargetBit() [1/2]
unsigned etiss::fault::Action::getTargetBit () const
BITFLIP only.
Definition at line 111 of file Action.cpp.
References bit_.
Referenced by etiss::VirtualStruct::applyAction().
getTargetBit() [2/2]
unsigned etiss::fault::Action::getTargetBit () const
getTargetField() [1/2]
const std::string & etiss::fault::Action::getTargetField () const
BITFLIP only.
Definition at line 105 of file Action.cpp.
References field_.
Referenced by etiss::VirtualStruct::applyAction().
getTargetField() [2/2]
const std::string& etiss::fault::Action::getTargetField () const
BITFLIP only.
getType() [1/2]
Type etiss::fault::Action::getType () const
getType() [2/2]
Action::Type etiss::fault::Action::getType () const
Definition at line 88 of file Action.cpp.
References type_.
Referenced by etiss::VirtualStruct::applyAction().
toString() [1/2]
std::string etiss::fault::Action::toString () const
operator<< can be used.
toString() [2/2]
std::string etiss::fault::Action::toString () const
operator<< can be used.
Definition at line 123 of file Action.cpp.
References pugi::xml_node::append_child(), pugi::xml_document::load(), and pugi::xml_document::save().
Member Data Documentation
bit_
unsigned etiss::fault::Action::bit_ private
concerning Bit (for fault injection)
Definition at line 139 of file Action.h.
Referenced by getTargetBit().
command_
std::string etiss::fault::Action::command_ private
command e.g. for booting OR1KVCPU
Definition at line 137 of file Action.h.
Referenced by getCommand().
fault_
std::vector< Fault > etiss::fault::Action::fault_ private
for other injections
Definition at line 140 of file Action.h.
Referenced by Action(), and getFault().
field_
std::string etiss::fault::Action::field_ private
concerning Field (for fault injection)
Definition at line 138 of file Action.h.
Referenced by getTargetField().
inj_
InjectorAddress etiss::fault::Action::inj_ private
Definition at line 136 of file Action.h.
Referenced by getInjectorAddress().
type_
Type etiss::fault::Action::type_ private
type of the Attribute
Definition at line 135 of file Action.h.
Referenced by ensure(), getFault(), and getType().
The documentation for this class was generated from the following files:
include/etiss/fault/Action.h
/home/runner/work/etiss/etiss/src/fault/Action.cpp