ETISS 0.8.0: xml_buffered_writer Class Reference
xml_buffered_writer Class Reference
Public Types
enum { bufcapacitybytes, bufcapacity = bufcapacitybytes / (sizeof(char_t) + 4) }
Public Member Functions
xml_buffered_writer (xml_writer &writer_, xml_encoding user_encoding)
~xml_buffered_writer ()
void flush ()
void flush (const char_t *data, size_t size)
void write (const char_t *data, size_t length)
void write (const char_t *data)
void write (char_t d0)
void write (char_t d0, char_t d1)
void write (char_t d0, char_t d1, char_t d2)
void write (char_t d0, char_t d1, char_t d2, char_t d3)
void write (char_t d0, char_t d1, char_t d2, char_t d3, char_t d4)
void write (char_t d0, char_t d1, char_t d2, char_t d3, char_t d4, char_t d5)
Public Attributes
char_t buffer [bufcapacity]
union {
uint8_t data_u8 [4 *bufcapacity]
uint16_t data_u16 [2 *bufcapacity]
uint32_t data_u32 [bufcapacity]
char_t data_char [bufcapacity]
} scratch
xml_writer & writer
size_t bufsize
xml_encoding encoding
Private Member Functions
xml_buffered_writer (const xml_buffered_writer &)
xml_buffered_writer & operator= (const xml_buffered_writer &)
Detailed Description
Definition at line 3216 of file pugixml.cpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
bufcapacitybytes
bufcapacity
Definition at line 3371 of file pugixml.cpp.
Constructor & Destructor Documentation
xml_buffered_writer() [1/2]
xml_buffered_writer::xml_buffered_writer (const xml_buffered_writer &) private
xml_buffered_writer() [2/2]
xml_buffered_writer::xml_buffered_writer (xml_writer & writer_, xml_encoding user_encoding) inline
Definition at line 3222 of file pugixml.cpp.
References bufcapacity, and PUGI__STATIC_ASSERT.
~xml_buffered_writer()
xml_buffered_writer::~xml_buffered_writer () inline
Definition at line 3228 of file pugixml.cpp.
References flush().
Member Function Documentation
flush() [1/2]
void xml_buffered_writer::flush () inline
Definition at line 3230 of file pugixml.cpp.
References buffer, and bufsize.
Referenced by write(), and ~xml_buffered_writer().
flush() [2/2]
void xml_buffered_writer::flush (const char_t * data, size_t size) inline
Definition at line 3236 of file pugixml.cpp.
References convert_buffer_output(), encoding, get_write_native_encoding(), scratch, and writer.
operator=()
xml_buffered_writer& xml_buffered_writer::operator= (const xml_buffered_writer &) private
write() [1/8]
void xml_buffered_writer::write (char_t d0) inline
Definition at line 3299 of file pugixml.cpp.
References bufcapacity, buffer, bufsize, and flush().
write() [2/8]
void xml_buffered_writer::write (char_t d0, char_t d1) inline
Definition at line 3308 of file pugixml.cpp.
References bufcapacity, buffer, bufsize, and flush().
write() [3/8]
void xml_buffered_writer::write (char_t d0, char_t d1, char_t d2) inline
Definition at line 3318 of file pugixml.cpp.
References bufcapacity, buffer, bufsize, and flush().
write() [4/8]
void xml_buffered_writer::write (char_t d0, char_t d1, char_t d2, char_t d3) inline
Definition at line 3329 of file pugixml.cpp.
References bufcapacity, buffer, bufsize, and flush().
write() [5/8]
void xml_buffered_writer::write (char_t d0, char_t d1, char_t d2, char_t d3, char_t d4) inline
Definition at line 3341 of file pugixml.cpp.
References bufcapacity, buffer, bufsize, and flush().
write() [6/8]
void xml_buffered_writer::write (char_t d0, char_t d1, char_t d2, char_t d3, char_t d4, char_t d5) inline
Definition at line 3354 of file pugixml.cpp.
References bufcapacity, buffer, bufsize, and flush().
write() [7/8]
void xml_buffered_writer::write (const char_t * data) inline
Definition at line 3297 of file pugixml.cpp.
References strlength(), and write().
Referenced by write().
write() [8/8]
void xml_buffered_writer::write (const char_t * data, size_t length) inline
Definition at line 3256 of file pugixml.cpp.
References bufcapacity, buffer, bufsize, encoding, flush(), get_valid_length(), get_write_native_encoding(), length(), memcpy(), and writer.
Referenced by node_output(), node_output_attributes(), text_output(), text_output_cdata(), and text_output_escaped().
Member Data Documentation
buffer
char_t xml_buffered_writer::buffer[bufcapacity]
Definition at line 3383 of file pugixml.cpp.
Referenced by flush(), and write().
bufsize
size_t xml_buffered_writer::bufsize
Definition at line 3393 of file pugixml.cpp.
Referenced by flush(), and write().
data_char
char_t xml_buffered_writer::data_char[bufcapacity]
Definition at line 3389 of file pugixml.cpp.
data_u16
uint16_t xml_buffered_writer::data_u16[2 *bufcapacity]
Definition at line 3387 of file pugixml.cpp.
data_u32
uint32_t xml_buffered_writer::data_u32[bufcapacity]
Definition at line 3388 of file pugixml.cpp.
data_u8
uint8_t xml_buffered_writer::data_u8[4 *bufcapacity]
Definition at line 3386 of file pugixml.cpp.
encoding
xml_encoding xml_buffered_writer::encoding
Definition at line 3394 of file pugixml.cpp.
Referenced by flush(), and write().
scratch
union { ... } xml_buffered_writer::scratch
Referenced by flush().
writer
xml_writer& xml_buffered_writer::writer
Definition at line 3392 of file pugixml.cpp.
Referenced by flush(), and write().
The documentation for this class was generated from the following file:
/home/runner/work/etiss/etiss/src/fault/xml/pugixml.cpp