ETISS 0.8.0: CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER > Class Template Reference
CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER > Class Template Reference
Simple INI file reader.
#include <SimpleIni.h>
Classes
class Converter
Characterset conversion utility class to convert strings to the same format as is used for the storage.
struct Entry
key entry
class FileWriter
OutputWriter class to write the INI data to a file.
class OutputWriter
interface definition for the OutputWriter object to pass to Save() in order to output the INI file data.
class StringWriter
OutputWriter class to write the INI data to a string.
Public Types
typedef SI_CHAR SI_CHAR_T
typedef std::multimap< Entry, const SI_CHAR *, typename Entry::KeyOrder > TKeyVal
map keys to values
typedef std::map< Entry, TKeyVal, typename Entry::KeyOrder > TSection
map sections to key/value map
typedef std::list< Entry > TNamesDepend
set of dependent string pointers.
typedef SI_CHAR SI_CHAR_T
typedef std::multimap< Entry, const SI_CHAR *, typename Entry::KeyOrder > TKeyVal
map keys to values
typedef std::map< Entry, TKeyVal, typename Entry::KeyOrder > TSection
map sections to key/value map
typedef std::list< Entry > TNamesDepend
set of dependent string pointers.
Public Member Functions
CSimpleIniTempl (bool a_bIsUtf8=false, bool a_bMultiKey=false, bool a_bMultiLine=false)
Default constructor.
~CSimpleIniTempl ()
Destructor.
void Reset ()
Deallocate all memory stored by this object.
bool IsEmpty () const
Has any data been loaded.
SI_Error LoadFile (const char *a_pszFile)
Load an INI file from disk into memory.
SI_Error LoadFile (FILE *a_fpFile)
Load the file from a file pointer.
SI_Error LoadData (const std::string &a_strData)
Load INI file data direct from a std::string.
SI_Error LoadData (const char *a_pData, size_t a_uDataLen)
Load INI file data direct from memory.
SI_Error SaveFile (const char *a_pszFile, bool a_bAddSignature=true) const
Save an INI file from memory to disk.
SI_Error SaveFile (FILE *a_pFile, bool a_bAddSignature=false) const
Save the INI data to a file.
SI_Error Save (OutputWriter &a_oOutput, bool a_bAddSignature=false) const
Save the INI data.
SI_Error Save (std::string &a_sBuffer, bool a_bAddSignature=false) const
Append the INI data to a string.
void GetAllSections (TNamesDepend &a_names) const
Retrieve all section names.
bool GetAllKeys (const SI_CHAR *a_pSection, TNamesDepend &a_names) const
Retrieve all unique key names in a section.
bool GetAllValues (const SI_CHAR *a_pSection, const SI_CHAR *a_pKey, TNamesDepend &a_values) const
Retrieve all values for a specific key.
int GetSectionSize (const SI_CHAR *a_pSection) const
Query the number of keys in a specific section.
const TKeyVal * GetSection (const SI_CHAR *a_pSection) const
Retrieve all key and value pairs for a section.
const SI_CHAR * GetValue (const SI_CHAR *a_pSection, const SI_CHAR *a_pKey, const SI_CHAR *a_pDefault=NULL, bool *a_pHasMultiple=NULL) const
Retrieve the value for a specific key.
long GetLongValue (const SI_CHAR *a_pSection, const SI_CHAR *a_pKey, long a_nDefault=0, bool *a_pHasMultiple=NULL) const
Retrieve a numeric value for a specific key.
double GetDoubleValue (const SI_CHAR *a_pSection, const SI_CHAR *a_pKey, double a_nDefault=0, bool *a_pHasMultiple=NULL) const
Retrieve a numeric value for a specific key.
bool GetBoolValue (const SI_CHAR *a_pSection, const SI_CHAR *a_pKey, bool a_bDefault=false, bool *a_pHasMultiple=NULL) const
Retrieve a boolean value for a specific key.
SI_Error SetValue (const SI_CHAR *a_pSection, const SI_CHAR *a_pKey, const SI_CHAR *a_pValue, const SI_CHAR *a_pComment=NULL, bool a_bForceReplace=false)
Add or update a section or value.
SI_Error SetLongValue (const SI_CHAR *a_pSection, const SI_CHAR *a_pKey, long a_nValue, const SI_CHAR *a_pComment=NULL, bool a_bUseHex=false, bool a_bForceReplace=false)
Add or update a numeric value.
SI_Error SetDoubleValue (const SI_CHAR *a_pSection, const SI_CHAR *a_pKey, double a_nValue, const SI_CHAR *a_pComment=NULL, bool a_bForceReplace=false)
Add or update a double value.
SI_Error SetBoolValue (const SI_CHAR *a_pSection, const SI_CHAR *a_pKey, bool a_bValue, const SI_CHAR *a_pComment=NULL, bool a_bForceReplace=false)
Add or update a boolean value.
bool Delete (const SI_CHAR *a_pSection, const SI_CHAR *a_pKey, bool a_bRemoveEmpty=false)
Delete an entire section, or a key from a section.
bool DeleteValue (const SI_CHAR *a_pSection, const SI_CHAR *a_pKey, const SI_CHAR *a_pValue, bool a_bRemoveEmpty=false)
Delete an entire section, or a key from a section.
Converter GetConverter () const
Return a conversion object to convert text to the same encoding as is used by the Save(), SaveFile() and SaveString() functions.
CSimpleIniTempl (bool a_bIsUtf8=false, bool a_bMultiKey=false, bool a_bMultiLine=false)
Default constructor.
~CSimpleIniTempl ()
Destructor.
void Reset ()
Deallocate all memory stored by this object.
bool IsEmpty () const
Has any data been loaded.
SI_Error LoadFile (const char *a_pszFile)
Load an INI file from disk into memory.
SI_Error LoadFile (FILE *a_fpFile)
Load the file from a file pointer.
SI_Error LoadData (const std::string &a_strData)
Load INI file data direct from a std::string.
SI_Error LoadData (const char *a_pData, size_t a_uDataLen)
Load INI file data direct from memory.
SI_Error SaveFile (const char *a_pszFile, bool a_bAddSignature=true) const
Save an INI file from memory to disk.
SI_Error SaveFile (FILE *a_pFile, bool a_bAddSignature=false) const
Save the INI data to a file.
SI_Error Save (OutputWriter &a_oOutput, bool a_bAddSignature=false) const
Save the INI data.
SI_Error Save (std::string &a_sBuffer, bool a_bAddSignature=false) const
Append the INI data to a string.
void GetAllSections (TNamesDepend &a_names) const
Retrieve all section names.
bool GetAllKeys (const SI_CHAR *a_pSection, TNamesDepend &a_names) const
Retrieve all unique key names in a section.
bool GetAllValues (const SI_CHAR *a_pSection, const SI_CHAR *a_pKey, TNamesDepend &a_values) const
Retrieve all values for a specific key.
int GetSectionSize (const SI_CHAR *a_pSection) const
Query the number of keys in a specific section.
const TKeyVal * GetSection (const SI_CHAR *a_pSection) const
Retrieve all key and value pairs for a section.
const SI_CHAR * GetValue (const SI_CHAR *a_pSection, const SI_CHAR *a_pKey, const SI_CHAR *a_pDefault=NULL, bool *a_pHasMultiple=NULL) const
Retrieve the value for a specific key.
long GetLongValue (const SI_CHAR *a_pSection, const SI_CHAR *a_pKey, long a_nDefault=0, bool *a_pHasMultiple=NULL) const
Retrieve a numeric value for a specific key.
double GetDoubleValue (const SI_CHAR *a_pSection, const SI_CHAR *a_pKey, double a_nDefault=0, bool *a_pHasMultiple=NULL) const
Retrieve a numeric value for a specific key.
bool GetBoolValue (const SI_CHAR *a_pSection, const SI_CHAR *a_pKey, bool a_bDefault=false, bool *a_pHasMultiple=NULL) const
Retrieve a boolean value for a specific key.
SI_Error SetValue (const SI_CHAR *a_pSection, const SI_CHAR *a_pKey, const SI_CHAR *a_pValue, const SI_CHAR *a_pComment=NULL, bool a_bForceReplace=false)
Add or update a section or value.
SI_Error SetLongValue (const SI_CHAR *a_pSection, const SI_CHAR *a_pKey, long a_nValue, const SI_CHAR *a_pComment=NULL, bool a_bUseHex=false, bool a_bForceReplace=false)
Add or update a numeric value.
SI_Error SetDoubleValue (const SI_CHAR *a_pSection, const SI_CHAR *a_pKey, double a_nValue, const SI_CHAR *a_pComment=NULL, bool a_bForceReplace=false)
Add or update a double value.
SI_Error SetBoolValue (const SI_CHAR *a_pSection, const SI_CHAR *a_pKey, bool a_bValue, const SI_CHAR *a_pComment=NULL, bool a_bForceReplace=false)
Add or update a boolean value.
bool Delete (const SI_CHAR *a_pSection, const SI_CHAR *a_pKey, bool a_bRemoveEmpty=false)
Delete an entire section, or a key from a section.
bool DeleteValue (const SI_CHAR *a_pSection, const SI_CHAR *a_pKey, const SI_CHAR *a_pValue, bool a_bRemoveEmpty=false)
Delete an entire section, or a key from a section.
Converter GetConverter () const
Return a conversion object to convert text to the same encoding as is used by the Save(), SaveFile() and SaveString() functions.
Settings
void SetUnicode (bool a_bIsUtf8=true)
Set the storage format of the INI data.
bool IsUnicode () const
Get the storage format of the INI data.
void SetMultiKey (bool a_bAllowMultiKey=true)
Should multiple identical keys be permitted in the file.
bool IsMultiKey () const
Get the storage format of the INI data.
void SetMultiLine (bool a_bAllowMultiLine=true)
Should data values be permitted to span multiple lines in the file.
bool IsMultiLine () const
Query the status of multi-line data.
void SetSpaces (bool a_bSpaces=true)
Should spaces be added around the equals sign when writing key/value pairs out.
bool UsingSpaces () const
Query the status of spaces output.
void SetUnicode (bool a_bIsUtf8=true)
Set the storage format of the INI data.
bool IsUnicode () const
Get the storage format of the INI data.
void SetMultiKey (bool a_bAllowMultiKey=true)
Should multiple identical keys be permitted in the file.
bool IsMultiKey () const
Get the storage format of the INI data.
void SetMultiLine (bool a_bAllowMultiLine=true)
Should data values be permitted to span multiple lines in the file.
bool IsMultiLine () const
Query the status of multi-line data.
void SetSpaces (bool a_bSpaces=true)
Should spaces be added around the equals sign when writing key/value pairs out.
bool UsingSpaces () const
Query the status of spaces output.
Private Member Functions
CSimpleIniTempl (const CSimpleIniTempl &)
CSimpleIniTempl & operator= (const CSimpleIniTempl &)
SI_Error FindFileComment (SI_CHAR *&a_pData, bool a_bCopyStrings)
Parse the data looking for a file comment and store it if found.
bool FindEntry (SI_CHAR *&a_pData, const SI_CHAR *&a_pSection, const SI_CHAR *&a_pKey, const SI_CHAR *&a_pVal, const SI_CHAR *&a_pComment) const
Parse the data looking for the next valid entry.
SI_Error AddEntry (const SI_CHAR *a_pSection, const SI_CHAR *a_pKey, const SI_CHAR *a_pValue, const SI_CHAR *a_pComment, bool a_bForceReplace, bool a_bCopyStrings)
Add the section/key/value to our data.
bool IsSpace (SI_CHAR ch) const
Is the supplied character a whitespace character?
bool IsComment (SI_CHAR ch) const
Does the supplied character start a comment line?
void SkipNewLine (SI_CHAR *&a_pData) const
Skip over a newline character (or characters) for either DOS or UNIX.
SI_Error CopyString (const SI_CHAR *&a_pString)
Make a copy of the supplied string, replacing the original pointer.
void DeleteString (const SI_CHAR *a_pString)
Delete a string from the copied strings buffer if necessary.
bool IsLess (const SI_CHAR *a_pLeft, const SI_CHAR *a_pRight) const
Internal use of our string comparison function.
bool IsMultiLineTag (const SI_CHAR *a_pData) const
bool IsMultiLineData (const SI_CHAR *a_pData) const
bool LoadMultiLineText (SI_CHAR *&a_pData, const SI_CHAR *&a_pVal, const SI_CHAR *a_pTagName, bool a_bAllowBlankLinesInComment=false) const
bool IsNewLineChar (SI_CHAR a_c) const
bool OutputMultiLineText (OutputWriter &a_oOutput, Converter &a_oConverter, const SI_CHAR *a_pText) const
CSimpleIniTempl (const CSimpleIniTempl &)
CSimpleIniTempl & operator= (const CSimpleIniTempl &)
SI_Error FindFileComment (SI_CHAR *&a_pData, bool a_bCopyStrings)
Parse the data looking for a file comment and store it if found.
bool FindEntry (SI_CHAR *&a_pData, const SI_CHAR *&a_pSection, const SI_CHAR *&a_pKey, const SI_CHAR *&a_pVal, const SI_CHAR *&a_pComment) const
Parse the data looking for the next valid entry.
SI_Error AddEntry (const SI_CHAR *a_pSection, const SI_CHAR *a_pKey, const SI_CHAR *a_pValue, const SI_CHAR *a_pComment, bool a_bForceReplace, bool a_bCopyStrings)
Add the section/key/value to our data.
bool IsSpace (SI_CHAR ch) const
Is the supplied character a whitespace character?
bool IsComment (SI_CHAR ch) const
Does the supplied character start a comment line?
void SkipNewLine (SI_CHAR *&a_pData) const
Skip over a newline character (or characters) for either DOS or UNIX.
SI_Error CopyString (const SI_CHAR *&a_pString)
Make a copy of the supplied string, replacing the original pointer.
void DeleteString (const SI_CHAR *a_pString)
Delete a string from the copied strings buffer if necessary.
bool IsLess (const SI_CHAR *a_pLeft, const SI_CHAR *a_pRight) const
Internal use of our string comparison function.
bool IsMultiLineTag (const SI_CHAR *a_pData) const
bool IsMultiLineData (const SI_CHAR *a_pData) const
bool LoadMultiLineText (SI_CHAR *&a_pData, const SI_CHAR *&a_pVal, const SI_CHAR *a_pTagName, bool a_bAllowBlankLinesInComment=false) const
bool IsNewLineChar (SI_CHAR a_c) const
bool OutputMultiLineText (OutputWriter &a_oOutput, Converter &a_oConverter, const SI_CHAR *a_pText) const
Private Attributes
SI_CHAR * m_pData
Copy of the INI file data in our character format.
size_t m_uDataLen
Length of the data that we have stored.
const SI_CHAR * m_pFileComment
File comment for this data, if one exists.
TSection m_data
Parsed INI data.
TNamesDepend m_strings
This vector stores allocated memory for copies of strings that have been supplied after the file load.
bool m_bStoreIsUtf8
Is the format of our datafile UTF-8 or MBCS?
bool m_bAllowMultiKey
Are multiple values permitted for the same key?
bool m_bAllowMultiLine
Are data values permitted to span multiple lines?
bool m_bSpaces
Should spaces be written out surrounding the equals sign?
int m_nOrder
Next order value, used to ensure sections and keys are output in the same order that they are loaded/added.
Detailed Description
template<class SI_CHAR, class SI_STRLESS, class SI_CONVERTER>
class CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >
Simple INI file reader.
This can be instantiated with the choice of unicode or native characterset, and case sensitive or insensitive comparisons of section and key names. The supported combinations are pre-defined with the following typedefs:
Interface Case-sensitive Typedef
char No CSimpleIniA
char Yes CSimpleIniCaseA
wchar_t No CSimpleIniW
wchar_t Yes CSimpleIniCaseW
Note that using other types for the SI_CHAR is supported. For instance, unsigned char, unsigned short, etc. Note that where the alternative type is a different size to char/wchar_t you may need to supply new helper classes for SI_STRLESS and SI_CONVERTER.
Definition at line 297 of file SimpleIni.h.
Member Typedef Documentation
SI_CHAR_T [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > typedef SI_CHAR CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SI_CHAR_T
Definition at line 300 of file SimpleIni.h.
SI_CHAR_T [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > typedef SI_CHAR CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SI_CHAR_T
Definition at line 300 of file SimpleIni.h.
TKeyVal [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > typedef std::multimap<Entry, const SI_CHAR *, typename Entry::KeyOrder> CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::TKeyVal
map keys to values
Definition at line 354 of file SimpleIni.h.
TKeyVal [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > typedef std::multimap<Entry, const SI_CHAR *, typename Entry::KeyOrder> CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::TKeyVal
map keys to values
Definition at line 354 of file SimpleIni.h.
TNamesDepend [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > typedef std::list<Entry> CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::TNamesDepend
set of dependent string pointers.
Note that these pointers are dependent on memory owned by CSimpleIni.
Definition at line 362 of file SimpleIni.h.
TNamesDepend [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > typedef std::list<Entry> CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::TNamesDepend
set of dependent string pointers.
Note that these pointers are dependent on memory owned by CSimpleIni.
Definition at line 362 of file SimpleIni.h.
TSection [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > typedef std::map<Entry, TKeyVal, typename Entry::KeyOrder> CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::TSection
map sections to key/value map
Definition at line 357 of file SimpleIni.h.
TSection [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > typedef std::map<Entry, TKeyVal, typename Entry::KeyOrder> CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::TSection
map sections to key/value map
Definition at line 357 of file SimpleIni.h.
Constructor & Destructor Documentation
CSimpleIniTempl() [1/4]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::CSimpleIniTempl (bool a_bIsUtf8 = false, bool a_bMultiKey = false, bool a_bMultiLine = false)
Default constructor.
Parameters
a_bIsUtf8 See the method SetUnicode() for details.
a_bMultiKey See the method SetMultiKey() for details.
a_bMultiLine See the method SetMultiLine() for details.
Definition at line 1166 of file SimpleIni.h.
~CSimpleIniTempl() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::~CSimpleIniTempl
Destructor.
Definition at line 1180 of file SimpleIni.h.
CSimpleIniTempl() [2/4]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::CSimpleIniTempl (const CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER > &) private
CSimpleIniTempl() [3/4]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::CSimpleIniTempl (bool a_bIsUtf8 = false, bool a_bMultiKey = false, bool a_bMultiLine = false)
Default constructor.
Parameters
a_bIsUtf8 See the method SetUnicode() for details.
a_bMultiKey See the method SetMultiKey() for details.
a_bMultiLine See the method SetMultiLine() for details.
~CSimpleIniTempl() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::~CSimpleIniTempl ()
Destructor.
CSimpleIniTempl() [4/4]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::CSimpleIniTempl (const CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER > &) private
Member Function Documentation
AddEntry() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > SI_Error CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::AddEntry (const SI_CHAR * a_pSection, const SI_CHAR * a_pKey, const SI_CHAR * a_pValue, const SI_CHAR * a_pComment, bool a_bForceReplace, bool a_bCopyStrings) private
Add the section/key/value to our data.
Parameters
a_pSection Section name. Sections will be created if they don't already exist.
a_pKey Key name. May be NULL to create an empty section. Existing entries will be updated. New entries will be created.
a_pValue Value for the key.
a_pComment Comment to be associated with the section or the key. If a_pKey is NULL then it will be associated with the section, otherwise the key. This must be a string in full comment form already (have a comment character starting every line).
a_bForceReplace Should all existing values in a multi-key INI file be replaced with this entry. This option has no effect if not using multi-key files. The difference between Delete/AddEntry and AddEntry with a_bForceReplace = true, is that the load order and comment will be preserved this way.
a_bCopyStrings Should copies of the strings be made or not. If false then the pointers will be used as is.
Definition at line 1787 of file SimpleIni.h.
References NULL, CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Entry::pComment, SI_ASSERT, SI_INSERTED, and SI_UPDATED.
Referenced by CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SetValue().
AddEntry() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > SI_Error CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::AddEntry (const SI_CHAR * a_pSection, const SI_CHAR * a_pKey, const SI_CHAR * a_pValue, const SI_CHAR * a_pComment, bool a_bForceReplace, bool a_bCopyStrings) private
Add the section/key/value to our data.
Parameters
a_pSection Section name. Sections will be created if they don't already exist.
a_pKey Key name. May be NULL to create an empty section. Existing entries will be updated. New entries will be created.
a_pValue Value for the key.
a_pComment Comment to be associated with the section or the key. If a_pKey is NULL then it will be associated with the section, otherwise the key. This must be a string in full comment form already (have a comment character starting every line).
a_bForceReplace Should all existing values in a multi-key INI file be replaced with this entry. This option has no effect if not using multi-key files. The difference between Delete/AddEntry and AddEntry with a_bForceReplace = true, is that the load order and comment will be preserved this way.
a_bCopyStrings Should copies of the strings be made or not. If false then the pointers will be used as is.
CopyString() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > SI_Error CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::CopyString (const SI_CHAR *& a_pString) private
Make a copy of the supplied string, replacing the original pointer.
Definition at line 1758 of file SimpleIni.h.
References memcpy(), SI_NOMEM, and SI_OK.
CopyString() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > SI_Error CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::CopyString (const SI_CHAR *& a_pString) private
Make a copy of the supplied string, replacing the original pointer.
Delete() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Delete (const SI_CHAR * a_pSection, const SI_CHAR * a_pKey, bool a_bRemoveEmpty = false)
Delete an entire section, or a key from a section.
Note that the data returned by GetSection is invalid and must not be used after anything has been deleted from that section using this method. Note when multiple keys is enabled, this will delete all keys with that name; to selectively delete individual key/values, use DeleteValue.
Parameters
a_pSection Section to delete key from, or if a_pKey is NULL, the section to remove.
a_pKey Key to remove from the section. Set to NULL to remove the entire section.
a_bRemoveEmpty If the section is empty after this key has been deleted, should the empty section be removed?
Returns
true Key or section was deleted.
false Key or section was not found.
Definition at line 2480 of file SimpleIni.h.
References NULL.
Delete() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Delete (const SI_CHAR * a_pSection, const SI_CHAR * a_pKey, bool a_bRemoveEmpty = false)
Delete an entire section, or a key from a section.
Note that the data returned by GetSection is invalid and must not be used after anything has been deleted from that section using this method. Note when multiple keys is enabled, this will delete all keys with that name; to selectively delete individual key/values, use DeleteValue.
Parameters
a_pSection Section to delete key from, or if a_pKey is NULL, the section to remove.
a_pKey Key to remove from the section. Set to NULL to remove the entire section.
a_bRemoveEmpty If the section is empty after this key has been deleted, should the empty section be removed?
Returns
true Key or section was deleted.
false Key or section was not found.
DeleteString() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > void CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::DeleteString (const SI_CHAR * a_pString) private
Delete a string from the copied strings buffer if necessary.
Definition at line 2562 of file SimpleIni.h.
DeleteString() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > void CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::DeleteString (const SI_CHAR * a_pString) private
Delete a string from the copied strings buffer if necessary.
DeleteValue() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::DeleteValue (const SI_CHAR * a_pSection, const SI_CHAR * a_pKey, const SI_CHAR * a_pValue, bool a_bRemoveEmpty = false)
Delete an entire section, or a key from a section.
If value is provided, only remove keys with the value. Note that the data returned by GetSection is invalid and must not be used after anything has been deleted from that section using this method. Note when multiple keys is enabled, all keys with the value will be deleted.
Parameters
a_pSection Section to delete key from, or if a_pKey is NULL, the section to remove.
a_pKey Key to remove from the section. Set to NULL to remove the entire section.
a_pValue Value of key to remove from the section. Set to NULL to remove all keys.
a_bRemoveEmpty If the section is empty after this key has been deleted, should the empty section be removed?
Returns
true Key/value or section was deleted.
false Key/value or section was not found.
Definition at line 2487 of file SimpleIni.h.
References NULL.
DeleteValue() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::DeleteValue (const SI_CHAR * a_pSection, const SI_CHAR * a_pKey, const SI_CHAR * a_pValue, bool a_bRemoveEmpty = false)
Delete an entire section, or a key from a section.
If value is provided, only remove keys with the value. Note that the data returned by GetSection is invalid and must not be used after anything has been deleted from that section using this method. Note when multiple keys is enabled, all keys with the value will be deleted.
Parameters
a_pSection Section to delete key from, or if a_pKey is NULL, the section to remove.
a_pKey Key to remove from the section. Set to NULL to remove the entire section.
a_pValue Value of key to remove from the section. Set to NULL to remove all keys.
a_bRemoveEmpty If the section is empty after this key has been deleted, should the empty section be removed?
Returns
true Key/value or section was deleted.
false Key/value or section was not found.
FindEntry() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::FindEntry (SI_CHAR *& a_pData, const SI_CHAR *& a_pSection, const SI_CHAR *& a_pKey, const SI_CHAR *& a_pVal, const SI_CHAR *& a_pComment) const private
Parse the data looking for the next valid entry.
The memory pointed to by a_pData is modified by inserting NULL characters. The pointer is updated to the current location in the block of text.
Definition at line 1420 of file SimpleIni.h.
References NULL.
FindEntry() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::FindEntry (SI_CHAR *& a_pData, const SI_CHAR *& a_pSection, const SI_CHAR *& a_pKey, const SI_CHAR *& a_pVal, const SI_CHAR *& a_pComment) const private
Parse the data looking for the next valid entry.
The memory pointed to by a_pData is modified by inserting NULL characters. The pointer is updated to the current location in the block of text.
FindFileComment() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > SI_Error CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::FindFileComment (SI_CHAR *& a_pData, bool a_bCopyStrings) private
Parse the data looking for a file comment and store it if found.
Definition at line 1393 of file SimpleIni.h.
References NULL, and SI_OK.
FindFileComment() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > SI_Error CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::FindFileComment (SI_CHAR *& a_pData, bool a_bCopyStrings) private
Parse the data looking for a file comment and store it if found.
GetAllKeys() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::GetAllKeys (const SI_CHAR * a_pSection, TNamesDepend & a_names) const
Retrieve all unique key names in a section.
The sort order of the returned strings is NOT DEFINED. You can sort the names into the load order if desired. Search this file for ".sort" for an example. Only unique key names are returned.
NOTE! This structure contains only pointers to strings. The actual string data is stored in memory owned by CSimpleIni. Ensure that the CSimpleIni object is not destroyed or Reset() while these strings are in use!
Parameters
a_pSection Section to request data for
a_names List that will receive all of the key names. See note above!
Returns
true Section was found.
false Matching section was not found.
GetAllKeys() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::GetAllKeys (const SI_CHAR * a_pSection, TNamesDepend & a_names) const
Retrieve all unique key names in a section.
The sort order of the returned strings is NOT DEFINED. You can sort the names into the load order if desired. Search this file for ".sort" for an example. Only unique key names are returned.
NOTE! This structure contains only pointers to strings. The actual string data is stored in memory owned by CSimpleIni. Ensure that the CSimpleIni object is not destroyed or Reset() while these strings are in use!
Parameters
a_pSection Section to request data for
a_names List that will receive all of the key names. See note above!
Returns
true Section was found.
false Matching section was not found.
Definition at line 2229 of file SimpleIni.h.
References NULL.
Referenced by etiss_loadIniConfigs(), and etiss::Initializer::loadIniPlugins().
GetAllSections() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > void CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::GetAllSections (TNamesDepend & a_names) const
Retrieve all section names.
The list is returned as an STL vector of names and can be iterated or searched as necessary. Note that the sort order of the returned strings is NOT DEFINED. You can sort the names into the load order if desired. Search this file for ".sort" for an example.
NOTE! This structure contains only pointers to strings. The actual string data is stored in memory owned by CSimpleIni. Ensure that the CSimpleIni object is not destroyed or Reset() while these pointers are in use!
Parameters
a_names Vector that will receive all of the section names. See note above!
Definition at line 2218 of file SimpleIni.h.
Referenced by etiss_loadIniConfigs(), and etiss::Initializer::loadIniPlugins().
GetAllSections() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > void CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::GetAllSections (TNamesDepend & a_names) const
Retrieve all section names.
The list is returned as an STL vector of names and can be iterated or searched as necessary. Note that the sort order of the returned strings is NOT DEFINED. You can sort the names into the load order if desired. Search this file for ".sort" for an example.
NOTE! This structure contains only pointers to strings. The actual string data is stored in memory owned by CSimpleIni. Ensure that the CSimpleIni object is not destroyed or Reset() while these pointers are in use!
Parameters
a_names Vector that will receive all of the section names. See note above!
GetAllValues() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::GetAllValues (const SI_CHAR * a_pSection, const SI_CHAR * a_pKey, TNamesDepend & a_values) const
Retrieve all values for a specific key.
This method can be used when multiple keys are both enabled and disabled. Note that the sort order of the returned strings is NOT DEFINED. You can sort the names into the load order if desired. Search this file for ".sort" for an example.
NOTE! The returned values are pointers to string data stored in memory owned by CSimpleIni. Ensure that the CSimpleIni object is not destroyed or Reset while you are using this pointer!
Parameters
a_pSection Section to search
a_pKey Key to search for
a_values List to return if the key is not found
Returns
true Key was found.
false Matching section/key was not found.
GetAllValues() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::GetAllValues (const SI_CHAR * a_pSection, const SI_CHAR * a_pKey, TNamesDepend & a_values) const
Retrieve all values for a specific key.
This method can be used when multiple keys are both enabled and disabled. Note that the sort order of the returned strings is NOT DEFINED. You can sort the names into the load order if desired. Search this file for ".sort" for an example.
NOTE! The returned values are pointers to string data stored in memory owned by CSimpleIni. Ensure that the CSimpleIni object is not destroyed or Reset while you are using this pointer!
Parameters
a_pSection Section to search
a_pKey Key to search for
a_values List to return if the key is not found
Returns
true Key was found.
false Matching section/key was not found.
Definition at line 2130 of file SimpleIni.h.
Referenced by etiss_loadIniConfigs(), and etiss::Initializer::loadIniPlugins().
GetBoolValue() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::GetBoolValue (const SI_CHAR * a_pSection, const SI_CHAR * a_pKey, bool a_bDefault = false, bool * a_pHasMultiple = NULL) const
Retrieve a boolean value for a specific key.
If multiple keys are enabled (see SetMultiKey) then only the first value associated with that key will be returned, see GetAllValues for getting all values with multikey.
Strings starting with "t", "y", "on" or "1" are returned as logically true. Strings starting with "f", "n", "of" or "0" are returned as logically false. For all other values the default is returned. Character comparisons are case-insensitive.
Parameters
a_pSection Section to search
a_pKey Key to search for
a_bDefault Value to return if the key is not found
a_pHasMultiple Optionally receive notification of if there are multiple entries for this key.
Returns
a_nDefault Key was not found in the section
other Value of the key
GetBoolValue() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::GetBoolValue (const SI_CHAR * a_pSection, const SI_CHAR * a_pKey, bool a_bDefault = false, bool * a_pHasMultiple = NULL) const
Retrieve a boolean value for a specific key.
If multiple keys are enabled (see SetMultiKey) then only the first value associated with that key will be returned, see GetAllValues for getting all values with multikey.
Strings starting with "t", "y", "on" or "1" are returned as logically true. Strings starting with "f", "n", "of" or "0" are returned as logically false. For all other values the default is returned. Character comparisons are case-insensitive.
Parameters
a_pSection Section to search
a_pKey Key to search for
a_bDefault Value to return if the key is not found
a_pHasMultiple Optionally receive notification of if there are multiple entries for this key.
Returns
a_nDefault Key was not found in the section
other Value of the key
Definition at line 2069 of file SimpleIni.h.
References NULL.
GetConverter() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > Converter CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::GetConverter () const inline
Return a conversion object to convert text to the same encoding as is used by the Save(), SaveFile() and SaveString() functions.
Use this to prepare the strings that you wish to append or prepend to the output INI data.
Definition at line 1038 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_bStoreIsUtf8.
GetConverter() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > Converter CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::GetConverter () const inline
Return a conversion object to convert text to the same encoding as is used by the Save(), SaveFile() and SaveString() functions.
Use this to prepare the strings that you wish to append or prepend to the output INI data.
Definition at line 1038 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_bStoreIsUtf8.
GetDoubleValue() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > double CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::GetDoubleValue (const SI_CHAR * a_pSection, const SI_CHAR * a_pKey, double a_nDefault = 0, bool * a_pHasMultiple = NULL) const
Retrieve a numeric value for a specific key.
If multiple keys are enabled (see SetMultiKey) then only the first value associated with that key will be returned, see GetAllValues for getting all values with multikey.
Parameters
a_pSection Section to search
a_pKey Key to search for
a_nDefault Value to return if the key is not found
a_pHasMultiple Optionally receive notification of if there are multiple entries for this key.
Returns
a_nDefault Key was not found in the section
other Value of the key
GetDoubleValue() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > double CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::GetDoubleValue (const SI_CHAR * a_pSection, const SI_CHAR * a_pKey, double a_nDefault = 0, bool * a_pHasMultiple = NULL) const
Retrieve a numeric value for a specific key.
If multiple keys are enabled (see SetMultiKey) then only the first value associated with that key will be returned, see GetAllValues for getting all values with multikey.
Parameters
a_pSection Section to search
a_pKey Key to search for
a_nDefault Value to return if the key is not found
a_pHasMultiple Optionally receive notification of if there are multiple entries for this key.
Returns
a_nDefault Key was not found in the section
other Value of the key
Definition at line 2012 of file SimpleIni.h.
References c, and NULL.
GetLongValue() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > long CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::GetLongValue (const SI_CHAR * a_pSection, const SI_CHAR * a_pKey, long a_nDefault = 0, bool * a_pHasMultiple = NULL) const
Retrieve a numeric value for a specific key.
If multiple keys are enabled (see SetMultiKey) then only the first value associated with that key will be returned, see GetAllValues for getting all values with multikey.
Parameters
a_pSection Section to search
a_pKey Key to search for
a_nDefault Value to return if the key is not found
a_pHasMultiple Optionally receive notification of if there are multiple entries for this key.
Returns
a_nDefault Key was not found in the section
other Value of the key
GetLongValue() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > long CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::GetLongValue (const SI_CHAR * a_pSection, const SI_CHAR * a_pKey, long a_nDefault = 0, bool * a_pHasMultiple = NULL) const
Retrieve a numeric value for a specific key.
If multiple keys are enabled (see SetMultiKey) then only the first value associated with that key will be returned, see GetAllValues for getting all values with multikey.
Parameters
a_pSection Section to search
a_pKey Key to search for
a_nDefault Value to return if the key is not found
a_pHasMultiple Optionally receive notification of if there are multiple entries for this key.
Returns
a_nDefault Key was not found in the section
other Value of the key
Definition at line 1945 of file SimpleIni.h.
References c, and NULL.
Referenced by etiss_loadIniConfigs().
GetSection() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > const TKeyVal* CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::GetSection (const SI_CHAR * a_pSection) const
Retrieve all key and value pairs for a section.
The data is returned as a pointer to an STL map and can be iterated or searched as desired. Note that multiple entries for the same key may exist when multiple keys have been enabled.
NOTE! This structure contains only pointers to strings. The actual string data is stored in memory owned by CSimpleIni. Ensure that the CSimpleIni object is not destroyed or Reset() while these strings are in use!
Parameters
a_pSection Name of the section to return
Returns
boolean Was a section matching the supplied name found.
GetSection() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > const CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::TKeyVal * CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::GetSection (const SI_CHAR * a_pSection) const
Retrieve all key and value pairs for a section.
The data is returned as a pointer to an STL map and can be iterated or searched as desired. Note that multiple entries for the same key may exist when multiple keys have been enabled.
NOTE! This structure contains only pointers to strings. The actual string data is stored in memory owned by CSimpleIni. Ensure that the CSimpleIni object is not destroyed or Reset() while these strings are in use!
Parameters
a_pSection Name of the section to return
Returns
boolean Was a section matching the supplied name found.
Definition at line 2204 of file SimpleIni.h.
GetSectionSize() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > int CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::GetSectionSize (const SI_CHAR * a_pSection) const
Query the number of keys in a specific section.
Note that if multiple keys are enabled, then this value may be different to the number of keys returned by GetAllKeys.
Parameters
a_pSection Section to request data for
Returns
-1 Section does not exist in the file
>=0 Number of keys in the section
GetSectionSize() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > int CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::GetSectionSize (const SI_CHAR * a_pSection) const
Query the number of keys in a specific section.
Note that if multiple keys are enabled, then this value may be different to the number of keys returned by GetAllKeys.
Parameters
a_pSection Section to request data for
Returns
-1 Section does not exist in the file
>=0 Number of keys in the section
Definition at line 2166 of file SimpleIni.h.
References NULL.
GetValue() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > const SI_CHAR* CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::GetValue (const SI_CHAR * a_pSection, const SI_CHAR * a_pKey, const SI_CHAR * a_pDefault = NULL, bool * a_pHasMultiple = NULL) const
Retrieve the value for a specific key.
If multiple keys are enabled (see SetMultiKey) then only the first value associated with that key will be returned, see GetAllValues for getting all values with multikey.
NOTE! The returned value is a pointer to string data stored in memory owned by CSimpleIni. Ensure that the CSimpleIni object is not destroyed or Reset while you are using this pointer!
Parameters
a_pSection Section to search
a_pKey Key to search for
a_pDefault Value to return if the key is not found
a_pHasMultiple Optionally receive notification of if there are multiple entries for this key.
Returns
a_pDefault Key was not found in the section
other Value of the key
GetValue() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > const SI_CHAR * CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::GetValue (const SI_CHAR * a_pSection, const SI_CHAR * a_pKey, const SI_CHAR * a_pDefault = NULL, bool * a_pHasMultiple = NULL) const
Retrieve the value for a specific key.
If multiple keys are enabled (see SetMultiKey) then only the first value associated with that key will be returned, see GetAllValues for getting all values with multikey.
NOTE! The returned value is a pointer to string data stored in memory owned by CSimpleIni. Ensure that the CSimpleIni object is not destroyed or Reset while you are using this pointer!
Parameters
a_pSection Section to search
a_pKey Key to search for
a_pDefault Value to return if the key is not found
a_pHasMultiple Optionally receive notification of if there are multiple entries for this key.
Returns
a_pDefault Key was not found in the section
other Value of the key
Definition at line 1904 of file SimpleIni.h.
IsComment() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::IsComment (SI_CHAR ch) const inline private
Does the supplied character start a comment line?
Definition at line 1088 of file SimpleIni.h.
IsComment() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::IsComment (SI_CHAR ch) const inline private
Does the supplied character start a comment line?
Definition at line 1088 of file SimpleIni.h.
IsEmpty() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::IsEmpty () const inline
Has any data been loaded.
Definition at line 473 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_data.
IsEmpty() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::IsEmpty () const inline
Has any data been loaded.
Definition at line 473 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_data.
IsLess() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::IsLess (const SI_CHAR * a_pLeft, const SI_CHAR * a_pRight) const inline private
Internal use of our string comparison function.
Definition at line 1103 of file SimpleIni.h.
IsLess() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::IsLess (const SI_CHAR * a_pLeft, const SI_CHAR * a_pRight) const inline private
Internal use of our string comparison function.
Definition at line 1103 of file SimpleIni.h.
IsMultiKey() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::IsMultiKey () const inline
Get the storage format of the INI data.
Definition at line 522 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_bAllowMultiKey.
IsMultiKey() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::IsMultiKey () const inline
Get the storage format of the INI data.
Definition at line 522 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_bAllowMultiKey.
IsMultiLine() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::IsMultiLine () const inline
Query the status of multi-line data.
Definition at line 534 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_bAllowMultiLine.
IsMultiLine() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::IsMultiLine () const inline
Query the status of multi-line data.
Definition at line 534 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_bAllowMultiLine.
IsMultiLineData() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::IsMultiLineData (const SI_CHAR * a_pData) const private
Definition at line 1581 of file SimpleIni.h.
IsMultiLineData() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::IsMultiLineData (const SI_CHAR * a_pData) const private
IsMultiLineTag() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::IsMultiLineTag (const SI_CHAR * a_pData) const private
IsMultiLineTag() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::IsMultiLineTag (const SI_CHAR * a_pData) const private
Definition at line 1568 of file SimpleIni.h.
IsNewLineChar() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::IsNewLineChar (SI_CHAR a_c) const private
Definition at line 1620 of file SimpleIni.h.
IsNewLineChar() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::IsNewLineChar (SI_CHAR a_c) const private
IsSpace() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::IsSpace (SI_CHAR ch) const inline private
Is the supplied character a whitespace character?
Definition at line 1085 of file SimpleIni.h.
IsSpace() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::IsSpace (SI_CHAR ch) const inline private
Is the supplied character a whitespace character?
Definition at line 1085 of file SimpleIni.h.
IsUnicode() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::IsUnicode () const inline
Get the storage format of the INI data.
Definition at line 499 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_bStoreIsUtf8.
IsUnicode() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::IsUnicode () const inline
Get the storage format of the INI data.
Definition at line 499 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_bStoreIsUtf8.
LoadData() [1/4]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > SI_Error CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::LoadData (const char * a_pData, size_t a_uDataLen)
Load INI file data direct from memory.
Parameters
a_pData Data to be loaded
a_uDataLen Length of the data in bytes
Returns
SI_Error See error definitions
Definition at line 1295 of file SimpleIni.h.
References memset(), NULL, SI_FAIL, SI_NOMEM, SI_OK, and SI_UTF8_SIGNATURE.
LoadData() [2/4]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > SI_Error CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::LoadData (const char * a_pData, size_t a_uDataLen)
Load INI file data direct from memory.
Parameters
a_pData Data to be loaded
a_uDataLen Length of the data in bytes
Returns
SI_Error See error definitions
LoadData() [3/4]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > SI_Error CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::LoadData (const std::string & a_strData) inline
Load INI file data direct from a std::string.
Parameters
a_strData Data to be loaded
Returns
SI_Error See error definitions
Definition at line 596 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::LoadData().
Referenced by CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::LoadData().
LoadData() [4/4]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > SI_Error CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::LoadData (const std::string & a_strData) inline
Load INI file data direct from a std::string.
Parameters
a_strData Data to be loaded
Returns
SI_Error See error definitions
Definition at line 596 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::LoadData().
Referenced by CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::LoadData().
LoadFile() [1/4]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > SI_Error CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::LoadFile (const char * a_pszFile)
Load an INI file from disk into memory.
Parameters
a_pszFile Path of the file to be loaded. This will be passed to fopen() and so must be a valid path for the current platform.
Returns
SI_Error See error definitions
Definition at line 1211 of file SimpleIni.h.
References NULL, and SI_FILE.
Referenced by etiss_loadIni().
LoadFile() [2/4]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > SI_Error CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::LoadFile (const char * a_pszFile)
Load an INI file from disk into memory.
Parameters
a_pszFile Path of the file to be loaded. This will be passed to fopen() and so must be a valid path for the current platform.
Returns
SI_Error See error definitions
LoadFile() [3/4]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > SI_Error CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::LoadFile (FILE * a_fpFile)
Load the file from a file pointer.
Parameters
a_fpFile Valid file pointer to read the file data from. The file will be read until end of file.
Returns
SI_Error See error definitions
Definition at line 1253 of file SimpleIni.h.
References SI_FILE, SI_NOMEM, and SI_OK.
LoadFile() [4/4]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > SI_Error CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::LoadFile (FILE * a_fpFile)
Load the file from a file pointer.
Parameters
a_fpFile Valid file pointer to read the file data from. The file will be read until end of file.
Returns
SI_Error See error definitions
LoadMultiLineText() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::LoadMultiLineText (SI_CHAR *& a_pData, const SI_CHAR *& a_pVal, const SI_CHAR * a_pTagName, bool a_bAllowBlankLinesInComment = false) const private
Definition at line 1626 of file SimpleIni.h.
References NULL, and SI_ASSERT.
LoadMultiLineText() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::LoadMultiLineText (SI_CHAR *& a_pData, const SI_CHAR *& a_pVal, const SI_CHAR * a_pTagName, bool a_bAllowBlankLinesInComment = false) const private
operator=() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > CSimpleIniTempl& CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::operator= (const CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER > &) private
operator=() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > CSimpleIniTempl& CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::operator= (const CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER > &) private
OutputMultiLineText() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::OutputMultiLineText (OutputWriter & a_oOutput, Converter & a_oConverter, const SI_CHAR * a_pText) const private
OutputMultiLineText() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::OutputMultiLineText (OutputWriter & a_oOutput, Converter & a_oConverter, const SI_CHAR * a_pText) const private
Definition at line 2451 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::ConvertToStore(), CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::Data(), SI_NEWLINE_A, and CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::OutputWriter::Write().
Reset() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > void CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Reset
Deallocate all memory stored by this object.
Definition at line 1186 of file SimpleIni.h.
References NULL.
Reset() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > void CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Reset ()
Deallocate all memory stored by this object.
Save() [1/4]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > SI_Error CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Save (OutputWriter & a_oOutput, bool a_bAddSignature = false) const
Save the INI data.
The data will be written to the output device in a format appropriate to the current data, selected by:
SI_CHAR FORMAT
char same format as when loaded (MBCS or UTF-8)
wchar_t UTF-8
other UTF-8
Note that comments from the original data is preserved as per the documentation on comments. The order of the sections and values from the original file will be preserved.
Any data prepended or appended to the output device must use the the same format (MBCS or UTF-8). You may use the GetConverter() method to convert text to the correct format regardless of the output format being used by SimpleIni.
To add a BOM to UTF-8 data, write it out manually at the very beginning like is done in SaveFile when a_bUseBOM is true.
Parameters
a_oOutput Output writer to write the data to.
a_bAddSignature Prepend the UTF-8 BOM if the output data is in UTF-8 format. If it is not UTF-8 then this value is ignored. Do not set this to true if anything has already been written to the OutputWriter.
Returns
SI_Error See error definitions
Save() [2/4]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > SI_Error CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Save (OutputWriter & a_oOutput, bool a_bAddSignature = false) const
Save the INI data.
The data will be written to the output device in a format appropriate to the current data, selected by:
SI_CHAR FORMAT
char same format as when loaded (MBCS or UTF-8)
wchar_t UTF-8
other UTF-8
Note that comments from the original data is preserved as per the documentation on comments. The order of the sections and values from the original file will be preserved.
Any data prepended or appended to the output device must use the the same format (MBCS or UTF-8). You may use the GetConverter() method to convert text to the correct format regardless of the output format being used by SimpleIni.
To add a BOM to UTF-8 data, write it out manually at the very beginning like is done in SaveFile when a_bUseBOM is true.
Parameters
a_oOutput Output writer to write the data to.
a_bAddSignature Prepend the UTF-8 BOM if the output data is in UTF-8 format. If it is not UTF-8 then this value is ignored. Do not set this to true if anything has already been written to the OutputWriter.
Returns
SI_Error See error definitions
Definition at line 2309 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::ConvertToStore(), CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::Data(), SI_FAIL, SI_NEWLINE_A, SI_OK, SI_UTF8_SIGNATURE, and CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::OutputWriter::Write().
Referenced by CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Save().
Save() [3/4]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > SI_Error CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Save (std::string & a_sBuffer, bool a_bAddSignature = false) const inline
Append the INI data to a string.
See Save() for details.
Parameters
a_sBuffer String to have the INI data appended to.
a_bAddSignature Prepend the UTF-8 BOM if the output data is in UTF-8 format. If it is not UTF-8 then this value is ignored. Do not set this to true if anything has already been written to the string.
Returns
SI_Error See error definitions
Definition at line 716 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Save().
Save() [4/4]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > SI_Error CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Save (std::string & a_sBuffer, bool a_bAddSignature = false) const inline
Append the INI data to a string.
See Save() for details.
Parameters
a_sBuffer String to have the INI data appended to.
a_bAddSignature Prepend the UTF-8 BOM if the output data is in UTF-8 format. If it is not UTF-8 then this value is ignored. Do not set this to true if anything has already been written to the string.
Returns
SI_Error See error definitions
Definition at line 716 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Save().
SaveFile() [1/4]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > SI_Error CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SaveFile (const char * a_pszFile, bool a_bAddSignature = true) const
Save an INI file from memory to disk.
Parameters
a_pszFile Path of the file to be saved. This will be passed to fopen() and so must be a valid path for the current platform.
a_bAddSignature Prepend the UTF-8 BOM if the output data is in UTF-8 format. If it is not UTF-8 then this parameter is ignored.
Returns
SI_Error See error definitions
SaveFile() [2/4]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > SI_Error CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SaveFile (const char * a_pszFile, bool a_bAddSignature = true) const
Save an INI file from memory to disk.
Parameters
a_pszFile Path of the file to be saved. This will be passed to fopen() and so must be a valid path for the current platform.
a_bAddSignature Prepend the UTF-8 BOM if the output data is in UTF-8 format. If it is not UTF-8 then this parameter is ignored.
Returns
SI_Error See error definitions
Definition at line 2261 of file SimpleIni.h.
References NULL, and SI_FILE.
SaveFile() [3/4]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > SI_Error CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SaveFile (FILE * a_pFile, bool a_bAddSignature = false) const
Save the INI data to a file.
See Save() for details.
Parameters
a_pFile Handle to a file. File should be opened for binary output.
a_bAddSignature Prepend the UTF-8 BOM if the output data is in UTF-8 format. If it is not UTF-8 then this value is ignored. Do not set this to true if anything has already been written to the file.
Returns
SI_Error See error definitions
SaveFile() [4/4]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > SI_Error CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SaveFile (FILE * a_pFile, bool a_bAddSignature = false) const
Save the INI data to a file.
See Save() for details.
Parameters
a_pFile Handle to a file. File should be opened for binary output.
a_bAddSignature Prepend the UTF-8 BOM if the output data is in UTF-8 format. If it is not UTF-8 then this value is ignored. Do not set this to true if anything has already been written to the file.
Returns
SI_Error See error definitions
Definition at line 2302 of file SimpleIni.h.
SetBoolValue() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > SI_Error CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SetBoolValue (const SI_CHAR * a_pSection, const SI_CHAR * a_pKey, bool a_bValue, const SI_CHAR * a_pComment = NULL, bool a_bForceReplace = false)
Add or update a boolean value.
This will always insert when multiple keys are enabled.
Parameters
a_pSection Section to add or update
a_pKey Key to add or update.
a_bValue Value to set.
a_pComment Comment to be associated with the key. See the notes on SetValue() for comments.
a_bForceReplace Should all existing values in a multi-key INI file be replaced with this entry. This option has no effect if not using multi-key files. The difference between Delete/SetBoolValue and SetBoolValue with a_bForceReplace = true, is that the load order and comment will be preserved this way.
Returns
SI_Error See error definitions
SI_UPDATED Value was updated
SI_INSERTED Value was inserted
Definition at line 2108 of file SimpleIni.h.
References c, and SI_FAIL.
SetBoolValue() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > SI_Error CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SetBoolValue (const SI_CHAR * a_pSection, const SI_CHAR * a_pKey, bool a_bValue, const SI_CHAR * a_pComment = NULL, bool a_bForceReplace = false)
Add or update a boolean value.
This will always insert when multiple keys are enabled.
Parameters
a_pSection Section to add or update
a_pKey Key to add or update.
a_bValue Value to set.
a_pComment Comment to be associated with the key. See the notes on SetValue() for comments.
a_bForceReplace Should all existing values in a multi-key INI file be replaced with this entry. This option has no effect if not using multi-key files. The difference between Delete/SetBoolValue and SetBoolValue with a_bForceReplace = true, is that the load order and comment will be preserved this way.
Returns
SI_Error See error definitions
SI_UPDATED Value was updated
SI_INSERTED Value was inserted
SetDoubleValue() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > SI_Error CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SetDoubleValue (const SI_CHAR * a_pSection, const SI_CHAR * a_pKey, double a_nValue, const SI_CHAR * a_pComment = NULL, bool a_bForceReplace = false)
Add or update a double value.
This will always insert when multiple keys are enabled.
Parameters
a_pSection Section to add or update
a_pKey Key to add or update.
a_nValue Value to set.
a_pComment Comment to be associated with the key. See the notes on SetValue() for comments.
a_bForceReplace Should all existing values in a multi-key INI file be replaced with this entry. This option has no effect if not using multi-key files. The difference between Delete/SetDoubleValue and SetDoubleValue with a_bForceReplace = true, is that the load order and comment will be preserved this way.
Returns
SI_Error See error definitions
SI_UPDATED Value was updated
SI_INSERTED Value was inserted
Definition at line 2042 of file SimpleIni.h.
References c, and SI_FAIL.
SetDoubleValue() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > SI_Error CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SetDoubleValue (const SI_CHAR * a_pSection, const SI_CHAR * a_pKey, double a_nValue, const SI_CHAR * a_pComment = NULL, bool a_bForceReplace = false)
Add or update a double value.
This will always insert when multiple keys are enabled.
Parameters
a_pSection Section to add or update
a_pKey Key to add or update.
a_nValue Value to set.
a_pComment Comment to be associated with the key. See the notes on SetValue() for comments.
a_bForceReplace Should all existing values in a multi-key INI file be replaced with this entry. This option has no effect if not using multi-key files. The difference between Delete/SetDoubleValue and SetDoubleValue with a_bForceReplace = true, is that the load order and comment will be preserved this way.
Returns
SI_Error See error definitions
SI_UPDATED Value was updated
SI_INSERTED Value was inserted
SetLongValue() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > SI_Error CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SetLongValue (const SI_CHAR * a_pSection, const SI_CHAR * a_pKey, long a_nValue, const SI_CHAR * a_pComment = NULL, bool a_bUseHex = false, bool a_bForceReplace = false)
Add or update a numeric value.
This will always insert when multiple keys are enabled.
Parameters
a_pSection Section to add or update
a_pKey Key to add or update.
a_nValue Value to set.
a_pComment Comment to be associated with the key. See the notes on SetValue() for comments.
a_bUseHex By default the value will be written to the file in decimal format. Set this to true to write it as hexadecimal.
a_bForceReplace Should all existing values in a multi-key INI file be replaced with this entry. This option has no effect if not using multi-key files. The difference between Delete/SetLongValue and SetLongValue with a_bForceReplace = true, is that the load order and comment will be preserved this way.
Returns
SI_Error See error definitions
SI_UPDATED Value was updated
SI_INSERTED Value was inserted
SetLongValue() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > SI_Error CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SetLongValue (const SI_CHAR * a_pSection, const SI_CHAR * a_pKey, long a_nValue, const SI_CHAR * a_pComment = NULL, bool a_bUseHex = false, bool a_bForceReplace = false)
Add or update a numeric value.
This will always insert when multiple keys are enabled.
Parameters
a_pSection Section to add or update
a_pKey Key to add or update.
a_nValue Value to set.
a_pComment Comment to be associated with the key. See the notes on SetValue() for comments.
a_bUseHex By default the value will be written to the file in decimal format. Set this to true to write it as hexadecimal.
a_bForceReplace Should all existing values in a multi-key INI file be replaced with this entry. This option has no effect if not using multi-key files. The difference between Delete/SetLongValue and SetLongValue with a_bForceReplace = true, is that the load order and comment will be preserved this way.
Returns
SI_Error See error definitions
SI_UPDATED Value was updated
SI_INSERTED Value was inserted
Definition at line 1985 of file SimpleIni.h.
References c, and SI_FAIL.
SetMultiKey() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > void CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SetMultiKey (bool a_bAllowMultiKey = true) inline
Should multiple identical keys be permitted in the file.
If set to false then the last value encountered will be used as the value of the key. If set to true, then all values will be available to be queried. For example, with the following input:
[section]
test=value1
test=value2
Then with SetMultiKey(true), both of the values "value1" and "value2" will be returned for the key test. If SetMultiKey(false) is used, then the value for "test" will only be "value2". This value may be changed at any time.
Parameters
a_bAllowMultiKey Allow multi-keys in the source?
Definition at line 519 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_bAllowMultiKey.
SetMultiKey() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > void CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SetMultiKey (bool a_bAllowMultiKey = true) inline
Should multiple identical keys be permitted in the file.
If set to false then the last value encountered will be used as the value of the key. If set to true, then all values will be available to be queried. For example, with the following input:
[section]
test=value1
test=value2
Then with SetMultiKey(true), both of the values "value1" and "value2" will be returned for the key test. If SetMultiKey(false) is used, then the value for "test" will only be "value2". This value may be changed at any time.
Parameters
a_bAllowMultiKey Allow multi-keys in the source?
Definition at line 519 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_bAllowMultiKey.
SetMultiLine() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > void CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SetMultiLine (bool a_bAllowMultiLine = true) inline
Should data values be permitted to span multiple lines in the file.
If set to false then the multi-line construct <<<TAG as a value will be returned as is instead of loading the data. This value may be changed at any time.
Parameters
a_bAllowMultiLine Allow multi-line values in the source?
Definition at line 531 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_bAllowMultiLine.
SetMultiLine() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > void CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SetMultiLine (bool a_bAllowMultiLine = true) inline
Should data values be permitted to span multiple lines in the file.
If set to false then the multi-line construct <<<TAG as a value will be returned as is instead of loading the data. This value may be changed at any time.
Parameters
a_bAllowMultiLine Allow multi-line values in the source?
Definition at line 531 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_bAllowMultiLine.
SetSpaces() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > void CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SetSpaces (bool a_bSpaces = true) inline
Should spaces be added around the equals sign when writing key/value pairs out.
When true, the result will be "key = value". When false, the result will be "key=value". This value may be changed at any time.
Parameters
a_bSpaces Add spaces around the equals sign?
Definition at line 542 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_bSpaces.
SetSpaces() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > void CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SetSpaces (bool a_bSpaces = true) inline
Should spaces be added around the equals sign when writing key/value pairs out.
When true, the result will be "key = value". When false, the result will be "key=value". This value may be changed at any time.
Parameters
a_bSpaces Add spaces around the equals sign?
Definition at line 542 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_bSpaces.
SetUnicode() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > void CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SetUnicode (bool a_bIsUtf8 = true) inline
Set the storage format of the INI data.
This affects both the loading and saving of the INI data using all of the Load/Save API functions. This value cannot be changed after any INI data has been loaded.
If the file is not set to Unicode (UTF-8), then the data encoding is assumed to be the OS native encoding. This encoding is the system locale on Linux/Unix and the legacy MBCS encoding on Windows NT/2K/XP. If the storage format is set to Unicode then the file will be loaded as UTF-8 encoded data regardless of the native file encoding. If SI_CHAR == char then all of the char* parameters take and return UTF-8 encoded data regardless of the system locale.
Parameters
a_bIsUtf8 Assume UTF-8 encoding for the source?
Definition at line 492 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_bStoreIsUtf8, and CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_pData.
SetUnicode() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > void CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SetUnicode (bool a_bIsUtf8 = true) inline
Set the storage format of the INI data.
This affects both the loading and saving of the INI data using all of the Load/Save API functions. This value cannot be changed after any INI data has been loaded.
If the file is not set to Unicode (UTF-8), then the data encoding is assumed to be the OS native encoding. This encoding is the system locale on Linux/Unix and the legacy MBCS encoding on Windows NT/2K/XP. If the storage format is set to Unicode then the file will be loaded as UTF-8 encoded data regardless of the native file encoding. If SI_CHAR == char then all of the char* parameters take and return UTF-8 encoded data regardless of the system locale.
Parameters
a_bIsUtf8 Assume UTF-8 encoding for the source?
Definition at line 492 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_bStoreIsUtf8, and CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_pData.
SetValue() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > SI_Error CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SetValue (const SI_CHAR * a_pSection, const SI_CHAR * a_pKey, const SI_CHAR * a_pValue, const SI_CHAR * a_pComment = NULL, bool a_bForceReplace = false) inline
Add or update a section or value.
This will always insert when multiple keys are enabled.
Parameters
a_pSection Section to add or update
a_pKey Key to add or update. Set to NULL to create an empty section.
a_pValue Value to set. Set to NULL to create an empty section.
a_pComment Comment to be associated with the section or the key. If a_pKey is NULL then it will be associated with the section, otherwise the key. Note that a comment may be set ONLY when the section or key is first created (i.e. when this function returns the value SI_INSERTED). If you wish to create a section with a comment then you need to create the section separately to the key. The comment string must be in full comment form already (have a comment character starting every line).
a_bForceReplace Should all existing values in a multi-key INI file be replaced with this entry. This option has no effect if not using multi-key files. The difference between Delete/SetValue and SetValue with a_bForceReplace = true, is that the load order and comment will be preserved this way.
Returns
SI_Error See error definitions
SI_UPDATED Value was updated
SI_INSERTED Value was inserted
Definition at line 908 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::AddEntry().
SetValue() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > SI_Error CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SetValue (const SI_CHAR * a_pSection, const SI_CHAR * a_pKey, const SI_CHAR * a_pValue, const SI_CHAR * a_pComment = NULL, bool a_bForceReplace = false) inline
Add or update a section or value.
This will always insert when multiple keys are enabled.
Parameters
a_pSection Section to add or update
a_pKey Key to add or update. Set to NULL to create an empty section.
a_pValue Value to set. Set to NULL to create an empty section.
a_pComment Comment to be associated with the section or the key. If a_pKey is NULL then it will be associated with the section, otherwise the key. Note that a comment may be set ONLY when the section or key is first created (i.e. when this function returns the value SI_INSERTED). If you wish to create a section with a comment then you need to create the section separately to the key. The comment string must be in full comment form already (have a comment character starting every line).
a_bForceReplace Should all existing values in a multi-key INI file be replaced with this entry. This option has no effect if not using multi-key files. The difference between Delete/SetValue and SetValue with a_bForceReplace = true, is that the load order and comment will be preserved this way.
Returns
SI_Error See error definitions
SI_UPDATED Value was updated
SI_INSERTED Value was inserted
Definition at line 908 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::AddEntry().
SkipNewLine() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > void CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SkipNewLine (SI_CHAR *& a_pData) const inline private
Skip over a newline character (or characters) for either DOS or UNIX.
Definition at line 1091 of file SimpleIni.h.
SkipNewLine() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > void CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SkipNewLine (SI_CHAR *& a_pData) const inline private
Skip over a newline character (or characters) for either DOS or UNIX.
Definition at line 1091 of file SimpleIni.h.
UsingSpaces() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::UsingSpaces () const inline
Query the status of spaces output.
Definition at line 545 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_bSpaces.
UsingSpaces() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::UsingSpaces () const inline
Query the status of spaces output.
Definition at line 545 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_bSpaces.
Member Data Documentation
m_bAllowMultiKey
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_bAllowMultiKey private
Are multiple values permitted for the same key?
Definition at line 1147 of file SimpleIni.h.
Referenced by CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::IsMultiKey(), and CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SetMultiKey().
m_bAllowMultiLine
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_bAllowMultiLine private
Are data values permitted to span multiple lines?
Definition at line 1150 of file SimpleIni.h.
Referenced by CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::IsMultiLine(), and CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SetMultiLine().
m_bSpaces
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_bSpaces private
Should spaces be written out surrounding the equals sign?
Definition at line 1153 of file SimpleIni.h.
Referenced by CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SetSpaces(), and CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::UsingSpaces().
m_bStoreIsUtf8
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_bStoreIsUtf8 private
Is the format of our datafile UTF-8 or MBCS?
Definition at line 1144 of file SimpleIni.h.
Referenced by CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::GetConverter(), CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::IsUnicode(), and CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SetUnicode().
m_data
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > TSection CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_data private
Parsed INI data.
Section -> (Key -> Value).
Definition at line 1135 of file SimpleIni.h.
Referenced by CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::IsEmpty().
m_nOrder
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > int CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_nOrder private
Next order value, used to ensure sections and keys are output in the same order that they are loaded/added.
Definition at line 1158 of file SimpleIni.h.
m_pData
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > SI_CHAR * CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_pData private
Copy of the INI file data in our character format.
This will be modified when parsed to have NULL characters added after all interesting string entries. All of the string pointers to sections, keys and values point into this block of memory.
Definition at line 1123 of file SimpleIni.h.
Referenced by CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SetUnicode().
m_pFileComment
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > const SI_CHAR * CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_pFileComment private
File comment for this data, if one exists.
Definition at line 1132 of file SimpleIni.h.
m_strings
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > TNamesDepend CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_strings private
This vector stores allocated memory for copies of strings that have been supplied after the file load.
It will be empty unless SetValue() has been called.
Definition at line 1141 of file SimpleIni.h.
m_uDataLen
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > size_t CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::m_uDataLen private
Length of the data that we have stored.
Used when deleting strings to determine if the string is stored here or in the allocated string buffer.
Definition at line 1129 of file SimpleIni.h.
The documentation for this class was generated from the following file:
include/etiss/IntegratedLibrary/SimpleIni/SimpleIni.h