ETISS 0.8.0: RISCV64Arch Class Reference
RISCV64Arch Class Reference
#include <RISCV64Arch.h>
Public Member Functions
RISCV64Arch ()
virtual const std::set< std::string > & getListenerSupportedRegisters ()
virtual ETISS_CPU * newCPU ()
allocate new cpu structure
virtual void resetCPU (ETISS_CPU *cpu, etiss::uint64 *startpointer)
reset cpu (structure)
virtual void deleteCPU (ETISS_CPU *)
delete cpu structure
virtual std::shared_ptr< etiss::VirtualStruct > getVirtualStruct (ETISS_CPU *cpu)
get the VirtualStruct of the core to mitigate register access
virtual unsigned getMaximumInstructionSizeInBytes ()
virtual unsigned getInstructionSizeInBytes ()
virtual const std::set< std::string > & getHeaders () const
required headers (RISCV64.h)
virtual etiss::int32 handleException (etiss::int32 code, ETISS_CPU *cpu)
This function will be called automatically in order to handling architecure dependent exceptions such as interrupt, system call, illegal instructions.
virtual void initInstrSet (etiss::instr::ModedInstructionSet &) const
This function is called during CPUArch initialization.
virtual void initCodeBlock (etiss::CodeBlock &cb) const
called before instructions are translated for the code block
virtual void compensateEndianess (ETISS_CPU *cpu, etiss::instr::BitArray &ba) const
Target architecture may have inconsistent endianess.
virtual etiss::InterruptVector * createInterruptVector (ETISS_CPU *cpu)
If interrupt handling is expected, vector table could be provided to support interrupt triggering.
virtual void deleteInterruptVector (etiss::InterruptVector *vec, ETISS_CPU *cpu)
delete an allocated interrupt vector object
virtual etiss::plugin::gdb::GDBCore & getGDBCore ()
get the GDBcore for RISCV64 architecture
etiss::Plugin * newTimer (ETISS_CPU *cpu)
create a simple default timer implementaion instance for this architecture.
void deleteTimer (etiss::Plugin *timer)
delete timer instance
etiss::mm::MMU * newMMU (ETISS_CPU *cpu)
It is an interface to instanciate a Memory Management Unit.
Public Member Functions inherited from etiss::CPUArch
CPUArch (std::string archname)
virtual ~CPUArch ()
std::string getArchName () const
returns the name of this architecture.
std::string getName () const
returns the name of this architecture.
virtual unsigned getMaximumInstructionsPerMetaInstruction ()
maximum number of instructions in a meta instruction
virtual unsigned getSuperInstructionCount ()
fixed number of sub instructions per instruction (e.g.
virtual std::string getBlockGlobalCode ()
get c++ code snippet that is placed at the top of a translated block
virtual bool unlikelyInstruction (etiss::uint8 *instr, unsigned length, bool &ismetainstruction)
return true if the given data is unlikely to be an instruction.
virtual std::string getIncludePath ()
returns a path that will be used to look up header files
virtual void finalizeInstrSet (etiss::instr::ModedInstructionSet &) const
the default behavior of this function of a cpu arch is to add "cpu->cpuTime_ps += cpu->cpuCycleTime_ps;" if the cpu time update group is not in use
CPUArch (std::string archname)
virtual ~CPUArch ()
std::string getArchName () const
returns the name of this architecture.
std::string getName () const
returns the name of this architecture.
virtual unsigned getMaximumInstructionsPerMetaInstruction ()
maximum number of instructions in a meta instruction
virtual unsigned getSuperInstructionCount ()
fixed number of sub instructions per instruction (e.g.
virtual std::string getBlockGlobalCode ()
get c++ code snippet that is placed at the top of a translated block
virtual bool unlikelyInstruction (etiss::uint8 *instr, unsigned length, bool &ismetainstruction)
return true if the given data is unlikely to be an instruction.
virtual std::string getIncludePath ()
returns a path that will be used to look up header files
virtual void finalizeInstrSet (etiss::instr::ModedInstructionSet &) const
the default behavior of this function of a cpu arch is to add "cpu->cpuTime_ps += cpu->cpuCycleTime_ps;" if the cpu time update group is not in use
Public Member Functions inherited from etiss::CPUArchRegListenerInterface
virtual ~CPUArchRegListenerInterface ()
virtual ~CPUArchRegListenerInterface ()
Public Member Functions inherited from etiss::CPUArchCPUManipulation
virtual ~CPUArchCPUManipulation ()
virtual ~CPUArchCPUManipulation ()
Public Member Functions inherited from etiss::CPUArchDefaultPlugins
virtual ~CPUArchDefaultPlugins ()
virtual ~CPUArchDefaultPlugins ()
Public Member Functions inherited from etiss::TranslationPlugin
TranslationPlugin ()
virtual ~TranslationPlugin ()
virtual void finalizeCodeBlock (etiss::CodeBlock &) const
called after all instructions have been translated for the code block
virtual void * getPluginHandle ()
called to get the handle that is available in translated code via getPoinerCode(). [default: this]
TranslationPlugin ()
virtual ~TranslationPlugin ()
virtual void finalizeCodeBlock (etiss::CodeBlock &) const
called after all instructions have been translated for the code block
virtual void * getPluginHandle ()
called to get the handle that is available in translated code via getPoinerCode(). [default: this]
Public Member Functions inherited from etiss::Plugin
virtual ~Plugin ()
unsigned getType ()
InterruptListenerPlugin * getInterruptListenerPlugin ()
CoroutinePlugin * getCoroutinePlugin ()
SystemWrapperPlugin * getSystemWrapperPlugin ()
RegisterDevicePlugin * getRegisterDevicePlugin ()
TranslationPlugin * getTranslationPlugin ()
std::string getPluginName () const
const std::string & getLastAssignedCoreName ()
std::string toString () const
virtual ~Plugin ()
unsigned getType ()
InterruptListenerPlugin * getInterruptListenerPlugin ()
CoroutinePlugin * getCoroutinePlugin ()
SystemWrapperPlugin * getSystemWrapperPlugin ()
RegisterDevicePlugin * getRegisterDevicePlugin ()
TranslationPlugin * getTranslationPlugin ()
std::string getPluginName () const
const std::string & getLastAssignedCoreName ()
std::string toString () const
Public Member Functions inherited from etiss::ToString
ToString ()
virtual ~ToString ()
ToString ()
virtual ~ToString ()
Private Attributes
std::set< std::string > listenerSupportedRegisters_
std::set< std::string > headers_
RISCV64GDBCore gdbcore_
Additional Inherited Members
Static Public Member Functions inherited from etiss::CPUArchRegListenerInterface
static void signalChangedRegisterValue (ETISS_CPU *cpu, const char *registerName)
call this function to inform RegisterDevicePlugins about changed special register values.
static void signalChangedRegisterValue (ETISS_CPU *cpu, const char *registerName)
call this function to inform RegisterDevicePlugins about changed special register values.
Static Public Attributes inherited from etiss::Plugin
static const unsigned INTERRUPTLISTENER = 1 << 0
access to translated code
static const unsigned COROUTINE = 1 << 1
callback after execution of each translated block
static const unsigned SYSTEMWRAPPER = 1 << 2
can wrap/change ETISS_System structure at execution start
static const unsigned REGISTERDEVICE
gets noticed of changes to special registers (e.g. mmu register etc. [depends on architecture])
static const unsigned TRANSLATION
access to translated code during translation phase or when instruction tree is built
Protected Member Functions inherited from etiss::CPUArch
virtual std::string _getPluginName () const
do not override. maps to getName().
virtual std::string _getPluginName () const
do not override. maps to getName().
Protected Member Functions inherited from etiss::TranslationPlugin
std::string getPointerCode () const
returns a C code expression that allows to get or assign a pointer to the variable assigned to this translation plugin.
std::string getPointerCode () const
returns a C code expression that allows to get or assign a pointer to the variable assigned to this translation plugin.
Protected Member Functions inherited from etiss::Plugin
Plugin (unsigned type=0)
virtual void init (ETISS_CPU *cpu, ETISS_System *system, CPUArch *arch)
this function is called before the plugin is used in the cpu execution loop (etiss::CPUCore::execute).
virtual void cleanup ()
this function is called after cpu execution loop (etiss::CPUCore::execute) finished.
void setCorrespondingCPUCoreName (std::string name)
virtual void addedToCPUCore (etiss::CPUCore *core)
called as soon a plugin has been added to its CPUCore.
virtual void removedFromCPUCore (etiss::CPUCore *core)
called as soon a plugin has been removed from its CPUCore.
Plugin (unsigned type=0)
virtual void init (ETISS_CPU *cpu, ETISS_System *system, CPUArch *arch)
this function is called before the plugin is used in the cpu execution loop (etiss::CPUCore::execute).
virtual void cleanup ()
this function is called after cpu execution loop (etiss::CPUCore::execute) finished.
void setCorrespondingCPUCoreName (std::string name)
virtual void addedToCPUCore (etiss::CPUCore *core)
called as soon a plugin has been added to its CPUCore.
virtual void removedFromCPUCore (etiss::CPUCore *core)
called as soon a plugin has been removed from its CPUCore.
Protected Attributes inherited from etiss::Plugin
ETISS_CPU * plugin_cpu_
holds a pointer to the cpu structure. will be set before init call and after cleanup call
ETISS_System * plugin_system_
holds a pointer to the system structure.
CPUArch * plugin_arch_
holds a pointer to the CPUArch instance. will be set before init call and after cleanup call
CPUCore * plugin_core_
holds a pointer to the associated CPUCore instance.
Detailed Description
Definition at line 62 of file RISCV64Arch.h.
Constructor & Destructor Documentation
RISCV64Arch()
RISCV64Arch::RISCV64Arch ()
Definition at line 50 of file RISCV64Arch.cpp.
References headers_.
Member Function Documentation
compensateEndianess()
void RISCV64Arch::compensateEndianess (ETISS_CPU * cpu, etiss::instr::BitArray & ba) const virtual
Target architecture may have inconsistent endianess.
This function is called whenever a data is read from memory.
Data read from memory is buffered, and this function is called to alter sequence of buffered data so that the inconsistent endianess is compensated.
See also
RISCV64ArchSpecificImp.h
Target architecture may have inconsistent endianess. Data read from memory is buffered, and this function is called to alter sequence of buffered data so that the inconsistent endianess is compensated. Example for ARMv6M: void * ptr = ba.internalBuffer(); if (ba.byteCount() == 2) { ((uint32_t*)ptr) = ((uint16_t)(*((uint8_t*)ptr))) | ((uint16_t)(*(((uint8_t*)ptr)+1)) << 8); } else if (ba.byteCount() == 4) { ((uint32_t*)ptr) = ((((uint32_t)(*((uint8_t*)ptr))) | ((uint32_t)(*(((uint8_t*)ptr)+1)) << 8)) << 16) | ((uint32_t)(*(((uint8_t*)ptr)+2))) | ((uint32_t)(*(((uint8_t*)ptr)+3)) << 8); } else { etiss::log(etiss::FATALERROR,"Endianess cannot be handled",ba.byteCount()); }
Attention
Default endianess: little-endian
Reimplemented from etiss::CPUArch.
Definition at line 531 of file RISCV64ArchSpecificImp.h.
createInterruptVector()
etiss::InterruptVector * RISCV64Arch::createInterruptVector (ETISS_CPU * cpu) virtual
If interrupt handling is expected, vector table could be provided to support interrupt triggering.
See also
RISCV64ArchSpecificImp.h
Interrupt vector table is used to inform the core whenever an edge/level triggered interrupt incoming. The content of interrupt vector could be a special register or standalone interrupt lines.
Reimplemented from etiss::CPUArch.
Definition at line 641 of file RISCV64ArchSpecificImp.h.
References RISCV64::CSR, CSR_MIE, and CSR_MIP.
deleteCPU()
void RISCV64Arch::deleteCPU (ETISS_CPU *) virtual
delete cpu structure
Implements etiss::CPUArch.
Definition at line 194 of file RISCV64Arch.cpp.
deleteInterruptVector()
void RISCV64Arch::deleteInterruptVector (etiss::InterruptVector * vec, ETISS_CPU * cpu) virtual
delete an allocated interrupt vector object
Reimplemented from etiss::CPUArch.
Definition at line 652 of file RISCV64ArchSpecificImp.h.
deleteTimer()
void RISCV64Arch::deleteTimer (etiss::Plugin * timer) virtual
delete timer instance
Returns
may be 0
Reimplemented from etiss::CPUArchDefaultPlugins.
Definition at line 240 of file RISCV64Arch.cpp.
getGDBCore()
etiss::plugin::gdb::GDBCore & RISCV64Arch::getGDBCore () virtual
get the GDBcore for RISCV64 architecture
See also
RISCV64GDBCore.h for implementation of GDBcore
Reimplemented from etiss::CPUArch.
Definition at line 227 of file RISCV64Arch.cpp.
References gdbcore_.
getHeaders()
const std::set< std::string > & RISCV64Arch::getHeaders () const virtual
required headers (RISCV64.h)
Implements etiss::CPUArch.
Definition at line 217 of file RISCV64Arch.cpp.
References headers_.
getInstructionSizeInBytes()
unsigned RISCV64Arch::getInstructionSizeInBytes () virtual
Returns
2
Implements etiss::CPUArch.
Definition at line 210 of file RISCV64Arch.cpp.
getListenerSupportedRegisters()
const std::set< std::string > & RISCV64Arch::getListenerSupportedRegisters () virtual
See also
CPUArchRegListenerInterface::signalChangedRegisterValue
Implements etiss::CPUArchRegListenerInterface.
Definition at line 55 of file RISCV64Arch.cpp.
References listenerSupportedRegisters_.
getMaximumInstructionSizeInBytes()
unsigned RISCV64Arch::getMaximumInstructionSizeInBytes () virtual
Returns
8 (jump instruction + instruction of delay slot)
Implements etiss::CPUArch.
Definition at line 203 of file RISCV64Arch.cpp.
getVirtualStruct()
std::shared_ptr< etiss::VirtualStruct > RISCV64Arch::getVirtualStruct (ETISS_CPU * cpu) virtual
get the VirtualStruct of the core to mitigate register access
See also
RISCV64ArchSpecificImp.h
Implements etiss::CPUArchCPUManipulation.
Definition at line 621 of file RISCV64ArchSpecificImp.h.
References etiss::VirtualStruct::allocate().
handleException()
etiss::int32 RISCV64Arch::handleException (etiss::int32 cause, ETISS_CPU * cpu) virtual
This function will be called automatically in order to handling architecure dependent exceptions such as interrupt, system call, illegal instructions.
This function will be called automatically in order to handling exceptions such as interrupt, system call, illegal instructions.
See also
RISCV64ArchSpecificImp.h
Exception handling mechanism is implementation dependent for each cpu variant. Please add it to the following block if exception handling is demanded. Pesudo example: switch(cause){ case etiss::RETURNCODE::INTERRUPT: break;
Reimplemented from etiss::CPUArch.
Definition at line 80 of file RISCV64ArchSpecificImp.h.
References ETISS_CPU::_etiss_private_handle_, CAUSE_BREAKPOINT, CAUSE_FETCH_ACCESS, CAUSE_FETCH_PAGE_FAULT, CAUSE_ILLEGAL_INSTRUCTION, CAUSE_LOAD_ACCESS, CAUSE_LOAD_PAGE_FAULT, CAUSE_MACHINE_ECALL, CAUSE_STORE_ACCESS, CAUSE_STORE_PAGE_FAULT, CAUSE_SUPERVISOR_ECALL, CAUSE_USER_ECALL, etiss::cfg(), RISCV64::CSR, CSR_MCAUSE, CSR_MEDELEG, CSR_MEPC, CSR_MIDELEG, CSR_MIE, CSR_MIP, CSR_MSTATUS, CSR_MTVAL, CSR_MTVEC, CSR_SCAUSE, CSR_SEPC, CSR_SSTATUS, CSR_STVEC, etiss::ERROR, etiss::INFO, ETISS_CPU::instructionPointer, likely, etiss::log(), MSTATUS_MIE, MSTATUS_MPIE, MSTATUS_MPP, MSTATUS_SIE, MSTATUS_SPP, MSTATUS_UIE, etiss::mm::NOERROR, PRV_M, PRV_S, PRV_U, etiss::toString(), unlikely, etiss::VERBOSE, and etiss::WARNING.
initCodeBlock()
void RISCV64Arch::initCodeBlock (etiss::CodeBlock &) const virtual
called before instructions are translated for the code block
Reimplemented from etiss::TranslationPlugin.
Definition at line 222 of file RISCV64Arch.cpp.
References etiss::CodeBlock::fileglobalCode().
initInstrSet()
void RISCV64Arch::initInstrSet (etiss::instr::ModedInstructionSet & mis) const virtual
This function is called during CPUArch initialization.
See also
RISCV64ArchSpecificImp.h
Function pointer length_updater_ has to be replaced if multiple length instruction execution is supported. This function enables dynamic instruction length update in order to guarantee correct binary translation Pesudo example: vis->length_updater_ = [](VariableInstructionSet & ,InstructionContext & ic, BitArray & ba) { switch(ba.byteCount()){ case 4: if (INSTRUCTION_LENTH_NOT_EQUAL(4)){ updateInstrLength(ic, ba); ic.is_not_default_width_ = true; } break; } };
Reimplemented from etiss::TranslationPlugin.
Definition at line 381 of file RISCV64ArchSpecificImp.h.
References etiss::instr::InstructionCollection::addTo(), etiss::cfg(), etiss::FATALERROR, etiss::Configuration::get(), etiss::instr::ModedInstructionSet::get(), if(), etiss::instr::InstructionContext::instr_width_, etiss::instr::InstructionContext::instr_width_fully_evaluated_, etiss::instr::InstructionContext::is_not_default_width_, etiss::instr::VariableInstructionSet::length_updater_, etiss::log(), etiss::instr::BitArrayRange::read(), RISCV64ISA(), and etiss::Configuration::set().
newCPU()
ETISS_CPU * RISCV64Arch::newCPU () virtual
allocate new cpu structure
Implements etiss::CPUArch.
Definition at line 60 of file RISCV64Arch.cpp.
References resetCPU().
newMMU()
etiss::mm::MMU * RISCV64Arch::newMMU (ETISS_CPU * cpu) virtual
It is an interface to instanciate a Memory Management Unit.
Reimplemented from etiss::CPUArch.
Definition at line 246 of file RISCV64Arch.cpp.
newTimer()
etiss::Plugin * RISCV64Arch::newTimer (ETISS_CPU * cpu) virtual
create a simple default timer implementaion instance for this architecture.
Returns
may be 0
Reimplemented from etiss::CPUArchDefaultPlugins.
Definition at line 234 of file RISCV64Arch.cpp.
resetCPU()
void RISCV64Arch::resetCPU (ETISS_CPU * cpu, etiss::uint64 * startpointer) virtual
reset cpu (structure)
Implements etiss::CPUArch.
Definition at line 67 of file RISCV64Arch.cpp.
References RISCV64::A0, RISCV64::A1, RISCV64::A2, RISCV64::A3, RISCV64::A4, RISCV64::A5, RISCV64::A6, RISCV64::A7, ETISS_CPU::cpuCycleTime_ps, ETISS_CPU::cpuTime_ps, RISCV64::CSR, ETISS_CPU::cycles, RISCV64::F, RISCV64::FCSR, RISCV64::FENCE, RISCV64::GP, RISCV64::ins_X, ETISS_CPU::instructionPointer, memset(), ETISS_CPU::mode, RISCV64::RA, RISCV64::RES, ETISS_CPU::resources, ETISS_CPU::resourceUsages, RISCV64::S0, RISCV64::S1, RISCV64::S10, RISCV64::S11, RISCV64::S2, RISCV64::S3, RISCV64::S4, RISCV64::S5, RISCV64::S6, RISCV64::S7, RISCV64::S8, RISCV64::S9, RISCV64::SP, RISCV64::T0, RISCV64::T1, RISCV64::T2, RISCV64::T3, RISCV64::T4, RISCV64::T5, RISCV64::T6, RISCV64::TP, RISCV64::X, and RISCV64::ZERO.
Referenced by newCPU().
Member Data Documentation
gdbcore_
RISCV64GDBCore RISCV64Arch::gdbcore_ private
Definition at line 147 of file RISCV64Arch.h.
Referenced by getGDBCore().
headers_
std::set<std::string> RISCV64Arch::headers_ private
Definition at line 146 of file RISCV64Arch.h.
Referenced by getHeaders(), and RISCV64Arch().
listenerSupportedRegisters_
std::set<std::string> RISCV64Arch::listenerSupportedRegisters_ private
Definition at line 145 of file RISCV64Arch.h.
Referenced by getListenerSupportedRegisters().
The documentation for this class was generated from the following files:
/home/runner/work/etiss/etiss/ArchImpl/RISCV64/RISCV64Arch.h
/home/runner/work/etiss/etiss/ArchImpl/RISCV64/RISCV64Arch.cpp
/home/runner/work/etiss/etiss/ArchImpl/RISCV64/RISCV64ArchSpecificImp.h