ETISS 0.8.0: etiss::mm::DMMUWrapper Class Reference
etiss::mm::DMMUWrapper Class Reference
#include <DMMUWrapper.h>
Public Member Functions
DMMUWrapper (std::shared_ptr< MMU > mmu)
virtual ~DMMUWrapper ()
ETISS_System * wrap (ETISS_CPU *cpu, ETISS_System *system)
SystemWrapperPlugin interface to wrap around original ETISS_System.
ETISS_System * unwrap (ETISS_CPU *cpu, ETISS_System *system)
SystemWrapperPlugin interface to unwrap original ETISS_System.
DMMUWrapper (std::shared_ptr< MMU > mmu)
virtual ~DMMUWrapper ()
ETISS_System * wrap (ETISS_CPU *cpu, ETISS_System *system)
SystemWrapperPlugin interface to wrap around original ETISS_System.
ETISS_System * unwrap (ETISS_CPU *cpu, ETISS_System *system)
SystemWrapperPlugin interface to unwrap original ETISS_System.
Public Member Functions inherited from etiss::SystemWrapperPlugin
SystemWrapperPlugin ()
virtual ~SystemWrapperPlugin ()
SystemWrapperPlugin ()
virtual ~SystemWrapperPlugin ()
Public Member Functions inherited from etiss::Plugin
virtual ~Plugin ()
unsigned getType ()
InterruptListenerPlugin * getInterruptListenerPlugin ()
CoroutinePlugin * getCoroutinePlugin ()
SystemWrapperPlugin * getSystemWrapperPlugin ()
RegisterDevicePlugin * getRegisterDevicePlugin ()
TranslationPlugin * getTranslationPlugin ()
std::string getPluginName () const
const std::string & getLastAssignedCoreName ()
std::string toString () const
virtual ~Plugin ()
unsigned getType ()
InterruptListenerPlugin * getInterruptListenerPlugin ()
CoroutinePlugin * getCoroutinePlugin ()
SystemWrapperPlugin * getSystemWrapperPlugin ()
RegisterDevicePlugin * getRegisterDevicePlugin ()
TranslationPlugin * getTranslationPlugin ()
std::string getPluginName () const
const std::string & getLastAssignedCoreName ()
std::string toString () const
Public Member Functions inherited from etiss::ToString
ToString ()
virtual ~ToString ()
ToString ()
virtual ~ToString ()
Public Attributes
std::shared_ptr< MMU > mmu_
Protected Member Functions
std::string _getPluginName () const
std::string _getPluginName () const
Protected Member Functions inherited from etiss::Plugin
Plugin (unsigned type=0)
virtual void init (ETISS_CPU *cpu, ETISS_System *system, CPUArch *arch)
this function is called before the plugin is used in the cpu execution loop (etiss::CPUCore::execute).
virtual void cleanup ()
this function is called after cpu execution loop (etiss::CPUCore::execute) finished.
void setCorrespondingCPUCoreName (std::string name)
virtual void addedToCPUCore (etiss::CPUCore *core)
called as soon a plugin has been added to its CPUCore.
virtual void removedFromCPUCore (etiss::CPUCore *core)
called as soon a plugin has been removed from its CPUCore.
Plugin (unsigned type=0)
virtual void init (ETISS_CPU *cpu, ETISS_System *system, CPUArch *arch)
this function is called before the plugin is used in the cpu execution loop (etiss::CPUCore::execute).
virtual void cleanup ()
this function is called after cpu execution loop (etiss::CPUCore::execute) finished.
void setCorrespondingCPUCoreName (std::string name)
virtual void addedToCPUCore (etiss::CPUCore *core)
called as soon a plugin has been added to its CPUCore.
virtual void removedFromCPUCore (etiss::CPUCore *core)
called as soon a plugin has been removed from its CPUCore.
Additional Inherited Members
Static Public Attributes inherited from etiss::Plugin
static const unsigned INTERRUPTLISTENER = 1 << 0
access to translated code
static const unsigned COROUTINE = 1 << 1
callback after execution of each translated block
static const unsigned SYSTEMWRAPPER = 1 << 2
can wrap/change ETISS_System structure at execution start
static const unsigned REGISTERDEVICE
gets noticed of changes to special registers (e.g. mmu register etc. [depends on architecture])
static const unsigned TRANSLATION
access to translated code during translation phase or when instruction tree is built
Protected Attributes inherited from etiss::Plugin
ETISS_CPU * plugin_cpu_
holds a pointer to the cpu structure. will be set before init call and after cleanup call
ETISS_System * plugin_system_
holds a pointer to the system structure.
CPUArch * plugin_arch_
holds a pointer to the CPUArch instance. will be set before init call and after cleanup call
CPUCore * plugin_core_
holds a pointer to the associated CPUCore instance.
Detailed Description
Definition at line 66 of file DMMUWrapper.h.
Constructor & Destructor Documentation
DMMUWrapper() [1/2]
etiss::mm::DMMUWrapper::DMMUWrapper (std::shared_ptr< MMU > mmu) explicit
Definition at line 173 of file DMMUWrapper.cpp.
~DMMUWrapper() [1/2]
virtual etiss::mm::DMMUWrapper::~DMMUWrapper () inline virtual
Definition at line 72 of file DMMUWrapper.h.
DMMUWrapper() [2/2]
etiss::mm::DMMUWrapper::DMMUWrapper (std::shared_ptr< MMU > mmu) explicit
~DMMUWrapper() [2/2]
virtual etiss::mm::DMMUWrapper::~DMMUWrapper () inline virtual
Definition at line 72 of file DMMUWrapper.h.
Member Function Documentation
_getPluginName() [1/2]
std::string etiss::mm::DMMUWrapper::_getPluginName () const protected virtual
Implements etiss::Plugin.
Definition at line 210 of file DMMUWrapper.cpp.
References mmu_.
_getPluginName() [2/2]
std::string etiss::mm::DMMUWrapper::_getPluginName () const protected virtual
Implements etiss::Plugin.
unwrap() [1/2]
ETISS_System* etiss::mm::DMMUWrapper::unwrap (ETISS_CPU * cpu, ETISS_System * system) virtual
SystemWrapperPlugin interface to unwrap original ETISS_System.
Implements etiss::SystemWrapperPlugin.
unwrap() [2/2]
ETISS_System * etiss::mm::DMMUWrapper::unwrap (ETISS_CPU * cpu, ETISS_System * system) virtual
SystemWrapperPlugin interface to unwrap original ETISS_System.
Implements etiss::SystemWrapperPlugin.
Definition at line 203 of file DMMUWrapper.cpp.
wrap() [1/2]
ETISS_System* etiss::mm::DMMUWrapper::wrap (ETISS_CPU * cpu, ETISS_System * system) virtual
SystemWrapperPlugin interface to wrap around original ETISS_System.
Implements etiss::SystemWrapperPlugin.
wrap() [2/2]
ETISS_System * etiss::mm::DMMUWrapper::wrap (ETISS_CPU * cpu, ETISS_System * system) virtual
SystemWrapperPlugin interface to wrap around original ETISS_System.
Implements etiss::SystemWrapperPlugin.
Definition at line 178 of file DMMUWrapper.cpp.
References ETISS_System::dbg_read, etiss::mm::dbg_read(), ETISS_System::dbg_write, etiss::mm::dbg_write(), ETISS_System::dread, etiss::mm::dread(), ETISS_System::dwrite, etiss::mm::dwrite(), ETISS_System::handle, etiss::mm::iread(), ETISS_System::iread, etiss::mm::iwrite(), ETISS_System::iwrite, mmu_, etiss::mm::DMMUWrapperSystem::orig, ETISS_System::syncTime, etiss::mm::syncTime(), etiss::mm::DMMUWrapperSystem::sys, and etiss::mm::DMMUWrapperSystem::this_.
Member Data Documentation
mmu_
std::shared_ptr< MMU > etiss::mm::DMMUWrapper::mmu_
Definition at line 84 of file DMMUWrapper.h.
Referenced by _getPluginName(), and wrap().
The documentation for this class was generated from the following files:
include/etiss/mm/DMMUWrapper.h
/home/runner/work/etiss/etiss/src/mm/DMMUWrapper.cpp