ETISS 0.8.0: etiss::SimpleMemSystem Class Reference
etiss::SimpleMemSystem Class Reference
simple etiss:System implementation for testing
#include <SimpleMemSystem.h>
Classes
struct find_fitting_mseg
Public Member Functions
SimpleMemSystem (void)
virtual ~SimpleMemSystem (void)
etiss::int32 iread (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint32 len)
Instruction read operation.
etiss::int32 iwrite (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Instruction write operation.
etiss::int32 dread (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Data read operation.
etiss::int32 dwrite (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Data write operation.
etiss::int32 dbg_read (etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Debug read operation.
etiss::int32 dbg_write (etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Debug write operation.
void syncTime (ETISS_CPU *cpu)
Synchronize simulation time.
void init_memory ()
void load_elf ()
void load_segments (void)
etiss::uint64 get_startaddr (void)
void add_memsegment (std::unique_ptr< MemSegment > &mseg, const void *raw_data, size_t file_size_bytes)
SimpleMemSystem (void)
virtual ~SimpleMemSystem (void)
etiss::int32 iread (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint32 len)
Instruction read operation.
etiss::int32 iwrite (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Instruction write operation.
etiss::int32 dread (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Data read operation.
etiss::int32 dwrite (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Data write operation.
etiss::int32 dbg_read (etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Debug read operation.
etiss::int32 dbg_write (etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Debug write operation.
void syncTime (ETISS_CPU *cpu)
Synchronize simulation time.
void init_memory ()
void load_elf ()
void load_segments (void)
etiss::uint64 get_startaddr (void)
void add_memsegment (std::unique_ptr< MemSegment > &mseg, const void *raw_data, size_t file_size_bytes)
Public Member Functions inherited from etiss::System
virtual ~System ()
virtual ~System ()
Private Member Functions
template<bool write>
etiss::int32 dbus_access (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
template<bool write>
etiss::int32 dbus_access (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Private Attributes
std::vector< std::unique_ptr< MemSegment > > msegs_ {}
etiss::uint64 start_addr_ { 0 }
bool print_ibus_access_
bool print_dbus_access_
bool print_dbgbus_access_
bool print_to_file_
bool error_on_seg_mismatch_
int message_max_cnt_
std::ofstream trace_file_dbus_
std::map< etiss::uint64, etiss::uint64 > configured_address_spaces_
Detailed Description
simple etiss:System implementation for testing
Definition at line 138 of file SimpleMemSystem.h.
Constructor & Destructor Documentation
SimpleMemSystem() [1/2]
SimpleMemSystem::SimpleMemSystem (void)
Definition at line 273 of file SimpleMemSystem.cpp.
References etiss::cfg(), print_dbus_access_, and trace_file_dbus_.
~SimpleMemSystem() [1/2]
virtual etiss::SimpleMemSystem::~SimpleMemSystem (void) inline virtual
Definition at line 143 of file SimpleMemSystem.h.
References msegs_.
SimpleMemSystem() [2/2]
etiss::SimpleMemSystem::SimpleMemSystem (void)
~SimpleMemSystem() [2/2]
virtual etiss::SimpleMemSystem::~SimpleMemSystem (void) inline virtual
Definition at line 143 of file SimpleMemSystem.h.
References msegs_.
Member Function Documentation
add_memsegment() [1/2]
void SimpleMemSystem::add_memsegment (std::unique_ptr< MemSegment > & mseg, const void * raw_data, size_t file_size_bytes)
Definition at line 262 of file SimpleMemSystem.cpp.
References etiss::INFO, etiss::MemSegment::load(), etiss::log(), msegs_, and etiss::MemSegment::name_.
Referenced by load_elf(), and load_segments().
add_memsegment() [2/2]
void etiss::SimpleMemSystem::add_memsegment (std::unique_ptr< MemSegment > & mseg, const void * raw_data, size_t file_size_bytes)
dbg_read() [1/2]
etiss::int32 etiss::SimpleMemSystem::dbg_read (etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Debug read operation.
This method should implement a debug read operation. The debug operations are used for data access that should not influence the simulation time. To indicate an error a non 0 value should be returned.
Note
The read debug operation is used for the instruction fetches required for generating the code blocks.
Parameters
addr The address from which the data should be read.
buf Pointer to the buffer, that contains the instruction.
len The length of the data in bytes.
Returns
0 if no error occurred.
Implements etiss::System.
dbg_read() [2/2]
etiss::int32 SimpleMemSystem::dbg_read (etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Debug read operation.
This method should implement a debug read operation. The debug operations are used for data access that should not influence the simulation time. To indicate an error a non 0 value should be returned.
Note
The read debug operation is used for the instruction fetches required for generating the code blocks.
Parameters
addr The address from which the data should be read.
buf Pointer to the buffer, that contains the instruction.
len The length of the data in bytes.
Returns
0 if no error occurred.
Implements etiss::System.
Definition at line 369 of file SimpleMemSystem.cpp.
References dread().
dbg_write() [1/2]
etiss::int32 etiss::SimpleMemSystem::dbg_write (etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Debug write operation.
This method should implement a debug write operation. The debug operations are used for data access that should not influence the simulation time. To indicate an error a non 0 value should be returned.
Parameters
addr The address to which the data should be written.
buf Pointer to the buffer, that contains the instruction.
len The length of the data in bytes.
Returns
0 if no error occurred
Implements etiss::System.
dbg_write() [2/2]
etiss::int32 SimpleMemSystem::dbg_write (etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Debug write operation.
This method should implement a debug write operation. The debug operations are used for data access that should not influence the simulation time. To indicate an error a non 0 value should be returned.
Parameters
addr The address to which the data should be written.
buf Pointer to the buffer, that contains the instruction.
len The length of the data in bytes.
Returns
0 if no error occurred
Implements etiss::System.
Definition at line 374 of file SimpleMemSystem.cpp.
References dwrite().
dbus_access() [1/2]
template<bool write> etiss::int32 etiss::SimpleMemSystem::dbus_access (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) private
dbus_access() [2/2]
template<bool write> etiss::int32 SimpleMemSystem::dbus_access (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) private
Definition at line 331 of file SimpleMemSystem.cpp.
References access_error(), etiss::ERROR, memcpy(), msegs_, etiss::mm::NOERROR, print_dbus_access_, print_to_file_, etiss::MemSegment::READ, trace(), trace_file_dbus_, etiss::WARNING, and etiss::MemSegment::WRITE.
dread() [1/2]
etiss::int32 SimpleMemSystem::dread (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Data read operation.
This method should implement a data read operation. To indicate an error a non 0 value should be returned. The CPU time needs to be increased according to the delay of this instruction operation.
Parameters
cpu Pointer to the CPU structure, that requested this operation.
addr The address from which the data should be read.
buf Pointer to the buffer, that contains the instruction.
len The length of the data in bytes.
Returns
0 if no error occurred.
Implements etiss::System.
Definition at line 359 of file SimpleMemSystem.cpp.
Referenced by dbg_read().
dread() [2/2]
etiss::int32 etiss::SimpleMemSystem::dread (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Data read operation.
This method should implement a data read operation. To indicate an error a non 0 value should be returned. The CPU time needs to be increased according to the delay of this instruction operation.
Parameters
cpu Pointer to the CPU structure, that requested this operation.
addr The address from which the data should be read.
buf Pointer to the buffer, that contains the instruction.
len The length of the data in bytes.
Returns
0 if no error occurred.
Implements etiss::System.
dwrite() [1/2]
etiss::int32 etiss::SimpleMemSystem::dwrite (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Data write operation.
This method should implement a data write operation. To indicate an error a non 0 value should be returned. The CPU time needs to be increased according to the delay of this instruction operation.
Parameters
cpu Pointer to the CPU structure, that requested this operation.
addr The address to which the data should be written.
buf Pointer to the buffer, that contains the instruction.
len The length of the data in bytes.
Returns
0 if no error occurred.
Implements etiss::System.
dwrite() [2/2]
etiss::int32 SimpleMemSystem::dwrite (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Data write operation.
This method should implement a data write operation. To indicate an error a non 0 value should be returned. The CPU time needs to be increased according to the delay of this instruction operation.
Parameters
cpu Pointer to the CPU structure, that requested this operation.
addr The address to which the data should be written.
buf Pointer to the buffer, that contains the instruction.
len The length of the data in bytes.
Returns
0 if no error occurred.
Implements etiss::System.
Definition at line 364 of file SimpleMemSystem.cpp.
Referenced by dbg_write().
get_startaddr() [1/2]
etiss::uint64 etiss::SimpleMemSystem::get_startaddr (void) inline
Definition at line 162 of file SimpleMemSystem.h.
References start_addr_.
get_startaddr() [2/2]
etiss::uint64 etiss::SimpleMemSystem::get_startaddr (void) inline
Definition at line 162 of file SimpleMemSystem.h.
References start_addr_.
init_memory() [1/2]
void SimpleMemSystem::init_memory ()
Definition at line 78 of file SimpleMemSystem.cpp.
References b, load_elf(), load_segments(), msegs_, and sort().
init_memory() [2/2]
void etiss::SimpleMemSystem::init_memory ()
iread() [1/2]
etiss::int32 SimpleMemSystem::iread (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint32 len) virtual
Instruction read operation.
This method should implement an instruction read operation. To indicate an error a non 0 value should be returned. The CPU time needs to be increased according to the delay of this instruction operation.
Note
Normally this method can be implemented as an empty method that only returns an error value. Because of the translating nature of ETISS all instruction operations are out of order an will be performed via the debug interface.
Parameters
cpu Pointer to the CPU structure, that requested this operation.
addr The address from which the instruction should be read.
len The length of the instruction in bytes.
Returns
0 if no error occurred
Implements etiss::System.
Definition at line 298 of file SimpleMemSystem.cpp.
References access_error(), etiss::ERROR, msegs_, and etiss::mm::NOERROR.
iread() [2/2]
etiss::int32 etiss::SimpleMemSystem::iread (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint32 len) virtual
Instruction read operation.
This method should implement an instruction read operation. To indicate an error a non 0 value should be returned. The CPU time needs to be increased according to the delay of this instruction operation.
Note
Normally this method can be implemented as an empty method that only returns an error value. Because of the translating nature of ETISS all instruction operations are out of order an will be performed via the debug interface.
Parameters
cpu Pointer to the CPU structure, that requested this operation.
addr The address from which the instruction should be read.
len The length of the instruction in bytes.
Returns
0 if no error occurred
Implements etiss::System.
iwrite() [1/2]
etiss::int32 SimpleMemSystem::iwrite (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Instruction write operation.
This method should implement an instruction write operation. To indicate an error a non 0 value should be returned. The CPU time needs to be increased according to the delay of this instruction operation.
Note
Normally this method can be implemented as an empty method that only returns an error value. Because of the translating nature of ETISS all instruction operations are out of order an will be performed via the debug interface
Parameters
cpu Pointer to the CPU structure, that requested this operation.
addr The address to which the instruction should be written.
buf Pointer to the buffer, that contains the instruction.
len The length of the instruction in bytes.
Returns
0 if no error occurred.
Implements etiss::System.
Definition at line 307 of file SimpleMemSystem.cpp.
References access_error(), and etiss::ERROR.
iwrite() [2/2]
etiss::int32 etiss::SimpleMemSystem::iwrite (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Instruction write operation.
This method should implement an instruction write operation. To indicate an error a non 0 value should be returned. The CPU time needs to be increased according to the delay of this instruction operation.
Note
Normally this method can be implemented as an empty method that only returns an error value. Because of the translating nature of ETISS all instruction operations are out of order an will be performed via the debug interface
Parameters
cpu Pointer to the CPU structure, that requested this operation.
addr The address to which the instruction should be written.
buf Pointer to the buffer, that contains the instruction.
len The length of the instruction in bytes.
Returns
0 if no error occurred.
Implements etiss::System.
load_elf() [1/2]
void SimpleMemSystem::load_elf ()
Definition at line 152 of file SimpleMemSystem.cpp.
References add_memsegment(), etiss::cfg(), error_on_seg_mismatch_, etiss::MemSegment::EXEC, etiss::FATALERROR, etiss::Configuration::get(), etiss::INFO, etiss::log(), msegs_, etiss::MemSegment::READ, etiss::Configuration::set(), start_addr_, etiss::WARNING, and etiss::MemSegment::WRITE.
Referenced by init_memory().
load_elf() [2/2]
void etiss::SimpleMemSystem::load_elf ()
load_segments() [1/2]
void SimpleMemSystem::load_segments (void)
Definition at line 84 of file SimpleMemSystem.cpp.
References add_memsegment(), etiss::cfg(), configured_address_spaces_, etiss::MemSegment::EXEC, etiss::FATALERROR, etiss::Configuration::get(), length(), etiss::log(), MAX_MEMSEGS, etiss::MemSegment::READ, etiss::MemSegment::UNSET, and etiss::MemSegment::WRITE.
Referenced by init_memory().
load_segments() [2/2]
void etiss::SimpleMemSystem::load_segments (void)
syncTime() [1/2]
void etiss::SimpleMemSystem::syncTime (ETISS_CPU * cpu) virtual
Synchronize simulation time.
This method should implement the synchronization between the simulation time of the system and the CPU. This function call should allow the system to catch up with the CPU.
See also
etiss::ETISS_CPU
Parameters
cpu Pointer to the CPU structure, for which the synchronization should be performed.
Implements etiss::System.
syncTime() [2/2]
void SimpleMemSystem::syncTime (ETISS_CPU * cpu) virtual
Synchronize simulation time.
This method should implement the synchronization between the simulation time of the system and the CPU. This function call should allow the system to catch up with the CPU.
See also
etiss::ETISS_CPU
Parameters
cpu Pointer to the CPU structure, for which the synchronization should be performed.
Implements etiss::System.
Definition at line 380 of file SimpleMemSystem.cpp.
Member Data Documentation
configured_address_spaces_
std::map< etiss::uint64, etiss::uint64 > etiss::SimpleMemSystem::configured_address_spaces_ private
Definition at line 191 of file SimpleMemSystem.h.
Referenced by load_segments().
error_on_seg_mismatch_
bool etiss::SimpleMemSystem::error_on_seg_mismatch_ private
Definition at line 185 of file SimpleMemSystem.h.
Referenced by load_elf().
message_max_cnt_
int etiss::SimpleMemSystem::message_max_cnt_ private
Definition at line 187 of file SimpleMemSystem.h.
msegs_
std::vector< std::unique_ptr< MemSegment > > etiss::SimpleMemSystem::msegs_ {} private
Definition at line 166 of file SimpleMemSystem.h.
Referenced by add_memsegment(), dbus_access(), init_memory(), iread(), load_elf(), and ~SimpleMemSystem().
print_dbgbus_access_
bool etiss::SimpleMemSystem::print_dbgbus_access_ private
Definition at line 182 of file SimpleMemSystem.h.
print_dbus_access_
bool etiss::SimpleMemSystem::print_dbus_access_ private
Definition at line 181 of file SimpleMemSystem.h.
Referenced by dbus_access(), and SimpleMemSystem().
print_ibus_access_
bool etiss::SimpleMemSystem::print_ibus_access_ private
Definition at line 180 of file SimpleMemSystem.h.
print_to_file_
bool etiss::SimpleMemSystem::print_to_file_ private
Definition at line 183 of file SimpleMemSystem.h.
Referenced by dbus_access().
start_addr_
etiss::uint64 etiss::SimpleMemSystem::start_addr_ { 0 } private
Definition at line 171 of file SimpleMemSystem.h.
Referenced by get_startaddr(), and load_elf().
trace_file_dbus_
std::ofstream etiss::SimpleMemSystem::trace_file_dbus_ private
Definition at line 189 of file SimpleMemSystem.h.
Referenced by dbus_access(), and SimpleMemSystem().
The documentation for this class was generated from the following files:
include/etiss/SimpleMemSystem.h
/home/runner/work/etiss/etiss/src/SimpleMemSystem.cpp