ETISS 0.8.0: etiss::plugin::InstructionSpecificAddressCallback Class Reference
etiss::plugin::InstructionSpecificAddressCallback Class Reference abstract
a simple plugin that prints the instruction and address when an instruction is executed
#include <InstructionSpecificAddressCallback.h>
Classes
struct Data
Public Member Functions
InstructionSpecificAddressCallback ()
~InstructionSpecificAddressCallback ()
virtual bool callback ()=0
implement this callback to manipulate the cpu be fore executing the defined instructions at the defined address
virtual bool callbackOnInstruction (etiss::instr::Instruction &instr) const
implement to return true to call InstructionSpecificAddressCallback::callback whenever that etiss::instr::Instruction is executed.
virtual void addCallbackAddress (uint64_t addr)
call to add an address at which callback should be called upon execution.
virtual void removeCallbackAddress (uint64_t addr)
const std::set< uint64_t > & callbackAddresses () const
virtual void finalizeInstrSet (etiss::instr::ModedInstructionSet &) const
called after all instructions have been added to allow last changes
virtual void initCodeBlock (etiss::CodeBlock &block) const
called before instructions are translated for the code block
virtual std::string _getPluginName () const
virtual void * getPluginHandle ()
called to get the handle that is available in translated code via getPoinerCode(). [default: this]
InstructionSpecificAddressCallback ()
~InstructionSpecificAddressCallback ()
virtual bool callback ()=0
implement this callback to manipulate the cpu be fore executing the defined instructions at the defined address
virtual bool callbackOnInstruction (etiss::instr::Instruction &instr) const
implement to return true to call InstructionSpecificAddressCallback::callback whenever that etiss::instr::Instruction is executed.
virtual void addCallbackAddress (uint64_t addr)
call to add an address at which callback should be called upon execution.
virtual void removeCallbackAddress (uint64_t addr)
const std::set< uint64_t > & callbackAddresses () const
virtual void finalizeInstrSet (etiss::instr::ModedInstructionSet &) const
called after all instructions have been added to allow last changes
virtual void initCodeBlock (etiss::CodeBlock &block) const
called before instructions are translated for the code block
virtual std::string _getPluginName () const
virtual void * getPluginHandle ()
called to get the handle that is available in translated code via getPoinerCode(). [default: this]
Public Member Functions inherited from etiss::TranslationPlugin
TranslationPlugin ()
virtual ~TranslationPlugin ()
virtual void initInstrSet (etiss::instr::ModedInstructionSet &) const
called to add instructions to the instruction set
virtual void finalizeCodeBlock (etiss::CodeBlock &) const
called after all instructions have been translated for the code block
TranslationPlugin ()
virtual ~TranslationPlugin ()
virtual void initInstrSet (etiss::instr::ModedInstructionSet &) const
called to add instructions to the instruction set
virtual void finalizeCodeBlock (etiss::CodeBlock &) const
called after all instructions have been translated for the code block
Public Member Functions inherited from etiss::Plugin
virtual ~Plugin ()
unsigned getType ()
InterruptListenerPlugin * getInterruptListenerPlugin ()
CoroutinePlugin * getCoroutinePlugin ()
SystemWrapperPlugin * getSystemWrapperPlugin ()
RegisterDevicePlugin * getRegisterDevicePlugin ()
TranslationPlugin * getTranslationPlugin ()
std::string getPluginName () const
const std::string & getLastAssignedCoreName ()
std::string toString () const
virtual ~Plugin ()
unsigned getType ()
InterruptListenerPlugin * getInterruptListenerPlugin ()
CoroutinePlugin * getCoroutinePlugin ()
SystemWrapperPlugin * getSystemWrapperPlugin ()
RegisterDevicePlugin * getRegisterDevicePlugin ()
TranslationPlugin * getTranslationPlugin ()
std::string getPluginName () const
const std::string & getLastAssignedCoreName ()
std::string toString () const
Public Member Functions inherited from etiss::ToString
ToString ()
virtual ~ToString ()
ToString ()
virtual ~ToString ()
Private Attributes
Data pluginData_
std::set< uint64_t > caddrset_
Additional Inherited Members
Static Public Attributes inherited from etiss::Plugin
static const unsigned INTERRUPTLISTENER = 1 << 0
access to translated code
static const unsigned COROUTINE = 1 << 1
callback after execution of each translated block
static const unsigned SYSTEMWRAPPER = 1 << 2
can wrap/change ETISS_System structure at execution start
static const unsigned REGISTERDEVICE
gets noticed of changes to special registers (e.g. mmu register etc. [depends on architecture])
static const unsigned TRANSLATION
access to translated code during translation phase or when instruction tree is built
Protected Member Functions inherited from etiss::TranslationPlugin
std::string getPointerCode () const
returns a C code expression that allows to get or assign a pointer to the variable assigned to this translation plugin.
std::string getPointerCode () const
returns a C code expression that allows to get or assign a pointer to the variable assigned to this translation plugin.
Protected Member Functions inherited from etiss::Plugin
Plugin (unsigned type=0)
virtual void init (ETISS_CPU *cpu, ETISS_System *system, CPUArch *arch)
this function is called before the plugin is used in the cpu execution loop (etiss::CPUCore::execute).
virtual void cleanup ()
this function is called after cpu execution loop (etiss::CPUCore::execute) finished.
void setCorrespondingCPUCoreName (std::string name)
virtual void addedToCPUCore (etiss::CPUCore *core)
called as soon a plugin has been added to its CPUCore.
virtual void removedFromCPUCore (etiss::CPUCore *core)
called as soon a plugin has been removed from its CPUCore.
Plugin (unsigned type=0)
virtual void init (ETISS_CPU *cpu, ETISS_System *system, CPUArch *arch)
this function is called before the plugin is used in the cpu execution loop (etiss::CPUCore::execute).
virtual void cleanup ()
this function is called after cpu execution loop (etiss::CPUCore::execute) finished.
void setCorrespondingCPUCoreName (std::string name)
virtual void addedToCPUCore (etiss::CPUCore *core)
called as soon a plugin has been added to its CPUCore.
virtual void removedFromCPUCore (etiss::CPUCore *core)
called as soon a plugin has been removed from its CPUCore.
Protected Attributes inherited from etiss::Plugin
ETISS_CPU * plugin_cpu_
holds a pointer to the cpu structure. will be set before init call and after cleanup call
ETISS_System * plugin_system_
holds a pointer to the system structure.
CPUArch * plugin_arch_
holds a pointer to the CPUArch instance. will be set before init call and after cleanup call
CPUCore * plugin_core_
holds a pointer to the associated CPUCore instance.
Detailed Description
a simple plugin that prints the instruction and address when an instruction is executed
Definition at line 67 of file InstructionSpecificAddressCallback.h.
Constructor & Destructor Documentation
InstructionSpecificAddressCallback() [1/2]
InstructionSpecificAddressCallback::InstructionSpecificAddressCallback ()
Definition at line 78 of file InstructionSpecificAddressCallback.cpp.
References pluginData_, etiss::plugin::InstructionSpecificAddressCallback::Data::state_, and etiss::plugin::InstructionSpecificAddressCallback::Data::this_.
~InstructionSpecificAddressCallback() [1/2]
InstructionSpecificAddressCallback::~InstructionSpecificAddressCallback ()
Definition at line 83 of file InstructionSpecificAddressCallback.cpp.
InstructionSpecificAddressCallback() [2/2]
etiss::plugin::InstructionSpecificAddressCallback::InstructionSpecificAddressCallback ()
~InstructionSpecificAddressCallback() [2/2]
etiss::plugin::InstructionSpecificAddressCallback::~InstructionSpecificAddressCallback ()
Member Function Documentation
_getPluginName() [1/2]
std::string InstructionSpecificAddressCallback::_getPluginName () const virtual
Implements etiss::Plugin.
Definition at line 143 of file InstructionSpecificAddressCallback.cpp.
_getPluginName() [2/2]
virtual std::string etiss::plugin::InstructionSpecificAddressCallback::_getPluginName () const virtual
Implements etiss::Plugin.
addCallbackAddress() [1/2]
virtual void etiss::plugin::InstructionSpecificAddressCallback::addCallbackAddress (uint64_t addr) inline virtual
call to add an address at which callback should be called upon execution.
May be changed during execution.please not that only aligned addresses will have an effect.
Definition at line 93 of file InstructionSpecificAddressCallback.h.
References caddrset_, pluginData_, and etiss::plugin::InstructionSpecificAddressCallback::Data::state_.
addCallbackAddress() [2/2]
virtual void etiss::plugin::InstructionSpecificAddressCallback::addCallbackAddress (uint64_t addr) inline virtual
call to add an address at which callback should be called upon execution.
May be changed during execution.please not that only aligned addresses will have an effect.
Definition at line 93 of file InstructionSpecificAddressCallback.h.
References caddrset_, pluginData_, and etiss::plugin::InstructionSpecificAddressCallback::Data::state_.
callback() [1/2]
virtual bool etiss::plugin::InstructionSpecificAddressCallback::callback () pure virtual
implement this callback to manipulate the cpu be fore executing the defined instructions at the defined address
callback() [2/2]
virtual bool etiss::plugin::InstructionSpecificAddressCallback::callback () pure virtual
implement this callback to manipulate the cpu be fore executing the defined instructions at the defined address
callbackAddresses() [1/2]
const std::set<uint64_t>& etiss::plugin::InstructionSpecificAddressCallback::callbackAddresses () const inline
Definition at line 104 of file InstructionSpecificAddressCallback.h.
References caddrset_.
Referenced by finalizeInstrSet().
callbackAddresses() [2/2]
const std::set<uint64_t>& etiss::plugin::InstructionSpecificAddressCallback::callbackAddresses () const inline
Definition at line 104 of file InstructionSpecificAddressCallback.h.
References caddrset_.
callbackOnInstruction() [1/2]
virtual bool etiss::plugin::InstructionSpecificAddressCallback::callbackOnInstruction (etiss::instr::Instruction & instr) const inline virtual
implement to return true to call InstructionSpecificAddressCallback::callback whenever that etiss::instr::Instruction is executed.
used by finalizeInstrSet
Definition at line 89 of file InstructionSpecificAddressCallback.h.
Referenced by finalizeInstrSet().
callbackOnInstruction() [2/2]
virtual bool etiss::plugin::InstructionSpecificAddressCallback::callbackOnInstruction (etiss::instr::Instruction & instr) const inline virtual
implement to return true to call InstructionSpecificAddressCallback::callback whenever that etiss::instr::Instruction is executed.
used by finalizeInstrSet
Definition at line 89 of file InstructionSpecificAddressCallback.h.
finalizeInstrSet() [1/2]
virtual void etiss::plugin::InstructionSpecificAddressCallback::finalizeInstrSet (etiss::instr::ModedInstructionSet &) const virtual
called after all instructions have been added to allow last changes
Reimplemented from etiss::TranslationPlugin.
finalizeInstrSet() [2/2]
void InstructionSpecificAddressCallback::finalizeInstrSet (etiss::instr::ModedInstructionSet &) const virtual
called after all instructions have been added to allow last changes
Reimplemented from etiss::TranslationPlugin.
Definition at line 93 of file InstructionSpecificAddressCallback.cpp.
References etiss::instr::Instruction::addCallback(), etiss::CodeSet::append(), callbackAddresses(), callbackOnInstruction(), etiss::instr::InstructionContext::current_address_, etiss::instr::InstructionSet::foreach(), etiss::instr::VariableInstructionSet::foreach(), etiss::instr::ModedInstructionSet::foreach(), etiss::TranslationPlugin::getPointerCode(), and etiss::CodePart::PREINITIALDEBUGRETURNING.
getPluginHandle() [1/2]
void * InstructionSpecificAddressCallback::getPluginHandle () virtual
called to get the handle that is available in translated code via getPoinerCode(). [default: this]
Reimplemented from etiss::TranslationPlugin.
Definition at line 148 of file InstructionSpecificAddressCallback.cpp.
References pluginData_.
getPluginHandle() [2/2]
virtual void* etiss::plugin::InstructionSpecificAddressCallback::getPluginHandle () virtual
called to get the handle that is available in translated code via getPoinerCode(). [default: this]
Reimplemented from etiss::TranslationPlugin.
initCodeBlock() [1/2]
virtual void etiss::plugin::InstructionSpecificAddressCallback::initCodeBlock (etiss::CodeBlock &) const virtual
called before instructions are translated for the code block
Reimplemented from etiss::TranslationPlugin.
initCodeBlock() [2/2]
void InstructionSpecificAddressCallback::initCodeBlock (etiss::CodeBlock &) const virtual
called before instructions are translated for the code block
Reimplemented from etiss::TranslationPlugin.
Definition at line 85 of file InstructionSpecificAddressCallback.cpp.
References etiss::CodeBlock::fileglobalCode(), etiss::CodeBlock::functionglobalCode(), etiss::TranslationPlugin::getPointerCode(), pluginData_, etiss::plugin::InstructionSpecificAddressCallback::Data::state_, and etiss::toString().
removeCallbackAddress() [1/2]
virtual void etiss::plugin::InstructionSpecificAddressCallback::removeCallbackAddress (uint64_t addr) inline virtual
Definition at line 98 of file InstructionSpecificAddressCallback.h.
References caddrset_, pluginData_, and etiss::plugin::InstructionSpecificAddressCallback::Data::state_.
removeCallbackAddress() [2/2]
virtual void etiss::plugin::InstructionSpecificAddressCallback::removeCallbackAddress (uint64_t addr) inline virtual
Definition at line 98 of file InstructionSpecificAddressCallback.h.
References caddrset_, pluginData_, and etiss::plugin::InstructionSpecificAddressCallback::Data::state_.
Member Data Documentation
caddrset_
std::set< uint64_t > etiss::plugin::InstructionSpecificAddressCallback::caddrset_ private
Definition at line 79 of file InstructionSpecificAddressCallback.h.
Referenced by addCallbackAddress(), callbackAddresses(), and removeCallbackAddress().
pluginData_
Data etiss::plugin::InstructionSpecificAddressCallback::pluginData_ private
Definition at line 78 of file InstructionSpecificAddressCallback.h.
Referenced by addCallbackAddress(), getPluginHandle(), initCodeBlock(), InstructionSpecificAddressCallback(), and removeCallbackAddress().
The documentation for this class was generated from the following files:
include/etiss/IntegratedLibrary/InstructionSpecificAddressCallback.h
/home/runner/work/etiss/etiss/src/IntegratedLibrary/InstructionSpecificAddressCallback.cpp