ETISS 0.8.0: etiss::fault::InjectorAddress Class Reference
etiss::fault::InjectorAddress Class Reference
#include <InjectorAddress.h>
Public Member Functions
InjectorAddress ()
InjectorAddress (const std::string &address)
InjectorAddress (const InjectorAddress &)
InjectorAddress & operator= (const InjectorAddress &)
const std::string & getInjectorPath () const
const Injector_ptr & getInjector () const
bool isResolved () const
> Calls Injector::get (implemented in VirtualStruct) to resolve path_ and get iptr_
std::string toString () const
InjectorAddress ()
InjectorAddress (const std::string &address)
InjectorAddress (const InjectorAddress &)
InjectorAddress & operator= (const InjectorAddress &)
const std::string & getInjectorPath () const
const Injector_ptr & getInjector () const
bool isResolved () const
> Calls Injector::get (implemented in VirtualStruct) to resolve path_ and get iptr_
std::string toString () const
Public Member Functions inherited from etiss::ToString
ToString ()
virtual ~ToString ()
ToString ()
virtual ~ToString ()
Private Attributes
std::string path_
Contains the VirtualStruct as string where the Injector refers to.
Injector_ptr iptr_
Contains the pointer to the Injector.
Detailed Description
Definition at line 73 of file InjectorAddress.h.
Constructor & Destructor Documentation
InjectorAddress() [1/6]
etiss::fault::InjectorAddress::InjectorAddress ()
Definition at line 56 of file InjectorAddress.cpp.
References iptr_, etiss::log(), path_, and etiss::VERBOSE.
InjectorAddress() [2/6]
etiss::fault::InjectorAddress::InjectorAddress (const std::string & address)
Definition at line 62 of file InjectorAddress.cpp.
References iptr_, etiss::log(), path_, and etiss::VERBOSE.
InjectorAddress() [3/6]
etiss::fault::InjectorAddress::InjectorAddress (const InjectorAddress & cpy)
Definition at line 68 of file InjectorAddress.cpp.
References etiss::log(), toString(), and etiss::VERBOSE.
InjectorAddress() [4/6]
etiss::fault::InjectorAddress::InjectorAddress ()
InjectorAddress() [5/6]
etiss::fault::InjectorAddress::InjectorAddress (const std::string & address)
InjectorAddress() [6/6]
etiss::fault::InjectorAddress::InjectorAddress (const InjectorAddress &)
Member Function Documentation
getInjector() [1/2]
const Injector_ptr & etiss::fault::InjectorAddress::getInjector () const
Definition at line 103 of file InjectorAddress.cpp.
References etiss::ERROR, etiss::fault::Injector::get(), iptr_, etiss::log(), and path_.
Referenced by etiss::fault::Trigger::fired(), etiss::fault::Trigger::getInjector(), etiss::fault::Trigger::operator=(), and etiss::fault::Trigger::~Trigger().
getInjector() [2/2]
const Injector_ptr& etiss::fault::InjectorAddress::getInjector () const
getInjectorPath() [1/2]
const std::string & etiss::fault::InjectorAddress::getInjectorPath () const
Definition at line 99 of file InjectorAddress.cpp.
References path_.
Referenced by etiss::fault::Action::Action(), etiss::fault::Trigger::fired(), and toString().
getInjectorPath() [2/2]
const std::string& etiss::fault::InjectorAddress::getInjectorPath () const
isResolved() [1/2]
bool etiss::fault::InjectorAddress::isResolved () const
> Calls Injector::get (implemented in VirtualStruct) to resolve path_ and get iptr_
Definition at line 123 of file InjectorAddress.cpp.
References iptr_.
Referenced by etiss::fault::Trigger::operator=(), and etiss::fault::Trigger::~Trigger().
isResolved() [2/2]
bool etiss::fault::InjectorAddress::isResolved () const
> Calls Injector::get (implemented in VirtualStruct) to resolve path_ and get iptr_
operator=() [1/2]
InjectorAddress& etiss::fault::InjectorAddress::operator= (const InjectorAddress &)
operator=() [2/2]
InjectorAddress & etiss::fault::InjectorAddress::operator= (const InjectorAddress & cpy)
Definition at line 74 of file InjectorAddress.cpp.
References iptr_, etiss::log(), path_, toString(), and etiss::VERBOSE.
toString() [1/2]
std::string etiss::fault::InjectorAddress::toString () const inline
Definition at line 95 of file InjectorAddress.h.
References getInjectorPath().
toString() [2/2]
std::string etiss::fault::InjectorAddress::toString () const inline
Definition at line 95 of file InjectorAddress.h.
References getInjectorPath().
Referenced by InjectorAddress(), and operator=().
Member Data Documentation
iptr_
Injector_ptr etiss::fault::InjectorAddress::iptr_ mutable private
Contains the pointer to the Injector.
Definition at line 77 of file InjectorAddress.h.
Referenced by getInjector(), InjectorAddress(), isResolved(), and operator=().
path_
std::string etiss::fault::InjectorAddress::path_ private
Contains the VirtualStruct as string where the Injector refers to.
Definition at line 76 of file InjectorAddress.h.
Referenced by getInjector(), getInjectorPath(), InjectorAddress(), and operator=().
The documentation for this class was generated from the following files:
include/etiss/fault/InjectorAddress.h
/home/runner/work/etiss/etiss/src/fault/InjectorAddress.cpp