ETISS 0.8.0: etiss::Translation Class Reference
etiss::Translation Class Reference
#include <Translation.h>
Public Member Functions
Translation (std::shared_ptr< etiss::CPUArch > &arch, std::shared_ptr< etiss::JIT > &jit, std::list< std::shared_ptr< etiss::Plugin >> &plugins, ETISS_System &system, ETISS_CPU &cpu)
~Translation ()
void ** init ()
BlockLink * getBlockFast (BlockLink *prev, const etiss::uint64 &instructionindex)
CALL THIS function NOT getBlock(...) since getBlock will not check next/branch references.
BlockLink * getBlock (BlockLink *prev, const etiss::uint64 &instructionindex)
etiss::int32 translateBlock (CodeBlock &cb)
void unloadBlocks (etiss::uint64 startindex=0, etiss::uint64 endindex=((etiss::uint64)((etiss::int64) -1)))
std::string disasm (uint8_t *buf, unsigned len, int &append)
Translation (std::shared_ptr< etiss::CPUArch > &arch, std::shared_ptr< etiss::JIT > &jit, std::list< std::shared_ptr< etiss::Plugin >> &plugins, ETISS_System &system, ETISS_CPU &cpu)
~Translation ()
void ** init ()
BlockLink * getBlockFast (BlockLink *prev, const etiss::uint64 &instructionindex)
CALL THIS function NOT getBlock(...) since getBlock will not check next/branch references.
BlockLink * getBlock (BlockLink *prev, const etiss::uint64 &instructionindex)
etiss::int32 translateBlock (CodeBlock &cb)
void unloadBlocks (etiss::uint64 startindex=0, etiss::uint64 endindex=((etiss::uint64)((etiss::int64) -1)))
std::string disasm (uint8_t *buf, unsigned len, int &append)
Private Attributes
std::shared_ptr< etiss::CPUArch > & archptr_
std::shared_ptr< etiss::JIT > & jitptr_
etiss::CPUArch *const arch_
etiss::JIT *const jit_
std::list< std::shared_ptr< etiss::Plugin > > & plugins_
ETISS_System & system_
ETISS_CPU & cpu_
etiss::TranslationPlugin ** plugins_array_
void ** plugins_handle_array_
size_t plugins_array_size_
void(* plugins_initCodeBlock_)(etiss::TranslationPlugin **, CodeBlock &)
Function pointer, the function is getting defined in Translation::init via template function etiss::call_initCodeBlock It calls the TranslationPlugin::initCodeBlock functions of all translation plugins.
void(* plugins_finalizeCodeBlock_)(etiss::TranslationPlugin **, CodeBlock &)
Function pointer, the function is getting defined in Translation::init via template function etiss::call_finalizeCodeBlock It calls the TranslationPlugin::finalizeCodeBlock functions of all translation plugins.
etiss::instr::ModedInstructionSet * mis_
std::unordered_map< etiss::uint64, std::list< BlockLink * > > blockmap_
const uint64_t id
unique id used to generate unique function names across translation instances
uint64_t tblockcount
countes translated blocks. needed to guarantee unique block function names
Detailed Description
Definition at line 121 of file Translation.h.
Constructor & Destructor Documentation
Translation() [1/2]
etiss::Translation::Translation (std::shared_ptr< etiss::CPUArch > & arch, std::shared_ptr< etiss::JIT > & jit, std::list< std::shared_ptr< etiss::Plugin >> & plugins, ETISS_System & system, ETISS_CPU & cpu)
Definition at line 117 of file Translation.cpp.
References tblockcount.
~Translation() [1/2]
etiss::Translation::~Translation ()
Definition at line 139 of file Translation.cpp.
References mis_, plugins_array_, plugins_handle_array_, and unloadBlocks().
Translation() [2/2]
etiss::Translation::Translation (std::shared_ptr< etiss::CPUArch > & arch, std::shared_ptr< etiss::JIT > & jit, std::list< std::shared_ptr< etiss::Plugin >> & plugins, ETISS_System & system, ETISS_CPU & cpu)
~Translation() [2/2]
etiss::Translation::~Translation ()
Member Function Documentation
disasm() [1/2]
std::string etiss::Translation::disasm (uint8_t * buf, unsigned len, int & append)
Definition at line 615 of file Translation.cpp.
References cpu_, etiss::instr::VariableInstructionSet::get(), etiss::instr::ModedInstructionSet::get(), etiss::instr::BitArray::internalBuffer(), memcpy(), mis_, ETISS_CPU::mode, etiss::instr::Instruction::printASM(), and etiss::instr::InstructionSet::resolve().
disasm() [2/2]
std::string etiss::Translation::disasm (uint8_t * buf, unsigned len, int & append)
getBlock() [1/2]
BlockLink* etiss::Translation::getBlock (BlockLink * prev, const etiss::uint64 & instructionindex)
getBlock() [2/2]
BlockLink * etiss::Translation::getBlock (BlockLink * prev, const etiss::uint64 & instructionindex)
Definition at line 263 of file Translation.cpp.
References arch_, blockmap_, etiss::BlockLink::branch, etiss::cfg(), cpu_, etiss::BlockLink::decrRef(), etiss::BlockLink::end, etiss::CodeBlock::endaddress_, etiss::ERROR, ETISS_DEBUG, etiss::CodeBlock::fileglobalCode(), etiss::CodeBlock::functionglobalCode(), etiss::JIT::getFunction(), etiss::CPUArch::getIncludePath(), etiss::BlockLink::incrRef(), jit_, etiss::jitExtHeaderPaths(), etiss::jitExtHeaders(), etiss::jitExtLibPaths(), etiss::jitExtLibraries(), etiss::jitFiles(), etiss::log(), ETISS_CPU::mode, etiss::BlockLink::next, plugins_array_, plugins_finalizeCodeBlock_, plugins_initCodeBlock_, etiss::BlockLink::start, etiss::CodeBlock::startindex_, tblockcount, etiss::CodeBlock::toCode(), etiss::toString(), etiss::JIT::translate(), translateBlock(), etiss::BlockLink::updateRef(), and etiss::BlockLink::valid.
Referenced by getBlockFast().
getBlockFast() [1/2]
BlockLink* etiss::Translation::getBlockFast (BlockLink * prev, const etiss::uint64 & instructionindex) inline
CALL THIS function NOT getBlock(...) since getBlock will not check next/branch references.
Returns
a reference to a block containing the instruction index if it is referenced by the current block
Definition at line 165 of file Translation.h.
References getBlock(), and etiss::BlockLink::updateRef().
getBlockFast() [2/2]
BlockLink* etiss::Translation::getBlockFast (BlockLink * prev, const etiss::uint64 & instructionindex) inline
CALL THIS function NOT getBlock(...) since getBlock will not check next/branch references.
Returns
a reference to a block containing the instruction index if it is referenced by the current block
Definition at line 165 of file Translation.h.
References etiss::BlockLink::branch, etiss::BlockLink::end, getBlock(), etiss::BlockLink::next, etiss::BlockLink::start, etiss::BlockLink::updateRef(), and etiss::BlockLink::valid.
Referenced by etiss::CPUCore::execute().
init() [1/2]
void ** etiss::Translation::init ()
TODO verify instructions, add an error message here
Definition at line 147 of file Translation.cpp.
References arch_, etiss::call_finalizeCodeBlock_ul(), etiss::call_initCodeBlock_ul(), etiss::instr::ModedInstructionSet::compile(), etiss::ERROR, etiss::TranslationPlugin::finalizeInstrSet(), etiss::CPUArch::getName(), etiss::TranslationPlugin::getPluginHandle(), etiss::Plugin::getTranslationPlugin(), etiss::TranslationPlugin::initInstrSet(), jit_, etiss::log(), mis_, plugins_, plugins_array_, plugins_array_size_, plugins_finalizeCodeBlock_, plugins_handle_array_, plugins_initCodeBlock_, etiss::TranslationPlugin::pointerCode, and etiss::toString().
Referenced by etiss::CPUCore::execute().
init() [2/2]
void** etiss::Translation::init ()
translateBlock() [1/2]
etiss::int32 etiss::Translation::translateBlock (CodeBlock & cb)
translateBlock() [2/2]
etiss::int32 etiss::Translation::translateBlock (CodeBlock & cb)
Note
this function only does the instruction to C code translation. compilation (C code to function pointer) is done in getBlock()
Definition at line 444 of file Translation.cpp.
References etiss::CodeSet::append(), etiss::CodeBlock::append(), arch_, etiss::instr::BitArray::byteCount(), etiss::instr::InstructionContext::cf_delay_slot_, etiss::cfg(), etiss::CPUArch::compensateEndianess(), cpu_, etiss::instr::InstructionContext::current_address_, etiss::instr::InstructionContext::current_local_address_, ETISS_System::dbg_read, etiss::CodeBlock::endaddress_, etiss::instr::InstructionContext::force_append_next_instr_, etiss::instr::InstructionContext::force_block_end_, etiss::Configuration::get(), etiss::instr::InstructionSet::get(), etiss::instr::ModedInstructionSet::get(), etiss::CodeBlock::Line::getCodeSet(), etiss::instr::InstructionSet::getInvalid(), ETISS_System::handle, etiss::instr::InstructionContext::instr_width_, etiss::instr::InstructionContext::instr_width_fully_evaluated_, etiss::instr::BitArray::internalBuffer(), etiss::instr::InstructionContext::is_not_default_width_, mis_, ETISS_CPU::mode, etiss::mm::NOERROR, etiss::CodePart::PREINITIALDEBUGRETURNING, etiss::instr::InstructionSet::resolve(), etiss::CodeBlock::startindex_, system_, etiss::instr::Instruction::translate(), unlikely, and etiss::instr::BitArray::width().
Referenced by getBlock().
unloadBlocks() [1/2]
void etiss::Translation::unloadBlocks (etiss::uint64 startindex = 0, etiss::uint64 endindex = ((etiss::uint64)((etiss::int64)-1)))
Definition at line 582 of file Translation.cpp.
References blockmap_, etiss::BlockLink::branch, etiss::BlockLink::decrRef(), etiss::BlockLink::end, etiss::BlockLink::next, etiss::BlockLink::start, etiss::BlockLink::updateRef(), and etiss::BlockLink::valid.
Referenced by etiss_CPUCore_handleException(), and ~Translation().
unloadBlocks() [2/2]
void etiss::Translation::unloadBlocks (etiss::uint64 startindex = 0, etiss::uint64 endindex = ((etiss::uint64)((etiss::int64) -1)))
Member Data Documentation
arch_
etiss::CPUArch *const etiss::Translation::arch_ private
Definition at line 126 of file Translation.h.
Referenced by getBlock(), init(), and translateBlock().
archptr_
std::shared_ptr< etiss::CPUArch > & etiss::Translation::archptr_ private
Definition at line 124 of file Translation.h.
blockmap_
std::unordered_map< etiss::uint64, std::list< BlockLink * > > etiss::Translation::blockmap_ private
Definition at line 150 of file Translation.h.
Referenced by getBlock(), and unloadBlocks().
cpu_
ETISS_CPU & etiss::Translation::cpu_ private
Definition at line 130 of file Translation.h.
Referenced by disasm(), getBlock(), and translateBlock().
id
const uint64_t etiss::Translation::id private
unique id used to generate unique function names across translation instances
Definition at line 218 of file Translation.h.
jit_
etiss::JIT *const etiss::Translation::jit_ private
Definition at line 127 of file Translation.h.
Referenced by getBlock(), and init().
jitptr_
std::shared_ptr< etiss::JIT > & etiss::Translation::jitptr_ private
Definition at line 125 of file Translation.h.
mis_
etiss::instr::ModedInstructionSet * etiss::Translation::mis_ private
Definition at line 148 of file Translation.h.
Referenced by disasm(), init(), translateBlock(), and ~Translation().
plugins_
std::list< std::shared_ptr< etiss::Plugin > > & etiss::Translation::plugins_ private
Definition at line 128 of file Translation.h.
Referenced by init().
plugins_array_
etiss::TranslationPlugin ** etiss::Translation::plugins_array_ private
Definition at line 131 of file Translation.h.
Referenced by getBlock(), init(), and ~Translation().
plugins_array_size_
size_t etiss::Translation::plugins_array_size_ private
Definition at line 133 of file Translation.h.
Referenced by init().
plugins_finalizeCodeBlock_
void(* etiss::Translation::plugins_finalizeCodeBlock_)(etiss::TranslationPlugin **, CodeBlock &) private
Function pointer, the function is getting defined in Translation::init via template function etiss::call_finalizeCodeBlock It calls the TranslationPlugin::finalizeCodeBlock functions of all translation plugins.
Definition at line 146 of file Translation.h.
Referenced by getBlock(), and init().
plugins_handle_array_
void ** etiss::Translation::plugins_handle_array_ private
Definition at line 132 of file Translation.h.
Referenced by init(), and ~Translation().
plugins_initCodeBlock_
void(* etiss::Translation::plugins_initCodeBlock_)(etiss::TranslationPlugin **, CodeBlock &) private
Function pointer, the function is getting defined in Translation::init via template function etiss::call_initCodeBlock It calls the TranslationPlugin::initCodeBlock functions of all translation plugins.
Definition at line 140 of file Translation.h.
Referenced by getBlock(), and init().
system_
ETISS_System & etiss::Translation::system_ private
Definition at line 129 of file Translation.h.
Referenced by translateBlock().
tblockcount
uint64_t etiss::Translation::tblockcount private
countes translated blocks. needed to guarantee unique block function names
Definition at line 220 of file Translation.h.
Referenced by getBlock(), and Translation().
The documentation for this class was generated from the following files:
include/etiss/Translation.h
/home/runner/work/etiss/etiss/src/Translation.cpp