ETISS 0.8.0: etiss::mm::MMU Class Reference
etiss::mm::MMU Class Reference abstract
#include <MMU.h>
Public Member Functions
MMU (bool hw_ptw, std::string name, bool pid_enabled)
MMU ctor.
virtual ~MMU ()
virtual int32_t Translate (const uint64_t vma, uint64_t *const pma_buf, MM_ACCESS access, uint64_t data=0)
Conduct the actual translation according to the format set by PTEFormatBuilder.
void SignalMMU (uint64_t control_reg_val_)
Whenever the MMU control register changes, the MMU has to be notified with the updated control register value.
void Dump ()
Dump the details of the MMU, when page fault cannot be handled.
void Init (ETISS_CPU *cpu, ETISS_System *system)
Initialize the MMU, when DMMUWrapper is wrapping the MMU.
void AddTLBEntryMap (uint64_t phy_addr_, PTE &pte)
Keep a record of mapping between cached PTE with its physical address.
virtual bool CheckPrivilegedMode ()=0
MMU is enabled in certain mode.
virtual int32_t CheckProtection (const PTE &, MM_ACCESS access)=0
Memory protection is architecture-dependent, which should be implemented with architecture model.
virtual int32_t WalkPageTable (uint64_t, MM_ACCESS)
Page table walking is required to translate virtual address to physical address if TLB miss occurs.
virtual void UpdatePTEFlags (PTE &, MM_ACCESS)
Reserved for some MMU that might update PTE when translating.
bool IsTLBFull () const
PTE EvictTLBEntry (const uint64_t vfn)
bool HasPageTableWalker ()
bool IsProcessIdEnabled ()
void UpdatePid (uint32_t new_pid)
uint64_t GetMMUControlReg ()
int32_t AddTLBEntry (const uint64_t vfn, const PTE &pte)
std::string GetName () const
virtual int32_t GetPid (uint64_t control_reg_val_)
MMU (bool hw_ptw, std::string name, bool pid_enabled)
MMU ctor.
virtual ~MMU ()
virtual int32_t Translate (const uint64_t vma, uint64_t *const pma_buf, MM_ACCESS access, uint64_t data=0)
Conduct the actual translation according to the format set by PTEFormatBuilder.
void SignalMMU (uint64_t control_reg_val_)
Whenever the MMU control register changes, the MMU has to be notified with the updated control register value.
void Dump ()
Dump the details of the MMU, when page fault cannot be handled.
void Init (ETISS_CPU *cpu, ETISS_System *system)
Initialize the MMU, when DMMUWrapper is wrapping the MMU.
void AddTLBEntryMap (uint64_t phy_addr_, PTE &pte)
Keep a record of mapping between cached PTE with its physical address.
virtual bool CheckPrivilegedMode ()=0
MMU is enabled in certain mode.
virtual int32_t CheckProtection (const PTE &, MM_ACCESS access)=0
Memory protection is architecture-dependent, which should be implemented with architecture model.
virtual int32_t WalkPageTable (uint64_t, MM_ACCESS)
Page table walking is required to translate virtual address to physical address if TLB miss occurs.
virtual void UpdatePTEFlags (PTE &, MM_ACCESS)
Reserved for some MMU that might update PTE when translating.
bool IsTLBFull () const
PTE EvictTLBEntry (const uint64_t vfn)
bool HasPageTableWalker ()
bool IsProcessIdEnabled ()
void UpdatePid (uint32_t new_pid)
uint64_t GetMMUControlReg ()
int32_t AddTLBEntry (const uint64_t vfn, const PTE &pte)
std::string GetName () const
virtual int32_t GetPid (uint64_t control_reg_val_)
Public Attributes
bool cache_flush_pending
Protected Attributes
ETISS_CPU * cpu_
ETISS_System * system_
bool mmu_enabled_
Private Attributes
std::shared_ptr< etiss::mm::TLB< 0 > > tlb_
std::map< uint64_t, PTE * > tlb_entry_map_
uint64_t mmu_control_reg_val_
uint32_t pid_
std::string name_
const bool pid_enabled_
const bool hw_page_table_walker_
Detailed Description
Definition at line 75 of file MMU.h.
Constructor & Destructor Documentation
MMU() [1/2]
etiss::mm::MMU::MMU (bool hw_ptw, std::string name, bool pid_enabled) explicit
MMU ctor.
It is needed to explicitly declared whether the MMU has a hardware page table walker, or support process identifier
Definition at line 68 of file MMU.cpp.
References REGISTER_PAGE_FAULT_HANDLER, tlb_, etiss::mm::tlb_miss_handler(), and etiss::mm::TLBMISS.
~MMU() [1/2]
virtual etiss::mm::MMU::~MMU () inline virtual
Definition at line 89 of file MMU.h.
MMU() [2/2]
etiss::mm::MMU::MMU (bool hw_ptw, std::string name, bool pid_enabled) explicit
MMU ctor.
It is needed to explicitly declared whether the MMU has a hardware page table walker, or support process identifier
~MMU() [2/2]
virtual etiss::mm::MMU::~MMU () inline virtual
Definition at line 89 of file MMU.h.
Member Function Documentation
AddTLBEntry() [1/2]
int32_t etiss::mm::MMU::AddTLBEntry (const uint64_t vfn, const PTE & pte)
Definition at line 154 of file MMU.cpp.
References HANDLE_PAGE_FAULT, etiss::mm::NOERROR, etiss::mm::R_ACCESS, and tlb_.
Referenced by RISCV64MMU::WalkPageTable().
AddTLBEntry() [2/2]
int32_t etiss::mm::MMU::AddTLBEntry (const uint64_t vfn, const PTE & pte)
AddTLBEntryMap() [1/2]
void etiss::mm::MMU::AddTLBEntryMap (uint64_t phy_addr_, PTE & pte)
Keep a record of mapping between cached PTE with its physical address.
Definition at line 214 of file MMU.cpp.
References HANDLE_PAGE_FAULT, etiss::mm::PTEOVERLAP, etiss::mm::R_ACCESS, and tlb_entry_map_.
Referenced by RISCV64MMU::WalkPageTable().
AddTLBEntryMap() [2/2]
void etiss::mm::MMU::AddTLBEntryMap (uint64_t phy_addr_, PTE & pte)
Keep a record of mapping between cached PTE with its physical address.
CheckPrivilegedMode() [1/2]
virtual bool etiss::mm::MMU::CheckPrivilegedMode () pure virtual
MMU is enabled in certain mode.
Thus the privilege mode check should be implemented in architectural part
Implemented in RISCV64MMU.
Referenced by Translate().
CheckPrivilegedMode() [2/2]
virtual bool etiss::mm::MMU::CheckPrivilegedMode () pure virtual
MMU is enabled in certain mode.
Thus the privilege mode check should be implemented in architectural part
Implemented in RISCV64MMU.
CheckProtection() [1/2]
virtual int32_t etiss::mm::MMU::CheckProtection (const PTE & , MM_ACCESS access) pure virtual
Memory protection is architecture-dependent, which should be implemented with architecture model.
Implemented in RISCV64MMU.
CheckProtection() [2/2]
virtual int32_t etiss::mm::MMU::CheckProtection (const PTE & , MM_ACCESS access) pure virtual
Memory protection is architecture-dependent, which should be implemented with architecture model.
Implemented in RISCV64MMU.
Referenced by Translate().
Dump() [1/2]
void etiss::mm::MMU::Dump ()
Dump the details of the MMU, when page fault cannot be handled.
Definition at line 189 of file MMU.cpp.
References mmu_control_reg_val_, mmu_enabled_, name_, pid_, pid_enabled_, and tlb_.
Referenced by etiss::mm::DUMP_MMU(), and Translate().
Dump() [2/2]
void etiss::mm::MMU::Dump ()
Dump the details of the MMU, when page fault cannot be handled.
EvictTLBEntry() [1/2]
PTE etiss::mm::MMU::EvictTLBEntry (const uint64_t vfn) inline
Definition at line 157 of file MMU.h.
References tlb_.
EvictTLBEntry() [2/2]
PTE etiss::mm::MMU::EvictTLBEntry (const uint64_t vfn) inline
Definition at line 157 of file MMU.h.
References tlb_.
GetMMUControlReg() [1/2]
uint64_t etiss::mm::MMU::GetMMUControlReg () inline
Definition at line 169 of file MMU.h.
References mmu_control_reg_val_.
GetMMUControlReg() [2/2]
uint64_t etiss::mm::MMU::GetMMUControlReg () inline
Definition at line 169 of file MMU.h.
References mmu_control_reg_val_.
Referenced by RISCV64MMU::WalkPageTable().
GetName() [1/2]
std::string etiss::mm::MMU::GetName () const inline
Definition at line 173 of file MMU.h.
References name_.
Referenced by SignalMMU(), and RISCV64MMU::WalkPageTable().
GetName() [2/2]
std::string etiss::mm::MMU::GetName () const inline
Definition at line 173 of file MMU.h.
References name_.
GetPid() [1/2]
virtual int32_t etiss::mm::MMU::GetPid (uint64_t control_reg_val_) inline virtual
Definition at line 175 of file MMU.h.
Referenced by SignalMMU().
GetPid() [2/2]
virtual int32_t etiss::mm::MMU::GetPid (uint64_t control_reg_val_) inline virtual
Definition at line 175 of file MMU.h.
HasPageTableWalker() [1/2]
bool etiss::mm::MMU::HasPageTableWalker () inline
Definition at line 159 of file MMU.h.
References hw_page_table_walker_.
Referenced by etiss::mm::tlb_miss_handler().
HasPageTableWalker() [2/2]
bool etiss::mm::MMU::HasPageTableWalker () inline
Definition at line 159 of file MMU.h.
References hw_page_table_walker_.
Init() [1/2]
void etiss::mm::MMU::Init (ETISS_CPU * cpu, ETISS_System * system)
Initialize the MMU, when DMMUWrapper is wrapping the MMU.
See also
etiss::mm::DMMUWrapper
Init() [2/2]
void etiss::mm::MMU::Init (ETISS_CPU * cpu, ETISS_System * system)
Initialize the MMU, when DMMUWrapper is wrapping the MMU.
See also
etiss::mm::DMMUWrapper
Definition at line 204 of file MMU.cpp.
References cpu_, DEFAULT_PAGE_TABLE_WALKER, etiss::FATALERROR, hw_page_table_walker_, etiss::log(), etiss::mm::R_ACCESS, system_, and WalkPageTable().
IsProcessIdEnabled() [1/2]
bool etiss::mm::MMU::IsProcessIdEnabled () inline
Definition at line 161 of file MMU.h.
References pid_enabled_.
IsProcessIdEnabled() [2/2]
bool etiss::mm::MMU::IsProcessIdEnabled () inline
Definition at line 161 of file MMU.h.
References pid_enabled_.
IsTLBFull() [1/2]
bool etiss::mm::MMU::IsTLBFull () const inline
Definition at line 155 of file MMU.h.
References tlb_.
IsTLBFull() [2/2]
bool etiss::mm::MMU::IsTLBFull () const inline
Definition at line 155 of file MMU.h.
References tlb_.
SignalMMU() [1/2]
void etiss::mm::MMU::SignalMMU (uint64_t control_reg_val_)
Whenever the MMU control register changes, the MMU has to be notified with the updated control register value.
SignalMMU() [2/2]
void etiss::mm::MMU::SignalMMU (uint64_t control_reg_val_)
Whenever the MMU control register changes, the MMU has to be notified with the updated control register value.
Definition at line 166 of file MMU.cpp.
References cache_flush_pending, GetName(), GetPid(), etiss::log(), mmu_control_reg_val_, mmu_enabled_, pid_enabled_, tlb_, tlb_entry_map_, UpdatePid(), etiss::VERBOSE, and etiss::WARNING.
Translate() [1/2]
int32_t etiss::mm::MMU::Translate (const uint64_t vma, uint64_t *const pma_buf, MM_ACCESS access, uint64_t data = 0) virtual
Conduct the actual translation according to the format set by PTEFormatBuilder.
See also
etiss::mm::PTEFormatBuilder and etiss::mm::PTEFormat
Definition at line 82 of file MMU.cpp.
References CheckPrivilegedMode(), CheckProtection(), Dump(), etiss::FATALERROR, etiss::mm::PTEFormat::GetFormatMap(), etiss::mm::PTE::GetPPN(), HANDLE_PAGE_FAULT, etiss::mm::PTEFormat::Instance(), etiss::log(), mmu_enabled_, etiss::mm::NOERROR, pid_, pid_enabled_, tlb_, tlb_entry_map_, UpdatePTEFlags(), and etiss::mm::W_ACCESS.
Referenced by etiss::mm::dbg_read(), etiss::mm::dbg_write(), etiss::mm::dread(), etiss::mm::dwrite(), etiss::mm::iread(), and etiss::mm::iwrite().
Translate() [2/2]
virtual int32_t etiss::mm::MMU::Translate (const uint64_t vma, uint64_t *const pma_buf, MM_ACCESS access, uint64_t data = 0) virtual
Conduct the actual translation according to the format set by PTEFormatBuilder.
See also
etiss::mm::PTEFormatBuilder and etiss::mm::PTEFormat
UpdatePid() [1/2]
void etiss::mm::MMU::UpdatePid (uint32_t new_pid) inline
Definition at line 163 of file MMU.h.
References pid_, and pid_enabled_.
UpdatePid() [2/2]
void etiss::mm::MMU::UpdatePid (uint32_t new_pid) inline
Definition at line 163 of file MMU.h.
References pid_, and pid_enabled_.
Referenced by SignalMMU().
UpdatePTEFlags() [1/2]
virtual void etiss::mm::MMU::UpdatePTEFlags (PTE & , MM_ACCESS) inline virtual
Reserved for some MMU that might update PTE when translating.
Reimplemented in RISCV64MMU.
Definition at line 153 of file MMU.h.
UpdatePTEFlags() [2/2]
virtual void etiss::mm::MMU::UpdatePTEFlags (PTE & , MM_ACCESS) inline virtual
Reserved for some MMU that might update PTE when translating.
Reimplemented in RISCV64MMU.
Definition at line 153 of file MMU.h.
Referenced by Translate().
WalkPageTable() [1/2]
virtual int32_t etiss::mm::MMU::WalkPageTable (uint64_t , MM_ACCESS) inline virtual
Page table walking is required to translate virtual address to physical address if TLB miss occurs.
Reimplemented in RISCV64MMU.
Definition at line 147 of file MMU.h.
References DEFAULT_PAGE_TABLE_WALKER.
WalkPageTable() [2/2]
virtual int32_t etiss::mm::MMU::WalkPageTable (uint64_t , MM_ACCESS) inline virtual
Page table walking is required to translate virtual address to physical address if TLB miss occurs.
Reimplemented in RISCV64MMU.
Definition at line 147 of file MMU.h.
References DEFAULT_PAGE_TABLE_WALKER.
Referenced by Init(), and etiss::mm::tlb_miss_handler().
Member Data Documentation
cache_flush_pending
bool etiss::mm::MMU::cache_flush_pending
Definition at line 177 of file MMU.h.
Referenced by SignalMMU().
cpu_
ETISS_CPU * etiss::mm::MMU::cpu_ protected
Definition at line 180 of file MMU.h.
Referenced by Init(), and RISCV64MMU::WalkPageTable().
hw_page_table_walker_
const bool etiss::mm::MMU::hw_page_table_walker_ private
Definition at line 198 of file MMU.h.
Referenced by HasPageTableWalker(), and Init().
mmu_control_reg_val_
uint64_t etiss::mm::MMU::mmu_control_reg_val_ private
Definition at line 193 of file MMU.h.
Referenced by Dump(), GetMMUControlReg(), and SignalMMU().
mmu_enabled_
bool etiss::mm::MMU::mmu_enabled_ protected
Definition at line 182 of file MMU.h.
Referenced by Dump(), SignalMMU(), Translate(), and RISCV64MMU::WalkPageTable().
name_
std::string etiss::mm::MMU::name_ private
Definition at line 195 of file MMU.h.
Referenced by Dump(), and GetName().
pid_
uint32_t etiss::mm::MMU::pid_ private
Definition at line 194 of file MMU.h.
Referenced by Dump(), Translate(), and UpdatePid().
pid_enabled_
const bool etiss::mm::MMU::pid_enabled_ private
Definition at line 197 of file MMU.h.
Referenced by Dump(), IsProcessIdEnabled(), SignalMMU(), Translate(), and UpdatePid().
system_
ETISS_System * etiss::mm::MMU::system_ protected
Definition at line 181 of file MMU.h.
Referenced by Init(), and RISCV64MMU::WalkPageTable().
tlb_
std::shared_ptr< etiss::mm::TLB< 0 > > etiss::mm::MMU::tlb_ private
Definition at line 186 of file MMU.h.
Referenced by AddTLBEntry(), Dump(), EvictTLBEntry(), IsTLBFull(), MMU(), SignalMMU(), and Translate().
tlb_entry_map_
std::map< uint64_t, PTE * > etiss::mm::MMU::tlb_entry_map_ private
Definition at line 191 of file MMU.h.
Referenced by AddTLBEntryMap(), SignalMMU(), and Translate().
The documentation for this class was generated from the following files:
include/etiss/mm/MMU.h
/home/runner/work/etiss/etiss/src/mm/MMU.cpp