ETISS 0.8.0: etiss::fault::Injector Class Reference
etiss::fault::Injector Class Reference abstract
#include <Injector.h>
Public Types
typedef Injector * ptr
typedef Injector * ptr
Public Member Functions
Injector ()
virtual ~Injector ()
virtual std::list< std::string > listFields ()=0
list all fields directly reachable by this injector
virtual std::list< std::string > listSubInjectors ()=0
list all sub injectors.
virtual ptr getSubInjector (const std::string &name)=0
get a sub injector.
virtual ptr getParentInjector ()=0
get a the parent injector (root returns 0).
virtual bool needsCallbacks ()
virtual bool cycleAccurateCallback (uint64_t time_ps)
virtual bool instructionAccurateCallback (uint64_t time_ps)
virtual void * fastFieldAccessPtr (const std::string &name, std::string &errormsg)=0
virtual void freeFastFieldAccessPtr (void *)
MUST be called to cleanup a pointer acquired with fastFieldAccessPtr() default implementation is nop.
virtual bool readField (void *fastfieldaccessptr, uint64_t &val, std::string &errormsg)=0
read the value of a field
virtual bool applyAction (const etiss::fault::Fault &fault, const etiss::fault::Action &action, std::string &errormsg)=0
virtual bool acceleratedTrigger (const etiss::fault::Trigger &, int32_t fault_id)
virtual std::string getInjectorPath ()
returns the path of the current object.
void addTrigger (const Trigger &t, int32_t fault_id)
> Triggers to look at in callbacks
Injector ()
virtual ~Injector ()
virtual std::list< std::string > listFields ()=0
list all fields directly reachable by this injector
virtual std::list< std::string > listSubInjectors ()=0
list all sub injectors.
virtual ptr getSubInjector (const std::string &name)=0
get a sub injector.
virtual ptr getParentInjector ()=0
get a the parent injector (root returns 0).
virtual bool needsCallbacks ()
virtual bool cycleAccurateCallback (uint64_t time_ps)
virtual bool instructionAccurateCallback (uint64_t time_ps)
virtual void * fastFieldAccessPtr (const std::string &name, std::string &errormsg)=0
virtual void freeFastFieldAccessPtr (void *)
MUST be called to cleanup a pointer acquired with fastFieldAccessPtr() default implementation is nop.
virtual bool readField (void *fastfieldaccessptr, uint64_t &val, std::string &errormsg)=0
read the value of a field
virtual bool applyAction (const etiss::fault::Fault &fault, const etiss::fault::Action &action, std::string &errormsg)=0
virtual bool acceleratedTrigger (const etiss::fault::Trigger &, int32_t fault_id)
virtual std::string getInjectorPath ()
returns the path of the current object.
void addTrigger (const Trigger &t, int32_t fault_id)
> Triggers to look at in callbacks
Static Public Member Functions
static ptr get (const std::string &injectorPath)
static ptr get (const std::string &injectorPath)
Private Attributes
volatile bool has_pending_triggers
std::list< std::pair< Trigger, int32_t > > pending_triggers
std::list< std::pair< Trigger, int32_t > > unknown_triggers
> Triggers which were just added
Detailed Description
Definition at line 77 of file Injector.h.
Member Typedef Documentation
ptr [1/2]
typedef Injector* etiss::fault::Injector::ptr
Definition at line 83 of file Injector.h.
ptr [2/2]
typedef Injector* etiss::fault::Injector::ptr
Definition at line 83 of file Injector.h.
Constructor & Destructor Documentation
Injector() [1/2]
etiss::fault::Injector::Injector ()
Definition at line 61 of file Injector.cpp.
References has_pending_triggers, etiss::log(), and etiss::VERBOSE.
~Injector() [1/2]
virtual etiss::fault::Injector::~Injector () inline virtual
Definition at line 88 of file Injector.h.
Injector() [2/2]
etiss::fault::Injector::Injector ()
~Injector() [2/2]
virtual etiss::fault::Injector::~Injector () inline virtual
Definition at line 88 of file Injector.h.
Member Function Documentation
acceleratedTrigger() [1/2]
bool etiss::fault::Injector::acceleratedTrigger (const etiss::fault::Trigger & t, int32_t fault_id) virtual
Reimplemented in etiss::VirtualStruct, and etiss::VirtualStruct.
Definition at line 225 of file Injector.cpp.
References etiss::log(), etiss::fault::Trigger::toString(), and etiss::VERBOSE.
Referenced by addTrigger().
acceleratedTrigger() [2/2]
virtual bool etiss::fault::Injector::acceleratedTrigger (const etiss::fault::Trigger & , int32_t fault_id) virtual
Reimplemented in etiss::VirtualStruct, and etiss::VirtualStruct.
addTrigger() [1/2]
void etiss::fault::Injector::addTrigger (const Trigger & t, int32_t fault_id)
> Triggers to look at in callbacks
TODO specialized lists. e.g. time triggers should be sorted and only the earliest time should be checked
Definition at line 204 of file Injector.cpp.
References acceleratedTrigger(), has_pending_triggers, etiss::log(), pending_triggers, etiss::fault::Trigger::toString(), and etiss::VERBOSE.
Referenced by etiss::fault::Stressor::addFault().
addTrigger() [2/2]
void etiss::fault::Injector::addTrigger (const Trigger & t, int32_t fault_id)
> Triggers to look at in callbacks
TODO specialized lists. e.g. time triggers should be sorted and only the earliest time should be checked
applyAction() [1/2]
virtual bool etiss::fault::Injector::applyAction (const etiss::fault::Fault & fault, const etiss::fault::Action & action, std::string & errormsg) pure virtual
Returns
true if action could be applied
Attention
MUST NOT be called from without the callback functions cycleAccurateCallback() and instructionAccurateCallback(). The assumption of a singlethreaded access/use of these functions MUST hold.
Implemented in etiss::VirtualStruct, and etiss::VirtualStruct.
applyAction() [2/2]
virtual bool etiss::fault::Injector::applyAction (const etiss::fault::Fault & fault, const etiss::fault::Action & action, std::string & errormsg) pure virtual
Returns
true if action could be applied
Attention
MUST NOT be called from without the callback functions cycleAccurateCallback() and instructionAccurateCallback(). The assumption of a singlethreaded access/use of these functions MUST hold.
Implemented in etiss::VirtualStruct, and etiss::VirtualStruct.
cycleAccurateCallback() [1/2]
bool etiss::fault::Injector::cycleAccurateCallback (uint64_t time_ps) virtual
Definition at line 79 of file Injector.cpp.
References etiss::fault::Stressor::firedTrigger(), has_pending_triggers, etiss::log(), pending_triggers, unknown_triggers, and etiss::VERBOSE.
Referenced by instructionAccurateCallback().
cycleAccurateCallback() [2/2]
virtual bool etiss::fault::Injector::cycleAccurateCallback (uint64_t time_ps) virtual
fastFieldAccessPtr() [1/2]
virtual void* etiss::fault::Injector::fastFieldAccessPtr (const std::string & name, std::string & errormsg) pure virtual
Attention
MUST NOT be called from without the callback functions cycleAccurateCallback() and instructionAccurateCallback(). The assumption of a singlethreaded access/use of these functions MUST hold.
Returns
0 in case of failure. otherwise an internal pointer shall be retuned that allows to access a field in a quick manner. freefastFieldAccessPtr MUST be called after use.
Implemented in etiss::VirtualStruct, and etiss::VirtualStruct.
Referenced by etiss::fault::Trigger::fired().
fastFieldAccessPtr() [2/2]
virtual void* etiss::fault::Injector::fastFieldAccessPtr (const std::string & name, std::string & errormsg) pure virtual
Attention
MUST NOT be called from without the callback functions cycleAccurateCallback() and instructionAccurateCallback(). The assumption of a singlethreaded access/use of these functions MUST hold.
Returns
0 in case of failure. otherwise an internal pointer shall be retuned that allows to access a field in a quick manner. freefastFieldAccessPtr MUST be called after use.
Implemented in etiss::VirtualStruct, and etiss::VirtualStruct.
freeFastFieldAccessPtr() [1/2]
void etiss::fault::Injector::freeFastFieldAccessPtr (void *) virtual
MUST be called to cleanup a pointer acquired with fastFieldAccessPtr() default implementation is nop.
Attention
MUST NOT be called from outside the callback functions cycleAccurateCallback() and instructionAccurateCallback(). The assumption of a singlethreaded access/use of these functions MUST hold.
Definition at line 67 of file Injector.cpp.
References etiss::INFO, etiss::log(), and etiss::VERBOSE.
freeFastFieldAccessPtr() [2/2]
virtual void etiss::fault::Injector::freeFastFieldAccessPtr (void *) virtual
MUST be called to cleanup a pointer acquired with fastFieldAccessPtr() default implementation is nop.
Attention
MUST NOT be called from outside the callback functions cycleAccurateCallback() and instructionAccurateCallback(). The assumption of a singlethreaded access/use of these functions MUST hold.
get() [1/2]
std::shared_ptr< etiss::fault::Injector > etiss::fault::Injector::get (const std::string & injectorPath) static
Parameters
injectorPath the full path/name to/off an injector. in case of using ETISS/VirtualStruct please have a look at the doc of etiss::VirtualStruct for examples of the path syntax
Attention
this function needs to be implemented in case of not using ETISS/VirtualStruct
Definition at line 655 of file VirtualStruct.cpp.
References etiss::VirtualStruct::root().
Referenced by etiss::fault::InjectorAddress::getInjector().
get() [2/2]
static ptr etiss::fault::Injector::get (const std::string & injectorPath) static
Parameters
injectorPath the full path/name to/off an injector. in case of using ETISS/VirtualStruct please have a look at the doc of etiss::VirtualStruct for examples of the path syntax
Attention
this function needs to be implemented in case of not using ETISS/VirtualStruct
getInjectorPath() [1/2]
std::string etiss::fault::Injector::getInjectorPath () virtual
returns the path of the current object.
by default the path will consists of the injector names from getSubInjectors() seperated by "::" (see etiss::VirtualStruct). override this function to match other/custom syntax
Definition at line 142 of file Injector.cpp.
References etiss::ERROR, ETISS_SRCLOC, getParentInjector(), getSubInjector(), listSubInjectors(), etiss::log(), and name.
Referenced by etiss::VirtualStruct::applyAction().
getInjectorPath() [2/2]
virtual std::string etiss::fault::Injector::getInjectorPath () virtual
returns the path of the current object.
by default the path will consists of the injector names from getSubInjectors() seperated by "::" (see etiss::VirtualStruct). override this function to match other/custom syntax
getParentInjector() [1/2]
virtual ptr etiss::fault::Injector::getParentInjector () pure virtual
get a the parent injector (root returns 0).
in case of c++11 this function returns a smart pointer (std::shared_ptr<Injector>)
See also
etiss::VirtualStruct for example implemention
Implemented in etiss::VirtualStruct, and etiss::VirtualStruct.
getParentInjector() [2/2]
virtual ptr etiss::fault::Injector::getParentInjector () pure virtual
get a the parent injector (root returns 0).
in case of c++11 this function returns a smart pointer (std::shared_ptr<Injector>)
See also
etiss::VirtualStruct for example implemention
Implemented in etiss::VirtualStruct, and etiss::VirtualStruct.
Referenced by getInjectorPath().
getSubInjector() [1/2]
virtual ptr etiss::fault::Injector::getSubInjector (const std::string & name) pure virtual
get a sub injector.
in case of c++11 this function returns a smart pointer (std::shared_ptr<Injector>)
See also
etiss::VirtualStruct for example implemention
Implemented in etiss::VirtualStruct, and etiss::VirtualStruct.
getSubInjector() [2/2]
virtual ptr etiss::fault::Injector::getSubInjector (const std::string & name) pure virtual
get a sub injector.
in case of c++11 this function returns a smart pointer (std::shared_ptr<Injector>)
See also
etiss::VirtualStruct for example implemention
Implemented in etiss::VirtualStruct, and etiss::VirtualStruct.
Referenced by getInjectorPath().
instructionAccurateCallback() [1/2]
virtual bool etiss::fault::Injector::instructionAccurateCallback (uint64_t time_ps) virtual
instructionAccurateCallback() [2/2]
bool etiss::fault::Injector::instructionAccurateCallback (uint64_t time_ps) virtual
todo
Definition at line 123 of file Injector.cpp.
References cycleAccurateCallback(), etiss::log(), and etiss::VERBOSE.
listFields() [1/2]
virtual std::list<std::string> etiss::fault::Injector::listFields () pure virtual
list all fields directly reachable by this injector
See also
etiss::VirtualStruct for example implemention
Implemented in etiss::VirtualStruct, and etiss::VirtualStruct.
listFields() [2/2]
virtual std::list<std::string> etiss::fault::Injector::listFields () pure virtual
list all fields directly reachable by this injector
See also
etiss::VirtualStruct for example implemention
Implemented in etiss::VirtualStruct, and etiss::VirtualStruct.
listSubInjectors() [1/2]
virtual std::list<std::string> etiss::fault::Injector::listSubInjectors () pure virtual
list all sub injectors.
See also
etiss::VirtualStruct for example implemention
Implemented in etiss::VirtualStruct, and etiss::VirtualStruct.
listSubInjectors() [2/2]
virtual std::list<std::string> etiss::fault::Injector::listSubInjectors () pure virtual
list all sub injectors.
See also
etiss::VirtualStruct for example implemention
Implemented in etiss::VirtualStruct, and etiss::VirtualStruct.
Referenced by getInjectorPath().
needsCallbacks() [1/2]
bool etiss::fault::Injector::needsCallbacks () virtual
Definition at line 73 of file Injector.cpp.
References has_pending_triggers, etiss::log(), and etiss::VERBOSE.
needsCallbacks() [2/2]
virtual bool etiss::fault::Injector::needsCallbacks () virtual
readField() [1/2]
virtual bool etiss::fault::Injector::readField (void * fastfieldaccessptr, uint64_t & val, std::string & errormsg) pure virtual
read the value of a field
Returns
true if read succeded
Attention
MUST NOT be called from outside the callback functions cycleAccurateCallback() and instructionAccurateCallback(). The assumption of a singlethreaded access/use of these functions MUST hold.
Implemented in etiss::VirtualStruct, and etiss::VirtualStruct.
readField() [2/2]
virtual bool etiss::fault::Injector::readField (void * fastfieldaccessptr, uint64_t & val, std::string & errormsg) pure virtual
read the value of a field
Returns
true if read succeded
Attention
MUST NOT be called from outside the callback functions cycleAccurateCallback() and instructionAccurateCallback(). The assumption of a singlethreaded access/use of these functions MUST hold.
Implemented in etiss::VirtualStruct, and etiss::VirtualStruct.
Member Data Documentation
has_pending_triggers
volatile bool etiss::fault::Injector::has_pending_triggers private
Definition at line 178 of file Injector.h.
Referenced by addTrigger(), cycleAccurateCallback(), Injector(), and needsCallbacks().
pending_triggers
std::list< std::pair< Trigger, int32_t > > etiss::fault::Injector::pending_triggers private
Definition at line 179 of file Injector.h.
Referenced by addTrigger(), and cycleAccurateCallback().
unknown_triggers
std::list< std::pair< Trigger, int32_t > > etiss::fault::Injector::unknown_triggers private
> Triggers which were just added
Definition at line 180 of file Injector.h.
Referenced by cycleAccurateCallback().
The documentation for this class was generated from the following files:
include/etiss/fault/Injector.h
/home/runner/work/etiss/etiss/src/fault/Injector.cpp
/home/runner/work/etiss/etiss/src/VirtualStruct.cpp