ETISS 0.8.0: etiss::instr::VariableInstructionSet Class Reference
etiss::instr::VariableInstructionSet Class Reference
holds etiss::instr::InstructionSet instances with different bit widths.
#include <Instruction.h>
Public Member Functions
etiss_del_como (VariableInstructionSet) VariableInstructionSet(ModedInstructionSet &
~VariableInstructionSet ()
bool compile ()
InstructionSet * get (unsigned width)
InstructionSet * create (unsigned width, const std::string &name=std::string())
InstructionSet & open (unsigned width, const std::string &name=std::string())
InstructionSet * getMain ()
InstructionSet * createMain (const std::string &name=std::string())
InstructionSet & openMain (const std::string &name=std::string())
template<typename T >
Instruction & open (unsigned bits, T code, T mask, const char *name)
void foreach (std::function< void(InstructionSet &)> func)
std::string print (std::string prefix=std::string())
etiss_del_como (VariableInstructionSet) VariableInstructionSet(ModedInstructionSet &
~VariableInstructionSet ()
bool compile ()
InstructionSet * get (unsigned width)
InstructionSet * create (unsigned width, const std::string &name=std::string())
InstructionSet & open (unsigned width, const std::string &name=std::string())
InstructionSet * getMain ()
InstructionSet * createMain (const std::string &name=std::string())
InstructionSet & openMain (const std::string &name=std::string())
template<typename T >
Instruction & open (unsigned bits, T code, T mask, const char *name)
void foreach (std::function< void(InstructionSet &)> func)
std::string print (std::string prefix=std::string())
Public Attributes
ModedInstructionSet & parent_
unsigned width_
const std::string archname_
std::function< void(VariableInstructionSet &, InstructionContext &, BitArray &)> length_updater_
unsigned width
unsigned const std::string & archname
Private Attributes
std::map< unsigned, InstructionSet * > ismap_
Detailed Description
holds etiss::instr::InstructionSet instances with different bit widths.
    Location in an instruction translation tree:
    ModedInstructionSet
        ↳ VariableInstructionSet (e.g. for mode 0)
            ↳ InstructionSet (e.g. 32 bit)
                ↳ Node
                    ↳ ...                ↳ Node
                    ↳ ...                    ↳ ...
                        ↳ Instruction
            ↳ InstructionSet (e.g. 16 bit)
Definition at line 741 of file Instruction.h.
Constructor & Destructor Documentation
~VariableInstructionSet() [1/2]
etiss::instr::VariableInstructionSet::~VariableInstructionSet ()
Definition at line 1036 of file Instruction.cpp.
References ismap_.
~VariableInstructionSet() [2/2]
etiss::instr::VariableInstructionSet::~VariableInstructionSet ()
Member Function Documentation
compile() [1/2]
bool etiss::instr::VariableInstructionSet::compile ()
Definition at line 1045 of file Instruction.cpp.
References ismap_, etiss::log(), etiss::WARNING, and width_.
Referenced by etiss::instr::ModedInstructionSet::compile().
compile() [2/2]
bool etiss::instr::VariableInstructionSet::compile ()
create() [1/2]
InstructionSet * etiss::instr::VariableInstructionSet::create (unsigned width, const std::string & name = std::string())
Definition at line 1073 of file Instruction.cpp.
References ismap_, name, and width.
Referenced by createMain(), and open().
create() [2/2]
InstructionSet* etiss::instr::VariableInstructionSet::create (unsigned width, const std::string & name = std::string())
createMain() [1/2]
InstructionSet* etiss::instr::VariableInstructionSet::createMain (const std::string & name = std::string()) inline
Definition at line 763 of file Instruction.h.
References create(), and width_.
createMain() [2/2]
InstructionSet* etiss::instr::VariableInstructionSet::createMain (const std::string & name = std::string()) inline
Definition at line 763 of file Instruction.h.
References create(), and width_.
etiss_del_como() [1/2]
etiss::instr::VariableInstructionSet::etiss_del_como (VariableInstructionSet) &
etiss_del_como() [2/2]
etiss::instr::VariableInstructionSet::etiss_del_como (VariableInstructionSet) &
foreach() [1/2]
void etiss::instr::VariableInstructionSet::foreach (std::function< void(InstructionSet &)> func)
Definition at line 1092 of file Instruction.cpp.
References etiss::ERROR, etiss_log, and ismap_.
Referenced by etiss::plugin::InstructionAccurateCallback::finalizeInstrSet(), etiss::plugin::PrintInstruction::finalizeInstrSet(), etiss::plugin::VariableValueLogger::finalizeInstrSet(), etiss::plugin::InstructionSpecificAddressCallback::finalizeInstrSet(), etiss::plugin::gdb::Server::finalizeInstrSet(), etiss::CPUArch::finalizeInstrSet(), and etiss::DataSheetAccurateTiming::initInstrSet().
foreach() [2/2]
void etiss::instr::VariableInstructionSet::foreach (std::function< void(InstructionSet &)> func)
get() [1/2]
InstructionSet* etiss::instr::VariableInstructionSet::get (unsigned width)
get() [2/2]
InstructionSet * etiss::instr::VariableInstructionSet::get (unsigned width)
Definition at line 1066 of file Instruction.cpp.
References ismap_, and width.
Referenced by etiss::Translation::disasm(), getMain(), and open().
getMain() [1/2]
InstructionSet* etiss::instr::VariableInstructionSet::getMain () inline
Definition at line 762 of file Instruction.h.
References get(), and width_.
getMain() [2/2]
InstructionSet* etiss::instr::VariableInstructionSet::getMain () inline
Definition at line 762 of file Instruction.h.
References get(), and width_.
open() [1/4]
template<typename T > Instruction& etiss::instr::VariableInstructionSet::open (unsigned bits, T code, T mask, const char * name) inline
Definition at line 767 of file Instruction.h.
References etiss::ERROR, etiss_log, name, etiss::instr::InstructionSet::open(), and open().
open() [2/4]
template<typename T > Instruction& etiss::instr::VariableInstructionSet::open (unsigned bits, T code, T mask, const char * name) inline
Definition at line 767 of file Instruction.h.
References etiss::ERROR, etiss_log, name, etiss::instr::InstructionSet::open(), and open().
open() [3/4]
InstructionSet& etiss::instr::VariableInstructionSet::open (unsigned width, const std::string & name = std::string())
open() [4/4]
InstructionSet & etiss::instr::VariableInstructionSet::open (unsigned width, const std::string & name = std::string())
Definition at line 1082 of file Instruction.cpp.
References create(), get(), name, and width.
Referenced by etiss::instr::InstructionClass::addTo(), open(), etiss::instr::ModedInstructionSet::open(), and openMain().
openMain() [1/2]
InstructionSet& etiss::instr::VariableInstructionSet::openMain (const std::string & name = std::string()) inline
Definition at line 764 of file Instruction.h.
References open(), and width_.
openMain() [2/2]
InstructionSet& etiss::instr::VariableInstructionSet::openMain (const std::string & name = std::string()) inline
Definition at line 764 of file Instruction.h.
References open(), and width_.
print() [1/2]
std::string etiss::instr::VariableInstructionSet::print (std::string prefix = std::string())
print() [2/2]
std::string etiss::instr::VariableInstructionSet::print (std::string prefix = std::string())
Definition at line 1107 of file Instruction.cpp.
References archname_, etiss::instr::InstructionSet::print(), and width_.
Referenced by etiss::instr::ModedInstructionSet::print().
Member Data Documentation
archname
unsigned const std::string & etiss::instr::VariableInstructionSet::archname
Definition at line 755 of file Instruction.h.
archname_
const std::string etiss::instr::VariableInstructionSet::archname_
Definition at line 749 of file Instruction.h.
Referenced by print().
ismap_
std::map< unsigned, InstructionSet * > etiss::instr::VariableInstructionSet::ismap_ private
Definition at line 744 of file Instruction.h.
Referenced by compile(), create(), foreach(), get(), and ~VariableInstructionSet().
length_updater_
std::function< void(VariableInstructionSet &, InstructionContext &, BitArray &)> etiss::instr::VariableInstructionSet::length_updater_
Definition at line 750 of file Instruction.h.
Referenced by RISCVArch::initInstrSet(), and RISCV64Arch::initInstrSet().
parent_
ModedInstructionSet & etiss::instr::VariableInstructionSet::parent_
Definition at line 747 of file Instruction.h.
Referenced by etiss::DataSheetAccurateTiming::initInstrSet(), and etiss::instr::ModedInstructionSet::print().
width
unsigned etiss::instr::VariableInstructionSet::width
Definition at line 755 of file Instruction.h.
Referenced by create(), get(), and open().
width_
unsigned etiss::instr::VariableInstructionSet::width_
Definition at line 748 of file Instruction.h.
Referenced by compile(), createMain(), getMain(), etiss::instr::ModedInstructionSet::open(), openMain(), and print().
The documentation for this class was generated from the following files:
include/etiss/Instruction.h
/home/runner/work/etiss/etiss/src/Instruction.cpp