ETISS 0.8.0: etiss::fault::Fault Class Reference
etiss::fault::Fault Class Reference
#include <Fault.h>
Public Member Functions
Fault ()
Constructor: Generates a new Fault with unique ID.
std::string toString () const
operator<< can be used.
void resolveTime (uint64_t time)
Resolves time for all its Triggers.
bool isResoved () const
check all Triggers if they are resolved.
Fault ()
Constructor: Generates a new Fault with unique ID.
std::string toString () const
operator<< can be used.
void resolveTime (uint64_t time)
Resolves time for all its Triggers.
bool isResoved () const
check all Triggers if they are resolved.
Public Member Functions inherited from etiss::ToString
ToString ()
virtual ~ToString ()
ToString ()
virtual ~ToString ()
Public Attributes
std::string name_
int32_t id_
std::vector< Trigger > triggers
contains the triggers for this fault
std::vector< Action > actions
contains the actions for this fault
Detailed Description
Definition at line 87 of file Fault.h.
Constructor & Destructor Documentation
Fault() [1/2]
etiss::fault::Fault::Fault ()
Constructor: Generates a new Fault with unique ID.
Definition at line 208 of file Fault.cpp.
References id_, etiss::log(), etiss::fault::uniqueFaultId(), and etiss::VERBOSE.
Fault() [2/2]
etiss::fault::Fault::Fault ()
Constructor: Generates a new Fault with unique ID.
Member Function Documentation
isResoved() [1/2]
bool etiss::fault::Fault::isResoved () const
check all Triggers if they are resolved.
Definition at line 239 of file Fault.cpp.
References triggers.
isResoved() [2/2]
bool etiss::fault::Fault::isResoved () const
check all Triggers if they are resolved.
resolveTime() [1/2]
void etiss::fault::Fault::resolveTime (uint64_t time)
Resolves time for all its Triggers.
resolveTime() [2/2]
void etiss::fault::Fault::resolveTime (uint64_t time)
Resolves time for all its Triggers.
Definition at line 230 of file Fault.cpp.
References etiss::log(), triggers, and etiss::VERBOSE.
toString() [1/2]
std::string etiss::fault::Fault::toString () const
operator<< can be used.
toString() [2/2]
std::string etiss::fault::Fault::toString () const
operator<< can be used.
Definition at line 213 of file Fault.cpp.
References pugi::xml_node::append_child(), pugi::xml_document::load(), and pugi::xml_document::save().
Referenced by etiss::fault::Action::Action(), and etiss::fault::Stressor::addFault().
Member Data Documentation
actions
std::vector< Action > etiss::fault::Fault::actions
contains the actions for this fault
Definition at line 101 of file Fault.h.
id_
int32_t etiss::fault::Fault::id_
Attention
negative ids are reserved
Definition at line 99 of file Fault.h.
Referenced by etiss::fault::Stressor::addFault(), etiss::VirtualStruct::applyAction(), and Fault().
name_
std::string etiss::fault::Fault::name_
Definition at line 98 of file Fault.h.
triggers
std::vector< Trigger > etiss::fault::Fault::triggers
contains the triggers for this fault
Definition at line 100 of file Fault.h.
Referenced by etiss::fault::Stressor::addFault(), isResoved(), and resolveTime().
The documentation for this class was generated from the following files:
include/etiss/fault/Fault.h
/home/runner/work/etiss/etiss/src/fault/Fault.cpp