ETISS 0.8.0: RISCV64MMU Class Reference
RISCV64MMU Class Reference
#include <RISCV64MMU.h>
Public Member Functions
RISCV64MMU (bool pid_enabled)
~RISCV64MMU ()
Public Member Functions inherited from etiss::mm::MMU
MMU (bool hw_ptw, std::string name, bool pid_enabled)
MMU ctor.
virtual ~MMU ()
virtual int32_t Translate (const uint64_t vma, uint64_t *const pma_buf, MM_ACCESS access, uint64_t data=0)
Conduct the actual translation according to the format set by PTEFormatBuilder.
void SignalMMU (uint64_t control_reg_val_)
Whenever the MMU control register changes, the MMU has to be notified with the updated control register value.
void Dump ()
Dump the details of the MMU, when page fault cannot be handled.
void Init (ETISS_CPU *cpu, ETISS_System *system)
Initialize the MMU, when DMMUWrapper is wrapping the MMU.
void AddTLBEntryMap (uint64_t phy_addr_, PTE &pte)
Keep a record of mapping between cached PTE with its physical address.
bool IsTLBFull () const
PTE EvictTLBEntry (const uint64_t vfn)
bool HasPageTableWalker ()
bool IsProcessIdEnabled ()
void UpdatePid (uint32_t new_pid)
uint64_t GetMMUControlReg ()
int32_t AddTLBEntry (const uint64_t vfn, const PTE &pte)
std::string GetName () const
virtual int32_t GetPid (uint64_t control_reg_val_)
MMU (bool hw_ptw, std::string name, bool pid_enabled)
MMU ctor.
virtual ~MMU ()
virtual int32_t Translate (const uint64_t vma, uint64_t *const pma_buf, MM_ACCESS access, uint64_t data=0)
Conduct the actual translation according to the format set by PTEFormatBuilder.
void SignalMMU (uint64_t control_reg_val_)
Whenever the MMU control register changes, the MMU has to be notified with the updated control register value.
void Dump ()
Dump the details of the MMU, when page fault cannot be handled.
void Init (ETISS_CPU *cpu, ETISS_System *system)
Initialize the MMU, when DMMUWrapper is wrapping the MMU.
void AddTLBEntryMap (uint64_t phy_addr_, PTE &pte)
Keep a record of mapping between cached PTE with its physical address.
bool IsTLBFull () const
PTE EvictTLBEntry (const uint64_t vfn)
bool HasPageTableWalker ()
bool IsProcessIdEnabled ()
void UpdatePid (uint32_t new_pid)
uint64_t GetMMUControlReg ()
int32_t AddTLBEntry (const uint64_t vfn, const PTE &pte)
std::string GetName () const
virtual int32_t GetPid (uint64_t control_reg_val_)
Private Member Functions
int32_t WalkPageTable (uint64_t vma, etiss::mm::MM_ACCESS access)
Page table walking is required to translate virtual address to physical address if TLB miss occurs.
int32_t CheckProtection (const PTE &pte, etiss::mm::MM_ACCESS access)
Memory protection is architecture-dependent, which should be implemented with architecture model.
void UpdatePTEFlags (PTE &pte, etiss::mm::MM_ACCESS access)
Reserved for some MMU that might update PTE when translating.
bool CheckPrivilegedMode ()
MMU is enabled in certain mode.
Additional Inherited Members
Public Attributes inherited from etiss::mm::MMU
bool cache_flush_pending
Protected Attributes inherited from etiss::mm::MMU
ETISS_CPU * cpu_
ETISS_System * system_
bool mmu_enabled_
Detailed Description
Definition at line 56 of file RISCV64MMU.h.
Constructor & Destructor Documentation
RISCV64MMU()
RISCV64MMU::RISCV64MMU (bool pid_enabled)
Definition at line 50 of file RISCV64MMU.cpp.
References etiss::mm::PTEOVERLAP, REGISTER_PAGE_FAULT_HANDLER, and tlb_overlap_handler().
~RISCV64MMU()
RISCV64MMU::~RISCV64MMU () inline
Definition at line 62 of file RISCV64MMU.h.
Member Function Documentation
CheckPrivilegedMode()
bool RISCV64MMU::CheckPrivilegedMode () inline private virtual
MMU is enabled in certain mode.
Thus the privilege mode check should be implemented in architectural part
Implements etiss::mm::MMU.
Definition at line 71 of file RISCV64MMU.h.
References false, and PRV_M.
CheckProtection()
int32_t RISCV64MMU::CheckProtection (const PTE & , etiss::mm::MM_ACCESS access) private virtual
Memory protection is architecture-dependent, which should be implemented with architecture model.
Implements etiss::mm::MMU.
Definition at line 194 of file RISCV64MMU.cpp.
References etiss::mm::PTE::GetByName(), etiss::mm::NOERROR, etiss::mm::R_ACCESS, etiss::mm::W_ACCESS, and etiss::mm::X_ACCESS.
UpdatePTEFlags()
void RISCV64MMU::UpdatePTEFlags (PTE & , etiss::mm::MM_ACCESS) inline private virtual
Reserved for some MMU that might update PTE when translating.
Reimplemented from etiss::mm::MMU.
Definition at line 69 of file RISCV64MMU.h.
WalkPageTable()
int32_t RISCV64MMU::WalkPageTable (uint64_t , etiss::mm::MM_ACCESS) private virtual
Page table walking is required to translate virtual address to physical address if TLB miss occurs.
Reimplemented from etiss::mm::MMU.
Definition at line 79 of file RISCV64MMU.cpp.
References etiss::mm::MMU::AddTLBEntry(), etiss::mm::MMU::AddTLBEntryMap(), etiss::mm::MMU::cpu_, ETISS_System::dread, ETISS_System::dwrite, etiss::mm::PTE::Get(), etiss::mm::PTE::GetByName(), etiss::mm::MMU::GetMMUControlReg(), etiss::mm::MMU::GetName(), ETISS_System::handle, etiss::INFO, LEVELS, etiss::log(), etiss::mm::MMU::mmu_enabled_, etiss::mm::NOERROR, PAGE_OFFSET, PTE_A, PTE_D, PTESIZE, etiss::mm::R_ACCESS, SATP_PPN_MASK, etiss::mm::MMU::system_, etiss::mm::PTE::Update(), VPN_OFFSET, etiss::mm::W_ACCESS, etiss::WARNING, and etiss::mm::X_ACCESS.
The documentation for this class was generated from the following files:
/home/runner/work/etiss/etiss/ArchImpl/RISCV64/RISCV64MMU.h
/home/runner/work/etiss/etiss/ArchImpl/RISCV64/RISCV64MMU.cpp