ETISS 0.8.0: etiss::interfaces::VCD Class Reference
etiss::interfaces::VCD Class Reference
#include <VCD.h>
Classes
class Signal
Public Member Functions
template<typename T >
bool declare (T &variable, const std::string &name, unsigned width, uint64_t initialvalue, uint64_t undefined=-1)
template<typename T >
void update (double time_s, const T &variable, uint64_t value, uint64_t undefined=0)
std::string toString () const
void close ()
template<typename T >
bool declare (T &variable, const std::string &name, unsigned width, uint64_t initialvalue, uint64_t undefined=-1)
template<typename T >
void update (double time_s, const T &variable, uint64_t value, uint64_t undefined=0)
std::string toString () const
void close ()
Public Member Functions inherited from etiss::ToString
ToString ()
virtual ~ToString ()
ToString ()
virtual ~ToString ()
Protected Member Functions
bool declare (void *variable, const std::string &name, unsigned width, uint64_t initialvalue, uint64_t undefined)
void update (uint64_t time_ps, void *variable, uint64_t value, uint64_t undefined)
void flush ()
bool declare (void *variable, const std::string &name, unsigned width, uint64_t initialvalue, uint64_t undefined)
void update (uint64_t time_ps, void *variable, uint64_t value, uint64_t undefined)
void flush ()
Private Attributes
std::ofstream out_
bool valid_
bool dumpstarted_
std::vector< Signal > sigs_
uint64_t lasttime_ps
std::map< void *, int > ptr2index_
std::string dumpvar
TODO replace with better lookup.
std::string file
Detailed Description
Attention
this class streams the output to a file. the update() function may therfore only be called with equal or increasing time values
Definition at line 86 of file VCD.h.
Member Function Documentation
close() [1/2]
void etiss::interfaces::VCD::close ()
Definition at line 124 of file VCD.cpp.
close() [2/2]
void etiss::interfaces::VCD::close ()
declare() [1/4]
template<typename T > bool etiss::interfaces::VCD::declare (T & variable, const std::string & name, unsigned width, uint64_t initialvalue, uint64_t undefined = -1) inline
Definition at line 107 of file VCD.h.
References declare(), and name.
declare() [2/4]
template<typename T > bool etiss::interfaces::VCD::declare (T & variable, const std::string & name, unsigned width, uint64_t initialvalue, uint64_t undefined = -1) inline
Definition at line 107 of file VCD.h.
References name.
Referenced by declare().
declare() [3/4]
bool etiss::interfaces::VCD::declare (void * variable, const std::string & name, unsigned width, uint64_t initialvalue, uint64_t undefined) protected
Definition at line 133 of file VCD.cpp.
References etiss::ERROR, etiss::interfaces::VCD::Signal::ident, etiss::interfaces::index2str(), etiss::log(), etiss::interfaces::VCD::Signal::name, name, etiss::split(), etiss::interfaces::VCD::Signal::undefined, etiss::interfaces::val2str(), etiss::interfaces::VCD::Signal::valid, etiss::interfaces::VCD::Signal::value, and etiss::interfaces::VCD::Signal::width.
declare() [4/4]
bool etiss::interfaces::VCD::declare (void * variable, const std::string & name, unsigned width, uint64_t initialvalue, uint64_t undefined) protected
flush() [1/2]
void etiss::interfaces::VCD::flush () protected
Definition at line 223 of file VCD.cpp.
References s, and etiss::interfaces::val2str().
flush() [2/2]
void etiss::interfaces::VCD::flush () protected
toString() [1/2]
std::string etiss::interfaces::VCD::toString () const inline
Definition at line 119 of file VCD.h.
References file.
toString() [2/2]
std::string etiss::interfaces::VCD::toString () const inline
Definition at line 119 of file VCD.h.
References file.
update() [1/4]
template<typename T > void etiss::interfaces::VCD::update (double time_s, const T & variable, uint64_t value, uint64_t undefined = 0) inline
Definition at line 114 of file VCD.h.
Referenced by update().
update() [2/4]
template<typename T > void etiss::interfaces::VCD::update (double time_s, const T & variable, uint64_t value, uint64_t undefined = 0) inline
Definition at line 114 of file VCD.h.
References update().
update() [3/4]
void etiss::interfaces::VCD::update (uint64_t time_ps, void * variable, uint64_t value, uint64_t undefined) protected
Definition at line 195 of file VCD.cpp.
References etiss::ERROR, etiss::log(), etiss::interfaces::VCD::Signal::undefined, etiss::interfaces::VCD::Signal::valid, and etiss::interfaces::VCD::Signal::value.
update() [4/4]
void etiss::interfaces::VCD::update (uint64_t time_ps, void * variable, uint64_t value, uint64_t undefined) protected
Member Data Documentation
dumpstarted_
bool etiss::interfaces::VCD::dumpstarted_ private
Definition at line 131 of file VCD.h.
dumpvar
std::string etiss::interfaces::VCD::dumpvar private
TODO replace with better lookup.
Definition at line 135 of file VCD.h.
file
std::string etiss::interfaces::VCD::file private
Definition at line 136 of file VCD.h.
Referenced by toString().
lasttime_ps
uint64_t etiss::interfaces::VCD::lasttime_ps private
Definition at line 133 of file VCD.h.
out_
std::ofstream etiss::interfaces::VCD::out_ private
Definition at line 129 of file VCD.h.
ptr2index_
std::map< void *, int > etiss::interfaces::VCD::ptr2index_ private
Definition at line 134 of file VCD.h.
sigs_
std::vector< Signal > etiss::interfaces::VCD::sigs_ private
Definition at line 132 of file VCD.h.
valid_
bool etiss::interfaces::VCD::valid_ private
Definition at line 130 of file VCD.h.
The documentation for this class was generated from the following files:
include/etiss/interfaces/VCD.h
/home/runner/work/etiss/etiss/src/interfaces/VCD.cpp