ETISS 0.8.0: etiss::VSSync Class Reference
etiss::VSSync Class Reference
used for synchronization of the tree of virtual structs.
#include <VirtualStruct.h>
Public Member Functions
VSSync ()
~VSSync ()
VSSync ()
~VSSync ()
Static Private Member Functions
static std::recursive_mutex & mutex ()
static std::recursive_mutex & mutex ()
Detailed Description
used for synchronization of the tree of virtual structs.
Attention
this cannot be used to synchronize field access
Definition at line 419 of file VirtualStruct.h.
Constructor & Destructor Documentation
VSSync() [1/2]
etiss::VSSync::VSSync ()
Definition at line 520 of file VirtualStruct.cpp.
References mutex().
~VSSync() [1/2]
etiss::VSSync::~VSSync ()
Definition at line 524 of file VirtualStruct.cpp.
References mutex().
VSSync() [2/2]
etiss::VSSync::VSSync ()
~VSSync() [2/2]
etiss::VSSync::~VSSync ()
Member Function Documentation
mutex() [1/2]
std::recursive_mutex & etiss::VSSync::mutex () static private
Definition at line 528 of file VirtualStruct.cpp.
Referenced by VSSync(), and ~VSSync().
mutex() [2/2]
static std::recursive_mutex& etiss::VSSync::mutex () static private
The documentation for this class was generated from the following files:
include/etiss/VirtualStruct.h
/home/runner/work/etiss/etiss/src/VirtualStruct.cpp