ETISS 0.8.0: etiss::plugin::gdb::Server Class Reference
etiss::plugin::gdb::Server Class Reference
gdb server implementation that is used as a plugin in etiss
#include <GDBServer.h>
Public Member Functions
Server (etiss::plugin::gdb::PacketProtocol &pp)
void init (ETISS_CPU *cpu, ETISS_System *system, CPUArch *arch) override
this function is called before the plugin is used in the cpu execution loop (etiss::CPUCore::execute).
void cleanup () override
this function is called after cpu execution loop (etiss::CPUCore::execute) finished.
etiss::int32 execute () override
called before a block and may act in the same way as a block
void finalizeInstrSet (etiss::instr::ModedInstructionSet &) const override
called after all instructions have been added to allow last changes
void finalizeCodeBlock (etiss::CodeBlock &) const override
called after all instructions have been translated for the code block
void * getPluginHandle () override
called to get the handle that is available in translated code via getPoinerCode(). [default: this]
ETISS_System * wrap (ETISS_CPU *cpu, ETISS_System *system) override
SystemWrapper,.
ETISS_System * unwrap (ETISS_CPU *cpu, ETISS_System *system) override
undo wrap function call this function will be called AFTER etiss::Plugin::cleanup
etiss::int32 preInstructionCallback ()
void preDReadCallback (etiss::uint64 addr)
void preDWriteCallback (etiss::uint64 addr)
etiss::int32 postMemAccessCallback (etiss::int32 exception)
Server (etiss::plugin::gdb::PacketProtocol &pp)
void init (ETISS_CPU *cpu, ETISS_System *system, CPUArch *arch) override
this function is called before the plugin is used in the cpu execution loop (etiss::CPUCore::execute).
void cleanup () override
this function is called after cpu execution loop (etiss::CPUCore::execute) finished.
etiss::int32 execute () override
called before a block and may act in the same way as a block
void finalizeInstrSet (etiss::instr::ModedInstructionSet &) const override
called after all instructions have been added to allow last changes
void finalizeCodeBlock (etiss::CodeBlock &) const override
called after all instructions have been translated for the code block
void * getPluginHandle () override
called to get the handle that is available in translated code via getPoinerCode(). [default: this]
ETISS_System * wrap (ETISS_CPU *cpu, ETISS_System *system) override
SystemWrapper,.
ETISS_System * unwrap (ETISS_CPU *cpu, ETISS_System *system) override
undo wrap function call this function will be called AFTER etiss::Plugin::cleanup
etiss::int32 preInstructionCallback ()
void preDReadCallback (etiss::uint64 addr)
void preDWriteCallback (etiss::uint64 addr)
etiss::int32 postMemAccessCallback (etiss::int32 exception)
Public Member Functions inherited from etiss::CoroutinePlugin
CoroutinePlugin ()
virtual ~CoroutinePlugin ()
virtual void executionEnd (int32_t code)
called when the simulation ends but before any deinitialization is done
virtual bool isActive ()
indicates if the plugin will do something in execution loop.
CoroutinePlugin ()
virtual ~CoroutinePlugin ()
virtual void executionEnd (int32_t code)
called when the simulation ends but before any deinitialization is done
virtual bool isActive ()
indicates if the plugin will do something in execution loop.
Public Member Functions inherited from etiss::Plugin
virtual ~Plugin ()
unsigned getType ()
InterruptListenerPlugin * getInterruptListenerPlugin ()
CoroutinePlugin * getCoroutinePlugin ()
SystemWrapperPlugin * getSystemWrapperPlugin ()
RegisterDevicePlugin * getRegisterDevicePlugin ()
TranslationPlugin * getTranslationPlugin ()
std::string getPluginName () const
const std::string & getLastAssignedCoreName ()
std::string toString () const
virtual ~Plugin ()
unsigned getType ()
InterruptListenerPlugin * getInterruptListenerPlugin ()
CoroutinePlugin * getCoroutinePlugin ()
SystemWrapperPlugin * getSystemWrapperPlugin ()
RegisterDevicePlugin * getRegisterDevicePlugin ()
TranslationPlugin * getTranslationPlugin ()
std::string getPluginName () const
const std::string & getLastAssignedCoreName ()
std::string toString () const
Public Member Functions inherited from etiss::ToString
ToString ()
virtual ~ToString ()
ToString ()
virtual ~ToString ()
Public Member Functions inherited from etiss::TranslationPlugin
TranslationPlugin ()
virtual ~TranslationPlugin ()
virtual void initInstrSet (etiss::instr::ModedInstructionSet &) const
called to add instructions to the instruction set
virtual void initCodeBlock (etiss::CodeBlock &) const
called before instructions are translated for the code block
TranslationPlugin ()
virtual ~TranslationPlugin ()
virtual void initInstrSet (etiss::instr::ModedInstructionSet &) const
called to add instructions to the instruction set
virtual void initCodeBlock (etiss::CodeBlock &) const
called before instructions are translated for the code block
Public Member Functions inherited from etiss::SystemWrapperPlugin
SystemWrapperPlugin ()
virtual ~SystemWrapperPlugin ()
SystemWrapperPlugin ()
virtual ~SystemWrapperPlugin ()
Static Public Member Functions
static Server * createTCPServer (std::map< std::string, std::string > options)
static Server * createTCPServer (int port)
static Server * createTCPServer (std::map< std::string, std::string > options)
static Server * createTCPServer (int port)
Protected Member Functions
std::string _getPluginName () const override
void handlePacket (bool block)
std::string _getPluginName () const override
void handlePacket (bool block)
Protected Member Functions inherited from etiss::Plugin
Plugin (unsigned type=0)
void setCorrespondingCPUCoreName (std::string name)
virtual void addedToCPUCore (etiss::CPUCore *core)
called as soon a plugin has been added to its CPUCore.
virtual void removedFromCPUCore (etiss::CPUCore *core)
called as soon a plugin has been removed from its CPUCore.
Plugin (unsigned type=0)
void setCorrespondingCPUCoreName (std::string name)
virtual void addedToCPUCore (etiss::CPUCore *core)
called as soon a plugin has been added to its CPUCore.
virtual void removedFromCPUCore (etiss::CPUCore *core)
called as soon a plugin has been removed from its CPUCore.
Protected Member Functions inherited from etiss::TranslationPlugin
std::string getPointerCode () const
returns a C code expression that allows to get or assign a pointer to the variable assigned to this translation plugin.
std::string getPointerCode () const
returns a C code expression that allows to get or assign a pointer to the variable assigned to this translation plugin.
Protected Attributes
etiss::plugin::gdb::PacketProtocol & con_
CPUArch * arch_
ETISS_CPU * cpu_
ETISS_System * system_
ETISS_System * unwrappedSys_
bool status_paused_
bool gdb_status_paused_
unsigned status_step_
bool status_pending_jump_
bool status_pending_kill_
etiss::uint64 status_jumpaddr_
BreakpointDB breakpoints_
BreakpointDB watchpoints_
unsigned execute_skip_count
unsigned execute_skip_index
unsigned minimal_pc_alignment
Protected Attributes inherited from etiss::Plugin
ETISS_CPU * plugin_cpu_
holds a pointer to the cpu structure. will be set before init call and after cleanup call
ETISS_System * plugin_system_
holds a pointer to the system structure.
CPUArch * plugin_arch_
holds a pointer to the CPUArch instance. will be set before init call and after cleanup call
CPUCore * plugin_core_
holds a pointer to the associated CPUCore instance.
Private Attributes
std::shared_ptr< Connection > cinst_
Additional Inherited Members
Static Public Attributes inherited from etiss::Plugin
static const unsigned INTERRUPTLISTENER = 1 << 0
access to translated code
static const unsigned COROUTINE = 1 << 1
callback after execution of each translated block
static const unsigned SYSTEMWRAPPER = 1 << 2
can wrap/change ETISS_System structure at execution start
static const unsigned REGISTERDEVICE
gets noticed of changes to special registers (e.g. mmu register etc. [depends on architecture])
static const unsigned TRANSLATION
access to translated code during translation phase or when instruction tree is built
Detailed Description
gdb server implementation that is used as a plugin in etiss
Definition at line 124 of file GDBServer.h.
Constructor & Destructor Documentation
Server() [1/2]
Server::Server (etiss::plugin::gdb::PacketProtocol & pp)
Definition at line 157 of file GDBServer.cpp.
References arch_, cpu_, execute_skip_count, execute_skip_index, gdb_status_paused_, minimal_pc_alignment, status_jumpaddr_, status_paused_, status_pending_jump_, status_pending_kill_, status_step_, and system_.
Referenced by createTCPServer().
Server() [2/2]
etiss::plugin::gdb::Server::Server (etiss::plugin::gdb::PacketProtocol & pp)
Member Function Documentation
_getPluginName() [1/2]
std::string Server::_getPluginName () const override protected virtual
Implements etiss::Plugin.
Definition at line 809 of file GDBServer.cpp.
_getPluginName() [2/2]
std::string etiss::plugin::gdb::Server::_getPluginName () const override protected virtual
Implements etiss::Plugin.
cleanup() [1/2]
void etiss::plugin::gdb::Server::cleanup () override virtual
this function is called after cpu execution loop (etiss::CPUCore::execute) finished.
Only the SystemWrapperPlugin::unwrap function is called AFTER Plugin::cleanup
Reimplemented from etiss::Plugin.
cleanup() [2/2]
void Server::cleanup () override virtual
this function is called after cpu execution loop (etiss::CPUCore::execute) finished.
Only the SystemWrapperPlugin::unwrap function is called AFTER Plugin::cleanup
Reimplemented from etiss::Plugin.
Definition at line 826 of file GDBServer.cpp.
References arch_, cpu_, and system_.
createTCPServer() [1/4]
Server * Server::createTCPServer (int port) static
Definition at line 875 of file GDBServer.cpp.
References etiss::plugin::gdb::Connection::getPacketProtocol(), etiss::log(), s, Server(), etiss::toString(), and etiss::VERBOSE.
createTCPServer() [2/4]
static Server* etiss::plugin::gdb::Server::createTCPServer (int port) static
createTCPServer() [3/4]
Server * Server::createTCPServer (std::map< std::string, std::string > options) static
Definition at line 833 of file GDBServer.cpp.
References etiss::ERROR, etiss::log(), options, and s.
Referenced by ETISSINCLUDED_createPlugin().
createTCPServer() [4/4]
static Server* etiss::plugin::gdb::Server::createTCPServer (std::map< std::string, std::string > options) static
execute() [1/2]
etiss::int32 etiss::plugin::gdb::Server::execute () override virtual
called before a block and may act in the same way as a block
Implements etiss::CoroutinePlugin.
execute() [2/2]
etiss::int32 Server::execute () override virtual
called before a block and may act in the same way as a block
Implements etiss::CoroutinePlugin.
Definition at line 225 of file GDBServer.cpp.
References execute_skip_count, execute_skip_index, handlePacket(), status_pending_kill_, and unlikely.
finalizeCodeBlock() [1/2]
void Server::finalizeCodeBlock (etiss::CodeBlock &) const override virtual
called after all instructions have been translated for the code block
Reimplemented from etiss::TranslationPlugin.
Definition at line 277 of file GDBServer.cpp.
References etiss::CodeBlock::fileglobalCode().
finalizeCodeBlock() [2/2]
void etiss::plugin::gdb::Server::finalizeCodeBlock (etiss::CodeBlock &) const override virtual
called after all instructions have been translated for the code block
Reimplemented from etiss::TranslationPlugin.
finalizeInstrSet() [1/2]
void Server::finalizeInstrSet (etiss::instr::ModedInstructionSet &) const override virtual
called after all instructions have been added to allow last changes
Reimplemented from etiss::TranslationPlugin.
Definition at line 269 of file GDBServer.cpp.
References etiss::instr::VariableInstructionSet::foreach(), etiss::instr::ModedInstructionSet::foreach(), etiss::TranslationPlugin::getPointerCode(), and Server_finalizeInstrSet().
finalizeInstrSet() [2/2]
void etiss::plugin::gdb::Server::finalizeInstrSet (etiss::instr::ModedInstructionSet &) const override virtual
called after all instructions have been added to allow last changes
Reimplemented from etiss::TranslationPlugin.
getPluginHandle() [1/2]
void* etiss::plugin::gdb::Server::getPluginHandle () override virtual
called to get the handle that is available in translated code via getPoinerCode(). [default: this]
Reimplemented from etiss::TranslationPlugin.
getPluginHandle() [2/2]
void * Server::getPluginHandle () override virtual
called to get the handle that is available in translated code via getPoinerCode(). [default: this]
Reimplemented from etiss::TranslationPlugin.
Definition at line 814 of file GDBServer.cpp.
handlePacket() [1/2]
void Server::handlePacket (bool block) protected
Definition at line 284 of file GDBServer.cpp.
References arch_, etiss::plugin::gdb::PacketProtocol::available(), etiss::plugin::gdb::BreakpointDB::BPTYPE_BREAK_HW, etiss::plugin::gdb::BreakpointDB::BPTYPE_BREAK_MEM, etiss::plugin::gdb::BreakpointDB::BPTYPE_WATCH_READ, etiss::plugin::gdb::BreakpointDB::BPTYPE_WATCH_WRITE, breakpoints_, con_, ETISS_System::dbg_read, ETISS_System::dbg_write, etiss::ERROR, etiss::plugin::gdb::hex::fromByte(), etiss::plugin::gdb::hex::fromBytes(), etiss::plugin::gdb::hex::fromHex(), etiss::plugin::gdb::hex::fromInt(), gdb_status_paused_, etiss::plugin::gdb::BreakpointDB::get(), etiss::CPUArch::getGDBCore(), etiss::CPUCore::getStruct(), ETISS_System::handle, etiss::plugin::gdb::GDBCore::isLittleEndian(), length(), etiss::log(), etiss::plugin::gdb::GDBCore::mapRegister(), minimal_pc_alignment, etiss::mm::NOERROR, etiss::Plugin::plugin_core_, etiss::plugin::gdb::PacketProtocol::rcv(), etiss::plugin::gdb::BreakpointDB::set(), etiss::plugin::gdb::PacketProtocol::snd(), status_jumpaddr_, status_paused_, status_pending_jump_, status_pending_kill_, status_step_, system_, etiss::plugin::gdb::hex::toByte(), and watchpoints_.
Referenced by execute(), postMemAccessCallback(), and preInstructionCallback().
handlePacket() [2/2]
void etiss::plugin::gdb::Server::handlePacket (bool block) protected
init() [1/2]
void Server::init (ETISS_CPU * cpu, ETISS_System * system, etiss::CPUArch * arch) override virtual
this function is called before the plugin is used in the cpu execution loop (etiss::CPUCore::execute).
Only exception is the SystemWrapperPlugin whose SystemWrapperPlugin::wrap function is called BEFORE Plugin::init
Reimplemented from etiss::Plugin.
Definition at line 819 of file GDBServer.cpp.
References arch_, cpu_, and system_.
init() [2/2]
void etiss::plugin::gdb::Server::init (ETISS_CPU * cpu, ETISS_System * system, CPUArch * arch) override virtual
this function is called before the plugin is used in the cpu execution loop (etiss::CPUCore::execute).
Only exception is the SystemWrapperPlugin whose SystemWrapperPlugin::wrap function is called BEFORE Plugin::init
Reimplemented from etiss::Plugin.
postMemAccessCallback() [1/2]
etiss::int32 Server::postMemAccessCallback (etiss::int32 exception)
Definition at line 775 of file GDBServer.cpp.
References con_, cpu_, etiss::plugin::gdb::hex::fromByte(), gdb_status_paused_, handlePacket(), ETISS_CPU::instructionPointer, etiss::mm::NOERROR, etiss::plugin::gdb::PacketProtocol::snd(), status_jumpaddr_, status_paused_, status_pending_jump_, status_pending_kill_, and unlikely.
postMemAccessCallback() [2/2]
etiss::int32 etiss::plugin::gdb::Server::postMemAccessCallback (etiss::int32 exception)
preDReadCallback() [1/2]
void Server::preDReadCallback (etiss::uint64 addr)
Definition at line 754 of file GDBServer.cpp.
References etiss::plugin::gdb::BreakpointDB::BPTYPE_WATCH_READ, etiss::plugin::gdb::BreakpointDB::get(), etiss::plugin::gdb::BreakpointDB::isEmpty(), status_paused_, and watchpoints_.
preDReadCallback() [2/2]
void etiss::plugin::gdb::Server::preDReadCallback (etiss::uint64 addr)
preDWriteCallback() [1/2]
void etiss::plugin::gdb::Server::preDWriteCallback (etiss::uint64 addr)
preDWriteCallback() [2/2]
void Server::preDWriteCallback (etiss::uint64 addr)
Definition at line 764 of file GDBServer.cpp.
References etiss::plugin::gdb::BreakpointDB::BPTYPE_WATCH_WRITE, etiss::plugin::gdb::BreakpointDB::get(), etiss::plugin::gdb::BreakpointDB::isEmpty(), status_paused_, and watchpoints_.
preInstructionCallback() [1/2]
etiss::int32 etiss::plugin::gdb::Server::preInstructionCallback ()
preInstructionCallback() [2/2]
etiss::int32 Server::preInstructionCallback ()
Definition at line 173 of file GDBServer.cpp.
References arch_, etiss::plugin::gdb::BreakpointDB::BPTYPE_BREAK_HW, etiss::plugin::gdb::BreakpointDB::BPTYPE_BREAK_MEM, breakpoints_, con_, cpu_, etiss::plugin::gdb::hex::fromByte(), gdb_status_paused_, etiss::plugin::gdb::BreakpointDB::get(), etiss::CPUArch::getGDBCore(), etiss::plugin::gdb::GDBCore::getInstructionPointer(), handlePacket(), ETISS_CPU::instructionPointer, etiss::plugin::gdb::BreakpointDB::isEmpty(), minimal_pc_alignment, etiss::mm::NOERROR, etiss::plugin::gdb::PacketProtocol::snd(), status_jumpaddr_, status_paused_, status_pending_jump_, status_pending_kill_, status_step_, and unlikely.
unwrap() [1/2]
ETISS_System * Server::unwrap (ETISS_CPU * cpu, ETISS_System * system) override virtual
undo wrap function call this function will be called AFTER etiss::Plugin::cleanup
Implements etiss::SystemWrapperPlugin.
Definition at line 146 of file GDBSystemWrapper.cpp.
References ETISS_GDBSystem::sys_, and ETISS_GDBSystem::system.
unwrap() [2/2]
ETISS_System* etiss::plugin::gdb::Server::unwrap (ETISS_CPU * cpu, ETISS_System * system) override virtual
undo wrap function call this function will be called AFTER etiss::Plugin::cleanup
Implements etiss::SystemWrapperPlugin.
wrap() [1/2]
ETISS_System* etiss::plugin::gdb::Server::wrap (ETISS_CPU * cpu, ETISS_System * system) override virtual
SystemWrapper,.
See also
GDBSystemWrapper.cpp
Implements etiss::SystemWrapperPlugin.
wrap() [2/2]
ETISS_System * Server::wrap (ETISS_CPU * cpu, ETISS_System * system) override virtual
SystemWrapper,.
See also
GDBSystemWrapper.cpp
Implements etiss::SystemWrapperPlugin.
Definition at line 116 of file GDBSystemWrapper.cpp.
References ETISS_System::dbg_read, ETISS_System::dbg_write, ETISS_System::dread, ETISS_System::dwrite, gdb_system_call_dbg_read(), gdb_system_call_dbg_write(), gdb_system_call_dread(), gdb_system_call_dwrite(), gdb_system_call_iread(), gdb_system_call_iwrite(), gdb_system_call_syncTime(), ETISS_System::handle, ETISS_System::iread, ETISS_System::iwrite, ETISS_GDBSystem::server_, ETISS_System::syncTime, ETISS_GDBSystem::sys_, and unwrappedSys_.
Member Data Documentation
arch_
CPUArch * etiss::plugin::gdb::Server::arch_ protected
Definition at line 159 of file GDBServer.h.
Referenced by cleanup(), handlePacket(), init(), preInstructionCallback(), and Server().
breakpoints_
BreakpointDB etiss::plugin::gdb::Server::breakpoints_ protected
Definition at line 169 of file GDBServer.h.
Referenced by handlePacket(), and preInstructionCallback().
cinst_
std::shared_ptr< Connection > etiss::plugin::gdb::Server::cinst_ private
Definition at line 176 of file GDBServer.h.
con_
etiss::plugin::gdb::PacketProtocol & etiss::plugin::gdb::Server::con_ protected
Definition at line 158 of file GDBServer.h.
Referenced by handlePacket(), postMemAccessCallback(), and preInstructionCallback().
cpu_
ETISS_CPU * etiss::plugin::gdb::Server::cpu_ protected
Definition at line 160 of file GDBServer.h.
Referenced by cleanup(), init(), postMemAccessCallback(), preInstructionCallback(), and Server().
execute_skip_count
unsigned etiss::plugin::gdb::Server::execute_skip_count protected
Definition at line 171 of file GDBServer.h.
Referenced by execute(), and Server().
execute_skip_index
unsigned etiss::plugin::gdb::Server::execute_skip_index protected
Definition at line 172 of file GDBServer.h.
Referenced by execute(), and Server().
gdb_status_paused_
bool etiss::plugin::gdb::Server::gdb_status_paused_ protected
Definition at line 164 of file GDBServer.h.
Referenced by handlePacket(), postMemAccessCallback(), preInstructionCallback(), and Server().
minimal_pc_alignment
unsigned etiss::plugin::gdb::Server::minimal_pc_alignment protected
Definition at line 173 of file GDBServer.h.
Referenced by handlePacket(), preInstructionCallback(), and Server().
status_jumpaddr_
etiss::uint64 etiss::plugin::gdb::Server::status_jumpaddr_ protected
Definition at line 168 of file GDBServer.h.
Referenced by handlePacket(), postMemAccessCallback(), preInstructionCallback(), and Server().
status_paused_
bool etiss::plugin::gdb::Server::status_paused_ protected
Definition at line 163 of file GDBServer.h.
Referenced by handlePacket(), postMemAccessCallback(), preDReadCallback(), preDWriteCallback(), preInstructionCallback(), and Server().
status_pending_jump_
bool etiss::plugin::gdb::Server::status_pending_jump_ protected
Definition at line 166 of file GDBServer.h.
Referenced by handlePacket(), postMemAccessCallback(), preInstructionCallback(), and Server().
status_pending_kill_
bool etiss::plugin::gdb::Server::status_pending_kill_ protected
Definition at line 167 of file GDBServer.h.
Referenced by execute(), handlePacket(), postMemAccessCallback(), preInstructionCallback(), and Server().
status_step_
unsigned etiss::plugin::gdb::Server::status_step_ protected
Definition at line 165 of file GDBServer.h.
Referenced by handlePacket(), preInstructionCallback(), and Server().
system_
ETISS_System * etiss::plugin::gdb::Server::system_ protected
Definition at line 161 of file GDBServer.h.
Referenced by cleanup(), handlePacket(), init(), and Server().
unwrappedSys_
ETISS_System * etiss::plugin::gdb::Server::unwrappedSys_ protected
Definition at line 162 of file GDBServer.h.
Referenced by wrap().
watchpoints_
BreakpointDB etiss::plugin::gdb::Server::watchpoints_ protected
Definition at line 170 of file GDBServer.h.
Referenced by handlePacket(), preDReadCallback(), and preDWriteCallback().
The documentation for this class was generated from the following files:
include/etiss/IntegratedLibrary/gdb/GDBServer.h
/home/runner/work/etiss/etiss/src/IntegratedLibrary/gdb/GDBServer.cpp
/home/runner/work/etiss/etiss/src/IntegratedLibrary/gdb/GDBSystemWrapper.cpp