ETISS 0.8.0: etiss::ConfigAnnouncer Class Reference
etiss::ConfigAnnouncer Class Reference
simple class to add a configuration option to the list of known options
#include <Misc.h>
Public Member Functions
ConfigAnnouncer (Configuration &config, std::string key, std::string type=std::string(), std::string values=std::string(), std::string description=std::string())
ConfigAnnouncer (std::string key, std::string type=std::string(), std::string values=std::string(), std::string description=std::string())
ConfigAnnouncer (Configuration &config, std::string key, std::string type=std::string(), std::string values=std::string(), std::string description=std::string())
ConfigAnnouncer (std::string key, std::string type=std::string(), std::string values=std::string(), std::string description=std::string())
Detailed Description
simple class to add a configuration option to the list of known options
Definition at line 505 of file Misc.h.
Constructor & Destructor Documentation
ConfigAnnouncer() [1/4]
etiss::ConfigAnnouncer::ConfigAnnouncer (Configuration & config, std::string key, std::string type = std::string(), std::string values = std::string(), std::string description = std::string()) inline
Definition at line 508 of file Misc.h.
References etiss::Configuration::announce().
ConfigAnnouncer() [2/4]
etiss::ConfigAnnouncer::ConfigAnnouncer (std::string key, std::string type = std::string(), std::string values = std::string(), std::string description = std::string()) inline
Definition at line 514 of file Misc.h.
References etiss::Configuration::announce(), and etiss::cfg().
ConfigAnnouncer() [3/4]
etiss::ConfigAnnouncer::ConfigAnnouncer (Configuration & config, std::string key, std::string type = std::string(), std::string values = std::string(), std::string description = std::string()) inline
Definition at line 508 of file Misc.h.
ConfigAnnouncer() [4/4]
etiss::ConfigAnnouncer::ConfigAnnouncer (std::string key, std::string type = std::string(), std::string values = std::string(), std::string description = std::string()) inline
Definition at line 514 of file Misc.h.
References etiss::Configuration::announce(), and etiss::cfg().
The documentation for this class was generated from the following file:
include/etiss/Misc.h