ETISS 0.8.0: etiss::instr::OPCode Class Reference
etiss::instr::OPCode Class Reference
defines the relevant bits and their value to identify an instruction.
#include <Instruction.h>
Public Member Functions
template<typename T , typename = typename std::enable_if<std::is_integral<T>::value, T>::type>
OPCode (unsigned width, const T code, const T mask)
ctor that uses integral values for mask and code
OPCode (const BitArray &code, const BitArray &mask)
OPCode (const OPCode &cpy)
copy ctor
bool operator< (const OPCode &o) const
comparison operator for map/sets.
bool operator== (const OPCode &o) const
bool operator!= (const OPCode &o) const
template<typename T , typename = typename std::enable_if<std::is_integral<T>::value, T>::type>
OPCode (unsigned width, const T code, const T mask)
ctor that uses integral values for mask and code
OPCode (const BitArray &code, const BitArray &mask)
OPCode (const OPCode &cpy)
copy ctor
bool operator< (const OPCode &o) const
comparison operator for map/sets.
bool operator== (const OPCode &o) const
bool operator!= (const OPCode &o) const
Public Attributes
const BitArray code_
const BitArray mask_
Detailed Description
defines the relevant bits and their value to identify an instruction.
e.g. l.add of the or1k architecture:
opcode: 0x38 (bit 31-25), 0x0 (bit 9-8), 0x0 (bit 3-0)
the resulting code as passed to the constructor would be: 0xE0000000 the resulting mask as passed to the constructor would be: 0xFC00030F
to simplify that procedure a simple language is provided to generate those values from a representation that is much more similar to the opcode definition in text form.
see uint32_t parse_i32(const char * s) or for a more general implementation see template <typename T> T parse_i(const char * s)
if there is c++11 support then the literal operator ""_i32 can be used instead of parse_i32()
the syntax for parse_i/parse_i32 is very simple. the number of bits is followed by an 'x' and the value represented in hex (additional bits from the hex representation are discarded). further such definitions are seperated by a space character. the definitions further to the left will be left shifted by the length of followind definitions. e.g for l.add:
uint32_t code = parse_i32("6x32 16x0 2x0 4x0 4x0"); // or parse_i32("6x32 26x0") or parse_i32("6x32 15x0 1x0 2x0 4x0 4x0") uint32_t mask = parse_i32("6xFF 16x0 2xF 4x0 4xF");
Definition at line 418 of file Instruction.h.
Constructor & Destructor Documentation
OPCode() [1/6]
template<typename T , typename = typename std::enable_if<std::is_integral<T>::value, T>::type> etiss::instr::OPCode::OPCode (unsigned width, const T code, const T mask) inline
ctor that uses integral values for mask and code
Attention
only if DEBUG is defined as non zero a warning message will be printed if the code doesn't fit the mask
Parameters
width width in bits
Definition at line 431 of file Instruction.h.
References etiss::log(), etiss::toString(), etiss::VERBOSE, and etiss::WARNING.
OPCode() [2/6]
etiss::instr::OPCode::OPCode (const BitArray & code, const BitArray & mask)
Attention
the width of code and mask MUST be equal
Definition at line 467 of file Instruction.cpp.
References code_, etiss::ERROR, etiss::log(), mask_, etiss::WARNING, and etiss::instr::BitArray::width().
OPCode() [3/6]
etiss::instr::OPCode::OPCode (const OPCode & cpy)
copy ctor
Definition at line 482 of file Instruction.cpp.
OPCode() [4/6]
template<typename T , typename = typename std::enable_if<std::is_integral<T>::value, T>::type> etiss::instr::OPCode::OPCode (unsigned width, const T code, const T mask) inline
ctor that uses integral values for mask and code
Attention
only if DEBUG is defined as non zero a warning message will be printed if the code doesn't fit the mask
Parameters
width width in bits
Definition at line 431 of file Instruction.h.
References etiss::log(), etiss::toString(), etiss::VERBOSE, and etiss::WARNING.
OPCode() [5/6]
etiss::instr::OPCode::OPCode (const BitArray & code, const BitArray & mask)
Attention
the width of code and mask MUST be equal
OPCode() [6/6]
etiss::instr::OPCode::OPCode (const OPCode & cpy)
copy ctor
Member Function Documentation
operator!=() [1/2]
bool etiss::instr::OPCode::operator!= (const OPCode & o) const inline
Definition at line 462 of file Instruction.h.
operator!=() [2/2]
bool etiss::instr::OPCode::operator!= (const OPCode & o) const inline
Definition at line 462 of file Instruction.h.
operator<() [1/2]
bool etiss::instr::OPCode::operator< (const OPCode & o) const
comparison operator for map/sets.
compares mask and code to provide some sort of order. has no further meaning.
operator<() [2/2]
bool etiss::instr::OPCode::operator< (const OPCode & o) const
comparison operator for map/sets.
compares mask and code to provide some sort of order. has no further meaning.
Definition at line 484 of file Instruction.cpp.
References code_, and mask_.
operator==() [1/2]
bool etiss::instr::OPCode::operator== (const OPCode & o) const inline
Definition at line 461 of file Instruction.h.
operator==() [2/2]
bool etiss::instr::OPCode::operator== (const OPCode & o) const inline
Definition at line 461 of file Instruction.h.
Member Data Documentation
code_
const BitArray etiss::instr::OPCode::code_
Definition at line 422 of file Instruction.h.
Referenced by OPCode(), and operator<().
mask_
const BitArray etiss::instr::OPCode::mask_
Definition at line 423 of file Instruction.h.
Referenced by OPCode(), and operator<().
The documentation for this class was generated from the following files:
include/etiss/Instruction.h
/home/runner/work/etiss/etiss/src/Instruction.cpp