ETISS 0.8.0: etiss::plugin::PrintInstruction Class Reference
etiss::plugin::PrintInstruction Class Reference
a simple plugin that prints the instruction and address when an instruction is executed
#include <PrintInstruction.h>
Public Member Functions
virtual void finalizeInstrSet (etiss::instr::ModedInstructionSet &) const
called after all instructions have been added to allow last changes
virtual void initCodeBlock (etiss::CodeBlock &block) const
called before instructions are translated for the code block
virtual std::string _getPluginName () const
virtual void * getPluginHandle ()
called to get the handle that is available in translated code via getPoinerCode(). [default: this]
virtual void finalizeInstrSet (etiss::instr::ModedInstructionSet &) const
called after all instructions have been added to allow last changes
virtual void initCodeBlock (etiss::CodeBlock &block) const
called before instructions are translated for the code block
virtual std::string _getPluginName () const
virtual void * getPluginHandle ()
called to get the handle that is available in translated code via getPoinerCode(). [default: this]
Public Member Functions inherited from etiss::TranslationPlugin
TranslationPlugin ()
virtual ~TranslationPlugin ()
virtual void initInstrSet (etiss::instr::ModedInstructionSet &) const
called to add instructions to the instruction set
virtual void finalizeCodeBlock (etiss::CodeBlock &) const
called after all instructions have been translated for the code block
TranslationPlugin ()
virtual ~TranslationPlugin ()
virtual void initInstrSet (etiss::instr::ModedInstructionSet &) const
called to add instructions to the instruction set
virtual void finalizeCodeBlock (etiss::CodeBlock &) const
called after all instructions have been translated for the code block
Public Member Functions inherited from etiss::Plugin
virtual ~Plugin ()
unsigned getType ()
InterruptListenerPlugin * getInterruptListenerPlugin ()
CoroutinePlugin * getCoroutinePlugin ()
SystemWrapperPlugin * getSystemWrapperPlugin ()
RegisterDevicePlugin * getRegisterDevicePlugin ()
TranslationPlugin * getTranslationPlugin ()
std::string getPluginName () const
const std::string & getLastAssignedCoreName ()
std::string toString () const
virtual ~Plugin ()
unsigned getType ()
InterruptListenerPlugin * getInterruptListenerPlugin ()
CoroutinePlugin * getCoroutinePlugin ()
SystemWrapperPlugin * getSystemWrapperPlugin ()
RegisterDevicePlugin * getRegisterDevicePlugin ()
TranslationPlugin * getTranslationPlugin ()
std::string getPluginName () const
const std::string & getLastAssignedCoreName ()
std::string toString () const
Public Member Functions inherited from etiss::ToString
ToString ()
virtual ~ToString ()
ToString ()
virtual ~ToString ()
Additional Inherited Members
Static Public Attributes inherited from etiss::Plugin
static const unsigned INTERRUPTLISTENER = 1 << 0
access to translated code
static const unsigned COROUTINE = 1 << 1
callback after execution of each translated block
static const unsigned SYSTEMWRAPPER = 1 << 2
can wrap/change ETISS_System structure at execution start
static const unsigned REGISTERDEVICE
gets noticed of changes to special registers (e.g. mmu register etc. [depends on architecture])
static const unsigned TRANSLATION
access to translated code during translation phase or when instruction tree is built
Protected Member Functions inherited from etiss::TranslationPlugin
std::string getPointerCode () const
returns a C code expression that allows to get or assign a pointer to the variable assigned to this translation plugin.
std::string getPointerCode () const
returns a C code expression that allows to get or assign a pointer to the variable assigned to this translation plugin.
Protected Member Functions inherited from etiss::Plugin
Plugin (unsigned type=0)
virtual void init (ETISS_CPU *cpu, ETISS_System *system, CPUArch *arch)
this function is called before the plugin is used in the cpu execution loop (etiss::CPUCore::execute).
virtual void cleanup ()
this function is called after cpu execution loop (etiss::CPUCore::execute) finished.
void setCorrespondingCPUCoreName (std::string name)
virtual void addedToCPUCore (etiss::CPUCore *core)
called as soon a plugin has been added to its CPUCore.
virtual void removedFromCPUCore (etiss::CPUCore *core)
called as soon a plugin has been removed from its CPUCore.
Plugin (unsigned type=0)
virtual void init (ETISS_CPU *cpu, ETISS_System *system, CPUArch *arch)
this function is called before the plugin is used in the cpu execution loop (etiss::CPUCore::execute).
virtual void cleanup ()
this function is called after cpu execution loop (etiss::CPUCore::execute) finished.
void setCorrespondingCPUCoreName (std::string name)
virtual void addedToCPUCore (etiss::CPUCore *core)
called as soon a plugin has been added to its CPUCore.
virtual void removedFromCPUCore (etiss::CPUCore *core)
called as soon a plugin has been removed from its CPUCore.
Protected Attributes inherited from etiss::Plugin
ETISS_CPU * plugin_cpu_
holds a pointer to the cpu structure. will be set before init call and after cleanup call
ETISS_System * plugin_system_
holds a pointer to the system structure.
CPUArch * plugin_arch_
holds a pointer to the CPUArch instance. will be set before init call and after cleanup call
CPUCore * plugin_core_
holds a pointer to the associated CPUCore instance.
Detailed Description
a simple plugin that prints the instruction and address when an instruction is executed
Definition at line 63 of file PrintInstruction.h.
Member Function Documentation
_getPluginName() [1/2]
std::string PrintInstruction::_getPluginName () const virtual
Implements etiss::Plugin.
Definition at line 98 of file PrintInstruction.cpp.
_getPluginName() [2/2]
virtual std::string etiss::plugin::PrintInstruction::_getPluginName () const virtual
Implements etiss::Plugin.
finalizeInstrSet() [1/2]
virtual void etiss::plugin::PrintInstruction::finalizeInstrSet (etiss::instr::ModedInstructionSet &) const virtual
called after all instructions have been added to allow last changes
Reimplemented from etiss::TranslationPlugin.
finalizeInstrSet() [2/2]
void PrintInstruction::finalizeInstrSet (etiss::instr::ModedInstructionSet &) const virtual
called after all instructions have been added to allow last changes
Reimplemented from etiss::TranslationPlugin.
Definition at line 68 of file PrintInstruction.cpp.
References etiss::instr::Instruction::addCallback(), etiss::CodeSet::append(), etiss::instr::InstructionContext::current_address_, etiss::instr::InstructionSet::foreach(), etiss::instr::VariableInstructionSet::foreach(), etiss::instr::ModedInstructionSet::foreach(), etiss::CodePart::PREINITIALDEBUGRETURNING, and etiss::instr::Instruction::printASM().
getPluginHandle() [1/2]
void * PrintInstruction::getPluginHandle () virtual
called to get the handle that is available in translated code via getPoinerCode(). [default: this]
Reimplemented from etiss::TranslationPlugin.
Definition at line 103 of file PrintInstruction.cpp.
getPluginHandle() [2/2]
virtual void* etiss::plugin::PrintInstruction::getPluginHandle () virtual
called to get the handle that is available in translated code via getPoinerCode(). [default: this]
Reimplemented from etiss::TranslationPlugin.
initCodeBlock() [1/2]
virtual void etiss::plugin::PrintInstruction::initCodeBlock (etiss::CodeBlock &) const virtual
called before instructions are translated for the code block
Reimplemented from etiss::TranslationPlugin.
initCodeBlock() [2/2]
void PrintInstruction::initCodeBlock (etiss::CodeBlock &) const virtual
called before instructions are translated for the code block
Reimplemented from etiss::TranslationPlugin.
Definition at line 63 of file PrintInstruction.cpp.
References etiss::CodeBlock::fileglobalCode().
The documentation for this class was generated from the following files:
include/etiss/IntegratedLibrary/PrintInstruction.h
/home/runner/work/etiss/etiss/src/IntegratedLibrary/PrintInstruction.cpp