ETISS 0.8.0: etiss::mm::PTEFormatBuilder Class Reference
etiss::mm::PTEFormatBuilder Class Reference
Sigleton builder utility to build up customized PTE format.
#include <PTEFormatBuilder.h>
Public Member Functions
PTEFormatBuilder & AddPPNBitField (uint32_t begin, uint32_t end)
Add mandatory bit field, Physical Page Number (PPN), for PTE.
PTEFormatBuilder & AddPageOffset (uint32_t begin, uint32_t end)
Add mandatory bit field for page size offset (Not included in PTE neither in PTE format)
PTEFormatBuilder & AddFlag (std::string name, uint32_t begin, uint32_t end)
Add optional bit field for protection flag in PTE.
PTEFormatBuilder & AddFlag (std::string name, uint32_t pos)
Add optional bit field for protection flag in PTE.
PTEFormatBuilder & AddPPNBitField (uint32_t begin, uint32_t end)
Add mandatory bit field, Physical Page Number (PPN), for PTE.
PTEFormatBuilder & AddPageOffset (uint32_t begin, uint32_t end)
Add mandatory bit field for page size offset (Not included in PTE neither in PTE format)
PTEFormatBuilder & AddFlag (std::string name, uint32_t begin, uint32_t end)
Add optional bit field for protection flag in PTE.
PTEFormatBuilder & AddFlag (std::string name, uint32_t pos)
Add optional bit field for protection flag in PTE.
Static Public Member Functions
static PTEFormatBuilder & Instance ()
Get the singleton instance.
static PTEFormatBuilder & Instance ()
Get the singleton instance.
Private Member Functions
PTEFormatBuilder (PTEFormat &format)
PTEFormatBuilder (PTEFormat &format)
Private Attributes
PTEFormat & format_
Friends
class PTEFormat
Detailed Description
Sigleton builder utility to build up customized PTE format.
Definition at line 62 of file PTEFormatBuilder.h.
Constructor & Destructor Documentation
PTEFormatBuilder() [1/2]
etiss::mm::PTEFormatBuilder::PTEFormatBuilder (PTEFormat & format) inline private
Definition at line 112 of file PTEFormatBuilder.h.
Referenced by Instance().
PTEFormatBuilder() [2/2]
etiss::mm::PTEFormatBuilder::PTEFormatBuilder (PTEFormat & format) inline private
Definition at line 112 of file PTEFormatBuilder.h.
Member Function Documentation
AddFlag() [1/4]
PTEFormatBuilder& etiss::mm::PTEFormatBuilder::AddFlag (std::string name, uint32_t begin, uint32_t end) inline
Add optional bit field for protection flag in PTE.
Definition at line 96 of file PTEFormatBuilder.h.
References etiss::mm::PTEFormat::AddBitField(), format_, and name.
AddFlag() [2/4]
PTEFormatBuilder& etiss::mm::PTEFormatBuilder::AddFlag (std::string name, uint32_t begin, uint32_t end) inline
Add optional bit field for protection flag in PTE.
Definition at line 96 of file PTEFormatBuilder.h.
References etiss::mm::PTEFormat::AddBitField(), format_, and name.
AddFlag() [3/4]
PTEFormatBuilder& etiss::mm::PTEFormatBuilder::AddFlag (std::string name, uint32_t pos) inline
Add optional bit field for protection flag in PTE.
Definition at line 105 of file PTEFormatBuilder.h.
References etiss::mm::PTEFormat::AddBitField(), format_, and name.
AddFlag() [4/4]
PTEFormatBuilder& etiss::mm::PTEFormatBuilder::AddFlag (std::string name, uint32_t pos) inline
Add optional bit field for protection flag in PTE.
Definition at line 105 of file PTEFormatBuilder.h.
References etiss::mm::PTEFormat::AddBitField(), format_, and name.
AddPageOffset() [1/2]
PTEFormatBuilder& etiss::mm::PTEFormatBuilder::AddPageOffset (uint32_t begin, uint32_t end) inline
Add mandatory bit field for page size offset (Not included in PTE neither in PTE format)
Definition at line 87 of file PTEFormatBuilder.h.
References etiss::mm::PTEFormat::AddBitField(), and format_.
AddPageOffset() [2/2]
PTEFormatBuilder& etiss::mm::PTEFormatBuilder::AddPageOffset (uint32_t begin, uint32_t end) inline
Add mandatory bit field for page size offset (Not included in PTE neither in PTE format)
Definition at line 87 of file PTEFormatBuilder.h.
References etiss::mm::PTEFormat::AddBitField(), and format_.
AddPPNBitField() [1/2]
PTEFormatBuilder& etiss::mm::PTEFormatBuilder::AddPPNBitField (uint32_t begin, uint32_t end) inline
Add mandatory bit field, Physical Page Number (PPN), for PTE.
Definition at line 77 of file PTEFormatBuilder.h.
References etiss::mm::PTEFormat::AddBitField(), and format_.
AddPPNBitField() [2/2]
PTEFormatBuilder& etiss::mm::PTEFormatBuilder::AddPPNBitField (uint32_t begin, uint32_t end) inline
Add mandatory bit field, Physical Page Number (PPN), for PTE.
Definition at line 77 of file PTEFormatBuilder.h.
References etiss::mm::PTEFormat::AddBitField(), and format_.
Instance() [1/2]
static PTEFormatBuilder& etiss::mm::PTEFormatBuilder::Instance () inline static
Get the singleton instance.
Definition at line 68 of file PTEFormatBuilder.h.
References etiss::mm::PTEFormat::Instance(), and PTEFormatBuilder().
Instance() [2/2]
static PTEFormatBuilder& etiss::mm::PTEFormatBuilder::Instance () inline static
Get the singleton instance.
Definition at line 68 of file PTEFormatBuilder.h.
References etiss::mm::PTEFormat::Instance(), and PTEFormatBuilder().
Friends And Related Function Documentation
PTEFormat
PTEFormat friend
Definition at line 116 of file PTEFormatBuilder.h.
Member Data Documentation
format_
PTEFormat & etiss::mm::PTEFormatBuilder::format_ private
Definition at line 114 of file PTEFormatBuilder.h.
Referenced by AddFlag(), AddPageOffset(), and AddPPNBitField().
The documentation for this class was generated from the following file:
include/etiss/mm/PTEFormatBuilder.h