ETISS 0.8.0: etiss::RegisterSet Class Reference
etiss::RegisterSet Class Reference
set of register parts.
#include <CodePart.h>
Classes
struct lex_compare
special comparison function that only takes register name into account.
Public Member Functions
RegisterSet ()
RegisterSet (const RegisterSet &rs)
void add (const RegisterPart &rp)
add a registerPart to the set or just its relevant bits if a register with the same name is already present
void add (const std::string &name, unsigned registerWidth, etiss::uintMax bits=(uintMax)((intMax) -1))
void applyShadow (const RegisterSet &rs)
any register bits set in the passed RegisterSet won't be set in this RegisterSet
void merge (const RegisterSet &rs)
any register bits set in the passed RegisterSet will be set in this RegisterSet (plus previously set bits)
void intersect (const RegisterSet &rs)
only register bits set in this AND the passed RegisterSet remain set in this RegisterSet
bool disjoint (const RegisterSet &rs) const
bool maskedBy (const RegisterSet &rs) const
bool isEmpty ()
void clear ()
std::string _dbg_print () const
writes a human readable string listing all set bit of every register in this RegisterSet
RegisterSet ()
RegisterSet (const RegisterSet &rs)
void add (const RegisterPart &rp)
add a registerPart to the set or just its relevant bits if a register with the same name is already present
void add (const std::string &name, unsigned registerWidth, etiss::uintMax bits=(uintMax)((intMax) -1))
void applyShadow (const RegisterSet &rs)
any register bits set in the passed RegisterSet won't be set in this RegisterSet
void merge (const RegisterSet &rs)
any register bits set in the passed RegisterSet will be set in this RegisterSet (plus previously set bits)
void intersect (const RegisterSet &rs)
only register bits set in this AND the passed RegisterSet remain set in this RegisterSet
bool disjoint (const RegisterSet &rs) const
bool maskedBy (const RegisterSet &rs) const
bool isEmpty ()
void clear ()
std::string _dbg_print () const
writes a human readable string listing all set bit of every register in this RegisterSet
Private Attributes
std::set< RegisterPart, lex_compare > set_
Detailed Description
set of register parts.
each register contained in a set has a different name.
Definition at line 200 of file CodePart.h.
Constructor & Destructor Documentation
RegisterSet() [1/4]
etiss::RegisterSet::RegisterSet () inline
Definition at line 216 of file CodePart.h.
RegisterSet() [2/4]
etiss::RegisterSet::RegisterSet (const RegisterSet & rs) inline
Definition at line 217 of file CodePart.h.
References set_.
RegisterSet() [3/4]
etiss::RegisterSet::RegisterSet () inline
Definition at line 216 of file CodePart.h.
RegisterSet() [4/4]
etiss::RegisterSet::RegisterSet (const RegisterSet & rs) inline
Definition at line 217 of file CodePart.h.
References set_.
Member Function Documentation
_dbg_print() [1/2]
std::string etiss::RegisterSet::_dbg_print () const inline
writes a human readable string listing all set bit of every register in this RegisterSet
Definition at line 361 of file CodePart.h.
References set_.
_dbg_print() [2/2]
std::string etiss::RegisterSet::_dbg_print () const inline
writes a human readable string listing all set bit of every register in this RegisterSet
Definition at line 361 of file CodePart.h.
References set_.
add() [1/4]
void etiss::RegisterSet::add (const RegisterPart & rp) inline
add a registerPart to the set or just its relevant bits if a register with the same name is already present
Definition at line 222 of file CodePart.h.
References etiss::RegisterPart::isEmpty(), and set_.
Referenced by add(), l_addsubX(), l_ext(), l_sf(), loadinstr(), merge(), OR1K_l_muluX(), OR1K_l_mulX(), shift(), simple_op_rDAB(), simple_op_rDAI(), and update_pc().
add() [2/4]
void etiss::RegisterSet::add (const RegisterPart & rp) inline
add a registerPart to the set or just its relevant bits if a register with the same name is already present
Definition at line 222 of file CodePart.h.
References set_.
add() [3/4]
void etiss::RegisterSet::add (const std::string & name, unsigned registerWidth, etiss::uintMax bits = (uintMax)((intMax)-1)) inline
See also
add(const RegisterPart & rp)
Definition at line 243 of file CodePart.h.
References add(), and name.
add() [4/4]
void etiss::RegisterSet::add (const std::string & name, unsigned registerWidth, etiss::uintMax bits = (uintMax)((intMax)-1)) inline
See also
add(const RegisterPart & rp)
Definition at line 243 of file CodePart.h.
References add(), and name.
applyShadow() [1/2]
void etiss::RegisterSet::applyShadow (const RegisterSet & rs) inline
any register bits set in the passed RegisterSet won't be set in this RegisterSet
Definition at line 250 of file CodePart.h.
References set_.
Referenced by etiss::CodeSet::writeCodeParts().
applyShadow() [2/2]
void etiss::RegisterSet::applyShadow (const RegisterSet & rs) inline
any register bits set in the passed RegisterSet won't be set in this RegisterSet
Definition at line 250 of file CodePart.h.
References set_.
clear() [1/2]
void etiss::RegisterSet::clear () inline
Definition at line 357 of file CodePart.h.
References set_.
Referenced by etiss::CodeSet::writeCodeParts().
clear() [2/2]
void etiss::RegisterSet::clear () inline
Definition at line 357 of file CodePart.h.
References set_.
disjoint() [1/2]
bool etiss::RegisterSet::disjoint (const RegisterSet & rs) const inline
Returns
true if no register in this set is in the passed RegisterSet
Definition at line 318 of file CodePart.h.
References set_.
disjoint() [2/2]
bool etiss::RegisterSet::disjoint (const RegisterSet & rs) const inline
Returns
true if no register in this set is in the passed RegisterSet
Definition at line 318 of file CodePart.h.
References set_.
intersect() [1/2]
void etiss::RegisterSet::intersect (const RegisterSet & rs) inline
only register bits set in this AND the passed RegisterSet remain set in this RegisterSet
Definition at line 291 of file CodePart.h.
References set_.
Referenced by etiss::CodeSet::writeCodeParts().
intersect() [2/2]
void etiss::RegisterSet::intersect (const RegisterSet & rs) inline
only register bits set in this AND the passed RegisterSet remain set in this RegisterSet
Definition at line 291 of file CodePart.h.
References set_.
isEmpty() [1/2]
bool etiss::RegisterSet::isEmpty () inline
Definition at line 356 of file CodePart.h.
References set_.
isEmpty() [2/2]
bool etiss::RegisterSet::isEmpty () inline
Definition at line 356 of file CodePart.h.
References set_.
maskedBy() [1/2]
bool etiss::RegisterSet::maskedBy (const RegisterSet & rs) const inline
Returns
true if any bit set in this RegisterSet is also set in the passed RegisterSet
Definition at line 335 of file CodePart.h.
References set_.
maskedBy() [2/2]
bool etiss::RegisterSet::maskedBy (const RegisterSet & rs) const inline
Returns
true if any bit set in this RegisterSet is also set in the passed RegisterSet
Definition at line 335 of file CodePart.h.
References set_.
merge() [1/2]
void etiss::RegisterSet::merge (const RegisterSet & rs) inline
any register bits set in the passed RegisterSet will be set in this RegisterSet (plus previously set bits)
Definition at line 279 of file CodePart.h.
References add(), and set_.
Referenced by etiss::CodeSet::writeCodeParts().
merge() [2/2]
void etiss::RegisterSet::merge (const RegisterSet & rs) inline
any register bits set in the passed RegisterSet will be set in this RegisterSet (plus previously set bits)
Definition at line 279 of file CodePart.h.
References add().
Member Data Documentation
set_
std::set< RegisterPart, lex_compare > etiss::RegisterSet::set_ private
Definition at line 374 of file CodePart.h.
Referenced by _dbg_print(), add(), applyShadow(), clear(), disjoint(), intersect(), isEmpty(), maskedBy(), merge(), and RegisterSet().
The documentation for this class was generated from the following file:
include/etiss/CodePart.h