ETISS 0.8.0: etiss::VirtualStruct Class Reference
etiss::VirtualStruct Class Reference
abstract representation of an module of a simulation which could be a embedded device of the cpu of an embedded device.
#include <VirtualStruct.h>
Classes
class Field
a Field instance represents e.g.
class FieldT
Public Member Functions
virtual ~VirtualStruct ()
bool addField (Field *f, bool noerrorprint=false)
template<typename structT , typename retT , retT structT::* field>
bool addField (const std::string &name, const std::string &prettyname="", bool noerrorprint=false)
add a structure field to this VirtualStructure
template<typename T >
bool addField (const std::string &name, const std::string &prettyname, std::function< T()> read, std::function< void(T)> write, bool supportsListener=false, bool noerrorprint=false)
std::shared_ptr< Field > findName (const std::string &name) const
std::shared_ptr< Field > findPrettyName (const std::string &name) const
void foreachField (const std::function< void(std::shared_ptr< Field >)> &func)
bool mountStruct (const std::string &name, const std::shared_ptr< VirtualStruct > vs)
std::shared_ptr< VirtualStruct > findStruct (const std::string &name)
void foreachStruct (const std::function< void(const std::string &name, VirtualStruct &vs)> &func)
void close ()
bool isClosed ()
virtual std::list< std::string > listFields ()
list all fields directly reachable by this injector
virtual std::list< std::string > listSubInjectors ()
list all sub injectors.
virtual std::shared_ptr< etiss::fault::Injector > getSubInjector (const std::string &name)
get a sub injector.
virtual std::shared_ptr< etiss::fault::Injector > getParentInjector ()
get a the parent injector (root returns 0).
virtual bool acceleratedTrigger (const etiss::fault::Trigger &, int32_t fault_id)
std::shared_ptr< VirtualStruct > getVirtualStruct (const std::string &path)
std::shared_ptr< VirtualStruct::Field > getResolvedField (const std::string &path)
virtual ~VirtualStruct ()
bool addField (Field *f, bool noerrorprint=false)
template<typename structT , typename retT , retT structT::* field>
bool addField (const std::string &name, const std::string &prettyname="", bool noerrorprint=false)
add a structure field to this VirtualStructure
template<typename T >
bool addField (const std::string &name, const std::string &prettyname, std::function< T()> read, std::function< void(T)> write, bool supportsListener=false, bool noerrorprint=false)
std::shared_ptr< Field > findName (const std::string &name) const
std::shared_ptr< Field > findPrettyName (const std::string &name) const
void foreachField (const std::function< void(std::shared_ptr< Field >)> &func)
bool mountStruct (const std::string &name, const std::shared_ptr< VirtualStruct > vs)
std::shared_ptr< VirtualStruct > findStruct (const std::string &name)
void foreachStruct (const std::function< void(const std::string &name, VirtualStruct &vs)> &func)
void close ()
bool isClosed ()
virtual std::list< std::string > listFields ()
list all fields directly reachable by this injector
virtual std::list< std::string > listSubInjectors ()
list all sub injectors.
virtual std::shared_ptr< etiss::fault::Injector > getSubInjector (const std::string &name)
get a sub injector.
virtual std::shared_ptr< etiss::fault::Injector > getParentInjector ()
get a the parent injector (root returns 0).
virtual bool acceleratedTrigger (const etiss::fault::Trigger &, int32_t fault_id)
std::shared_ptr< VirtualStruct > getVirtualStruct (const std::string &path)
std::shared_ptr< VirtualStruct::Field > getResolvedField (const std::string &path)
Public Member Functions inherited from etiss::fault::Injector
Injector ()
virtual ~Injector ()
virtual bool needsCallbacks ()
virtual bool cycleAccurateCallback (uint64_t time_ps)
virtual bool instructionAccurateCallback (uint64_t time_ps)
virtual void freeFastFieldAccessPtr (void *)
MUST be called to cleanup a pointer acquired with fastFieldAccessPtr() default implementation is nop.
virtual std::string getInjectorPath ()
returns the path of the current object.
void addTrigger (const Trigger &t, int32_t fault_id)
> Triggers to look at in callbacks
Injector ()
virtual ~Injector ()
virtual bool needsCallbacks ()
virtual bool cycleAccurateCallback (uint64_t time_ps)
virtual bool instructionAccurateCallback (uint64_t time_ps)
virtual void freeFastFieldAccessPtr (void *)
MUST be called to cleanup a pointer acquired with fastFieldAccessPtr() default implementation is nop.
virtual std::string getInjectorPath ()
returns the path of the current object.
void addTrigger (const Trigger &t, int32_t fault_id)
> Triggers to look at in callbacks
Static Public Member Functions
static std::shared_ptr< VirtualStruct > allocate (void *structure, std::function< void(Field *)> delete_)
static std::shared_ptr< VirtualStruct > root ()
static std::shared_ptr< VirtualStruct > allocateFromC (void *handle, VirtualStruct_names names, VirtualStruct_prettyNames prettyNames_optional, VirtualStruct_read read_recommended, VirtualStruct_write write_optional, VirtualStruct_setListenerCallback setListenerCallback_optional, std::function< void(void *handle)> cleanup)
implemented in CVirtualStruct.cpp
static std::shared_ptr< VirtualStruct > allocate (void *structure, std::function< void(Field *)> delete_)
static std::shared_ptr< VirtualStruct > root ()
static std::shared_ptr< VirtualStruct > allocateFromC (void *handle, VirtualStruct_names names, VirtualStruct_prettyNames prettyNames_optional, VirtualStruct_read read_recommended, VirtualStruct_write write_optional, VirtualStruct_setListenerCallback setListenerCallback_optional, std::function< void(void *handle)> cleanup)
implemented in CVirtualStruct.cpp
Static Public Member Functions inherited from etiss::fault::Injector
static ptr get (const std::string &injectorPath)
static ptr get (const std::string &injectorPath)
Public Attributes
std::function< bool(const etiss::fault::Fault &, const etiss::fault::Action &, std::string &)> applyCustomAction
set this function to handle custom commands passed by etiss::fault::Action of the type etiss::fault::Action::COMMAND
void *const structure_
std::function< bool(const etiss::fault::Trigger &, int32_t)> acceleratedTrigger_
Protected Member Functions
virtual void * fastFieldAccessPtr (const std::string &name, std::string &errormsg)
virtual bool readField (void *fastfieldaccessptr, uint64_t &val, std::string &errormsg)
read the value of a field
virtual bool applyAction (const etiss::fault::Fault &fault, const etiss::fault::Action &action, std::string &errormsg)
virtual void * fastFieldAccessPtr (const std::string &name, std::string &errormsg)
virtual bool readField (void *fastfieldaccessptr, uint64_t &val, std::string &errormsg)
read the value of a field
virtual bool applyAction (const etiss::fault::Fault &fault, const etiss::fault::Action &action, std::string &errormsg)
Private Member Functions
VirtualStruct (void *structure, std::function< void(Field *)> dtor=[](Field *f) { delete f;})
VirtualStruct (void *structure, std::function< void(Field *)> dtor=[](Field *f) { delete f;})
Private Attributes
std::list< Field * > fields_
std::map< std::string, Field * > fieldNames_
std::map< std::string, Field * > fieldPrettyNames_
std::map< std::string, std::weak_ptr< VirtualStruct > > subStructs_
std::function< void(Field *)> dtor_
bool closed
std::shared_ptr< VirtualStruct > parent_
Friends
class VSSync
Additional Inherited Members
Public Types inherited from etiss::fault::Injector
typedef Injector * ptr
typedef Injector * ptr
Detailed Description
abstract representation of an module of a simulation which could be a embedded device of the cpu of an embedded device.
it is recommended to model and address the full hardware hirachy. e.g.
 device1
            -> cpu
                -> cache
            -> bus
            -> memory
                -> bank1
                -> bank2
        example address: "device1::cpu::cache"
To resolve a path to a VirtualStruct use VirtualStruct::root()->getVirtualStruct("device1::cpu::cache");
Fields of a VirtualStruct can be addressed by appending ".FIELDNAME" to the pass and pass it to getResolvedField(). e.g. VirtualStruct::root()->getResolvedField("device1::cpu::cache.tag1");
Syntax (Wirth syntax notation):
    module_path_to_field:   module_path "." { ASCII-character }
    module_path:            module_name { "::" module_name } .
    module_name:            letter { digit | letter } .
    letter:                 "a" | "A" | "b" | "B" | ... | "z" | "Z" .
    digit:                  "0" | "1" | "2" | "3" | "4" | "5" | "6" | 7" | "8" |
"9" .
    module_path_to_field is the full path to a field.
    module_path is always relative to the current module
EXTENSION for absolute paths:
    absolute_module_path_to_field:  "::" module_path_to_field
    absolute_module_path:           "::" module_path .
    absolute module path will NOT use root()!
        it will traverse from the current module upward until no parent exists
and then the path will be resolved
the tree of modules uses weak/shared pointers to create a tree that will clean itself up as soon as possible depending on the lifetime of the virtual structs that were associated with said module.
weak reference: –> (x holds a weak reference to y [x.weak_ptr = y]) strong reference: x -> y (x holds a strong reference to y [x.shared_ptr = y])
Relations:
    VirtualStruct
        --> <- VirtualStruct
            --> <- VirtualStruct
    VirtualStruct holds a weak reference to child VirtualStructs and a child VirtualStruct holds a strong reference to
VirtualStruct. Module holds a weak reference to a child Module and a child Module holds a strong reference to parent
Module VirtualStructs are deleted if the original shared_ptr is deleted, there is no child and there is no shared_ptr to
a field
Attention
: while VirtualStruct won't throw exceptions by itself, VirtualStruct::Field will throw exception upon invalid access or if the associated VirtualStruct has been closed
Definition at line 139 of file VirtualStruct.h.
Constructor & Destructor Documentation
VirtualStruct() [1/2]
etiss::VirtualStruct::VirtualStruct (void * structure, std::function< void(Field *)> dtor = [](Field *f) { delete f; }) private
Definition at line 232 of file VirtualStruct.cpp.
Referenced by allocate().
~VirtualStruct() [1/2]
etiss::VirtualStruct::~VirtualStruct () virtual
Definition at line 236 of file VirtualStruct.cpp.
References close(), dtor_, etiss::ERROR, fields_, and etiss::log().
VirtualStruct() [2/2]
etiss::VirtualStruct::VirtualStruct (void * structure, std::function< void(Field *)> dtor = [](Field *f) { delete f;}) private
~VirtualStruct() [2/2]
virtual etiss::VirtualStruct::~VirtualStruct () virtual
Member Function Documentation
acceleratedTrigger() [1/2]
bool etiss::VirtualStruct::acceleratedTrigger (const etiss::fault::Trigger & t, int32_t fault_id) virtual
Reimplemented from etiss::fault::Injector.
Definition at line 341 of file VirtualStruct.cpp.
References acceleratedTrigger_.
acceleratedTrigger() [2/2]
virtual bool etiss::VirtualStruct::acceleratedTrigger (const etiss::fault::Trigger & , int32_t fault_id) virtual
Reimplemented from etiss::fault::Injector.
addField() [1/6]
template<typename T > bool etiss::VirtualStruct::addField (const std::string & name, const std::string & prettyname, std::function< T()> read, std::function< void(T)> write, bool supportsListener = false, bool noerrorprint = false) inline
Definition at line 328 of file VirtualStruct.h.
References addField(), etiss::VirtualStruct::Field::L, name, etiss::VirtualStruct::Field::R, supportsListener(), v, and etiss::VirtualStruct::Field::W.
addField() [2/6]
template<typename T > bool etiss::VirtualStruct::addField (const std::string & name, const std::string & prettyname, std::function< T()> read, std::function< void(T)> write, bool supportsListener = false, bool noerrorprint = false) inline
Definition at line 328 of file VirtualStruct.h.
References addField(), etiss::VirtualStruct::Field::L, name, etiss::VirtualStruct::Field::R, supportsListener(), v, and etiss::VirtualStruct::Field::W.
addField() [3/6]
template<typename structT , typename retT , retT structT::* field> bool etiss::VirtualStruct::addField (const std::string & name, const std::string & prettyname = "", bool noerrorprint = false) inline
add a structure field to this VirtualStructure
Definition at line 313 of file VirtualStruct.h.
References addField(), and name.
addField() [4/6]
template<typename structT , typename retT , retT structT::* field> bool etiss::VirtualStruct::addField (const std::string & name, const std::string & prettyname = "", bool noerrorprint = false) inline
add a structure field to this VirtualStructure
Definition at line 313 of file VirtualStruct.h.
References addField(), and name.
addField() [5/6]
bool etiss::VirtualStruct::addField (VirtualStruct::Field * f, bool noerrorprint = false)
Definition at line 264 of file VirtualStruct.cpp.
References etiss::ERROR, ETISS_SRCLOC, fieldNames_, fieldPrettyNames_, fields_, etiss::log(), etiss::VirtualStruct::Field::name_, etiss::VirtualStruct::Field::prettyname_, and etiss::VERBOSE.
Referenced by addField().
addField() [6/6]
bool etiss::VirtualStruct::addField (Field * f, bool noerrorprint = false)
allocate() [1/2]
std::shared_ptr< VirtualStruct > etiss::VirtualStruct::allocate (void * structure, std::function< void(Field *)> delete_) static
Definition at line 596 of file VirtualStruct.cpp.
References VirtualStruct().
Referenced by allocateFromC(), RISCVArch::getVirtualStruct(), RISCV64Arch::getVirtualStruct(), OR1KArch::getVirtualStruct(), and root().
allocate() [2/2]
static std::shared_ptr<VirtualStruct> etiss::VirtualStruct::allocate (void * structure, std::function< void(Field *)> delete_) static
allocateFromC() [1/2]
std::shared_ptr< VirtualStruct > etiss::VirtualStruct::allocateFromC (void * handle, VirtualStruct_names names, VirtualStruct_prettyNames prettyNames_optional, VirtualStruct_read read_recommended, VirtualStruct_write write_optional, VirtualStruct_setListenerCallback setListenerCallback_optional, std::function< void(void *handle)> cleanup) static
implemented in CVirtualStruct.cpp
TODO
Definition at line 69 of file CVirtualStruct.cpp.
References allocate(), etiss::ERROR, etiss::VirtualStruct::Field::L, etiss::log(), name, etiss::VirtualStruct::Field::P, etiss::parseName(), etiss::VirtualStruct::Field::R, and etiss::VirtualStruct::Field::W.
allocateFromC() [2/2]
static std::shared_ptr<VirtualStruct> etiss::VirtualStruct::allocateFromC (void * handle, VirtualStruct_names names, VirtualStruct_prettyNames prettyNames_optional, VirtualStruct_read read_recommended, VirtualStruct_write write_optional, VirtualStruct_setListenerCallback setListenerCallback_optional, std::function< void(void *handle)> cleanup) static
implemented in CVirtualStruct.cpp
applyAction() [1/2]
bool etiss::VirtualStruct::applyAction (const etiss::fault::Fault & fault, const etiss::fault::Action & action, std::string & errormsg) protected virtual
Returns
true if action could be applied
Attention
MUST NOT be called from without the callback functions cycleAccurateCallback() and instructionAccurateCallback(). The assumption of a singlethreaded access/use of these functions MUST hold.
Implements etiss::fault::Injector.
Definition at line 464 of file VirtualStruct.cpp.
References etiss::VirtualStruct::Field::A, etiss::VirtualStruct::Field::applyAction(), etiss::VirtualStruct::Field::applyBitflip(), applyCustomAction, etiss::fault::Action::BITFLIP, etiss::fault::Action::COMMAND, etiss::VirtualStruct::Field::F, fieldNames_, fieldPrettyNames_, etiss::VirtualStruct::Field::flags_, etiss::fault::Injector::getInjectorPath(), etiss::fault::Action::getTargetBit(), etiss::fault::Action::getTargetField(), etiss::fault::Action::getType(), and etiss::fault::Fault::id_.
applyAction() [2/2]
virtual bool etiss::VirtualStruct::applyAction (const etiss::fault::Fault & fault, const etiss::fault::Action & action, std::string & errormsg) protected virtual
Returns
true if action could be applied
Attention
MUST NOT be called from without the callback functions cycleAccurateCallback() and instructionAccurateCallback(). The assumption of a singlethreaded access/use of these functions MUST hold.
Implements etiss::fault::Injector.
close() [1/2]
void etiss::VirtualStruct::close ()
close() [2/2]
void etiss::VirtualStruct::close ()
Definition at line 396 of file VirtualStruct.cpp.
References closed.
Referenced by ~VirtualStruct().
fastFieldAccessPtr() [1/2]
void * etiss::VirtualStruct::fastFieldAccessPtr (const std::string & name, std::string & errormsg) protected virtual
Attention
MUST NOT be called from without the callback functions cycleAccurateCallback() and instructionAccurateCallback(). The assumption of a singlethreaded access/use of these functions MUST hold.
Returns
0 in case of failure. otherwise an internal pointer shall be retuned that allows to access a field in a quick manner. freefastFieldAccessPtr MUST be called after use.
Implements etiss::fault::Injector.
Definition at line 433 of file VirtualStruct.cpp.
References fieldNames_, fieldPrettyNames_, and name.
fastFieldAccessPtr() [2/2]
virtual void* etiss::VirtualStruct::fastFieldAccessPtr (const std::string & name, std::string & errormsg) protected virtual
Attention
MUST NOT be called from without the callback functions cycleAccurateCallback() and instructionAccurateCallback(). The assumption of a singlethreaded access/use of these functions MUST hold.
Returns
0 in case of failure. otherwise an internal pointer shall be retuned that allows to access a field in a quick manner. freefastFieldAccessPtr MUST be called after use.
Implements etiss::fault::Injector.
findName() [1/2]
std::shared_ptr< VirtualStruct::Field > etiss::VirtualStruct::findName (const std::string & name) const
Definition at line 303 of file VirtualStruct.cpp.
References closed, fieldNames_, and name.
Referenced by etiss::copy().
findName() [2/2]
std::shared_ptr<Field> etiss::VirtualStruct::findName (const std::string & name) const
findPrettyName() [1/2]
std::shared_ptr< VirtualStruct::Field > etiss::VirtualStruct::findPrettyName (const std::string & name) const
Definition at line 317 of file VirtualStruct.cpp.
References closed, fieldPrettyNames_, and name.
findPrettyName() [2/2]
std::shared_ptr<Field> etiss::VirtualStruct::findPrettyName (const std::string & name) const
findStruct() [1/2]
std::shared_ptr<VirtualStruct> etiss::VirtualStruct::findStruct (const std::string & name)
findStruct() [2/2]
std::shared_ptr< VirtualStruct > etiss::VirtualStruct::findStruct (const std::string & name)
Definition at line 374 of file VirtualStruct.cpp.
References name, and subStructs_.
Referenced by getSubInjector().
foreachField() [1/2]
void etiss::VirtualStruct::foreachField (const std::function< void(std::shared_ptr< Field >)> & func)
Definition at line 330 of file VirtualStruct.cpp.
References closed, and fields_.
Referenced by etiss::copy(), and listFields().
foreachField() [2/2]
void etiss::VirtualStruct::foreachField (const std::function< void(std::shared_ptr< Field >)> & func)
foreachStruct() [1/2]
void etiss::VirtualStruct::foreachStruct (const std::function< void(const std::string &name, VirtualStruct &vs)> & func)
Definition at line 382 of file VirtualStruct.cpp.
References subStructs_.
Referenced by listSubInjectors().
foreachStruct() [2/2]
void etiss::VirtualStruct::foreachStruct (const std::function< void(const std::string &name, VirtualStruct &vs)> & func)
getParentInjector() [1/2]
virtual std::shared_ptr<etiss::fault::Injector> etiss::VirtualStruct::getParentInjector () virtual
get a the parent injector (root returns 0).
in case of c++11 this function returns a smart pointer (std::shared_ptr<Injector>)
See also
etiss::VirtualStruct for example implemention
Implements etiss::fault::Injector.
getParentInjector() [2/2]
std::shared_ptr< etiss::fault::Injector > etiss::VirtualStruct::getParentInjector () virtual
get a the parent injector (root returns 0).
in case of c++11 this function returns a smart pointer (std::shared_ptr<Injector>)
See also
etiss::VirtualStruct for example implemention
Implements etiss::fault::Injector.
Definition at line 428 of file VirtualStruct.cpp.
References parent_.
getResolvedField() [1/2]
std::shared_ptr<VirtualStruct::Field> etiss::VirtualStruct::getResolvedField (const std::string & path)
getResolvedField() [2/2]
std::shared_ptr< VirtualStruct::Field > etiss::VirtualStruct::getResolvedField (const std::string & path)
Definition at line 660 of file VirtualStruct.cpp.
References getVirtualStruct().
getSubInjector() [1/2]
virtual std::shared_ptr<etiss::fault::Injector> etiss::VirtualStruct::getSubInjector (const std::string & name) virtual
get a sub injector.
in case of c++11 this function returns a smart pointer (std::shared_ptr<Injector>)
See also
etiss::VirtualStruct for example implemention
Implements etiss::fault::Injector.
getSubInjector() [2/2]
std::shared_ptr< etiss::fault::Injector > etiss::VirtualStruct::getSubInjector (const std::string & name) virtual
get a sub injector.
in case of c++11 this function returns a smart pointer (std::shared_ptr<Injector>)
See also
etiss::VirtualStruct for example implemention
Implements etiss::fault::Injector.
Definition at line 424 of file VirtualStruct.cpp.
References findStruct(), and name.
getVirtualStruct() [1/2]
std::shared_ptr< VirtualStruct > etiss::VirtualStruct::getVirtualStruct (const std::string & path)
Definition at line 609 of file VirtualStruct.cpp.
References parent_, and subStructs_.
Referenced by getResolvedField().
getVirtualStruct() [2/2]
std::shared_ptr<VirtualStruct> etiss::VirtualStruct::getVirtualStruct (const std::string & path)
isClosed() [1/2]
bool etiss::VirtualStruct::isClosed ()
isClosed() [2/2]
bool etiss::VirtualStruct::isClosed ()
Definition at line 402 of file VirtualStruct.cpp.
References closed.
listFields() [1/2]
virtual std::list<std::string> etiss::VirtualStruct::listFields () virtual
list all fields directly reachable by this injector
See also
etiss::VirtualStruct for example implemention
Implements etiss::fault::Injector.
listFields() [2/2]
std::list< std::string > etiss::VirtualStruct::listFields () virtual
list all fields directly reachable by this injector
See also
etiss::VirtualStruct for example implemention
Implements etiss::fault::Injector.
Definition at line 408 of file VirtualStruct.cpp.
References foreachField(), and etiss::VirtualStruct::Field::name_.
listSubInjectors() [1/2]
std::list< std::string > etiss::VirtualStruct::listSubInjectors () virtual
list all sub injectors.
See also
etiss::VirtualStruct for example implemention
Implements etiss::fault::Injector.
Definition at line 417 of file VirtualStruct.cpp.
References foreachStruct(), and name.
listSubInjectors() [2/2]
virtual std::list<std::string> etiss::VirtualStruct::listSubInjectors () virtual
list all sub injectors.
See also
etiss::VirtualStruct for example implemention
Implements etiss::fault::Injector.
mountStruct() [1/2]
bool etiss::VirtualStruct::mountStruct (const std::string & name, const std::shared_ptr< VirtualStruct > vs)
mountStruct() [2/2]
bool etiss::VirtualStruct::mountStruct (const std::string & name, const std::shared_ptr< VirtualStruct > vs)
Definition at line 352 of file VirtualStruct.cpp.
References name, and subStructs_.
readField() [1/2]
bool etiss::VirtualStruct::readField (void * fastfieldaccessptr, uint64_t & val, std::string & errormsg) protected virtual
read the value of a field
Returns
true if read succeded
Attention
MUST NOT be called from outside the callback functions cycleAccurateCallback() and instructionAccurateCallback(). The assumption of a singlethreaded access/use of these functions MUST hold.
Implements etiss::fault::Injector.
Definition at line 448 of file VirtualStruct.cpp.
References etiss::VirtualStruct::Field::flags_, etiss::VirtualStruct::Field::R, and etiss::VirtualStruct::Field::read().
readField() [2/2]
virtual bool etiss::VirtualStruct::readField (void * fastfieldaccessptr, uint64_t & val, std::string & errormsg) protected virtual
read the value of a field
Returns
true if read succeded
Attention
MUST NOT be called from outside the callback functions cycleAccurateCallback() and instructionAccurateCallback(). The assumption of a singlethreaded access/use of these functions MUST hold.
Implements etiss::fault::Injector.
root() [1/2]
static std::shared_ptr<VirtualStruct> etiss::VirtualStruct::root () static
root() [2/2]
std::shared_ptr< VirtualStruct > etiss::VirtualStruct::root () static
Definition at line 603 of file VirtualStruct.cpp.
References allocate().
Referenced by etiss::fault::Injector::get().
Friends And Related Function Documentation
VSSync
VSSync friend
Definition at line 141 of file VirtualStruct.h.
Member Data Documentation
acceleratedTrigger_
std::function< bool(const etiss::fault::Trigger &, int32_t)> etiss::VirtualStruct::acceleratedTrigger_
Definition at line 380 of file VirtualStruct.h.
Referenced by acceleratedTrigger().
applyCustomAction
std::function< bool(const etiss::fault::Fault &, const etiss::fault::Action &, std::string &)> etiss::VirtualStruct::applyCustomAction
set this function to handle custom commands passed by etiss::fault::Action of the type etiss::fault::Action::COMMAND
Definition at line 376 of file VirtualStruct.h.
Referenced by applyAction().
closed
bool etiss::VirtualStruct::closed private
Definition at line 388 of file VirtualStruct.h.
Referenced by close(), findName(), findPrettyName(), foreachField(), and isClosed().
dtor_
std::function< void(Field *)> etiss::VirtualStruct::dtor_ private
Definition at line 387 of file VirtualStruct.h.
Referenced by ~VirtualStruct().
fieldNames_
std::map< std::string, Field * > etiss::VirtualStruct::fieldNames_ private
Definition at line 384 of file VirtualStruct.h.
Referenced by addField(), applyAction(), fastFieldAccessPtr(), and findName().
fieldPrettyNames_
std::map< std::string, Field * > etiss::VirtualStruct::fieldPrettyNames_ private
Definition at line 385 of file VirtualStruct.h.
Referenced by addField(), applyAction(), fastFieldAccessPtr(), and findPrettyName().
fields_
std::list< Field * > etiss::VirtualStruct::fields_ private
Definition at line 383 of file VirtualStruct.h.
Referenced by addField(), foreachField(), and ~VirtualStruct().
parent_
std::shared_ptr< VirtualStruct > etiss::VirtualStruct::parent_ private
Definition at line 391 of file VirtualStruct.h.
Referenced by getParentInjector(), and getVirtualStruct().
structure_
void *const etiss::VirtualStruct::structure_
Definition at line 379 of file VirtualStruct.h.
Referenced by etiss::VirtualStruct::FieldT< structT, retT, field >::_read(), PPCField::_read(), NPCField::_read(), SRField::_read(), etiss::VirtualStruct::FieldT< structT, retT, field >::_write(), PPCField::_write(), NPCField::_write(), and SRField::_write().
subStructs_
std::map< std::string, std::weak_ptr< VirtualStruct > > etiss::VirtualStruct::subStructs_ private
Definition at line 386 of file VirtualStruct.h.
Referenced by findStruct(), foreachStruct(), getVirtualStruct(), and mountStruct().
The documentation for this class was generated from the following files:
include/etiss/VirtualStruct.h
/home/runner/work/etiss/etiss/src/CVirtualStruct.cpp
/home/runner/work/etiss/etiss/src/VirtualStruct.cpp