ETISS 0.8.0: etiss::string::form_string Class Reference
etiss::string::form_string Class Reference
#include <FastString.h>
Public Member Functions
template<typename... T>
form_string (T... str)
template<typename T >
std::enable_if< std::is_integral< T >::value, void > write_dec (unsigned field, T value)
void write (unsigned field, const char *buf, size_t length)
void writet (unsigned field, const char *buf, size_t length, char terminator=' ', char fill=' ')
char * c_str ()
const char * c_str () const
template<typename... T>
form_string (T... str)
template<typename T >
std::enable_if< std::is_integral< T >::value, void > write_dec (unsigned field, T value)
void write (unsigned field, const char *buf, size_t length)
void writet (unsigned field, const char *buf, size_t length, char terminator=' ', char fill=' ')
char * c_str ()
const char * c_str () const
Private Member Functions
size_t char_size (unsigned, size_t *, bool *)
terminates template recursion
template<typename... O>
size_t char_size (unsigned pos, size_t *size, bool *isPlaceholder, const char *s, O... others)
template<typename... O>
size_t char_size (unsigned pos, size_t *size, bool *isPlaceholder, size_t len, O... others)
void char_copy (unsigned, char *, size_t *)
terminates template recursion
template<typename... O>
void char_copy (unsigned pos, char *buf, size_t *size, const char *s, O... others)
template<typename... O>
void char_copy (unsigned pos, char *buf, size_t *size, size_t, O... others)
size_t char_size (unsigned, size_t *, bool *)
terminates template recursion
template<typename... O>
size_t char_size (unsigned pos, size_t *size, bool *isPlaceholder, const char *s, O... others)
template<typename... O>
size_t char_size (unsigned pos, size_t *size, bool *isPlaceholder, size_t len, O... others)
void char_copy (unsigned, char *, size_t *)
terminates template recursion
template<typename... O>
void char_copy (unsigned pos, char *buf, size_t *size, const char *s, O... others)
template<typename... O>
void char_copy (unsigned pos, char *buf, size_t *size, size_t, O... others)
Private Attributes
char * buffer
size_t size
std::vector< std::pair< size_t, size_t > > fields
list of field in the form_string. (offset,length) pairs
Detailed Description
Attention
this function relies on spaces being an acceptable fill character in case of field/input length missmatch
Definition at line 80 of file FastString.h.
Constructor & Destructor Documentation
form_string() [1/2]
template<typename... T> etiss::string::form_string::form_string (T... str) inline
Definition at line 123 of file FastString.h.
References buffer, char_copy(), char_size(), fields, and size.
form_string() [2/2]
template<typename... T> etiss::string::form_string::form_string (T... str) inline
Definition at line 123 of file FastString.h.
References buffer, char_copy(), char_size(), fields, and size.
Member Function Documentation
c_str() [1/4]
char* etiss::string::form_string::c_str () inline
Definition at line 215 of file FastString.h.
References buffer.
Referenced by etiss::string::operator<<().
c_str() [2/4]
char* etiss::string::form_string::c_str () inline
Definition at line 215 of file FastString.h.
References buffer.
c_str() [3/4]
const char* etiss::string::form_string::c_str () const inline
Definition at line 216 of file FastString.h.
References buffer.
c_str() [4/4]
const char* etiss::string::form_string::c_str () const inline
Definition at line 216 of file FastString.h.
References buffer.
char_copy() [1/6]
template<typename... O> void etiss::string::form_string::char_copy (unsigned pos, char * buf, size_t * size, const char * s, O... others) inline private
Definition at line 109 of file FastString.h.
References char_copy(), memcpy(), s, and size.
char_copy() [2/6]
template<typename... O> void etiss::string::form_string::char_copy (unsigned pos, char * buf, size_t * size, const char * s, O... others) inline private
Definition at line 109 of file FastString.h.
References char_copy(), memcpy(), s, and size.
char_copy() [3/6]
template<typename... O> void etiss::string::form_string::char_copy (unsigned pos, char * buf, size_t * size, size_t , O... others) inline private
Definition at line 115 of file FastString.h.
References char_copy(), memset(), and size.
char_copy() [4/6]
template<typename... O> void etiss::string::form_string::char_copy (unsigned pos, char * buf, size_t * size, size_t , O... others) inline private
Definition at line 115 of file FastString.h.
References char_copy(), memset(), and size.
char_copy() [5/6]
void etiss::string::form_string::char_copy (unsigned , char * , size_t *) inline private
terminates template recursion
Definition at line 107 of file FastString.h.
Referenced by char_copy(), and form_string().
char_copy() [6/6]
void etiss::string::form_string::char_copy (unsigned , char * , size_t *) inline private
terminates template recursion
Definition at line 107 of file FastString.h.
char_size() [1/6]
template<typename... O> size_t etiss::string::form_string::char_size (unsigned pos, size_t * size, bool * isPlaceholder, const char * s, O... others) inline private
Definition at line 91 of file FastString.h.
References char_size(), s, and size.
char_size() [2/6]
template<typename... O> size_t etiss::string::form_string::char_size (unsigned pos, size_t * size, bool * isPlaceholder, const char * s, O... others) inline private
Definition at line 91 of file FastString.h.
References char_size(), s, and size.
char_size() [3/6]
template<typename... O> size_t etiss::string::form_string::char_size (unsigned pos, size_t * size, bool * isPlaceholder, size_t len, O... others) inline private
Definition at line 98 of file FastString.h.
References char_size(), and size.
char_size() [4/6]
template<typename... O> size_t etiss::string::form_string::char_size (unsigned pos, size_t * size, bool * isPlaceholder, size_t len, O... others) inline private
Definition at line 98 of file FastString.h.
References char_size(), and size.
char_size() [5/6]
size_t etiss::string::form_string::char_size (unsigned , size_t * , bool *) inline private
terminates template recursion
Definition at line 89 of file FastString.h.
Referenced by char_size(), and form_string().
char_size() [6/6]
size_t etiss::string::form_string::char_size (unsigned , size_t * , bool *) inline private
terminates template recursion
Definition at line 89 of file FastString.h.
write() [1/2]
void etiss::string::form_string::write (unsigned field, const char * buf, size_t length) inline
Definition at line 179 of file FastString.h.
References buffer, ETISS_SRCLOC, etiss::FATALERROR, fields, length(), etiss::log(), memcpy(), and memset().
write() [2/2]
void etiss::string::form_string::write (unsigned field, const char * buf, size_t length) inline
Definition at line 179 of file FastString.h.
References buffer, ETISS_SRCLOC, etiss::FATALERROR, fields, length(), etiss::log(), memcpy(), and memset().
write_dec() [1/2]
template<typename T > std::enable_if<std::is_integral<T>::value, void> etiss::string::form_string::write_dec (unsigned field, T value) inline
Definition at line 149 of file FastString.h.
References buffer, c, ETISS_SRCLOC, etiss::FATALERROR, fields, and etiss::log().
write_dec() [2/2]
template<typename T > std::enable_if<std::is_integral<T>::value, void> etiss::string::form_string::write_dec (unsigned field, T value) inline
Definition at line 149 of file FastString.h.
References buffer, c, ETISS_SRCLOC, etiss::FATALERROR, fields, and etiss::log().
writet() [1/2]
void etiss::string::form_string::writet (unsigned field, const char * buf, size_t length, char terminator = ' ', char fill = ' ') inline
Definition at line 196 of file FastString.h.
References buffer, ETISS_SRCLOC, etiss::FATALERROR, fields, length(), etiss::log(), memcpy(), and memset().
writet() [2/2]
void etiss::string::form_string::writet (unsigned field, const char * buf, size_t length, char terminator = ' ', char fill = ' ') inline
Definition at line 196 of file FastString.h.
References buffer, ETISS_SRCLOC, etiss::FATALERROR, fields, length(), etiss::log(), memcpy(), and memset().
Member Data Documentation
buffer
char * etiss::string::form_string::buffer private
Definition at line 83 of file FastString.h.
Referenced by c_str(), form_string(), write(), write_dec(), and writet().
fields
std::vector< std::pair< size_t, size_t > > etiss::string::form_string::fields private
list of field in the form_string. (offset,length) pairs
Definition at line 85 of file FastString.h.
Referenced by form_string(), write(), write_dec(), and writet().
size
size_t etiss::string::form_string::size private
Definition at line 84 of file FastString.h.
Referenced by char_copy(), char_size(), and form_string().
The documentation for this class was generated from the following file:
include/etiss/FastString.h