ETISS 0.8.0: etiss::SimpleSystem Class Reference
etiss::SimpleSystem Class Reference abstract
A simple system, that implements the etiss::System interface.
#include <System.h>
Public Member Functions
virtual ~SimpleSystem ()
virtual etiss::int32 iread (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint32 len)
Instruction read operation.
virtual etiss::int32 iwrite (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Instruction write operation.
virtual etiss::int32 dread (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Data read operation.
virtual etiss::int32 dwrite (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Data write operation.
virtual etiss::int32 dbg_read (etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Debug read operation.
virtual etiss::int32 dbg_write (etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Debug write operation.
virtual void syncTime (ETISS_CPU *cpu)
Synchronize simulation time.
virtual bool read (bool debug, ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)=0
virtual bool write (bool debug, ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)=0
virtual ~SimpleSystem ()
virtual etiss::int32 iread (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint32 len)
Instruction read operation.
virtual etiss::int32 iwrite (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Instruction write operation.
virtual etiss::int32 dread (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Data read operation.
virtual etiss::int32 dwrite (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Data write operation.
virtual etiss::int32 dbg_read (etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Debug read operation.
virtual etiss::int32 dbg_write (etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Debug write operation.
virtual void syncTime (ETISS_CPU *cpu)
Synchronize simulation time.
virtual bool read (bool debug, ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)=0
virtual bool write (bool debug, ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)=0
Public Member Functions inherited from etiss::System
virtual ~System ()
virtual ~System ()
Detailed Description
A simple system, that implements the etiss::System interface.
Definition at line 220 of file System.h.
Constructor & Destructor Documentation
~SimpleSystem() [1/2]
virtual etiss::SimpleSystem::~SimpleSystem () inline virtual
Definition at line 223 of file System.h.
~SimpleSystem() [2/2]
virtual etiss::SimpleSystem::~SimpleSystem () inline virtual
Definition at line 223 of file System.h.
Member Function Documentation
dbg_read() [1/2]
etiss::int32 etiss::SimpleSystem::dbg_read (etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Debug read operation.
This method should implement a debug read operation. The debug operations are used for data access that should not influence the simulation time. To indicate an error a non 0 value should be returned.
Note
The read debug operation is used for the instruction fetches required for generating the code blocks.
Parameters
addr The address from which the data should be read.
buf Pointer to the buffer, that contains the instruction.
len The length of the data in bytes.
Returns
0 if no error occurred.
Implements etiss::System.
Definition at line 161 of file System.cpp.
References read().
dbg_read() [2/2]
virtual etiss::int32 etiss::SimpleSystem::dbg_read (etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Debug read operation.
This method should implement a debug read operation. The debug operations are used for data access that should not influence the simulation time. To indicate an error a non 0 value should be returned.
Note
The read debug operation is used for the instruction fetches required for generating the code blocks.
Parameters
addr The address from which the data should be read.
buf Pointer to the buffer, that contains the instruction.
len The length of the data in bytes.
Returns
0 if no error occurred.
Implements etiss::System.
dbg_write() [1/2]
etiss::int32 etiss::SimpleSystem::dbg_write (etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Debug write operation.
This method should implement a debug write operation. The debug operations are used for data access that should not influence the simulation time. To indicate an error a non 0 value should be returned.
Parameters
addr The address to which the data should be written.
buf Pointer to the buffer, that contains the instruction.
len The length of the data in bytes.
Returns
0 if no error occurred
Implements etiss::System.
Definition at line 168 of file System.cpp.
References write().
dbg_write() [2/2]
virtual etiss::int32 etiss::SimpleSystem::dbg_write (etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Debug write operation.
This method should implement a debug write operation. The debug operations are used for data access that should not influence the simulation time. To indicate an error a non 0 value should be returned.
Parameters
addr The address to which the data should be written.
buf Pointer to the buffer, that contains the instruction.
len The length of the data in bytes.
Returns
0 if no error occurred
Implements etiss::System.
dread() [1/2]
etiss::int32 etiss::SimpleSystem::dread (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Data read operation.
This method should implement a data read operation. To indicate an error a non 0 value should be returned. The CPU time needs to be increased according to the delay of this instruction operation.
Parameters
cpu Pointer to the CPU structure, that requested this operation.
addr The address from which the data should be read.
buf Pointer to the buffer, that contains the instruction.
len The length of the data in bytes.
Returns
0 if no error occurred.
Implements etiss::System.
Definition at line 147 of file System.cpp.
References read().
dread() [2/2]
virtual etiss::int32 etiss::SimpleSystem::dread (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Data read operation.
This method should implement a data read operation. To indicate an error a non 0 value should be returned. The CPU time needs to be increased according to the delay of this instruction operation.
Parameters
cpu Pointer to the CPU structure, that requested this operation.
addr The address from which the data should be read.
buf Pointer to the buffer, that contains the instruction.
len The length of the data in bytes.
Returns
0 if no error occurred.
Implements etiss::System.
dwrite() [1/2]
etiss::int32 etiss::SimpleSystem::dwrite (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Data write operation.
This method should implement a data write operation. To indicate an error a non 0 value should be returned. The CPU time needs to be increased according to the delay of this instruction operation.
Parameters
cpu Pointer to the CPU structure, that requested this operation.
addr The address to which the data should be written.
buf Pointer to the buffer, that contains the instruction.
len The length of the data in bytes.
Returns
0 if no error occurred.
Implements etiss::System.
Definition at line 154 of file System.cpp.
References write().
dwrite() [2/2]
virtual etiss::int32 etiss::SimpleSystem::dwrite (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Data write operation.
This method should implement a data write operation. To indicate an error a non 0 value should be returned. The CPU time needs to be increased according to the delay of this instruction operation.
Parameters
cpu Pointer to the CPU structure, that requested this operation.
addr The address to which the data should be written.
buf Pointer to the buffer, that contains the instruction.
len The length of the data in bytes.
Returns
0 if no error occurred.
Implements etiss::System.
iread() [1/2]
virtual etiss::int32 etiss::SimpleSystem::iread (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint32 len) virtual
Instruction read operation.
This method should implement an instruction read operation. To indicate an error a non 0 value should be returned. The CPU time needs to be increased according to the delay of this instruction operation.
Note
Normally this method can be implemented as an empty method that only returns an error value. Because of the translating nature of ETISS all instruction operations are out of order an will be performed via the debug interface.
Parameters
cpu Pointer to the CPU structure, that requested this operation.
addr The address from which the instruction should be read.
len The length of the instruction in bytes.
Returns
0 if no error occurred
Implements etiss::System.
iread() [2/2]
etiss::int32 etiss::SimpleSystem::iread (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint32 len) virtual
Instruction read operation.
This method should implement an instruction read operation. To indicate an error a non 0 value should be returned. The CPU time needs to be increased according to the delay of this instruction operation.
Note
Normally this method can be implemented as an empty method that only returns an error value. Because of the translating nature of ETISS all instruction operations are out of order an will be performed via the debug interface.
Parameters
cpu Pointer to the CPU structure, that requested this operation.
addr The address from which the instruction should be read.
len The length of the instruction in bytes.
Returns
0 if no error occurred
Implements etiss::System.
Definition at line 132 of file System.cpp.
iwrite() [1/2]
etiss::int32 etiss::SimpleSystem::iwrite (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Instruction write operation.
This method should implement an instruction write operation. To indicate an error a non 0 value should be returned. The CPU time needs to be increased according to the delay of this instruction operation.
Note
Normally this method can be implemented as an empty method that only returns an error value. Because of the translating nature of ETISS all instruction operations are out of order an will be performed via the debug interface
Parameters
cpu Pointer to the CPU structure, that requested this operation.
addr The address to which the instruction should be written.
buf Pointer to the buffer, that contains the instruction.
len The length of the instruction in bytes.
Returns
0 if no error occurred.
Implements etiss::System.
Definition at line 140 of file System.cpp.
References write().
iwrite() [2/2]
virtual etiss::int32 etiss::SimpleSystem::iwrite (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Instruction write operation.
This method should implement an instruction write operation. To indicate an error a non 0 value should be returned. The CPU time needs to be increased according to the delay of this instruction operation.
Note
Normally this method can be implemented as an empty method that only returns an error value. Because of the translating nature of ETISS all instruction operations are out of order an will be performed via the debug interface
Parameters
cpu Pointer to the CPU structure, that requested this operation.
addr The address to which the instruction should be written.
buf Pointer to the buffer, that contains the instruction.
len The length of the instruction in bytes.
Returns
0 if no error occurred.
Implements etiss::System.
read() [1/2]
virtual bool etiss::SimpleSystem::read (bool debug, ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) pure virtual
Implemented in etiss::plugin::VirtualStructMemory, and etiss::plugin::VirtualStructMemory.
Referenced by dbg_read(), and dread().
read() [2/2]
virtual bool etiss::SimpleSystem::read (bool debug, ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) pure virtual
Implemented in etiss::plugin::VirtualStructMemory, and etiss::plugin::VirtualStructMemory.
syncTime() [1/2]
virtual void etiss::SimpleSystem::syncTime (ETISS_CPU * cpu) virtual
Synchronize simulation time.
This method should implement the synchronization between the simulation time of the system and the CPU. This function call should allow the system to catch up with the CPU.
See also
etiss::ETISS_CPU
Parameters
cpu Pointer to the CPU structure, for which the synchronization should be performed.
Implements etiss::System.
syncTime() [2/2]
void etiss::SimpleSystem::syncTime (ETISS_CPU * cpu) virtual
Synchronize simulation time.
This method should implement the synchronization between the simulation time of the system and the CPU. This function call should allow the system to catch up with the CPU.
See also
etiss::ETISS_CPU
Parameters
cpu Pointer to the CPU structure, for which the synchronization should be performed.
Implements etiss::System.
Definition at line 175 of file System.cpp.
write() [1/2]
virtual bool etiss::SimpleSystem::write (bool debug, ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) pure virtual
Implemented in etiss::plugin::VirtualStructMemory, and etiss::plugin::VirtualStructMemory.
write() [2/2]
virtual bool etiss::SimpleSystem::write (bool debug, ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) pure virtual
Implemented in etiss::plugin::VirtualStructMemory, and etiss::plugin::VirtualStructMemory.
Referenced by dbg_write(), dwrite(), and iwrite().
The documentation for this class was generated from the following files:
include/etiss/System.h
/home/runner/work/etiss/etiss/src/System.cpp