ETISS 0.8.0: etiss::Initializer Class Reference
etiss::Initializer Class Reference
ETISS_Frontend
Wrapper for the initialize and shutdown of the ETISS environment.
#include <ETISS.h>
Public Member Functions
void loadIniPlugins (std::shared_ptr< etiss::CPUCore > cpu)
loads the plugins given with the previous loaded .ini files
void loadIniJIT (std::shared_ptr< etiss::CPUCore > cpu)
sets the JIT given with the previous loaded .ini files
template<typename argvT , typename... lisT>
Initializer (int argc, argvT **argv, lisT... args_append)
Constructor that initializes ETISS.
Initializer (std::list< std::string > *files, int argc, const char *argv[])
template<typename... listT>
Initializer (listT... args)
Constructor that initializes ETISS.
template<typename argvT , typename... lisT>
Initializer (std::list< std::string > *files, int argc, argvT **argv, lisT... args_append)
Constructor that initializes ETISS.
template<typename... listT>
Initializer (std::list< std::string > *files, listT... args)
Constructor that initializes ETISS.
~Initializer ()
Destructor that shutdowns ETISS.
void loadIniPlugins (std::shared_ptr< etiss::CPUCore > cpu)
loads the plugins given with the previous loaded .ini files
void loadIniJIT (std::shared_ptr< etiss::CPUCore > cpu)
sets the JIT given with the previous loaded .ini files
template<typename argvT , typename... lisT>
Initializer (int argc, argvT **argv, lisT... args_append)
Constructor that initializes ETISS.
Initializer (std::list< std::string > *files, int argc, const char *argv[])
template<typename... listT>
Initializer (listT... args)
Constructor that initializes ETISS.
template<typename argvT , typename... lisT>
Initializer (std::list< std::string > *files, int argc, argvT **argv, lisT... args_append)
Constructor that initializes ETISS.
template<typename... listT>
Initializer (std::list< std::string > *files, listT... args)
Constructor that initializes ETISS.
~Initializer ()
Destructor that shutdowns ETISS.
Private Member Functions
template<typename T , typename... lisT>
void toList (std::vector< std::string > &vec, T t, lisT... args)
Add argument list to a string vector.
void toList (std::vector< std::string > &vec)
Break condition for empty argument list.
void loadIni (std::list< std::string > *files)
creates a simpleIni object which holds the data of the given .ini file.
template<typename T , typename... lisT>
void static_assertFirstParamNotArithmetic (T t, lisT... args)
Make sure that the first variadic parameter at compiletime is no number.
void static_assertFirstParamNotArithmetic ()
version of static_assertFirstParamNotArithmetic for the case that no parameter is given.
template<typename T , typename... lisT>
void toList (std::vector< std::string > &vec, T t, lisT... args)
Add argument list to a string vector.
void toList (std::vector< std::string > &vec)
Break condition for empty argument list.
void loadIni (std::list< std::string > *files)
creates a simpleIni object which holds the data of the given .ini file.
template<typename T , typename... lisT>
void static_assertFirstParamNotArithmetic (T t, lisT... args)
Make sure that the first variadic parameter at compiletime is no number.
void static_assertFirstParamNotArithmetic ()
version of static_assertFirstParamNotArithmetic for the case that no parameter is given.
Detailed Description
Wrapper for the initialize and shutdown of the ETISS environment.
At creation of an Initializer object ETISS is initialized. On destruction of an Initializer object ETISS shutdown. There should only be one instance of Initializer at any point of time.
Create an instance at the beginning of main to ensure proper initialization and cleanup.
int main(int argc,char ** argv){
  etiss::Initializer etiss_initializer(argc,argv);
  // program/simulation
} // The etiss::Initializer instance will be destroyed here and performs cleanup operations
Note
It is recommended to use this class instead of etiss::initialize() / etiss::shutdown().
Definition at line 253 of file ETISS.h.
Constructor & Destructor Documentation
Initializer() [1/10]
template<typename argvT , typename... lisT> etiss::Initializer::Initializer (int argc, argvT ** argv, lisT... args_append) inline
Constructor that initializes ETISS.
This Constructor is useful if the arguments provided to the main function should be forwarded to etiss::initialize(). Additional arguments can simply be added at the end of the argument list. If an argument is not a string it will be converted to a string with the help of etiss::toString().
Parameters
argc The number of arguments in the C-string array.
argv Pointer to a C-string array.
args_append Additional arguments for etiss::initialize.
Definition at line 333 of file ETISS.h.
References etiss::initialize(), static_assert, and toList().
Initializer() [2/10]
etiss::Initializer::Initializer (std::list< std::string > * files, int argc, const char * argv[]) inline
Definition at line 348 of file ETISS.h.
References etiss::initialize(), and loadIni().
Initializer() [3/10]
template<typename... listT> etiss::Initializer::Initializer (listT... args) inline
Constructor that initializes ETISS.
If an argument is not a string it will be converted to a string with the help of etiss::toString(). E.g.
  etiss::Initializer
initializer("-foption1","-fno-option2","-osomevallue",123,"etc.");
Parameters
args List of arguments for etiss::initialize.
Definition at line 373 of file ETISS.h.
References etiss::initialize(), static_assertFirstParamNotArithmetic(), and toList().
Initializer() [4/10]
template<typename argvT , typename... lisT> etiss::Initializer::Initializer (std::list< std::string > * files, int argc, argvT ** argv, lisT... args_append) inline
Constructor that initializes ETISS.
This Constructor is useful if the arguments provided to the main function should be forwarded to etiss::initialize(). Additional arguments can simply be added at the end of the argument list. If an argument is not a string it will be converted to a string with the help of etiss::toString().
Parameters
argc The number of arguments in the C-string array.
argv Pointer to a C-string array.
filename File to open an ini file.
args_append Additional arguments for etiss::initialize.
Definition at line 401 of file ETISS.h.
References etiss::initialize(), loadIni(), static_assert, and toList().
Initializer() [5/10]
template<typename... listT> etiss::Initializer::Initializer (std::list< std::string > * files, listT... args) inline
Constructor that initializes ETISS.
If an argument is not a string it will be converted to a string with the help of etiss::toString(). E.g.
  etiss::Initializer
initializer("-foption1","-fno-option2","-osomevallue",123,"etc.");
Parameters
filename File to open an ini file.
args List of arguments for etiss::initialize.
Definition at line 433 of file ETISS.h.
References etiss::initialize(), loadIni(), static_assertFirstParamNotArithmetic(), and toList().
~Initializer() [1/2]
etiss::Initializer::~Initializer ()
Destructor that shutdowns ETISS.
The destructor calls etiss::shutdown().
Definition at line 976 of file ETISS.cpp.
References po_simpleIni, and etiss::shutdown().
Initializer() [6/10]
template<typename argvT , typename... lisT> etiss::Initializer::Initializer (int argc, argvT ** argv, lisT... args_append) inline
Constructor that initializes ETISS.
This Constructor is useful if the arguments provided to the main function should be forwarded to etiss::initialize(). Additional arguments can simply be added at the end of the argument list. If an argument is not a string it will be converted to a string with the help of etiss::toString().
Parameters
argc The number of arguments in the C-string array.
argv Pointer to a C-string array.
args_append Additional arguments for etiss::initialize.
Definition at line 333 of file ETISS.h.
References etiss::initialize(), static_assert, and toList().
Initializer() [7/10]
etiss::Initializer::Initializer (std::list< std::string > * files, int argc, const char * argv[]) inline
Definition at line 348 of file ETISS.h.
References etiss::initialize(), and loadIni().
Initializer() [8/10]
template<typename... listT> etiss::Initializer::Initializer (listT... args) inline
Constructor that initializes ETISS.
If an argument is not a string it will be converted to a string with the help of etiss::toString(). E.g.
  etiss::Initializer
initializer("-foption1","-fno-option2","-osomevallue",123,"etc.");
Parameters
args List of arguments for etiss::initialize.
Definition at line 373 of file ETISS.h.
References etiss::initialize(), static_assertFirstParamNotArithmetic(), and toList().
Initializer() [9/10]
template<typename argvT , typename... lisT> etiss::Initializer::Initializer (std::list< std::string > * files, int argc, argvT ** argv, lisT... args_append) inline
Constructor that initializes ETISS.
This Constructor is useful if the arguments provided to the main function should be forwarded to etiss::initialize(). Additional arguments can simply be added at the end of the argument list. If an argument is not a string it will be converted to a string with the help of etiss::toString().
Parameters
argc The number of arguments in the C-string array.
argv Pointer to a C-string array.
filename File to open an ini file.
args_append Additional arguments for etiss::initialize.
Definition at line 401 of file ETISS.h.
References etiss::initialize(), loadIni(), static_assert, and toList().
Initializer() [10/10]
template<typename... listT> etiss::Initializer::Initializer (std::list< std::string > * files, listT... args) inline
Constructor that initializes ETISS.
If an argument is not a string it will be converted to a string with the help of etiss::toString(). E.g.
  etiss::Initializer
initializer("-foption1","-fno-option2","-osomevallue",123,"etc.");
Parameters
filename File to open an ini file.
args List of arguments for etiss::initialize.
Definition at line 433 of file ETISS.h.
References etiss::initialize(), loadIni(), static_assertFirstParamNotArithmetic(), and toList().
~Initializer() [2/2]
etiss::Initializer::~Initializer ()
Destructor that shutdowns ETISS.
The destructor calls etiss::shutdown().
Member Function Documentation
loadIni() [1/2]
void etiss::Initializer::loadIni (std::list< std::string > * files) private
creates a simpleIni object which holds the data of the given .ini file.
Definition at line 410 of file ETISS.cpp.
References etiss_loadIni(), NULL, and po_simpleIni.
Referenced by Initializer().
loadIni() [2/2]
void etiss::Initializer::loadIni (std::list< std::string > * files) private
creates a simpleIni object which holds the data of the given .ini file.
loadIniJIT() [1/2]
void etiss::Initializer::loadIniJIT (std::shared_ptr< etiss::CPUCore > cpu)
sets the JIT given with the previous loaded .ini files
Parameters
Needed to add the JIT to the CPU
Definition at line 660 of file ETISS.cpp.
References etiss::cfg(), etiss::getJIT(), etiss::CPUCore::getJITName(), etiss::INFO, etiss::log(), etiss::CPUCore::set(), and etiss::WARNING.
loadIniJIT() [2/2]
void etiss::Initializer::loadIniJIT (std::shared_ptr< etiss::CPUCore > cpu)
sets the JIT given with the previous loaded .ini files
Parameters
Needed to add the JIT to the CPU
loadIniPlugins() [1/2]
void etiss::Initializer::loadIniPlugins (std::shared_ptr< etiss::CPUCore > cpu)
loads the plugins given with the previous loaded .ini files
Parameters
Needed to add the plugins to the CPU
Definition at line 552 of file ETISS.cpp.
References etiss::CPUCore::addPlugin(), etiss::cfg(), CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::GetAllKeys(), CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::GetAllSections(), CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::GetAllValues(), etiss::getPlugin(), etiss::CPUCore::getPlugins(), etiss::INFO, etiss::log(), options, pluginOptions, po_simpleIni, vm, and etiss::WARNING.
loadIniPlugins() [2/2]
void etiss::Initializer::loadIniPlugins (std::shared_ptr< etiss::CPUCore > cpu)
loads the plugins given with the previous loaded .ini files
Parameters
Needed to add the plugins to the CPU
static_assertFirstParamNotArithmetic() [1/4]
void etiss::Initializer::static_assertFirstParamNotArithmetic () inline private
version of static_assertFirstParamNotArithmetic for the case that no parameter is given.
Definition at line 305 of file ETISS.h.
Referenced by Initializer().
static_assertFirstParamNotArithmetic() [2/4]
void etiss::Initializer::static_assertFirstParamNotArithmetic () inline private
version of static_assertFirstParamNotArithmetic for the case that no parameter is given.
Definition at line 305 of file ETISS.h.
static_assertFirstParamNotArithmetic() [3/4]
template<typename T , typename... lisT> void etiss::Initializer::static_assertFirstParamNotArithmetic (T t, lisT... args) inline private
Make sure that the first variadic parameter at compiletime is no number.
The original goal was: The Initializer versions that take argc and argv wanted const char as type for argv. In some projects, the Initializer constructor was called with char instead of const char. This led to problems as another construtor with completely variadic parameters was choosen instead, which failed to parse argc and argv. This function was used to make sure these versions of Initializer are not instantiated with argc as the first argument.
Definition at line 296 of file ETISS.h.
References static_assert.
static_assertFirstParamNotArithmetic() [4/4]
template<typename T , typename... lisT> void etiss::Initializer::static_assertFirstParamNotArithmetic (T t, lisT... args) inline private
Make sure that the first variadic parameter at compiletime is no number.
The original goal was: The Initializer versions that take argc and argv wanted const char as type for argv. In some projects, the Initializer constructor was called with char instead of const char. This led to problems as another construtor with completely variadic parameters was choosen instead, which failed to parse argc and argv. This function was used to make sure these versions of Initializer are not instantiated with argc as the first argument.
Definition at line 296 of file ETISS.h.
References static_assert.
toList() [1/4]
void etiss::Initializer::toList (std::vector< std::string > & vec) inline private
Break condition for empty argument list.
Definition at line 278 of file ETISS.h.
toList() [2/4]
void etiss::Initializer::toList (std::vector< std::string > & vec) inline private
Break condition for empty argument list.
Definition at line 278 of file ETISS.h.
toList() [3/4]
template<typename T , typename... lisT> void etiss::Initializer::toList (std::vector< std::string > & vec, T t, lisT... args) inline private
Add argument list to a string vector.
Recursively converts function arguments to a string with etiss::toString() and adds them to a string vector.
Parameters
vec The string vector where the arguments should be appended.
t The argument that is add next.
args The arguments added in the next recursion.
Definition at line 269 of file ETISS.h.
References toList(), and etiss::toString().
toList() [4/4]
template<typename T , typename... lisT> void etiss::Initializer::toList (std::vector< std::string > & vec, T t, lisT... args) inline private
Add argument list to a string vector.
Recursively converts function arguments to a string with etiss::toString() and adds them to a string vector.
Parameters
vec The string vector where the arguments should be appended.
t The argument that is add next.
args The arguments added in the next recursion.
Definition at line 269 of file ETISS.h.
References etiss::toString().
Referenced by Initializer(), and toList().
The documentation for this class was generated from the following files:
include/etiss/ETISS.h
/home/runner/work/etiss/etiss/src/ETISS.cpp