ETISS 0.8.0: etiss::CPUArch Class Reference
etiss::CPUArch Class Reference abstract
the interface to translate instructions of and processor architecture
#include <CPUArch.h>
Public Member Functions
CPUArch (std::string archname)
virtual ~CPUArch ()
std::string getArchName () const
returns the name of this architecture.
std::string getName () const
returns the name of this architecture.
virtual ETISS_CPU * newCPU ()=0
allocate new cpu structure
virtual void resetCPU (ETISS_CPU *cpu, etiss::uint64 *startpointer)=0
reset cpu (structure)
virtual void deleteCPU (ETISS_CPU *)=0
delete cpu structure
virtual unsigned getMaximumInstructionSizeInBytes ()=0
used for variable instruction size and delay slots
virtual unsigned getMaximumInstructionsPerMetaInstruction ()
maximum number of instructions in a meta instruction
virtual unsigned getInstructionSizeInBytes ()=0
size of one instruction/ smalest data unit for instructions of variable length
virtual unsigned getSuperInstructionCount ()
fixed number of sub instructions per instruction (e.g.
virtual std::string getBlockGlobalCode ()
get c++ code snippet that is placed at the top of a translated block
virtual bool unlikelyInstruction (etiss::uint8 *instr, unsigned length, bool &ismetainstruction)
return true if the given data is unlikely to be an instruction.
virtual const std::set< std::string > & getHeaders () const =0
set of code header files e.g.
virtual etiss::int32 handleException (etiss::int32 code, ETISS_CPU *cpu)
translate/process exceptions that occur at runtime
virtual etiss::InterruptVector * createInterruptVector (ETISS_CPU *cpu)
allocate a new interrupt vector object for the given cpu
virtual void deleteInterruptVector (etiss::InterruptVector *vec, ETISS_CPU *cpu)
delete an allocated interrupt vector object
virtual etiss::plugin::gdb::GDBCore & getGDBCore ()
returns arch dependent gdb functions.
virtual std::string getIncludePath ()
returns a path that will be used to look up header files
virtual void finalizeInstrSet (etiss::instr::ModedInstructionSet &) const
the default behavior of this function of a cpu arch is to add "cpu->cpuTime_ps += cpu->cpuCycleTime_ps;" if the cpu time update group is not in use
virtual void compensateEndianess (ETISS_CPU *cpu, etiss::instr::BitArray &ba) const
this function should compensate for any endianess on a BitArray so that bit 0 is always the LSB.
virtual etiss::mm::MMU * newMMU (ETISS_CPU *cpu)
It is an interface to instanciate a Memory Management Unit.
CPUArch (std::string archname)
virtual ~CPUArch ()
std::string getArchName () const
returns the name of this architecture.
std::string getName () const
returns the name of this architecture.
virtual ETISS_CPU * newCPU ()=0
allocate new cpu structure
virtual void resetCPU (ETISS_CPU *cpu, etiss::uint64 *startpointer)=0
reset cpu (structure)
virtual void deleteCPU (ETISS_CPU *)=0
delete cpu structure
virtual unsigned getMaximumInstructionSizeInBytes ()=0
used for variable instruction size and delay slots
virtual unsigned getMaximumInstructionsPerMetaInstruction ()
maximum number of instructions in a meta instruction
virtual unsigned getInstructionSizeInBytes ()=0
size of one instruction/ smalest data unit for instructions of variable length
virtual unsigned getSuperInstructionCount ()
fixed number of sub instructions per instruction (e.g.
virtual std::string getBlockGlobalCode ()
get c++ code snippet that is placed at the top of a translated block
virtual bool unlikelyInstruction (etiss::uint8 *instr, unsigned length, bool &ismetainstruction)
return true if the given data is unlikely to be an instruction.
virtual const std::set< std::string > & getHeaders () const =0
set of code header files e.g.
virtual etiss::int32 handleException (etiss::int32 code, ETISS_CPU *cpu)
translate/process exceptions that occur at runtime
virtual etiss::InterruptVector * createInterruptVector (ETISS_CPU *cpu)
allocate a new interrupt vector object for the given cpu
virtual void deleteInterruptVector (etiss::InterruptVector *vec, ETISS_CPU *cpu)
delete an allocated interrupt vector object
virtual etiss::plugin::gdb::GDBCore & getGDBCore ()
returns arch dependent gdb functions.
virtual std::string getIncludePath ()
returns a path that will be used to look up header files
virtual void finalizeInstrSet (etiss::instr::ModedInstructionSet &) const
the default behavior of this function of a cpu arch is to add "cpu->cpuTime_ps += cpu->cpuCycleTime_ps;" if the cpu time update group is not in use
virtual void compensateEndianess (ETISS_CPU *cpu, etiss::instr::BitArray &ba) const
this function should compensate for any endianess on a BitArray so that bit 0 is always the LSB.
virtual etiss::mm::MMU * newMMU (ETISS_CPU *cpu)
It is an interface to instanciate a Memory Management Unit.
Public Member Functions inherited from etiss::CPUArchRegListenerInterface
virtual ~CPUArchRegListenerInterface ()
virtual const std::set< std::string > & getListenerSupportedRegisters ()=0
virtual ~CPUArchRegListenerInterface ()
virtual const std::set< std::string > & getListenerSupportedRegisters ()=0
Public Member Functions inherited from etiss::CPUArchCPUManipulation
virtual ~CPUArchCPUManipulation ()
virtual std::shared_ptr< etiss::VirtualStruct > getVirtualStruct (ETISS_CPU *cpu)=0
this function must return a valid pointer to a virtual struct
virtual ~CPUArchCPUManipulation ()
virtual std::shared_ptr< etiss::VirtualStruct > getVirtualStruct (ETISS_CPU *cpu)=0
this function must return a valid pointer to a virtual struct
Public Member Functions inherited from etiss::CPUArchDefaultPlugins
virtual ~CPUArchDefaultPlugins ()
virtual etiss::Plugin * newTimer (ETISS_CPU *cpu)
create a simple default timer implementaion instance for this architecture.
virtual void deleteTimer (etiss::Plugin *timer)
delete timer instance
virtual ~CPUArchDefaultPlugins ()
virtual etiss::Plugin * newTimer (ETISS_CPU *cpu)
create a simple default timer implementaion instance for this architecture.
virtual void deleteTimer (etiss::Plugin *timer)
delete timer instance
Public Member Functions inherited from etiss::TranslationPlugin
TranslationPlugin ()
virtual ~TranslationPlugin ()
virtual void initInstrSet (etiss::instr::ModedInstructionSet &) const
called to add instructions to the instruction set
virtual void initCodeBlock (etiss::CodeBlock &) const
called before instructions are translated for the code block
virtual void finalizeCodeBlock (etiss::CodeBlock &) const
called after all instructions have been translated for the code block
virtual void * getPluginHandle ()
called to get the handle that is available in translated code via getPoinerCode(). [default: this]
TranslationPlugin ()
virtual ~TranslationPlugin ()
virtual void initInstrSet (etiss::instr::ModedInstructionSet &) const
called to add instructions to the instruction set
virtual void initCodeBlock (etiss::CodeBlock &) const
called before instructions are translated for the code block
virtual void finalizeCodeBlock (etiss::CodeBlock &) const
called after all instructions have been translated for the code block
virtual void * getPluginHandle ()
called to get the handle that is available in translated code via getPoinerCode(). [default: this]
Public Member Functions inherited from etiss::Plugin
virtual ~Plugin ()
unsigned getType ()
InterruptListenerPlugin * getInterruptListenerPlugin ()
CoroutinePlugin * getCoroutinePlugin ()
SystemWrapperPlugin * getSystemWrapperPlugin ()
RegisterDevicePlugin * getRegisterDevicePlugin ()
TranslationPlugin * getTranslationPlugin ()
std::string getPluginName () const
const std::string & getLastAssignedCoreName ()
std::string toString () const
virtual ~Plugin ()
unsigned getType ()
InterruptListenerPlugin * getInterruptListenerPlugin ()
CoroutinePlugin * getCoroutinePlugin ()
SystemWrapperPlugin * getSystemWrapperPlugin ()
RegisterDevicePlugin * getRegisterDevicePlugin ()
TranslationPlugin * getTranslationPlugin ()
std::string getPluginName () const
const std::string & getLastAssignedCoreName ()
std::string toString () const
Public Member Functions inherited from etiss::ToString
ToString ()
virtual ~ToString ()
ToString ()
virtual ~ToString ()
Protected Member Functions
virtual std::string _getPluginName () const
do not override. maps to getName().
virtual std::string _getPluginName () const
do not override. maps to getName().
Protected Member Functions inherited from etiss::TranslationPlugin
std::string getPointerCode () const
returns a C code expression that allows to get or assign a pointer to the variable assigned to this translation plugin.
std::string getPointerCode () const
returns a C code expression that allows to get or assign a pointer to the variable assigned to this translation plugin.
Protected Member Functions inherited from etiss::Plugin
Plugin (unsigned type=0)
virtual void init (ETISS_CPU *cpu, ETISS_System *system, CPUArch *arch)
this function is called before the plugin is used in the cpu execution loop (etiss::CPUCore::execute).
virtual void cleanup ()
this function is called after cpu execution loop (etiss::CPUCore::execute) finished.
void setCorrespondingCPUCoreName (std::string name)
virtual void addedToCPUCore (etiss::CPUCore *core)
called as soon a plugin has been added to its CPUCore.
virtual void removedFromCPUCore (etiss::CPUCore *core)
called as soon a plugin has been removed from its CPUCore.
Plugin (unsigned type=0)
virtual void init (ETISS_CPU *cpu, ETISS_System *system, CPUArch *arch)
this function is called before the plugin is used in the cpu execution loop (etiss::CPUCore::execute).
virtual void cleanup ()
this function is called after cpu execution loop (etiss::CPUCore::execute) finished.
void setCorrespondingCPUCoreName (std::string name)
virtual void addedToCPUCore (etiss::CPUCore *core)
called as soon a plugin has been added to its CPUCore.
virtual void removedFromCPUCore (etiss::CPUCore *core)
called as soon a plugin has been removed from its CPUCore.
Private Attributes
etiss::plugin::gdb::GDBCore gdbcore_
std::string archname_
Friends
class LibraryInterface
Additional Inherited Members
Static Public Member Functions inherited from etiss::CPUArchRegListenerInterface
static void signalChangedRegisterValue (ETISS_CPU *cpu, const char *registerName)
call this function to inform RegisterDevicePlugins about changed special register values.
static void signalChangedRegisterValue (ETISS_CPU *cpu, const char *registerName)
call this function to inform RegisterDevicePlugins about changed special register values.
Static Public Attributes inherited from etiss::Plugin
static const unsigned INTERRUPTLISTENER = 1 << 0
access to translated code
static const unsigned COROUTINE = 1 << 1
callback after execution of each translated block
static const unsigned SYSTEMWRAPPER = 1 << 2
can wrap/change ETISS_System structure at execution start
static const unsigned REGISTERDEVICE
gets noticed of changes to special registers (e.g. mmu register etc. [depends on architecture])
static const unsigned TRANSLATION
access to translated code during translation phase or when instruction tree is built
Protected Attributes inherited from etiss::Plugin
ETISS_CPU * plugin_cpu_
holds a pointer to the cpu structure. will be set before init call and after cleanup call
ETISS_System * plugin_system_
holds a pointer to the system structure.
CPUArch * plugin_arch_
holds a pointer to the CPUArch instance. will be set before init call and after cleanup call
CPUCore * plugin_core_
holds a pointer to the associated CPUCore instance.
Detailed Description
the interface to translate instructions of and processor architecture
Definition at line 157 of file CPUArch.h.
Constructor & Destructor Documentation
CPUArch() [1/2]
CPUArch::CPUArch (std::string archname)
Parameters
archname must match the returned string of LibraryInterface::nameCPUArch(unsigned)/YOURLIBRARY_nameCPUArch(unsigned)
Definition at line 74 of file CPUArch.cpp.
References etiss::CPUCore::getNextID(), and etiss::Plugin::setCorrespondingCPUCoreName().
~CPUArch() [1/2]
CPUArch::~CPUArch () virtual
Definition at line 79 of file CPUArch.cpp.
CPUArch() [2/2]
etiss::CPUArch::CPUArch (std::string archname)
Parameters
archname must match the returned string of LibraryInterface::nameCPUArch(unsigned)/YOURLIBRARY_nameCPUArch(unsigned)
~CPUArch() [2/2]
virtual etiss::CPUArch::~CPUArch () virtual
Member Function Documentation
_getPluginName() [1/2]
std::string CPUArch::_getPluginName () const protected virtual
do not override. maps to getName().
Implements etiss::Plugin.
Definition at line 148 of file CPUArch.cpp.
References getName().
_getPluginName() [2/2]
virtual std::string etiss::CPUArch::_getPluginName () const protected virtual
do not override. maps to getName().
Implements etiss::Plugin.
compensateEndianess() [1/2]
void CPUArch::compensateEndianess (ETISS_CPU * cpu, etiss::instr::BitArray & ba) const virtual
this function should compensate for any endianess on a BitArray so that bit 0 is always the LSB.
the function etiss::instr::BitArray::recoverFromEndianness() can be used or the operation can be performed directly on th byte array with etiss::instr::BitArray::internalBuffer() by default bigendian aligned to 4 bytes is assumed
Reimplemented in RISCV64Arch, and RISCVArch.
Definition at line 181 of file CPUArch.cpp.
References etiss::_BIG_ENDIAN_, and etiss::instr::BitArray::recoverFromEndianness().
Referenced by etiss::Translation::translateBlock().
compensateEndianess() [2/2]
virtual void etiss::CPUArch::compensateEndianess (ETISS_CPU * cpu, etiss::instr::BitArray & ba) const virtual
this function should compensate for any endianess on a BitArray so that bit 0 is always the LSB.
the function etiss::instr::BitArray::recoverFromEndianness() can be used or the operation can be performed directly on th byte array with etiss::instr::BitArray::internalBuffer() by default bigendian aligned to 4 bytes is assumed
Reimplemented in RISCV64Arch, and RISCVArch.
createInterruptVector() [1/2]
virtual etiss::InterruptVector* etiss::CPUArch::createInterruptVector (ETISS_CPU * cpu) virtual
allocate a new interrupt vector object for the given cpu
Reimplemented in RISCV64Arch, RISCVArch, and OR1KArch.
createInterruptVector() [2/2]
etiss::InterruptVector * CPUArch::createInterruptVector (ETISS_CPU * cpu) virtual
allocate a new interrupt vector object for the given cpu
Reimplemented in RISCV64Arch, RISCVArch, and OR1KArch.
Definition at line 128 of file CPUArch.cpp.
deleteCPU() [1/2]
virtual void etiss::CPUArch::deleteCPU (ETISS_CPU *) pure virtual
delete cpu structure
Implemented in OR1KArch, RISCV64Arch, and RISCVArch.
deleteCPU() [2/2]
virtual void etiss::CPUArch::deleteCPU (ETISS_CPU *) pure virtual
delete cpu structure
Implemented in OR1KArch, RISCV64Arch, and RISCVArch.
deleteInterruptVector() [1/2]
virtual void etiss::CPUArch::deleteInterruptVector (etiss::InterruptVector * vec, ETISS_CPU * cpu) virtual
delete an allocated interrupt vector object
Reimplemented in RISCV64Arch, RISCVArch, and OR1KArch.
deleteInterruptVector() [2/2]
void CPUArch::deleteInterruptVector (etiss::InterruptVector * vec, ETISS_CPU * cpu) virtual
delete an allocated interrupt vector object
Reimplemented in RISCV64Arch, RISCVArch, and OR1KArch.
Definition at line 132 of file CPUArch.cpp.
finalizeInstrSet() [1/2]
void CPUArch::finalizeInstrSet (etiss::instr::ModedInstructionSet & mis) const virtual
the default behavior of this function of a cpu arch is to add "cpu->cpuTime_ps += cpu->cpuCycleTime_ps;" if the cpu time update group is not in use
Reimplemented from etiss::TranslationPlugin.
Definition at line 174 of file CPUArch.cpp.
References CPUArch_finalizeInstrSet(), etiss::instr::VariableInstructionSet::foreach(), and etiss::instr::ModedInstructionSet::foreach().
finalizeInstrSet() [2/2]
virtual void etiss::CPUArch::finalizeInstrSet (etiss::instr::ModedInstructionSet &) const virtual
the default behavior of this function of a cpu arch is to add "cpu->cpuTime_ps += cpu->cpuCycleTime_ps;" if the cpu time update group is not in use
Reimplemented from etiss::TranslationPlugin.
getArchName() [1/2]
std::string CPUArch::getArchName () const
returns the name of this architecture.
this name was passed to the constructor and must match the returned string of LibraryInterface::nameCPUArch(unsigned)/YOURLIBRARY_nameCPUArch(unsigned)
Deprecated:
Definition at line 81 of file CPUArch.cpp.
References archname_.
Referenced by getName().
getArchName() [2/2]
std::string etiss::CPUArch::getArchName () const
returns the name of this architecture.
this name was passed to the constructor and must match the returned string of LibraryInterface::nameCPUArch(unsigned)/YOURLIBRARY_nameCPUArch(unsigned)
Deprecated:
getBlockGlobalCode() [1/2]
std::string CPUArch::getBlockGlobalCode () virtual
get c++ code snippet that is placed at the top of a translated block
Definition at line 107 of file CPUArch.cpp.
getBlockGlobalCode() [2/2]
virtual std::string etiss::CPUArch::getBlockGlobalCode () virtual
get c++ code snippet that is placed at the top of a translated block
getGDBCore() [1/2]
etiss::plugin::gdb::GDBCore & CPUArch::getGDBCore () virtual
returns arch dependent gdb functions.
althought not required it is strongly recommended to implement this
Reimplemented in RISCV64Arch, RISCVArch, and OR1KArch.
Definition at line 138 of file CPUArch.cpp.
References gdbcore_.
Referenced by etiss::plugin::gdb::Server::handlePacket(), and etiss::plugin::gdb::Server::preInstructionCallback().
getGDBCore() [2/2]
virtual etiss::plugin::gdb::GDBCore& etiss::CPUArch::getGDBCore () virtual
returns arch dependent gdb functions.
althought not required it is strongly recommended to implement this
Reimplemented in RISCV64Arch, RISCVArch, and OR1KArch.
getHeaders() [1/2]
virtual const std::set<std::string>& etiss::CPUArch::getHeaders () const pure virtual
set of code header files e.g.
CustomCPU.h containing a cpu register structure needed to compile the generated code
Implemented in OR1KArch, RISCV64Arch, and RISCVArch.
getHeaders() [2/2]
virtual const std::set<std::string>& etiss::CPUArch::getHeaders () const pure virtual
set of code header files e.g.
CustomCPU.h containing a cpu register structure needed to compile the generated code
Implemented in OR1KArch, RISCV64Arch, and RISCVArch.
getIncludePath() [1/2]
std::string CPUArch::getIncludePath () virtual
returns a path that will be used to look up header files
Definition at line 143 of file CPUArch.cpp.
References etiss::cfg(), etiss::Configuration::get(), and getName().
Referenced by etiss::Translation::getBlock().
getIncludePath() [2/2]
virtual std::string etiss::CPUArch::getIncludePath () virtual
returns a path that will be used to look up header files
getInstructionSizeInBytes() [1/2]
virtual unsigned etiss::CPUArch::getInstructionSizeInBytes () pure virtual
size of one instruction/ smalest data unit for instructions of variable length
Implemented in OR1KArch, RISCV64Arch, and RISCVArch.
Referenced by getMaximumInstructionsPerMetaInstruction().
getInstructionSizeInBytes() [2/2]
virtual unsigned etiss::CPUArch::getInstructionSizeInBytes () pure virtual
size of one instruction/ smalest data unit for instructions of variable length
Implemented in OR1KArch, RISCV64Arch, and RISCVArch.
getMaximumInstructionSizeInBytes() [1/2]
virtual unsigned etiss::CPUArch::getMaximumInstructionSizeInBytes () pure virtual
used for variable instruction size and delay slots
Deprecated:
use getMaximumInstructionsPerMetaInstruction()
Implemented in OR1KArch, RISCV64Arch, and RISCVArch.
Referenced by getMaximumInstructionsPerMetaInstruction().
getMaximumInstructionSizeInBytes() [2/2]
virtual unsigned etiss::CPUArch::getMaximumInstructionSizeInBytes () pure virtual
used for variable instruction size and delay slots
Deprecated:
use getMaximumInstructionsPerMetaInstruction()
Implemented in OR1KArch, RISCV64Arch, and RISCVArch.
getMaximumInstructionsPerMetaInstruction() [1/2]
unsigned CPUArch::getMaximumInstructionsPerMetaInstruction () virtual
maximum number of instructions in a meta instruction
TODO update to remove deprecated function
Definition at line 112 of file CPUArch.cpp.
References getInstructionSizeInBytes(), and getMaximumInstructionSizeInBytes().
getMaximumInstructionsPerMetaInstruction() [2/2]
virtual unsigned etiss::CPUArch::getMaximumInstructionsPerMetaInstruction () virtual
maximum number of instructions in a meta instruction
getName() [1/2]
std::string etiss::CPUArch::getName () const inline
returns the name of this architecture.
this name was passed to the constructor and must match the returned string of LibraryInterface::nameCPUArch(unsigned)/YOURLIBRARY_nameCPUArch(unsigned)
Definition at line 183 of file CPUArch.h.
References getArchName().
Referenced by _getPluginName(), etiss::errorMessage(), getIncludePath(), and etiss::Translation::init().
getName() [2/2]
std::string etiss::CPUArch::getName () const inline
returns the name of this architecture.
this name was passed to the constructor and must match the returned string of LibraryInterface::nameCPUArch(unsigned)/YOURLIBRARY_nameCPUArch(unsigned)
Definition at line 183 of file CPUArch.h.
References getArchName().
getSuperInstructionCount() [1/2]
unsigned CPUArch::getSuperInstructionCount () virtual
fixed number of sub instructions per instruction (e.g.
thumb -> 2 16bit instructions per 1 32bit instruction)
Definition at line 118 of file CPUArch.cpp.
getSuperInstructionCount() [2/2]
virtual unsigned etiss::CPUArch::getSuperInstructionCount () virtual
fixed number of sub instructions per instruction (e.g.
thumb -> 2 16bit instructions per 1 32bit instruction)
handleException() [1/2]
virtual etiss::int32 etiss::CPUArch::handleException (etiss::int32 code, ETISS_CPU * cpu) virtual
translate/process exceptions that occur at runtime
Reimplemented in RISCV64Arch, OR1KArch, and RISCVArch.
handleException() [2/2]
etiss::int32 CPUArch::handleException (etiss::int32 code, ETISS_CPU * cpu) virtual
translate/process exceptions that occur at runtime
Reimplemented in RISCV64Arch, OR1KArch, and RISCVArch.
Definition at line 123 of file CPUArch.cpp.
Referenced by etiss_CPUCore_handleException().
newCPU() [1/2]
virtual ETISS_CPU* etiss::CPUArch::newCPU () pure virtual
allocate new cpu structure
Implemented in OR1KArch, RISCV64Arch, and RISCVArch.
newCPU() [2/2]
virtual ETISS_CPU* etiss::CPUArch::newCPU () pure virtual
allocate new cpu structure
Implemented in OR1KArch, RISCV64Arch, and RISCVArch.
newMMU() [1/2]
virtual etiss::mm::MMU* etiss::CPUArch::newMMU (ETISS_CPU * cpu) inline virtual
It is an interface to instanciate a Memory Management Unit.
Reimplemented in RISCV64Arch.
Definition at line 263 of file CPUArch.h.
newMMU() [2/2]
virtual etiss::mm::MMU* etiss::CPUArch::newMMU (ETISS_CPU * cpu) inline virtual
It is an interface to instanciate a Memory Management Unit.
Reimplemented in RISCV64Arch.
Definition at line 263 of file CPUArch.h.
resetCPU() [1/2]
virtual void etiss::CPUArch::resetCPU (ETISS_CPU * cpu, etiss::uint64 * startpointer) pure virtual
reset cpu (structure)
Implemented in OR1KArch, RISCV64Arch, and RISCVArch.
resetCPU() [2/2]
virtual void etiss::CPUArch::resetCPU (ETISS_CPU * cpu, etiss::uint64 * startpointer) pure virtual
reset cpu (structure)
Implemented in OR1KArch, RISCV64Arch, and RISCVArch.
unlikelyInstruction() [1/2]
virtual bool etiss::CPUArch::unlikelyInstruction (etiss::uint8 * instr, unsigned length, bool & ismetainstruction) virtual
return true if the given data is unlikely to be an instruction.
used for precompilation. default implementation returns true if data is all zeros
unlikelyInstruction() [2/2]
bool CPUArch::unlikelyInstruction (etiss::uint8 * instr, unsigned length, bool & ismetainstruction) virtual
return true if the given data is unlikely to be an instruction.
used for precompilation. default implementation returns true if data is all zeros
Definition at line 86 of file CPUArch.cpp.
References length().
Friends And Related Function Documentation
LibraryInterface
LibraryInterface friend
Definition at line 162 of file CPUArch.h.
Member Data Documentation
archname_
std::string etiss::CPUArch::archname_ private
Definition at line 271 of file CPUArch.h.
Referenced by getArchName().
gdbcore_
etiss::plugin::gdb::GDBCore etiss::CPUArch::gdbcore_ private
Definition at line 270 of file CPUArch.h.
Referenced by getGDBCore().
The documentation for this class was generated from the following files:
include/etiss/CPUArch.h
/home/runner/work/etiss/etiss/src/CPUArch.cpp