ETISS 0.8.0: CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter Class Reference
CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter Class Reference
Characterset conversion utility class to convert strings to the same format as is used for the storage.
#include <SimpleIni.h>
Public Member Functions
Converter (bool a_bStoreIsUtf8)
Converter (const Converter &rhs)
Converter & operator= (const Converter &rhs)
bool ConvertToStore (const SI_CHAR *a_pszString)
const char * Data ()
Converter (bool a_bStoreIsUtf8)
Converter (const Converter &rhs)
Converter & operator= (const Converter &rhs)
bool ConvertToStore (const SI_CHAR *a_pszString)
const char * Data ()
Private Attributes
std::string m_scratch
Detailed Description
template<class SI_CHAR, class SI_STRLESS, class SI_CONVERTER>
class CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter
Characterset conversion utility class to convert strings to the same format as is used for the storage.
Definition at line 426 of file SimpleIni.h.
Constructor & Destructor Documentation
Converter() [1/4]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::Converter (bool a_bStoreIsUtf8) inline
Definition at line 429 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::m_scratch.
Converter() [2/4]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::Converter (const Converter & rhs) inline
Definition at line 430 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::operator=().
Converter() [3/4]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::Converter (bool a_bStoreIsUtf8) inline
Definition at line 429 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::m_scratch.
Converter() [4/4]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::Converter (const Converter & rhs) inline
Definition at line 430 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::operator=().
Member Function Documentation
ConvertToStore() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::ConvertToStore (const SI_CHAR * a_pszString) inline
Definition at line 436 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::m_scratch.
Referenced by CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::OutputMultiLineText(), and CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Save().
ConvertToStore() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::ConvertToStore (const SI_CHAR * a_pszString) inline
Definition at line 436 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::m_scratch.
Data() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > const char* CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::Data () inline
Definition at line 449 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::m_scratch.
Data() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > const char* CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::Data () inline
Definition at line 449 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::m_scratch.
Referenced by CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::OutputMultiLineText(), and CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Save().
operator=() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > Converter& CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::operator= (const Converter & rhs) inline
Definition at line 431 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::m_scratch.
operator=() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > Converter& CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::operator= (const Converter & rhs) inline
Definition at line 431 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::m_scratch.
Referenced by CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::Converter().
Member Data Documentation
m_scratch
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > std::string CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::m_scratch private
Definition at line 452 of file SimpleIni.h.
Referenced by CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::Converter(), CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::ConvertToStore(), CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::Data(), and CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::operator=().
The documentation for this class was generated from the following file:
include/etiss/IntegratedLibrary/SimpleIni/SimpleIni.h