ETISS 0.8.0: etiss::instr::InstructionSet Class Reference
etiss::instr::InstructionSet Class Reference
holds etiss::instr::Instruction instances and handles automatic instruction tree creation.
#include <Instruction.h>
Public Member Functions
etiss_del_como (InstructionSet) VariableInstructionSet &parent_
InstructionSet (VariableInstructionSet &parent, unsigned width, const std::string &name)
~InstructionSet ()
Instruction * get (const OPCode &key)
Instruction & open (const OPCode &key, const std::string &name)
Instruction * create (const OPCode &key, const std::string &name)
template<typename T >
Instruction & open (T code, T val, const std::string &name)
bool compile ()
Instruction * resolve (BitArray &instr)
std::string print (std::string prefix, bool printunused=false)
Instruction & getInvalid ()
void foreach (std::function< void(Instruction &)> func)
size_t size ()
std::string toString () const
etiss_del_como (InstructionSet) VariableInstructionSet &parent_
InstructionSet (VariableInstructionSet &parent, unsigned width, const std::string &name)
~InstructionSet ()
Instruction * get (const OPCode &key)
Instruction & open (const OPCode &key, const std::string &name)
Instruction * create (const OPCode &key, const std::string &name)
template<typename T >
Instruction & open (T code, T val, const std::string &name)
bool compile ()
Instruction * resolve (BitArray &instr)
std::string print (std::string prefix, bool printunused=false)
Instruction & getInvalid ()
void foreach (std::function< void(Instruction &)> func)
size_t size ()
std::string toString () const
Public Member Functions inherited from etiss::ToString
ToString ()
virtual ~ToString ()
ToString ()
virtual ~ToString ()
Public Attributes
const std::string name_
const unsigned width_
Private Attributes
std::map< const OPCode *, Instruction *, etiss::instr::less > instrmap_
Node * root_
Instruction invalid
Detailed Description
holds etiss::instr::Instruction instances and handles automatic instruction tree creation.
 Location in an instruction translation tree:
    ModedInstructionSet
        ↳ VariableInstructionSet (e.g. for mode 0)
            ↳ InstructionSet (e.g. 32 bit)
                ↳ Node
                    ↳ ...                ↳ Node
                    ↳ ...                    ↳ ...
                        ↳ Instruction
            ↳ InstructionSet (e.g. 16 bit)
Definition at line 672 of file Instruction.h.
Constructor & Destructor Documentation
InstructionSet() [1/2]
etiss::instr::InstructionSet::InstructionSet (VariableInstructionSet & parent, unsigned width, const std::string & name)
Definition at line 876 of file Instruction.cpp.
References etiss::instr::Instruction::addCallback(), etiss::CodeSet::append(), etiss::CodePart::APPENDEDRETURNINGREQUIRED, etiss::instr::InstructionContext::current_address_, and invalid.
~InstructionSet() [1/2]
etiss::instr::InstructionSet::~InstructionSet ()
Definition at line 893 of file Instruction.cpp.
References instrmap_, and root_.
InstructionSet() [2/2]
etiss::instr::InstructionSet::InstructionSet (VariableInstructionSet & parent, unsigned width, const std::string & name)
~InstructionSet() [2/2]
etiss::instr::InstructionSet::~InstructionSet ()
Member Function Documentation
compile() [1/2]
bool etiss::instr::InstructionSet::compile ()
Definition at line 947 of file Instruction.cpp.
References etiss::instr::Node::compile(), etiss::ERROR, instrmap_, etiss::log(), root_, etiss::instr::BitArray::setAll(), etiss::WARNING, and width_.
compile() [2/2]
bool etiss::instr::InstructionSet::compile ()
create() [1/2]
Instruction* etiss::instr::InstructionSet::create (const OPCode & key, const std::string & name)
create() [2/2]
Instruction * etiss::instr::InstructionSet::create (const OPCode & key, const std::string & name)
Definition at line 930 of file Instruction.cpp.
References etiss::ERROR, instrmap_, etiss::log(), name, and etiss::instr::Instruction::opc_.
Referenced by etiss::instr::InstructionGroup::addTo(), and open().
etiss_del_como() [1/2]
etiss::instr::InstructionSet::etiss_del_como (InstructionSet) &
etiss_del_como() [2/2]
etiss::instr::InstructionSet::etiss_del_como (InstructionSet) &
foreach() [1/2]
void etiss::instr::InstructionSet::foreach (std::function< void(Instruction &)> func)
Definition at line 1004 of file Instruction.cpp.
References etiss::ERROR, instrmap_, and etiss::log().
Referenced by CPUArch_finalizeInstrSet(), etiss::plugin::PrintInstruction::finalizeInstrSet(), etiss::plugin::VariableValueLogger::finalizeInstrSet(), etiss::plugin::InstructionAccurateCallback::finalizeInstrSet(), etiss::plugin::InstructionSpecificAddressCallback::finalizeInstrSet(), etiss::DataSheetAccurateTiming::initInstrSet(), and Server_finalizeInstrSet().
foreach() [2/2]
void etiss::instr::InstructionSet::foreach (std::function< void(Instruction &)> func)
get() [1/2]
Instruction * etiss::instr::InstructionSet::get (const OPCode & key)
Definition at line 907 of file Instruction.cpp.
References instrmap_.
Referenced by open(), and etiss::Translation::translateBlock().
get() [2/2]
Instruction* etiss::instr::InstructionSet::get (const OPCode & key)
getInvalid() [1/2]
Instruction & etiss::instr::InstructionSet::getInvalid ()
Definition at line 999 of file Instruction.cpp.
References invalid.
Referenced by etiss::Translation::translateBlock().
getInvalid() [2/2]
Instruction& etiss::instr::InstructionSet::getInvalid ()
open() [1/4]
Instruction & etiss::instr::InstructionSet::open (const OPCode & key, const std::string & name)
Definition at line 916 of file Instruction.cpp.
References create(), etiss_log, etiss::FATALERROR, get(), and name.
Referenced by open(), and etiss::instr::VariableInstructionSet::open().
open() [2/4]
Instruction& etiss::instr::InstructionSet::open (const OPCode & key, const std::string & name)
open() [3/4]
template<typename T > Instruction& etiss::instr::InstructionSet::open (T code, T val, const std::string & name) inline
Definition at line 690 of file Instruction.h.
References name, open(), and width_.
open() [4/4]
template<typename T > Instruction& etiss::instr::InstructionSet::open (T code, T val, const std::string & name) inline
Definition at line 690 of file Instruction.h.
References name, open(), and width_.
print() [1/2]
std::string etiss::instr::InstructionSet::print (std::string prefix, bool printunused = false)
Definition at line 984 of file Instruction.cpp.
References name_, etiss::instr::Node::print(), root_, and width_.
Referenced by etiss::instr::VariableInstructionSet::print().
print() [2/2]
std::string etiss::instr::InstructionSet::print (std::string prefix, bool printunused = false)
resolve() [1/2]
Instruction * etiss::instr::InstructionSet::resolve (BitArray & instr)
Definition at line 979 of file Instruction.cpp.
References etiss::instr::Node::resolve(), and root_.
Referenced by etiss::Translation::disasm(), and etiss::Translation::translateBlock().
resolve() [2/2]
Instruction* etiss::instr::InstructionSet::resolve (BitArray & instr)
size() [1/2]
size_t etiss::instr::InstructionSet::size ()
Definition at line 1023 of file Instruction.cpp.
References instrmap_.
size() [2/2]
size_t etiss::instr::InstructionSet::size ()
toString() [1/2]
std::string etiss::instr::InstructionSet::toString () const inline
Definition at line 707 of file Instruction.h.
References name_.
toString() [2/2]
std::string etiss::instr::InstructionSet::toString () const inline
Definition at line 707 of file Instruction.h.
References name_.
Member Data Documentation
instrmap_
std::map< const OPCode *, Instruction *, etiss::instr::less > etiss::instr::InstructionSet::instrmap_ private
Definition at line 710 of file Instruction.h.
Referenced by compile(), create(), foreach(), get(), size(), and ~InstructionSet().
invalid
Instruction etiss::instr::InstructionSet::invalid private
Definition at line 714 of file Instruction.h.
Referenced by getInvalid(), and InstructionSet().
name_
const std::string etiss::instr::InstructionSet::name_
Definition at line 679 of file Instruction.h.
Referenced by print(), and toString().
root_
Node * etiss::instr::InstructionSet::root_ private
Definition at line 712 of file Instruction.h.
Referenced by compile(), print(), resolve(), and ~InstructionSet().
width_
const unsigned etiss::instr::InstructionSet::width_
Definition at line 680 of file Instruction.h.
Referenced by compile(), open(), and print().
The documentation for this class was generated from the following files:
include/etiss/Instruction.h
/home/runner/work/etiss/etiss/src/Instruction.cpp