ETISS 0.8.0: etiss::mm::PTE Class Reference
etiss::mm::PTE Class Reference
Page Table Entry (PTE) defines the composition of Page Frame Number (PFN) and relavant flags.
#include <PTE.h>
Public Member Functions
PTE ()
PTE (uint64_t pte)
void Update (uint64_t new_pte)
Update the PTE with a new value.
uint64_t GetByName (std::string const name) const
Get the bit field value with its name.
void SetFlagByName (std::string name, uint64_t val)
Set the bit field value with its name.
void ClearFlagByName (std::string name)
Clear the bit field value with its name.
void Dump ()
Dump the details of the PTE entry.
uint64_t Get () const
uint64_t GetPPN () const
PTE ()
PTE (uint64_t pte)
void Update (uint64_t new_pte)
Update the PTE with a new value.
uint64_t GetByName (std::string const name) const
Get the bit field value with its name.
void SetFlagByName (std::string name, uint64_t val)
Set the bit field value with its name.
void ClearFlagByName (std::string name)
Clear the bit field value with its name.
void Dump ()
Dump the details of the PTE entry.
uint64_t Get () const
uint64_t GetPPN () const
Private Member Functions
uint64_t GenerateMask (uint64_t len) const
void SetBit (uint32_t pos)
void ClearBit (uint32_t pos)
bool CheckBit (uint32_t pos) const
uint64_t GenerateMask (uint64_t len) const
void SetBit (uint32_t pos)
void ClearBit (uint32_t pos)
bool CheckBit (uint32_t pos) const
Private Attributes
uint64_t ppn_val_
uint64_t pte_val_
Detailed Description
Page Table Entry (PTE) defines the composition of Page Frame Number (PFN) and relavant flags.
A PTE contains page frame number (pfn) and protection flags. PTEFormat is used to record bit field of PFR and flags in PTE raw value.PFN or flags could be read/write with help of PTEFormat, which could be built up by its builder utility.
Definition at line 68 of file PTE.h.
Constructor & Destructor Documentation
PTE() [1/4]
etiss::mm::PTE::PTE () inline
Definition at line 71 of file PTE.h.
PTE() [2/4]
etiss::mm::PTE::PTE (uint64_t pte) inline
Definition at line 73 of file PTE.h.
References Update().
PTE() [3/4]
etiss::mm::PTE::PTE () inline
Definition at line 71 of file PTE.h.
PTE() [4/4]
etiss::mm::PTE::PTE (uint64_t pte) inline
Definition at line 73 of file PTE.h.
References Update().
Member Function Documentation
CheckBit() [1/2]
bool etiss::mm::PTE::CheckBit (uint32_t pos) const inline private
Definition at line 136 of file PTE.h.
References pte_val_, and true.
CheckBit() [2/2]
bool etiss::mm::PTE::CheckBit (uint32_t pos) const inline private
Definition at line 136 of file PTE.h.
References pte_val_, and true.
ClearBit() [1/2]
void etiss::mm::PTE::ClearBit (uint32_t pos) inline private
Definition at line 134 of file PTE.h.
References pte_val_.
Referenced by ClearFlagByName().
ClearBit() [2/2]
void etiss::mm::PTE::ClearBit (uint32_t pos) inline private
Definition at line 134 of file PTE.h.
References pte_val_.
ClearFlagByName() [1/2]
void etiss::mm::PTE::ClearFlagByName (std::string name)
Clear the bit field value with its name.
Definition at line 124 of file PTE.cpp.
References ClearBit(), etiss::mm::PTEFormat::Dump(), etiss::FATALERROR, etiss::mm::PTEFormat::GetFormatMap(), etiss::mm::PTEFormat::Instance(), etiss::log(), and name.
ClearFlagByName() [2/2]
void etiss::mm::PTE::ClearFlagByName (std::string name)
Clear the bit field value with its name.
Dump() [1/2]
void etiss::mm::PTE::Dump ()
Dump the details of the PTE entry.
Dump() [2/2]
void etiss::mm::PTE::Dump ()
Dump the details of the PTE entry.
Definition at line 143 of file PTE.cpp.
References etiss::mm::PTEFormat::DumpBitFild(), GetByName(), etiss::mm::PTEFormat::GetFormatMap(), etiss::mm::PTEFormat::GetPTELength(), etiss::mm::PTEFormat::Instance(), name, and pte_val_.
GenerateMask() [1/2]
uint64_t etiss::mm::PTE::GenerateMask (uint64_t len) const inline private
Definition at line 122 of file PTE.h.
Referenced by GetByName(), and Update().
GenerateMask() [2/2]
uint64_t etiss::mm::PTE::GenerateMask (uint64_t len) const inline private
Definition at line 122 of file PTE.h.
Get() [1/2]
uint64_t etiss::mm::PTE::Get () const inline
Definition at line 117 of file PTE.h.
References pte_val_.
Get() [2/2]
uint64_t etiss::mm::PTE::Get () const inline
Definition at line 117 of file PTE.h.
References pte_val_.
Referenced by RISCV64MMU::WalkPageTable().
GetByName() [1/2]
uint64_t etiss::mm::PTE::GetByName (std::string const name) const
Get the bit field value with its name.
Definition at line 87 of file PTE.cpp.
References etiss::mm::PTEFormat::Dump(), etiss::FATALERROR, GenerateMask(), etiss::mm::PTEFormat::GetFormatMap(), etiss::mm::PTEFormat::Instance(), etiss::log(), name, and pte_val_.
Referenced by RISCV64MMU::CheckProtection(), Dump(), and RISCV64MMU::WalkPageTable().
GetByName() [2/2]
uint64_t etiss::mm::PTE::GetByName (std::string const name) const
Get the bit field value with its name.
GetPPN() [1/2]
uint64_t etiss::mm::PTE::GetPPN () const inline
Definition at line 119 of file PTE.h.
References ppn_val_.
GetPPN() [2/2]
uint64_t etiss::mm::PTE::GetPPN () const inline
Definition at line 119 of file PTE.h.
References ppn_val_.
Referenced by etiss::mm::MMU::Translate().
SetBit() [1/2]
void etiss::mm::PTE::SetBit (uint32_t pos) inline private
Definition at line 132 of file PTE.h.
References pte_val_.
Referenced by SetFlagByName().
SetBit() [2/2]
void etiss::mm::PTE::SetBit (uint32_t pos) inline private
Definition at line 132 of file PTE.h.
References pte_val_.
SetFlagByName() [1/2]
void etiss::mm::PTE::SetFlagByName (std::string name, uint64_t val)
Set the bit field value with its name.
SetFlagByName() [2/2]
void etiss::mm::PTE::SetFlagByName (std::string name, uint64_t val)
Set the bit field value with its name.
Definition at line 104 of file PTE.cpp.
References etiss::mm::PTEFormat::Dump(), etiss::FATALERROR, etiss::mm::PTEFormat::GetFormatMap(), etiss::mm::PTEFormat::Instance(), etiss::log(), name, and SetBit().
Update() [1/2]
void etiss::mm::PTE::Update (uint64_t new_pte)
Update the PTE with a new value.
Update() [2/2]
void etiss::mm::PTE::Update (uint64_t new_pte)
Update the PTE with a new value.
Definition at line 62 of file PTE.cpp.
References etiss::mm::PTEFormat::Dump(), etiss::FATALERROR, GenerateMask(), etiss::mm::PTEFormat::GetFormatMap(), etiss::mm::PTEFormat::GetPTELength(), etiss::mm::PTEFormat::Instance(), etiss::log(), ppn_val_, and pte_val_.
Referenced by PTE(), and RISCV64MMU::WalkPageTable().
Member Data Documentation
ppn_val_
uint64_t etiss::mm::PTE::ppn_val_ private
Definition at line 138 of file PTE.h.
Referenced by GetPPN(), and Update().
pte_val_
uint64_t etiss::mm::PTE::pte_val_ private
Definition at line 139 of file PTE.h.
Referenced by CheckBit(), ClearBit(), Dump(), Get(), GetByName(), SetBit(), and Update().
The documentation for this class was generated from the following files:
include/etiss/mm/PTE.h
/home/runner/work/etiss/etiss/src/mm/PTE.cpp