ETISS 0.8.0: pugi::xml_attribute Class Reference
pugi::xml_attribute Class Reference
#include <pugixml.hpp>
Public Member Functions
xml_attribute ()
xml_attribute (xml_attribute_struct *attr)
operator unspecified_bool_type () const
bool operator! () const
bool operator== (const xml_attribute &r) const
bool operator!= (const xml_attribute &r) const
bool operator< (const xml_attribute &r) const
bool operator> (const xml_attribute &r) const
bool operator<= (const xml_attribute &r) const
bool operator>= (const xml_attribute &r) const
bool empty () const
const char_t * name () const
const char_t * value () const
const char_t * as_string (const char_t *def=PUGIXML_TEXT("")) const
int as_int (int def=0) const
unsigned int as_uint (unsigned int def=0) const
double as_double (double def=0) const
float as_float (float def=0) const
bool as_bool (bool def=false) const
bool set_name (const char_t *rhs)
bool set_value (const char_t *rhs)
bool set_value (int rhs)
bool set_value (unsigned int rhs)
bool set_value (double rhs)
bool set_value (bool rhs)
xml_attribute & operator= (const char_t *rhs)
xml_attribute & operator= (int rhs)
xml_attribute & operator= (unsigned int rhs)
xml_attribute & operator= (double rhs)
xml_attribute & operator= (bool rhs)
xml_attribute next_attribute () const
xml_attribute previous_attribute () const
size_t hash_value () const
xml_attribute_struct * internal_object () const
xml_attribute ()
xml_attribute (xml_attribute_struct *attr)
operator unspecified_bool_type () const
bool operator! () const
bool operator== (const xml_attribute &r) const
bool operator!= (const xml_attribute &r) const
bool operator< (const xml_attribute &r) const
bool operator> (const xml_attribute &r) const
bool operator<= (const xml_attribute &r) const
bool operator>= (const xml_attribute &r) const
bool empty () const
const char_t * name () const
const char_t * value () const
const char_t * as_string (const char_t *def=PUGIXML_TEXT("")) const
int as_int (int def=0) const
unsigned int as_uint (unsigned int def=0) const
double as_double (double def=0) const
float as_float (float def=0) const
bool as_bool (bool def=false) const
bool set_name (const char_t *rhs)
bool set_value (const char_t *rhs)
bool set_value (int rhs)
bool set_value (unsigned int rhs)
bool set_value (double rhs)
bool set_value (bool rhs)
xml_attribute & operator= (const char_t *rhs)
xml_attribute & operator= (int rhs)
xml_attribute & operator= (unsigned int rhs)
xml_attribute & operator= (double rhs)
xml_attribute & operator= (bool rhs)
xml_attribute next_attribute () const
xml_attribute previous_attribute () const
size_t hash_value () const
xml_attribute_struct * internal_object () const
Private Types
typedef void(* unspecified_bool_type) (xml_attribute ***)
typedef void(* unspecified_bool_type) (xml_attribute ***)
Private Attributes
xml_attribute_struct * _attr
Friends
class xml_attribute_iterator
class xml_node
Detailed Description
Definition at line 296 of file pugixml.hpp.
Member Typedef Documentation
unspecified_bool_type [1/2]
typedef void(* pugi::xml_attribute::unspecified_bool_type) (xml_attribute ***) private
Definition at line 304 of file pugixml.hpp.
unspecified_bool_type [2/2]
typedef void(* pugi::xml_attribute::unspecified_bool_type) (xml_attribute ***) private
Definition at line 304 of file pugixml.hpp.
Constructor & Destructor Documentation
xml_attribute() [1/4]
PUGI__FN pugi::xml_attribute::xml_attribute ()
Definition at line 4332 of file pugixml.cpp.
Referenced by next_attribute(), and previous_attribute().
xml_attribute() [2/4]
PUGI__FN pugi::xml_attribute::xml_attribute (xml_attribute_struct * attr) explicit
Definition at line 4334 of file pugixml.cpp.
xml_attribute() [3/4]
pugi::xml_attribute::xml_attribute ()
xml_attribute() [4/4]
pugi::xml_attribute::xml_attribute (xml_attribute_struct * attr) explicit
Member Function Documentation
as_bool() [1/2]
PUGI__FN bool pugi::xml_attribute::as_bool (bool def = false) const
Definition at line 4413 of file pugixml.cpp.
References _attr, get_value_bool(), and pugi::xml_attribute_struct::value.
as_bool() [2/2]
bool pugi::xml_attribute::as_bool (bool def = false) const
as_double() [1/2]
PUGI__FN double pugi::xml_attribute::as_double (double def = 0) const
Definition at line 4403 of file pugixml.cpp.
References _attr, get_value_double(), and pugi::xml_attribute_struct::value.
as_double() [2/2]
double pugi::xml_attribute::as_double (double def = 0) const
as_float() [1/2]
PUGI__FN float pugi::xml_attribute::as_float (float def = 0) const
Definition at line 4408 of file pugixml.cpp.
References _attr, get_value_float(), and pugi::xml_attribute_struct::value.
as_float() [2/2]
float pugi::xml_attribute::as_float (float def = 0) const
as_int() [1/2]
int pugi::xml_attribute::as_int (int def = 0) const
as_int() [2/2]
PUGI__FN int pugi::xml_attribute::as_int (int def = 0) const
Definition at line 4393 of file pugixml.cpp.
References _attr, get_value_int(), and pugi::xml_attribute_struct::value.
as_string() [1/2]
const char_t* pugi::xml_attribute::as_string (const char_t * def = PUGIXML_TEXT("")) const
as_string() [2/2]
const PUGI__FN char_t * pugi::xml_attribute::as_string (const char_t * def = PUGIXML_TEXT("")) const
Definition at line 4388 of file pugixml.cpp.
References _attr, and pugi::xml_attribute_struct::value.
as_uint() [1/2]
unsigned int pugi::xml_attribute::as_uint (unsigned int def = 0) const
as_uint() [2/2]
PUGI__FN unsigned int pugi::xml_attribute::as_uint (unsigned int def = 0) const
Definition at line 4398 of file pugixml.cpp.
References _attr, get_value_uint(), and pugi::xml_attribute_struct::value.
empty() [1/2]
bool pugi::xml_attribute::empty () const
empty() [2/2]
PUGI__FN bool pugi::xml_attribute::empty () const
Definition at line 4430 of file pugixml.cpp.
References _attr.
Referenced by pugi::xml_node::insert_attribute_after(), and pugi::xml_node::insert_attribute_before().
hash_value() [1/2]
size_t pugi::xml_attribute::hash_value () const
hash_value() [2/2]
PUGI__FN size_t pugi::xml_attribute::hash_value () const
Definition at line 4445 of file pugixml.cpp.
References _attr.
internal_object() [1/2]
PUGI__FN xml_attribute_struct * pugi::xml_attribute::internal_object () const
Definition at line 4450 of file pugixml.cpp.
References _attr.
internal_object() [2/2]
xml_attribute_struct* pugi::xml_attribute::internal_object () const
name() [1/2]
const PUGI__FN char_t * pugi::xml_attribute::name () const
Definition at line 4435 of file pugixml.cpp.
References _attr, pugi::xml_attribute_struct::name, and PUGIXML_TEXT.
Referenced by pugi::xml_node::append_copy(), pugi::xml_node::insert_copy_after(), pugi::xml_node::insert_copy_before(), and pugi::xml_node::prepend_copy().
name() [2/2]
const char_t* pugi::xml_attribute::name () const
next_attribute() [1/2]
PUGI__FN xml_attribute pugi::xml_attribute::next_attribute () const
Definition at line 4378 of file pugixml.cpp.
References _attr, pugi::xml_attribute_struct::next_attribute, and xml_attribute().
Referenced by pugi::xml_node::find_attribute(), and etiss::fault::xml::getAttribute().
next_attribute() [2/2]
xml_attribute pugi::xml_attribute::next_attribute () const
operator unspecified_bool_type() [1/2]
pugi::xml_attribute::operator unspecified_bool_type () const
operator unspecified_bool_type() [2/2]
PUGI__FN pugi::xml_attribute::operator xml_attribute::unspecified_bool_type () const
Definition at line 4338 of file pugixml.cpp.
References _attr, and pugi::unspecified_bool_xml_attribute().
operator!() [1/2]
PUGI__FN bool pugi::xml_attribute::operator! () const
Definition at line 4343 of file pugixml.cpp.
References _attr.
operator!() [2/2]
bool pugi::xml_attribute::operator! () const
operator!=() [1/2]
PUGI__FN bool pugi::xml_attribute::operator!= (const xml_attribute & r) const
Definition at line 4353 of file pugixml.cpp.
References _attr.
operator!=() [2/2]
bool pugi::xml_attribute::operator!= (const xml_attribute & r) const
operator<() [1/2]
bool pugi::xml_attribute::operator< (const xml_attribute & r) const
operator<() [2/2]
PUGI__FN bool pugi::xml_attribute::operator< (const xml_attribute & r) const
Definition at line 4358 of file pugixml.cpp.
References _attr.
operator<=() [1/2]
bool pugi::xml_attribute::operator<= (const xml_attribute & r) const
operator<=() [2/2]
PUGI__FN bool pugi::xml_attribute::operator<= (const xml_attribute & r) const
Definition at line 4368 of file pugixml.cpp.
References _attr.
operator=() [1/10]
xml_attribute& pugi::xml_attribute::operator= (bool rhs)
operator=() [2/10]
PUGI__FN xml_attribute & pugi::xml_attribute::operator= (bool rhs)
Definition at line 4479 of file pugixml.cpp.
References set_value().
operator=() [3/10]
PUGI__FN xml_attribute & pugi::xml_attribute::operator= (const char_t * rhs)
Definition at line 4455 of file pugixml.cpp.
References set_value().
operator=() [4/10]
xml_attribute& pugi::xml_attribute::operator= (const char_t * rhs)
operator=() [5/10]
xml_attribute& pugi::xml_attribute::operator= (double rhs)
operator=() [6/10]
PUGI__FN xml_attribute & pugi::xml_attribute::operator= (double rhs)
Definition at line 4473 of file pugixml.cpp.
References set_value().
operator=() [7/10]
xml_attribute& pugi::xml_attribute::operator= (int rhs)
operator=() [8/10]
PUGI__FN xml_attribute & pugi::xml_attribute::operator= (int rhs)
Definition at line 4461 of file pugixml.cpp.
References set_value().
operator=() [9/10]
PUGI__FN xml_attribute & pugi::xml_attribute::operator= (unsigned int rhs)
Definition at line 4467 of file pugixml.cpp.
References set_value().
operator=() [10/10]
xml_attribute& pugi::xml_attribute::operator= (unsigned int rhs)
operator==() [1/2]
bool pugi::xml_attribute::operator== (const xml_attribute & r) const
operator==() [2/2]
PUGI__FN bool pugi::xml_attribute::operator== (const xml_attribute & r) const
Definition at line 4348 of file pugixml.cpp.
References _attr.
operator>() [1/2]
bool pugi::xml_attribute::operator> (const xml_attribute & r) const
operator>() [2/2]
PUGI__FN bool pugi::xml_attribute::operator> (const xml_attribute & r) const
Definition at line 4363 of file pugixml.cpp.
References _attr.
operator>=() [1/2]
PUGI__FN bool pugi::xml_attribute::operator>= (const xml_attribute & r) const
Definition at line 4373 of file pugixml.cpp.
References _attr.
operator>=() [2/2]
bool pugi::xml_attribute::operator>= (const xml_attribute & r) const
previous_attribute() [1/2]
xml_attribute pugi::xml_attribute::previous_attribute () const
previous_attribute() [2/2]
PUGI__FN xml_attribute pugi::xml_attribute::previous_attribute () const
Definition at line 4383 of file pugixml.cpp.
References _attr, pugi::xml_attribute_struct::next_attribute, pugi::xml_attribute_struct::prev_attribute_c, and xml_attribute().
Referenced by pugi::xml_attribute_iterator::operator--().
set_name() [1/2]
PUGI__FN bool pugi::xml_attribute::set_name (const char_t * rhs)
Definition at line 4499 of file pugixml.cpp.
References _attr, pugi::xml_attribute_struct::header, pugi::xml_attribute_struct::name, strcpy_insitu(), and xml_memory_page_name_allocated_mask.
Referenced by pugi::xml_node::append_attribute(), pugi::xml_node::insert_attribute_after(), pugi::xml_node::insert_attribute_before(), and pugi::xml_node::prepend_attribute().
set_name() [2/2]
bool pugi::xml_attribute::set_name (const char_t * rhs)
set_value() [1/10]
bool pugi::xml_attribute::set_value (bool rhs)
set_value() [2/10]
PUGI__FN bool pugi::xml_attribute::set_value (bool rhs)
Definition at line 4539 of file pugixml.cpp.
References _attr, pugi::xml_attribute_struct::header, set_value_convert(), pugi::xml_attribute_struct::value, and xml_memory_page_value_allocated_mask.
set_value() [3/10]
PUGI__FN bool pugi::xml_attribute::set_value (const char_t * rhs)
Definition at line 4507 of file pugixml.cpp.
References _attr, pugi::xml_attribute_struct::header, strcpy_insitu(), pugi::xml_attribute_struct::value, and xml_memory_page_value_allocated_mask.
Referenced by pugi::xml_node::append_copy(), pugi::xml_node::insert_copy_after(), pugi::xml_node::insert_copy_before(), operator=(), pugi::xml_node::prepend_copy(), and etiss::fault::xml::setAttribute().
set_value() [4/10]
bool pugi::xml_attribute::set_value (const char_t * rhs)
set_value() [5/10]
PUGI__FN bool pugi::xml_attribute::set_value (double rhs)
Definition at line 4531 of file pugixml.cpp.
References _attr, pugi::xml_attribute_struct::header, set_value_convert(), pugi::xml_attribute_struct::value, and xml_memory_page_value_allocated_mask.
set_value() [6/10]
bool pugi::xml_attribute::set_value (double rhs)
set_value() [7/10]
bool pugi::xml_attribute::set_value (int rhs)
set_value() [8/10]
PUGI__FN bool pugi::xml_attribute::set_value (int rhs)
Definition at line 4515 of file pugixml.cpp.
References _attr, pugi::xml_attribute_struct::header, set_value_convert(), pugi::xml_attribute_struct::value, and xml_memory_page_value_allocated_mask.
set_value() [9/10]
bool pugi::xml_attribute::set_value (unsigned int rhs)
set_value() [10/10]
PUGI__FN bool pugi::xml_attribute::set_value (unsigned int rhs)
Definition at line 4523 of file pugixml.cpp.
References _attr, pugi::xml_attribute_struct::header, set_value_convert(), pugi::xml_attribute_struct::value, and xml_memory_page_value_allocated_mask.
value() [1/2]
const char_t* pugi::xml_attribute::value () const
value() [2/2]
const PUGI__FN char_t * pugi::xml_attribute::value () const
Definition at line 4440 of file pugixml.cpp.
References _attr, PUGIXML_TEXT, and pugi::xml_attribute_struct::value.
Referenced by pugi::xml_node::append_copy(), pugi::xml_node::insert_copy_after(), pugi::xml_node::insert_copy_before(), and pugi::xml_node::prepend_copy().
Friends And Related Function Documentation
xml_attribute_iterator
xml_attribute_iterator friend
Definition at line 298 of file pugixml.hpp.
xml_node
xml_node friend
Definition at line 299 of file pugixml.hpp.
Member Data Documentation
_attr
xml_attribute_struct * pugi::xml_attribute::_attr private
Definition at line 302 of file pugixml.hpp.
Referenced by as_bool(), as_double(), as_float(), as_int(), as_string(), as_uint(), empty(), hash_value(), pugi::xml_node::insert_attribute_after(), pugi::xml_node::insert_attribute_before(), internal_object(), name(), next_attribute(), operator unspecified_bool_type(), operator!(), operator!=(), pugi::xml_attribute_iterator::operator!=(), pugi::xml_attribute_iterator::operator*(), pugi::xml_attribute_iterator::operator++(), pugi::xml_attribute_iterator::operator--(), pugi::xml_attribute_iterator::operator->(), operator<(), operator<=(), operator==(), pugi::xml_attribute_iterator::operator==(), operator>(), operator>=(), pugi::xml_node::prepend_attribute(), previous_attribute(), pugi::xml_node::remove_attribute(), set_name(), set_value(), and value().
The documentation for this class was generated from the following files:
include/etiss/fault/xml/pugixml.hpp
/home/runner/work/etiss/etiss/src/fault/xml/pugixml.cpp