ETISS 0.8.0: etiss::instr::InstructionCollection Class Reference
etiss::instr::InstructionCollection Class Reference
maps to ModedInstructionSet
#include <Instruction.h>
Public Member Functions
template<typename... T>
etiss_del_como(InstructionCollection) const std InstructionCollection (const std::string &name, InstructionClass &class1, T &... otherclasses)
void foreach (std::function< void(InstructionClass &)> call)
void addTo (ModedInstructionSet &set, bool &ok)
template<typename... T>
etiss_del_como(InstructionCollection) const std InstructionCollection (const std::string &name, InstructionClass &class1, T &... otherclasses)
void foreach (std::function< void(InstructionClass &)> call)
void addTo (ModedInstructionSet &set, bool &ok)
Private Member Functions
template<typename... T>
void add (InstructionClass &klass, T &... args)
void add ()
template<typename... T>
void add (InstructionClass &klass, T &... args)
void add ()
Private Attributes
std::set< InstructionClass * > classes_
Detailed Description
maps to ModedInstructionSet
Definition at line 858 of file Instruction.h.
Constructor & Destructor Documentation
InstructionCollection() [1/2]
template<typename... T> etiss_del_como (InstructionCollection) const std etiss::instr::InstructionCollection::InstructionCollection (const std::string & name, InstructionClass & class1, T &... otherclasses) const inline
Definition at line 875 of file Instruction.h.
References add().
InstructionCollection() [2/2]
template<typename... T> etiss_del_como (InstructionCollection) const std etiss::instr::InstructionCollection::InstructionCollection (const std::string & name, InstructionClass & class1, T &... otherclasses) const inline
Definition at line 875 of file Instruction.h.
References add().
Member Function Documentation
add() [1/4]
void etiss::instr::InstructionCollection::add () inline private
Definition at line 868 of file Instruction.h.
Referenced by add(), and InstructionCollection().
add() [2/4]
void etiss::instr::InstructionCollection::add () inline private
Definition at line 868 of file Instruction.h.
add() [3/4]
template<typename... T> void etiss::instr::InstructionCollection::add (InstructionClass & klass, T &... args) inline private
Definition at line 863 of file Instruction.h.
References add(), and classes_.
add() [4/4]
template<typename... T> void etiss::instr::InstructionCollection::add (InstructionClass & klass, T &... args) inline private
Definition at line 863 of file Instruction.h.
References add(), and classes_.
addTo() [1/2]
void etiss::instr::InstructionCollection::addTo (ModedInstructionSet & set, bool & ok)
Definition at line 1210 of file Instruction.cpp.
References etiss::instr::InstructionClass::addTo(), etiss::instr::InstructionClass::mode_, etiss::instr::InstructionClass::name_, etiss::instr::ModedInstructionSet::open(), and etiss::instr::InstructionClass::width_.
Referenced by OR1KArch::initInstrSet(), RISCVArch::initInstrSet(), and RISCV64Arch::initInstrSet().
addTo() [2/2]
void etiss::instr::InstructionCollection::addTo (ModedInstructionSet & set, bool & ok)
foreach() [1/2]
void etiss::instr::InstructionCollection::foreach (std::function< void(InstructionClass &)> call) inline
Definition at line 879 of file Instruction.h.
References classes_.
foreach() [2/2]
void etiss::instr::InstructionCollection::foreach (std::function< void(InstructionClass &)> call) inline
Definition at line 879 of file Instruction.h.
References classes_.
Member Data Documentation
classes_
std::set< InstructionClass * > etiss::instr::InstructionCollection::classes_ private
Definition at line 861 of file Instruction.h.
Referenced by add(), and foreach().
The documentation for this class was generated from the following files:
include/etiss/Instruction.h
/home/runner/work/etiss/etiss/src/Instruction.cpp