ETISS 0.8.0: etiss::instr::Node Class Reference
etiss::instr::Node Class Reference
base class that is used to build the instruction translation tree within an InstructionSet object
#include <Instruction.h>
Public Member Functions
Node ()
ctor
virtual ~Node ()
dtor
virtual void compile (const std::map< const OPCode *, Instruction *, etiss::instr::less > &instrmap_, const BitArray &used, bool &ok, std::list< std::string > &warnings, std::list< std::string > &errors)
called by InstructionSet::compile() calls Node::compile() of sub nodes
virtual Instruction * resolve (BitArray &instr)
performs a lookup for the matching Instruction for the passed instruction in the bit array.
virtual bool isInstruction ()
returns true if this object is an instance of etiss::instr::Instruction
virtual std::string print (std::string indent, I pos, unsigned pfillwidth, bool printunused=false)
recursive print function to produce a human readable text that represents the structure of this node and sub nodes
Node ()
ctor
virtual ~Node ()
dtor
virtual void compile (const std::map< const OPCode *, Instruction *, etiss::instr::less > &instrmap_, const BitArray &used, bool &ok, std::list< std::string > &warnings, std::list< std::string > &errors)
called by InstructionSet::compile() calls Node::compile() of sub nodes
virtual Instruction * resolve (BitArray &instr)
performs a lookup for the matching Instruction for the passed instruction in the bit array.
virtual bool isInstruction ()
returns true if this object is an instance of etiss::instr::Instruction
virtual std::string print (std::string indent, I pos, unsigned pfillwidth, bool printunused=false)
recursive print function to produce a human readable text that represents the structure of this node and sub nodes
Private Member Functions
etiss_del_como (Node) Node **subs_
no copy/moce operations
etiss_del_como (Node) Node **subs_
no copy/moce operations
Private Attributes
BitArrayRange * reader_
reader to extract the bits to identify a sub node
Detailed Description
base class that is used to build the instruction translation tree within an InstructionSet object
Attention
any change to virtual functions must be applied to etiss::instr::Instruction aswell
Definition at line 481 of file Instruction.h.
Constructor & Destructor Documentation
Node() [1/2]
etiss::instr::Node::Node ()
ctor
Definition at line 507 of file Instruction.cpp.
Referenced by compile().
~Node() [1/2]
etiss::instr::Node::~Node () virtual
dtor
Definition at line 508 of file Instruction.cpp.
References etiss::instr::BitArrayRange::end(), isInstruction(), reader_, and etiss::instr::BitArrayRange::start().
Node() [2/2]
etiss::instr::Node::Node ()
ctor
~Node() [2/2]
virtual etiss::instr::Node::~Node () virtual
dtor
Member Function Documentation
compile() [1/2]
void etiss::instr::Node::compile (const std::map< const OPCode *, Instruction *, etiss::instr::less > & instrmap_, const BitArray & used, bool & ok, std::list< std::string > & warnings, std::list< std::string > & errors) virtual
called by InstructionSet::compile() calls Node::compile() of sub nodes
Parameters
instrmap_ a subset of instructions that will be put into/linked as sub nodes.
used bits that have already been used in previous nodes and cannot be used by this node to distinguish instruction opcodes
Reimplemented in etiss::instr::Instruction, and etiss::instr::Instruction.
Definition at line 615 of file Instruction.cpp.
References etiss::ERROR, etiss_log, etiss::FATALERROR, etiss::instr::BitArray::getBitSetCount(), etiss::instr::HandleCollision(), etiss::log(), min(), Node(), etiss::instr::BitArrayRange::read(), reader_, etiss::instr::BitArray::setAll(), etiss::instr::BitArrayRange::setAll(), and etiss::instr::BitArray::width().
Referenced by etiss::instr::InstructionSet::compile().
compile() [2/2]
virtual void etiss::instr::Node::compile (const std::map< const OPCode *, Instruction *, etiss::instr::less > & instrmap_, const BitArray & used, bool & ok, std::list< std::string > & warnings, std::list< std::string > & errors) virtual
called by InstructionSet::compile() calls Node::compile() of sub nodes
Parameters
instrmap_ a subset of instructions that will be put into/linked as sub nodes.
used bits that have already been used in previous nodes and cannot be used by this node to distinguish instruction opcodes
Reimplemented in etiss::instr::Instruction, and etiss::instr::Instruction.
etiss_del_como() [1/2]
etiss::instr::Node::etiss_del_como (Node) private
no copy/moce operations
array of sub nodes
etiss_del_como() [2/2]
etiss::instr::Node::etiss_del_como (Node) private
no copy/moce operations
array of sub nodes
isInstruction() [1/2]
virtual bool etiss::instr::Node::isInstruction () virtual
returns true if this object is an instance of etiss::instr::Instruction
Reimplemented in etiss::instr::Instruction, and etiss::instr::Instruction.
isInstruction() [2/2]
bool etiss::instr::Node::isInstruction () virtual
returns true if this object is an instance of etiss::instr::Instruction
Reimplemented in etiss::instr::Instruction, and etiss::instr::Instruction.
Definition at line 732 of file Instruction.cpp.
Referenced by ~Node().
print() [1/2]
std::string etiss::instr::Node::print (std::string indent, I pos, unsigned pfillwidth, bool printunused = false) virtual
recursive print function to produce a human readable text that represents the structure of this node and sub nodes
See also
InstructionSet::print()
Reimplemented in etiss::instr::Instruction, and etiss::instr::Instruction.
Definition at line 736 of file Instruction.cpp.
References etiss::instr::BitArrayRange::end(), print(), reader_, and etiss::instr::BitArrayRange::start().
Referenced by print(), and etiss::instr::InstructionSet::print().
print() [2/2]
virtual std::string etiss::instr::Node::print (std::string indent, I pos, unsigned pfillwidth, bool printunused = false) virtual
recursive print function to produce a human readable text that represents the structure of this node and sub nodes
See also
InstructionSet::print()
Reimplemented in etiss::instr::Instruction, and etiss::instr::Instruction.
resolve() [1/2]
virtual Instruction* etiss::instr::Node::resolve (BitArray & instr) virtual
performs a lookup for the matching Instruction for the passed instruction in the bit array.
Reimplemented in etiss::instr::OverlappedNode, etiss::instr::Instruction, and etiss::instr::Instruction.
resolve() [2/2]
Instruction * etiss::instr::Node::resolve (BitArray & instr) virtual
performs a lookup for the matching Instruction for the passed instruction in the bit array.
Reimplemented in etiss::instr::OverlappedNode, etiss::instr::Instruction, and etiss::instr::Instruction.
Definition at line 719 of file Instruction.cpp.
References etiss::FATALERROR, etiss::log(), etiss::instr::BitArrayRange::read(), reader_, resolve(), and unlikely.
Referenced by resolve(), etiss::instr::OverlappedNode::resolve(), and etiss::instr::InstructionSet::resolve().
Member Data Documentation
reader_
BitArrayRange * etiss::instr::Node::reader_ private
reader to extract the bits to identify a sub node
Definition at line 489 of file Instruction.h.
Referenced by compile(), print(), resolve(), and ~Node().
The documentation for this class was generated from the following files:
include/etiss/Instruction.h
/home/runner/work/etiss/etiss/src/Instruction.cpp