ETISS 0.8.0: etiss::plugin::gdb::Connection Class Reference
etiss::plugin::gdb::Connection Class Reference abstract
interface for gdb connections.
#include <GDBConnection.h>
Public Member Functions
Connection ()
virtual ~Connection ()
virtual bool available ()=0
virtual std::string rcv ()=0
virtual bool snd (std::string answer)=0
virtual PacketProtocol & getPacketProtocol ()
virtual bool isRelyable ()
virtual bool pendingBREAK ()
virtual void clearBREAK ()
Connection ()
virtual ~Connection ()
virtual bool available ()=0
virtual std::string rcv ()=0
virtual bool snd (std::string answer)=0
virtual PacketProtocol & getPacketProtocol ()
virtual bool isRelyable ()
virtual bool pendingBREAK ()
virtual void clearBREAK ()
Protected Attributes
bool pending_break_
Private Attributes
PacketProtocol packproc_
Friends
class PacketProtocol
Detailed Description
interface for gdb connections.
implemented by UnixTCPGDBConnection.h . use PacketProtocol (Connection::getPacketProtocol) for communication with gdb
Definition at line 101 of file GDBConnection.h.
Constructor & Destructor Documentation
Connection() [1/2]
Connection::Connection ()
Definition at line 64 of file GDBConnection.cpp.
~Connection() [1/2]
Connection::~Connection () virtual
Definition at line 65 of file GDBConnection.cpp.
Connection() [2/2]
etiss::plugin::gdb::Connection::Connection ()
~Connection() [2/2]
virtual etiss::plugin::gdb::Connection::~Connection () virtual
Member Function Documentation
available() [1/2]
virtual bool etiss::plugin::gdb::Connection::available () pure virtual
Referenced by etiss::plugin::gdb::PacketProtocol::_available(), and etiss::plugin::gdb::PacketProtocol::snd().
available() [2/2]
virtual bool etiss::plugin::gdb::Connection::available () pure virtual
clearBREAK() [1/2]
void Connection::clearBREAK () virtual
Definition at line 365 of file GDBConnection.cpp.
References pending_break_.
Referenced by etiss::plugin::gdb::PacketProtocol::tryReadPacket().
clearBREAK() [2/2]
virtual void etiss::plugin::gdb::Connection::clearBREAK () virtual
getPacketProtocol() [1/2]
PacketProtocol & Connection::getPacketProtocol () virtual
Definition at line 67 of file GDBConnection.cpp.
References packproc_.
Referenced by etiss::plugin::gdb::Server::createTCPServer().
getPacketProtocol() [2/2]
virtual PacketProtocol& etiss::plugin::gdb::Connection::getPacketProtocol () virtual
isRelyable() [1/2]
bool Connection::isRelyable () virtual
Definition at line 357 of file GDBConnection.cpp.
isRelyable() [2/2]
virtual bool etiss::plugin::gdb::Connection::isRelyable () virtual
pendingBREAK() [1/2]
bool Connection::pendingBREAK () virtual
Definition at line 361 of file GDBConnection.cpp.
References pending_break_.
Referenced by etiss::plugin::gdb::PacketProtocol::tryReadPacket().
pendingBREAK() [2/2]
virtual bool etiss::plugin::gdb::Connection::pendingBREAK () virtual
rcv() [1/2]
virtual std::string etiss::plugin::gdb::Connection::rcv () pure virtual
Referenced by etiss::plugin::gdb::PacketProtocol::_available(), and etiss::plugin::gdb::PacketProtocol::snd().
rcv() [2/2]
virtual std::string etiss::plugin::gdb::Connection::rcv () pure virtual
snd() [1/2]
virtual bool etiss::plugin::gdb::Connection::snd (std::string answer) pure virtual
Referenced by etiss::plugin::gdb::PacketProtocol::snd(), and etiss::plugin::gdb::PacketProtocol::tryReadPacket().
snd() [2/2]
virtual bool etiss::plugin::gdb::Connection::snd (std::string answer) pure virtual
Friends And Related Function Documentation
PacketProtocol
PacketProtocol friend
Definition at line 103 of file GDBConnection.h.
Member Data Documentation
packproc_
PacketProtocol etiss::plugin::gdb::Connection::packproc_ private
Definition at line 120 of file GDBConnection.h.
Referenced by getPacketProtocol().
pending_break_
bool etiss::plugin::gdb::Connection::pending_break_ protected
Definition at line 117 of file GDBConnection.h.
Referenced by clearBREAK(), and pendingBREAK().
The documentation for this class was generated from the following files:
include/etiss/IntegratedLibrary/gdb/GDBConnection.h
/home/runner/work/etiss/etiss/src/IntegratedLibrary/gdb/GDBConnection.cpp