ETISS 0.8.0: xpath_string Class Reference
xpath_string Class Reference
Public Member Functions
xpath_string ()
xpath_string (const char_t *str, xpath_allocator *alloc)
xpath_string (const char_t *str, bool use_heap)
xpath_string (const char_t *begin, const char_t *end, xpath_allocator *alloc)
void append (const xpath_string &o, xpath_allocator *alloc)
const char_t * c_str () const
size_t length () const
char_t * data (xpath_allocator *alloc)
bool empty () const
bool operator== (const xpath_string &o) const
bool operator!= (const xpath_string &o) const
bool uses_heap () const
Static Private Member Functions
static char_t * duplicate_string (const char_t *string, size_t length, xpath_allocator *alloc)
static char_t * duplicate_string (const char_t *string, xpath_allocator *alloc)
Private Attributes
const char_t * _buffer
bool _uses_heap
Detailed Description
Definition at line 6753 of file pugixml.cpp.
Constructor & Destructor Documentation
xpath_string() [1/4]
xpath_string::xpath_string () inline
Definition at line 6775 of file pugixml.cpp.
xpath_string() [2/4]
xpath_string::xpath_string (const char_t * str, xpath_allocator * alloc) inline explicit
Definition at line 6777 of file pugixml.cpp.
References _buffer, _uses_heap, duplicate_string(), and PUGIXML_TEXT.
xpath_string() [3/4]
xpath_string::xpath_string (const char_t * str, bool use_heap) inline explicit
Definition at line 6785 of file pugixml.cpp.
xpath_string() [4/4]
xpath_string::xpath_string (const char_t * begin, const char_t * end, xpath_allocator * alloc) inline
Definition at line 6787 of file pugixml.cpp.
References _buffer, _uses_heap, duplicate_string(), and PUGIXML_TEXT.
Member Function Documentation
append()
void xpath_string::append (const xpath_string & o, xpath_allocator * alloc) inline
Definition at line 6797 of file pugixml.cpp.
References _buffer, _uses_heap, memcpy(), xpath_allocator::reallocate(), and strlength().
Referenced by string_value().
c_str()
const char_t* xpath_string::c_str () const inline
Definition at line 6835 of file pugixml.cpp.
References _buffer.
Referenced by xpath_ast_node::compare_eq(), xpath_ast_node::compare_rel(), xpath_ast_node::eval_boolean(), xpath_ast_node::eval_number(), xpath_ast_node::eval_string(), and pugi::xpath_query::evaluate_string().
data()
char_t* xpath_string::data (xpath_allocator * alloc) inline
Definition at line 6839 of file pugixml.cpp.
References _buffer, _uses_heap, and duplicate_string().
duplicate_string() [1/2]
static char_t* xpath_string::duplicate_string (const char_t * string, size_t length, xpath_allocator * alloc) inline static private
Definition at line 6758 of file pugixml.cpp.
References xpath_allocator::allocate(), length(), and memcpy().
Referenced by data(), duplicate_string(), and xpath_string().
duplicate_string() [2/2]
static char_t* xpath_string::duplicate_string (const char_t * string, xpath_allocator * alloc) inline static private
Definition at line 6769 of file pugixml.cpp.
References duplicate_string(), and strlength().
empty()
bool xpath_string::empty () const inline
Definition at line 6851 of file pugixml.cpp.
References _buffer.
Referenced by xpath_ast_node::eval_boolean().
length()
size_t xpath_string::length () const inline
Definition at line 6837 of file pugixml.cpp.
References _buffer, and strlength().
Referenced by duplicate_string(), xpath_ast_node::eval_number(), and xpath_ast_node::eval_string().
operator!=()
bool xpath_string::operator!= (const xpath_string & o) const inline
Definition at line 6855 of file pugixml.cpp.
References _buffer, and strequal().
operator==()
bool xpath_string::operator== (const xpath_string & o) const inline
Definition at line 6853 of file pugixml.cpp.
References _buffer, and strequal().
uses_heap()
bool xpath_string::uses_heap () const inline
Definition at line 6857 of file pugixml.cpp.
References _uses_heap.
Member Data Documentation
_buffer
const char_t* xpath_string::_buffer private
Definition at line 6755 of file pugixml.cpp.
Referenced by append(), c_str(), data(), empty(), length(), operator!=(), operator==(), and xpath_string().
_uses_heap
bool xpath_string::_uses_heap private
Definition at line 6756 of file pugixml.cpp.
Referenced by append(), data(), uses_heap(), and xpath_string().
The documentation for this class was generated from the following file:
/home/runner/work/etiss/etiss/src/fault/xml/pugixml.cpp