ETISS 0.8.0: etiss::instr::InstructionDefinition Class Reference
etiss::instr::InstructionDefinition Class Reference
maps to Instruction
#include <Instruction.h>
Public Member Functions
etiss_del_como (InstructionDefinition) template< typename T > InstructionDefinition(InstructionGroup &ig
const std::string T T std::function< bool(BitArray &, etiss::CodeSet &, InstructionContext &)> uint32_t std::function< std::string(BitArray &, Instruction &)> name_ (name)
const std::string T T std::function< bool(BitArray &, etiss::CodeSet &, InstructionContext &)> uint32_t std::function< std::string(BitArray &, Instruction &)> opc_ (ig.width_, code, mask)
const std::string T T std::function< bool(BitArray &, etiss::CodeSet &, InstructionContext &)> uint32_t std::function< std::string(BitArray &, Instruction &)> callback_ (callback)
const std::string T T std::function< bool(BitArray &, etiss::CodeSet &, InstructionContext &)> uint32_t std::function< std::string(BitArray &, Instruction &)> ASMprinter_ (ASMprinter)
const std::string T T std::function< bool(BitArray &, etiss::CodeSet &, InstructionContext &)> uint32_t std::function< std::string(BitArray &, Instruction &)> builtinGroups_ (builtinGroups)
~InstructionDefinition ()
void addTo (Instruction &set, bool &ok)
std::string toString () const
etiss_del_como (InstructionDefinition) template< typename T > InstructionDefinition(InstructionGroup &ig
const std::string T T std::function< bool(BitArray &, etiss::CodeSet &, InstructionContext &)> uint32_t std::function< std::string(BitArray &, Instruction &)> name_ (name)
const std::string T T std::function< bool(BitArray &, etiss::CodeSet &, InstructionContext &)> uint32_t std::function< std::string(BitArray &, Instruction &)> opc_ (ig.width_, code, mask)
const std::string T T std::function< bool(BitArray &, etiss::CodeSet &, InstructionContext &)> uint32_t std::function< std::string(BitArray &, Instruction &)> callback_ (callback)
const std::string T T std::function< bool(BitArray &, etiss::CodeSet &, InstructionContext &)> uint32_t std::function< std::string(BitArray &, Instruction &)> ASMprinter_ (ASMprinter)
const std::string T T std::function< bool(BitArray &, etiss::CodeSet &, InstructionContext &)> uint32_t std::function< std::string(BitArray &, Instruction &)> builtinGroups_ (builtinGroups)
~InstructionDefinition ()
void addTo (Instruction &set, bool &ok)
std::string toString () const
Public Member Functions inherited from etiss::ToString
ToString ()
virtual ~ToString ()
ToString ()
virtual ~ToString ()
Public Attributes
InstructionGroup & group_
const std::string name_
const OPCode opc_
const std::function< bool(BitArray &, etiss::CodeSet &, InstructionContext &)> callback_
const std::function< std::string(BitArray &, Instruction &)> ASMprinter_
const uint32_t builtinGroups_
const std::string & name
const std::string T code
const std::string T T mask
const std::string T T std::function< bool(BitArray &, etiss::CodeSet &, InstructionContext &)> callback
const std::string T T std::function< bool(BitArray &, etiss::CodeSet &, InstructionContext &)> uint32_t builtinGroups
const std::string T T std::function< bool(BitArray &, etiss::CodeSet &, InstructionContext &)> uint32_t std::function< std::string(BitArray &, Instruction &)> ASMprinter: group_(ig)
Detailed Description
maps to Instruction
Definition at line 961 of file Instruction.h.
Constructor & Destructor Documentation
~InstructionDefinition() [1/2]
etiss::instr::InstructionDefinition::~InstructionDefinition () inline
Definition at line 996 of file Instruction.h.
~InstructionDefinition() [2/2]
etiss::instr::InstructionDefinition::~InstructionDefinition () inline
Definition at line 996 of file Instruction.h.
Member Function Documentation
addTo() [1/2]
void etiss::instr::InstructionDefinition::addTo (Instruction & set, bool & ok)
Definition at line 1240 of file Instruction.cpp.
References etiss::instr::Instruction::addCallback(), ASMprinter_, builtinGroups_, callback_, etiss::ERROR, etiss::log(), etiss::instr::Instruction::opc_, opc_, etiss::instr::Instruction::setASMPrinter(), and etiss::VERBOSE.
addTo() [2/2]
void etiss::instr::InstructionDefinition::addTo (Instruction & set, bool & ok)
ASMprinter_() [1/2]
const std::string T T std::function<bool(BitArray &, etiss::CodeSet &, InstructionContext &)> uint32_t std::function<std::string(BitArray &, Instruction &)> etiss::instr::InstructionDefinition::ASMprinter_ (ASMprinter)
ASMprinter_() [2/2]
const std::string T T std::function<bool(BitArray &, etiss::CodeSet &, InstructionContext &)> uint32_t std::function<std::string(BitArray &, Instruction &)> etiss::instr::InstructionDefinition::ASMprinter_ (ASMprinter)
builtinGroups_() [1/2]
const std::string T T std::function<bool(BitArray &, etiss::CodeSet &, InstructionContext &)> uint32_t std::function<std::string(BitArray &, Instruction &)> etiss::instr::InstructionDefinition::builtinGroups_ (builtinGroups) inline
Definition at line 983 of file Instruction.h.
References callback, etiss::instr::InstructionGroup::defs_, etiss_log, etiss::FATALERROR, group_, and name.
builtinGroups_() [2/2]
const std::string T T std::function<bool(BitArray &, etiss::CodeSet &, InstructionContext &)> uint32_t std::function<std::string(BitArray &, Instruction &)> etiss::instr::InstructionDefinition::builtinGroups_ (builtinGroups) inline
Definition at line 983 of file Instruction.h.
References callback, etiss::instr::InstructionGroup::defs_, etiss_log, etiss::FATALERROR, group_, and name.
callback_() [1/2]
const std::string T T std::function<bool(BitArray &, etiss::CodeSet &, InstructionContext &)> uint32_t std::function<std::string(BitArray &, Instruction &)> etiss::instr::InstructionDefinition::callback_ (callback)
callback_() [2/2]
const std::string T T std::function<bool(BitArray &, etiss::CodeSet &, InstructionContext &)> uint32_t std::function<std::string(BitArray &, Instruction &)> etiss::instr::InstructionDefinition::callback_ (callback)
etiss_del_como() [1/2]
etiss::instr::InstructionDefinition::etiss_del_como (InstructionDefinition) &
etiss_del_como() [2/2]
etiss::instr::InstructionDefinition::etiss_del_como (InstructionDefinition) &
name_() [1/2]
const std::string T T std::function<bool(BitArray &, etiss::CodeSet &, InstructionContext &)> uint32_t std::function<std::string(BitArray &, Instruction &)> etiss::instr::InstructionDefinition::name_ (name)
name_() [2/2]
const std::string T T std::function<bool(BitArray &, etiss::CodeSet &, InstructionContext &)> uint32_t std::function<std::string(BitArray &, Instruction &)> etiss::instr::InstructionDefinition::name_ (name)
opc_() [1/2]
const std::string T T std::function<bool(BitArray &, etiss::CodeSet &, InstructionContext &)> uint32_t std::function<std::string(BitArray &, Instruction &)> etiss::instr::InstructionDefinition::opc_ (ig. width_, code , mask)
opc_() [2/2]
const std::string T T std::function<bool(BitArray &, etiss::CodeSet &, InstructionContext &)> uint32_t std::function<std::string(BitArray &, Instruction &)> etiss::instr::InstructionDefinition::opc_ (ig. width_, code , mask)
toString() [1/2]
std::string etiss::instr::InstructionDefinition::toString () const inline
Definition at line 1001 of file Instruction.h.
References group_, etiss::instr::InstructionGroup::name_, and name_.
toString() [2/2]
std::string etiss::instr::InstructionDefinition::toString () const inline
Definition at line 1001 of file Instruction.h.
References group_, etiss::instr::InstructionGroup::name_, and name_.
Member Data Documentation
ASMprinter
const std::string T T std::function< bool(BitArray &, etiss::CodeSet &, InstructionContext &)> uint32_t std::function< std::string(BitArray &, Instruction &)> etiss::instr::InstructionDefinition::ASMprinter
Definition at line 979 of file Instruction.h.
ASMprinter_
const std::function< std::string(BitArray &, Instruction &)> etiss::instr::InstructionDefinition::ASMprinter_
Definition at line 968 of file Instruction.h.
Referenced by addTo().
builtinGroups
const std::string T T std::function< bool(BitArray &, etiss::CodeSet &, InstructionContext &)> uint32_t etiss::instr::InstructionDefinition::builtinGroups
Definition at line 977 of file Instruction.h.
builtinGroups_
const uint32_t etiss::instr::InstructionDefinition::builtinGroups_
Definition at line 969 of file Instruction.h.
Referenced by addTo().
callback
const std::string T T std::function< bool(BitArray &, etiss::CodeSet &, InstructionContext &)> etiss::instr::InstructionDefinition::callback
Definition at line 976 of file Instruction.h.
Referenced by builtinGroups_().
callback_
const std::function< bool(BitArray &, etiss::CodeSet &, InstructionContext &)> etiss::instr::InstructionDefinition::callback_
Definition at line 967 of file Instruction.h.
Referenced by addTo().
code
const std::string T etiss::instr::InstructionDefinition::code
Definition at line 975 of file Instruction.h.
group_
InstructionGroup & etiss::instr::InstructionDefinition::group_
Definition at line 964 of file Instruction.h.
Referenced by builtinGroups_(), and toString().
mask
const std::string T T etiss::instr::InstructionDefinition::mask
Definition at line 975 of file Instruction.h.
name
const std::string & etiss::instr::InstructionDefinition::name
Definition at line 975 of file Instruction.h.
Referenced by builtinGroups_().
name_
const std::string etiss::instr::InstructionDefinition::name_
Definition at line 965 of file Instruction.h.
Referenced by toString().
opc_
const OPCode etiss::instr::InstructionDefinition::opc_
Definition at line 966 of file Instruction.h.
Referenced by addTo().
The documentation for this class was generated from the following files:
include/etiss/Instruction.h
/home/runner/work/etiss/etiss/src/Instruction.cpp