ETISS 0.8.0: xpath_allocator Class Reference
xpath_allocator Class Reference
Public Member Functions
xpath_allocator (xpath_memory_block *root, size_t root_size=0)
void * allocate_nothrow (size_t size)
void * allocate (size_t size)
void * reallocate (void *ptr, size_t old_size, size_t new_size)
void revert (const xpath_allocator &state)
void release ()
Private Attributes
xpath_memory_block * _root
size_t _root_size
Detailed Description
Definition at line 6558 of file pugixml.cpp.
Constructor & Destructor Documentation
xpath_allocator()
xpath_allocator::xpath_allocator (xpath_memory_block * root, size_t root_size = 0) inline
Definition at line 6568 of file pugixml.cpp.
Member Function Documentation
allocate()
void* xpath_allocator::allocate (size_t size) inline
Definition at line 6606 of file pugixml.cpp.
References allocate_nothrow().
Referenced by convert_number_to_string(), xpath_string::duplicate_string(), xpath_ast_node::eval_string_concat(), and reallocate().
allocate_nothrow()
void* xpath_allocator::allocate_nothrow (size_t size) inline
Definition at line 6575 of file pugixml.cpp.
References _root, _root_size, xml_memory_management_function_storage< T >::allocate, xpath_memory_block::data, xpath_memory_block::next, and offsetof.
Referenced by xpath_parser::alloc_node(), xpath_parser::alloc_string(), and allocate().
reallocate()
void* xpath_allocator::reallocate (void * ptr, size_t old_size, size_t new_size) inline
Definition at line 6623 of file pugixml.cpp.
References _root, _root_size, allocate(), xpath_memory_block::data, xml_memory_management_function_storage< T >::deallocate, memcpy(), and xpath_memory_block::next.
Referenced by xpath_string::append(), xpath_node_set_raw::append(), and xpath_node_set_raw::push_back().
release()
void xpath_allocator::release () inline
Definition at line 6688 of file pugixml.cpp.
References _root, xml_memory_management_function_storage< T >::deallocate, and xpath_memory_block::next.
Referenced by xpath_query_impl::destroy(), and xpath_stack_data::~xpath_stack_data().
revert()
void xpath_allocator::revert (const xpath_allocator & state) inline
Definition at line 6669 of file pugixml.cpp.
References _root, _root_size, xml_memory_management_function_storage< T >::deallocate, and xpath_memory_block::next.
Referenced by xpath_allocator_capture::~xpath_allocator_capture().
Member Data Documentation
_root
xpath_memory_block* xpath_allocator::_root private
Definition at line 6560 of file pugixml.cpp.
Referenced by allocate_nothrow(), reallocate(), release(), and revert().
_root_size
size_t xpath_allocator::_root_size private
Definition at line 6561 of file pugixml.cpp.
Referenced by allocate_nothrow(), reallocate(), and revert().
The documentation for this class was generated from the following file:
/home/runner/work/etiss/etiss/src/fault/xml/pugixml.cpp