ETISS 0.8.0: pugi::xpath_variable_set Class Reference
pugi::xpath_variable_set Class Reference
#include <pugixml.hpp>
Public Member Functions
xpath_variable_set ()
~xpath_variable_set ()
xpath_variable * add (const char_t *name, xpath_value_type type)
bool set (const char_t *name, bool value)
bool set (const char_t *name, double value)
bool set (const char_t *name, const char_t *value)
bool set (const char_t *name, const xpath_node_set &value)
xpath_variable * get (const char_t *name)
const xpath_variable * get (const char_t *name) const
xpath_variable_set ()
~xpath_variable_set ()
xpath_variable * add (const char_t *name, xpath_value_type type)
bool set (const char_t *name, bool value)
bool set (const char_t *name, double value)
bool set (const char_t *name, const char_t *value)
bool set (const char_t *name, const xpath_node_set &value)
xpath_variable * get (const char_t *name)
const xpath_variable * get (const char_t *name) const
Private Member Functions
xpath_variable_set (const xpath_variable_set &)
xpath_variable_set & operator= (const xpath_variable_set &)
xpath_variable * find (const char_t *name) const
xpath_variable_set (const xpath_variable_set &)
xpath_variable_set & operator= (const xpath_variable_set &)
xpath_variable * find (const char_t *name) const
Private Attributes
xpath_variable * _data [64]
Detailed Description
Definition at line 1056 of file pugixml.hpp.
Constructor & Destructor Documentation
xpath_variable_set() [1/4]
pugi::xpath_variable_set::xpath_variable_set (const xpath_variable_set &) private
xpath_variable_set() [2/4]
PUGI__FN pugi::xpath_variable_set::xpath_variable_set ()
Definition at line 10901 of file pugixml.cpp.
References _data.
~xpath_variable_set() [1/2]
PUGI__FN pugi::xpath_variable_set::~xpath_variable_set ()
Definition at line 10907 of file pugixml.cpp.
References _data, pugi::xpath_variable::_next, pugi::xpath_variable::_type, and delete_xpath_variable().
xpath_variable_set() [3/4]
pugi::xpath_variable_set::xpath_variable_set (const xpath_variable_set &) private
xpath_variable_set() [4/4]
pugi::xpath_variable_set::xpath_variable_set ()
~xpath_variable_set() [2/2]
pugi::xpath_variable_set::~xpath_variable_set ()
Member Function Documentation
add() [1/2]
PUGI__FN xpath_variable * pugi::xpath_variable_set::add (const char_t * name, xpath_value_type type)
Definition at line 10937 of file pugixml.cpp.
References _data, pugi::xpath_variable::_next, pugi::xpath_variable::_type, hash_string(), name, new_xpath_variable(), and strequal().
Referenced by set().
add() [2/2]
xpath_variable* pugi::xpath_variable_set::add (const char_t * name, xpath_value_type type)
find() [1/2]
xpath_variable* pugi::xpath_variable_set::find (const char_t * name) const private
find() [2/2]
PUGI__FN xpath_variable * pugi::xpath_variable_set::find (const char_t * name) const private
Definition at line 10924 of file pugixml.cpp.
References _data, pugi::xpath_variable::_next, hash_string(), name, and strequal().
Referenced by get().
get() [1/4]
xpath_variable* pugi::xpath_variable_set::get (const char_t * name)
get() [2/4]
PUGI__FN xpath_variable * pugi::xpath_variable_set::get (const char_t * name)
Definition at line 10985 of file pugixml.cpp.
References find(), and name.
get() [3/4]
const PUGI__FN xpath_variable * pugi::xpath_variable_set::get (const char_t * name) const
Definition at line 10990 of file pugixml.cpp.
References find(), and name.
get() [4/4]
const xpath_variable* pugi::xpath_variable_set::get (const char_t * name) const
operator=() [1/2]
xpath_variable_set& pugi::xpath_variable_set::operator= (const xpath_variable_set &) private
operator=() [2/2]
xpath_variable_set& pugi::xpath_variable_set::operator= (const xpath_variable_set &) private
set() [1/8]
PUGI__FN bool pugi::xpath_variable_set::set (const char_t * name, bool value)
Definition at line 10961 of file pugixml.cpp.
References add(), name, pugi::xpath_variable::set(), and pugi::xpath_type_boolean.
set() [2/8]
bool pugi::xpath_variable_set::set (const char_t * name, bool value)
set() [3/8]
PUGI__FN bool pugi::xpath_variable_set::set (const char_t * name, const char_t * value)
Definition at line 10973 of file pugixml.cpp.
References add(), name, pugi::xpath_variable::set(), and pugi::xpath_type_string.
set() [4/8]
bool pugi::xpath_variable_set::set (const char_t * name, const char_t * value)
set() [5/8]
bool pugi::xpath_variable_set::set (const char_t * name, const xpath_node_set & value)
set() [6/8]
PUGI__FN bool pugi::xpath_variable_set::set (const char_t * name, const xpath_node_set & value)
Definition at line 10979 of file pugixml.cpp.
References add(), name, pugi::xpath_variable::set(), and pugi::xpath_type_node_set.
set() [7/8]
PUGI__FN bool pugi::xpath_variable_set::set (const char_t * name, double value)
Definition at line 10967 of file pugixml.cpp.
References add(), name, pugi::xpath_variable::set(), and pugi::xpath_type_number.
set() [8/8]
bool pugi::xpath_variable_set::set (const char_t * name, double value)
Member Data Documentation
_data
xpath_variable * pugi::xpath_variable_set::_data private
Definition at line 1059 of file pugixml.hpp.
Referenced by add(), find(), xpath_variable_set(), and ~xpath_variable_set().
The documentation for this class was generated from the following files:
include/etiss/fault/xml/pugixml.hpp
/home/runner/work/etiss/etiss/src/fault/xml/pugixml.cpp