ETISS 0.8.0: etiss::JIT Class Reference
etiss::JIT Class Reference abstract
compiler interface for just in time compilation of generated C code
#include <JIT.h>
Public Member Functions
JIT (std::string name)
virtual ~JIT ()
virtual void * translate (std::string code, std::set< std::string > headerpaths, std::set< std::string > librarypaths, std::set< std::string > libraries, std::string &error, bool debug=true)=0
translate C code to executable code and return a handle/pointer that identifies the compilation result
virtual void * getFunction (void *handle, std::string name, std::string &error)=0
returns a function pointer to a compiled function from the handle returned by etiss::JIT::translate
virtual void free (void *handle)=0
clean up handled returned by etiss::JIT::translate
std::string getName ()
returns the JIT instance name previously passed to the constructor
JIT (std::string name)
virtual ~JIT ()
virtual void * translate (std::string code, std::set< std::string > headerpaths, std::set< std::string > librarypaths, std::set< std::string > libraries, std::string &error, bool debug=true)=0
translate C code to executable code and return a handle/pointer that identifies the compilation result
virtual void * getFunction (void *handle, std::string name, std::string &error)=0
returns a function pointer to a compiled function from the handle returned by etiss::JIT::translate
virtual void free (void *handle)=0
clean up handled returned by etiss::JIT::translate
std::string getName ()
returns the JIT instance name previously passed to the constructor
Private Attributes
std::string name_
Detailed Description
compiler interface for just in time compilation of generated C code
Definition at line 66 of file JIT.h.
Constructor & Destructor Documentation
JIT() [1/2]
JIT::JIT (std::string name)
Definition at line 56 of file JIT.cpp.
~JIT() [1/2]
JIT::~JIT () virtual
Definition at line 58 of file JIT.cpp.
JIT() [2/2]
etiss::JIT::JIT (std::string name)
~JIT() [2/2]
virtual etiss::JIT::~JIT () virtual
Member Function Documentation
free() [1/2]
virtual void etiss::JIT::free (void * handle) pure virtual
clean up handled returned by etiss::JIT::translate
Implemented in etiss::LLVMJIT, GCCJIT, and TCCJIT.
Referenced by verifyJITPragmaPack(), and verifyJITSizeOf().
free() [2/2]
virtual void etiss::JIT::free (void * handle) pure virtual
clean up handled returned by etiss::JIT::translate
Implemented in etiss::LLVMJIT, GCCJIT, and TCCJIT.
getFunction() [1/2]
virtual void* etiss::JIT::getFunction (void * handle, std::string name, std::string & error) pure virtual
returns a function pointer to a compiled function from the handle returned by etiss::JIT::translate
Implemented in etiss::LLVMJIT, GCCJIT, and TCCJIT.
Referenced by etiss::Translation::getBlock(), verifyJITPragmaPack(), and verifyJITSizeOf().
getFunction() [2/2]
virtual void* etiss::JIT::getFunction (void * handle, std::string name, std::string & error) pure virtual
returns a function pointer to a compiled function from the handle returned by etiss::JIT::translate
Implemented in etiss::LLVMJIT, GCCJIT, and TCCJIT.
getName() [1/2]
std::string JIT::getName ()
returns the JIT instance name previously passed to the constructor
Definition at line 60 of file JIT.cpp.
References name_.
Referenced by etiss::CPUCore::execute(), and etiss::CPUCore::getJITName().
getName() [2/2]
std::string etiss::JIT::getName ()
returns the JIT instance name previously passed to the constructor
translate() [1/2]
virtual void* etiss::JIT::translate (std::string code, std::set< std::string > headerpaths, std::set< std::string > librarypaths, std::set< std::string > libraries, std::string & error, bool debug = true) pure virtual
translate C code to executable code and return a handle/pointer that identifies the compilation result
Parameters
code generated code
headerpaths paths where required header files are located
librarypaths paths where required libraries are located (usually not needed since libraries don't require full linking)
libraries file names of required libraries (usually not needed since libraries don't require full linking)
error string to return additional error information
debug if true then compilation should try to enable gdb to jump into compiled functions
Implemented in etiss::LLVMJIT, GCCJIT, and TCCJIT.
Referenced by etiss::Translation::getBlock(), verifyJITPragmaPack(), and verifyJITSizeOf().
translate() [2/2]
virtual void* etiss::JIT::translate (std::string code, std::set< std::string > headerpaths, std::set< std::string > librarypaths, std::set< std::string > libraries, std::string & error, bool debug = true) pure virtual
translate C code to executable code and return a handle/pointer that identifies the compilation result
Parameters
code generated code
headerpaths paths where required header files are located
librarypaths paths where required libraries are located (usually not needed since libraries don't require full linking)
libraries file names of required libraries (usually not needed since libraries don't require full linking)
error string to return additional error information
debug if true then compilation should try to enable gdb to jump into compiled functions
Implemented in etiss::LLVMJIT, GCCJIT, and TCCJIT.
Member Data Documentation
name_
std::string etiss::JIT::name_ private
Definition at line 100 of file JIT.h.
Referenced by getName().
The documentation for this class was generated from the following files:
include/etiss/JIT.h
/home/runner/work/etiss/etiss/src/JIT.cpp