ETISS 0.8.0: RISCV64Timer Class Reference
RISCV64Timer Class Reference
#include <RISCV64Timer.h>
Public Member Functions
RISCV64Timer ()
virtual ~RISCV64Timer ()
void init (ETISS_CPU *cpu, ETISS_System *system, etiss::CPUArch *arch)
this function is called before the plugin is used in the cpu execution loop (etiss::CPUCore::execute).
etiss::int32 execute ()
called before a block and may act in the same way as a block
ETISS_System * wrap (ETISS_CPU *cpu, ETISS_System *system)
change/wrap the passed system structure.
ETISS_System * unwrap (ETISS_CPU *cpu, ETISS_System *system)
undo wrap function call this function will be called AFTER etiss::Plugin::cleanup
Public Member Functions inherited from etiss::CoroutinePlugin
CoroutinePlugin ()
virtual ~CoroutinePlugin ()
virtual void executionEnd (int32_t code)
called when the simulation ends but before any deinitialization is done
virtual bool isActive ()
indicates if the plugin will do something in execution loop.
CoroutinePlugin ()
virtual ~CoroutinePlugin ()
virtual void executionEnd (int32_t code)
called when the simulation ends but before any deinitialization is done
virtual bool isActive ()
indicates if the plugin will do something in execution loop.
Public Member Functions inherited from etiss::Plugin
virtual ~Plugin ()
unsigned getType ()
InterruptListenerPlugin * getInterruptListenerPlugin ()
CoroutinePlugin * getCoroutinePlugin ()
SystemWrapperPlugin * getSystemWrapperPlugin ()
RegisterDevicePlugin * getRegisterDevicePlugin ()
TranslationPlugin * getTranslationPlugin ()
std::string getPluginName () const
const std::string & getLastAssignedCoreName ()
std::string toString () const
virtual ~Plugin ()
unsigned getType ()
InterruptListenerPlugin * getInterruptListenerPlugin ()
CoroutinePlugin * getCoroutinePlugin ()
SystemWrapperPlugin * getSystemWrapperPlugin ()
RegisterDevicePlugin * getRegisterDevicePlugin ()
TranslationPlugin * getTranslationPlugin ()
std::string getPluginName () const
const std::string & getLastAssignedCoreName ()
std::string toString () const
Public Member Functions inherited from etiss::ToString
ToString ()
virtual ~ToString ()
ToString ()
virtual ~ToString ()
Public Member Functions inherited from etiss::SystemWrapperPlugin
SystemWrapperPlugin ()
virtual ~SystemWrapperPlugin ()
SystemWrapperPlugin ()
virtual ~SystemWrapperPlugin ()
Public Attributes
etiss::uint64 mtime_
etiss::uint64 mtimecmp_
char mtimecmp_buf_ [8]
Protected Member Functions
virtual std::string _getPluginName () const
Protected Member Functions inherited from etiss::Plugin
Plugin (unsigned type=0)
virtual void cleanup ()
this function is called after cpu execution loop (etiss::CPUCore::execute) finished.
void setCorrespondingCPUCoreName (std::string name)
virtual void addedToCPUCore (etiss::CPUCore *core)
called as soon a plugin has been added to its CPUCore.
virtual void removedFromCPUCore (etiss::CPUCore *core)
called as soon a plugin has been removed from its CPUCore.
Plugin (unsigned type=0)
virtual void cleanup ()
this function is called after cpu execution loop (etiss::CPUCore::execute) finished.
void setCorrespondingCPUCoreName (std::string name)
virtual void addedToCPUCore (etiss::CPUCore *core)
called as soon a plugin has been added to its CPUCore.
virtual void removedFromCPUCore (etiss::CPUCore *core)
called as soon a plugin has been removed from its CPUCore.
Private Attributes
RISCV64 * riscv64cpu
bool timer_enabled_
bool mtimecmp_overflow_clear_
bool mtimecmp_overflow_
bool mtime_overflow_
Additional Inherited Members
Static Public Attributes inherited from etiss::Plugin
static const unsigned INTERRUPTLISTENER = 1 << 0
access to translated code
static const unsigned COROUTINE = 1 << 1
callback after execution of each translated block
static const unsigned SYSTEMWRAPPER = 1 << 2
can wrap/change ETISS_System structure at execution start
static const unsigned REGISTERDEVICE
gets noticed of changes to special registers (e.g. mmu register etc. [depends on architecture])
static const unsigned TRANSLATION
access to translated code during translation phase or when instruction tree is built
Protected Attributes inherited from etiss::Plugin
ETISS_CPU * plugin_cpu_
holds a pointer to the cpu structure. will be set before init call and after cleanup call
ETISS_System * plugin_system_
holds a pointer to the system structure.
CPUArch * plugin_arch_
holds a pointer to the CPUArch instance. will be set before init call and after cleanup call
CPUCore * plugin_core_
holds a pointer to the associated CPUCore instance.
Detailed Description
Definition at line 66 of file RISCV64Timer.h.
Constructor & Destructor Documentation
RISCV64Timer()
RISCV64Timer::RISCV64Timer ()
Definition at line 148 of file RISCV64Timer.cpp.
References memset(), and mtimecmp_buf_.
~RISCV64Timer()
virtual RISCV64Timer::~RISCV64Timer () inline virtual
Definition at line 71 of file RISCV64Timer.h.
Member Function Documentation
_getPluginName()
virtual std::string RISCV64Timer::_getPluginName () const inline protected virtual
Implements etiss::Plugin.
Definition at line 86 of file RISCV64Timer.h.
execute()
etiss::int32 RISCV64Timer::execute () virtual
called before a block and may act in the same way as a block
Implements etiss::CoroutinePlugin.
Definition at line 160 of file RISCV64Timer.cpp.
References RISCV64::CSR, CSR_MIP, etiss::log(), memset(), MIP_MTIP, mtime_, mtime_overflow_, mtimecmp_, mtimecmp_buf_, mtimecmp_overflow_, mtimecmp_overflow_clear_, etiss::mm::NOERROR, riscv64cpu, timer_enabled_, and etiss::VERBOSE.
init()
void RISCV64Timer::init (ETISS_CPU * cpu, ETISS_System * system, etiss::CPUArch * arch) inline virtual
this function is called before the plugin is used in the cpu execution loop (etiss::CPUCore::execute).
Only exception is the SystemWrapperPlugin whose SystemWrapperPlugin::wrap function is called BEFORE Plugin::init
Reimplemented from etiss::Plugin.
Definition at line 73 of file RISCV64Timer.h.
References riscv64cpu.
unwrap()
ETISS_System * RISCV64Timer::unwrap (ETISS_CPU * cpu, ETISS_System * system) virtual
undo wrap function call this function will be called AFTER etiss::Plugin::cleanup
Implements etiss::SystemWrapperPlugin.
Definition at line 237 of file RISCV64Timer.cpp.
wrap()
ETISS_System * RISCV64Timer::wrap (ETISS_CPU * cpu, ETISS_System * system) virtual
change/wrap the passed system structure.
the returned value will be used as the current system this function will be called BEFORE etiss::Plugin::init
Implements etiss::SystemWrapperPlugin.
Definition at line 215 of file RISCV64Timer.cpp.
References dbg_read(), ETISS_System::dbg_read, ETISS_System::dbg_write, dbg_write(), dread(), ETISS_System::dread, dwrite(), ETISS_System::dwrite, ETISS_System::handle, iread(), ETISS_System::iread, iwrite(), ETISS_System::iwrite, RISCV64TimerSystem::orig, ETISS_System::syncTime, syncTime(), RISCV64TimerSystem::sys, and RISCV64TimerSystem::this_.
Member Data Documentation
mtime_
etiss::uint64 RISCV64Timer::mtime_
Definition at line 81 of file RISCV64Timer.h.
Referenced by dbg_read(), dread(), and execute().
mtime_overflow_
bool RISCV64Timer::mtime_overflow_ private
Definition at line 94 of file RISCV64Timer.h.
Referenced by execute().
mtimecmp_
etiss::uint64 RISCV64Timer::mtimecmp_
Definition at line 82 of file RISCV64Timer.h.
Referenced by execute().
mtimecmp_buf_
char RISCV64Timer::mtimecmp_buf_[8]
Definition at line 83 of file RISCV64Timer.h.
Referenced by dbg_write(), dwrite(), execute(), and RISCV64Timer().
mtimecmp_overflow_
bool RISCV64Timer::mtimecmp_overflow_ private
Definition at line 93 of file RISCV64Timer.h.
Referenced by execute().
mtimecmp_overflow_clear_
bool RISCV64Timer::mtimecmp_overflow_clear_ private
Definition at line 92 of file RISCV64Timer.h.
Referenced by execute().
riscv64cpu
RISCV64* RISCV64Timer::riscv64cpu private
Definition at line 89 of file RISCV64Timer.h.
Referenced by execute(), and init().
timer_enabled_
bool RISCV64Timer::timer_enabled_ private
Definition at line 91 of file RISCV64Timer.h.
Referenced by execute().
The documentation for this class was generated from the following files:
/home/runner/work/etiss/etiss/ArchImpl/RISCV64/RISCV64Timer.h
/home/runner/work/etiss/etiss/ArchImpl/RISCV64/RISCV64Timer.cpp