ETISS 0.8.0: etiss::instr::InstructionClass Class Reference
etiss::instr::InstructionClass Class Reference
maps to VariableInstructionSet
#include <Instruction.h>
Public Member Functions
etiss_del_como (InstructionClass) template< typename... T > InstructionClass(unsigned mode
const std::string unsigned InstructionGroup T name_ (name)
const std::string unsigned InstructionGroup T width_ (width)
void foreach (std::function< void(InstructionGroup &)> call)
void addTo (VariableInstructionSet &set, bool &ok)
etiss_del_como (InstructionClass) template< typename... T > InstructionClass(unsigned mode
const std::string unsigned InstructionGroup T name_ (name)
const std::string unsigned InstructionGroup T width_ (width)
void foreach (std::function< void(InstructionGroup &)> call)
void addTo (VariableInstructionSet &set, bool &ok)
Public Attributes
const unsigned mode_
const std::string name_
const unsigned width_
const std::string & name
const std::string unsigned width
const std::string unsigned InstructionGroup & group1
const std::string unsigned InstructionGroup T & othergroups: mode_(mode)
Private Member Functions
template<typename... T>
void add (InstructionGroup &group, T &... args)
void add ()
template<typename... T>
void add (InstructionGroup &group, T &... args)
void add ()
Private Attributes
std::set< InstructionGroup * > groups_
Detailed Description
maps to VariableInstructionSet
Definition at line 892 of file Instruction.h.
Member Function Documentation
add() [1/4]
void etiss::instr::InstructionClass::add () inline private
Definition at line 902 of file Instruction.h.
Referenced by add(), and width_().
add() [2/4]
void etiss::instr::InstructionClass::add () inline private
Definition at line 902 of file Instruction.h.
add() [3/4]
template<typename... T> void etiss::instr::InstructionClass::add (InstructionGroup & group, T &... args) inline private
Definition at line 897 of file Instruction.h.
References add(), and groups_.
add() [4/4]
template<typename... T> void etiss::instr::InstructionClass::add (InstructionGroup & group, T &... args) inline private
Definition at line 897 of file Instruction.h.
References add(), and groups_.
addTo() [1/2]
void etiss::instr::InstructionClass::addTo (VariableInstructionSet & set, bool & ok)
Definition at line 1218 of file Instruction.cpp.
References etiss::instr::InstructionGroup::addTo(), etiss::instr::InstructionGroup::name_, etiss::instr::VariableInstructionSet::open(), and etiss::instr::InstructionGroup::width_.
Referenced by etiss::instr::InstructionCollection::addTo().
addTo() [2/2]
void etiss::instr::InstructionClass::addTo (VariableInstructionSet & set, bool & ok)
etiss_del_como() [1/2]
etiss::instr::InstructionClass::etiss_del_como (InstructionClass)
etiss_del_como() [2/2]
etiss::instr::InstructionClass::etiss_del_como (InstructionClass)
foreach() [1/2]
void etiss::instr::InstructionClass::foreach (std::function< void(InstructionGroup &)> call) inline
Definition at line 918 of file Instruction.h.
References groups_.
foreach() [2/2]
void etiss::instr::InstructionClass::foreach (std::function< void(InstructionGroup &)> call) inline
Definition at line 918 of file Instruction.h.
References groups_.
name_() [1/2]
const std::string unsigned InstructionGroup T etiss::instr::InstructionClass::name_ (name)
name_() [2/2]
const std::string unsigned InstructionGroup T etiss::instr::InstructionClass::name_ (name)
width_() [1/2]
const std::string unsigned InstructionGroup T etiss::instr::InstructionClass::width_ (width) inline
Definition at line 914 of file Instruction.h.
References add(), group1, and othergroups.
width_() [2/2]
const std::string unsigned InstructionGroup T etiss::instr::InstructionClass::width_ (width) inline
Definition at line 914 of file Instruction.h.
References add(), group1, and othergroups.
Member Data Documentation
group1
const std::string unsigned InstructionGroup & etiss::instr::InstructionClass::group1
Definition at line 912 of file Instruction.h.
Referenced by width_().
groups_
std::set< InstructionGroup * > etiss::instr::InstructionClass::groups_ private
Definition at line 895 of file Instruction.h.
Referenced by add(), and foreach().
mode_
const unsigned etiss::instr::InstructionClass::mode_
Definition at line 905 of file Instruction.h.
Referenced by etiss::instr::InstructionCollection::addTo().
name
const std::string & etiss::instr::InstructionClass::name
Definition at line 912 of file Instruction.h.
name_
const std::string etiss::instr::InstructionClass::name_
Definition at line 906 of file Instruction.h.
Referenced by etiss::instr::InstructionCollection::addTo().
othergroups
const std::string unsigned InstructionGroup T & etiss::instr::InstructionClass::othergroups
Definition at line 914 of file Instruction.h.
Referenced by width_().
width
const std::string unsigned etiss::instr::InstructionClass::width
Definition at line 912 of file Instruction.h.
width_
const unsigned etiss::instr::InstructionClass::width_
Definition at line 907 of file Instruction.h.
Referenced by etiss::instr::InstructionCollection::addTo().
The documentation for this class was generated from the following files:
include/etiss/Instruction.h
/home/runner/work/etiss/etiss/src/Instruction.cpp