ETISS 0.8.0: etiss::FixedSizeHashMap< K, V, hashFunc, log2_buckets > Class Template Reference
etiss::FixedSizeHashMap< K, V, hashFunc, log2_buckets > Class Template Reference
#include <FixedSizeHashMap.h>
Classes
class Entry
Public Member Functions
FixedSizeHashMap ()
~FixedSizeHashMap ()
etiss_del_como (FixedSizeHashMap) V *insert(const K &key
void erase (const K &key)
V * find (const K &key)
const V * find (const K &key) const
FixedSizeHashMap ()
~FixedSizeHashMap ()
etiss_del_como (FixedSizeHashMap) V *insert(const K &key
void erase (const K &key)
V * find (const K &key)
const V * find (const K &key) const
Public Attributes
const V & val
Entry ** ptr = &(map[hk & set_lsbs(log2_buckets)])
Private Attributes
etiss::ObjectPool< Entry > pool
Entry * map [1<< log2_buckets]
hashFunc hash
Detailed Description
template<typename K, typename V, typename hashFunc = typename std::hash<K>, size_t log2_buckets = 16>
class etiss::FixedSizeHashMap< K, V, hashFunc, log2_buckets >
Definition at line 78 of file FixedSizeHashMap.h.
Constructor & Destructor Documentation
FixedSizeHashMap() [1/2]
template<typename K , typename V , typename hashFunc = typename std::hash<K>, size_t log2_buckets = 16> etiss::FixedSizeHashMap< K, V, hashFunc, log2_buckets >::FixedSizeHashMap () inline
Definition at line 99 of file FixedSizeHashMap.h.
~FixedSizeHashMap() [1/2]
template<typename K , typename V , typename hashFunc = typename std::hash<K>, size_t log2_buckets = 16> etiss::FixedSizeHashMap< K, V, hashFunc, log2_buckets >::~FixedSizeHashMap () inline
Definition at line 107 of file FixedSizeHashMap.h.
FixedSizeHashMap() [2/2]
template<typename K , typename V , typename hashFunc = typename std::hash<K>, size_t log2_buckets = 16> etiss::FixedSizeHashMap< K, V, hashFunc, log2_buckets >::FixedSizeHashMap () inline
Definition at line 99 of file FixedSizeHashMap.h.
~FixedSizeHashMap() [2/2]
template<typename K , typename V , typename hashFunc = typename std::hash<K>, size_t log2_buckets = 16> etiss::FixedSizeHashMap< K, V, hashFunc, log2_buckets >::~FixedSizeHashMap () inline
Definition at line 107 of file FixedSizeHashMap.h.
Member Function Documentation
erase() [1/2]
template<typename K , typename V , typename hashFunc = typename std::hash<K>, size_t log2_buckets = 16> void etiss::FixedSizeHashMap< K, V, hashFunc, log2_buckets >::erase (const K & key) inline
Definition at line 160 of file FixedSizeHashMap.h.
Referenced by etiss::interfaces::dot::ValueOperationTraceGraphStreamer::undefineNode().
erase() [2/2]
template<typename K , typename V , typename hashFunc = typename std::hash<K>, size_t log2_buckets = 16> void etiss::FixedSizeHashMap< K, V, hashFunc, log2_buckets >::erase (const K & key) inline
Definition at line 160 of file FixedSizeHashMap.h.
etiss_del_como() [1/2]
template<typename K , typename V , typename hashFunc = typename std::hash<K>, size_t log2_buckets = 16> etiss::FixedSizeHashMap< K, V, hashFunc, log2_buckets >::etiss_del_como (FixedSizeHashMap< K, V, hashFunc, log2_buckets >) const &
etiss_del_como() [2/2]
template<typename K , typename V , typename hashFunc = typename std::hash<K>, size_t log2_buckets = 16> etiss::FixedSizeHashMap< K, V, hashFunc, log2_buckets >::etiss_del_como (FixedSizeHashMap< K, V, hashFunc, log2_buckets >) const &
find() [1/4]
template<typename K , typename V , typename hashFunc = typename std::hash<K>, size_t log2_buckets = 16> V* etiss::FixedSizeHashMap< K, V, hashFunc, log2_buckets >::find (const K & key) inline
Definition at line 180 of file FixedSizeHashMap.h.
find() [2/4]
template<typename K , typename V , typename hashFunc = typename std::hash<K>, size_t log2_buckets = 16> V* etiss::FixedSizeHashMap< K, V, hashFunc, log2_buckets >::find (const K & key) inline
Definition at line 180 of file FixedSizeHashMap.h.
Referenced by etiss::interfaces::dot::ValueOperationTraceGraphStreamer::link(), etiss::interfaces::dot::ValueOperationTraceGraphStreamer::traverse(), and etiss::interfaces::dot::ValueOperationTraceGraphStreamer::writePath().
find() [3/4]
template<typename K , typename V , typename hashFunc = typename std::hash<K>, size_t log2_buckets = 16> const V* etiss::FixedSizeHashMap< K, V, hashFunc, log2_buckets >::find (const K & key) const inline
Definition at line 194 of file FixedSizeHashMap.h.
find() [4/4]
template<typename K , typename V , typename hashFunc = typename std::hash<K>, size_t log2_buckets = 16> const V* etiss::FixedSizeHashMap< K, V, hashFunc, log2_buckets >::find (const K & key) const inline
Definition at line 194 of file FixedSizeHashMap.h.
Member Data Documentation
hash
template<typename K , typename V , typename hashFunc = typename std::hash<K>, size_t log2_buckets = 16> hashFunc etiss::FixedSizeHashMap< K, V, hashFunc, log2_buckets >::hash private
Definition at line 96 of file FixedSizeHashMap.h.
Referenced by etiss::FixedSizeHashMap< const void *, etiss::interfaces::dot::ValueOperationTraceGraphStreamer::Node *, etiss::pointerHash< const void > >::erase(), and etiss::FixedSizeHashMap< const void *, etiss::interfaces::dot::ValueOperationTraceGraphStreamer::Node *, etiss::pointerHash< const void > >::find().
map
template<typename K , typename V , typename hashFunc = typename std::hash<K>, size_t log2_buckets = 16> Entry * etiss::FixedSizeHashMap< K, V, hashFunc, log2_buckets >::map private
Definition at line 95 of file FixedSizeHashMap.h.
Referenced by etiss::FixedSizeHashMap< const void *, etiss::interfaces::dot::ValueOperationTraceGraphStreamer::Node *, etiss::pointerHash< const void > >::erase(), etiss::FixedSizeHashMap< const void *, etiss::interfaces::dot::ValueOperationTraceGraphStreamer::Node *, etiss::pointerHash< const void > >::find(), etiss::FixedSizeHashMap< const void *, etiss::interfaces::dot::ValueOperationTraceGraphStreamer::Node *, etiss::pointerHash< const void > >::FixedSizeHashMap(), and etiss::FixedSizeHashMap< const void *, etiss::interfaces::dot::ValueOperationTraceGraphStreamer::Node *, etiss::pointerHash< const void > >::~FixedSizeHashMap().
pool
template<typename K , typename V , typename hashFunc = typename std::hash<K>, size_t log2_buckets = 16> etiss::ObjectPool< Entry > etiss::FixedSizeHashMap< K, V, hashFunc, log2_buckets >::pool private
Definition at line 94 of file FixedSizeHashMap.h.
Referenced by etiss::FixedSizeHashMap< const void *, etiss::interfaces::dot::ValueOperationTraceGraphStreamer::Node *, etiss::pointerHash< const void > >::erase(), and etiss::FixedSizeHashMap< const void *, etiss::interfaces::dot::ValueOperationTraceGraphStreamer::Node *, etiss::pointerHash< const void > >::~FixedSizeHashMap().
ptr
template<typename K , typename V , typename hashFunc = typename std::hash<K>, size_t log2_buckets = 16> Entry ** etiss::FixedSizeHashMap< K, V, hashFunc, log2_buckets >::ptr = &(map[hk & set_lsbs(log2_buckets)])
Definition at line 130 of file FixedSizeHashMap.h.
Referenced by etiss::FixedSizeHashMap< const void *, etiss::interfaces::dot::ValueOperationTraceGraphStreamer::Node *, etiss::pointerHash< const void > >::erase(), and etiss::FixedSizeHashMap< const void *, etiss::interfaces::dot::ValueOperationTraceGraphStreamer::Node *, etiss::pointerHash< const void > >::find().
val
template<typename K , typename V , typename hashFunc = typename std::hash<K>, size_t log2_buckets = 16> const V & etiss::FixedSizeHashMap< K, V, hashFunc, log2_buckets >::val
Initial value:
{
        size_t hk = hash(key)
Definition at line 125 of file FixedSizeHashMap.h.
The documentation for this class was generated from the following file:
include/etiss/FixedSizeHashMap.h