ETISS 0.8.0: etiss::instr::BitArray Class Reference
etiss::instr::BitArray Class Reference
stores a bit vector
#include <Instruction.h>
Public Member Functions
BitArray (unsigned width)
constructs a bit array with the given width in bits.
template<typename T , typename = typename std::enable_if<std::is_integral<T>::value, T>::type>
BitArray (unsigned width, const T val)
constructs a bit array with the given width in bits.
BitArray (const BitArray &o)
copy ctor
BitArray (BitArray &&o)
move ctor
~BitArray ()
dtor
unsigned wordCount () const
unsigned byteCount () const
unsigned width () const
I & getWord (unsigned index)
returns a reference to the word at the given index.
const I & getWord (unsigned index) const
const version.
bool get (unsigned index) const
void set (unsigned index, bool val)
sets the value of the bit at the given index
void setAll (bool val)
sets all bits in the array to the given value
BitArray operator| (const BitArray &o) const
bitwise or operator
BitArray operator& (const BitArray &o) const
bitwise and operator
BitArray operator~ () const
bitwise not operator
bool operator< (const BitArray &o) const
less than operator
bool operator== (const BitArray &o) const
equals operator
bool operator!= (const BitArray &o) const
template<typename LI >
std::enable_if< std::is_integral< LI >::value &&(sizeof(LI) > sizeof(I)), BitArray & >::type operator= (LI val)
assign operator.
template<typename LI >
std::enable_if< std::is_integral< LI >::value &&(sizeof(LI)<=sizeof(I)), BitArray & >::type operator= (LI val)
assign operator.
BitArray & operator= (const BitArray &o)
copy operator
BitArray & operator= (BitArray &&o)
move operator
unsigned getBitSetCount (unsigned index) const
returns the number of consecutive bits set upwards from given address.
char * internalBuffer ()
get the internal buffer
unsigned internalBufferSize ()
void recoverFromEndianness (unsigned alignment, endian_t endianness)
changes byte positions as needed to resove endiannes incompabilities after using the internal buffer to write
BitArray (unsigned width)
constructs a bit array with the given width in bits.
template<typename T , typename = typename std::enable_if<std::is_integral<T>::value, T>::type>
BitArray (unsigned width, const T val)
constructs a bit array with the given width in bits.
BitArray (const BitArray &o)
copy ctor
BitArray (BitArray &&o)
move ctor
~BitArray ()
dtor
unsigned wordCount () const
unsigned byteCount () const
unsigned width () const
I & getWord (unsigned index)
returns a reference to the word at the given index.
const I & getWord (unsigned index) const
const version.
bool get (unsigned index) const
void set (unsigned index, bool val)
sets the value of the bit at the given index
void setAll (bool val)
sets all bits in the array to the given value
BitArray operator| (const BitArray &o) const
bitwise or operator
BitArray operator& (const BitArray &o) const
bitwise and operator
BitArray operator~ () const
bitwise not operator
bool operator< (const BitArray &o) const
less than operator
bool operator== (const BitArray &o) const
equals operator
bool operator!= (const BitArray &o) const
template<typename LI >
std::enable_if< std::is_integral< LI >::value &&(sizeof(LI) > sizeof(I)), BitArray & >::type operator= (LI val)
assign operator.
template<typename LI >
std::enable_if< std::is_integral< LI >::value &&(sizeof(LI)<=sizeof(I)), BitArray & >::type operator= (LI val)
assign operator.
BitArray & operator= (const BitArray &o)
copy operator
BitArray & operator= (BitArray &&o)
move operator
unsigned getBitSetCount (unsigned index) const
returns the number of consecutive bits set upwards from given address.
char * internalBuffer ()
get the internal buffer
unsigned internalBufferSize ()
void recoverFromEndianness (unsigned alignment, endian_t endianness)
changes byte positions as needed to resove endiannes incompabilities after using the internal buffer to write
Static Private Member Functions
static unsigned gen_mask (unsigned width, unsigned intcount)
static unsigned gen_intcount (unsigned width)
static unsigned gen_bytecount (unsigned width)
static unsigned gen_mask (unsigned width, unsigned intcount)
static unsigned gen_intcount (unsigned width)
static unsigned gen_bytecount (unsigned width)
Private Attributes
const unsigned intcount_
number of I's required to store the data
I * d_
stored data
const unsigned w_
bit width
const unsigned bw_
byte width
const unsigned endmask_
mask to remove additional bits due to width/sizeof(I) missmatch
bool bsvalid_
unsigned * bscount_
Static Private Attributes
static const unsigned aaddr_mask_ = etiss_instr_generateMask()
static const unsigned aaddr_shift_ = etiss_instr_sqrt_2pow(sizeof(I) * 8)
Friends
class BitArrayRange
Detailed Description
stores a bit vector
Definition at line 84 of file Instruction.h.
Constructor & Destructor Documentation
BitArray() [1/8]
etiss::instr::BitArray::BitArray (unsigned width)
constructs a bit array with the given width in bits.
Definition at line 67 of file Instruction.cpp.
References d_, and intcount_.
BitArray() [2/8]
template<typename T , typename = typename std::enable_if<std::is_integral<T>::value, T>::type> etiss::instr::BitArray::BitArray (unsigned width, const T val) inline
constructs a bit array with the given width in bits.
the passed value is used to initialize the array and may be longer or shorter than the storage type I
Definition at line 140 of file Instruction.h.
References d_, int, and intcount_.
BitArray() [3/8]
etiss::instr::BitArray::BitArray (const BitArray & o)
copy ctor
Definition at line 82 of file Instruction.cpp.
References bscount_, bsvalid_, d_, intcount_, and w_.
BitArray() [4/8]
etiss::instr::BitArray::BitArray (BitArray && o)
move ctor
Definition at line 103 of file Instruction.cpp.
~BitArray() [1/2]
etiss::instr::BitArray::~BitArray ()
dtor
Definition at line 134 of file Instruction.cpp.
References bscount_, and d_.
BitArray() [5/8]
etiss::instr::BitArray::BitArray (unsigned width)
constructs a bit array with the given width in bits.
BitArray() [6/8]
template<typename T , typename = typename std::enable_if<std::is_integral<T>::value, T>::type> etiss::instr::BitArray::BitArray (unsigned width, const T val) inline
constructs a bit array with the given width in bits.
the passed value is used to initialize the array and may be longer or shorter than the storage type I
Definition at line 140 of file Instruction.h.
References d_, int, and intcount_.
BitArray() [7/8]
etiss::instr::BitArray::BitArray (const BitArray & o)
copy ctor
BitArray() [8/8]
etiss::instr::BitArray::BitArray (BitArray && o)
move ctor
~BitArray() [2/2]
etiss::instr::BitArray::~BitArray ()
dtor
Member Function Documentation
byteCount() [1/2]
unsigned etiss::instr::BitArray::byteCount () const inline
Returns
number of bytes stored in this array (rounded up if neccessary)
Definition at line 183 of file Instruction.h.
References bw_.
Referenced by etiss::instr::operator<<(), and etiss::Translation::translateBlock().
byteCount() [2/2]
unsigned etiss::instr::BitArray::byteCount () const inline
Returns
number of bytes stored in this array (rounded up if neccessary)
Definition at line 183 of file Instruction.h.
References bw_.
gen_bytecount() [1/2]
static unsigned etiss::instr::BitArray::gen_bytecount (unsigned width) inline static private
Definition at line 113 of file Instruction.h.
References width().
gen_bytecount() [2/2]
static unsigned etiss::instr::BitArray::gen_bytecount (unsigned width) inline static private
Definition at line 113 of file Instruction.h.
References width().
gen_intcount() [1/2]
static unsigned etiss::instr::BitArray::gen_intcount (unsigned width) inline static private
Definition at line 105 of file Instruction.h.
References width().
gen_intcount() [2/2]
static unsigned etiss::instr::BitArray::gen_intcount (unsigned width) inline static private
Definition at line 105 of file Instruction.h.
References width().
gen_mask() [1/2]
static unsigned etiss::instr::BitArray::gen_mask (unsigned width, unsigned intcount) inline static private
Definition at line 95 of file Instruction.h.
References width().
gen_mask() [2/2]
static unsigned etiss::instr::BitArray::gen_mask (unsigned width, unsigned intcount) inline static private
Definition at line 95 of file Instruction.h.
References width().
get() [1/2]
bool etiss::instr::BitArray::get (unsigned index) const
Returns
the value of the bit at the given index
Definition at line 140 of file Instruction.cpp.
References aaddr_mask_, aaddr_shift_, d_, and w_.
Referenced by getBitSetCount().
get() [2/2]
bool etiss::instr::BitArray::get (unsigned index) const
Returns
the value of the bit at the given index
getBitSetCount() [1/2]
unsigned etiss::instr::BitArray::getBitSetCount (unsigned index) const
returns the number of consecutive bits set upwards from given address.
e.g. b1011 -> getBitSetCount(0) returns 2,getBitSetCount(1) returns 1, getBitSetCount(2) returns 0
Definition at line 270 of file Instruction.cpp.
References bscount_, bsvalid_, get(), and w_.
Referenced by etiss::instr::Node::compile().
getBitSetCount() [2/2]
unsigned etiss::instr::BitArray::getBitSetCount (unsigned index) const
returns the number of consecutive bits set upwards from given address.
e.g. b1011 -> getBitSetCount(0) returns 2,getBitSetCount(1) returns 1, getBitSetCount(2) returns 0
getWord() [1/4]
I& etiss::instr::BitArray::getWord (unsigned index) inline
returns a reference to the word at the given index.
Attention
the index is not check. use wordCount() to get the size of the internal storage array
the array size in bits may be smaller then the total count of bits in the storage array. in this case the additional bits MUST be zero
Definition at line 195 of file Instruction.h.
References d_.
getWord() [2/4]
I& etiss::instr::BitArray::getWord (unsigned index) inline
returns a reference to the word at the given index.
Attention
the index is not check. use wordCount() to get the size of the internal storage array
the array size in bits may be smaller then the total count of bits in the storage array. in this case the additional bits MUST be zero
Definition at line 195 of file Instruction.h.
References d_.
Referenced by etiss::instr::operator<<().
getWord() [3/4]
const I& etiss::instr::BitArray::getWord (unsigned index) const inline
const version.
See also
getWord(unsigned index)
Definition at line 199 of file Instruction.h.
References d_.
getWord() [4/4]
const I& etiss::instr::BitArray::getWord (unsigned index) const inline
const version.
See also
getWord(unsigned index)
Definition at line 199 of file Instruction.h.
References d_.
internalBuffer() [1/2]
char * etiss::instr::BitArray::internalBuffer ()
get the internal buffer
Attention
call recoverFromEndianness() to order the bytes after writing data
selective write operations together with recoverFromEndianness() are not supported
Definition at line 298 of file Instruction.cpp.
References d_.
Referenced by etiss::Translation::disasm(), and etiss::Translation::translateBlock().
internalBuffer() [2/2]
char* etiss::instr::BitArray::internalBuffer ()
get the internal buffer
Attention
call recoverFromEndianness() to order the bytes after writing data
selective write operations together with recoverFromEndianness() are not supported
internalBufferSize() [1/2]
unsigned etiss::instr::BitArray::internalBufferSize ()
Returns
same as width * sizeof(I)
internalBufferSize() [2/2]
unsigned etiss::instr::BitArray::internalBufferSize ()
Returns
same as width * sizeof(I)
Definition at line 302 of file Instruction.cpp.
References intcount_.
operator!=() [1/2]
bool etiss::instr::BitArray::operator!= (const BitArray & o) const inline
Definition at line 222 of file Instruction.h.
operator!=() [2/2]
bool etiss::instr::BitArray::operator!= (const BitArray & o) const inline
Definition at line 222 of file Instruction.h.
operator&() [1/2]
BitArray etiss::instr::BitArray::operator& (const BitArray & o) const
bitwise and operator
operator&() [2/2]
BitArray etiss::instr::BitArray::operator& (const BitArray & o) const
bitwise and operator
Definition at line 202 of file Instruction.cpp.
References d_, intcount_, w_, and width().
operator<() [1/2]
bool etiss::instr::BitArray::operator< (const BitArray & o) const
less than operator
operator<() [2/2]
bool etiss::instr::BitArray::operator< (const BitArray & o) const
less than operator
Definition at line 222 of file Instruction.cpp.
References d_, intcount_, and w_.
operator=() [1/8]
BitArray & etiss::instr::BitArray::operator= (BitArray && o)
move operator
Definition at line 115 of file Instruction.cpp.
References bscount_, d_, and w_.
operator=() [2/8]
BitArray& etiss::instr::BitArray::operator= (BitArray && o)
move operator
operator=() [3/8]
BitArray& etiss::instr::BitArray::operator= (const BitArray & o)
copy operator
operator=() [4/8]
BitArray & etiss::instr::BitArray::operator= (const BitArray & o)
copy operator
Definition at line 249 of file Instruction.cpp.
References bscount_, bsvalid_, d_, intcount_, and w_.
operator=() [5/8]
template<typename LI > std::enable_if<std::is_integral<LI>::value && (sizeof(LI) > sizeof(I)), BitArray &>::type etiss::instr::BitArray::operator= (LI val) inline
assign operator.
allows to use any type of integral value
Attention
if LI is larger than this bit array the most significant bits will be silently discarded
signed variables will have their msb extended
Definition at line 230 of file Instruction.h.
References d_, endmask_, and intcount_.
operator=() [6/8]
template<typename LI > std::enable_if<std::is_integral<LI>::value && (sizeof(LI) > sizeof(I)), BitArray &>::type etiss::instr::BitArray::operator= (LI val) inline
assign operator.
allows to use any type of integral value
Attention
if LI is larger than this bit array the most significant bits will be silently discarded
signed variables will have their msb extended
Definition at line 230 of file Instruction.h.
References d_, endmask_, and intcount_.
operator=() [7/8]
template<typename LI > std::enable_if<std::is_integral<LI>::value && (sizeof(LI) <= sizeof(I)), BitArray &>::type etiss::instr::BitArray::operator= (LI val) inline
assign operator.
allows to use any type of integral value
Attention
signed variables will have their msb extended.
Definition at line 249 of file Instruction.h.
References d_, endmask_, and intcount_.
operator=() [8/8]
template<typename LI > std::enable_if<std::is_integral<LI>::value && (sizeof(LI) <= sizeof(I)), BitArray &>::type etiss::instr::BitArray::operator= (LI val) inline
assign operator.
allows to use any type of integral value
Attention
signed variables will have their msb extended.
Definition at line 249 of file Instruction.h.
References d_, endmask_, and intcount_.
operator==() [1/2]
bool etiss::instr::BitArray::operator== (const BitArray & o) const
equals operator
operator==() [2/2]
bool etiss::instr::BitArray::operator== (const BitArray & o) const
equals operator
Definition at line 235 of file Instruction.cpp.
References d_, intcount_, and w_.
operator|() [1/2]
BitArray etiss::instr::BitArray::operator| (const BitArray & o) const
bitwise or operator
operator|() [2/2]
BitArray etiss::instr::BitArray::operator| (const BitArray & o) const
bitwise or operator
Definition at line 191 of file Instruction.cpp.
References d_, intcount_, w_, and width().
operator~() [1/2]
BitArray etiss::instr::BitArray::operator~ () const
bitwise not operator
operator~() [2/2]
BitArray etiss::instr::BitArray::operator~ () const
bitwise not operator
Definition at line 213 of file Instruction.cpp.
References d_, and intcount_.
recoverFromEndianness() [1/2]
void etiss::instr::BitArray::recoverFromEndianness (unsigned alignment, endian_t endianness)
changes byte positions as needed to resove endiannes incompabilities after using the internal buffer to write
recoverFromEndianness() [2/2]
void etiss::instr::BitArray::recoverFromEndianness (unsigned alignment, endian_t endianness)
changes byte positions as needed to resove endiannes incompabilities after using the internal buffer to write
Definition at line 307 of file Instruction.cpp.
References d_, ETISS_SRCLOC, etiss::FATALERROR, etiss::getEndianness(), intcount_, and etiss::log().
Referenced by etiss::CPUArch::compensateEndianess().
set() [1/2]
void etiss::instr::BitArray::set (unsigned index, bool val)
sets the value of the bit at the given index
set() [2/2]
void etiss::instr::BitArray::set (unsigned index, bool val)
sets the value of the bit at the given index
Definition at line 152 of file Instruction.cpp.
References aaddr_mask_, aaddr_shift_, bsvalid_, d_, v, and w_.
setAll() [1/2]
void etiss::instr::BitArray::setAll (bool val)
sets all bits in the array to the given value
setAll() [2/2]
void etiss::instr::BitArray::setAll (bool val)
sets all bits in the array to the given value
Definition at line 173 of file Instruction.cpp.
References d_, and intcount_.
Referenced by etiss::instr::Node::compile(), and etiss::instr::InstructionSet::compile().
width() [1/2]
unsigned etiss::instr::BitArray::width () const inline
Returns
number of bits in this array. this equals the width value passed to the constructor
Definition at line 188 of file Instruction.h.
References w_.
Referenced by etiss::instr::Node::compile(), gen_bytecount(), gen_intcount(), gen_mask(), etiss::instr::OPCode::OPCode(), operator&(), operator|(), and etiss::Translation::translateBlock().
width() [2/2]
unsigned etiss::instr::BitArray::width () const inline
Returns
number of bits in this array. this equals the width value passed to the constructor
Definition at line 188 of file Instruction.h.
References w_.
wordCount() [1/2]
unsigned etiss::instr::BitArray::wordCount () const inline
Returns
number of internal number of I variables used to store the bit array
Definition at line 179 of file Instruction.h.
References intcount_.
wordCount() [2/2]
unsigned etiss::instr::BitArray::wordCount () const inline
Returns
number of internal number of I variables used to store the bit array
Definition at line 179 of file Instruction.h.
References intcount_.
Referenced by etiss::instr::operator<<().
Friends And Related Function Documentation
BitArrayRange
BitArrayRange friend
Definition at line 88 of file Instruction.h.
Member Data Documentation
aaddr_mask_
const unsigned etiss::instr::BitArray::aaddr_mask_ = etiss_instr_generateMask() static private
Definition at line 93 of file Instruction.h.
Referenced by get(), and set().
aaddr_shift_
const unsigned etiss::instr::BitArray::aaddr_shift_ = etiss_instr_sqrt_2pow(sizeof(I) * 8) static private
Definition at line 94 of file Instruction.h.
Referenced by get(), and set().
bscount_
unsigned * etiss::instr::BitArray::bscount_ mutable private
See also
getBitSetCount
Definition at line 129 of file Instruction.h.
Referenced by BitArray(), getBitSetCount(), operator=(), and ~BitArray().
bsvalid_
bool etiss::instr::BitArray::bsvalid_ mutable private
See also
getBitSetCount
Definition at line 128 of file Instruction.h.
Referenced by BitArray(), getBitSetCount(), operator=(), and set().
bw_
const unsigned etiss::instr::BitArray::bw_ private
byte width
Definition at line 126 of file Instruction.h.
Referenced by byteCount().
d_
I * etiss::instr::BitArray::d_ private
stored data
Definition at line 124 of file Instruction.h.
Referenced by BitArray(), get(), getWord(), internalBuffer(), operator&(), operator<(), operator=(), operator==(), operator|(), operator~(), etiss::instr::BitArrayRange::read(), recoverFromEndianness(), set(), setAll(), etiss::instr::BitArrayRange::write(), and ~BitArray().
endmask_
const unsigned etiss::instr::BitArray::endmask_ private
mask to remove additional bits due to width/sizeof(I) missmatch
Definition at line 127 of file Instruction.h.
Referenced by operator=().
intcount_
const unsigned etiss::instr::BitArray::intcount_ private
number of I's required to store the data
Definition at line 123 of file Instruction.h.
Referenced by BitArray(), internalBufferSize(), operator&(), operator<(), operator=(), operator==(), operator|(), operator~(), recoverFromEndianness(), setAll(), and wordCount().
w_
const unsigned etiss::instr::BitArray::w_ private
bit width
Definition at line 125 of file Instruction.h.
Referenced by BitArray(), get(), getBitSetCount(), operator&(), operator<(), operator=(), operator==(), operator|(), etiss::instr::BitArrayRange::read(), set(), width(), and etiss::instr::BitArrayRange::write().
The documentation for this class was generated from the following files:
include/etiss/Instruction.h
/home/runner/work/etiss/etiss/src/Instruction.cpp