ETISS 0.8.0: pugi::xml_node Class Reference
pugi::xml_node Class Reference
#include <pugixml.hpp>
Public Types
typedef xml_node_iterator iterator
typedef xml_attribute_iterator attribute_iterator
typedef xml_node_iterator iterator
typedef xml_attribute_iterator attribute_iterator
Public Member Functions
xml_node ()
xml_node (xml_node_struct *p)
operator unspecified_bool_type () const
bool operator! () const
bool operator== (const xml_node &r) const
bool operator!= (const xml_node &r) const
bool operator< (const xml_node &r) const
bool operator> (const xml_node &r) const
bool operator<= (const xml_node &r) const
bool operator>= (const xml_node &r) const
bool empty () const
xml_node_type type () const
const char_t * name () const
const char_t * value () const
xml_attribute first_attribute () const
xml_attribute last_attribute () const
xml_node first_child () const
xml_node last_child () const
xml_node next_sibling () const
xml_node previous_sibling () const
xml_node parent () const
xml_node root () const
xml_text text () const
xml_node child (const char_t *name) const
xml_attribute attribute (const char_t *name) const
xml_node next_sibling (const char_t *name) const
xml_node previous_sibling (const char_t *name) const
const char_t * child_value () const
const char_t * child_value (const char_t *name) const
bool set_name (const char_t *rhs)
bool set_value (const char_t *rhs)
xml_attribute append_attribute (const char_t *name)
xml_attribute prepend_attribute (const char_t *name)
xml_attribute insert_attribute_after (const char_t *name, const xml_attribute &attr)
xml_attribute insert_attribute_before (const char_t *name, const xml_attribute &attr)
xml_attribute append_copy (const xml_attribute &proto)
xml_attribute prepend_copy (const xml_attribute &proto)
xml_attribute insert_copy_after (const xml_attribute &proto, const xml_attribute &attr)
xml_attribute insert_copy_before (const xml_attribute &proto, const xml_attribute &attr)
xml_node append_child (xml_node_type type=node_element)
xml_node prepend_child (xml_node_type type=node_element)
xml_node insert_child_after (xml_node_type type, const xml_node &node)
xml_node insert_child_before (xml_node_type type, const xml_node &node)
xml_node append_child (const char_t *name)
xml_node prepend_child (const char_t *name)
xml_node insert_child_after (const char_t *name, const xml_node &node)
xml_node insert_child_before (const char_t *name, const xml_node &node)
xml_node append_copy (const xml_node &proto)
xml_node prepend_copy (const xml_node &proto)
xml_node insert_copy_after (const xml_node &proto, const xml_node &node)
xml_node insert_copy_before (const xml_node &proto, const xml_node &node)
bool remove_attribute (const xml_attribute &a)
bool remove_attribute (const char_t *name)
bool remove_child (const xml_node &n)
bool remove_child (const char_t *name)
xml_parse_result append_buffer (const void *contents, size_t size, unsigned int options=parse_default, xml_encoding encoding=encoding_auto)
template<typename Predicate >
xml_attribute find_attribute (Predicate pred) const
template<typename Predicate >
xml_node find_child (Predicate pred) const
template<typename Predicate >
xml_node find_node (Predicate pred) const
xml_node find_child_by_attribute (const char_t *name, const char_t *attr_name, const char_t *attr_value) const
xml_node find_child_by_attribute (const char_t *attr_name, const char_t *attr_value) const
string_t path (char_t delimiter='/') const
xml_node first_element_by_path (const char_t *path, char_t delimiter='/') const
bool traverse (xml_tree_walker &walker)
xpath_node select_single_node (const char_t *query, xpath_variable_set *variables=0) const
xpath_node select_single_node (const xpath_query &query) const
xpath_node_set select_nodes (const char_t *query, xpath_variable_set *variables=0) const
xpath_node_set select_nodes (const xpath_query &query) const
void print (xml_writer &writer, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default, xml_encoding encoding=encoding_auto, unsigned int depth=0) const
void print (std::basic_ostream< char, std::char_traits< char > > &os, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default, xml_encoding encoding=encoding_auto, unsigned int depth=0) const
void print (std::basic_ostream< wchar_t, std::char_traits< wchar_t > > &os, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default, unsigned int depth=0) const
iterator begin () const
iterator end () const
attribute_iterator attributes_begin () const
attribute_iterator attributes_end () const
xml_object_range< xml_node_iterator > children () const
xml_object_range< xml_named_node_iterator > children (const char_t *name) const
xml_object_range< xml_attribute_iterator > attributes () const
ptrdiff_t offset_debug () const
size_t hash_value () const
xml_node_struct * internal_object () const
xml_node ()
xml_node (xml_node_struct *p)
operator unspecified_bool_type () const
bool operator! () const
bool operator== (const xml_node &r) const
bool operator!= (const xml_node &r) const
bool operator< (const xml_node &r) const
bool operator> (const xml_node &r) const
bool operator<= (const xml_node &r) const
bool operator>= (const xml_node &r) const
bool empty () const
xml_node_type type () const
const char_t * name () const
const char_t * value () const
xml_attribute first_attribute () const
xml_attribute last_attribute () const
xml_node first_child () const
xml_node last_child () const
xml_node next_sibling () const
xml_node previous_sibling () const
xml_node parent () const
xml_node root () const
xml_text text () const
xml_node child (const char_t *name) const
xml_attribute attribute (const char_t *name) const
xml_node next_sibling (const char_t *name) const
xml_node previous_sibling (const char_t *name) const
const char_t * child_value () const
const char_t * child_value (const char_t *name) const
bool set_name (const char_t *rhs)
bool set_value (const char_t *rhs)
xml_attribute append_attribute (const char_t *name)
xml_attribute prepend_attribute (const char_t *name)
xml_attribute insert_attribute_after (const char_t *name, const xml_attribute &attr)
xml_attribute insert_attribute_before (const char_t *name, const xml_attribute &attr)
xml_attribute append_copy (const xml_attribute &proto)
xml_attribute prepend_copy (const xml_attribute &proto)
xml_attribute insert_copy_after (const xml_attribute &proto, const xml_attribute &attr)
xml_attribute insert_copy_before (const xml_attribute &proto, const xml_attribute &attr)
xml_node append_child (xml_node_type type=node_element)
xml_node prepend_child (xml_node_type type=node_element)
xml_node insert_child_after (xml_node_type type, const xml_node &node)
xml_node insert_child_before (xml_node_type type, const xml_node &node)
xml_node append_child (const char_t *name)
xml_node prepend_child (const char_t *name)
xml_node insert_child_after (const char_t *name, const xml_node &node)
xml_node insert_child_before (const char_t *name, const xml_node &node)
xml_node append_copy (const xml_node &proto)
xml_node prepend_copy (const xml_node &proto)
xml_node insert_copy_after (const xml_node &proto, const xml_node &node)
xml_node insert_copy_before (const xml_node &proto, const xml_node &node)
bool remove_attribute (const xml_attribute &a)
bool remove_attribute (const char_t *name)
bool remove_child (const xml_node &n)
bool remove_child (const char_t *name)
xml_parse_result append_buffer (const void *contents, size_t size, unsigned int options=parse_default, xml_encoding encoding=encoding_auto)
template<typename Predicate >
xml_attribute find_attribute (Predicate pred) const
template<typename Predicate >
xml_node find_child (Predicate pred) const
template<typename Predicate >
xml_node find_node (Predicate pred) const
xml_node find_child_by_attribute (const char_t *name, const char_t *attr_name, const char_t *attr_value) const
xml_node find_child_by_attribute (const char_t *attr_name, const char_t *attr_value) const
string_t path (char_t delimiter='/') const
xml_node first_element_by_path (const char_t *path, char_t delimiter='/') const
bool traverse (xml_tree_walker &walker)
xpath_node select_single_node (const char_t *query, xpath_variable_set *variables=0) const
xpath_node select_single_node (const xpath_query &query) const
xpath_node_set select_nodes (const char_t *query, xpath_variable_set *variables=0) const
xpath_node_set select_nodes (const xpath_query &query) const
void print (xml_writer &writer, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default, xml_encoding encoding=encoding_auto, unsigned int depth=0) const
void print (std::basic_ostream< char, std::char_traits< char > > &os, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default, xml_encoding encoding=encoding_auto, unsigned int depth=0) const
void print (std::basic_ostream< wchar_t, std::char_traits< wchar_t > > &os, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default, unsigned int depth=0) const
iterator begin () const
iterator end () const
attribute_iterator attributes_begin () const
attribute_iterator attributes_end () const
xml_object_range< xml_node_iterator > children () const
xml_object_range< xml_named_node_iterator > children (const char_t *name) const
xml_object_range< xml_attribute_iterator > attributes () const
ptrdiff_t offset_debug () const
size_t hash_value () const
xml_node_struct * internal_object () const
Protected Types
typedef void(* unspecified_bool_type) (xml_node ***)
typedef void(* unspecified_bool_type) (xml_node ***)
Protected Attributes
xml_node_struct * _root
Friends
class xml_attribute_iterator
class xml_node_iterator
class xml_named_node_iterator
Detailed Description
Definition at line 396 of file pugixml.hpp.
Member Typedef Documentation
attribute_iterator [1/2]
typedef xml_attribute_iterator pugi::xml_node::attribute_iterator
Definition at line 610 of file pugixml.hpp.
attribute_iterator [2/2]
typedef xml_attribute_iterator pugi::xml_node::attribute_iterator
Definition at line 610 of file pugixml.hpp.
iterator [1/2]
typedef xml_node_iterator pugi::xml_node::iterator
Definition at line 604 of file pugixml.hpp.
iterator [2/2]
typedef xml_node_iterator pugi::xml_node::iterator
Definition at line 604 of file pugixml.hpp.
unspecified_bool_type [1/2]
typedef void(* pugi::xml_node::unspecified_bool_type) (xml_node ***) protected
Definition at line 405 of file pugixml.hpp.
unspecified_bool_type [2/2]
typedef void(* pugi::xml_node::unspecified_bool_type) (xml_node ***) protected
Definition at line 405 of file pugixml.hpp.
Constructor & Destructor Documentation
xml_node() [1/4]
PUGI__FN pugi::xml_node::xml_node ()
Definition at line 4577 of file pugixml.cpp.
Referenced by append_child(), child(), pugi::xml_document::document_element(), find_child_by_attribute(), first_child(), first_element_by_path(), insert_child_after(), insert_child_before(), last_child(), next_sibling(), parent(), prepend_child(), previous_sibling(), and root().
xml_node() [2/4]
PUGI__FN pugi::xml_node::xml_node (xml_node_struct * p) explicit
Definition at line 4579 of file pugixml.cpp.
xml_node() [3/4]
pugi::xml_node::xml_node ()
xml_node() [4/4]
pugi::xml_node::xml_node (xml_node_struct * p) explicit
Member Function Documentation
append_attribute() [1/2]
PUGI__FN xml_attribute pugi::xml_node::append_attribute (const char_t * name)
Definition at line 4837 of file pugixml.cpp.
References _root, append_attribute_ll(), get_allocator(), pugi::node_declaration, pugi::node_element, pugi::xml_attribute::set_name(), and type().
Referenced by append_copy(), and etiss::fault::xml::setAttribute().
append_attribute() [2/2]
xml_attribute pugi::xml_node::append_attribute (const char_t * name)
append_buffer() [1/2]
xml_parse_result pugi::xml_node::append_buffer (const void * contents, size_t size, unsigned int options = parse_default, xml_encoding encoding = encoding_auto)
append_buffer() [2/2]
PUGI__FN xml_parse_result pugi::xml_node::append_buffer (const void * contents, size_t size, unsigned int options = parse_default, xml_encoding encoding = encoding_auto)
Definition at line 5217 of file pugixml.cpp.
References _root, allow_insert_child(), load_buffer_impl(), make_parse_result(), pugi::xml_node_struct::name, pugi::node_element, options, root(), pugi::status_append_invalid_root, pugi::status_out_of_memory, and type().
append_child() [1/4]
PUGI__FN xml_node pugi::xml_node::append_child (const char_t * name)
Definition at line 5082 of file pugixml.cpp.
References append_child(), pugi::node_element, and set_name().
append_child() [2/4]
xml_node pugi::xml_node::append_child (const char_t * name)
append_child() [3/4]
PUGI__FN xml_node pugi::xml_node::append_child (xml_node_type type = node_element)
Definition at line 4983 of file pugixml.cpp.
References _root, allow_insert_child(), append_node(), get_allocator(), pugi::node_declaration, PUGIXML_TEXT, set_name(), type(), and xml_node().
Referenced by append_child(), append_copy(), etiss::fault::Fault::toString(), and etiss::fault::Action::toString().
append_child() [4/4]
xml_node pugi::xml_node::append_child (xml_node_type type = node_element)
append_copy() [1/4]
PUGI__FN xml_attribute pugi::xml_node::append_copy (const xml_attribute & proto)
Definition at line 4939 of file pugixml.cpp.
References append_attribute(), pugi::xml_attribute::name(), pugi::xml_attribute::set_value(), and pugi::xml_attribute::value().
Referenced by pugi::xml_document::reset().
append_copy() [2/4]
xml_attribute pugi::xml_node::append_copy (const xml_attribute & proto)
append_copy() [3/4]
PUGI__FN xml_node pugi::xml_node::append_copy (const xml_node & proto)
Definition at line 5118 of file pugixml.cpp.
References append_child(), recursive_copy_skip(), and type().
append_copy() [4/4]
xml_node pugi::xml_node::append_copy (const xml_node & proto)
attribute() [1/2]
xml_attribute pugi::xml_node::attribute (const char_t * name) const
attribute() [2/2]
PUGI__FN xml_attribute pugi::xml_node::attribute (const char_t * name) const
Definition at line 4691 of file pugixml.cpp.
References _root, pugi::xml_node_struct::first_attribute, pugi::xml_attribute_struct::next_attribute, and strequal().
Referenced by remove_attribute().
attributes() [1/2]
PUGI__FN xml_object_range< xml_attribute_iterator > pugi::xml_node::attributes () const
Definition at line 4624 of file pugixml.cpp.
References attributes_begin(), and attributes_end().
attributes() [2/2]
xml_object_range<xml_attribute_iterator> pugi::xml_node::attributes () const
attributes_begin() [1/2]
attribute_iterator pugi::xml_node::attributes_begin () const
attributes_begin() [2/2]
PUGI__FN xml_node::attribute_iterator pugi::xml_node::attributes_begin () const
Definition at line 4603 of file pugixml.cpp.
References _root, and pugi::xml_node_struct::first_attribute.
Referenced by attributes().
attributes_end() [1/2]
PUGI__FN xml_node::attribute_iterator pugi::xml_node::attributes_end () const
Definition at line 4608 of file pugixml.cpp.
References _root.
Referenced by attributes().
attributes_end() [2/2]
attribute_iterator pugi::xml_node::attributes_end () const
begin() [1/2]
PUGI__FN xml_node::iterator pugi::xml_node::begin () const
Definition at line 4593 of file pugixml.cpp.
References _root, and pugi::xml_node_struct::first_child.
Referenced by children().
begin() [2/2]
iterator pugi::xml_node::begin () const
child() [1/2]
PUGI__FN xml_node pugi::xml_node::child (const char_t * name) const
Definition at line 4679 of file pugixml.cpp.
References _root, pugi::xml_node_struct::first_child, pugi::xml_node_struct::next_sibling, strequal(), and xml_node().
Referenced by child_value(), children(), and remove_child().
child() [2/2]
xml_node pugi::xml_node::child (const char_t * name) const
child_value() [1/4]
const char_t* pugi::xml_node::child_value () const
child_value() [2/4]
const PUGI__FN char_t * pugi::xml_node::child_value () const
Definition at line 4770 of file pugixml.cpp.
References _root, pugi::xml_node_struct::first_child, is_text_node(), pugi::xml_node_struct::next_sibling, and PUGIXML_TEXT.
Referenced by child_value().
child_value() [3/4]
const PUGI__FN char_t * pugi::xml_node::child_value (const char_t * name) const
Definition at line 4782 of file pugixml.cpp.
References child(), and child_value().
child_value() [4/4]
const char_t* pugi::xml_node::child_value (const char_t * name) const
children() [1/4]
PUGI__FN xml_object_range< xml_node_iterator > pugi::xml_node::children () const
Definition at line 4613 of file pugixml.cpp.
References begin(), and end().
children() [2/4]
xml_object_range<xml_node_iterator> pugi::xml_node::children () const
children() [3/4]
PUGI__FN xml_object_range< xml_named_node_iterator > pugi::xml_node::children (const char_t * name) const
Definition at line 4618 of file pugixml.cpp.
References _root, child(), and xml_named_node_iterator.
children() [4/4]
xml_object_range<xml_named_node_iterator> pugi::xml_node::children (const char_t * name) const
empty() [1/2]
PUGI__FN bool pugi::xml_node::empty () const
Definition at line 4659 of file pugixml.cpp.
References _root.
Referenced by traverse().
empty() [2/2]
bool pugi::xml_node::empty () const
end() [1/2]
PUGI__FN xml_node::iterator pugi::xml_node::end () const
Definition at line 4598 of file pugixml.cpp.
References _root.
Referenced by children().
end() [2/2]
iterator pugi::xml_node::end () const
find_attribute() [1/2]
template<typename Predicate > xml_attribute pugi::xml_node::find_attribute (Predicate pred) const inline
Definition at line 522 of file pugixml.hpp.
References pugi::xml_attribute::next_attribute().
find_attribute() [2/2]
template<typename Predicate > xml_attribute pugi::xml_node::find_attribute (Predicate pred) const inline
Definition at line 522 of file pugixml.hpp.
References pugi::xml_attribute::next_attribute().
find_child() [1/2]
template<typename Predicate > xml_node pugi::xml_node::find_child (Predicate pred) const inline
Definition at line 534 of file pugixml.hpp.
References next_sibling().
find_child() [2/2]
template<typename Predicate > xml_node pugi::xml_node::find_child (Predicate pred) const inline
Definition at line 534 of file pugixml.hpp.
References next_sibling().
find_child_by_attribute() [1/4]
xml_node pugi::xml_node::find_child_by_attribute (const char_t * attr_name, const char_t * attr_value) const
find_child_by_attribute() [2/4]
PUGI__FN xml_node pugi::xml_node::find_child_by_attribute (const char_t * attr_name, const char_t * attr_value) const
Definition at line 5276 of file pugixml.cpp.
References _root, pugi::xml_node_struct::first_child, pugi::xml_attribute_struct::next_attribute, pugi::xml_node_struct::next_sibling, PUGIXML_TEXT, strequal(), and xml_node().
find_child_by_attribute() [3/4]
xml_node pugi::xml_node::find_child_by_attribute (const char_t * name, const char_t * attr_name, const char_t * attr_value) const
find_child_by_attribute() [4/4]
PUGI__FN xml_node pugi::xml_node::find_child_by_attribute (const char_t * name, const char_t * attr_name, const char_t * attr_value) const
Definition at line 5258 of file pugixml.cpp.
References _root, pugi::xml_node_struct::first_child, pugi::xml_attribute_struct::next_attribute, pugi::xml_node_struct::next_sibling, PUGIXML_TEXT, strequal(), and xml_node().
find_node() [1/2]
template<typename Predicate > xml_node pugi::xml_node::find_node (Predicate pred) const inline
Definition at line 546 of file pugixml.hpp.
References _root, first_child(), next_sibling(), and parent().
find_node() [2/2]
template<typename Predicate > xml_node pugi::xml_node::find_node (Predicate pred) const inline
Definition at line 546 of file pugixml.hpp.
References _root, first_child(), next_sibling(), and parent().
first_attribute() [1/2]
xml_attribute pugi::xml_node::first_attribute () const
first_attribute() [2/2]
PUGI__FN xml_attribute pugi::xml_node::first_attribute () const
Definition at line 4787 of file pugixml.cpp.
References _root, and pugi::xml_node_struct::first_attribute.
Referenced by etiss::fault::xml::getAttribute().
first_child() [1/2]
xml_node pugi::xml_node::first_child () const
first_child() [2/2]
PUGI__FN xml_node pugi::xml_node::first_child () const
Definition at line 4797 of file pugixml.cpp.
References _root, pugi::xml_node_struct::first_child, and xml_node().
Referenced by find_node(), etiss::fault::xml::parse< std::vector< etiss::fault::Fault > >(), pugi::xml_document::reset(), and traverse().
first_element_by_path() [1/2]
xml_node pugi::xml_node::first_element_by_path (const char_t * path, char_t delimiter = '/') const
first_element_by_path() [2/2]
PUGI__FN xml_node pugi::xml_node::first_element_by_path (const char_t * path, char_t delimiter = '/') const
Definition at line 5311 of file pugixml.cpp.
References _root, pugi::xml_node_struct::first_child, first_element_by_path(), pugi::xml_node_struct::next_sibling, parent(), root(), strequalrange(), and xml_node().
Referenced by first_element_by_path().
hash_value() [1/2]
PUGI__FN size_t pugi::xml_node::hash_value () const
Definition at line 5413 of file pugixml.cpp.
References _root.
hash_value() [2/2]
size_t pugi::xml_node::hash_value () const
insert_attribute_after() [1/2]
PUGI__FN xml_attribute pugi::xml_node::insert_attribute_after (const char_t * name, const xml_attribute & attr)
Definition at line 4907 of file pugixml.cpp.
References pugi::xml_attribute::_attr, _root, allocate_attribute(), pugi::xml_attribute::empty(), pugi::xml_node_struct::first_attribute, get_allocator(), pugi::xml_attribute_struct::next_attribute, pugi::node_declaration, pugi::node_element, pugi::xml_attribute_struct::prev_attribute_c, pugi::xml_attribute::set_name(), and type().
Referenced by insert_copy_after().
insert_attribute_after() [2/2]
xml_attribute pugi::xml_node::insert_attribute_after (const char_t * name, const xml_attribute & attr)
insert_attribute_before() [1/2]
PUGI__FN xml_attribute pugi::xml_node::insert_attribute_before (const char_t * name, const xml_attribute & attr)
Definition at line 4875 of file pugixml.cpp.
References pugi::xml_attribute::_attr, _root, allocate_attribute(), pugi::xml_attribute::empty(), pugi::xml_node_struct::first_attribute, get_allocator(), pugi::xml_attribute_struct::next_attribute, pugi::node_declaration, pugi::node_element, pugi::xml_attribute_struct::prev_attribute_c, pugi::xml_attribute::set_name(), and type().
Referenced by insert_copy_before().
insert_attribute_before() [2/2]
xml_attribute pugi::xml_node::insert_attribute_before (const char_t * name, const xml_attribute & attr)
insert_child_after() [1/4]
PUGI__FN xml_node pugi::xml_node::insert_child_after (const char_t * name, const xml_node & node)
Definition at line 5100 of file pugixml.cpp.
References insert_child_after(), pugi::node_element, and set_name().
insert_child_after() [2/4]
xml_node pugi::xml_node::insert_child_after (const char_t * name, const xml_node & node)
insert_child_after() [3/4]
PUGI__FN xml_node pugi::xml_node::insert_child_after (xml_node_type type, const xml_node & node)
Definition at line 5054 of file pugixml.cpp.
References _root, allocate_node(), allow_insert_child(), pugi::xml_node_struct::first_child, get_allocator(), pugi::xml_node_struct::next_sibling, pugi::node_declaration, pugi::xml_node_struct::parent, pugi::xml_node_struct::prev_sibling_c, PUGIXML_TEXT, set_name(), type(), and xml_node().
Referenced by insert_child_after(), and insert_copy_after().
insert_child_after() [4/4]
xml_node pugi::xml_node::insert_child_after (xml_node_type type, const xml_node & node)
insert_child_before() [1/4]
PUGI__FN xml_node pugi::xml_node::insert_child_before (const char_t * name, const xml_node & node)
Definition at line 5109 of file pugixml.cpp.
References insert_child_before(), pugi::node_element, and set_name().
insert_child_before() [2/4]
xml_node pugi::xml_node::insert_child_before (const char_t * name, const xml_node & node)
insert_child_before() [3/4]
PUGI__FN xml_node pugi::xml_node::insert_child_before (xml_node_type type, const xml_node & node)
Definition at line 5026 of file pugixml.cpp.
References _root, allocate_node(), allow_insert_child(), pugi::xml_node_struct::first_child, get_allocator(), pugi::xml_node_struct::next_sibling, pugi::node_declaration, pugi::xml_node_struct::parent, pugi::xml_node_struct::prev_sibling_c, PUGIXML_TEXT, set_name(), type(), and xml_node().
Referenced by insert_child_before(), and insert_copy_before().
insert_child_before() [4/4]
xml_node pugi::xml_node::insert_child_before (xml_node_type type, const xml_node & node)
insert_copy_after() [1/4]
PUGI__FN xml_attribute pugi::xml_node::insert_copy_after (const xml_attribute & proto, const xml_attribute & attr)
Definition at line 4961 of file pugixml.cpp.
References insert_attribute_after(), pugi::xml_attribute::name(), pugi::xml_attribute::set_value(), and pugi::xml_attribute::value().
insert_copy_after() [2/4]
xml_attribute pugi::xml_node::insert_copy_after (const xml_attribute & proto, const xml_attribute & attr)
insert_copy_after() [3/4]
PUGI__FN xml_node pugi::xml_node::insert_copy_after (const xml_node & proto, const xml_node & node)
Definition at line 5138 of file pugixml.cpp.
References insert_child_after(), recursive_copy_skip(), and type().
insert_copy_after() [4/4]
xml_node pugi::xml_node::insert_copy_after (const xml_node & proto, const xml_node & node)
insert_copy_before() [1/4]
PUGI__FN xml_attribute pugi::xml_node::insert_copy_before (const xml_attribute & proto, const xml_attribute & attr)
Definition at line 4972 of file pugixml.cpp.
References insert_attribute_before(), pugi::xml_attribute::name(), pugi::xml_attribute::set_value(), and pugi::xml_attribute::value().
insert_copy_before() [2/4]
xml_attribute pugi::xml_node::insert_copy_before (const xml_attribute & proto, const xml_attribute & attr)
insert_copy_before() [3/4]
xml_node pugi::xml_node::insert_copy_before (const xml_node & proto, const xml_node & node)
insert_copy_before() [4/4]
PUGI__FN xml_node pugi::xml_node::insert_copy_before (const xml_node & proto, const xml_node & node)
Definition at line 5148 of file pugixml.cpp.
References insert_child_before(), recursive_copy_skip(), and type().
internal_object() [1/2]
PUGI__FN xml_node_struct * pugi::xml_node::internal_object () const
Definition at line 5418 of file pugixml.cpp.
References _root.
internal_object() [2/2]
xml_node_struct* pugi::xml_node::internal_object () const
last_attribute() [1/2]
PUGI__FN xml_attribute pugi::xml_node::last_attribute () const
Definition at line 4792 of file pugixml.cpp.
References _root, pugi::xml_node_struct::first_attribute, and pugi::xml_attribute_struct::prev_attribute_c.
Referenced by pugi::xml_attribute_iterator::operator--().
last_attribute() [2/2]
xml_attribute pugi::xml_node::last_attribute () const
last_child() [1/2]
PUGI__FN xml_node pugi::xml_node::last_child () const
Definition at line 4802 of file pugixml.cpp.
References _root, pugi::xml_node_struct::first_child, pugi::xml_node_struct::prev_sibling_c, and xml_node().
Referenced by pugi::xml_node_iterator::operator--(), and pugi::xml_named_node_iterator::operator--().
last_child() [2/2]
xml_node pugi::xml_node::last_child () const
name() [1/2]
const PUGI__FN char_t * pugi::xml_node::name () const
Definition at line 4664 of file pugixml.cpp.
References _root, pugi::xml_node_struct::name, and PUGIXML_TEXT.
Referenced by pugi::xml_named_node_iterator::operator--(), and path().
name() [2/2]
const char_t* pugi::xml_node::name () const
next_sibling() [1/4]
PUGI__FN xml_node pugi::xml_node::next_sibling () const
Definition at line 4715 of file pugixml.cpp.
References _root, pugi::xml_node_struct::next_sibling, and xml_node().
Referenced by find_child(), find_node(), pugi::xml_named_node_iterator::operator++(), etiss::fault::xml::parse< std::vector< etiss::fault::Fault > >(), pugi::xml_document::reset(), and traverse().
next_sibling() [2/4]
xml_node pugi::xml_node::next_sibling () const
next_sibling() [3/4]
xml_node pugi::xml_node::next_sibling (const char_t * name) const
next_sibling() [4/4]
PUGI__FN xml_node pugi::xml_node::next_sibling (const char_t * name) const
Definition at line 4703 of file pugixml.cpp.
References _root, pugi::xml_node_struct::next_sibling, strequal(), and xml_node().
offset_debug() [1/2]
PUGI__FN ptrdiff_t pugi::xml_node::offset_debug () const
Definition at line 5452 of file pugixml.cpp.
References _root, pugi::xml_node_struct::header, pugi::xml_node_struct::name, pugi::node_cdata, pugi::node_comment, pugi::node_declaration, pugi::node_doctype, pugi::node_document, pugi::node_element, pugi::node_pcdata, pugi::node_pi, root(), type(), pugi::xml_node_struct::value, xml_memory_page_name_allocated_mask, and xml_memory_page_value_allocated_mask.
offset_debug() [2/2]
ptrdiff_t pugi::xml_node::offset_debug () const
operator unspecified_bool_type() [1/2]
pugi::xml_node::operator unspecified_bool_type () const
operator unspecified_bool_type() [2/2]
PUGI__FN pugi::xml_node::operator xml_node::unspecified_bool_type () const
Definition at line 4583 of file pugixml.cpp.
References _root, and pugi::unspecified_bool_xml_node().
operator!() [1/2]
PUGI__FN bool pugi::xml_node::operator! () const
Definition at line 4588 of file pugixml.cpp.
References _root.
operator!() [2/2]
bool pugi::xml_node::operator! () const
operator!=() [1/2]
PUGI__FN bool pugi::xml_node::operator!= (const xml_node & r) const
Definition at line 4634 of file pugixml.cpp.
References _root.
operator!=() [2/2]
bool pugi::xml_node::operator!= (const xml_node & r) const
operator<() [1/2]
bool pugi::xml_node::operator< (const xml_node & r) const
operator<() [2/2]
PUGI__FN bool pugi::xml_node::operator< (const xml_node & r) const
Definition at line 4639 of file pugixml.cpp.
References _root.
operator<=() [1/2]
bool pugi::xml_node::operator<= (const xml_node & r) const
operator<=() [2/2]
PUGI__FN bool pugi::xml_node::operator<= (const xml_node & r) const
Definition at line 4649 of file pugixml.cpp.
References _root.
operator==() [1/2]
bool pugi::xml_node::operator== (const xml_node & r) const
operator==() [2/2]
PUGI__FN bool pugi::xml_node::operator== (const xml_node & r) const
Definition at line 4629 of file pugixml.cpp.
References _root.
operator>() [1/2]
bool pugi::xml_node::operator> (const xml_node & r) const
operator>() [2/2]
PUGI__FN bool pugi::xml_node::operator> (const xml_node & r) const
Definition at line 4644 of file pugixml.cpp.
References _root.
operator>=() [1/2]
PUGI__FN bool pugi::xml_node::operator>= (const xml_node & r) const
Definition at line 4654 of file pugixml.cpp.
References _root.
operator>=() [2/2]
bool pugi::xml_node::operator>= (const xml_node & r) const
parent() [1/2]
PUGI__FN xml_node pugi::xml_node::parent () const
Definition at line 4749 of file pugixml.cpp.
References _root, pugi::xml_node_struct::parent, and xml_node().
Referenced by find_node(), first_element_by_path(), pugi::xpath_node::parent(), path(), and traverse().
parent() [2/2]
xml_node pugi::xml_node::parent () const
path() [1/2]
string_t pugi::xml_node::path (char_t delimiter = '/') const
path() [2/2]
PUGI__FN string_t pugi::xml_node::path (char_t delimiter = '/') const
Definition at line 5291 of file pugixml.cpp.
References name(), and parent().
prepend_attribute() [1/2]
xml_attribute pugi::xml_node::prepend_attribute (const char_t * name)
prepend_attribute() [2/2]
PUGI__FN xml_attribute pugi::xml_node::prepend_attribute (const char_t * name)
Definition at line 4848 of file pugixml.cpp.
References pugi::xml_attribute::_attr, _root, allocate_attribute(), pugi::xml_node_struct::first_attribute, get_allocator(), pugi::xml_attribute_struct::next_attribute, pugi::node_declaration, pugi::node_element, pugi::xml_attribute_struct::prev_attribute_c, pugi::xml_attribute::set_name(), and type().
Referenced by prepend_copy().
prepend_child() [1/4]
PUGI__FN xml_node pugi::xml_node::prepend_child (const char_t * name)
Definition at line 5091 of file pugixml.cpp.
References pugi::node_element, prepend_child(), and set_name().
prepend_child() [2/4]
xml_node pugi::xml_node::prepend_child (const char_t * name)
prepend_child() [3/4]
PUGI__FN xml_node pugi::xml_node::prepend_child (xml_node_type type = node_element)
Definition at line 4996 of file pugixml.cpp.
References _root, allocate_node(), allow_insert_child(), pugi::xml_node_struct::first_child, get_allocator(), pugi::xml_node_struct::next_sibling, pugi::node_declaration, pugi::xml_node_struct::parent, pugi::xml_node_struct::prev_sibling_c, PUGIXML_TEXT, set_name(), type(), and xml_node().
Referenced by prepend_child(), and prepend_copy().
prepend_child() [4/4]
xml_node pugi::xml_node::prepend_child (xml_node_type type = node_element)
prepend_copy() [1/4]
PUGI__FN xml_attribute pugi::xml_node::prepend_copy (const xml_attribute & proto)
Definition at line 4950 of file pugixml.cpp.
References pugi::xml_attribute::name(), prepend_attribute(), pugi::xml_attribute::set_value(), and pugi::xml_attribute::value().
prepend_copy() [2/4]
xml_attribute pugi::xml_node::prepend_copy (const xml_attribute & proto)
prepend_copy() [3/4]
xml_node pugi::xml_node::prepend_copy (const xml_node & proto)
prepend_copy() [4/4]
PUGI__FN xml_node pugi::xml_node::prepend_copy (const xml_node & proto)
Definition at line 5128 of file pugixml.cpp.
References prepend_child(), recursive_copy_skip(), and type().
previous_sibling() [1/4]
PUGI__FN xml_node pugi::xml_node::previous_sibling () const
Definition at line 4738 of file pugixml.cpp.
References _root, pugi::xml_node_struct::next_sibling, pugi::xml_node_struct::prev_sibling_c, and xml_node().
Referenced by pugi::xml_node_iterator::operator--(), and pugi::xml_named_node_iterator::operator--().
previous_sibling() [2/4]
xml_node pugi::xml_node::previous_sibling () const
previous_sibling() [3/4]
PUGI__FN xml_node pugi::xml_node::previous_sibling (const char_t * name) const
Definition at line 4726 of file pugixml.cpp.
References _root, pugi::xml_node_struct::next_sibling, pugi::xml_node_struct::prev_sibling_c, strequal(), and xml_node().
previous_sibling() [4/4]
xml_node pugi::xml_node::previous_sibling (const char_t * name) const
print() [1/6]
void pugi::xml_node::print (std::basic_ostream< char, std::char_traits< char > > & os, const char_t * indent = PUGIXML_TEXT("\t"), unsigned int flags = format_default, xml_encoding encoding = encoding_auto, unsigned int depth = 0) const
print() [2/6]
void pugi::xml_node::print (std::basic_ostream< char, std::char_traits< char > > & os, const char_t * indent = PUGIXML_TEXT("\t"), unsigned int flags = format_default, xml_encoding encoding = encoding_auto, unsigned int depth = 0) const
print() [3/6]
void pugi::xml_node::print (std::basic_ostream< wchar_t, std::char_traits< wchar_t > > & os, const char_t * indent = PUGIXML_TEXT("\t"), unsigned int flags = format_default, unsigned int depth = 0) const
print() [4/6]
void pugi::xml_node::print (std::basic_ostream< wchar_t, std::char_traits< wchar_t > > & os, const char_t * indent = PUGIXML_TEXT("\t"), unsigned int flags = format_default, unsigned int depth = 0) const
print() [5/6]
PUGI__FN void pugi::xml_node::print (xml_writer & writer, const char_t * indent = PUGIXML_TEXT("\t"), unsigned int flags = format_default, xml_encoding encoding = encoding_auto, unsigned int depth = 0) const
Definition at line 5423 of file pugixml.cpp.
References _root, etiss::interfaces::depth(), and node_output().
print() [6/6]
void pugi::xml_node::print (xml_writer & writer, const char_t * indent = PUGIXML_TEXT("\t"), unsigned int flags = format_default, xml_encoding encoding = encoding_auto, unsigned int depth = 0) const
remove_attribute() [1/4]
bool pugi::xml_node::remove_attribute (const char_t * name)
remove_attribute() [2/4]
PUGI__FN bool pugi::xml_node::remove_attribute (const char_t * name)
Definition at line 5158 of file pugixml.cpp.
References attribute(), and remove_attribute().
remove_attribute() [3/4]
bool pugi::xml_node::remove_attribute (const xml_attribute & a)
remove_attribute() [4/4]
PUGI__FN bool pugi::xml_node::remove_attribute (const xml_attribute & a)
Definition at line 5163 of file pugixml.cpp.
References pugi::xml_attribute::_attr, _root, destroy_attribute(), pugi::xml_node_struct::first_attribute, get_allocator(), pugi::xml_attribute_struct::next_attribute, and pugi::xml_attribute_struct::prev_attribute_c.
Referenced by remove_attribute().
remove_child() [1/4]
PUGI__FN bool pugi::xml_node::remove_child (const char_t * name)
Definition at line 5192 of file pugixml.cpp.
References child(), and remove_child().
remove_child() [2/4]
bool pugi::xml_node::remove_child (const char_t * name)
remove_child() [3/4]
bool pugi::xml_node::remove_child (const xml_node & n)
remove_child() [4/4]
PUGI__FN bool pugi::xml_node::remove_child (const xml_node & n)
Definition at line 5197 of file pugixml.cpp.
References _root, destroy_node(), pugi::xml_node_struct::first_child, get_allocator(), pugi::xml_node_struct::next_sibling, pugi::xml_node_struct::parent, and pugi::xml_node_struct::prev_sibling_c.
Referenced by remove_child().
root() [1/2]
xml_node pugi::xml_node::root () const
root() [2/2]
PUGI__FN xml_node pugi::xml_node::root () const
Definition at line 4754 of file pugixml.cpp.
References _root, pugi::xml_node_struct::header, xml_memory_page_pointer_mask, and xml_node().
Referenced by append_buffer(), first_element_by_path(), and offset_debug().
select_nodes() [1/4]
PUGI__FN xpath_node_set pugi::xml_node::select_nodes (const char_t * query, xpath_variable_set * variables = 0) const
Definition at line 11156 of file pugixml.cpp.
select_nodes() [2/4]
xpath_node_set pugi::xml_node::select_nodes (const char_t * query, xpath_variable_set * variables = 0) const
select_nodes() [3/4]
xpath_node_set pugi::xml_node::select_nodes (const xpath_query & query) const
select_nodes() [4/4]
PUGI__FN xpath_node_set pugi::xml_node::select_nodes (const xpath_query & query) const
Definition at line 11162 of file pugixml.cpp.
References pugi::xpath_query::evaluate_node_set().
select_single_node() [1/4]
PUGI__FN xpath_node pugi::xml_node::select_single_node (const char_t * query, xpath_variable_set * variables = 0) const
Definition at line 11144 of file pugixml.cpp.
select_single_node() [2/4]
xpath_node pugi::xml_node::select_single_node (const char_t * query, xpath_variable_set * variables = 0) const
select_single_node() [3/4]
PUGI__FN xpath_node pugi::xml_node::select_single_node (const xpath_query & query) const
Definition at line 11150 of file pugixml.cpp.
References pugi::xpath_query::evaluate_node_set(), and s.
select_single_node() [4/4]
xpath_node pugi::xml_node::select_single_node (const xpath_query & query) const
set_name() [1/2]
bool pugi::xml_node::set_name (const char_t * rhs)
set_name() [2/2]
PUGI__FN bool pugi::xml_node::set_name (const char_t * rhs)
Definition at line 4807 of file pugixml.cpp.
References _root, pugi::xml_node_struct::header, pugi::xml_node_struct::name, pugi::node_declaration, pugi::node_element, pugi::node_pi, strcpy_insitu(), type(), and xml_memory_page_name_allocated_mask.
Referenced by append_child(), insert_child_after(), insert_child_before(), and prepend_child().
set_value() [1/2]
bool pugi::xml_node::set_value (const char_t * rhs)
set_value() [2/2]
PUGI__FN bool pugi::xml_node::set_value (const char_t * rhs)
Definition at line 4821 of file pugixml.cpp.
References _root, pugi::xml_node_struct::header, pugi::node_cdata, pugi::node_comment, pugi::node_doctype, pugi::node_pcdata, pugi::node_pi, strcpy_insitu(), type(), pugi::xml_node_struct::value, and xml_memory_page_value_allocated_mask.
text() [1/2]
PUGI__FN xml_text pugi::xml_node::text () const
Definition at line 4765 of file pugixml.cpp.
References _root.
text() [2/2]
xml_text pugi::xml_node::text () const
traverse() [1/2]
PUGI__FN bool pugi::xml_node::traverse (xml_tree_walker & walker)
Definition at line 5365 of file pugixml.cpp.
References pugi::xml_tree_walker::_depth, pugi::xml_tree_walker::begin(), empty(), pugi::xml_tree_walker::end(), first_child(), pugi::xml_tree_walker::for_each(), next_sibling(), and parent().
traverse() [2/2]
bool pugi::xml_node::traverse (xml_tree_walker & walker)
type() [1/2]
xml_node_type pugi::xml_node::type () const
type() [2/2]
PUGI__FN xml_node_type pugi::xml_node::type () const
Definition at line 4669 of file pugixml.cpp.
References _root, pugi::xml_node_struct::header, pugi::node_null, and xml_memory_page_type_mask.
Referenced by append_attribute(), append_buffer(), append_child(), append_copy(), insert_attribute_after(), insert_attribute_before(), insert_child_after(), insert_child_before(), insert_copy_after(), insert_copy_before(), offset_debug(), prepend_attribute(), prepend_child(), prepend_copy(), set_name(), and set_value().
value() [1/2]
const char_t* pugi::xml_node::value () const
value() [2/2]
const PUGI__FN char_t * pugi::xml_node::value () const
Definition at line 4674 of file pugixml.cpp.
References _root, PUGIXML_TEXT, and pugi::xml_node_struct::value.
Friends And Related Function Documentation
xml_attribute_iterator
xml_attribute_iterator friend
Definition at line 398 of file pugixml.hpp.
xml_named_node_iterator
xml_named_node_iterator friend
Definition at line 400 of file pugixml.hpp.
Referenced by children().
xml_node_iterator
xml_node_iterator friend
Definition at line 399 of file pugixml.hpp.
Member Data Documentation
_root
xml_node_struct * pugi::xml_node::_root protected
Definition at line 403 of file pugixml.hpp.
Referenced by append_attribute(), append_buffer(), append_child(), attribute(), attributes_begin(), attributes_end(), begin(), child(), child_value(), children(), pugi::xml_document::create(), pugi::xml_document::destroy(), pugi::xml_document::document_element(), empty(), end(), find_child_by_attribute(), find_node(), first_attribute(), first_child(), first_element_by_path(), hash_value(), insert_attribute_after(), insert_attribute_before(), insert_child_after(), insert_child_before(), internal_object(), last_attribute(), last_child(), pugi::xml_document::load_buffer(), pugi::xml_document::load_buffer_inplace(), pugi::xml_document::load_buffer_inplace_own(), name(), next_sibling(), offset_debug(), operator unspecified_bool_type(), operator!(), operator!=(), pugi::xml_node_iterator::operator!=(), pugi::xml_attribute_iterator::operator!=(), pugi::xml_named_node_iterator::operator!=(), pugi::xml_node_iterator::operator*(), pugi::xml_named_node_iterator::operator*(), pugi::xml_node_iterator::operator++(), pugi::xml_named_node_iterator::operator++(), pugi::xml_node_iterator::operator--(), pugi::xml_named_node_iterator::operator--(), pugi::xml_node_iterator::operator->(), pugi::xml_named_node_iterator::operator->(), operator<(), operator<=(), operator==(), pugi::xml_node_iterator::operator==(), pugi::xml_attribute_iterator::operator==(), pugi::xml_named_node_iterator::operator==(), operator>(), operator>=(), parent(), prepend_attribute(), prepend_child(), previous_sibling(), print(), remove_attribute(), remove_child(), root(), set_name(), set_value(), text(), type(), and value().
The documentation for this class was generated from the following files:
include/etiss/fault/xml/pugixml.hpp
/home/runner/work/etiss/etiss/src/fault/xml/pugixml.cpp