ETISS 0.8.0: OR1KTimer Class Reference
OR1KTimer Class Reference
#include <OR1KTimer.h>
Public Member Functions
OR1KTimer ()
virtual ~OR1KTimer ()
virtual etiss::int32 execute ()
called before a block and may act in the same way as a block
virtual void changedRegister (const char *name)
called when an observable register has been changed
Public Member Functions inherited from etiss::CoroutinePlugin
CoroutinePlugin ()
virtual ~CoroutinePlugin ()
virtual void executionEnd (int32_t code)
called when the simulation ends but before any deinitialization is done
virtual bool isActive ()
indicates if the plugin will do something in execution loop.
CoroutinePlugin ()
virtual ~CoroutinePlugin ()
virtual void executionEnd (int32_t code)
called when the simulation ends but before any deinitialization is done
virtual bool isActive ()
indicates if the plugin will do something in execution loop.
Public Member Functions inherited from etiss::Plugin
virtual ~Plugin ()
unsigned getType ()
InterruptListenerPlugin * getInterruptListenerPlugin ()
CoroutinePlugin * getCoroutinePlugin ()
SystemWrapperPlugin * getSystemWrapperPlugin ()
RegisterDevicePlugin * getRegisterDevicePlugin ()
TranslationPlugin * getTranslationPlugin ()
std::string getPluginName () const
const std::string & getLastAssignedCoreName ()
std::string toString () const
virtual ~Plugin ()
unsigned getType ()
InterruptListenerPlugin * getInterruptListenerPlugin ()
CoroutinePlugin * getCoroutinePlugin ()
SystemWrapperPlugin * getSystemWrapperPlugin ()
RegisterDevicePlugin * getRegisterDevicePlugin ()
TranslationPlugin * getTranslationPlugin ()
std::string getPluginName () const
const std::string & getLastAssignedCoreName ()
std::string toString () const
Public Member Functions inherited from etiss::ToString
ToString ()
virtual ~ToString ()
ToString ()
virtual ~ToString ()
Public Member Functions inherited from etiss::RegisterDevicePlugin
RegisterDevicePlugin ()
virtual ~RegisterDevicePlugin ()
RegisterDevicePlugin ()
virtual ~RegisterDevicePlugin ()
Protected Member Functions
virtual std::string _getPluginName () const
Protected Member Functions inherited from etiss::Plugin
Plugin (unsigned type=0)
virtual void init (ETISS_CPU *cpu, ETISS_System *system, CPUArch *arch)
this function is called before the plugin is used in the cpu execution loop (etiss::CPUCore::execute).
virtual void cleanup ()
this function is called after cpu execution loop (etiss::CPUCore::execute) finished.
void setCorrespondingCPUCoreName (std::string name)
virtual void addedToCPUCore (etiss::CPUCore *core)
called as soon a plugin has been added to its CPUCore.
virtual void removedFromCPUCore (etiss::CPUCore *core)
called as soon a plugin has been removed from its CPUCore.
Plugin (unsigned type=0)
virtual void init (ETISS_CPU *cpu, ETISS_System *system, CPUArch *arch)
this function is called before the plugin is used in the cpu execution loop (etiss::CPUCore::execute).
virtual void cleanup ()
this function is called after cpu execution loop (etiss::CPUCore::execute) finished.
void setCorrespondingCPUCoreName (std::string name)
virtual void addedToCPUCore (etiss::CPUCore *core)
called as soon a plugin has been added to its CPUCore.
virtual void removedFromCPUCore (etiss::CPUCore *core)
called as soon a plugin has been removed from its CPUCore.
Private Types
enum Modes { TIMER_DISABLED, TIMER_AUTORESTART, TIMER_ONESHOT, TIMER_CONTINUOUS }
Private Member Functions
void regs_to_internal_state ()
bool internal_state_to_TTCR ()
bool internal_state_to_TTMR_IP ()
Modes getMode ()
etiss::uint32 getTTCR ()
etiss::uint32 getTTCR_28Bit ()
etiss::uint32 getTTMR_TP ()
bool getTTMR_IE ()
Private Attributes
int64_t last_time_0_ps_ = 0
int64_t next_timer_match_ps_ = 0
Additional Inherited Members
Static Public Attributes inherited from etiss::Plugin
static const unsigned INTERRUPTLISTENER = 1 << 0
access to translated code
static const unsigned COROUTINE = 1 << 1
callback after execution of each translated block
static const unsigned SYSTEMWRAPPER = 1 << 2
can wrap/change ETISS_System structure at execution start
static const unsigned REGISTERDEVICE
gets noticed of changes to special registers (e.g. mmu register etc. [depends on architecture])
static const unsigned TRANSLATION
access to translated code during translation phase or when instruction tree is built
Protected Attributes inherited from etiss::Plugin
ETISS_CPU * plugin_cpu_
holds a pointer to the cpu structure. will be set before init call and after cleanup call
ETISS_System * plugin_system_
holds a pointer to the system structure.
CPUArch * plugin_arch_
holds a pointer to the CPUArch instance. will be set before init call and after cleanup call
CPUCore * plugin_core_
holds a pointer to the associated CPUCore instance.
Detailed Description
Definition at line 47 of file OR1KTimer.h.
Member Enumeration Documentation
Modes
enum OR1KTimer::Modes private
Enumerator
TIMER_DISABLED
TIMER_AUTORESTART
TIMER_ONESHOT
TIMER_CONTINUOUS
Definition at line 59 of file OR1KTimer.h.
Constructor & Destructor Documentation
OR1KTimer()
OR1KTimer::OR1KTimer ()
Definition at line 45 of file OR1KTimer.cpp.
~OR1KTimer()
OR1KTimer::~OR1KTimer () virtual
Definition at line 47 of file OR1KTimer.cpp.
Member Function Documentation
_getPluginName()
std::string OR1KTimer::_getPluginName () const protected virtual
Implements etiss::Plugin.
Definition at line 100 of file OR1KTimer.cpp.
changedRegister()
void OR1KTimer::changedRegister (const char * name) virtual
called when an observable register has been changed
See also
etiss::CPUArchRegListenerInterface
Implements etiss::RegisterDevicePlugin.
Definition at line 84 of file OR1KTimer.cpp.
References name, and regs_to_internal_state().
execute()
etiss::int32 OR1KTimer::execute () virtual
called before a block and may act in the same way as a block
Implements etiss::CoroutinePlugin.
Definition at line 49 of file OR1KTimer.cpp.
References internal_state_to_TTCR(), internal_state_to_TTMR_IP(), etiss::mm::NOERROR, OR1K_TICKTIMEREXCEPTION, and regs_to_internal_state().
getMode()
Modes OR1KTimer::getMode () inline private
Definition at line 169 of file OR1KTimer.h.
getTTCR()
etiss::uint32 OR1KTimer::getTTCR () inline private
Definition at line 171 of file OR1KTimer.h.
getTTCR_28Bit()
etiss::uint32 OR1KTimer::getTTCR_28Bit () inline private
Definition at line 173 of file OR1KTimer.h.
getTTMR_IE()
bool OR1KTimer::getTTMR_IE () inline private
Definition at line 177 of file OR1KTimer.h.
References true.
getTTMR_TP()
etiss::uint32 OR1KTimer::getTTMR_TP () inline private
Definition at line 175 of file OR1KTimer.h.
internal_state_to_TTCR()
bool OR1KTimer::internal_state_to_TTCR () inline private
Definition at line 115 of file OR1KTimer.h.
Referenced by execute().
internal_state_to_TTMR_IP()
bool OR1KTimer::internal_state_to_TTMR_IP () inline private
Definition at line 150 of file OR1KTimer.h.
References if().
Referenced by execute().
regs_to_internal_state()
void OR1KTimer::regs_to_internal_state () inline private
Definition at line 92 of file OR1KTimer.h.
Referenced by changedRegister(), and execute().
Member Data Documentation
last_time_0_ps_
int64_t OR1KTimer::last_time_0_ps_ = 0 private
Definition at line 72 of file OR1KTimer.h.
next_timer_match_ps_
int64_t OR1KTimer::next_timer_match_ps_ = 0 private
Definition at line 79 of file OR1KTimer.h.
The documentation for this class was generated from the following files:
/home/runner/work/etiss/etiss/ArchImpl/OR1K/OR1KTimer.h
/home/runner/work/etiss/etiss/ArchImpl/OR1K/OR1KTimer.cpp