ETISS 0.8.0: etiss::error::Error Class Reference
etiss::error::Error Class Reference abstract
base error class for simple handling of errors
#include <ErrorDefinition.h>
Public Member Functions
Error (bool persistent, int id=-1, const std::string &name="")
virtual ~Error ()
virtual void apply (uint64_t &var)=0
virtual void apply (uint32_t &var)
virtual void apply (uint16_t &var)
virtual void apply (uint8_t &var)
virtual const std::vector< unsigned > affectedBits ()=0
Error (bool persistent, int id=-1, const std::string &name="")
virtual ~Error ()
virtual void apply (uint64_t &var)=0
virtual void apply (uint32_t &var)
virtual void apply (uint16_t &var)
virtual void apply (uint8_t &var)
virtual const std::vector< unsigned > affectedBits ()=0
Public Attributes
const bool persistent_
int id_
std::string name_
Detailed Description
base error class for simple handling of errors
Attention
any class is required to implement virtual void apply(uint64_t & var) AND provide a templated function template<typename T> fapply(T & var) that applies the error.
currently no variable largt than uint64_t can be used
Definition at line 76 of file ErrorDefinition.h.
Constructor & Destructor Documentation
Error() [1/2]
etiss::error::Error::Error (bool persistent, int id = -1, const std::string & name = "")
Parameters
id if id is negative the a new negative id from a global id pool will be used. the pool may assign the same id if the total number of error instances during progam execution exceds 2^(sizeof(int)*8-1)
Definition at line 79 of file ErrorDefinition.cpp.
~Error() [1/2]
etiss::error::Error::~Error () virtual
Definition at line 83 of file ErrorDefinition.cpp.
Error() [2/2]
etiss::error::Error::Error (bool persistent, int id = -1, const std::string & name = "")
Parameters
id if id is negative the a new negative id from a global id pool will be used. the pool may assign the same id if the total number of error instances during progam execution exceds 2^(sizeof(int)*8-1)
~Error() [2/2]
virtual etiss::error::Error::~Error () virtual
Member Function Documentation
affectedBits() [1/2]
virtual const std::vector<unsigned> etiss::error::Error::affectedBits () pure virtual
Implemented in etiss::error::StuckLow, etiss::error::StuckLow, etiss::error::StuckHigh, etiss::error::StuckHigh, etiss::error::BitFlip, and etiss::error::BitFlip.
affectedBits() [2/2]
virtual const std::vector<unsigned> etiss::error::Error::affectedBits () pure virtual
Implemented in etiss::error::StuckLow, etiss::error::StuckLow, etiss::error::StuckHigh, etiss::error::StuckHigh, etiss::error::BitFlip, and etiss::error::BitFlip.
apply() [1/8]
virtual void etiss::error::Error::apply (uint16_t & var) virtual
apply() [2/8]
void etiss::error::Error::apply (uint16_t & var) virtual
Definition at line 91 of file ErrorDefinition.cpp.
References apply().
apply() [3/8]
virtual void etiss::error::Error::apply (uint32_t & var) virtual
apply() [4/8]
void etiss::error::Error::apply (uint32_t & var) virtual
Definition at line 85 of file ErrorDefinition.cpp.
References apply().
apply() [5/8]
virtual void etiss::error::Error::apply (uint64_t & var) pure virtual
Implemented in etiss::error::StuckLow, etiss::error::StuckLow, etiss::error::StuckHigh, etiss::error::StuckHigh, etiss::error::BitFlip, and etiss::error::BitFlip.
Referenced by apply().
apply() [6/8]
virtual void etiss::error::Error::apply (uint64_t & var) pure virtual
Implemented in etiss::error::StuckLow, etiss::error::StuckLow, etiss::error::StuckHigh, etiss::error::StuckHigh, etiss::error::BitFlip, and etiss::error::BitFlip.
apply() [7/8]
void etiss::error::Error::apply (uint8_t & var) virtual
Definition at line 97 of file ErrorDefinition.cpp.
References apply().
apply() [8/8]
virtual void etiss::error::Error::apply (uint8_t & var) virtual
Member Data Documentation
id_
int etiss::error::Error::id_
Definition at line 80 of file ErrorDefinition.h.
name_
std::string etiss::error::Error::name_
Definition at line 81 of file ErrorDefinition.h.
persistent_
const bool etiss::error::Error::persistent_
Definition at line 79 of file ErrorDefinition.h.
The documentation for this class was generated from the following files:
include/etiss/ErrorDefinition.h
/home/runner/work/etiss/etiss/src/ErrorDefinition.cpp