ETISS 0.8.0: SI_ConvertA< SI_CHAR > Class Template Reference
SI_ConvertA< SI_CHAR > Class Template Reference
Null conversion class for MBCS/UTF-8 to char (or equivalent).
#include <SimpleIni.h>
Public Member Functions
SI_ConvertA (bool a_bStoreIsUtf8)
SI_ConvertA (const SI_ConvertA &rhs)
SI_ConvertA & operator= (const SI_ConvertA &rhs)
size_t SizeFromStore (const char *a_pInputData, size_t a_uInputDataLen)
Calculate the number of SI_CHAR required for converting the input from the storage format.
bool ConvertFromStore (const char *a_pInputData, size_t a_uInputDataLen, SI_CHAR *a_pOutputData, size_t a_uOutputDataSize)
Convert the input string from the storage format to SI_CHAR.
size_t SizeToStore (const SI_CHAR *a_pInputData)
Calculate the number of char required by the storage format of this data.
bool ConvertToStore (const SI_CHAR *a_pInputData, char *a_pOutputData, size_t a_uOutputDataSize)
Convert the input string to the storage format of this data.
SI_ConvertA (bool a_bStoreIsUtf8)
SI_ConvertA (const SI_ConvertA &rhs)
SI_ConvertA & operator= (const SI_ConvertA &rhs)
size_t SizeFromStore (const char *a_pInputData, size_t a_uInputDataLen)
Calculate the number of SI_CHAR required for converting the input from the storage format.
bool ConvertFromStore (const char *a_pInputData, size_t a_uInputDataLen, SI_CHAR *a_pOutputData, size_t a_uOutputDataSize)
Convert the input string from the storage format to SI_CHAR.
size_t SizeToStore (const SI_CHAR *a_pInputData)
Calculate the number of char required by the storage format of this data.
bool ConvertToStore (const SI_CHAR *a_pInputData, char *a_pOutputData, size_t a_uOutputDataSize)
Convert the input string to the storage format of this data.
Protected Member Functions
SI_ConvertA ()
SI_ConvertA ()
Private Attributes
bool m_bStoreIsUtf8
Detailed Description
template<class SI_CHAR>
class SI_ConvertA< SI_CHAR >
Null conversion class for MBCS/UTF-8 to char (or equivalent).
Definition at line 2656 of file SimpleIni.h.
Constructor & Destructor Documentation
SI_ConvertA() [1/6]
template<class SI_CHAR > SI_ConvertA< SI_CHAR >::SI_ConvertA () inline protected
Definition at line 2661 of file SimpleIni.h.
SI_ConvertA() [2/6]
template<class SI_CHAR > SI_ConvertA< SI_CHAR >::SI_ConvertA (bool a_bStoreIsUtf8) inline
Definition at line 2664 of file SimpleIni.h.
SI_ConvertA() [3/6]
template<class SI_CHAR > SI_ConvertA< SI_CHAR >::SI_ConvertA (const SI_ConvertA< SI_CHAR > & rhs) inline
Definition at line 2667 of file SimpleIni.h.
References SI_ConvertA< SI_CHAR >::operator=().
SI_ConvertA() [4/6]
template<class SI_CHAR > SI_ConvertA< SI_CHAR >::SI_ConvertA () inline protected
Definition at line 2661 of file SimpleIni.h.
SI_ConvertA() [5/6]
template<class SI_CHAR > SI_ConvertA< SI_CHAR >::SI_ConvertA (bool a_bStoreIsUtf8) inline
Definition at line 2664 of file SimpleIni.h.
SI_ConvertA() [6/6]
template<class SI_CHAR > SI_ConvertA< SI_CHAR >::SI_ConvertA (const SI_ConvertA< SI_CHAR > & rhs) inline
Definition at line 2667 of file SimpleIni.h.
References SI_ConvertA< SI_CHAR >::operator=().
Member Function Documentation
ConvertFromStore() [1/2]
template<class SI_CHAR > bool SI_ConvertA< SI_CHAR >::ConvertFromStore (const char * a_pInputData, size_t a_uInputDataLen, SI_CHAR * a_pOutputData, size_t a_uOutputDataSize) inline
Convert the input string from the storage format to SI_CHAR.
The storage format is always UTF-8 or MBCS.
Parameters
a_pInputData Data in storage format to be converted to SI_CHAR.
a_uInputDataLen Length of storage format data in bytes. This must be the actual length of the data, including NULL byte if NULL terminated string is required.
a_pOutputData Pointer to the output buffer to received the converted data.
a_uOutputDataSize Size of the output buffer in SI_CHAR.
Returns
true if all of the input data was successfully converted.
Definition at line 2709 of file SimpleIni.h.
References memcpy().
ConvertFromStore() [2/2]
template<class SI_CHAR > bool SI_ConvertA< SI_CHAR >::ConvertFromStore (const char * a_pInputData, size_t a_uInputDataLen, SI_CHAR * a_pOutputData, size_t a_uOutputDataSize) inline
Convert the input string from the storage format to SI_CHAR.
The storage format is always UTF-8 or MBCS.
Parameters
a_pInputData Data in storage format to be converted to SI_CHAR.
a_uInputDataLen Length of storage format data in bytes. This must be the actual length of the data, including NULL byte if NULL terminated string is required.
a_pOutputData Pointer to the output buffer to received the converted data.
a_uOutputDataSize Size of the output buffer in SI_CHAR.
Returns
true if all of the input data was successfully converted.
Definition at line 2709 of file SimpleIni.h.
References memcpy().
ConvertToStore() [1/2]
template<class SI_CHAR > bool SI_ConvertA< SI_CHAR >::ConvertToStore (const SI_CHAR * a_pInputData, char * a_pOutputData, size_t a_uOutputDataSize) inline
Convert the input string to the storage format of this data.
The storage format is always UTF-8 or MBCS.
Parameters
a_pInputData NULL terminated source string to convert. All of the data will be converted including the terminating NULL character.
a_pOutputData Pointer to the buffer to receive the converted string.
a_uOutputDataSize Size of the output buffer in char.
Returns
true if all of the input data, including the terminating NULL character was successfully converted.
Definition at line 2750 of file SimpleIni.h.
References memcpy().
ConvertToStore() [2/2]
template<class SI_CHAR > bool SI_ConvertA< SI_CHAR >::ConvertToStore (const SI_CHAR * a_pInputData, char * a_pOutputData, size_t a_uOutputDataSize) inline
Convert the input string to the storage format of this data.
The storage format is always UTF-8 or MBCS.
Parameters
a_pInputData NULL terminated source string to convert. All of the data will be converted including the terminating NULL character.
a_pOutputData Pointer to the buffer to receive the converted string.
a_uOutputDataSize Size of the output buffer in char.
Returns
true if all of the input data, including the terminating NULL character was successfully converted.
Definition at line 2750 of file SimpleIni.h.
References memcpy().
operator=() [1/2]
template<class SI_CHAR > SI_ConvertA& SI_ConvertA< SI_CHAR >::operator= (const SI_ConvertA< SI_CHAR > & rhs) inline
Definition at line 2668 of file SimpleIni.h.
References SI_ConvertA< SI_CHAR >::m_bStoreIsUtf8.
Referenced by SI_ConvertA< SI_CHAR >::SI_ConvertA().
operator=() [2/2]
template<class SI_CHAR > SI_ConvertA& SI_ConvertA< SI_CHAR >::operator= (const SI_ConvertA< SI_CHAR > & rhs) inline
Definition at line 2668 of file SimpleIni.h.
References SI_ConvertA< SI_CHAR >::m_bStoreIsUtf8.
SizeFromStore() [1/2]
template<class SI_CHAR > size_t SI_ConvertA< SI_CHAR >::SizeFromStore (const char * a_pInputData, size_t a_uInputDataLen) inline
Calculate the number of SI_CHAR required for converting the input from the storage format.
The storage format is always UTF-8 or MBCS.
Parameters
a_pInputData Data in storage format to be converted to SI_CHAR.
a_uInputDataLen Length of storage format data in bytes. This must be the actual length of the data, including NULL byte if NULL terminated string is required.
Returns
Number of SI_CHAR required by the string when converted. If there are embedded NULL bytes in the input data, only the string up and not including the NULL byte will be converted.
-1 cast to size_t on a conversion error.
Definition at line 2687 of file SimpleIni.h.
References SI_ASSERT.
SizeFromStore() [2/2]
template<class SI_CHAR > size_t SI_ConvertA< SI_CHAR >::SizeFromStore (const char * a_pInputData, size_t a_uInputDataLen) inline
Calculate the number of SI_CHAR required for converting the input from the storage format.
The storage format is always UTF-8 or MBCS.
Parameters
a_pInputData Data in storage format to be converted to SI_CHAR.
a_uInputDataLen Length of storage format data in bytes. This must be the actual length of the data, including NULL byte if NULL terminated string is required.
Returns
Number of SI_CHAR required by the string when converted. If there are embedded NULL bytes in the input data, only the string up and not including the NULL byte will be converted.
-1 cast to size_t on a conversion error.
Definition at line 2687 of file SimpleIni.h.
References SI_ASSERT.
SizeToStore() [1/2]
template<class SI_CHAR > size_t SI_ConvertA< SI_CHAR >::SizeToStore (const SI_CHAR * a_pInputData) inline
Calculate the number of char required by the storage format of this data.
The storage format is always UTF-8 or MBCS.
Parameters
a_pInputData NULL terminated string to calculate the number of bytes required to be converted to storage format.
Returns
Number of bytes required by the string when converted to storage format. This size always includes space for the terminating NULL character.
-1 cast to size_t on a conversion error.
Definition at line 2731 of file SimpleIni.h.
SizeToStore() [2/2]
template<class SI_CHAR > size_t SI_ConvertA< SI_CHAR >::SizeToStore (const SI_CHAR * a_pInputData) inline
Calculate the number of char required by the storage format of this data.
The storage format is always UTF-8 or MBCS.
Parameters
a_pInputData NULL terminated string to calculate the number of bytes required to be converted to storage format.
Returns
Number of bytes required by the string when converted to storage format. This size always includes space for the terminating NULL character.
-1 cast to size_t on a conversion error.
Definition at line 2731 of file SimpleIni.h.
Member Data Documentation
m_bStoreIsUtf8
template<class SI_CHAR > bool SI_ConvertA< SI_CHAR >::m_bStoreIsUtf8 private
Definition at line 2658 of file SimpleIni.h.
Referenced by SI_ConvertA< SI_CHAR >::operator=().
The documentation for this class was generated from the following file:
include/etiss/IntegratedLibrary/SimpleIni/SimpleIni.h