ETISS 0.8.0: etiss::InterruptVector Class Reference
etiss::InterruptVector Class Reference abstract
interface to set interrupt bits
#include <InterruptVector.h>
Public Member Functions
virtual ~InterruptVector ()
virtual void setBit (unsigned bit, bool state)=0
set the bit of an interrupt line to state (true = raised)
virtual bool getBit (unsigned bit) const =0
get the bit of an interrupt line
virtual unsigned width () const =0
number of interrupt bits
virtual bool isActive () const
virtual void clear ()
sets every bit to false
virtual ~InterruptVector ()
virtual void setBit (unsigned bit, bool state)=0
set the bit of an interrupt line to state (true = raised)
virtual bool getBit (unsigned bit) const =0
get the bit of an interrupt line
virtual unsigned width () const =0
number of interrupt bits
virtual bool isActive () const
virtual void clear ()
sets every bit to false
Public Attributes
bool consumed_by_interruptlistener_ { false }
Detailed Description
interface to set interrupt bits
Definition at line 69 of file InterruptVector.h.
Constructor & Destructor Documentation
~InterruptVector() [1/2]
InterruptVector::~InterruptVector () virtual
Definition at line 57 of file InterruptVector.cpp.
~InterruptVector() [2/2]
virtual etiss::InterruptVector::~InterruptVector () virtual
Member Function Documentation
clear() [1/2]
void InterruptVector::clear () virtual
sets every bit to false
Reimplemented in etiss::MappedInterruptVector< INT >, etiss::MappedInterruptVector< INT >, etiss::CPUCore::InterruptVectorWrapper, and etiss::CPUCore::InterruptVectorWrapper.
Definition at line 68 of file InterruptVector.cpp.
References setBit(), and width().
clear() [2/2]
virtual void etiss::InterruptVector::clear () virtual
sets every bit to false
Reimplemented in etiss::MappedInterruptVector< INT >, etiss::MappedInterruptVector< INT >, etiss::CPUCore::InterruptVectorWrapper, and etiss::CPUCore::InterruptVectorWrapper.
getBit() [1/2]
virtual bool etiss::InterruptVector::getBit (unsigned bit) const pure virtual
get the bit of an interrupt line
Implemented in etiss::CPUCore::InterruptVectorWrapper, etiss::CPUCore::InterruptVectorWrapper, etiss::MappedInterruptVector< INT >, and etiss::MappedInterruptVector< INT >.
Referenced by isActive().
getBit() [2/2]
virtual bool etiss::InterruptVector::getBit (unsigned bit) const pure virtual
get the bit of an interrupt line
Implemented in etiss::CPUCore::InterruptVectorWrapper, etiss::CPUCore::InterruptVectorWrapper, etiss::MappedInterruptVector< INT >, and etiss::MappedInterruptVector< INT >.
isActive() [1/2]
virtual bool etiss::InterruptVector::isActive () const virtual
Returns
true if any bit is set to true
Reimplemented in etiss::MappedInterruptVector< INT >, etiss::MappedInterruptVector< INT >, etiss::CPUCore::InterruptVectorWrapper, and etiss::CPUCore::InterruptVectorWrapper.
isActive() [2/2]
bool InterruptVector::isActive () const virtual
Returns
true if any bit is set to true
Reimplemented in etiss::MappedInterruptVector< INT >, etiss::MappedInterruptVector< INT >, etiss::CPUCore::InterruptVectorWrapper, and etiss::CPUCore::InterruptVectorWrapper.
Definition at line 59 of file InterruptVector.cpp.
References getBit(), and width().
Referenced by etiss::InterruptHandler::execute().
setBit() [1/2]
virtual void etiss::InterruptVector::setBit (unsigned bit, bool state) pure virtual
set the bit of an interrupt line to state (true = raised)
Implemented in etiss::CPUCore::InterruptVectorWrapper, etiss::CPUCore::InterruptVectorWrapper, etiss::MappedInterruptVector< INT >, and etiss::MappedInterruptVector< INT >.
Referenced by clear(), and etiss::InterruptHandler::execute().
setBit() [2/2]
virtual void etiss::InterruptVector::setBit (unsigned bit, bool state) pure virtual
set the bit of an interrupt line to state (true = raised)
Implemented in etiss::CPUCore::InterruptVectorWrapper, etiss::CPUCore::InterruptVectorWrapper, etiss::MappedInterruptVector< INT >, and etiss::MappedInterruptVector< INT >.
width() [1/2]
virtual unsigned etiss::InterruptVector::width () const pure virtual
number of interrupt bits
Implemented in etiss::MappedInterruptVector< INT >, etiss::MappedInterruptVector< INT >, etiss::CPUCore::InterruptVectorWrapper, and etiss::CPUCore::InterruptVectorWrapper.
Referenced by clear(), and isActive().
width() [2/2]
virtual unsigned etiss::InterruptVector::width () const pure virtual
number of interrupt bits
Implemented in etiss::MappedInterruptVector< INT >, etiss::MappedInterruptVector< INT >, etiss::CPUCore::InterruptVectorWrapper, and etiss::CPUCore::InterruptVectorWrapper.
Member Data Documentation
consumed_by_interruptlistener_
bool etiss::InterruptVector::consumed_by_interruptlistener_ { false }
Definition at line 94 of file InterruptVector.h.
Referenced by etiss::InterruptHandler::execute().
The documentation for this class was generated from the following files:
include/etiss/InterruptVector.h
/home/runner/work/etiss/etiss/src/InterruptVector.cpp