ETISS 0.8.0: pugi::xpath_query Class Reference
pugi::xpath_query Class Reference
#include <pugixml.hpp>
Public Member Functions
xpath_query (const char_t *query, xpath_variable_set *variables=0)
~xpath_query ()
xpath_value_type return_type () const
bool evaluate_boolean (const xpath_node &n) const
double evaluate_number (const xpath_node &n) const
string_t evaluate_string (const xpath_node &n) const
size_t evaluate_string (char_t *buffer, size_t capacity, const xpath_node &n) const
xpath_node_set evaluate_node_set (const xpath_node &n) const
const xpath_parse_result & result () const
operator unspecified_bool_type () const
bool operator! () const
xpath_query (const char_t *query, xpath_variable_set *variables=0)
~xpath_query ()
xpath_value_type return_type () const
bool evaluate_boolean (const xpath_node &n) const
double evaluate_number (const xpath_node &n) const
string_t evaluate_string (const xpath_node &n) const
size_t evaluate_string (char_t *buffer, size_t capacity, const xpath_node &n) const
xpath_node_set evaluate_node_set (const xpath_node &n) const
const xpath_parse_result & result () const
operator unspecified_bool_type () const
bool operator! () const
Private Types
typedef void(* unspecified_bool_type) (xpath_query ***)
typedef void(* unspecified_bool_type) (xpath_query ***)
Private Member Functions
xpath_query (const xpath_query &)
xpath_query & operator= (const xpath_query &)
xpath_query (const xpath_query &)
xpath_query & operator= (const xpath_query &)
Private Attributes
void * _impl
xpath_parse_result _result
Detailed Description
Definition at line 1087 of file pugixml.hpp.
Member Typedef Documentation
unspecified_bool_type [1/2]
typedef void(* pugi::xpath_query::unspecified_bool_type) (xpath_query ***) private
Definition at line 1093 of file pugixml.hpp.
unspecified_bool_type [2/2]
typedef void(* pugi::xpath_query::unspecified_bool_type) (xpath_query ***) private
Definition at line 1093 of file pugixml.hpp.
Constructor & Destructor Documentation
xpath_query() [1/4]
pugi::xpath_query::xpath_query (const xpath_query &) private
xpath_query() [2/4]
PUGI__FN pugi::xpath_query::xpath_query (const char_t * query, xpath_variable_set * variables = 0) explicit
Definition at line 10995 of file pugixml.cpp.
References _impl, _result, and pugi::xpath_parse_result::error.
~xpath_query() [1/2]
PUGI__FN pugi::xpath_query::~xpath_query ()
Definition at line 11021 of file pugixml.cpp.
References _impl.
xpath_query() [3/4]
pugi::xpath_query::xpath_query (const xpath_query &) private
xpath_query() [4/4]
pugi::xpath_query::xpath_query (const char_t * query, xpath_variable_set * variables = 0) explicit
~xpath_query() [2/2]
pugi::xpath_query::~xpath_query ()
Member Function Documentation
evaluate_boolean() [1/2]
PUGI__FN bool pugi::xpath_query::evaluate_boolean (const xpath_node & n) const
Definition at line 11034 of file pugixml.cpp.
References _impl, and c.
evaluate_boolean() [2/2]
bool pugi::xpath_query::evaluate_boolean (const xpath_node & n) const
evaluate_node_set() [1/2]
xpath_node_set pugi::xpath_query::evaluate_node_set (const xpath_node & n) const
evaluate_node_set() [2/2]
PUGI__FN xpath_node_set pugi::xpath_query::evaluate_node_set (const xpath_node & n) const
Definition at line 11095 of file pugixml.cpp.
References _impl, c, pugi::xpath_parse_result::error, and pugi::xpath_type_node_set.
Referenced by pugi::xml_node::select_nodes(), and pugi::xml_node::select_single_node().
evaluate_number() [1/2]
PUGI__FN double pugi::xpath_query::evaluate_number (const xpath_node & n) const
Definition at line 11050 of file pugixml.cpp.
References _impl, c, and gen_nan().
evaluate_number() [2/2]
double pugi::xpath_query::evaluate_number (const xpath_node & n) const
evaluate_string() [1/4]
size_t pugi::xpath_query::evaluate_string (char_t * buffer, size_t capacity, const xpath_node & n) const
evaluate_string() [2/4]
PUGI__FN size_t pugi::xpath_query::evaluate_string (char_t * buffer, size_t capacity, const xpath_node & n) const
Definition at line 11075 of file pugixml.cpp.
References _impl, evaluate_string_impl(), and memcpy().
evaluate_string() [3/4]
PUGI__FN string_t pugi::xpath_query::evaluate_string (const xpath_node & n) const
Definition at line 11067 of file pugixml.cpp.
References _impl, xpath_string::c_str(), and evaluate_string_impl().
evaluate_string() [4/4]
string_t pugi::xpath_query::evaluate_string (const xpath_node & n) const
operator unspecified_bool_type() [1/2]
PUGI__FN pugi::xpath_query::operator xpath_query::unspecified_bool_type () const
Definition at line 11134 of file pugixml.cpp.
References _impl, and pugi::unspecified_bool_xpath_query().
operator unspecified_bool_type() [2/2]
pugi::xpath_query::operator unspecified_bool_type () const
operator!() [1/2]
PUGI__FN bool pugi::xpath_query::operator! () const
Definition at line 11139 of file pugixml.cpp.
References _impl.
operator!() [2/2]
bool pugi::xpath_query::operator! () const
operator=() [1/2]
xpath_query& pugi::xpath_query::operator= (const xpath_query &) private
operator=() [2/2]
xpath_query& pugi::xpath_query::operator= (const xpath_query &) private
result() [1/2]
const xpath_parse_result& pugi::xpath_query::result () const
result() [2/2]
const PUGI__FN xpath_parse_result & pugi::xpath_query::result () const
Definition at line 11127 of file pugixml.cpp.
References _result.
return_type() [1/2]
xpath_value_type pugi::xpath_query::return_type () const
return_type() [2/2]
PUGI__FN xpath_value_type pugi::xpath_query::return_type () const
Definition at line 11026 of file pugixml.cpp.
References _impl, and pugi::xpath_type_none.
Member Data Documentation
_impl
void * pugi::xpath_query::_impl private
Definition at line 1090 of file pugixml.hpp.
Referenced by evaluate_boolean(), evaluate_node_set(), evaluate_number(), evaluate_string(), operator unspecified_bool_type(), operator!(), return_type(), xpath_query(), and ~xpath_query().
_result
xpath_parse_result pugi::xpath_query::_result private
Definition at line 1091 of file pugixml.hpp.
Referenced by result(), and xpath_query().
The documentation for this class was generated from the following files:
include/etiss/fault/xml/pugixml.hpp
/home/runner/work/etiss/etiss/src/fault/xml/pugixml.cpp