ETISS 0.8.0: OR1KArch Class Reference
OR1KArch Class Reference
TODO: implement opt_hostendianess for store/load instructions.
#include <OR1KArch.h>
Public Member Functions
OR1KArch ()
virtual const std::set< std::string > & getListenerSupportedRegisters ()
virtual etiss::Plugin * newTimer (ETISS_CPU *cpu)
create a simple default timer implementaion instance for this architecture.
virtual void deleteTimer (etiss::Plugin *timer)
delete timer instance
virtual ETISS_CPU * newCPU ()
allocate new cpu structure
virtual void resetCPU (ETISS_CPU *cpu, etiss::uint64 *startpointer)
reset cpu (structure)
virtual void deleteCPU (ETISS_CPU *)
delete cpu structure
virtual std::shared_ptr< etiss::VirtualStruct > getVirtualStruct (ETISS_CPU *cpu)
this function must return a valid pointer to a virtual struct
virtual void deleteVirtualStruct (etiss::VirtualStruct *stru)
virtual unsigned getMaximumInstructionSizeInBytes ()
virtual unsigned getInstructionSizeInBytes ()
virtual const std::set< std::string > & getHeaders () const
required headers (OR1K.h)
virtual etiss::int32 handleException (etiss::int32 code, ETISS_CPU *cpu)
translate/process exceptions that occur at runtime
virtual void initInstrSet (etiss::instr::ModedInstructionSet &) const
called to add instructions to the instruction set
virtual void initCodeBlock (etiss::CodeBlock &cb) const
called before instructions are translated for the code block
virtual etiss::InterruptVector * createInterruptVector (ETISS_CPU *cpu)
allocate a new interrupt vector object for the given cpu
virtual void deleteInterruptVector (etiss::InterruptVector *vec, ETISS_CPU *cpu)
delete an allocated interrupt vector object
virtual etiss::plugin::gdb::GDBCore & getGDBCore ()
returns arch dependent gdb functions.
Public Member Functions inherited from etiss::CPUArch
CPUArch (std::string archname)
virtual ~CPUArch ()
std::string getArchName () const
returns the name of this architecture.
std::string getName () const
returns the name of this architecture.
virtual unsigned getMaximumInstructionsPerMetaInstruction ()
maximum number of instructions in a meta instruction
virtual unsigned getSuperInstructionCount ()
fixed number of sub instructions per instruction (e.g.
virtual std::string getBlockGlobalCode ()
get c++ code snippet that is placed at the top of a translated block
virtual bool unlikelyInstruction (etiss::uint8 *instr, unsigned length, bool &ismetainstruction)
return true if the given data is unlikely to be an instruction.
virtual std::string getIncludePath ()
returns a path that will be used to look up header files
virtual void finalizeInstrSet (etiss::instr::ModedInstructionSet &) const
the default behavior of this function of a cpu arch is to add "cpu->cpuTime_ps += cpu->cpuCycleTime_ps;" if the cpu time update group is not in use
virtual void compensateEndianess (ETISS_CPU *cpu, etiss::instr::BitArray &ba) const
this function should compensate for any endianess on a BitArray so that bit 0 is always the LSB.
virtual etiss::mm::MMU * newMMU (ETISS_CPU *cpu)
It is an interface to instanciate a Memory Management Unit.
CPUArch (std::string archname)
virtual ~CPUArch ()
std::string getArchName () const
returns the name of this architecture.
std::string getName () const
returns the name of this architecture.
virtual unsigned getMaximumInstructionsPerMetaInstruction ()
maximum number of instructions in a meta instruction
virtual unsigned getSuperInstructionCount ()
fixed number of sub instructions per instruction (e.g.
virtual std::string getBlockGlobalCode ()
get c++ code snippet that is placed at the top of a translated block
virtual bool unlikelyInstruction (etiss::uint8 *instr, unsigned length, bool &ismetainstruction)
return true if the given data is unlikely to be an instruction.
virtual std::string getIncludePath ()
returns a path that will be used to look up header files
virtual void finalizeInstrSet (etiss::instr::ModedInstructionSet &) const
the default behavior of this function of a cpu arch is to add "cpu->cpuTime_ps += cpu->cpuCycleTime_ps;" if the cpu time update group is not in use
virtual void compensateEndianess (ETISS_CPU *cpu, etiss::instr::BitArray &ba) const
this function should compensate for any endianess on a BitArray so that bit 0 is always the LSB.
virtual etiss::mm::MMU * newMMU (ETISS_CPU *cpu)
It is an interface to instanciate a Memory Management Unit.
Public Member Functions inherited from etiss::CPUArchRegListenerInterface
virtual ~CPUArchRegListenerInterface ()
virtual ~CPUArchRegListenerInterface ()
Public Member Functions inherited from etiss::CPUArchCPUManipulation
virtual ~CPUArchCPUManipulation ()
virtual ~CPUArchCPUManipulation ()
Public Member Functions inherited from etiss::CPUArchDefaultPlugins
virtual ~CPUArchDefaultPlugins ()
virtual ~CPUArchDefaultPlugins ()
Public Member Functions inherited from etiss::TranslationPlugin
TranslationPlugin ()
virtual ~TranslationPlugin ()
virtual void finalizeCodeBlock (etiss::CodeBlock &) const
called after all instructions have been translated for the code block
virtual void * getPluginHandle ()
called to get the handle that is available in translated code via getPoinerCode(). [default: this]
TranslationPlugin ()
virtual ~TranslationPlugin ()
virtual void finalizeCodeBlock (etiss::CodeBlock &) const
called after all instructions have been translated for the code block
virtual void * getPluginHandle ()
called to get the handle that is available in translated code via getPoinerCode(). [default: this]
Public Member Functions inherited from etiss::Plugin
virtual ~Plugin ()
unsigned getType ()
InterruptListenerPlugin * getInterruptListenerPlugin ()
CoroutinePlugin * getCoroutinePlugin ()
SystemWrapperPlugin * getSystemWrapperPlugin ()
RegisterDevicePlugin * getRegisterDevicePlugin ()
TranslationPlugin * getTranslationPlugin ()
std::string getPluginName () const
const std::string & getLastAssignedCoreName ()
std::string toString () const
virtual ~Plugin ()
unsigned getType ()
InterruptListenerPlugin * getInterruptListenerPlugin ()
CoroutinePlugin * getCoroutinePlugin ()
SystemWrapperPlugin * getSystemWrapperPlugin ()
RegisterDevicePlugin * getRegisterDevicePlugin ()
TranslationPlugin * getTranslationPlugin ()
std::string getPluginName () const
const std::string & getLastAssignedCoreName ()
std::string toString () const
Public Member Functions inherited from etiss::ToString
ToString ()
virtual ~ToString ()
ToString ()
virtual ~ToString ()
Public Attributes
bool ignore_sr_iee
ignore sr iee flag
Private Attributes
std::set< std::string > reg32names
std::set< std::string > listenerSupportedRegisters_
std::set< std::string > headers_
OR1KGDBCore gdbcore_
Additional Inherited Members
Static Public Member Functions inherited from etiss::CPUArchRegListenerInterface
static void signalChangedRegisterValue (ETISS_CPU *cpu, const char *registerName)
call this function to inform RegisterDevicePlugins about changed special register values.
static void signalChangedRegisterValue (ETISS_CPU *cpu, const char *registerName)
call this function to inform RegisterDevicePlugins about changed special register values.
Static Public Attributes inherited from etiss::Plugin
static const unsigned INTERRUPTLISTENER = 1 << 0
access to translated code
static const unsigned COROUTINE = 1 << 1
callback after execution of each translated block
static const unsigned SYSTEMWRAPPER = 1 << 2
can wrap/change ETISS_System structure at execution start
static const unsigned REGISTERDEVICE
gets noticed of changes to special registers (e.g. mmu register etc. [depends on architecture])
static const unsigned TRANSLATION
access to translated code during translation phase or when instruction tree is built
Protected Member Functions inherited from etiss::CPUArch
virtual std::string _getPluginName () const
do not override. maps to getName().
virtual std::string _getPluginName () const
do not override. maps to getName().
Protected Member Functions inherited from etiss::TranslationPlugin
std::string getPointerCode () const
returns a C code expression that allows to get or assign a pointer to the variable assigned to this translation plugin.
std::string getPointerCode () const
returns a C code expression that allows to get or assign a pointer to the variable assigned to this translation plugin.
Protected Member Functions inherited from etiss::Plugin
Plugin (unsigned type=0)
virtual void init (ETISS_CPU *cpu, ETISS_System *system, CPUArch *arch)
this function is called before the plugin is used in the cpu execution loop (etiss::CPUCore::execute).
virtual void cleanup ()
this function is called after cpu execution loop (etiss::CPUCore::execute) finished.
void setCorrespondingCPUCoreName (std::string name)
virtual void addedToCPUCore (etiss::CPUCore *core)
called as soon a plugin has been added to its CPUCore.
virtual void removedFromCPUCore (etiss::CPUCore *core)
called as soon a plugin has been removed from its CPUCore.
Plugin (unsigned type=0)
virtual void init (ETISS_CPU *cpu, ETISS_System *system, CPUArch *arch)
this function is called before the plugin is used in the cpu execution loop (etiss::CPUCore::execute).
virtual void cleanup ()
this function is called after cpu execution loop (etiss::CPUCore::execute) finished.
void setCorrespondingCPUCoreName (std::string name)
virtual void addedToCPUCore (etiss::CPUCore *core)
called as soon a plugin has been added to its CPUCore.
virtual void removedFromCPUCore (etiss::CPUCore *core)
called as soon a plugin has been removed from its CPUCore.
Protected Attributes inherited from etiss::Plugin
ETISS_CPU * plugin_cpu_
holds a pointer to the cpu structure. will be set before init call and after cleanup call
ETISS_System * plugin_system_
holds a pointer to the system structure.
CPUArch * plugin_arch_
holds a pointer to the CPUArch instance. will be set before init call and after cleanup call
CPUCore * plugin_core_
holds a pointer to the associated CPUCore instance.
Detailed Description
TODO: implement opt_hostendianess for store/load instructions.
Definition at line 69 of file OR1KArch.h.
Constructor & Destructor Documentation
OR1KArch()
OR1KArch::OR1KArch ()
Definition at line 215 of file OR1KArch.cpp.
References headers_, ignore_sr_iee, listenerSupportedRegisters_, and reg32names.
Member Function Documentation
createInterruptVector()
etiss::InterruptVector * OR1KArch::createInterruptVector (ETISS_CPU * cpu) virtual
allocate a new interrupt vector object for the given cpu
Reimplemented from etiss::CPUArch.
Definition at line 485 of file OR1KArch.cpp.
References OR1K::cpu, and OR1K::SPR.
deleteCPU()
void OR1KArch::deleteCPU (ETISS_CPU *) virtual
delete cpu structure
Implements etiss::CPUArch.
Definition at line 317 of file OR1KArch.cpp.
References OR1K::cpu.
deleteInterruptVector()
void OR1KArch::deleteInterruptVector (etiss::InterruptVector * vec, ETISS_CPU * cpu) virtual
delete an allocated interrupt vector object
Reimplemented from etiss::CPUArch.
Definition at line 495 of file OR1KArch.cpp.
deleteTimer()
void OR1KArch::deleteTimer (etiss::Plugin * timer) virtual
delete timer instance
Returns
may be 0
Reimplemented from etiss::CPUArchDefaultPlugins.
Definition at line 336 of file OR1KArch.cpp.
deleteVirtualStruct()
void OR1KArch::deleteVirtualStruct (etiss::VirtualStruct * stru) virtual
Definition at line 322 of file OR1KArch.cpp.
getGDBCore()
etiss::plugin::gdb::GDBCore & OR1KArch::getGDBCore () virtual
returns arch dependent gdb functions.
althought not required it is strongly recommended to implement this
Reimplemented from etiss::CPUArch.
Definition at line 499 of file OR1KArch.cpp.
References gdbcore_.
getHeaders()
const std::set< std::string > & OR1KArch::getHeaders () const virtual
required headers (OR1K.h)
Implements etiss::CPUArch.
Definition at line 370 of file OR1KArch.cpp.
References headers_.
getInstructionSizeInBytes()
unsigned OR1KArch::getInstructionSizeInBytes () virtual
Returns
4
Implements etiss::CPUArch.
Definition at line 345 of file OR1KArch.cpp.
getListenerSupportedRegisters()
const std::set< std::string > & OR1KArch::getListenerSupportedRegisters () virtual
See also
CPUArchRegListenerInterface::signalChangedRegisterValue
Implements etiss::CPUArchRegListenerInterface.
Definition at line 327 of file OR1KArch.cpp.
References listenerSupportedRegisters_.
getMaximumInstructionSizeInBytes()
unsigned OR1KArch::getMaximumInstructionSizeInBytes () virtual
Returns
8 (jump instruction + instruction of delay slot)
Implements etiss::CPUArch.
Definition at line 341 of file OR1KArch.cpp.
getVirtualStruct()
std::shared_ptr< etiss::VirtualStruct > OR1KArch::getVirtualStruct (ETISS_CPU * cpu) virtual
this function must return a valid pointer to a virtual struct
Implements etiss::CPUArchCPUManipulation.
Definition at line 655 of file OR1KArch.cpp.
References etiss::VirtualStruct::allocate().
handleException()
etiss::int32 OR1KArch::handleException (etiss::int32 code, ETISS_CPU * cpu) virtual
translate/process exceptions that occur at runtime
Reimplemented from etiss::CPUArch.
Definition at line 374 of file OR1KArch.cpp.
References OR1K::cpu, OR1K::exceptionDepth, ignore_sr_iee, etiss::INFO, ETISS_CPU::instructionPointer, etiss::log(), etiss::mm::NOERROR, OR1K_BUSEXCEPTION, OR1K_EXTERNALINTERRUPTEXCEPTION, OR1K_ILLEGALINSTRUCTIONEXCEPTION, OR1K_SR_DME, OR1K_SR_EPH, OR1K_SR_IEE, OR1K_SR_IME, OR1K_SR_SM, OR1K_SR_TEE, OR1K::PC, OR1K::SR, and etiss::WARNING.
initCodeBlock()
void OR1KArch::initCodeBlock (etiss::CodeBlock &) const virtual
called before instructions are translated for the code block
Reimplemented from etiss::TranslationPlugin.
Definition at line 363 of file OR1KArch.cpp.
References etiss::CodeBlock::fileglobalCode().
initInstrSet()
void OR1KArch::initInstrSet (etiss::instr::ModedInstructionSet &) const virtual
called to add instructions to the instruction set
Reimplemented from etiss::TranslationPlugin.
Definition at line 350 of file OR1KArch.cpp.
References etiss::instr::InstructionCollection::addTo(), etiss::ERROR, etiss_log, and Processor_OR1K.
newCPU()
ETISS_CPU * OR1KArch::newCPU () virtual
allocate new cpu structure
Implements etiss::CPUArch.
Definition at line 238 of file OR1KArch.cpp.
References resetCPU().
newTimer()
etiss::Plugin * OR1KArch::newTimer (ETISS_CPU * cpu) virtual
create a simple default timer implementaion instance for this architecture.
Returns
may be 0
Reimplemented from etiss::CPUArchDefaultPlugins.
Definition at line 332 of file OR1KArch.cpp.
resetCPU()
void OR1KArch::resetCPU (ETISS_CPU * cpu, etiss::uint64 * startpointer) virtual
reset cpu (structure)
index officially not defined as 0
index officially not defined as 1
Implements etiss::CPUArch.
Definition at line 249 of file OR1KArch.cpp.
References etiss::cfg(), OR1K::cpu, ETISS_CPU::cpuCycleTime_ps, ETISS_CPU::cpuTime_ps, etiss::Configuration::get(), etiss::Plugin::getLastAssignedCoreName(), ETISS_CPU::instructionPointer, memset(), ETISS_CPU::mode, OR1K_SR_FO, and OR1K_SR_SM.
Referenced by newCPU().
Member Data Documentation
gdbcore_
OR1KGDBCore OR1KArch::gdbcore_ private
Definition at line 112 of file OR1KArch.h.
Referenced by getGDBCore().
headers_
std::set<std::string> OR1KArch::headers_ private
Definition at line 111 of file OR1KArch.h.
Referenced by getHeaders(), and OR1KArch().
ignore_sr_iee
bool OR1KArch::ignore_sr_iee
ignore sr iee flag
Definition at line 115 of file OR1KArch.h.
Referenced by handleException(), OR1KArch(), and OR1KArch_createCPUArch().
listenerSupportedRegisters_
std::set<std::string> OR1KArch::listenerSupportedRegisters_ private
Definition at line 110 of file OR1KArch.h.
Referenced by getListenerSupportedRegisters(), and OR1KArch().
reg32names
std::set<std::string> OR1KArch::reg32names private
Definition at line 109 of file OR1KArch.h.
Referenced by OR1KArch().
The documentation for this class was generated from the following files:
/home/runner/work/etiss/etiss/ArchImpl/OR1K/OR1KArch.h
/home/runner/work/etiss/etiss/ArchImpl/OR1K/OR1KArch.cpp