ETISS 0.8.0: etiss::CodeSet Class Reference
etiss::CodeSet Class Reference
A set of CodeParts.
#include <CodePart.h>
Public Member Functions
CodeSet ()
CodeSet (const CodeSet &cs)
void append (const CodePart &part, CodePart::TYPE type)
CodePart & append (CodePart::TYPE type)
CodePart & prepend (CodePart::TYPE type)
std::string toString (RegisterSet &ignored, bool &ok) const
writes the contained CodeParts as needed with respect to the given RegisterSet of bits that are not required to be set by this code
CodeSet ()
CodeSet (const CodeSet &cs)
void append (const CodePart &part, CodePart::TYPE type)
CodePart & append (CodePart::TYPE type)
CodePart & prepend (CodePart::TYPE type)
std::string toString (RegisterSet &ignored, bool &ok) const
writes the contained CodeParts as needed with respect to the given RegisterSet of bits that are not required to be set by this code
Static Private Member Functions
static void writeCodeParts (std::string &code, const std::list< CodePart > &parts, bool required, RegisterSet &ignored, bool intersect)
static void writeCodeParts (std::string &code, const std::list< CodePart > &parts, bool required, RegisterSet &ignored, bool intersect)
Private Attributes
std::list< CodePart > pindbgretreq_parts_
std::list< CodePart > inireq_parts_
std::list< CodePart > midopt_parts_
std::list< CodePart > appreq_parts_
std::list< CodePart > appopt_parts_
std::list< CodePart > appretreq_parts_
Detailed Description
A set of CodeParts.
This class stores CodeParts and appends them as needed in the CodeSet::toString function
Definition at line 436 of file CodePart.h.
Constructor & Destructor Documentation
CodeSet() [1/4]
etiss::CodeSet::CodeSet () inline
Definition at line 440 of file CodePart.h.
CodeSet() [2/4]
etiss::CodeSet::CodeSet (const CodeSet & cs) inline
Definition at line 441 of file CodePart.h.
References appopt_parts_, appreq_parts_, appretreq_parts_, inireq_parts_, midopt_parts_, and pindbgretreq_parts_.
CodeSet() [3/4]
etiss::CodeSet::CodeSet () inline
Definition at line 440 of file CodePart.h.
CodeSet() [4/4]
etiss::CodeSet::CodeSet (const CodeSet & cs) inline
Definition at line 441 of file CodePart.h.
References appopt_parts_, appreq_parts_, appretreq_parts_, inireq_parts_, midopt_parts_, and pindbgretreq_parts_.
Member Function Documentation
append() [1/4]
CodePart& etiss::CodeSet::append (CodePart::TYPE type) inline
Definition at line 474 of file CodePart.h.
References etiss::CodePart::APPENDEDOPTIONAL, etiss::CodePart::APPENDEDREQUIRED, etiss::CodePart::APPENDEDRETURNINGREQUIRED, appopt_parts_, appreq_parts_, appretreq_parts_, inireq_parts_, etiss::CodePart::INITIALREQUIRED, midopt_parts_, etiss::CodePart::OPTIONALMIDDLE, pindbgretreq_parts_, and etiss::CodePart::PREINITIALDEBUGRETURNING.
append() [2/4]
CodePart& etiss::CodeSet::append (CodePart::TYPE type) inline
Definition at line 474 of file CodePart.h.
References etiss::CodePart::APPENDEDOPTIONAL, etiss::CodePart::APPENDEDREQUIRED, etiss::CodePart::APPENDEDRETURNINGREQUIRED, appopt_parts_, appreq_parts_, appretreq_parts_, inireq_parts_, etiss::CodePart::INITIALREQUIRED, midopt_parts_, etiss::CodePart::OPTIONALMIDDLE, pindbgretreq_parts_, and etiss::CodePart::PREINITIALDEBUGRETURNING.
append() [3/4]
void etiss::CodeSet::append (const CodePart & part, CodePart::TYPE type) inline
Definition at line 450 of file CodePart.h.
References etiss::CodePart::APPENDEDOPTIONAL, etiss::CodePart::APPENDEDREQUIRED, etiss::CodePart::APPENDEDRETURNINGREQUIRED, appopt_parts_, appreq_parts_, appretreq_parts_, inireq_parts_, etiss::CodePart::INITIALREQUIRED, midopt_parts_, etiss::CodePart::OPTIONALMIDDLE, pindbgretreq_parts_, and etiss::CodePart::PREINITIALDEBUGRETURNING.
Referenced by etiss::plugin::InstructionAccurateCallback::finalizeInstrSet(), etiss::plugin::PrintInstruction::finalizeInstrSet(), etiss::plugin::VariableValueLogger::finalizeInstrSet(), etiss::plugin::InstructionSpecificAddressCallback::finalizeInstrSet(), fpu_append_exceptioncode(), etiss::instr::InstructionSet::InstructionSet(), l_addsubX(), l_cust(), l_ext(), l_sf(), loadinstr(), OR1K_l_muluX(), OR1K_l_mulX(), shift(), simple_op_rDAB(), simple_op_rDAI(), storeinstr(), translate_fpu(), etiss::Translation::translateBlock(), and update_pc().
append() [4/4]
void etiss::CodeSet::append (const CodePart & part, CodePart::TYPE type) inline
Definition at line 450 of file CodePart.h.
References etiss::CodePart::APPENDEDOPTIONAL, etiss::CodePart::APPENDEDREQUIRED, etiss::CodePart::APPENDEDRETURNINGREQUIRED, appopt_parts_, appreq_parts_, appretreq_parts_, inireq_parts_, etiss::CodePart::INITIALREQUIRED, midopt_parts_, etiss::CodePart::OPTIONALMIDDLE, pindbgretreq_parts_, and etiss::CodePart::PREINITIALDEBUGRETURNING.
prepend() [1/2]
CodePart& etiss::CodeSet::prepend (CodePart::TYPE type) inline
Definition at line 503 of file CodePart.h.
References etiss::CodePart::APPENDEDOPTIONAL, etiss::CodePart::APPENDEDREQUIRED, etiss::CodePart::APPENDEDRETURNINGREQUIRED, appopt_parts_, appreq_parts_, appretreq_parts_, inireq_parts_, etiss::CodePart::INITIALREQUIRED, midopt_parts_, etiss::CodePart::OPTIONALMIDDLE, pindbgretreq_parts_, and etiss::CodePart::PREINITIALDEBUGRETURNING.
prepend() [2/2]
CodePart& etiss::CodeSet::prepend (CodePart::TYPE type) inline
Definition at line 503 of file CodePart.h.
References etiss::CodePart::APPENDEDOPTIONAL, etiss::CodePart::APPENDEDREQUIRED, etiss::CodePart::APPENDEDRETURNINGREQUIRED, appopt_parts_, appreq_parts_, appretreq_parts_, inireq_parts_, etiss::CodePart::INITIALREQUIRED, midopt_parts_, etiss::CodePart::OPTIONALMIDDLE, pindbgretreq_parts_, and etiss::CodePart::PREINITIALDEBUGRETURNING.
Referenced by getOR1200Timing(), etiss::DataSheetAccurateTiming::handleMatch_cycles(), and Server_finalizeInstrSet().
toString() [1/2]
std::string CodeSet::toString (RegisterSet & ignored, bool & ok) const
writes the contained CodeParts as needed with respect to the given RegisterSet of bits that are not required to be set by this code
Definition at line 120 of file CodePart.cpp.
References appopt_parts_, appreq_parts_, appretreq_parts_, inireq_parts_, midopt_parts_, pindbgretreq_parts_, and writeCodeParts().
toString() [2/2]
std::string etiss::CodeSet::toString (RegisterSet & ignored, bool & ok) const
writes the contained CodeParts as needed with respect to the given RegisterSet of bits that are not required to be set by this code
writeCodeParts() [1/2]
void CodeSet::writeCodeParts (std::string & code, const std::list< CodePart > & parts, bool required, RegisterSet & ignored, bool intersect) static private
Definition at line 57 of file CodePart.cpp.
References etiss::RegisterSet::applyShadow(), etiss::RegisterSet::clear(), etiss::RegisterSet::intersect(), and etiss::RegisterSet::merge().
Referenced by toString().
writeCodeParts() [2/2]
static void etiss::CodeSet::writeCodeParts (std::string & code, const std::list< CodePart > & parts, bool required, RegisterSet & ignored, bool intersect) static private
Member Data Documentation
appopt_parts_
std::list< CodePart > etiss::CodeSet::appopt_parts_ private
Definition at line 549 of file CodePart.h.
Referenced by append(), CodeSet(), prepend(), and toString().
appreq_parts_
std::list< CodePart > etiss::CodeSet::appreq_parts_ private
Definition at line 548 of file CodePart.h.
Referenced by append(), CodeSet(), prepend(), and toString().
appretreq_parts_
std::list< CodePart > etiss::CodeSet::appretreq_parts_ private
Definition at line 550 of file CodePart.h.
Referenced by append(), CodeSet(), prepend(), and toString().
inireq_parts_
std::list< CodePart > etiss::CodeSet::inireq_parts_ private
Definition at line 546 of file CodePart.h.
Referenced by append(), CodeSet(), prepend(), and toString().
midopt_parts_
std::list< CodePart > etiss::CodeSet::midopt_parts_ private
Definition at line 547 of file CodePart.h.
Referenced by append(), CodeSet(), prepend(), and toString().
pindbgretreq_parts_
std::list< CodePart > etiss::CodeSet::pindbgretreq_parts_ private
Definition at line 545 of file CodePart.h.
Referenced by append(), CodeSet(), prepend(), and toString().
The documentation for this class was generated from the following files:
include/etiss/CodePart.h
/home/runner/work/etiss/etiss/src/CodePart.cpp