ETISS 0.8.0: etiss::CodeBlock Class Reference
etiss::CodeBlock Class Reference
A list of CodeSets.
#include <CodePart.h>
Classes
class Line
equivalent of a translated instruction
Public Member Functions
CodeBlock (etiss::uint64 startindex)
Line & get (unsigned index)
Line & append (etiss::uint64 addr)
unsigned length () const
std::set< std::string > & fileglobalCode ()
std::set< std::string > & functionglobalCode ()
void toCode (std::stringstream &out, const std::string &funcname, std::set< std::string > *fileglobalcode)
CodeBlock (etiss::uint64 startindex)
Line & get (unsigned index)
Line & append (etiss::uint64 addr)
unsigned length () const
std::set< std::string > & fileglobalCode ()
std::set< std::string > & functionglobalCode ()
void toCode (std::stringstream &out, const std::string &funcname, std::set< std::string > *fileglobalcode)
Private Attributes
std::vector< Line > lines_
etiss::uint64 startindex_
etiss::uint64 endaddress_
std::set< std::string > fileglobal_code
std::set< std::string > functionglobal_code
Friends
class Translation
Detailed Description
A list of CodeSets.
this structure corresponds to the content of the switch statement of the translated block where one CodeSet is one translates instruction is one section after a case label.
e.g.: switch (instructionpointer){ case 0: { ... // CodeSet number 0 } case 1: { ... // CodeSet number 1 } }
Definition at line 569 of file CodePart.h.
Constructor & Destructor Documentation
CodeBlock() [1/2]
etiss::CodeBlock::CodeBlock (etiss::uint64 startindex) inline
Definition at line 595 of file CodePart.h.
CodeBlock() [2/2]
etiss::CodeBlock::CodeBlock (etiss::uint64 startindex) inline
Definition at line 595 of file CodePart.h.
Member Function Documentation
append() [1/2]
Line& etiss::CodeBlock::append (etiss::uint64 addr) inline
Definition at line 597 of file CodePart.h.
References lines_.
Referenced by etiss::Translation::translateBlock().
append() [2/2]
Line& etiss::CodeBlock::append (etiss::uint64 addr) inline
Definition at line 597 of file CodePart.h.
References lines_.
fileglobalCode() [1/2]
std::set<std::string>& etiss::CodeBlock::fileglobalCode () inline
Definition at line 603 of file CodePart.h.
References fileglobal_code.
Referenced by etiss::plugin::gdb::Server::finalizeCodeBlock(), etiss::Translation::getBlock(), etiss::plugin::VariableValueLogger::initCodeBlock(), etiss::plugin::InstructionAccurateCallback::initCodeBlock(), etiss::plugin::PrintInstruction::initCodeBlock(), OR1KArch::initCodeBlock(), RISCVArch::initCodeBlock(), etiss::plugin::InstructionSpecificAddressCallback::initCodeBlock(), and RISCV64Arch::initCodeBlock().
fileglobalCode() [2/2]
std::set<std::string>& etiss::CodeBlock::fileglobalCode () inline
Definition at line 603 of file CodePart.h.
References fileglobal_code.
functionglobalCode() [1/2]
std::set<std::string>& etiss::CodeBlock::functionglobalCode () inline
Definition at line 604 of file CodePart.h.
References functionglobal_code.
Referenced by etiss::Translation::getBlock(), and etiss::plugin::InstructionSpecificAddressCallback::initCodeBlock().
functionglobalCode() [2/2]
std::set<std::string>& etiss::CodeBlock::functionglobalCode () inline
Definition at line 604 of file CodePart.h.
References functionglobal_code.
get() [1/2]
Line& etiss::CodeBlock::get (unsigned index) inline
Definition at line 596 of file CodePart.h.
References lines_.
get() [2/2]
Line& etiss::CodeBlock::get (unsigned index) inline
Definition at line 596 of file CodePart.h.
References lines_.
length() [1/2]
unsigned etiss::CodeBlock::length () const inline
Definition at line 602 of file CodePart.h.
References lines_.
length() [2/2]
unsigned etiss::CodeBlock::length () const inline
Definition at line 602 of file CodePart.h.
References lines_.
toCode() [1/2]
void CodeBlock::toCode (std::stringstream & out, const std::string & funcname, std::set< std::string > * fileglobalcode)
Definition at line 146 of file CodePart.cpp.
References etiss::FATALERROR, fileglobal_code, functionglobal_code, lines_, etiss::log(), and startindex_.
Referenced by etiss::Translation::getBlock().
toCode() [2/2]
void etiss::CodeBlock::toCode (std::stringstream & out, const std::string & funcname, std::set< std::string > * fileglobalcode)
Friends And Related Function Documentation
Translation
Translation friend
Definition at line 571 of file CodePart.h.
Member Data Documentation
endaddress_
etiss::uint64 etiss::CodeBlock::endaddress_ private
Definition at line 610 of file CodePart.h.
Referenced by etiss::Translation::getBlock(), and etiss::Translation::translateBlock().
fileglobal_code
std::set< std::string > etiss::CodeBlock::fileglobal_code private
Definition at line 611 of file CodePart.h.
Referenced by fileglobalCode(), and toCode().
functionglobal_code
std::set< std::string > etiss::CodeBlock::functionglobal_code private
Definition at line 612 of file CodePart.h.
Referenced by functionglobalCode(), and toCode().
lines_
std::vector< Line > etiss::CodeBlock::lines_ private
Definition at line 608 of file CodePart.h.
Referenced by append(), get(), length(), and toCode().
startindex_
etiss::uint64 etiss::CodeBlock::startindex_ private
Definition at line 609 of file CodePart.h.
Referenced by etiss::Translation::getBlock(), toCode(), and etiss::Translation::translateBlock().
The documentation for this class was generated from the following files:
include/etiss/CodePart.h
/home/runner/work/etiss/etiss/src/CodePart.cpp