ETISS 0.8.0: pugi::xml_text Class Reference
pugi::xml_text Class Reference
#include <pugixml.hpp>
Public Member Functions
xml_text ()
operator unspecified_bool_type () const
bool operator! () const
bool empty () const
const char_t * get () const
const char_t * as_string (const char_t *def=PUGIXML_TEXT("")) const
int as_int (int def=0) const
unsigned int as_uint (unsigned int def=0) const
double as_double (double def=0) const
float as_float (float def=0) const
bool as_bool (bool def=false) const
bool set (const char_t *rhs)
bool set (int rhs)
bool set (unsigned int rhs)
bool set (double rhs)
bool set (bool rhs)
xml_text & operator= (const char_t *rhs)
xml_text & operator= (int rhs)
xml_text & operator= (unsigned int rhs)
xml_text & operator= (double rhs)
xml_text & operator= (bool rhs)
xml_node data () const
xml_text ()
operator unspecified_bool_type () const
bool operator! () const
bool empty () const
const char_t * get () const
const char_t * as_string (const char_t *def=PUGIXML_TEXT("")) const
int as_int (int def=0) const
unsigned int as_uint (unsigned int def=0) const
double as_double (double def=0) const
float as_float (float def=0) const
bool as_bool (bool def=false) const
bool set (const char_t *rhs)
bool set (int rhs)
bool set (unsigned int rhs)
bool set (double rhs)
bool set (bool rhs)
xml_text & operator= (const char_t *rhs)
xml_text & operator= (int rhs)
xml_text & operator= (unsigned int rhs)
xml_text & operator= (double rhs)
xml_text & operator= (bool rhs)
xml_node data () const
Private Types
typedef void(* unspecified_bool_type) (xml_text ***)
typedef void(* unspecified_bool_type) (xml_text ***)
Private Member Functions
xml_text (xml_node_struct *root)
xml_node_struct * _data_new ()
xml_node_struct * _data () const
xml_text (xml_node_struct *root)
xml_node_struct * _data_new ()
xml_node_struct * _data () const
Private Attributes
xml_node_struct * _root
Friends
class xml_node
Detailed Description
Definition at line 637 of file pugixml.hpp.
Member Typedef Documentation
unspecified_bool_type [1/2]
typedef void(* pugi::xml_text::unspecified_bool_type) (xml_text ***) private
Definition at line 643 of file pugixml.hpp.
unspecified_bool_type [2/2]
typedef void(* pugi::xml_text::unspecified_bool_type) (xml_text ***) private
Definition at line 643 of file pugixml.hpp.
Constructor & Destructor Documentation
xml_text() [1/4]
PUGI__FN pugi::xml_text::xml_text (xml_node_struct * root) explicit private
Definition at line 5497 of file pugixml.cpp.
xml_text() [2/4]
PUGI__FN pugi::xml_text::xml_text ()
Definition at line 5520 of file pugixml.cpp.
xml_text() [3/4]
pugi::xml_text::xml_text (xml_node_struct * root) explicit private
xml_text() [4/4]
pugi::xml_text::xml_text ()
Member Function Documentation
_data() [1/2]
PUGI__FN xml_node_struct * pugi::xml_text::_data () const private
Definition at line 5499 of file pugixml.cpp.
References _root, pugi::xml_node_struct::first_child, is_text_node(), and pugi::xml_node_struct::next_sibling.
Referenced by _data_new(), as_bool(), as_double(), as_float(), as_int(), as_string(), as_uint(), data(), empty(), get(), operator unspecified_bool_type(), and operator!().
_data() [2/2]
xml_node_struct* pugi::xml_text::_data () const private
_data_new() [1/2]
PUGI__FN xml_node_struct * pugi::xml_text::_data_new () private
Definition at line 5511 of file pugixml.cpp.
References _data(), _root, pugi::node_pcdata, and xml_node.
Referenced by set().
_data_new() [2/2]
xml_node_struct* pugi::xml_text::_data_new () private
as_bool() [1/2]
bool pugi::xml_text::as_bool (bool def = false) const
as_bool() [2/2]
PUGI__FN bool pugi::xml_text::as_bool (bool def = false) const
Definition at line 5581 of file pugixml.cpp.
References _data(), get_value_bool(), and pugi::xml_node_struct::value.
as_double() [1/2]
double pugi::xml_text::as_double (double def = 0) const
as_double() [2/2]
PUGI__FN double pugi::xml_text::as_double (double def = 0) const
Definition at line 5567 of file pugixml.cpp.
References _data(), get_value_double(), and pugi::xml_node_struct::value.
as_float() [1/2]
float pugi::xml_text::as_float (float def = 0) const
as_float() [2/2]
PUGI__FN float pugi::xml_text::as_float (float def = 0) const
Definition at line 5574 of file pugixml.cpp.
References _data(), get_value_float(), and pugi::xml_node_struct::value.
as_int() [1/2]
PUGI__FN int pugi::xml_text::as_int (int def = 0) const
Definition at line 5553 of file pugixml.cpp.
References _data(), get_value_int(), and pugi::xml_node_struct::value.
as_int() [2/2]
int pugi::xml_text::as_int (int def = 0) const
as_string() [1/2]
const PUGI__FN char_t * pugi::xml_text::as_string (const char_t * def = PUGIXML_TEXT("")) const
Definition at line 5546 of file pugixml.cpp.
References _data(), and pugi::xml_node_struct::value.
as_string() [2/2]
const char_t* pugi::xml_text::as_string (const char_t * def = PUGIXML_TEXT("")) const
as_uint() [1/2]
unsigned int pugi::xml_text::as_uint (unsigned int def = 0) const
as_uint() [2/2]
PUGI__FN unsigned int pugi::xml_text::as_uint (unsigned int def = 0) const
Definition at line 5560 of file pugixml.cpp.
References _data(), get_value_uint(), and pugi::xml_node_struct::value.
data() [1/2]
PUGI__FN xml_node pugi::xml_text::data () const
Definition at line 5699 of file pugixml.cpp.
References _data(), and xml_node.
data() [2/2]
xml_node pugi::xml_text::data () const
empty() [1/2]
PUGI__FN bool pugi::xml_text::empty () const
Definition at line 5534 of file pugixml.cpp.
References _data().
empty() [2/2]
bool pugi::xml_text::empty () const
get() [1/2]
const PUGI__FN char_t * pugi::xml_text::get () const
Definition at line 5539 of file pugixml.cpp.
References _data(), PUGIXML_TEXT, and pugi::xml_node_struct::value.
get() [2/2]
const char_t* pugi::xml_text::get () const
operator unspecified_bool_type() [1/2]
PUGI__FN pugi::xml_text::operator xml_text::unspecified_bool_type () const
Definition at line 5524 of file pugixml.cpp.
References _data(), and pugi::unspecified_bool_xml_text().
operator unspecified_bool_type() [2/2]
pugi::xml_text::operator unspecified_bool_type () const
operator!() [1/2]
PUGI__FN bool pugi::xml_text::operator! () const
Definition at line 5529 of file pugixml.cpp.
References _data().
operator!() [2/2]
bool pugi::xml_text::operator! () const
operator=() [1/10]
xml_text& pugi::xml_text::operator= (bool rhs)
operator=() [2/10]
PUGI__FN xml_text & pugi::xml_text::operator= (bool rhs)
Definition at line 5679 of file pugixml.cpp.
References set().
operator=() [3/10]
PUGI__FN xml_text & pugi::xml_text::operator= (const char_t * rhs)
Definition at line 5655 of file pugixml.cpp.
References set().
operator=() [4/10]
xml_text& pugi::xml_text::operator= (const char_t * rhs)
operator=() [5/10]
PUGI__FN xml_text & pugi::xml_text::operator= (double rhs)
Definition at line 5673 of file pugixml.cpp.
References set().
operator=() [6/10]
xml_text& pugi::xml_text::operator= (double rhs)
operator=() [7/10]
PUGI__FN xml_text & pugi::xml_text::operator= (int rhs)
Definition at line 5661 of file pugixml.cpp.
References set().
operator=() [8/10]
xml_text& pugi::xml_text::operator= (int rhs)
operator=() [9/10]
PUGI__FN xml_text & pugi::xml_text::operator= (unsigned int rhs)
Definition at line 5667 of file pugixml.cpp.
References set().
operator=() [10/10]
xml_text& pugi::xml_text::operator= (unsigned int rhs)
set() [1/10]
bool pugi::xml_text::set (bool rhs)
set() [2/10]
PUGI__FN bool pugi::xml_text::set (bool rhs)
Definition at line 5632 of file pugixml.cpp.
References _data_new(), pugi::xml_node_struct::header, set_value_convert(), pugi::xml_node_struct::value, and xml_memory_page_value_allocated_mask.
set() [3/10]
bool pugi::xml_text::set (const char_t * rhs)
set() [4/10]
PUGI__FN bool pugi::xml_text::set (const char_t * rhs)
Definition at line 5604 of file pugixml.cpp.
References _data_new(), pugi::xml_node_struct::header, strcpy_insitu(), pugi::xml_node_struct::value, and xml_memory_page_value_allocated_mask.
Referenced by operator=().
set() [5/10]
bool pugi::xml_text::set (double rhs)
set() [6/10]
PUGI__FN bool pugi::xml_text::set (double rhs)
Definition at line 5625 of file pugixml.cpp.
References _data_new(), pugi::xml_node_struct::header, set_value_convert(), pugi::xml_node_struct::value, and xml_memory_page_value_allocated_mask.
set() [7/10]
bool pugi::xml_text::set (int rhs)
set() [8/10]
PUGI__FN bool pugi::xml_text::set (int rhs)
Definition at line 5611 of file pugixml.cpp.
References _data_new(), pugi::xml_node_struct::header, set_value_convert(), pugi::xml_node_struct::value, and xml_memory_page_value_allocated_mask.
set() [9/10]
PUGI__FN bool pugi::xml_text::set (unsigned int rhs)
Definition at line 5618 of file pugixml.cpp.
References _data_new(), pugi::xml_node_struct::header, set_value_convert(), pugi::xml_node_struct::value, and xml_memory_page_value_allocated_mask.
set() [10/10]
bool pugi::xml_text::set (unsigned int rhs)
Friends And Related Function Documentation
xml_node
xml_node friend
Definition at line 639 of file pugixml.hpp.
Referenced by _data_new(), and data().
Member Data Documentation
_root
xml_node_struct * pugi::xml_text::_root private
Definition at line 641 of file pugixml.hpp.
Referenced by _data(), and _data_new().
The documentation for this class was generated from the following files:
include/etiss/fault/xml/pugixml.hpp
/home/runner/work/etiss/etiss/src/fault/xml/pugixml.cpp