ETISS 0.8.0: etiss::RegisterPart Class Reference
etiss::RegisterPart Class Reference
abstract description of needed or affected register bits.
#include <CodePart.h>
Public Member Functions
RegisterPart ()
RegisterPart (const std::string &name, unsigned registerWidth, etiss::uintMax bits=(uintMax)((intMax) -1))
RegisterPart (const RegisterPart &cpy)
bool matches (const RegisterPart &rp) const
check for equality
bool contains (const RegisterPart &rp) const
check if passed RegisterPart is a subset of relevant bits of the same register
void applyShadow (const RegisterPart &rp) const
this is not a const function in the usual sense.
void merge (const RegisterPart &rp) const
this is not a const function in the usual sense.
void intersect (const RegisterPart &rp) const
this is not a const function in the usual sense.
bool maskedBy (const RegisterPart &rp) const
const std::string & getName () const
const etiss::uintMax & getAffectedBits () const
const unsigned & getRegisterWidth () const
bool isEmpty () const
true if unnamed or no relevant bits
bool operator< (const RegisterPart &other) const
bool operator== (const RegisterPart &other) const
same as matches(const RegisterPart & other)
RegisterPart ()
RegisterPart (const std::string &name, unsigned registerWidth, etiss::uintMax bits=(uintMax)((intMax) -1))
RegisterPart (const RegisterPart &cpy)
bool matches (const RegisterPart &rp) const
check for equality
bool contains (const RegisterPart &rp) const
check if passed RegisterPart is a subset of relevant bits of the same register
void applyShadow (const RegisterPart &rp) const
this is not a const function in the usual sense.
void merge (const RegisterPart &rp) const
this is not a const function in the usual sense.
void intersect (const RegisterPart &rp) const
this is not a const function in the usual sense.
bool maskedBy (const RegisterPart &rp) const
const std::string & getName () const
const etiss::uintMax & getAffectedBits () const
const unsigned & getRegisterWidth () const
bool isEmpty () const
true if unnamed or no relevant bits
bool operator< (const RegisterPart &other) const
bool operator== (const RegisterPart &other) const
same as matches(const RegisterPart & other)
Private Attributes
std::string name
etiss::uintMax bits
unsigned regWidth
Detailed Description
abstract description of needed or affected register bits.
due to special behaviour of this class when used in a set (RegisterSet) not all const functions have const character. use with caution.
@TODO For consitency width's should really be size_t
Definition at line 75 of file CodePart.h.
Constructor & Destructor Documentation
RegisterPart() [1/6]
etiss::RegisterPart::RegisterPart () inline
Definition at line 78 of file CodePart.h.
RegisterPart() [2/6]
etiss::RegisterPart::RegisterPart (const std::string & name, unsigned registerWidth, etiss::uintMax bits = (uintMax)((intMax)-1)) inline
Parameters
name register name should be same as defined by the respective etiss::CPUArch instance.
registerWidth the register width in bits. must be consistet with the name and the context (e.g. cpu1 and cpu2 are allowed to have the same register with different widths).
bits relevant bits of the register (->register part).
Definition at line 85 of file CodePart.h.
References bits, and regWidth.
RegisterPart() [3/6]
etiss::RegisterPart::RegisterPart (const RegisterPart & cpy) inline
Definition at line 95 of file CodePart.h.
References bits, name, and regWidth.
RegisterPart() [4/6]
etiss::RegisterPart::RegisterPart () inline
Definition at line 78 of file CodePart.h.
RegisterPart() [5/6]
etiss::RegisterPart::RegisterPart (const std::string & name, unsigned registerWidth, etiss::uintMax bits = (uintMax)((intMax)-1)) inline
Parameters
name register name should be same as defined by the respective etiss::CPUArch instance.
registerWidth the register width in bits. must be consistet with the name and the context (e.g. cpu1 and cpu2 are allowed to have the same register with different widths).
bits relevant bits of the register (->register part).
Definition at line 85 of file CodePart.h.
References bits, and regWidth.
RegisterPart() [6/6]
etiss::RegisterPart::RegisterPart (const RegisterPart & cpy) inline
Definition at line 95 of file CodePart.h.
References bits, and regWidth.
Member Function Documentation
applyShadow() [1/2]
void etiss::RegisterPart::applyShadow (const RegisterPart & rp) const inline
this is not a const function in the usual sense.
Definition at line 142 of file CodePart.h.
References bits, and name.
applyShadow() [2/2]
void etiss::RegisterPart::applyShadow (const RegisterPart & rp) const inline
this is not a const function in the usual sense.
Definition at line 142 of file CodePart.h.
References bits, and name.
contains() [1/2]
bool etiss::RegisterPart::contains (const RegisterPart & rp) const inline
check if passed RegisterPart is a subset of relevant bits of the same register
Definition at line 124 of file CodePart.h.
References bits, isEmpty(), name, and regWidth.
Referenced by maskedBy().
contains() [2/2]
bool etiss::RegisterPart::contains (const RegisterPart & rp) const inline
check if passed RegisterPart is a subset of relevant bits of the same register
Definition at line 124 of file CodePart.h.
References bits, isEmpty(), and regWidth.
getAffectedBits() [1/2]
const etiss::uintMax& etiss::RegisterPart::getAffectedBits () const inline
Definition at line 165 of file CodePart.h.
References bits.
getAffectedBits() [2/2]
const etiss::uintMax& etiss::RegisterPart::getAffectedBits () const inline
Definition at line 165 of file CodePart.h.
References bits.
getName() [1/2]
const std::string& etiss::RegisterPart::getName () const inline
Definition at line 164 of file CodePart.h.
References name.
getName() [2/2]
const std::string& etiss::RegisterPart::getName () const inline
Definition at line 164 of file CodePart.h.
References name.
Referenced by etiss::RegisterSet::lex_compare::operator()().
getRegisterWidth() [1/2]
const unsigned& etiss::RegisterPart::getRegisterWidth () const inline
Definition at line 166 of file CodePart.h.
References regWidth.
getRegisterWidth() [2/2]
const unsigned& etiss::RegisterPart::getRegisterWidth () const inline
Definition at line 166 of file CodePart.h.
References regWidth.
intersect() [1/2]
void etiss::RegisterPart::intersect (const RegisterPart & rp) const inline
this is not a const function in the usual sense.
Definition at line 158 of file CodePart.h.
References bits, and name.
intersect() [2/2]
void etiss::RegisterPart::intersect (const RegisterPart & rp) const inline
this is not a const function in the usual sense.
Definition at line 158 of file CodePart.h.
References bits, and name.
isEmpty() [1/2]
bool etiss::RegisterPart::isEmpty () const inline
true if unnamed or no relevant bits
Definition at line 170 of file CodePart.h.
References bits, and name.
Referenced by etiss::RegisterSet::add(), contains(), matches(), and operator<().
isEmpty() [2/2]
bool etiss::RegisterPart::isEmpty () const inline
true if unnamed or no relevant bits
Definition at line 170 of file CodePart.h.
References bits, and name.
maskedBy() [1/2]
bool etiss::RegisterPart::maskedBy (const RegisterPart & rp) const inline
Definition at line 163 of file CodePart.h.
maskedBy() [2/2]
bool etiss::RegisterPart::maskedBy (const RegisterPart & rp) const inline
Definition at line 163 of file CodePart.h.
References contains().
matches() [1/2]
bool etiss::RegisterPart::matches (const RegisterPart & rp) const inline
check for equality
Definition at line 106 of file CodePart.h.
References bits, isEmpty(), name, and regWidth.
Referenced by operator==().
matches() [2/2]
bool etiss::RegisterPart::matches (const RegisterPart & rp) const inline
check for equality
Definition at line 106 of file CodePart.h.
References bits, isEmpty(), and regWidth.
merge() [1/2]
void etiss::RegisterPart::merge (const RegisterPart & rp) const inline
this is not a const function in the usual sense.
Definition at line 150 of file CodePart.h.
References bits, and name.
merge() [2/2]
void etiss::RegisterPart::merge (const RegisterPart & rp) const inline
this is not a const function in the usual sense.
Definition at line 150 of file CodePart.h.
References bits, and name.
operator<() [1/2]
bool etiss::RegisterPart::operator< (const RegisterPart & other) const inline
Definition at line 171 of file CodePart.h.
References bits, isEmpty(), name, and regWidth.
operator<() [2/2]
bool etiss::RegisterPart::operator< (const RegisterPart & other) const inline
Definition at line 171 of file CodePart.h.
References bits, isEmpty(), name, and regWidth.
operator==() [1/2]
bool etiss::RegisterPart::operator== (const RegisterPart & other) const inline
same as matches(const RegisterPart & other)
Definition at line 189 of file CodePart.h.
References matches().
operator==() [2/2]
bool etiss::RegisterPart::operator== (const RegisterPart & other) const inline
same as matches(const RegisterPart & other)
Definition at line 189 of file CodePart.h.
References matches().
Member Data Documentation
bits
etiss::uintMax etiss::RegisterPart::bits mutable private
Definition at line 193 of file CodePart.h.
Referenced by applyShadow(), contains(), getAffectedBits(), intersect(), isEmpty(), matches(), merge(), operator<(), and RegisterPart().
name
std::string etiss::RegisterPart::name private
Definition at line 192 of file CodePart.h.
Referenced by applyShadow(), contains(), getName(), intersect(), isEmpty(), matches(), merge(), operator<(), and RegisterPart().
regWidth
unsigned etiss::RegisterPart::regWidth private
Definition at line 194 of file CodePart.h.
Referenced by contains(), getRegisterWidth(), matches(), operator<(), and RegisterPart().
The documentation for this class was generated from the following file:
include/etiss/CodePart.h