ETISS 0.8.0: etiss::mm::PTEFormat Class Reference
etiss::mm::PTEFormat Class Reference
#include <PTEFormat.h>
Public Member Functions
void AddBitField (std::string name, uint32_t begin, uint32_t end)
Called only by PTEFormatBuilder.
void DumpBitFild (std::string name)
Dump the details of the bit field according to given name.
void Dump ()
Dump the details of the whole PTE format.
uint32_t GetPTELength () const
PTEFormatMap & GetFormatMap ()
void AddBitField (std::string name, uint32_t begin, uint32_t end)
Called only by PTEFormatBuilder.
void DumpBitFild (std::string name)
Dump the details of the bit field according to given name.
void Dump ()
Dump the details of the whole PTE format.
uint32_t GetPTELength () const
PTEFormatMap & GetFormatMap ()
Static Public Member Functions
static PTEFormat & Instance ()
Get the singleton instance.
static PTEFormat & Instance ()
Get the singleton instance.
Private Member Functions
PTEFormat ()
PTEFormat ()
Private Attributes
PTEFormatMap format_map_
uint32_t pte_len_
Detailed Description
Definition at line 64 of file PTEFormat.h.
Constructor & Destructor Documentation
PTEFormat() [1/2]
etiss::mm::PTEFormat::PTEFormat () inline private
Definition at line 98 of file PTEFormat.h.
Referenced by Instance().
PTEFormat() [2/2]
etiss::mm::PTEFormat::PTEFormat () inline private
Definition at line 98 of file PTEFormat.h.
Member Function Documentation
AddBitField() [1/2]
void etiss::mm::PTEFormat::AddBitField (std::string name, uint32_t begin, uint32_t end)
Called only by PTEFormatBuilder.
See also
etiss::mm::PTEFormatBuilder
Definition at line 57 of file PTEFormat.cpp.
References format_map_, name, and pte_len_.
Referenced by etiss::mm::PTEFormatBuilder::AddFlag(), etiss::mm::PTEFormatBuilder::AddPageOffset(), and etiss::mm::PTEFormatBuilder::AddPPNBitField().
AddBitField() [2/2]
void etiss::mm::PTEFormat::AddBitField (std::string name, uint32_t begin, uint32_t end)
Called only by PTEFormatBuilder.
See also
etiss::mm::PTEFormatBuilder
Dump() [1/2]
void etiss::mm::PTEFormat::Dump ()
Dump the details of the whole PTE format.
Definition at line 81 of file PTEFormat.cpp.
References format_map_.
Referenced by etiss::mm::PTE::ClearFlagByName(), etiss::mm::PTE::GetByName(), etiss::mm::PTE::SetFlagByName(), and etiss::mm::PTE::Update().
Dump() [2/2]
void etiss::mm::PTEFormat::Dump ()
Dump the details of the whole PTE format.
DumpBitFild() [1/2]
void etiss::mm::PTEFormat::DumpBitFild (std::string name)
Dump the details of the bit field according to given name.
DumpBitFild() [2/2]
void etiss::mm::PTEFormat::DumpBitFild (std::string name)
Dump the details of the bit field according to given name.
Definition at line 66 of file PTEFormat.cpp.
References format_map_, and name.
Referenced by etiss::mm::PTE::Dump().
GetFormatMap() [1/2]
PTEFormatMap& etiss::mm::PTEFormat::GetFormatMap () inline
Definition at line 95 of file PTEFormat.h.
References format_map_.
GetFormatMap() [2/2]
PTEFormatMap& etiss::mm::PTEFormat::GetFormatMap () inline
Definition at line 95 of file PTEFormat.h.
References format_map_.
Referenced by etiss::mm::PTE::ClearFlagByName(), etiss::mm::PTE::Dump(), etiss::mm::PTE::GetByName(), etiss::mm::PTE::SetFlagByName(), etiss::mm::MMU::Translate(), and etiss::mm::PTE::Update().
GetPTELength() [1/2]
uint32_t etiss::mm::PTEFormat::GetPTELength () const inline
Definition at line 93 of file PTEFormat.h.
References pte_len_.
GetPTELength() [2/2]
uint32_t etiss::mm::PTEFormat::GetPTELength () const inline
Definition at line 93 of file PTEFormat.h.
References pte_len_.
Referenced by etiss::mm::PTE::Dump(), and etiss::mm::PTE::Update().
Instance() [1/2]
static PTEFormat& etiss::mm::PTEFormat::Instance () inline static
Get the singleton instance.
Definition at line 70 of file PTEFormat.h.
References PTEFormat().
Referenced by etiss::mm::PTE::ClearFlagByName(), etiss::mm::PTE::Dump(), etiss::mm::PTE::GetByName(), etiss::mm::PTEFormatBuilder::Instance(), etiss::mm::PTE::SetFlagByName(), etiss::mm::MMU::Translate(), and etiss::mm::PTE::Update().
Instance() [2/2]
static PTEFormat& etiss::mm::PTEFormat::Instance () inline static
Get the singleton instance.
Definition at line 70 of file PTEFormat.h.
References PTEFormat().
Member Data Documentation
format_map_
PTEFormatMap etiss::mm::PTEFormat::format_map_ private
Definition at line 99 of file PTEFormat.h.
Referenced by AddBitField(), Dump(), DumpBitFild(), and GetFormatMap().
pte_len_
uint32_t etiss::mm::PTEFormat::pte_len_ private
Definition at line 100 of file PTEFormat.h.
Referenced by AddBitField(), and GetPTELength().
The documentation for this class was generated from the following files:
include/etiss/mm/PTEFormat.h
/home/runner/work/etiss/etiss/src/mm/PTEFormat.cpp