ETISS 0.8.0: pugi::xml_tree_walker Class Reference
pugi::xml_tree_walker Class Reference abstract
#include <pugixml.hpp>
Public Member Functions
xml_tree_walker ()
virtual ~xml_tree_walker ()
virtual bool begin (xml_node &node)
virtual bool for_each (xml_node &node)=0
virtual bool end (xml_node &node)
xml_tree_walker ()
virtual ~xml_tree_walker ()
virtual bool begin (xml_node &node)
virtual bool for_each (xml_node &node)=0
virtual bool end (xml_node &node)
Protected Member Functions
int depth () const
int depth () const
Private Attributes
int _depth
Friends
class xml_node
Detailed Description
Definition at line 847 of file pugixml.hpp.
Constructor & Destructor Documentation
xml_tree_walker() [1/2]
PUGI__FN pugi::xml_tree_walker::xml_tree_walker ()
Definition at line 4313 of file pugixml.cpp.
~xml_tree_walker() [1/2]
PUGI__FN pugi::xml_tree_walker::~xml_tree_walker () virtual
Definition at line 4315 of file pugixml.cpp.
xml_tree_walker() [2/2]
pugi::xml_tree_walker::xml_tree_walker ()
~xml_tree_walker() [2/2]
virtual pugi::xml_tree_walker::~xml_tree_walker () virtual
Member Function Documentation
begin() [1/2]
PUGI__FN bool pugi::xml_tree_walker::begin (xml_node & node) virtual
Definition at line 4322 of file pugixml.cpp.
Referenced by pugi::xml_node::traverse().
begin() [2/2]
virtual bool pugi::xml_tree_walker::begin (xml_node & node) virtual
depth() [1/2]
PUGI__FN int pugi::xml_tree_walker::depth () const protected
Definition at line 4317 of file pugixml.cpp.
References _depth.
depth() [2/2]
int pugi::xml_tree_walker::depth () const protected
end() [1/2]
PUGI__FN bool pugi::xml_tree_walker::end (xml_node & node) virtual
Definition at line 4327 of file pugixml.cpp.
Referenced by pugi::xml_node::traverse().
end() [2/2]
virtual bool pugi::xml_tree_walker::end (xml_node & node) virtual
for_each() [1/2]
virtual bool pugi::xml_tree_walker::for_each (xml_node & node) pure virtual
Referenced by pugi::xml_node::traverse().
for_each() [2/2]
virtual bool pugi::xml_tree_walker::for_each (xml_node & node) pure virtual
Friends And Related Function Documentation
xml_node
xml_node friend
Definition at line 849 of file pugixml.hpp.
Member Data Documentation
_depth
int pugi::xml_tree_walker::_depth private
Definition at line 852 of file pugixml.hpp.
Referenced by depth(), and pugi::xml_node::traverse().
The documentation for this class was generated from the following files:
include/etiss/fault/xml/pugixml.hpp
/home/runner/work/etiss/etiss/src/fault/xml/pugixml.cpp