ETISS 0.8.0: etiss::LibraryInterface Class Reference
etiss::LibraryInterface Class Reference
interface class for libraries.
#include <LibraryInterface.h>
Public Member Functions
LibraryInterface (std::string name)
virtual ~LibraryInterface ()
virtual std::string versionInfo ()
simple version info string. intended to present information in a human readable way.
virtual unsigned countPlugins ()
virtual unsigned countCPUArchs ()
virtual unsigned countJITs ()
virtual std::string nameJIT (unsigned index)
virtual std::string namePlugin (unsigned index)
virtual std::string nameCPUArch (unsigned index)
virtual etiss::JIT * createJIT (unsigned index, std::map< std::string, std::string > options=std::map< std::string, std::string >())
virtual etiss::CPUArch * createCPUArch (unsigned index, std::map< std::string, std::string > options=std::map< std::string, std::string >())
virtual etiss::Plugin * createPlugin (unsigned index, std::map< std::string, std::string > options=std::map< std::string, std::string >())
virtual void deleteJIT (etiss::JIT *)
virtual void deleteCPUArch (etiss::CPUArch *)
virtual void deletePlugin (etiss::Plugin *)
virtual bool isEmpty ()
returns true if this library provides nothing
virtual const std::string & getName ()
LibraryInterface (std::string name)
virtual ~LibraryInterface ()
virtual std::string versionInfo ()
simple version info string. intended to present information in a human readable way.
virtual unsigned countPlugins ()
virtual unsigned countCPUArchs ()
virtual unsigned countJITs ()
virtual std::string nameJIT (unsigned index)
virtual std::string namePlugin (unsigned index)
virtual std::string nameCPUArch (unsigned index)
virtual etiss::JIT * createJIT (unsigned index, std::map< std::string, std::string > options=std::map< std::string, std::string >())
virtual etiss::CPUArch * createCPUArch (unsigned index, std::map< std::string, std::string > options=std::map< std::string, std::string >())
virtual etiss::Plugin * createPlugin (unsigned index, std::map< std::string, std::string > options=std::map< std::string, std::string >())
virtual void deleteJIT (etiss::JIT *)
virtual void deleteCPUArch (etiss::CPUArch *)
virtual void deletePlugin (etiss::Plugin *)
virtual bool isEmpty ()
returns true if this library provides nothing
virtual const std::string & getName ()
Static Public Member Functions
static std::shared_ptr< LibraryInterface > openSharedLibrary (std::string path, std::string name)
static std::shared_ptr< LibraryInterface > openIntegratedLibrary ()
static unsigned getCurrentLibraryVersion ()
static std::shared_ptr< LibraryInterface > openSharedLibrary (std::string path, std::string name)
static std::shared_ptr< LibraryInterface > openIntegratedLibrary ()
static unsigned getCurrentLibraryVersion ()
Private Attributes
std::string name_
Detailed Description
interface class for libraries.
override functions as needed.
it is neccessary to override all function of the same category. e.g. for plugins: countPlugins(),namePlugin(1),createPlugin(1),deletePlugin(1). isEmpty() uses countXXXXXX() functions to assess its return value and doesn't need to be implemented.
to implement a dynamic library do NOT use this class. Refer to etiss/helper/CPUArchLibrary.h , etiss/helper/JITLibrary.h , etiss/helper/PluginLibrary.h for library functions to implement and use etiss::LibraryInterface::openSharedLibrary to load the dynamic library
Definition at line 91 of file LibraryInterface.h.
Constructor & Destructor Documentation
LibraryInterface() [1/2]
LibraryInterface::LibraryInterface (std::string name)
Parameters
name name of the library
path location of the library and its files
Definition at line 66 of file LibraryInterface.cpp.
~LibraryInterface() [1/2]
LibraryInterface::~LibraryInterface () virtual
Definition at line 67 of file LibraryInterface.cpp.
LibraryInterface() [2/2]
etiss::LibraryInterface::LibraryInterface (std::string name)
Parameters
name name of the library
path location of the library and its files
~LibraryInterface() [2/2]
virtual etiss::LibraryInterface::~LibraryInterface () virtual
Member Function Documentation
countCPUArchs() [1/2]
unsigned LibraryInterface::countCPUArchs () virtual
Reimplemented in IntegratedLibrary.
Definition at line 78 of file LibraryInterface.cpp.
Referenced by etiss::getCPUArch(), and isEmpty().
countCPUArchs() [2/2]
virtual unsigned etiss::LibraryInterface::countCPUArchs () virtual
Reimplemented in IntegratedLibrary.
countJITs() [1/2]
unsigned LibraryInterface::countJITs () virtual
Reimplemented in IntegratedLibrary.
Definition at line 82 of file LibraryInterface.cpp.
Referenced by etiss::addLibrary(), etiss::getJIT(), and isEmpty().
countJITs() [2/2]
virtual unsigned etiss::LibraryInterface::countJITs () virtual
Reimplemented in IntegratedLibrary.
countPlugins() [1/2]
virtual unsigned etiss::LibraryInterface::countPlugins () virtual
Reimplemented in IntegratedLibrary.
countPlugins() [2/2]
unsigned LibraryInterface::countPlugins () virtual
Reimplemented in IntegratedLibrary.
Definition at line 74 of file LibraryInterface.cpp.
Referenced by etiss::getPlugin(), and isEmpty().
createCPUArch() [1/2]
etiss::CPUArch * LibraryInterface::createCPUArch (unsigned index, std::map< std::string, std::string > options = std::map<std::string, std::string>()) virtual
Reimplemented in IntegratedLibrary.
Definition at line 104 of file LibraryInterface.cpp.
Referenced by etiss::getCPUArch().
createCPUArch() [2/2]
virtual etiss::CPUArch* etiss::LibraryInterface::createCPUArch (unsigned index, std::map< std::string, std::string > options = std::map< std::string, std::string >()) virtual
Reimplemented in IntegratedLibrary.
createJIT() [1/2]
etiss::JIT * LibraryInterface::createJIT (unsigned index, std::map< std::string, std::string > options = std::map<std::string, std::string>()) virtual
Reimplemented in IntegratedLibrary.
Definition at line 100 of file LibraryInterface.cpp.
Referenced by etiss::getJIT().
createJIT() [2/2]
virtual etiss::JIT* etiss::LibraryInterface::createJIT (unsigned index, std::map< std::string, std::string > options = std::map< std::string, std::string >()) virtual
Reimplemented in IntegratedLibrary.
createPlugin() [1/2]
etiss::Plugin * LibraryInterface::createPlugin (unsigned index, std::map< std::string, std::string > options = std::map<std::string, std::string>()) virtual
Reimplemented in IntegratedLibrary.
Definition at line 108 of file LibraryInterface.cpp.
Referenced by etiss::getPlugin().
createPlugin() [2/2]
virtual etiss::Plugin* etiss::LibraryInterface::createPlugin (unsigned index, std::map< std::string, std::string > options = std::map< std::string, std::string >()) virtual
Reimplemented in IntegratedLibrary.
deleteCPUArch() [1/2]
void LibraryInterface::deleteCPUArch (etiss::CPUArch *) virtual
Reimplemented in IntegratedLibrary.
Definition at line 114 of file LibraryInterface.cpp.
Referenced by etiss::getCPUArch().
deleteCPUArch() [2/2]
virtual void etiss::LibraryInterface::deleteCPUArch (etiss::CPUArch *) virtual
Reimplemented in IntegratedLibrary.
deleteJIT() [1/2]
void LibraryInterface::deleteJIT (etiss::JIT *) virtual
Reimplemented in IntegratedLibrary.
Definition at line 113 of file LibraryInterface.cpp.
Referenced by etiss::getJIT().
deleteJIT() [2/2]
virtual void etiss::LibraryInterface::deleteJIT (etiss::JIT *) virtual
Reimplemented in IntegratedLibrary.
deletePlugin() [1/2]
virtual void etiss::LibraryInterface::deletePlugin (etiss::Plugin *) virtual
Reimplemented in IntegratedLibrary.
deletePlugin() [2/2]
void LibraryInterface::deletePlugin (etiss::Plugin *) virtual
Reimplemented in IntegratedLibrary.
Definition at line 115 of file LibraryInterface.cpp.
Referenced by etiss::getPlugin().
getCurrentLibraryVersion() [1/2]
unsigned etiss::LibraryInterface::getCurrentLibraryVersion () static
Definition at line 152 of file IntegratedLibrary.cpp.
getCurrentLibraryVersion() [2/2]
static unsigned etiss::LibraryInterface::getCurrentLibraryVersion () static
getName() [1/2]
virtual const std::string& etiss::LibraryInterface::getName () virtual
Returns
name of this library
getName() [2/2]
const std::string & LibraryInterface::getName () virtual
Returns
name of this library
Definition at line 122 of file LibraryInterface.cpp.
References name_.
Referenced by etiss::getCPUArch(), etiss::getJIT(), etiss::getPlugin(), and etiss::shutdown().
isEmpty() [1/2]
virtual bool etiss::LibraryInterface::isEmpty () virtual
returns true if this library provides nothing
isEmpty() [2/2]
bool LibraryInterface::isEmpty () virtual
returns true if this library provides nothing
Definition at line 117 of file LibraryInterface.cpp.
References countCPUArchs(), countJITs(), and countPlugins().
Referenced by etiss::getCPUArch(), etiss::getJIT(), and etiss::getPlugin().
nameCPUArch() [1/2]
virtual std::string etiss::LibraryInterface::nameCPUArch (unsigned index) virtual
Reimplemented in IntegratedLibrary.
nameCPUArch() [2/2]
std::string LibraryInterface::nameCPUArch (unsigned index) virtual
Reimplemented in IntegratedLibrary.
Definition at line 95 of file LibraryInterface.cpp.
Referenced by etiss::getCPUArch().
nameJIT() [1/2]
virtual std::string etiss::LibraryInterface::nameJIT (unsigned index) virtual
Reimplemented in IntegratedLibrary.
nameJIT() [2/2]
std::string LibraryInterface::nameJIT (unsigned index) virtual
Reimplemented in IntegratedLibrary.
Definition at line 87 of file LibraryInterface.cpp.
Referenced by etiss::addLibrary(), and etiss::getJIT().
namePlugin() [1/2]
virtual std::string etiss::LibraryInterface::namePlugin (unsigned index) virtual
Reimplemented in IntegratedLibrary.
namePlugin() [2/2]
std::string LibraryInterface::namePlugin (unsigned index) virtual
Reimplemented in IntegratedLibrary.
Definition at line 91 of file LibraryInterface.cpp.
Referenced by etiss::getPlugin().
openIntegratedLibrary() [1/2]
std::shared_ptr< etiss::LibraryInterface > etiss::LibraryInterface::openIntegratedLibrary () static
Definition at line 122 of file IntegratedLibraryHelper.cpp.
Referenced by etiss_initialize().
openIntegratedLibrary() [2/2]
static std::shared_ptr<LibraryInterface> etiss::LibraryInterface::openIntegratedLibrary () static
openSharedLibrary() [1/2]
std::shared_ptr< LibraryInterface > LibraryInterface::openSharedLibrary (std::string path, std::string name) static
Definition at line 527 of file LibraryInterface.cpp.
References etiss::ERROR, ETISS_SRCLOC, ETISS_VARVAL, etiss::INFO, etiss::log(), name, etiss::VERBOSE, and etiss::WARNING.
Referenced by etiss::loadLibrary().
openSharedLibrary() [2/2]
static std::shared_ptr<LibraryInterface> etiss::LibraryInterface::openSharedLibrary (std::string path, std::string name) static
versionInfo() [1/2]
virtual std::string etiss::LibraryInterface::versionInfo () virtual
simple version info string. intended to present information in a human readable way.
Reimplemented in IntegratedLibrary.
versionInfo() [2/2]
std::string LibraryInterface::versionInfo () virtual
simple version info string. intended to present information in a human readable way.
Reimplemented in IntegratedLibrary.
Definition at line 69 of file LibraryInterface.cpp.
Member Data Documentation
name_
std::string etiss::LibraryInterface::name_ private
Definition at line 145 of file LibraryInterface.h.
Referenced by getName().
The documentation for this class was generated from the following files:
include/etiss/LibraryInterface.h
/home/runner/work/etiss/etiss/src/IntegratedLibrary.cpp
/home/runner/work/etiss/etiss/src/IntegratedLibraryHelper.cpp
/home/runner/work/etiss/etiss/src/LibraryInterface.cpp