ETISS 0.8.0: etiss::instr::Instruction Class Reference
etiss::instr::Instruction Class Reference
holds information and translation callbacks for an instruction.
#include <Instruction.h>
Public Member Functions
Instruction (const OPCode &opc, const std::string &name)
template<typename T , typename = typename std::enable_if<std::is_integral<T>::value, T>::type>
Instruction (unsigned width, const T code, const T mask, const std::string &name)
virtual void compile (const std::map< const OPCode *, Instruction *, etiss::instr::less > &instrmap_, const BitArray &used, bool &ok, std::list< std::string > &warnings, std::list< std::string > &errors)
called by InstructionSet::compile() calls Node::compile() of sub nodes
virtual Instruction * resolve (BitArray &instr)
performs a lookup for the matching Instruction for the passed instruction in the bit array.
virtual bool isInstruction ()
returns true if this object is an instance of etiss::instr::Instruction
virtual std::string print (std::string indent, I pos, unsigned pfillwidth, bool printunused=false)
recursive print function to produce a human readable text that represents the structure of this node and sub nodes
bool addCallback (std::function< bool(BitArray &, etiss::CodeSet &, InstructionContext &)> callback, uint32_t builtinGroups, const std::set< uint32_t > &groups=std::set< uint32_t >())
bool translate (BitArray &, CodeSet &cs, InstructionContext &context)
uint32_t & presentBuiltinGroups ()
std::set< uint32_t > & presentGroups ()
std::string printASM (BitArray &)
void setASMPrinter (std::function< std::string(BitArray &, Instruction &)> printer)
std::string toString () const
Instruction (const OPCode &opc, const std::string &name)
template<typename T , typename = typename std::enable_if<std::is_integral<T>::value, T>::type>
Instruction (unsigned width, const T code, const T mask, const std::string &name)
virtual void compile (const std::map< const OPCode *, Instruction *, etiss::instr::less > &instrmap_, const BitArray &used, bool &ok, std::list< std::string > &warnings, std::list< std::string > &errors)
called by InstructionSet::compile() calls Node::compile() of sub nodes
virtual Instruction * resolve (BitArray &instr)
performs a lookup for the matching Instruction for the passed instruction in the bit array.
virtual bool isInstruction ()
returns true if this object is an instance of etiss::instr::Instruction
virtual std::string print (std::string indent, I pos, unsigned pfillwidth, bool printunused=false)
recursive print function to produce a human readable text that represents the structure of this node and sub nodes
bool addCallback (std::function< bool(BitArray &, etiss::CodeSet &, InstructionContext &)> callback, uint32_t builtinGroups, const std::set< uint32_t > &groups=std::set< uint32_t >())
bool translate (BitArray &, CodeSet &cs, InstructionContext &context)
uint32_t & presentBuiltinGroups ()
std::set< uint32_t > & presentGroups ()
std::string printASM (BitArray &)
void setASMPrinter (std::function< std::string(BitArray &, Instruction &)> printer)
std::string toString () const
Public Member Functions inherited from etiss::instr::Node
Node ()
ctor
virtual ~Node ()
dtor
Node ()
ctor
virtual ~Node ()
dtor
Public Member Functions inherited from etiss::ToString
ToString ()
virtual ~ToString ()
ToString ()
virtual ~ToString ()
Static Public Member Functions
static std::string printASMSimple (BitArray &ba, Instruction &instr)
static std::string printASMSimple (BitArray &ba, Instruction &instr)
Public Attributes
const etiss_del_como(Instruction) enum class BUILTINGROUP OPCode opc_
const std::string name_
Private Attributes
std::list< std::tuple< std::function< bool(BitArray &, etiss::CodeSet &, InstructionContext &)>, uint32_t, std::set< uint32_t > > > callbacks_
uint32_t builtinGroups_
std::set< uint32_t > groups_
std::function< std::string(BitArray &, Instruction &)> printer_
Detailed Description
holds information and translation callbacks for an instruction.
    Location in an instruction translation tree:
    ModedInstructionSet
        ↳ VariableInstructionSet (e.g. for mode 0)
            ↳ InstructionSet (e.g. 32 bit)
                ↳ Node
                    ↳ ...                ↳ Node
                    ↳ ...                    ↳ ...
                        ↳ Instruction
            ↳ InstructionSet (e.g. 16 bit)
Definition at line 605 of file Instruction.h.
Constructor & Destructor Documentation
Instruction() [1/4]
etiss::instr::Instruction::Instruction (const OPCode & opc, const std::string & name)
Definition at line 777 of file Instruction.cpp.
Instruction() [2/4]
template<typename T , typename = typename std::enable_if<std::is_integral<T>::value, T>::type> etiss::instr::Instruction::Instruction (unsigned width, const T code, const T mask, const std::string & name) inline
Definition at line 630 of file Instruction.h.
Instruction() [3/4]
etiss::instr::Instruction::Instruction (const OPCode & opc, const std::string & name)
Instruction() [4/4]
template<typename T , typename = typename std::enable_if<std::is_integral<T>::value, T>::type> etiss::instr::Instruction::Instruction (unsigned width, const T code, const T mask, const std::string & name) inline
Definition at line 630 of file Instruction.h.
Member Function Documentation
addCallback() [1/2]
bool etiss::instr::Instruction::addCallback (std::function< bool(BitArray &, etiss::CodeSet &, InstructionContext &)> callback, uint32_t builtinGroups, const std::set< uint32_t > & groups = std::set<uint32_t>())
Definition at line 809 of file Instruction.cpp.
References builtinGroups_, callbacks_, groups_, etiss::log(), and etiss::VERBOSE.
Referenced by etiss::instr::InstructionDefinition::addTo(), etiss::plugin::PrintInstruction::finalizeInstrSet(), etiss::plugin::VariableValueLogger::finalizeInstrSet(), etiss::plugin::InstructionAccurateCallback::finalizeInstrSet(), etiss::plugin::InstructionSpecificAddressCallback::finalizeInstrSet(), getOR1200Timing(), etiss::DataSheetAccurateTiming::handleMatch_cycles(), etiss::instr::InstructionSet::InstructionSet(), and Server_finalizeInstrSet().
addCallback() [2/2]
bool etiss::instr::Instruction::addCallback (std::function< bool(BitArray &, etiss::CodeSet &, InstructionContext &)> callback, uint32_t builtinGroups, const std::set< uint32_t > & groups = std::set< uint32_t >())
compile() [1/2]
void etiss::instr::Instruction::compile (const std::map< const OPCode *, Instruction *, etiss::instr::less > & instrmap_, const BitArray & used, bool & ok, std::list< std::string > & warnings, std::list< std::string > & errors) virtual
called by InstructionSet::compile() calls Node::compile() of sub nodes
Parameters
instrmap_ a subset of instructions that will be put into/linked as sub nodes.
used bits that have already been used in previous nodes and cannot be used by this node to distinguish instruction opcodes
Reimplemented from etiss::instr::Node.
Definition at line 788 of file Instruction.cpp.
References etiss::FATALERROR, and etiss::log().
compile() [2/2]
virtual void etiss::instr::Instruction::compile (const std::map< const OPCode *, Instruction *, etiss::instr::less > & instrmap_, const BitArray & used, bool & ok, std::list< std::string > & warnings, std::list< std::string > & errors) virtual
called by InstructionSet::compile() calls Node::compile() of sub nodes
Parameters
instrmap_ a subset of instructions that will be put into/linked as sub nodes.
used bits that have already been used in previous nodes and cannot be used by this node to distinguish instruction opcodes
Reimplemented from etiss::instr::Node.
isInstruction() [1/2]
bool etiss::instr::Instruction::isInstruction () virtual
returns true if this object is an instance of etiss::instr::Instruction
Reimplemented from etiss::instr::Node.
Definition at line 798 of file Instruction.cpp.
isInstruction() [2/2]
virtual bool etiss::instr::Instruction::isInstruction () virtual
returns true if this object is an instance of etiss::instr::Instruction
Reimplemented from etiss::instr::Node.
presentBuiltinGroups() [1/2]
uint32_t & etiss::instr::Instruction::presentBuiltinGroups ()
Definition at line 855 of file Instruction.cpp.
References builtinGroups_.
Referenced by CPUArch_finalizeInstrSet().
presentBuiltinGroups() [2/2]
uint32_t& etiss::instr::Instruction::presentBuiltinGroups ()
presentGroups() [1/2]
std::set< uint32_t > & etiss::instr::Instruction::presentGroups ()
Definition at line 859 of file Instruction.cpp.
References groups_.
presentGroups() [2/2]
std::set<uint32_t>& etiss::instr::Instruction::presentGroups ()
print() [1/2]
std::string etiss::instr::Instruction::print (std::string indent, I pos, unsigned pfillwidth, bool printunused = false) virtual
recursive print function to produce a human readable text that represents the structure of this node and sub nodes
See also
InstructionSet::print()
Reimplemented from etiss::instr::Node.
Definition at line 802 of file Instruction.cpp.
References name_.
print() [2/2]
virtual std::string etiss::instr::Instruction::print (std::string indent, I pos, unsigned pfillwidth, bool printunused = false) virtual
recursive print function to produce a human readable text that represents the structure of this node and sub nodes
See also
InstructionSet::print()
Reimplemented from etiss::instr::Node.
printASM() [1/2]
std::string etiss::instr::Instruction::printASM (BitArray & ba)
Definition at line 864 of file Instruction.cpp.
References printer_.
Referenced by etiss::Translation::disasm(), and etiss::plugin::PrintInstruction::finalizeInstrSet().
printASM() [2/2]
std::string etiss::instr::Instruction::printASM (BitArray &)
printASMSimple() [1/2]
std::string etiss::instr::Instruction::printASMSimple (BitArray & ba, Instruction & instr) static
Definition at line 781 of file Instruction.cpp.
References name_.
Referenced by setASMPrinter().
printASMSimple() [2/2]
static std::string etiss::instr::Instruction::printASMSimple (BitArray & ba, Instruction & instr) static
resolve() [1/2]
Instruction * etiss::instr::Instruction::resolve (BitArray & instr) virtual
performs a lookup for the matching Instruction for the passed instruction in the bit array.
Reimplemented from etiss::instr::Node.
Definition at line 794 of file Instruction.cpp.
resolve() [2/2]
virtual Instruction* etiss::instr::Instruction::resolve (BitArray & instr) virtual
performs a lookup for the matching Instruction for the passed instruction in the bit array.
Reimplemented from etiss::instr::Node.
setASMPrinter() [1/2]
void etiss::instr::Instruction::setASMPrinter (std::function< std::string(BitArray &, Instruction &)> printer)
setASMPrinter() [2/2]
void etiss::instr::Instruction::setASMPrinter (std::function< std::string(BitArray &, Instruction &)> printer)
Definition at line 869 of file Instruction.cpp.
References printASMSimple(), and printer_.
Referenced by etiss::instr::InstructionDefinition::addTo().
toString() [1/2]
std::string etiss::instr::Instruction::toString () const inline
Definition at line 647 of file Instruction.h.
References name_.
toString() [2/2]
std::string etiss::instr::Instruction::toString () const inline
Definition at line 647 of file Instruction.h.
References name_.
translate() [1/2]
bool etiss::instr::Instruction::translate (BitArray & , CodeSet & cs, InstructionContext & context)
translate() [2/2]
bool etiss::instr::Instruction::translate (BitArray & ba, CodeSet & cs, InstructionContext & context)
Definition at line 845 of file Instruction.cpp.
References callbacks_.
Referenced by etiss::Translation::translateBlock().
Member Data Documentation
builtinGroups_
uint32_t etiss::instr::Instruction::builtinGroups_ private
Definition at line 611 of file Instruction.h.
Referenced by addCallback(), and presentBuiltinGroups().
callbacks_
std::list< std::tuple< std::function< bool(BitArray &, etiss::CodeSet &, InstructionContext &)>, uint32_t, std::set< uint32_t > > > etiss::instr::Instruction::callbacks_ private
Definition at line 610 of file Instruction.h.
Referenced by addCallback(), and translate().
groups_
std::set< uint32_t > etiss::instr::Instruction::groups_ private
Definition at line 612 of file Instruction.h.
Referenced by addCallback(), and presentGroups().
name_
const std::string etiss::instr::Instruction::name_
Definition at line 624 of file Instruction.h.
Referenced by or1k_asm_print_rDAB(), or1k_asm_print_rDAI(), print(), printASMSimple(), toString(), and unknown_asm().
opc_
const etiss_del_como (Instruction) enum class BUILTINGROUP OPCode etiss::instr::Instruction::opc_
Definition at line 616 of file Instruction.h.
Referenced by etiss::instr::InstructionDefinition::addTo(), etiss::instr::AssertOnTrueCollision(), etiss::instr::InstructionSet::create(), etiss::instr::HandleCollision(), and etiss::instr::OverlappedNode::resolve().
printer_
std::function< std::string(BitArray &, Instruction &)> etiss::instr::Instruction::printer_ private
Definition at line 613 of file Instruction.h.
Referenced by printASM(), and setASMPrinter().
The documentation for this class was generated from the following files:
include/etiss/Instruction.h
/home/runner/work/etiss/etiss/src/Instruction.cpp