ETISS 0.8.0: pugi::xml_document Class Reference
pugi::xml_document Class Reference
#include <pugixml.hpp>
Public Member Functions
xml_document ()
~xml_document ()
void reset ()
void reset (const xml_document &proto)
xml_parse_result load (std::basic_istream< char, std::char_traits< char > > &stream, unsigned int options=parse_default, xml_encoding encoding=encoding_auto)
xml_parse_result load (std::basic_istream< wchar_t, std::char_traits< wchar_t > > &stream, unsigned int options=parse_default)
xml_parse_result load (const char_t *contents, unsigned int options=parse_default)
xml_parse_result load_file (const char *path, unsigned int options=parse_default, xml_encoding encoding=encoding_auto)
xml_parse_result load_file (const wchar_t *path, unsigned int options=parse_default, xml_encoding encoding=encoding_auto)
xml_parse_result load_buffer (const void *contents, size_t size, unsigned int options=parse_default, xml_encoding encoding=encoding_auto)
xml_parse_result load_buffer_inplace (void *contents, size_t size, unsigned int options=parse_default, xml_encoding encoding=encoding_auto)
xml_parse_result load_buffer_inplace_own (void *contents, size_t size, unsigned int options=parse_default, xml_encoding encoding=encoding_auto)
void save (xml_writer &writer, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default, xml_encoding encoding=encoding_auto) const
void save (std::basic_ostream< char, std::char_traits< char > > &stream, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default, xml_encoding encoding=encoding_auto) const
void save (std::basic_ostream< wchar_t, std::char_traits< wchar_t > > &stream, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default) const
bool save_file (const char *path, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default, xml_encoding encoding=encoding_auto) const
bool save_file (const wchar_t *path, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default, xml_encoding encoding=encoding_auto) const
xml_node document_element () const
xml_document ()
~xml_document ()
void reset ()
void reset (const xml_document &proto)
xml_parse_result load (std::basic_istream< char, std::char_traits< char > > &stream, unsigned int options=parse_default, xml_encoding encoding=encoding_auto)
xml_parse_result load (std::basic_istream< wchar_t, std::char_traits< wchar_t > > &stream, unsigned int options=parse_default)
xml_parse_result load (const char_t *contents, unsigned int options=parse_default)
xml_parse_result load_file (const char *path, unsigned int options=parse_default, xml_encoding encoding=encoding_auto)
xml_parse_result load_file (const wchar_t *path, unsigned int options=parse_default, xml_encoding encoding=encoding_auto)
xml_parse_result load_buffer (const void *contents, size_t size, unsigned int options=parse_default, xml_encoding encoding=encoding_auto)
xml_parse_result load_buffer_inplace (void *contents, size_t size, unsigned int options=parse_default, xml_encoding encoding=encoding_auto)
xml_parse_result load_buffer_inplace_own (void *contents, size_t size, unsigned int options=parse_default, xml_encoding encoding=encoding_auto)
void save (xml_writer &writer, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default, xml_encoding encoding=encoding_auto) const
void save (std::basic_ostream< char, std::char_traits< char > > &stream, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default, xml_encoding encoding=encoding_auto) const
void save (std::basic_ostream< wchar_t, std::char_traits< wchar_t > > &stream, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default) const
bool save_file (const char *path, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default, xml_encoding encoding=encoding_auto) const
bool save_file (const wchar_t *path, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default, xml_encoding encoding=encoding_auto) const
xml_node document_element () const
Public Member Functions inherited from pugi::xml_node
xml_node ()
xml_node (xml_node_struct *p)
operator unspecified_bool_type () const
bool operator! () const
bool operator== (const xml_node &r) const
bool operator!= (const xml_node &r) const
bool operator< (const xml_node &r) const
bool operator> (const xml_node &r) const
bool operator<= (const xml_node &r) const
bool operator>= (const xml_node &r) const
bool empty () const
xml_node_type type () const
const char_t * name () const
const char_t * value () const
xml_attribute first_attribute () const
xml_attribute last_attribute () const
xml_node first_child () const
xml_node last_child () const
xml_node next_sibling () const
xml_node previous_sibling () const
xml_node parent () const
xml_node root () const
xml_text text () const
xml_node child (const char_t *name) const
xml_attribute attribute (const char_t *name) const
xml_node next_sibling (const char_t *name) const
xml_node previous_sibling (const char_t *name) const
const char_t * child_value () const
const char_t * child_value (const char_t *name) const
bool set_name (const char_t *rhs)
bool set_value (const char_t *rhs)
xml_attribute append_attribute (const char_t *name)
xml_attribute prepend_attribute (const char_t *name)
xml_attribute insert_attribute_after (const char_t *name, const xml_attribute &attr)
xml_attribute insert_attribute_before (const char_t *name, const xml_attribute &attr)
xml_attribute append_copy (const xml_attribute &proto)
xml_attribute prepend_copy (const xml_attribute &proto)
xml_attribute insert_copy_after (const xml_attribute &proto, const xml_attribute &attr)
xml_attribute insert_copy_before (const xml_attribute &proto, const xml_attribute &attr)
xml_node append_child (xml_node_type type=node_element)
xml_node prepend_child (xml_node_type type=node_element)
xml_node insert_child_after (xml_node_type type, const xml_node &node)
xml_node insert_child_before (xml_node_type type, const xml_node &node)
xml_node append_child (const char_t *name)
xml_node prepend_child (const char_t *name)
xml_node insert_child_after (const char_t *name, const xml_node &node)
xml_node insert_child_before (const char_t *name, const xml_node &node)
xml_node append_copy (const xml_node &proto)
xml_node prepend_copy (const xml_node &proto)
xml_node insert_copy_after (const xml_node &proto, const xml_node &node)
xml_node insert_copy_before (const xml_node &proto, const xml_node &node)
bool remove_attribute (const xml_attribute &a)
bool remove_attribute (const char_t *name)
bool remove_child (const xml_node &n)
bool remove_child (const char_t *name)
xml_parse_result append_buffer (const void *contents, size_t size, unsigned int options=parse_default, xml_encoding encoding=encoding_auto)
template<typename Predicate >
xml_attribute find_attribute (Predicate pred) const
template<typename Predicate >
xml_node find_child (Predicate pred) const
template<typename Predicate >
xml_node find_node (Predicate pred) const
xml_node find_child_by_attribute (const char_t *name, const char_t *attr_name, const char_t *attr_value) const
xml_node find_child_by_attribute (const char_t *attr_name, const char_t *attr_value) const
string_t path (char_t delimiter='/') const
xml_node first_element_by_path (const char_t *path, char_t delimiter='/') const
bool traverse (xml_tree_walker &walker)
xpath_node select_single_node (const char_t *query, xpath_variable_set *variables=0) const
xpath_node select_single_node (const xpath_query &query) const
xpath_node_set select_nodes (const char_t *query, xpath_variable_set *variables=0) const
xpath_node_set select_nodes (const xpath_query &query) const
void print (xml_writer &writer, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default, xml_encoding encoding=encoding_auto, unsigned int depth=0) const
void print (std::basic_ostream< char, std::char_traits< char > > &os, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default, xml_encoding encoding=encoding_auto, unsigned int depth=0) const
void print (std::basic_ostream< wchar_t, std::char_traits< wchar_t > > &os, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default, unsigned int depth=0) const
iterator begin () const
iterator end () const
attribute_iterator attributes_begin () const
attribute_iterator attributes_end () const
xml_object_range< xml_node_iterator > children () const
xml_object_range< xml_named_node_iterator > children (const char_t *name) const
xml_object_range< xml_attribute_iterator > attributes () const
ptrdiff_t offset_debug () const
size_t hash_value () const
xml_node_struct * internal_object () const
xml_node ()
xml_node (xml_node_struct *p)
operator unspecified_bool_type () const
bool operator! () const
bool operator== (const xml_node &r) const
bool operator!= (const xml_node &r) const
bool operator< (const xml_node &r) const
bool operator> (const xml_node &r) const
bool operator<= (const xml_node &r) const
bool operator>= (const xml_node &r) const
bool empty () const
xml_node_type type () const
const char_t * name () const
const char_t * value () const
xml_attribute first_attribute () const
xml_attribute last_attribute () const
xml_node first_child () const
xml_node last_child () const
xml_node next_sibling () const
xml_node previous_sibling () const
xml_node parent () const
xml_node root () const
xml_text text () const
xml_node child (const char_t *name) const
xml_attribute attribute (const char_t *name) const
xml_node next_sibling (const char_t *name) const
xml_node previous_sibling (const char_t *name) const
const char_t * child_value () const
const char_t * child_value (const char_t *name) const
bool set_name (const char_t *rhs)
bool set_value (const char_t *rhs)
xml_attribute append_attribute (const char_t *name)
xml_attribute prepend_attribute (const char_t *name)
xml_attribute insert_attribute_after (const char_t *name, const xml_attribute &attr)
xml_attribute insert_attribute_before (const char_t *name, const xml_attribute &attr)
xml_attribute append_copy (const xml_attribute &proto)
xml_attribute prepend_copy (const xml_attribute &proto)
xml_attribute insert_copy_after (const xml_attribute &proto, const xml_attribute &attr)
xml_attribute insert_copy_before (const xml_attribute &proto, const xml_attribute &attr)
xml_node append_child (xml_node_type type=node_element)
xml_node prepend_child (xml_node_type type=node_element)
xml_node insert_child_after (xml_node_type type, const xml_node &node)
xml_node insert_child_before (xml_node_type type, const xml_node &node)
xml_node append_child (const char_t *name)
xml_node prepend_child (const char_t *name)
xml_node insert_child_after (const char_t *name, const xml_node &node)
xml_node insert_child_before (const char_t *name, const xml_node &node)
xml_node append_copy (const xml_node &proto)
xml_node prepend_copy (const xml_node &proto)
xml_node insert_copy_after (const xml_node &proto, const xml_node &node)
xml_node insert_copy_before (const xml_node &proto, const xml_node &node)
bool remove_attribute (const xml_attribute &a)
bool remove_attribute (const char_t *name)
bool remove_child (const xml_node &n)
bool remove_child (const char_t *name)
xml_parse_result append_buffer (const void *contents, size_t size, unsigned int options=parse_default, xml_encoding encoding=encoding_auto)
template<typename Predicate >
xml_attribute find_attribute (Predicate pred) const
template<typename Predicate >
xml_node find_child (Predicate pred) const
template<typename Predicate >
xml_node find_node (Predicate pred) const
xml_node find_child_by_attribute (const char_t *name, const char_t *attr_name, const char_t *attr_value) const
xml_node find_child_by_attribute (const char_t *attr_name, const char_t *attr_value) const
string_t path (char_t delimiter='/') const
xml_node first_element_by_path (const char_t *path, char_t delimiter='/') const
bool traverse (xml_tree_walker &walker)
xpath_node select_single_node (const char_t *query, xpath_variable_set *variables=0) const
xpath_node select_single_node (const xpath_query &query) const
xpath_node_set select_nodes (const char_t *query, xpath_variable_set *variables=0) const
xpath_node_set select_nodes (const xpath_query &query) const
void print (xml_writer &writer, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default, xml_encoding encoding=encoding_auto, unsigned int depth=0) const
void print (std::basic_ostream< char, std::char_traits< char > > &os, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default, xml_encoding encoding=encoding_auto, unsigned int depth=0) const
void print (std::basic_ostream< wchar_t, std::char_traits< wchar_t > > &os, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default, unsigned int depth=0) const
iterator begin () const
iterator end () const
attribute_iterator attributes_begin () const
attribute_iterator attributes_end () const
xml_object_range< xml_node_iterator > children () const
xml_object_range< xml_named_node_iterator > children (const char_t *name) const
xml_object_range< xml_attribute_iterator > attributes () const
ptrdiff_t offset_debug () const
size_t hash_value () const
xml_node_struct * internal_object () const
Private Member Functions
xml_document (const xml_document &)
const xml_document & operator= (const xml_document &)
void create ()
void destroy ()
xml_document (const xml_document &)
const xml_document & operator= (const xml_document &)
void create ()
void destroy ()
Private Attributes
char_t * _buffer
char _memory [192]
Additional Inherited Members
Public Types inherited from pugi::xml_node
typedef xml_node_iterator iterator
typedef xml_attribute_iterator attribute_iterator
typedef xml_node_iterator iterator
typedef xml_attribute_iterator attribute_iterator
Protected Types inherited from pugi::xml_node
typedef void(* unspecified_bool_type) (xml_node ***)
typedef void(* unspecified_bool_type) (xml_node ***)
Protected Attributes inherited from pugi::xml_node
xml_node_struct * _root
Detailed Description
Definition at line 922 of file pugixml.hpp.
Constructor & Destructor Documentation
xml_document() [1/4]
pugi::xml_document::xml_document (const xml_document &) private
xml_document() [2/4]
PUGI__FN pugi::xml_document::xml_document ()
Definition at line 5962 of file pugixml.cpp.
References create().
~xml_document() [1/2]
PUGI__FN pugi::xml_document::~xml_document ()
Definition at line 5967 of file pugixml.cpp.
References destroy().
xml_document() [3/4]
pugi::xml_document::xml_document (const xml_document &) private
xml_document() [4/4]
pugi::xml_document::xml_document ()
~xml_document() [2/2]
pugi::xml_document::~xml_document ()
Member Function Documentation
create() [1/2]
PUGI__FN void pugi::xml_document::create () private
Definition at line 5986 of file pugixml.cpp.
References _memory, pugi::xml_node::_root, pugi::xml_node_struct::prev_sibling_c, PUGI__STATIC_ASSERT, xml_memory_page_alignment, and xml_memory_page_size.
Referenced by reset(), and xml_document().
create() [2/2]
void pugi::xml_document::create () private
destroy() [1/2]
void pugi::xml_document::destroy () private
destroy() [2/2]
PUGI__FN void pugi::xml_document::destroy () private
Definition at line 6014 of file pugixml.cpp.
References _buffer, pugi::xml_node::_root, pugi::xml_node_struct::header, and xml_memory_page_pointer_mask.
Referenced by reset(), and ~xml_document().
document_element() [1/2]
xml_node pugi::xml_document::document_element () const
document_element() [2/2]
PUGI__FN xml_node pugi::xml_document::document_element () const
Definition at line 6186 of file pugixml.cpp.
References pugi::xml_node::_root, pugi::xml_node_struct::first_child, pugi::xml_node_struct::next_sibling, pugi::node_element, xml_memory_page_type_mask, and pugi::xml_node::xml_node().
load() [1/6]
PUGI__FN xml_parse_result pugi::xml_document::load (const char_t * contents, unsigned int options = parse_default)
Definition at line 6068 of file pugixml.cpp.
References pugi::encoding_utf8, pugi::encoding_wchar, load_buffer(), options, and strlength().
load() [2/6]
xml_parse_result pugi::xml_document::load (const char_t * contents, unsigned int options = parse_default)
load() [3/6]
xml_parse_result pugi::xml_document::load (std::basic_istream< char, std::char_traits< char > > & stream, unsigned int options = parse_default, xml_encoding encoding = encoding_auto)
load() [4/6]
xml_parse_result pugi::xml_document::load (std::basic_istream< char, std::char_traits< char > > & stream, unsigned int options = parse_default, xml_encoding encoding = encoding_auto)
Referenced by etiss::fault::Fault::toString(), and etiss::fault::Action::toString().
load() [5/6]
xml_parse_result pugi::xml_document::load (std::basic_istream< wchar_t, std::char_traits< wchar_t > > & stream, unsigned int options = parse_default)
load() [6/6]
xml_parse_result pugi::xml_document::load (std::basic_istream< wchar_t, std::char_traits< wchar_t > > & stream, unsigned int options = parse_default)
load_buffer() [1/2]
PUGI__FN xml_parse_result pugi::xml_document::load_buffer (const void * contents, size_t size, unsigned int options = parse_default, xml_encoding encoding = encoding_auto)
Definition at line 6098 of file pugixml.cpp.
References _buffer, pugi::xml_node::_root, load_buffer_impl(), options, and reset().
Referenced by load().
load_buffer() [2/2]
xml_parse_result pugi::xml_document::load_buffer (const void * contents, size_t size, unsigned int options = parse_default, xml_encoding encoding = encoding_auto)
load_buffer_inplace() [1/2]
PUGI__FN xml_parse_result pugi::xml_document::load_buffer_inplace (void * contents, size_t size, unsigned int options = parse_default, xml_encoding encoding = encoding_auto)
Definition at line 6107 of file pugixml.cpp.
References _buffer, pugi::xml_node::_root, load_buffer_impl(), options, and reset().
load_buffer_inplace() [2/2]
xml_parse_result pugi::xml_document::load_buffer_inplace (void * contents, size_t size, unsigned int options = parse_default, xml_encoding encoding = encoding_auto)
load_buffer_inplace_own() [1/2]
xml_parse_result pugi::xml_document::load_buffer_inplace_own (void * contents, size_t size, unsigned int options = parse_default, xml_encoding encoding = encoding_auto)
load_buffer_inplace_own() [2/2]
PUGI__FN xml_parse_result pugi::xml_document::load_buffer_inplace_own (void * contents, size_t size, unsigned int options = parse_default, xml_encoding encoding = encoding_auto)
Definition at line 6116 of file pugixml.cpp.
References _buffer, pugi::xml_node::_root, load_buffer_impl(), options, and reset().
load_file() [1/4]
PUGI__FN xml_parse_result pugi::xml_document::load_file (const char * path, unsigned int options = parse_default, xml_encoding encoding = encoding_auto)
Definition at line 6080 of file pugixml.cpp.
References load_file_impl(), options, and reset().
load_file() [2/4]
xml_parse_result pugi::xml_document::load_file (const char * path, unsigned int options = parse_default, xml_encoding encoding = encoding_auto)
load_file() [3/4]
PUGI__FN xml_parse_result pugi::xml_document::load_file (const wchar_t * path, unsigned int options = parse_default, xml_encoding encoding = encoding_auto)
Definition at line 6089 of file pugixml.cpp.
References load_file_impl(), open_file_wide(), options, and reset().
load_file() [4/4]
xml_parse_result pugi::xml_document::load_file (const wchar_t * path, unsigned int options = parse_default, xml_encoding encoding = encoding_auto)
operator=() [1/2]
const xml_document& pugi::xml_document::operator= (const xml_document &) private
operator=() [2/2]
const xml_document& pugi::xml_document::operator= (const xml_document &) private
reset() [1/4]
void pugi::xml_document::reset ()
reset() [2/4]
PUGI__FN void pugi::xml_document::reset ()
Definition at line 5972 of file pugixml.cpp.
References create(), and destroy().
Referenced by load_buffer(), load_buffer_inplace(), load_buffer_inplace_own(), load_file(), and reset().
reset() [3/4]
PUGI__FN void pugi::xml_document::reset (const xml_document & proto)
Definition at line 5978 of file pugixml.cpp.
References pugi::xml_node::append_copy(), pugi::xml_node::first_child(), pugi::xml_node::next_sibling(), and reset().
reset() [4/4]
void pugi::xml_document::reset (const xml_document & proto)
save() [1/6]
void pugi::xml_document::save (std::basic_ostream< char, std::char_traits< char > > & stream, const char_t * indent = PUGIXML_TEXT("\t"), unsigned int flags = format_default, xml_encoding encoding = encoding_auto) const
save() [2/6]
void pugi::xml_document::save (std::basic_ostream< char, std::char_traits< char > > & stream, const char_t * indent = PUGIXML_TEXT("\t"), unsigned int flags = format_default, xml_encoding encoding = encoding_auto) const
save() [3/6]
void pugi::xml_document::save (std::basic_ostream< wchar_t, std::char_traits< wchar_t > > & stream, const char_t * indent = PUGIXML_TEXT("\t"), unsigned int flags = format_default) const
save() [4/6]
void pugi::xml_document::save (std::basic_ostream< wchar_t, std::char_traits< wchar_t > > & stream, const char_t * indent = PUGIXML_TEXT("\t"), unsigned int flags = format_default) const
save() [5/6]
void pugi::xml_document::save (xml_writer & writer, const char_t * indent = PUGIXML_TEXT("\t"), unsigned int flags = format_default, xml_encoding encoding = encoding_auto) const
save() [6/6]
PUGI__FN void pugi::xml_document::save (xml_writer & writer, const char_t * indent = PUGIXML_TEXT("\t"), unsigned int flags = format_default, xml_encoding encoding = encoding_auto) const
Definition at line 6125 of file pugixml.cpp.
References pugi::encoding_latin1, pugi::format_no_declaration, pugi::format_raw, pugi::format_write_bom, has_declaration(), node_output(), and PUGIXML_TEXT.
Referenced by etiss::fault::Fault::toString(), and etiss::fault::Action::toString().
save_file() [1/4]
PUGI__FN bool pugi::xml_document::save_file (const char * path, const char_t * indent = PUGIXML_TEXT("\t"), unsigned int flags = format_default, xml_encoding encoding = encoding_auto) const
Definition at line 6172 of file pugixml.cpp.
References pugi::format_save_file_text, and save_file_impl().
save_file() [2/4]
bool pugi::xml_document::save_file (const char * path, const char_t * indent = PUGIXML_TEXT("\t"), unsigned int flags = format_default, xml_encoding encoding = encoding_auto) const
save_file() [3/4]
bool pugi::xml_document::save_file (const wchar_t * path, const char_t * indent = PUGIXML_TEXT("\t"), unsigned int flags = format_default, xml_encoding encoding = encoding_auto) const
save_file() [4/4]
PUGI__FN bool pugi::xml_document::save_file (const wchar_t * path, const char_t * indent = PUGIXML_TEXT("\t"), unsigned int flags = format_default, xml_encoding encoding = encoding_auto) const
Definition at line 6179 of file pugixml.cpp.
References pugi::format_save_file_text, open_file_wide(), and save_file_impl().
Member Data Documentation
_buffer
char_t * pugi::xml_document::_buffer private
Definition at line 925 of file pugixml.hpp.
Referenced by destroy(), load_buffer(), load_buffer_inplace(), and load_buffer_inplace_own().
_memory
char pugi::xml_document::_memory private
Definition at line 927 of file pugixml.hpp.
Referenced by create().
The documentation for this class was generated from the following files:
include/etiss/fault/xml/pugixml.hpp
/home/runner/work/etiss/etiss/src/fault/xml/pugixml.cpp