ETISS 0.8.0: etiss::instr::ModedInstructionSet Class Reference
etiss::instr::ModedInstructionSet Class Reference
holds etiss::instr::VariableInstructionSet instances for different modes.
#include <Instruction.h>
Public Member Functions
VariableInstructionSet * get (uint32_t mode)
VariableInstructionSet * create (uint32_t mode, unsigned width, const std::string &name=std::string())
VariableInstructionSet & open (uint32_t mode, unsigned width, const std::string &name=std::string())
template<typename T >
Instruction & open (uint32_t mode, unsigned width, unsigned bits, T code, T mask, const char *instrname)
uint32_t getMode (VariableInstructionSet *vis)
uint32_t getMode (VariableInstructionSet &vis)
void foreach (std::function< void(VariableInstructionSet &)> call)
bool compile ()
std::string print (std::string prefix=std::string())
VariableInstructionSet * get (uint32_t mode)
VariableInstructionSet * create (uint32_t mode, unsigned width, const std::string &name=std::string())
VariableInstructionSet & open (uint32_t mode, unsigned width, const std::string &name=std::string())
template<typename T >
Instruction & open (uint32_t mode, unsigned width, unsigned bits, T code, T mask, const char *instrname)
uint32_t getMode (VariableInstructionSet *vis)
uint32_t getMode (VariableInstructionSet &vis)
void foreach (std::function< void(VariableInstructionSet &)> call)
bool compile ()
std::string print (std::string prefix=std::string())
Public Attributes
const std::string archname_
Private Attributes
std::map< uint32_t, std::string > modetostring_
std::map< std::string, uint32_t > stringtomode_
std::map< uint32_t, VariableInstructionSet * > vismap_
std::map< VariableInstructionSet *, uint32_t > invvismap_
Detailed Description
holds etiss::instr::VariableInstructionSet instances for different modes.
The field ETISS_CPU::mode selects the matching VariableInstructionSet from this ModedInstructionSet.
ETISS includes a mode check at the start of a translation block to check if the translated block was compiled with the same mode as the current mode. If the modes mismatch the block will be discarded and translated again.
    Location in an instruction translation tree:
    ModedInstructionSet
        ↳ VariableInstructionSet (e.g. for mode 0)
            ↳ InstructionSet (e.g. 32 bit)
                ↳ Node
                    ↳ ...                ↳ Node
                    ↳ ...                    ↳ ...
                        ↳ Instruction
            ↳ InstructionSet (e.g. 16 bit)
Definition at line 814 of file Instruction.h.
Member Function Documentation
compile() [1/2]
bool etiss::instr::ModedInstructionSet::compile ()
Definition at line 1190 of file Instruction.cpp.
References etiss::instr::VariableInstructionSet::compile().
Referenced by etiss::Translation::init(), and RISCVArch::initInstrSet().
compile() [2/2]
bool etiss::instr::ModedInstructionSet::compile ()
create() [1/2]
VariableInstructionSet * etiss::instr::ModedInstructionSet::create (uint32_t mode, unsigned width, const std::string & name = std::string())
Definition at line 1132 of file Instruction.cpp.
References etiss::ERROR, etiss_log, invvismap_, name, and vismap_.
Referenced by open().
create() [2/2]
VariableInstructionSet* etiss::instr::ModedInstructionSet::create (uint32_t mode, unsigned width, const std::string & name = std::string())
foreach() [1/2]
void etiss::instr::ModedInstructionSet::foreach (std::function< void(VariableInstructionSet &)> call)
foreach() [2/2]
void etiss::instr::ModedInstructionSet::foreach (std::function< void(VariableInstructionSet &)> call)
Definition at line 1175 of file Instruction.cpp.
References etiss::ERROR, etiss_log, and vismap_.
Referenced by etiss::plugin::InstructionAccurateCallback::finalizeInstrSet(), etiss::plugin::PrintInstruction::finalizeInstrSet(), etiss::plugin::VariableValueLogger::finalizeInstrSet(), etiss::plugin::InstructionSpecificAddressCallback::finalizeInstrSet(), etiss::plugin::gdb::Server::finalizeInstrSet(), etiss::CPUArch::finalizeInstrSet(), and etiss::DataSheetAccurateTiming::initInstrSet().
get() [1/2]
VariableInstructionSet * etiss::instr::ModedInstructionSet::get (uint32_t mode)
Definition at line 1125 of file Instruction.cpp.
References vismap_.
Referenced by etiss::Translation::disasm(), RISCVArch::initInstrSet(), RISCV64Arch::initInstrSet(), open(), and etiss::Translation::translateBlock().
get() [2/2]
VariableInstructionSet* etiss::instr::ModedInstructionSet::get (uint32_t mode)
getMode() [1/4]
uint32_t etiss::instr::ModedInstructionSet::getMode (VariableInstructionSet & vis) inline
Definition at line 845 of file Instruction.h.
References getMode().
Referenced by getMode().
getMode() [2/4]
uint32_t etiss::instr::ModedInstructionSet::getMode (VariableInstructionSet & vis) inline
Definition at line 845 of file Instruction.h.
References getMode().
Referenced by getMode().
getMode() [3/4]
uint32_t etiss::instr::ModedInstructionSet::getMode (VariableInstructionSet * vis)
Definition at line 1165 of file Instruction.cpp.
References etiss::ERROR, etiss_log, and invvismap_.
Referenced by etiss::DataSheetAccurateTiming::initInstrSet(), and print().
getMode() [4/4]
uint32_t etiss::instr::ModedInstructionSet::getMode (VariableInstructionSet * vis)
open() [1/4]
VariableInstructionSet& etiss::instr::ModedInstructionSet::open (uint32_t mode, unsigned width, const std::string & name = std::string())
Attention
in non debug build a width missmatch will be silently ignored
open() [2/4]
VariableInstructionSet & etiss::instr::ModedInstructionSet::open (uint32_t mode, unsigned width, const std::string & name = std::string())
Attention
in non debug build a width missmatch will be silently ignored
Definition at line 1150 of file Instruction.cpp.
References create(), etiss::ERROR, etiss_log, get(), name, and etiss::instr::VariableInstructionSet::width_.
Referenced by etiss::instr::InstructionCollection::addTo(), and open().
open() [3/4]
template<typename T > Instruction& etiss::instr::ModedInstructionSet::open (uint32_t mode, unsigned width, unsigned bits, T code, T mask, const char * instrname) inline
Definition at line 839 of file Instruction.h.
References etiss::instr::VariableInstructionSet::open(), and open().
open() [4/4]
template<typename T > Instruction& etiss::instr::ModedInstructionSet::open (uint32_t mode, unsigned width, unsigned bits, T code, T mask, const char * instrname) inline
Definition at line 839 of file Instruction.h.
References etiss::instr::VariableInstructionSet::open(), and open().
print() [1/2]
std::string etiss::instr::ModedInstructionSet::print (std::string prefix = std::string())
Definition at line 1198 of file Instruction.cpp.
References archname_, getMode(), etiss::instr::VariableInstructionSet::parent_, and etiss::instr::VariableInstructionSet::print().
print() [2/2]
std::string etiss::instr::ModedInstructionSet::print (std::string prefix = std::string())
Member Data Documentation
archname_
const std::string etiss::instr::ModedInstructionSet::archname_
Definition at line 823 of file Instruction.h.
Referenced by print().
invvismap_
std::map< VariableInstructionSet *, uint32_t > etiss::instr::ModedInstructionSet::invvismap_ private
Definition at line 820 of file Instruction.h.
Referenced by create(), and getMode().
modetostring_
std::map< uint32_t, std::string > etiss::instr::ModedInstructionSet::modetostring_ private
Definition at line 817 of file Instruction.h.
stringtomode_
std::map< std::string, uint32_t > etiss::instr::ModedInstructionSet::stringtomode_ private
Definition at line 818 of file Instruction.h.
vismap_
std::map< uint32_t, VariableInstructionSet * > etiss::instr::ModedInstructionSet::vismap_ private
Definition at line 819 of file Instruction.h.
Referenced by create(), foreach(), and get().
The documentation for this class was generated from the following files:
include/etiss/Instruction.h
/home/runner/work/etiss/etiss/src/Instruction.cpp