ETISS 0.8.0: etiss::instr::BitArrayRange Class Reference
etiss::instr::BitArrayRange Class Reference
Acts as a view/filter to a BitArray.
#include <Instruction.h>
Public Member Functions
BitArrayRange (unsigned startindex_included, unsigned endindex_included)
I read (const BitArray &ba)
reads bits from the range to the return value starting at the lsb.
void write (const BitArray &ba, I val)
write the bit from the passed value starting at the lsb to the range.
void setAll (const BitArray &ba, bool val)
sets all bits of the range to the specified value (true =1;false =0)
unsigned start ()
highest bit of the range (included)
unsigned end ()
lowest bit of the range (included).
BitArrayRange (unsigned startindex_included, unsigned endindex_included)
I read (const BitArray &ba)
reads bits from the range to the return value starting at the lsb.
void write (const BitArray &ba, I val)
write the bit from the passed value starting at the lsb to the range.
void setAll (const BitArray &ba, bool val)
sets all bits of the range to the specified value (true =1;false =0)
unsigned start ()
highest bit of the range (included)
unsigned end ()
lowest bit of the range (included).
Public Attributes
etiss_del_como(BitArrayRange) private unsigned filterEnd_
unsigned filterLen_
unsigned lowPartShift_ = 0
I lowPartMask_ = 0
unsigned dataArrayIndex_ = 0
bool needsSplitAccess_ = false
I highPartMask_ = 0
unsigned highPartShift_ = 0
Static Public Attributes
static const size_t Ibits = sizeof(I) * 8
Detailed Description
Acts as a view/filter to a BitArray.
Reading through it will only return bits within the range. Writing through it will only set bits within the range.
The length of the range may not be larger than sizeof(I)*8.
Definition at line 337 of file Instruction.h.
Constructor & Destructor Documentation
BitArrayRange() [1/2]
etiss::instr::BitArrayRange::BitArrayRange (unsigned startindex_included, unsigned endindex_included)
Attention
startindex_included MUST be the higher valued index. Only exception is for zero length ranges where startindex_included+1==endindex_included
Definition at line 389 of file Instruction.cpp.
References dataArrayIndex_, filterEnd_, filterLen_, highPartMask_, highPartShift_, Ibits, lowPartMask_, lowPartShift_, and needsSplitAccess_.
BitArrayRange() [2/2]
etiss::instr::BitArrayRange::BitArrayRange (unsigned startindex_included, unsigned endindex_included)
Attention
startindex_included MUST be the higher valued index. Only exception is for zero length ranges where startindex_included+1==endindex_included
Member Function Documentation
end() [1/2]
unsigned etiss::instr::BitArrayRange::end ()
lowest bit of the range (included).
Attention
for zero length ranges end() equals start()+1
Definition at line 462 of file Instruction.cpp.
References filterEnd_.
Referenced by etiss::instr::Node::print(), and etiss::instr::Node::~Node().
end() [2/2]
unsigned etiss::instr::BitArrayRange::end ()
lowest bit of the range (included).
Attention
for zero length ranges end() equals start()+1
read() [1/2]
I etiss::instr::BitArrayRange::read (const BitArray & ba)
reads bits from the range to the return value starting at the lsb.
higher bits are set to zero
Definition at line 421 of file Instruction.cpp.
References etiss::instr::BitArray::d_, dataArrayIndex_, highPartMask_, highPartShift_, lowPartMask_, lowPartShift_, needsSplitAccess_, and etiss::instr::BitArray::w_.
Referenced by etiss::instr::Node::compile(), RISCVArch::initInstrSet(), RISCV64Arch::initInstrSet(), l_cust(), l_ext(), l_sf(), loadinstr(), or1k_asm_print_rDAB(), or1k_asm_print_rDAI(), etiss::instr::Node::resolve(), etiss::instr::OverlappedNode::resolve(), shift(), simple_op_rDAB(), simple_op_rDAI(), and storeinstr().
read() [2/2]
I etiss::instr::BitArrayRange::read (const BitArray & ba)
reads bits from the range to the return value starting at the lsb.
higher bits are set to zero
setAll() [1/2]
void etiss::instr::BitArrayRange::setAll (const BitArray & ba, bool val)
sets all bits of the range to the specified value (true =1;false =0)
setAll() [2/2]
void etiss::instr::BitArrayRange::setAll (const BitArray & ba, bool val)
sets all bits of the range to the specified value (true =1;false =0)
Definition at line 445 of file Instruction.cpp.
References write().
Referenced by etiss::instr::Node::compile().
start() [1/2]
unsigned etiss::instr::BitArrayRange::start ()
highest bit of the range (included)
Definition at line 458 of file Instruction.cpp.
Referenced by etiss::instr::Node::print(), and etiss::instr::Node::~Node().
start() [2/2]
unsigned etiss::instr::BitArrayRange::start ()
highest bit of the range (included)
write() [1/2]
void etiss::instr::BitArrayRange::write (const BitArray & ba, I val)
write the bit from the passed value starting at the lsb to the range.
Definition at line 432 of file Instruction.cpp.
References etiss::instr::BitArray::d_, dataArrayIndex_, highPartMask_, highPartShift_, lowPartMask_, lowPartShift_, needsSplitAccess_, and etiss::instr::BitArray::w_.
Referenced by setAll().
write() [2/2]
void etiss::instr::BitArrayRange::write (const BitArray & ba, I val)
write the bit from the passed value starting at the lsb to the range.
Member Data Documentation
dataArrayIndex_
unsigned etiss::instr::BitArrayRange::dataArrayIndex_ = 0
Definition at line 347 of file Instruction.h.
Referenced by BitArrayRange(), read(), and write().
filterEnd_
etiss_del_como (BitArrayRange) private unsigned etiss::instr::BitArrayRange::filterEnd_
Definition at line 340 of file Instruction.h.
Referenced by BitArrayRange(), and end().
filterLen_
unsigned etiss::instr::BitArrayRange::filterLen_
Definition at line 344 of file Instruction.h.
Referenced by BitArrayRange().
highPartMask_
I etiss::instr::BitArrayRange::highPartMask_ = 0
Definition at line 349 of file Instruction.h.
Referenced by BitArrayRange(), read(), and write().
highPartShift_
unsigned etiss::instr::BitArrayRange::highPartShift_ = 0
Definition at line 350 of file Instruction.h.
Referenced by BitArrayRange(), read(), and write().
Ibits
static const size_t etiss::instr::BitArrayRange::Ibits = sizeof(I) * 8 static
Definition at line 352 of file Instruction.h.
Referenced by BitArrayRange().
lowPartMask_
I etiss::instr::BitArrayRange::lowPartMask_ = 0
Definition at line 346 of file Instruction.h.
Referenced by BitArrayRange(), read(), and write().
lowPartShift_
unsigned etiss::instr::BitArrayRange::lowPartShift_ = 0
Definition at line 345 of file Instruction.h.
Referenced by BitArrayRange(), read(), and write().
needsSplitAccess_
bool etiss::instr::BitArrayRange::needsSplitAccess_ = false
Definition at line 348 of file Instruction.h.
Referenced by BitArrayRange(), read(), and write().
The documentation for this class was generated from the following files:
include/etiss/Instruction.h
/home/runner/work/etiss/etiss/src/Instruction.cpp