ETISS 0.8.0: /home/runner/work/etiss/etiss/include/etiss/make_unique.h File Reference
make_unique.h File Reference
#include <cstddef>
#include <memory>
#include <type_traits>
#include <utility>
Classes
struct std::_Unique_if< T >
struct std::_Unique_if< T[]>
struct std::_Unique_if< T[N]>
Functions
template<class T , class... Args>
_Unique_if< T >::_Single_object std::make_unique (Args &&... args)
template<class T >
_Unique_if< T >::_Unknown_bound std::make_unique (size_t n)
template<class T , class... Args>
_Unique_if< T >::_Known_bound std::make_unique (Args &&...)=delete
Function Documentation
make_unique() [1/3]
template<class T , class... Args> _Unique_if< T >::_Single_object std::make_unique (Args &&... args)
Definition at line 27 of file make_unique.h.
References std::make_unique().
Referenced by std::make_unique().
make_unique() [2/3]
template<class T , class... Args> _Unique_if< T >::_Known_bound std::make_unique (Args && ...) delete
make_unique() [3/3]
template<class T > _Unique_if< T >::_Unknown_bound std::make_unique (size_t n)
Definition at line 33 of file make_unique.h.
References std::make_unique().