ETISS 0.8.0: /home/runner/work/etiss/etiss/src/ETISS.cpp File Reference
ETISS.cpp File Reference
Implementation of etiss/ETISS.h except for etiss::preloadLibraries.
#include "etiss/ETISS.h"
#include "etiss/fault/Stressor.h"
#include <csignal>
#include <cstring>
#include <fstream>
#include <functional>
#include <boost/program_options/options_description.hpp>
#include <boost/program_options/parsers.hpp>
#include <boost/program_options/variables_map.hpp>
Classes
class helper_class_etiss_2
replaces __attribute__((destructor)) in a portable way
class helper_class_etiss_1
replaces __attribute__((destructor)) in a portable way
class helper_class_etiss_3
replaces __attribute__((destructor)) in a portable way
Functions
void etiss_SIGINT_handler (int sig)
static void etiss_remove_SIGINT ()
void etiss_loadIni (std::string fileName)
void etiss_loadIniConfigs ()
std::pair< std::string, std::string > inifileload (const std::string &s)
void etiss_initialize (const std::vector< std::string > &args, bool forced=false)
static void etiss_shutdown ()
static void etiss_check_shutdown ()
check if etiss::shutdown() was called before exiting main.
Variables
std::string etiss_defaultjit_
std::list< std::shared_ptr< etiss::LibraryInterface > > etiss_libraries_
std::recursive_mutex etiss_libraries_mu_
boost::program_options::variables_map vm
std::vector< std::string > pluginOptions = {"plugin.logger.logaddr", "plugin.logger.logmask", "plugin.gdbserver.port"}
void(* etiss_prev_SIGINT_handler)(int)=0
bool etiss_SIGINT_handler_enabled = false
static class helper_class_etiss_2 helper_class_etiss_2
CSimpleIniA * po_simpleIni
static class helper_class_etiss_1 helper_class_etiss_1
bool etiss_shutdownOk = false
static class helper_class_etiss_3 helper_class_etiss_3
Detailed Description
Implementation of etiss/ETISS.h except for etiss::preloadLibraries.
Copyright
Copyright 2018 Infineon Technologies AG
This file is part of ETISS tool, see https://github.com/tum-ei-eda/etiss.
The initial version of this software has been created with the funding support by the German Federal
Ministry of Education and Research (BMBF) in the project EffektiV under grant 01IS13022.
Redistribution and use in source and binary forms, with or without modification, are permitted
provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and
the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions
and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse
or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
Author
Marc Greim marc..nosp@m.grei.nosp@m.m@myt.nosp@m.um.d.nosp@m.e, Chair of Electronic Design Automation, TUM
Date
July 29, 2014
Version
0.1
Definition in file ETISS.cpp.
Function Documentation
etiss_check_shutdown()
static void etiss_check_shutdown () static
check if etiss::shutdown() was called before exiting main.
Definition at line 960 of file ETISS.cpp.
References etiss::ERROR, etiss_shutdownOk, and etiss::log().
Referenced by helper_class_etiss_3::~helper_class_etiss_3().
etiss_initialize()
void etiss_initialize (const std::vector< std::string > & args, bool forced = false)
Definition at line 688 of file ETISS.cpp.
References etiss::addLibrary(), etiss::cfg(), etiss::ERROR, etiss_loadIniConfigs(), etiss_remove_SIGINT(), etiss::FATALERROR, etiss::fault::faults(), etiss::Configuration::get(), inifileload(), etiss::py::init(), etiss::installDir(), etiss::fault::Stressor::loadXML(), etiss::log(), etiss::LibraryInterface::openIntegratedLibrary(), etiss::preloadLibraries(), etiss::Configuration::set(), etiss::Configuration::set_cmd_line_boost(), etiss::split(), v, etiss::VERBOSE, etiss::verbosity(), vm, and etiss::WARNING.
Referenced by etiss::forceInitialization(), and etiss::initialize().
etiss_loadIni()
void etiss_loadIni (std::string fileName)
Definition at line 398 of file ETISS.cpp.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::LoadFile(), NULL, and po_simpleIni.
Referenced by inifileload(), and etiss::Initializer::loadIni().
etiss_loadIniConfigs()
void etiss_loadIniConfigs ()
Definition at line 427 of file ETISS.cpp.
References etiss::cfg(), etiss::ERROR, etiss::Configuration::get(), CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::GetAllKeys(), CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::GetAllSections(), CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::GetAllValues(), CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::GetLongValue(), etiss::INFO, etiss::log(), po_simpleIni, etiss::Configuration::set(), etiss::VERBOSE, etiss::verbosity(), vm, and etiss::WARNING.
Referenced by etiss_initialize().
etiss_remove_SIGINT()
static void etiss_remove_SIGINT () static
Definition at line 381 of file ETISS.cpp.
References etiss_prev_SIGINT_handler, and etiss_SIGINT_handler_enabled.
Referenced by etiss_initialize(), and helper_class_etiss_2::~helper_class_etiss_2().
etiss_shutdown()
static void etiss_shutdown () static
Definition at line 885 of file ETISS.cpp.
References etiss::shutdown().
Referenced by helper_class_etiss_1::~helper_class_etiss_1().
etiss_SIGINT_handler()
void etiss_SIGINT_handler (int sig)
TODO etiss::transferCMDControll();
Definition at line 364 of file ETISS.cpp.
inifileload()
std::pair<std::string, std::string> inifileload (const std::string & s)
Definition at line 677 of file ETISS.cpp.
References etiss_loadIni(), and s.
Referenced by etiss_initialize().
Variable Documentation
etiss_defaultjit_
std::string etiss_defaultjit_
Definition at line 72 of file ETISS.cpp.
Referenced by etiss::addLibrary(), and etiss::getDefaultJIT().
etiss_libraries_
std::list<std::shared_ptr<etiss::LibraryInterface> > etiss_libraries_
Definition at line 74 of file ETISS.cpp.
Referenced by etiss::addLibrary(), etiss::getCPUArch(), etiss::getJIT(), etiss::getPlugin(), etiss::listCPUArchs(), etiss::listJITs(), etiss::listLibraries(), etiss::listLibraryPrefixes(), etiss::listPlugins(), and etiss::shutdown().
etiss_libraries_mu_
std::recursive_mutex etiss_libraries_mu_
Definition at line 75 of file ETISS.cpp.
Referenced by etiss::addLibrary(), etiss::getCPUArch(), etiss::getJIT(), etiss::getPlugin(), etiss::listCPUArchs(), etiss::listJITs(), etiss::listLibraries(), etiss::listLibraryPrefixes(), etiss::listPlugins(), and etiss::shutdown().
etiss_prev_SIGINT_handler
void(* etiss_prev_SIGINT_handler) (int)=0
Definition at line 361 of file ETISS.cpp.
Referenced by etiss_remove_SIGINT().
etiss_shutdownOk
bool etiss_shutdownOk = false
Definition at line 904 of file ETISS.cpp.
Referenced by etiss_check_shutdown(), and etiss::shutdown().
etiss_SIGINT_handler_enabled
bool etiss_SIGINT_handler_enabled = false
Definition at line 362 of file ETISS.cpp.
Referenced by etiss_remove_SIGINT().
helper_class_etiss_1
class helper_class_etiss_1 helper_class_etiss_1 static
helper_class_etiss_2
class helper_class_etiss_2 helper_class_etiss_2 static
helper_class_etiss_3
class helper_class_etiss_3 helper_class_etiss_3 static
pluginOptions
std::vector<std::string> pluginOptions = {"plugin.logger.logaddr", "plugin.logger.logmask", "plugin.gdbserver.port"}
Definition at line 78 of file ETISS.cpp.
Referenced by etiss::Initializer::loadIniPlugins().
po_simpleIni
CSimpleIniA* po_simpleIni
Definition at line 397 of file ETISS.cpp.
Referenced by etiss_loadIni(), etiss_loadIniConfigs(), etiss::Initializer::loadIni(), etiss::Initializer::loadIniPlugins(), and etiss::Initializer::~Initializer().
vm
boost::program_options::variables_map vm
Definition at line 77 of file ETISS.cpp.
Referenced by etiss_initialize(), etiss_loadIniConfigs(), and etiss::Initializer::loadIniPlugins().