ETISS 0.8.0: /home/runner/work/etiss/etiss/include/etiss/IntegratedLibrary/SimpleIni/ConvertUTF.h File Reference
ConvertUTF.h File Reference
Macros
#define UNI_REPLACEMENT_CHAR (UTF32)0x0000FFFD
#define UNI_MAX_BMP (UTF32)0x0000FFFF
#define UNI_MAX_UTF16 (UTF32)0x0010FFFF
#define UNI_MAX_UTF32 (UTF32)0x7FFFFFFF
#define UNI_MAX_LEGAL_UTF32 (UTF32)0x0010FFFF
Typedefs
typedef unsigned int UTF32
typedef unsigned short UTF16
typedef unsigned char UTF8
typedef unsigned char Boolean
Enumerations
enum ConversionResult {
conversionOK, sourceExhausted, targetExhausted, sourceIllegal,
conversionOK, sourceExhausted, targetExhausted, sourceIllegal
}
enum ConversionFlags { strictConversion = 0, lenientConversion, strictConversion = 0, lenientConversion }
Functions
ConversionResult ConvertUTF8toUTF16 (const UTF8 **sourceStart, const UTF8 *sourceEnd, UTF16 **targetStart, UTF16 *targetEnd, ConversionFlags flags)
ConversionResult ConvertUTF16toUTF8 (const UTF16 **sourceStart, const UTF16 *sourceEnd, UTF8 **targetStart, UTF8 *targetEnd, ConversionFlags flags)
ConversionResult ConvertUTF8toUTF32 (const UTF8 **sourceStart, const UTF8 *sourceEnd, UTF32 **targetStart, UTF32 *targetEnd, ConversionFlags flags)
ConversionResult ConvertUTF32toUTF8 (const UTF32 **sourceStart, const UTF32 *sourceEnd, UTF8 **targetStart, UTF8 *targetEnd, ConversionFlags flags)
ConversionResult ConvertUTF16toUTF32 (const UTF16 **sourceStart, const UTF16 *sourceEnd, UTF32 **targetStart, UTF32 *targetEnd, ConversionFlags flags)
ConversionResult ConvertUTF32toUTF16 (const UTF32 **sourceStart, const UTF32 *sourceEnd, UTF16 **targetStart, UTF16 *targetEnd, ConversionFlags flags)
Boolean isLegalUTF8Sequence (const UTF8 *source, const UTF8 *sourceEnd)
Macro Definition Documentation
UNI_MAX_BMP
#define UNI_MAX_BMP (UTF32)0x0000FFFF
Definition at line 97 of file ConvertUTF.h.
UNI_MAX_LEGAL_UTF32
#define UNI_MAX_LEGAL_UTF32 (UTF32)0x0010FFFF
Definition at line 100 of file ConvertUTF.h.
UNI_MAX_UTF16
#define UNI_MAX_UTF16 (UTF32)0x0010FFFF
Definition at line 98 of file ConvertUTF.h.
UNI_MAX_UTF32
#define UNI_MAX_UTF32 (UTF32)0x7FFFFFFF
Definition at line 99 of file ConvertUTF.h.
UNI_REPLACEMENT_CHAR
#define UNI_REPLACEMENT_CHAR (UTF32)0x0000FFFD
Definition at line 96 of file ConvertUTF.h.
Typedef Documentation
Boolean
typedef unsigned char Boolean
Definition at line 93 of file ConvertUTF.h.
UTF16
typedef unsigned short UTF16
Definition at line 91 of file ConvertUTF.h.
UTF32
typedef unsigned int UTF32
Definition at line 90 of file ConvertUTF.h.
UTF8
typedef unsigned char UTF8
Definition at line 92 of file ConvertUTF.h.
Enumeration Type Documentation
ConversionFlags
enum ConversionFlags
Enumerator
strictConversion
lenientConversion
strictConversion
lenientConversion
Definition at line 110 of file ConvertUTF.h.
ConversionResult
enum ConversionResult
Enumerator
conversionOK
sourceExhausted
targetExhausted
sourceIllegal
conversionOK
sourceExhausted
targetExhausted
sourceIllegal
Definition at line 102 of file ConvertUTF.h.
Function Documentation
ConvertUTF16toUTF32()
ConversionResult ConvertUTF16toUTF32 (const UTF16 ** sourceStart, const UTF16 * sourceEnd, UTF32 ** targetStart, UTF32 * targetEnd, ConversionFlags flags)
Definition at line 110 of file ConvertUTF.c.
References conversionOK, halfBase, halfShift, sourceExhausted, sourceIllegal, strictConversion, targetExhausted, UNI_SUR_HIGH_END, UNI_SUR_HIGH_START, UNI_SUR_LOW_END, and UNI_SUR_LOW_START.
ConvertUTF16toUTF8()
ConversionResult ConvertUTF16toUTF8 (const UTF16 ** sourceStart, const UTF16 * sourceEnd, UTF8 ** targetStart, UTF8 * targetEnd, ConversionFlags flags)
Definition at line 214 of file ConvertUTF.c.
References conversionOK, firstByteMark, halfBase, halfShift, sourceExhausted, sourceIllegal, strictConversion, targetExhausted, UNI_REPLACEMENT_CHAR, UNI_SUR_HIGH_END, UNI_SUR_HIGH_START, UNI_SUR_LOW_END, and UNI_SUR_LOW_START.
ConvertUTF32toUTF16()
ConversionResult ConvertUTF32toUTF16 (const UTF32 ** sourceStart, const UTF32 * sourceEnd, UTF16 ** targetStart, UTF16 * targetEnd, ConversionFlags flags)
Definition at line 61 of file ConvertUTF.c.
References conversionOK, halfBase, halfMask, halfShift, sourceIllegal, strictConversion, targetExhausted, UNI_MAX_BMP, UNI_MAX_LEGAL_UTF32, UNI_REPLACEMENT_CHAR, UNI_SUR_HIGH_START, UNI_SUR_LOW_END, and UNI_SUR_LOW_START.
ConvertUTF32toUTF8()
ConversionResult ConvertUTF32toUTF8 (const UTF32 ** sourceStart, const UTF32 * sourceEnd, UTF8 ** targetStart, UTF8 * targetEnd, ConversionFlags flags)
Definition at line 409 of file ConvertUTF.c.
References conversionOK, firstByteMark, sourceIllegal, strictConversion, targetExhausted, UNI_MAX_LEGAL_UTF32, UNI_REPLACEMENT_CHAR, UNI_SUR_HIGH_START, and UNI_SUR_LOW_END.
ConvertUTF8toUTF16()
ConversionResult ConvertUTF8toUTF16 (const UTF8 ** sourceStart, const UTF8 * sourceEnd, UTF16 ** targetStart, UTF16 * targetEnd, ConversionFlags flags)
Definition at line 336 of file ConvertUTF.c.
References conversionOK, halfBase, halfMask, halfShift, isLegalUTF8(), offsetsFromUTF8, sourceExhausted, sourceIllegal, strictConversion, targetExhausted, trailingBytesForUTF8, UNI_MAX_BMP, UNI_MAX_UTF16, UNI_REPLACEMENT_CHAR, UNI_SUR_HIGH_START, UNI_SUR_LOW_END, and UNI_SUR_LOW_START.
ConvertUTF8toUTF32()
ConversionResult ConvertUTF8toUTF32 (const UTF8 ** sourceStart, const UTF8 * sourceEnd, UTF32 ** targetStart, UTF32 * targetEnd, ConversionFlags flags)
Definition at line 462 of file ConvertUTF.c.
References conversionOK, isLegalUTF8(), offsetsFromUTF8, sourceExhausted, sourceIllegal, strictConversion, targetExhausted, trailingBytesForUTF8, UNI_MAX_LEGAL_UTF32, UNI_REPLACEMENT_CHAR, UNI_SUR_HIGH_START, and UNI_SUR_LOW_END.
isLegalUTF8Sequence()
Boolean isLegalUTF8Sequence (const UTF8 * source, const UTF8 * sourceEnd)
Definition at line 326 of file ConvertUTF.c.
References isLegalUTF8(), length(), and trailingBytesForUTF8.