ETISS 0.8.0: /home/runner/work/etiss/etiss/src/FastMemory.cpp File Reference
FastMemory.cpp File Reference
#include "etiss/FastMemory.h"
#include "etiss/jit/ReturnCode.h"
#include <cstring>
Functions
static etiss_int32 system_call_iread (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint32 length)
static etiss_int32 system_call_iwrite (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
static etiss_int32 system_call_dread (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
static etiss_int32 system_call_dwrite (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
static etiss_int32 system_call_dbg_read (void *handle, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
static etiss_int32 system_call_dbg_write (void *handle, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
static void system_call_syncTime (void *handle, ETISS_CPU *cpu)
Function Documentation
system_call_dbg_read()
static etiss_int32 system_call_dbg_read (void * handle, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length) static
Definition at line 70 of file FastMemory.cpp.
References length(), and memcpy().
Referenced by etiss::createFastMemory().
system_call_dbg_write()
static etiss_int32 system_call_dbg_write (void * handle, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length) static
Definition at line 76 of file FastMemory.cpp.
References length(), and memcpy().
Referenced by etiss::createFastMemory().
system_call_dread()
static etiss_int32 system_call_dread (void * handle, ETISS_CPU * cpu, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length) static
Definition at line 57 of file FastMemory.cpp.
References length(), and memcpy().
Referenced by etiss::createFastMemory().
system_call_dwrite()
static etiss_int32 system_call_dwrite (void * handle, ETISS_CPU * cpu, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length) static
Definition at line 63 of file FastMemory.cpp.
References length(), and memcpy().
Referenced by etiss::createFastMemory().
system_call_iread()
static etiss_int32 system_call_iread (void * handle, ETISS_CPU * cpu, etiss_uint64 addr, etiss_uint32 length) static
Definition at line 47 of file FastMemory.cpp.
Referenced by etiss::createFastMemory().
system_call_iwrite()
static etiss_int32 system_call_iwrite (void * handle, ETISS_CPU * cpu, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length) static
Definition at line 51 of file FastMemory.cpp.
Referenced by etiss::createFastMemory().
system_call_syncTime()
static void system_call_syncTime (void * handle, ETISS_CPU * cpu) static
Definition at line 82 of file FastMemory.cpp.
Referenced by etiss::createFastMemory().