ETISS 0.8.0: /home/runner/work/etiss/etiss/JITImpl/GCC/GCCJITLIB.cpp File Reference
GCCJITLIB.cpp File Reference
#include "GCCJIT.h"
#include "etiss/Misc.h"
#include "etiss/helper/JITLibrary.h"
Macros
#define ETISS_LIBNAME GCCJIT
Functions
const char * GCCJIT_versionInfo ()
ETISS_LIBRARYIF_VERSION_FUNC_IMPL unsigned GCCJIT_countJIT ()
const char * GCCJIT_nameJIT (unsigned i)
etiss::JIT * GCCJIT_createJIT (unsigned i, std::map< std::string, std::string > options)
void GCCJIT_deleteJIT (etiss::JIT *jit)
Macro Definition Documentation
ETISS_LIBNAME
#define ETISS_LIBNAME GCCJIT
Definition at line 45 of file GCCJITLIB.cpp.
Function Documentation
GCCJIT_countJIT()
ETISS_LIBRARYIF_VERSION_FUNC_IMPL unsigned GCCJIT_countJIT ()
Definition at line 58 of file GCCJITLIB.cpp.
GCCJIT_createJIT()
etiss::JIT* GCCJIT_createJIT (unsigned i, std::map< std::string, std::string > options)
Definition at line 62 of file GCCJITLIB.cpp.
References etiss::cfg(), etiss::Configuration::config(), etiss::Configuration::get(), and options.
GCCJIT_deleteJIT()
void GCCJIT_deleteJIT (etiss::JIT * jit)
Definition at line 69 of file GCCJITLIB.cpp.
GCCJIT_nameJIT()
const char* GCCJIT_nameJIT (unsigned i)
Definition at line 60 of file GCCJITLIB.cpp.
GCCJIT_versionInfo()
const char* GCCJIT_versionInfo ()
Definition at line 53 of file GCCJITLIB.cpp.