ETISS 0.8.0: /home/runner/work/etiss/etiss/src/IntegratedLibrary/gdb/GDBConnection.cpp File Reference
GDBConnection.cpp File Reference
implementation of etiss/IntegratedLibrary/gdb/GDBConnection.h
#include "etiss/IntegratedLibrary/gdb/GDBConnection.h"
#include "etiss/IntegratedLibrary/gdb/Hex.h"
#include "etiss/jit/types.h"
#include <iostream>
#include <chrono>
#include <thread>
Functions
size_t PacketProtocol_findUE (std::string &buffer, char c)
int PacketProtocol_findResponse (std::string &buffer)
size_t PacketProtocol_getPacketStart (std::string &buffer)
bool PacketProtocol_startsWith (const std::string &str, const std::string &prefix)
Detailed Description
implementation of etiss/IntegratedLibrary/gdb/GDBConnection.h
Copyright
Copyright 2018 Infineon Technologies AG
This file is part of ETISS tool, see https://github.com/tum-ei-eda/etiss.
The initial version of this software has been created with the funding support by the German Federal
Ministry of Education and Research (BMBF) in the project EffektiV under grant 01IS13022.
Redistribution and use in source and binary forms, with or without modification, are permitted
provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and
the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions
and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse
or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
Author
Marc Greim marc..nosp@m.grei.nosp@m.m@myt.nosp@m.um.d.nosp@m.e, Chair of Electronic Design Automation, TUM
Date
July 29, 2014
Version
0.1
Definition in file GDBConnection.cpp.
Function Documentation
PacketProtocol_findResponse()
int PacketProtocol_findResponse (std::string & buffer)
Definition at line 92 of file GDBConnection.cpp.
References int, PacketProtocol_findUE(), and stream_code_info.
Referenced by etiss::plugin::gdb::PacketProtocol::snd().
PacketProtocol_findUE()
size_t PacketProtocol_findUE (std::string & buffer, char c)
Definition at line 77 of file GDBConnection.cpp.
References c.
Referenced by PacketProtocol_findResponse(), PacketProtocol_getPacketStart(), and etiss::plugin::gdb::PacketProtocol::tryReadPacket().
PacketProtocol_getPacketStart()
size_t PacketProtocol_getPacketStart (std::string & buffer)
Definition at line 123 of file GDBConnection.cpp.
References PacketProtocol_findUE().
PacketProtocol_startsWith()
bool PacketProtocol_startsWith (const std::string & str, const std::string & prefix)
Definition at line 144 of file GDBConnection.cpp.