ETISS 0.8.0: /home/runner/work/etiss/etiss/src/IntegratedLibrary/gdb/GDBServer.cpp File Reference
GDBServer.cpp File Reference
implementation of etiss/IntegratedLibrary/gdb/GDBServer.h
#include "etiss/IntegratedLibrary/gdb/GDBServer.h"
#include "etiss/CPUCore.h"
#include "etiss/IntegratedLibrary/gdb/Hex.h"
#include "etiss/IntegratedLibrary/gdb/UnixTCPGDBConnection.h"
#include "etiss/jit/types.h"
#include <chrono>
#include <cstring>
#include <thread>
Functions
static void Server_finalizeInstrSet (etiss::instr::InstructionSet *set, std::string pcode)
etiss_int32 gdb_pre_instruction (ETISS_CPU *cpu, ETISS_System *system, void *gdbserver)
void gdb_pre_instruction_noreturn (ETISS_CPU *, ETISS_System *, void *gdbserver)
Detailed Description
implementation of etiss/IntegratedLibrary/gdb/GDBServer.h
Copyright
Copyright 2018 Infineon Technologies AG
This file is part of ETISS tool, see https://github.com/tum-ei-eda/etiss.
The initial version of this software has been created with the funding support by the German Federal
Ministry of Education and Research (BMBF) in the project EffektiV under grant 01IS13022.
Redistribution and use in source and binary forms, with or without modification, are permitted
provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and
the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions
and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse
or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
Author
Marc Greim marc..nosp@m.grei.nosp@m.m@myt.nosp@m.um.d.nosp@m.e, Chair of Electronic Design Automation, TUM
Date
July 29, 2014
Version
0.1
Definition in file GDBServer.cpp.
Function Documentation
gdb_pre_instruction()
etiss_int32 gdb_pre_instruction (ETISS_CPU * cpu, ETISS_System * system, void * gdbserver)
Definition at line 898 of file GDBServer.cpp.
gdb_pre_instruction_noreturn()
void gdb_pre_instruction_noreturn (ETISS_CPU * , ETISS_System * , void * gdbserver)
Todo:
fix possible exception loss
Definition at line 902 of file GDBServer.cpp.
Server_finalizeInstrSet()
static void Server_finalizeInstrSet (etiss::instr::InstructionSet * set, std::string pcode) static
TODO? ensure instruction pointer update
Definition at line 248 of file GDBServer.cpp.
References etiss::instr::Instruction::addCallback(), etiss::CodePart::code(), etiss::instr::InstructionSet::foreach(), etiss::CodePart::PREINITIALDEBUGRETURNING, and etiss::CodeSet::prepend().
Referenced by etiss::plugin::gdb::Server::finalizeInstrSet().