ETISS 0.8.0: ETISS_Frontend
ETISS_Frontend
Classes
class etiss::Initializer
Wrapper for the initialize and shutdown of the ETISS environment.
Functions
std::set< std::string > etiss::listCPUArchs ()
Create a set with all identifier names of the known CPUArch plug-ins.
std::set< std::string > etiss::listJITs ()
Create a set with all identifier names of the known JIT plug-ins.
std::set< std::string > etiss::listPlugins ()
Create a set with all identifier names of the known plug-ins.
void etiss::preloadLibraries ()
Search and try to load libraries.
std::shared_ptr< JIT > etiss::getJIT (std::string name, std::map< std::string, std::string > options=std::map< std::string, std::string >())
Get a present JIT plug-in by name.
std::shared_ptr< CPUArch > etiss::getCPUArch (std::string name, std::map< std::string, std::string > options=std::map< std::string, std::string >())
Get a present CPUArch plug-in by name.
std::shared_ptr< Plugin > etiss::getPlugin (std::string name, std::map< std::string, std::string > options=std::map< std::string, std::string >())
Get a present Plugin plug-in by name.
bool etiss::loadLibrary (std::string path, std::string name)
Load a library.
void etiss::addLibrary (std::shared_ptr< etiss::LibraryInterface > libInterface)
Add a LibraryInterface to the ETISS environment.
std::set< std::string > etiss::listLibraries ()
Create a set with strings of the library names and some information appended in square brackets.
std::set< std::string > etiss::listLibraryPrefixes ()
Create a set with strings of the library names.
void etiss::initialize (std::vector< std::string > &args)
Initialize and configure ETISS.
std::shared_ptr< etiss::JIT > etiss::getDefaultJIT ()
Get the default JIT implementation.
void etiss::shutdown ()
Shutdown ETISS.
std::string etiss::errorMessage (etiss::int32 code, CPUArch *arch=0)
Get the error message for an error code for a specific CPUArch plug-in.
Detailed Description
Function Documentation
addLibrary()
void etiss::addLibrary (std::shared_ptr< etiss::LibraryInterface > libInterface)
Add a LibraryInterface to the ETISS environment.
Before a library can be use within ETISS the library needs to be added to ETISS.
Parameters
interface Pointer to the LibraryInterface of the library to be added.
See also
LibraryInteface.h
Definition at line 312 of file ETISS.cpp.
References etiss::LibraryInterface::countJITs(), etiss_defaultjit_, etiss_libraries_, etiss_libraries_mu_, etiss::forceInitialization(), and etiss::LibraryInterface::nameJIT().
Referenced by etiss_initialize(), and etiss::loadLibrary().
errorMessage()
std::string etiss::errorMessage (etiss::int32 code, CPUArch * arch = 0)
Get the error message for an error code for a specific CPUArch plug-in.
Todo:
add error message interface to etiss::CPUArch
Todo:
add error message interface to etiss::CPUArch
TODO: cpu arch error message function
Definition at line 983 of file ETISS.cpp.
References etiss::CPUArch::getName().
getCPUArch()
std::shared_ptr< CPUArch > etiss::getCPUArch (std::string name, std::map< std::string, std::string > options = std::map<std::string, std::string>())
Get a present CPUArch plug-in by name.
Parameters
name String of the plug-in name.
options A key value map with the options required to load the plug-in.
Returns
Pointer to the plug-in.
Definition at line 208 of file ETISS.cpp.
References etiss::LibraryInterface::countCPUArchs(), etiss::LibraryInterface::createCPUArch(), etiss::LibraryInterface::deleteCPUArch(), etiss::ERROR, etiss_libraries_, etiss_libraries_mu_, etiss::LibraryInterface::getName(), etiss::LibraryInterface::isEmpty(), etiss::log(), name, etiss::LibraryInterface::nameCPUArch(), and options.
Referenced by etiss::CPUCore::create().
getDefaultJIT()
std::shared_ptr< etiss::JIT > etiss::getDefaultJIT ()
Get the default JIT implementation.
The default JIT implementation, is the first loaded JIT plug-in.
Returns
Pointer to the JIT plug-in.
Definition at line 355 of file ETISS.cpp.
References etiss_defaultjit_, and etiss::getJIT().
Referenced by etiss::CPUCore::execute().
getJIT()
std::shared_ptr< JIT > etiss::getJIT (std::string name, std::map< std::string, std::string > options = std::map<std::string, std::string>())
Get a present JIT plug-in by name.
Parameters
name String of the plug-in name.
options A key value map with the options required to load the plug-in.
Returns
Pointer to the plug-in.
Definition at line 164 of file ETISS.cpp.
References etiss::LibraryInterface::countJITs(), etiss::LibraryInterface::createJIT(), etiss::LibraryInterface::deleteJIT(), etiss::ERROR, etiss_libraries_, etiss_libraries_mu_, etiss::LibraryInterface::getName(), etiss::LibraryInterface::isEmpty(), etiss::log(), name, etiss::LibraryInterface::nameJIT(), and options.
Referenced by etiss::getDefaultJIT(), and etiss::Initializer::loadIniJIT().
getPlugin()
std::shared_ptr< Plugin > etiss::getPlugin (std::string name, std::map< std::string, std::string > options = std::map<std::string, std::string>())
Get a present Plugin plug-in by name.
Parameters
name String of the plug-in name.
options A key value map with the options required to load the plug-in.
Returns
Pointer to the plug-in.
Definition at line 252 of file ETISS.cpp.
References etiss::LibraryInterface::countPlugins(), etiss::LibraryInterface::createPlugin(), etiss::LibraryInterface::deletePlugin(), etiss::ERROR, etiss_libraries_, etiss_libraries_mu_, etiss::LibraryInterface::getName(), etiss::INFO, etiss::LibraryInterface::isEmpty(), etiss::log(), name, etiss::LibraryInterface::namePlugin(), and options.
Referenced by etiss::Initializer::loadIniPlugins().
initialize()
void etiss::initialize (std::vector< std::string > & args)
Initialize and configure ETISS.
Attention
It is recommended to use etiss::Initializer instead of calling etiss::initialize / etiss::shutdown manually
Definition at line 873 of file ETISS.cpp.
References etiss_initialize().
Referenced by etiss::Initializer::Initializer().
listCPUArchs()
std::set< std::string > etiss::listCPUArchs ()
Create a set with all identifier names of the known CPUArch plug-ins.
See also
CPUArch
Returns
A set with the identifier strings.
Definition at line 80 of file ETISS.cpp.
References etiss::ERROR, etiss_libraries_, etiss_libraries_mu_, and etiss::log().
listJITs()
std::set< std::string > etiss::listJITs ()
Create a set with all identifier names of the known JIT plug-ins.
See also
JIT
Returns
A set with the identifier strings.
Definition at line 108 of file ETISS.cpp.
References etiss::ERROR, etiss_libraries_, etiss_libraries_mu_, and etiss::log().
listLibraries()
std::set< std::string > etiss::listLibraries ()
Create a set with strings of the library names and some information appended in square brackets.
Note
Use etiss::listLibraryPrefixes to get the raw library names.
Returns
A set with the strings.
Definition at line 333 of file ETISS.cpp.
References etiss_libraries_, and etiss_libraries_mu_.
listLibraryPrefixes()
std::set< std::string > etiss::listLibraryPrefixes ()
Create a set with strings of the library names.
The library names are also required to be used as prefixes to symbols (library name + '_': e.g. ETISSINCLUDED_exportedSymbol).
Returns
A set with the strings.
Definition at line 344 of file ETISS.cpp.
References etiss_libraries_, and etiss_libraries_mu_.
listPlugins()
std::set< std::string > etiss::listPlugins ()
Create a set with all identifier names of the known plug-ins.
See also
Plugin
Returns
A set with the identifier strings.
Definition at line 136 of file ETISS.cpp.
References etiss::ERROR, etiss_libraries_, etiss_libraries_mu_, and etiss::log().
loadLibrary()
bool etiss::loadLibrary (std::string path, std::string name)
Load a library.
The library needs to be an implementation of etiss::CPUArch, etiss::JIT or etiss::Plugin. A Library interface is created for the library with etiss::LibraryInterface::openSharedLibrary and added to the ETISS environment with etiss::addLibrary.
Parameters
path String of the library location. E.g. "/path/to/lib"
name String of the library name. The library name is the file name of the library without the lib prefix and the file extension. E.g. for libOR1KArch.so the name is OR1KArch.
Returns
True if the operation was successful or false otherwise.
Definition at line 299 of file ETISS.cpp.
References etiss::addLibrary(), name, and etiss::LibraryInterface::openSharedLibrary().
Referenced by loadLibraryList(), and etiss::preloadLibraries().
preloadLibraries()
void etiss::preloadLibraries ()
Search and try to load libraries.
This function is called automatically by CPUCore::create(1).
See also
ETISSInit.cpp
Definition at line 192 of file ETISSInit.cpp.
References etiss::cfg(), etiss_preload_libraries, findLibs(), etiss::Configuration::get(), etiss::installDir(), etiss::loadLibrary(), and loadLibraryList().
Referenced by etiss_initialize().
shutdown()
void etiss::shutdown ()
Shutdown ETISS.
This function shutsdown the ETISS environment. All used libraries are unloaded and the used resources are released.
Attention
It is recommende to use etiss::Initializer instead of calling etiss::initialize / etiss::shutdown manually
Definition at line 906 of file ETISS.cpp.
References etiss::fault::Stressor::clear(), etiss::ERROR, etiss_libraries_, etiss_libraries_mu_, etiss_shutdownOk, etiss::LibraryInterface::getName(), etiss::CPUCore::list(), etiss::log(), and etiss::py::shutdown().
Referenced by etiss_shutdown(), etiss::shutdown(), and etiss::Initializer::~Initializer().