ETISS 0.8.0: include/jit/clang_stdlib/immintrin.h File Reference
immintrin.h File Reference
#include <mmintrin.h>
#include <xmmintrin.h>
#include <emmintrin.h>
#include <pmmintrin.h>
#include <tmmintrin.h>
#include <smmintrin.h>
#include <wmmintrin.h>
#include <clflushoptintrin.h>
#include <clwbintrin.h>
#include <avxintrin.h>
#include <avx2intrin.h>
#include <f16cintrin.h>
#include <vpclmulqdqintrin.h>
#include <bmiintrin.h>
#include <bmi2intrin.h>
#include <lzcntintrin.h>
#include <popcntintrin.h>
#include <fmaintrin.h>
#include <avx512fintrin.h>
#include <avx512vlintrin.h>
#include <avx512bwintrin.h>
#include <avx512bitalgintrin.h>
#include <avx512cdintrin.h>
#include <avx512vpopcntdqintrin.h>
#include <avx512vpopcntdqvlintrin.h>
#include <avx512vnniintrin.h>
#include <avx512vlvnniintrin.h>
#include <avx512dqintrin.h>
#include <avx512vlbitalgintrin.h>
#include <avx512vlbwintrin.h>
#include <avx512vlcdintrin.h>
#include <avx512vldqintrin.h>
#include <avx512erintrin.h>
#include <avx512ifmaintrin.h>
#include <avx512ifmavlintrin.h>
#include <avx512vbmiintrin.h>
#include <avx512vbmivlintrin.h>
#include <avx512vbmi2intrin.h>
#include <avx512vlvbmi2intrin.h>
#include <avx512pfintrin.h>
#include <avx512bf16intrin.h>
#include <avx512vlbf16intrin.h>
#include <pkuintrin.h>
#include <vaesintrin.h>
#include <gfniintrin.h>
#include <rtmintrin.h>
#include <xtestintrin.h>
#include <shaintrin.h>
#include <fxsrintrin.h>
#include <xsaveintrin.h>
#include <xsaveoptintrin.h>
#include <xsavecintrin.h>
#include <xsavesintrin.h>
#include <cetintrin.h>
#include <adxintrin.h>
#include <rdseedintrin.h>
#include <wbnoinvdintrin.h>
#include <cldemoteintrin.h>
#include <waitpkgintrin.h>
#include <movdirintrin.h>
#include <pconfigintrin.h>
#include <sgxintrin.h>
#include <ptwriteintrin.h>
#include <invpcidintrin.h>
#include <amxintrin.h>
#include <avx512vp2intersectintrin.h>
#include <avx512vlvp2intersectintrin.h>
#include <enqcmdintrin.h>
#include <serializeintrin.h>
#include <tsxldtrkintrin.h>
Functions
static __inline__ unsigned int __attribute__ ((__always_inline__, __nodebug__, __target__("rdpid"))) _rdpid_u32(void)
Returns the value of the IA32_TSC_AUX MSR (0xc0000103).
static __inline__ int __attribute__ ((__always_inline__, __nodebug__, __target__("rdrnd"))) _rdrand16_step(unsigned short *__p)
static __inline__ short __attribute__ ((__always_inline__, __nodebug__, __target__("movbe"))) _loadbe_i16(void const *__P)
Variables
static __inline__ void short __D
struct __storeu_i16 *__P __v = __builtin_bswap16(__D)
Function Documentation
__attribute__() [1/3]
static __inline__ short __attribute__ ((__always_inline__, __nodebug__, __target__("movbe"))) const static
Definition at line 335 of file immintrin.h.
References __attribute__(), and __v.
__attribute__() [2/3]
static __inline__ unsigned int __attribute__ ((__always_inline__, __nodebug__, __target__("rdpid"))) static
Returns the value of the IA32_TSC_AUX MSR (0xc0000103).
This intrinsic corresponds to the RDPID instruction.
Definition at line 243 of file immintrin.h.
Referenced by __attribute__().
__attribute__() [3/3]
static __inline__ int __attribute__ ((__always_inline__, __nodebug__, __target__("rdrnd"))) static
Definition at line 251 of file immintrin.h.
References __p.
Variable Documentation
__D
__inline__ void int __D
Initial value:
{
  struct __storeu_i16 {
    short __v;
  } __attribute__((__packed__, __may_alias__))
Definition at line 344 of file immintrin.h.
__v
struct __storeu_i32 *__P __v = __builtin_bswap16(__D)
Definition at line 348 of file immintrin.h.
Referenced by __attribute__(), __dAtomicAdd(), __dAtomicAdd_block(), __dAtomicAdd_system(), __fAtomicAdd(), __fAtomicAdd_block(), __fAtomicAdd_system(), __fAtomicExch(), __fAtomicExch_block(), __fAtomicExch_system(), __iAtomicAdd(), __iAtomicAdd_block(), __iAtomicAdd_system(), __iAtomicAnd(), __iAtomicAnd_block(), __iAtomicAnd_system(), __iAtomicCAS(), __iAtomicCAS_block(), __iAtomicCAS_system(), __iAtomicExch(), __iAtomicExch_block(), __iAtomicExch_system(), __iAtomicMax(), __iAtomicMax_block(), __iAtomicMax_system(), __iAtomicMin(), __iAtomicMin_block(), __iAtomicMin_system(), __iAtomicOr(), __iAtomicOr_block(), __iAtomicOr_system(), __iAtomicXor(), __iAtomicXor_block(), __iAtomicXor_system(), __illAtomicMax(), __illAtomicMax_block(), __illAtomicMax_system(), __illAtomicMin(), __illAtomicMin_block(), __illAtomicMin_system(), __llAtomicAnd(), __llAtomicAnd_block(), __llAtomicAnd_system(), __llAtomicOr(), __llAtomicOr_block(), __llAtomicOr_system(), __llAtomicXor(), __llAtomicXor_block(), __llAtomicXor_system(), __uAtomicAdd(), __uAtomicAdd_block(), __uAtomicAdd_system(), __uAtomicAnd(), __uAtomicAnd_block(), __uAtomicAnd_system(), __uAtomicCAS(), __uAtomicCAS_block(), __uAtomicCAS_system(), __uAtomicDec(), __uAtomicDec_block(), __uAtomicDec_system(), __uAtomicExch(), __uAtomicExch_block(), __uAtomicExch_system(), __uAtomicInc(), __uAtomicInc_block(), __uAtomicInc_system(), __uAtomicMax(), __uAtomicMax_block(), __uAtomicMax_system(), __uAtomicMin(), __uAtomicMin_block(), __uAtomicMin_system(), __uAtomicOr(), __uAtomicOr_block(), __uAtomicOr_system(), __uAtomicXor(), __uAtomicXor_block(), __uAtomicXor_system(), __ullAtomicAdd(), __ullAtomicAdd_block(), __ullAtomicAdd_system(), __ullAtomicAnd(), __ullAtomicAnd_block(), __ullAtomicAnd_system(), __ullAtomicCAS(), __ullAtomicCAS_block(), __ullAtomicCAS_system(), __ullAtomicExch(), __ullAtomicExch_block(), __ullAtomicExch_system(), __ullAtomicMax(), __ullAtomicMax_block(), __ullAtomicMax_system(), __ullAtomicMin(), __ullAtomicMin_block(), __ullAtomicMin_system(), __ullAtomicOr(), __ullAtomicOr_block(), __ullAtomicOr_system(), __ullAtomicXor(), __ullAtomicXor_block(), __ullAtomicXor_system(), _cvtsh_ss(), _mm256_loadu_epi16(), _mm256_loadu_epi32(), _mm256_loadu_epi64(), _mm256_loadu_epi8(), _mm256_loadu_pd(), _mm256_loadu_ps(), _mm256_loadu_si256(), _mm256_storeu_epi16(), _mm256_storeu_epi32(), _mm256_storeu_epi64(), _mm256_storeu_epi8(), _mm256_storeu_pd(), _mm256_storeu_ps(), _mm256_storeu_si256(), _mm512_loadu_epi16(), _mm512_loadu_epi32(), _mm512_loadu_epi64(), _mm512_loadu_epi8(), _mm512_loadu_pd(), _mm512_loadu_ps(), _mm512_loadu_si512(), _mm512_storeu_epi16(), _mm512_storeu_epi32(), _mm512_storeu_epi64(), _mm512_storeu_epi8(), _mm512_storeu_pd(), _mm512_storeu_ps(), _mm512_storeu_si512(), _mm_loadu_epi16(), _mm_loadu_epi32(), _mm_loadu_epi64(), _mm_loadu_epi8(), _mm_loadu_pd(), _mm_loadu_ps(), _mm_loadu_si128(), _mm_loadu_si16(), _mm_loadu_si32(), _mm_loadu_si64(), _mm_storeu_epi16(), _mm_storeu_epi32(), _mm_storeu_epi64(), _mm_storeu_epi8(), _mm_storeu_pd(), _mm_storeu_ps(), _mm_storeu_si128(), _mm_storeu_si16(), _mm_storeu_si32(), _mm_storeu_si64(), wasm_i16x8_load_8x8(), wasm_i32x4_load_16x4(), wasm_i64x2_load_32x2(), wasm_u16x8_load_8x8(), wasm_u32x4_load_16x4(), wasm_u64x2_load_32x2(), wasm_v128_load(), wasm_v128_store(), wasm_v16x8_load_splat(), wasm_v32x4_load_splat(), wasm_v64x2_load_splat(), and wasm_v8x16_load_splat().