ETISS 0.8.0: /home/runner/work/etiss/etiss/src/IntegratedLibrary.cpp File Reference
IntegratedLibrary.cpp File Reference
example implementation of a dynamic library interface that is used to provide access to integrated plugins. Other dynamic libraries should be implemented like this
#include "etiss/helper/CPUArchLibrary.h"
#include "etiss/helper/JITLibrary.h"
#include "etiss/helper/PluginLibrary.h"
#include "etiss/LibraryInterface.h"
#include "etiss/IntegratedLibrary/Logger.h"
#include "etiss/IntegratedLibrary/PrintInstruction.h"
#include "etiss/IntegratedLibrary/errorInjection/Plugin.h"
#include "etiss/IntegratedLibrary/gdb/GDBServer.h"
Macros
#define ETISS_LIBNAME ETISSINCLUDED
Functions
ETISS_LIBRARYIF_VERSION_FUNC_IMPL unsigned ETISSINCLUDED_countJIT ()
unsigned ETISSINCLUDED_countCPUArch ()
unsigned ETISSINCLUDED_countPlugin ()
const char * ETISSINCLUDED_nameJIT (unsigned index)
const char * ETISSINCLUDED_nameCPUArch (unsigned index)
const char * ETISSINCLUDED_namePlugin (unsigned index)
etiss::JIT * ETISSINCLUDED_createJIT (unsigned index, std::map< std::string, std::string > options)
etiss::CPUArch * ETISSINCLUDED_createCPUArch (unsigned index, std::map< std::string, std::string > options)
etiss::Plugin * ETISSINCLUDED_createPlugin (unsigned index, std::map< std::string, std::string > options)
void ETISSINCLUDED_deleteJIT (etiss::JIT *o)
void ETISSINCLUDED_deleteCPUArch (etiss::CPUArch *o)
void ETISSINCLUDED_deletePlugin (etiss::Plugin *o)
Detailed Description
example implementation of a dynamic library interface that is used to provide access to integrated plugins. Other dynamic libraries should be implemented like this
Copyright
Copyright 2018 Infineon Technologies AG
This file is part of ETISS tool, see https://github.com/tum-ei-eda/etiss.
The initial version of this software has been created with the funding support by the German Federal
Ministry of Education and Research (BMBF) in the project EffektiV under grant 01IS13022.
Redistribution and use in source and binary forms, with or without modification, are permitted
provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and
the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions
and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse
or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
Author
Marc Greim marc..nosp@m.grei.nosp@m.m@myt.nosp@m.um.d.nosp@m.e, Chair of Electronic Design Automation, TUM
Date
July 29, 2014
Version
0.1
Definition in file IntegratedLibrary.cpp.
Macro Definition Documentation
ETISS_LIBNAME
#define ETISS_LIBNAME ETISSINCLUDED
Definition at line 54 of file IntegratedLibrary.cpp.
Function Documentation
ETISSINCLUDED_countCPUArch()
unsigned ETISSINCLUDED_countCPUArch ()
Definition at line 75 of file IntegratedLibrary.cpp.
Referenced by IntegratedLibrary::countCPUArchs().
ETISSINCLUDED_countJIT()
ETISS_LIBRARYIF_VERSION_FUNC_IMPL unsigned ETISSINCLUDED_countJIT ()
Definition at line 73 of file IntegratedLibrary.cpp.
Referenced by IntegratedLibrary::countJITs().
ETISSINCLUDED_countPlugin()
unsigned ETISSINCLUDED_countPlugin ()
Definition at line 77 of file IntegratedLibrary.cpp.
Referenced by IntegratedLibrary::countPlugins().
ETISSINCLUDED_createCPUArch()
etiss::CPUArch* ETISSINCLUDED_createCPUArch (unsigned index, std::map< std::string, std::string > options)
Definition at line 101 of file IntegratedLibrary.cpp.
Referenced by IntegratedLibrary::createCPUArch().
ETISSINCLUDED_createJIT()
etiss::JIT* ETISSINCLUDED_createJIT (unsigned index, std::map< std::string, std::string > options)
Definition at line 99 of file IntegratedLibrary.cpp.
Referenced by IntegratedLibrary::createJIT().
ETISSINCLUDED_createPlugin()
etiss::Plugin* ETISSINCLUDED_createPlugin (unsigned index, std::map< std::string, std::string > options)
expected option format: -rREGISTERNAME -> FILEPATH (e.g. -rR4 -> /home/you/registerErrors.txt)
Definition at line 106 of file IntegratedLibrary.cpp.
References etiss::cfg(), etiss::Configuration::config(), etiss::plugin::gdb::Server::createTCPServer(), etiss::Configuration::get(), etiss::log(), options, etiss::plugin::errorInjection::BlockAccurateHandler::parseFile(), and etiss::WARNING.
Referenced by IntegratedLibrary::createPlugin().
ETISSINCLUDED_deleteCPUArch()
void ETISSINCLUDED_deleteCPUArch (etiss::CPUArch * o)
Definition at line 146 of file IntegratedLibrary.cpp.
ETISSINCLUDED_deleteJIT()
void ETISSINCLUDED_deleteJIT (etiss::JIT * o)
Definition at line 144 of file IntegratedLibrary.cpp.
ETISSINCLUDED_deletePlugin()
void ETISSINCLUDED_deletePlugin (etiss::Plugin * o)
Definition at line 148 of file IntegratedLibrary.cpp.
ETISSINCLUDED_nameCPUArch()
const char* ETISSINCLUDED_nameCPUArch (unsigned index)
Definition at line 81 of file IntegratedLibrary.cpp.
Referenced by IntegratedLibrary::nameCPUArch().
ETISSINCLUDED_nameJIT()
const char* ETISSINCLUDED_nameJIT (unsigned index)
Definition at line 79 of file IntegratedLibrary.cpp.
Referenced by IntegratedLibrary::nameJIT().
ETISSINCLUDED_namePlugin()
const char* ETISSINCLUDED_namePlugin (unsigned index)
Definition at line 83 of file IntegratedLibrary.cpp.
Referenced by IntegratedLibrary::namePlugin().