ETISS 0.8.0: etiss::mm Namespace Reference
etiss::mm Namespace Reference
Classes
class DMMUWrapper
struct DMMUWrapperSystem
class MMU
class PTE
Page Table Entry (PTE) defines the composition of Page Frame Number (PFN) and relavant flags.
class PTEFormat
class PTEFormatBuilder
Sigleton builder utility to build up customized PTE format.
class TLB
Typedefs
typedef int32_t(* handler_ptr) (int32_t fault, MMU *mmu, uint64_t vma, MM_ACCESS access)
typedef std::map< std::string, std::pair< uint32_t, uint32_t > > PTEFormatMap
Singleton to represent specific PTE format, every PTE uses this singleton to parse raw PTE value into PPN and protection flags, read/write PPN or flags.
Enumerations
enum MM_ACCESS {
R_ACCESS, W_ACCESS, X_ACCESS, R_ACCESS,
W_ACCESS, X_ACCESS
}
enum MM_ACCESS {
R_ACCESS, W_ACCESS, X_ACCESS, R_ACCESS,
W_ACCESS, X_ACCESS
}
Functions
int32_t tlb_miss_handler (int32_t fault, MMU *mmu, uint64_t vma, MM_ACCESS access)
void DUMP_MMU (MMU *mmu)
static etiss_int32 iread (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint32 length)
static etiss_int32 iwrite (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
static etiss_int32 dread (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
static etiss_int32 dwrite (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
static etiss_int32 dbg_read (void *handle, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
static etiss_int32 dbg_write (void *handle, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
static void syncTime (void *handle, ETISS_CPU *cpu)
static int32_t page_fault_ni_ (int32_t fault, MMU *mmu, uint64_t, MM_ACCESS)
Variables
const MM_EXPORT int32_t NOERROR
const MM_EXPORT int32_t PTEOVERLAP
const MM_EXPORT int32_t TLBMISS
const MM_EXPORT int32_t PTENOTEXISTED
const MM_EXPORT int32_t TLBISFULL
const MM_EXPORT int32_t PROTECTIONVIALATION
MM_EXPORT std::string PAGE_FAULT_MSG []
MM_EXPORT handler_ptr page_fault_handler []
Typedef Documentation
handler_ptr
typedef int32_t(* etiss::mm::handler_ptr)(int32_t fault, MMU *mmu, uint64_t vma, MM_ACCESS access)
Definition at line 72 of file PageFaultVector.h.
PTEFormatMap
typedef std::map< std::string, std::pair< uint32_t, uint32_t > > etiss::mm::PTEFormatMap
Singleton to represent specific PTE format, every PTE uses this singleton to parse raw PTE value into PPN and protection flags, read/write PPN or flags.
Definition at line 62 of file PTEFormat.h.
Enumeration Type Documentation
MM_ACCESS [1/2]
enum etiss::mm::MM_ACCESS
Enumerator
R_ACCESS
W_ACCESS
X_ACCESS
R_ACCESS
W_ACCESS
X_ACCESS
Definition at line 62 of file PageFaultVector.h.
MM_ACCESS [2/2]
enum etiss::mm::MM_ACCESS
Enumerator
R_ACCESS
W_ACCESS
X_ACCESS
R_ACCESS
W_ACCESS
X_ACCESS
Definition at line 62 of file PageFaultVector.h.
Function Documentation
dbg_read()
static etiss_int32 etiss::mm::dbg_read (void * handle, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length) static
Definition at line 131 of file DMMUWrapper.cpp.
References ETISS_System::dbg_read, ETISS_System::handle, length(), etiss::mm::DMMUWrapperSystem::orig, etiss::mm::DMMUWrapperSystem::this_, etiss::mm::MMU::Translate(), unlikely, and X_ACCESS.
Referenced by etiss::mm::DMMUWrapper::wrap().
dbg_write()
static etiss_int32 etiss::mm::dbg_write (void * handle, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length) static
Definition at line 147 of file DMMUWrapper.cpp.
References ETISS_System::dbg_write, ETISS_System::handle, length(), etiss::log(), etiss::mm::DMMUWrapperSystem::orig, etiss::mm::DMMUWrapperSystem::this_, etiss::mm::MMU::Translate(), unlikely, etiss::VERBOSE, and W_ACCESS.
Referenced by etiss::mm::DMMUWrapper::wrap().
dread()
static etiss_int32 etiss::mm::dread (void * handle, ETISS_CPU * cpu, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length) static
Definition at line 97 of file DMMUWrapper.cpp.
References ETISS_System::dread, ETISS_System::handle, length(), etiss::mm::DMMUWrapperSystem::orig, R_ACCESS, etiss::mm::DMMUWrapperSystem::this_, etiss::mm::MMU::Translate(), and unlikely.
Referenced by etiss::mm::DMMUWrapper::wrap().
DUMP_MMU()
void etiss::mm::DUMP_MMU (MMU * mmu)
Definition at line 244 of file MMU.cpp.
References etiss::mm::MMU::Dump().
Referenced by page_fault_ni_().
dwrite()
static etiss_int32 etiss::mm::dwrite (void * handle, ETISS_CPU * cpu, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length) static
Definition at line 114 of file DMMUWrapper.cpp.
References ETISS_System::dwrite, ETISS_System::handle, length(), etiss::mm::DMMUWrapperSystem::orig, etiss::mm::DMMUWrapperSystem::this_, etiss::mm::MMU::Translate(), unlikely, and W_ACCESS.
Referenced by etiss::mm::DMMUWrapper::wrap().
iread()
static etiss_int32 etiss::mm::iread (void * handle, ETISS_CPU * cpu, etiss_uint64 addr, etiss_uint32 length) static
Definition at line 59 of file DMMUWrapper.cpp.
References ETISS_System::handle, ETISS_System::iread, length(), etiss::log(), etiss::mm::DMMUWrapperSystem::orig, R_ACCESS, etiss::mm::DMMUWrapperSystem::this_, etiss::mm::MMU::Translate(), unlikely, and etiss::VERBOSE.
Referenced by etiss::mm::DMMUWrapper::wrap().
iwrite()
static etiss_int32 etiss::mm::iwrite (void * handle, ETISS_CPU * cpu, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length) static
Definition at line 78 of file DMMUWrapper.cpp.
References ETISS_System::handle, ETISS_System::iwrite, length(), etiss::log(), etiss::mm::DMMUWrapperSystem::orig, etiss::mm::DMMUWrapperSystem::this_, etiss::mm::MMU::Translate(), unlikely, etiss::VERBOSE, and W_ACCESS.
Referenced by etiss::mm::DMMUWrapper::wrap().
page_fault_ni_()
static int32_t etiss::mm::page_fault_ni_ (int32_t fault, MMU * mmu, uint64_t , MM_ACCESS) static
Definition at line 71 of file PageFaultVector.cpp.
References DUMP_MMU(), etiss::FATALERROR, etiss::log(), NOERROR, and PAGE_FAULT_MSG.
syncTime()
static void etiss::mm::syncTime (void * handle, ETISS_CPU * cpu) static
Definition at line 166 of file DMMUWrapper.cpp.
References ETISS_System::handle, etiss::mm::DMMUWrapperSystem::orig, and ETISS_System::syncTime.
Referenced by etiss::mm::DMMUWrapper::wrap().
tlb_miss_handler()
int32_t etiss::mm::tlb_miss_handler (int32_t fault, MMU * mmu, uint64_t vma, MM_ACCESS access)
Definition at line 221 of file MMU.cpp.
References etiss::mm::MMU::HasPageTableWalker(), NOERROR, R_ACCESS, W_ACCESS, etiss::mm::MMU::WalkPageTable(), and X_ACCESS.
Referenced by etiss::mm::MMU::MMU().
Variable Documentation
NOERROR
const MM_EXPORT int32_t etiss::mm::NOERROR
Definition at line 98 of file PageFaultVector.h.
Referenced by etiss::mm::TLB< 0 >::AddPTE(), etiss::mm::MMU::AddTLBEntry(), RISCV64MMU::CheckProtection(), dbg_read(), dbg_write(), etiss::SimpleMemSystem::dbus_access(), dread(), dwrite(), etiss_CPUCore_handleException(), etiss::mm::TLB< 0 >::EvictPTE(), OR1KTimer::execute(), RISCV64Timer::execute(), etiss::InterruptHandler::execute(), etiss::plugin::errorInjection::BlockAccurateHandler::execute(), etiss::CPUCore::execute(), OR1KArch::handleException(), RISCVArch::handleException(), RISCV64Arch::handleException(), etiss::plugin::gdb::Server::handlePacket(), etiss::plugin::fault::SwitchSystem::iread(), etiss::SimpleMemSystem::iread(), etiss::mm::TLB< 0 >::Lookup(), page_fault_ni_(), etiss::plugin::gdb::Server::postMemAccessCallback(), etiss::plugin::gdb::Server::preInstructionCallback(), etiss::interfaces::Delegate::read(), tlb_miss_handler(), tlb_overlap_handler(), etiss::interfaces::SimpleInstructionInjector< T >::toFunction(), etiss::mm::MMU::Translate(), etiss::Translation::translateBlock(), etiss::interfaces::WishboneBus< BOOLSIG, VECTORSIG, instrBus, flipEndianess, bytewidth, VECTORSIGSTORAGETYPE >::update(), etiss::mm::TLB< 0 >::UpdatePTE(), RISCV64MMU::WalkPageTable(), and etiss::interfaces::Delegate::write().
page_fault_handler
handler_ptr etiss::mm::page_fault_handler
Initial value:
= {
    page_fault_ni_, page_fault_ni_, page_fault_ni_, page_fault_ni_, page_fault_ni_, page_fault_ni_, page_fault_ni_,
    page_fault_ni_, page_fault_ni_, page_fault_ni_, page_fault_ni_, page_fault_ni_, page_fault_ni_, page_fault_ni_,
    page_fault_ni_, page_fault_ni_, page_fault_ni_, page_fault_ni_, page_fault_ni_, page_fault_ni_,
}
Definition at line 106 of file PageFaultVector.h.
PAGE_FAULT_MSG
std::string etiss::mm::PAGE_FAULT_MSG
Initial value:
= {
    "no error occurs",
    "page table entry already existed",
    "TLB miss",
    "evict a non-existed PTE",
    "TLB is already full",
    "TLB is already full"
}
Definition at line 105 of file PageFaultVector.h.
Referenced by page_fault_ni_().
PROTECTIONVIALATION
const MM_EXPORT int32_t etiss::mm::PROTECTIONVIALATION
Definition at line 103 of file PageFaultVector.h.
PTENOTEXISTED
const MM_EXPORT int32_t etiss::mm::PTENOTEXISTED
Definition at line 101 of file PageFaultVector.h.
Referenced by etiss::mm::TLB< 0 >::EvictPTE(), and etiss::mm::TLB< 0 >::UpdatePTE().
PTEOVERLAP
const MM_EXPORT int32_t etiss::mm::PTEOVERLAP
Definition at line 99 of file PageFaultVector.h.
Referenced by etiss::mm::TLB< 0 >::AddPTE(), etiss::mm::MMU::AddTLBEntryMap(), and RISCV64MMU::RISCV64MMU().
TLBISFULL
const MM_EXPORT int32_t etiss::mm::TLBISFULL
Definition at line 102 of file PageFaultVector.h.
Referenced by etiss::mm::TLB< 0 >::AddPTE().
TLBMISS
const MM_EXPORT int32_t etiss::mm::TLBMISS
Definition at line 100 of file PageFaultVector.h.
Referenced by etiss::mm::TLB< 0 >::Lookup(), and etiss::mm::MMU::MMU().