ETISS 0.8.0: etiss::plugin::gdb::hex Namespace Reference
etiss::plugin::gdb::hex Namespace Reference
Functions
uint8_t fromHex (char c)
convert a character to the hex value it represents(0-15)
char toHex (uint8_t l)
converts the lower 4 bits to a representing char
uint8_t toByte (char h, char l)
converts 2 hex characters to a byte
uint8_t toByte (std::string hex, size_t pos=0)
converts 2 characters from a hex string to one byte
std::string fromByte (uint8_t byte)
converts a byte to a hex string (without "0x" prefix);
void fromByte (std::string &append, uint8_t byte)
converts a byte to hexadecimal representation and appends it to the passed string
std::string fromBytes (uint8_t *buf, size_t length)
converts a sequence of bytes to a representing hex string (without "0x" prefix)
template<typename INT >
void fromInt (std::string &string, INT val, bool isLittleEndian)
converts an integer type variable to a hexadecimal representation with the given endianness
template<typename INT >
INT toInt (const std::string &string, bool isLittleEndian, size_t pos=0)
convert a string of length (pos + sizeof(INT)) or larger to the represented value.
template<typename INT >
INT tryInt (std::string &string, unsigned &pos, size_t maxlength=sizeof(INT) *2)
parses a hex string and returns the result.
Function Documentation
fromByte() [1/2]
void etiss::plugin::gdb::hex::fromByte (std::string & append, uint8_t byte)
converts a byte to hexadecimal representation and appends it to the passed string
Parameters
append
byte
Definition at line 108 of file Hex.cpp.
References toHex().
fromByte() [2/2]
std::string etiss::plugin::gdb::hex::fromByte (uint8_t byte)
converts a byte to a hex string (without "0x" prefix);
Parameters
byte
Returns
a string of length 2 representing the passed byte in hex
Definition at line 100 of file Hex.cpp.
References toHex().
Referenced by fromInt(), etiss::plugin::gdb::Server::handlePacket(), etiss::plugin::gdb::Server::postMemAccessCallback(), etiss::plugin::gdb::Server::preInstructionCallback(), and etiss::plugin::gdb::PacketProtocol::snd().
fromBytes()
std::string etiss::plugin::gdb::hex::fromBytes (uint8_t * buf, size_t length)
converts a sequence of bytes to a representing hex string (without "0x" prefix)
Parameters
buf
length
Returns
hex representation of the passed byte sequence
Definition at line 114 of file Hex.cpp.
References length(), and toHex().
Referenced by etiss::plugin::gdb::Server::handlePacket().
fromHex()
uint8_t etiss::plugin::gdb::hex::fromHex (char c)
convert a character to the hex value it represents(0-15)
Parameters
c hex repesentation 0-9,a-f,A-F
Returns
represented hex value or 16 if invalid character
Definition at line 56 of file Hex.cpp.
References c.
Referenced by etiss::plugin::gdb::Server::handlePacket(), toByte(), and tryInt().
fromInt()
template<typename INT > void etiss::plugin::gdb::hex::fromInt (std::string & string, INT val, bool isLittleEndian)
converts an integer type variable to a hexadecimal representation with the given endianness
Parameters
string the string where hex characters will be appended
val interger value to convert
isLittleEndian true for little endian hex representaion, false for big endian
Definition at line 131 of file Hex.h.
References fromByte().
Referenced by etiss::plugin::gdb::Server::handlePacket().
toByte() [1/2]
uint8_t etiss::plugin::gdb::hex::toByte (char h, char l)
converts 2 hex characters to a byte
h character representing higher 4 bits; may not be invalid
l character representing lower 4 bits; may not be invalid
Returns
represented value
Definition at line 95 of file Hex.cpp.
References fromHex().
Referenced by etiss::plugin::gdb::Server::handlePacket(), toByte(), toInt(), and etiss::plugin::gdb::PacketProtocol::tryReadPacket().
toByte() [2/2]
uint8_t etiss::plugin::gdb::hex::toByte (std::string hex, size_t pos = 0)
converts 2 characters from a hex string to one byte
Parameters
hex string representing a hex value. must be longer than pos+1
pos start position of the hex representation
Definition at line 91 of file Hex.cpp.
References toByte().
toHex()
char etiss::plugin::gdb::hex::toHex (uint8_t l)
converts the lower 4 bits to a representing char
Parameters
l whose lower 4 bits are used. higher bits may not be set
Returns
character 0-9,A-F or '?' if l > 15
Definition at line 75 of file Hex.cpp.
Referenced by fromByte(), and fromBytes().
toInt()
template<typename INT > INT etiss::plugin::gdb::hex::toInt (const std::string & string, bool isLittleEndian, size_t pos = 0)
convert a string of length (pos + sizeof(INT)) or larger to the represented value.
no error checking will be performed
Definition at line 144 of file Hex.h.
References toByte().
tryInt()
template<typename INT > INT etiss::plugin::gdb::hex::tryInt (std::string & string, unsigned & pos, size_t maxlength = sizeof(INT) * 2)
parses a hex string and returns the result.
the string will be parsed until the end is reached, an invalid character was encountered or maxlength was reached. this function cannot handle a "0x" prefix
Parameters
string string to parse;
pos current position in the string. will be set to the index of the first character that was not part of the returned value
maxlength maximum parse length in characters (may be uneven)
Definition at line 163 of file Hex.h.
References fromHex(), and length().