ETISS 0.8.0: etiss::instr Namespace Reference
etiss::instr Namespace Reference
Classes
class BitArray
stores a bit vector
class BitArrayRange
Acts as a view/filter to a BitArray.
class Instruction
holds information and translation callbacks for an instruction.
class InstructionClass
maps to VariableInstructionSet
class InstructionCollection
maps to ModedInstructionSet
class InstructionContext
this class contains parameters that persist in between instruction lookpus/translation within a translation block.
class InstructionDefinition
maps to Instruction
class InstructionGroup
maps to InstructionSet
class InstructionSet
holds etiss::instr::Instruction instances and handles automatic instruction tree creation.
struct less
calls operator< of the objects.
class ModedInstructionSet
holds etiss::instr::VariableInstructionSet instances for different modes.
class Node
base class that is used to build the instruction translation tree within an InstructionSet object
class OPCode
defines the relevant bits and their value to identify an instruction.
class OverlappedNode
class VariableInstructionSet
holds etiss::instr::InstructionSet instances with different bit widths.
Typedefs
typedef uint32_t I
Functions
CONSTEXPR unsigned etiss_instr_sqrt_2pow (unsigned val)
CONSTEXPR I etiss_instr_generateMask ()
creates a mask to get the lower address of a bitwise address.
std::ostream & operator<< (std::ostream &os, const BitArray tf)
allow printing of bit arrays (always hex)
uint32_t parse_i32 (const char *s)
template<typename T_ >
std::enable_if< std::is_integral< T_ >::value, typename std::make_unsigned< T_ >::type >::type parse_i (const char *s, bool *good=0)
this parser basically allows to write as a string hexadecimal values which will be appended as if it is one hexadecimal sequence and the "0x" prefix is replaced by a "<decimal number>x" [e.g.
static void AssertOnTrueCollision (Instruction *i1, Instruction *i2)
static void HandleCollision (Instruction *instr, Node *&node)
Typedef Documentation
I
typedef uint32_t etiss::instr::I
Definition at line 79 of file Instruction.h.
Function Documentation
AssertOnTrueCollision()
static void etiss::instr::AssertOnTrueCollision (Instruction * i1, Instruction * i2) static
Definition at line 555 of file Instruction.cpp.
References etiss::FATALERROR, etiss::log(), and etiss::instr::Instruction::opc_.
Referenced by HandleCollision().
etiss_instr_generateMask()
CONSTEXPR I etiss::instr::etiss_instr_generateMask ()
creates a mask to get the lower address of a bitwise address.
e.g. for sizeof(I)==4, address 33: (33&etiss_instr_generateMask()) is 1
Definition at line 323 of file Instruction.h.
References etiss_instr_sqrt_2pow().
etiss_instr_sqrt_2pow()
CONSTEXPR unsigned etiss::instr::etiss_instr_sqrt_2pow (unsigned val)
Attention
only use if val has only one bit set to 1
Definition at line 314 of file Instruction.h.
Referenced by etiss_instr_generateMask().
HandleCollision()
static void etiss::instr::HandleCollision (Instruction * instr, Node *& node) static
Definition at line 562 of file Instruction.cpp.
References AssertOnTrueCollision(), etiss::FATALERROR, etiss::log(), and etiss::instr::Instruction::opc_.
Referenced by etiss::instr::Node::compile().
operator<<()
std::ostream & etiss::instr::operator<< (std::ostream & os, const BitArray tf)
allow printing of bit arrays (always hex)
Definition at line 366 of file Instruction.cpp.
References etiss::instr::BitArray::byteCount(), etiss::instr::BitArray::getWord(), and etiss::instr::BitArray::wordCount().
parse_i()
template<typename T_ > std::enable_if< std::is_integral< T_ >::value, typename std::make_unsigned< T_ >::type >::type etiss::instr::parse_i (const char * s, bool * good = 0)
this parser basically allows to write as a string hexadecimal values which will be appended as if it is one hexadecimal sequence and the "0x" prefix is replaced by a "<decimal number>x" [e.g.
12x] that defines the length in bits. e.g. "2xF 2x0 4xF" -> 0xCF
        syntax:
            string: definition [' ' string]
            definition: bit_count 'x' bit_value
            bit_count: digit [bit_count]
            digit: '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9'
            bit_value: hdigit [bit_value]
            hdigit: '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' |
'A' | 'B' | 'C' | 'D' | 'E' | 'F'
bit_count is a decimal number that defines the length in bits of the definition. bit_value defines the values of the bits of the definition in hexadecimal format. the definitions are alwas placed at the least significant bits and are left shifted by definitions to the right from them. the total sum of bit_count occurences in a string must match the width of the return type otherwise an error message is printed the behaviour is undefined in case of a bit_value that has less bits than defined by the bit_count.
        example parsing process of "2xF 2x0 2xF 10x0":
            initial value:          0x0000
            parse 1. definition:    0x0003
            parse 2. definition:    0x000C
            parse 3. definition:    0x0033
            parse 4. definition:    0xCC00
See also
etiss::instr::OPCode for an example use of this syntax.
Definition at line 1045 of file Instruction.h.
References etiss::ERROR, etiss::log(), and s.
parse_i32()
uint32_t etiss::instr::parse_i32 (const char * s)
Definition at line 1263 of file Instruction.cpp.
References s.