ETISS 0.8.0: etiss::plugin Namespace Reference
etiss::plugin Namespace Reference
Namespaces
anonymous_namespace{MemoryDevice.cpp}
errorInjection
fault
gdb
Classes
class InstructionAccurateCallback
writes the value of a field before each instruction
class InstructionSpecificAddressCallback
a simple plugin that prints the instruction and address when an instruction is executed
class Logger
simple logger implementation.
struct LoggerSystem
class MemoryDeviceMapper
class PrintInstruction
a simple plugin that prints the instruction and address when an instruction is executed
class VariableValueLogger
writes the value of a field before each instruction
class VirtualStructMemory
allows to read/write to a virtual structure as if it is a memory.
Functions
etiss_int32 iread (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint32 length)
etiss_int32 iwrite (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
etiss_int32 dread (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
etiss_int32 dwrite (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
etiss_int32 dbg_read (void *handle, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
etiss_int32 dbg_write (void *handle, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
void syncTime (void *handle, ETISS_CPU *cpu)
Function Documentation
dbg_read()
etiss_int32 etiss::plugin::dbg_read (void * handle, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length)
Definition at line 115 of file Logger.cpp.
References etiss::plugin::LoggerSystem::addr, ETISS_System::dbg_read, ETISS_System::handle, length(), etiss::plugin::Logger::log(), etiss::plugin::LoggerSystem::mask, etiss::plugin::LoggerSystem::orig, and etiss::plugin::LoggerSystem::this_.
Referenced by etiss::plugin::Logger::wrap().
dbg_write()
etiss_int32 etiss::plugin::dbg_write (void * handle, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length)
Definition at line 126 of file Logger.cpp.
References etiss::plugin::LoggerSystem::addr, ETISS_System::dbg_write, ETISS_System::handle, length(), etiss::plugin::Logger::log(), etiss::plugin::LoggerSystem::mask, etiss::plugin::LoggerSystem::orig, and etiss::plugin::LoggerSystem::this_.
Referenced by etiss::plugin::Logger::wrap().
dread()
etiss_int32 etiss::plugin::dread (void * handle, ETISS_CPU * cpu, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length)
Definition at line 94 of file Logger.cpp.
References ETISS_System::dread, ETISS_System::handle, length(), and etiss::plugin::LoggerSystem::orig.
Referenced by etiss::plugin::Logger::wrap().
dwrite()
etiss_int32 etiss::plugin::dwrite (void * handle, ETISS_CPU * cpu, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length)
Definition at line 104 of file Logger.cpp.
References etiss::plugin::LoggerSystem::addr, ETISS_System::dwrite, ETISS_System::handle, length(), etiss::plugin::Logger::log(), etiss::plugin::LoggerSystem::mask, etiss::plugin::LoggerSystem::orig, and etiss::plugin::LoggerSystem::this_.
Referenced by etiss::plugin::Logger::wrap().
iread()
etiss_int32 etiss::plugin::iread (void * handle, ETISS_CPU * cpu, etiss_uint64 addr, etiss_uint32 length)
Definition at line 73 of file Logger.cpp.
References etiss::plugin::LoggerSystem::addr, ETISS_System::handle, ETISS_System::iread, length(), etiss::plugin::Logger::log(), etiss::plugin::LoggerSystem::mask, etiss::plugin::LoggerSystem::orig, and etiss::plugin::LoggerSystem::this_.
Referenced by etiss::plugin::Logger::wrap().
iwrite()
etiss_int32 etiss::plugin::iwrite (void * handle, ETISS_CPU * cpu, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length)
Definition at line 83 of file Logger.cpp.
References etiss::plugin::LoggerSystem::addr, ETISS_System::handle, ETISS_System::iwrite, length(), etiss::plugin::Logger::log(), etiss::plugin::LoggerSystem::mask, etiss::plugin::LoggerSystem::orig, and etiss::plugin::LoggerSystem::this_.
Referenced by etiss::plugin::Logger::wrap().
syncTime()
void etiss::plugin::syncTime (void * handle, ETISS_CPU * cpu)
Definition at line 137 of file Logger.cpp.
References ETISS_System::handle, etiss::plugin::LoggerSystem::orig, and ETISS_System::syncTime.
Referenced by etiss::plugin::Logger::wrap().