ETISS 0.8.0: etiss::plugin::anonymous_namespace{MemoryDevice.cpp} Namespace Reference
etiss::plugin::anonymous_namespace{MemoryDevice.cpp} Namespace Reference
Classes
struct MapperSystem
Functions
bool empty_fastrule (uint64_t, unsigned)
etiss_int32 iread_ (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint32 length)
etiss_int32 iwrite_ (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
etiss_int32 dread_ (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
etiss_int32 dwrite_ (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
etiss_int32 dbg_read_ (void *handle, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
etiss_int32 dbg_write_ (void *handle, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
void syncTime_ (void *handle, ETISS_CPU *cpu)
Function Documentation
dbg_read_()
etiss_int32 etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::dbg_read_ (void * handle, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length)
Definition at line 112 of file MemoryDevice.cpp.
References etiss::plugin::MemoryDeviceMapper::dbg_read(), ETISS_System::dbg_read, etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::MapperSystem::fastrule, ETISS_System::handle, length(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::MapperSystem::orig, and etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::MapperSystem::this_.
Referenced by etiss::plugin::MemoryDeviceMapper::wrap().
dbg_write_()
etiss_int32 etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::dbg_write_ (void * handle, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length)
Definition at line 123 of file MemoryDevice.cpp.
References etiss::plugin::MemoryDeviceMapper::dbg_write(), ETISS_System::dbg_write, etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::MapperSystem::fastrule, ETISS_System::handle, length(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::MapperSystem::orig, and etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::MapperSystem::this_.
Referenced by etiss::plugin::MemoryDeviceMapper::wrap().
dread_()
etiss_int32 etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::dread_ (void * handle, ETISS_CPU * cpu, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length)
Definition at line 91 of file MemoryDevice.cpp.
References etiss::plugin::MemoryDeviceMapper::dread(), ETISS_System::dread, etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::MapperSystem::fastrule, ETISS_System::handle, length(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::MapperSystem::orig, and etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::MapperSystem::this_.
Referenced by etiss::plugin::MemoryDeviceMapper::wrap().
dwrite_()
etiss_int32 etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::dwrite_ (void * handle, ETISS_CPU * cpu, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length)
Definition at line 101 of file MemoryDevice.cpp.
References etiss::plugin::MemoryDeviceMapper::dwrite(), ETISS_System::dwrite, etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::MapperSystem::fastrule, ETISS_System::handle, length(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::MapperSystem::orig, and etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::MapperSystem::this_.
Referenced by etiss::plugin::MemoryDeviceMapper::wrap().
empty_fastrule()
bool etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::empty_fastrule (uint64_t , unsigned)
Definition at line 65 of file MemoryDevice.cpp.
Referenced by etiss::plugin::MemoryDeviceMapper::wrap().
iread_()
etiss_int32 etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::iread_ (void * handle, ETISS_CPU * cpu, etiss_uint64 addr, etiss_uint32 length)
Definition at line 70 of file MemoryDevice.cpp.
References etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::MapperSystem::fastrule, ETISS_System::handle, etiss::plugin::MemoryDeviceMapper::iread(), ETISS_System::iread, length(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::MapperSystem::orig, and etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::MapperSystem::this_.
Referenced by etiss::plugin::MemoryDeviceMapper::wrap().
iwrite_()
etiss_int32 etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::iwrite_ (void * handle, ETISS_CPU * cpu, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length)
Definition at line 80 of file MemoryDevice.cpp.
References etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::MapperSystem::fastrule, ETISS_System::handle, etiss::plugin::MemoryDeviceMapper::iwrite(), ETISS_System::iwrite, length(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::MapperSystem::orig, and etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::MapperSystem::this_.
Referenced by etiss::plugin::MemoryDeviceMapper::wrap().
syncTime_()
void etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::syncTime_ (void * handle, ETISS_CPU * cpu)
Definition at line 134 of file MemoryDevice.cpp.
References ETISS_System::handle, etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::MapperSystem::orig, and ETISS_System::syncTime.
Referenced by etiss::plugin::MemoryDeviceMapper::wrap().