ETISS 0.8.0: /home/runner/work/etiss/etiss/ArchImpl/OR1K/OR1200Timing.cpp File Reference
OR1200Timing.cpp File Reference
#include "etiss/Timing.h"
Functions
etiss::Plugin * getOR1200Timing (etiss::Configuration &cfg)
Function Documentation
getOR1200Timing()
etiss::Plugin* getOR1200Timing (etiss::Configuration & cfg)
Definition at line 45 of file OR1200Timing.cpp.
References etiss::instr::Instruction::addCallback(), etiss::DataSheetAccurateTiming::addRule(), etiss::cfg(), etiss::CodePart::code(), etiss::Configuration::get(), etiss::CodePart::getAffectedRegisters(), etiss::CodePart::INITIALREQUIRED, etiss::CodeSet::prepend(), and etiss::toString().