ETISS 0.8.0: /home/runner/work/etiss/etiss/ArchImpl/OR1K/OR1KArch.cpp File Reference
OR1KArch.cpp File Reference
#include "OR1KArch.h"
#include "OR1KTimer.h"
#include <iostream>
#include <sstream>
#include <ctime>
#include <limits>
#include "etiss/VirtualStruct.h"
Classes
struct OR1K_internal
class anonymous_namespace{OR1KArch.cpp}::SPRField
simple field implementation.
class anonymous_namespace{OR1KArch.cpp}::GPRField
class PPCField
class NPCField
class SRField
Namespaces
anonymous_namespace{OR1KArch.cpp}
Macros
#define SPR_ID(group, index) (((group & 0x1F) << 11) | (index & 0x7FF))
Functions
ETISS_PLUGIN_EXPORT unsigned OR1KArch_etissversion ()
ETISS_PLUGIN_EXPORT unsigned OR1KArch_countCPUArch ()
const ETISS_PLUGIN_EXPORT char * OR1KArch_nameCPUArch (unsigned index)
ETISS_PLUGIN_EXPORT etiss::CPUArch * OR1KArch_createCPUArch (unsigned index, std::map< std::string, std::string > options)
ETISS_PLUGIN_EXPORT void OR1KArch_deleteCPUArch (etiss::CPUArch *o)
ETISS_PLUGIN_EXPORT void OR1K_printchar (char c)
ETISS_PLUGIN_EXPORT void OR1K_report (uint32_t c)
ETISS_PLUGIN_EXPORT void OR1K_print (char *c)
ETISS_PLUGIN_EXPORT void OR1K_printtime (ETISS_CPU *cpu)
ETISS_PLUGIN_EXPORT etiss_uint32 OR1K_reset_stopwatch (ETISS_CPU *cpu)
ETISS_PLUGIN_EXPORT etiss_uint32 OR1KArch_mfspr (OR1K *cpu, etiss_uint32 id)
ETISS_PLUGIN_EXPORT void OR1KArch_mtspr (OR1K *cpu, etiss_uint32 id, etiss_uint32 value)
static std::string getName (uint16_t sprid)
static std::string getPrettyName (uint16_t sprid)
static bool supportsListener (uint16_t sprid)
static int getSPRFlags (uint16_t sprid)
Variables
etiss::instr::InstructionClass OR32 (0, "OR32", 32, ORBIS32_I, ORBIS32_II, ORFPX32)
etiss::instr::InstructionCollection Processor_OR1K ("OR1K", OR32)
Macro Definition Documentation
SPR_ID
#define SPR_ID (group, index) (((group & 0x1F) << 11) | (index & 0x7FF))
Definition at line 163 of file OR1KArch.cpp.
Function Documentation
getName()
static std::string getName (uint16_t sprid) static
Definition at line 504 of file OR1KArch.cpp.
getPrettyName()
static std::string getPrettyName (uint16_t sprid) static
Definition at line 510 of file OR1KArch.cpp.
getSPRFlags()
static int getSPRFlags (uint16_t sprid) static
Definition at line 542 of file OR1KArch.cpp.
References etiss::VirtualStruct::Field::L, etiss::VirtualStruct::Field::R, supportsListener(), and etiss::VirtualStruct::Field::W.
OR1K_print()
ETISS_PLUGIN_EXPORT void OR1K_print (char * c)
Definition at line 140 of file OR1KArch.cpp.
References c.
OR1K_printchar()
ETISS_PLUGIN_EXPORT void OR1K_printchar (char c)
Definition at line 138 of file OR1KArch.cpp.
References c.
OR1K_printtime()
ETISS_PLUGIN_EXPORT void OR1K_printtime (ETISS_CPU * cpu)
Definition at line 141 of file OR1KArch.cpp.
References OR1K::cpu, and ETISS_CPU::cpuTime_ps.
OR1K_report()
ETISS_PLUGIN_EXPORT void OR1K_report (uint32_t c)
Definition at line 139 of file OR1KArch.cpp.
References c.
OR1K_reset_stopwatch()
ETISS_PLUGIN_EXPORT etiss_uint32 OR1K_reset_stopwatch (ETISS_CPU * cpu)
Definition at line 149 of file OR1KArch.cpp.
References c, clock(), and OR1K::cpu.
OR1KArch_countCPUArch()
ETISS_PLUGIN_EXPORT unsigned OR1KArch_countCPUArch ()
Definition at line 73 of file OR1KArch.cpp.
OR1KArch_createCPUArch()
ETISS_PLUGIN_EXPORT etiss::CPUArch* OR1KArch_createCPUArch (unsigned index, std::map< std::string, std::string > options)
Definition at line 84 of file OR1KArch.cpp.
References etiss::cfg(), etiss::Configuration::config(), etiss::Configuration::get(), OR1KArch::ignore_sr_iee, etiss::INFO, etiss::log(), and options.
OR1KArch_deleteCPUArch()
ETISS_PLUGIN_EXPORT void OR1KArch_deleteCPUArch (etiss::CPUArch * o)
Definition at line 101 of file OR1KArch.cpp.
OR1KArch_etissversion()
ETISS_PLUGIN_EXPORT unsigned OR1KArch_etissversion ()
Definition at line 71 of file OR1KArch.cpp.
References ETISS_VERSION_MAJOR, and ETISS_VERSION_MINOR.
OR1KArch_mfspr()
ETISS_PLUGIN_EXPORT etiss_uint32 OR1KArch_mfspr (OR1K * cpu, etiss_uint32 id)
Definition at line 165 of file OR1KArch.cpp.
References OR1K::cpu.
OR1KArch_mtspr()
ETISS_PLUGIN_EXPORT void OR1KArch_mtspr (OR1K * cpu, etiss_uint32 id, etiss_uint32 value)
Definition at line 172 of file OR1KArch.cpp.
References OR1K::cpu, OR1K_SR_FO, OR1K_SR_SM, and etiss::CPUArchRegListenerInterface::signalChangedRegisterValue().
Referenced by anonymous_namespace{OR1KArch.cpp}::SPRField::_write().
OR1KArch_nameCPUArch()
const ETISS_PLUGIN_EXPORT char* OR1KArch_nameCPUArch (unsigned index)
Definition at line 74 of file OR1KArch.cpp.
supportsListener()
static bool supportsListener (uint16_t sprid) static
TODO add fields before this that are supported by OR1KArch_mtspr();
Definition at line 530 of file OR1KArch.cpp.
Referenced by etiss::VirtualStruct::addField(), and getSPRFlags().
Variable Documentation
OR32
etiss::instr::InstructionClass OR32(0, "OR32", 32, ORBIS32_I, ORBIS32_II, ORFPX32)
Processor_OR1K
etiss::instr::InstructionCollection Processor_OR1K("OR1K", OR32)
Referenced by OR1KArch::initInstrSet().