ETISS 0.8.0: /home/runner/work/etiss/etiss/ArchImpl/OR1K/OR1KCommonLocal.hpp File Reference
OR1KCommonLocal.hpp File Reference
#include "OR1KArch.h"
Functions
template<bool isjump, bool hasdelayslot>
void update_pc (BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic)
template<bool sig, bool imm, char op, char eop = ' '>
static bool l_sf (BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic)
static std::string or1k_asm_print_rDAB (BitArray &ba, Instruction &i)
template<bool sig>
static std::string or1k_asm_print_rDAI (BitArray &ba, Instruction &i)
Variables
static BitArrayRange rd (25, 21)
static BitArrayRange ra (20, 16)
static BitArrayRange rb (15, 11)
static BitArrayRange immediate (15, 0)
static BitArrayRange limmediate (25, 0)
static const char *const reg []
static const char *const reg_name []
Function Documentation
l_sf()
template<bool sig, bool imm, char op, char eop = ' '> static bool l_sf (BitArray & ba, etiss::CodeSet & cs, InstructionContext & ic) static
Definition at line 205 of file OR1KCommonLocal.hpp.
References etiss::RegisterSet::add(), etiss::CodeSet::append(), etiss::CodePart::code(), etiss::CodePart::getAffectedRegisters(), etiss::CodePart::getRegisterDependencies(), immediate, etiss::CodePart::INITIALREQUIRED, OR1K_SR_F, ra, rb, etiss::instr::BitArrayRange::read(), reg, reg_name, and etiss::toString().
or1k_asm_print_rDAB()
static std::string or1k_asm_print_rDAB (BitArray & ba, Instruction & i) static
Definition at line 225 of file OR1KCommonLocal.hpp.
References etiss::instr::Instruction::name_, ra, rb, rd, and etiss::instr::BitArrayRange::read().
or1k_asm_print_rDAI()
template<bool sig> static std::string or1k_asm_print_rDAI (BitArray & ba, Instruction & i) static
Definition at line 233 of file OR1KCommonLocal.hpp.
References immediate, etiss::instr::Instruction::name_, ra, rd, and etiss::instr::BitArrayRange::read().
update_pc()
template<bool isjump, bool hasdelayslot> void update_pc (BitArray & ba, etiss::CodeSet & cs, InstructionContext & ic)
Definition at line 127 of file OR1KCommonLocal.hpp.
References etiss::RegisterSet::add(), etiss::CodeSet::append(), etiss::CodePart::APPENDEDOPTIONAL, etiss::CodePart::APPENDEDRETURNINGREQUIRED, etiss::instr::InstructionContext::cf_delay_slot_, etiss::CodePart::code(), etiss::instr::InstructionContext::current_address_, etiss::instr::InstructionContext::force_append_next_instr_, etiss::instr::InstructionContext::force_block_end_, etiss::CodePart::getAffectedRegisters(), etiss::CodePart::getRegisterDependencies(), and etiss::toString().
Variable Documentation
immediate
BitArrayRange immediate(15, 0) static
Referenced by l_sf(), loadinstr(), or1k_asm_print_rDAI(), shift(), and simple_op_rDAI().
limmediate
BitArrayRange limmediate(25, 0) static
ra
BitArrayRange ra(20, 16) static
Referenced by l_cust(), l_ext(), l_sf(), loadinstr(), or1k_asm_print_rDAB(), or1k_asm_print_rDAI(), OR1KArch_mul32(), shift(), simple_op_rDAB(), simple_op_rDAI(), and storeinstr().
rb
BitArrayRange rb(15, 11) static
Referenced by l_sf(), or1k_asm_print_rDAB(), OR1KArch_mul32(), shift(), simple_op_rDAB(), and storeinstr().
rd
BitArrayRange rd(25, 21) static
Referenced by l_cust(), l_ext(), loadinstr(), or1k_asm_print_rDAB(), or1k_asm_print_rDAI(), shift(), simple_op_rDAB(), simple_op_rDAI(), and storeinstr().
reg
const char* const reg[] static
Definition at line 55 of file OR1KCommonLocal.hpp.
Referenced by l_cust(), l_ext(), l_sf(), loadinstr(), etiss::plugin::errorInjection::BlockAccurateHandler::parseFile(), shift(), simple_op_rDAB(), simple_op_rDAI(), and storeinstr().
reg_name
const char* const reg_name[] static
Definition at line 90 of file OR1KCommonLocal.hpp.
Referenced by l_ext(), l_sf(), loadinstr(), shift(), simple_op_rDAB(), simple_op_rDAI(), and storeinstr().