ETISS 0.8.0: /home/runner/work/etiss/etiss/ArchImpl/OR1K/OR1KArch.h File Reference
OR1KArch.h File Reference
class definition of the CPUArch implementation for an or1k processor
#include "OR1K.h"
#include "etiss/CPUArch.h"
#include "etiss/Instruction.h"
#include <map>
#include "OR1KGDBCore.h"
Classes
class OR1KArch
TODO: implement opt_hostendianess for store/load instructions.
Macros
#define ETISS_LIBNAME OR1KArch
#define OR1KArch_translateInvalidInstruction(CODESET)
Functions
etiss::Plugin * getOR1200Timing (etiss::Configuration &)
void translate_fpu (const etiss::uint32 instr, etiss::CodeSet &ret)
translates floating point instructions
Variables
etiss::instr::InstructionCollection Processor_OR1K
etiss::instr::InstructionClass OR32
etiss::instr::InstructionGroup ORFPX32
etiss::instr::InstructionGroup ORBIS32_I
etiss::instr::InstructionGroup ORBIS32_II
Detailed Description
class definition of the CPUArch implementation for an or1k processor
Copyright
Copyright 2018 Infineon Technologies AG
This file is part of ETISS tool, see https://github.com/tum-ei-eda/etiss.
The initial version of this software has been created with the funding support by the German Federal
Ministry of Education and Research (BMBF) in the project EffektiV under grant 01IS13022.
Redistribution and use in source and binary forms, with or without modification, are permitted
provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and
the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions
and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse
or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
Author
Marc Greim marc..nosp@m.grei.nosp@m.m@myt.nosp@m.um.d.nosp@m.e, Chair of Electronic Design Automation, TUM
Date
July 29, 2014
Version
0.1
Definition in file OR1KArch.h.
Macro Definition Documentation
ETISS_LIBNAME
#define ETISS_LIBNAME OR1KArch
Definition at line 62 of file OR1KArch.h.
OR1KArch_translateInvalidInstruction
#define OR1KArch_translateInvalidInstruction (CODESET)
Value:
    {                                                                                       \
        etiss::CodePart &part = CODESET.append(etiss::CodePart::APPENDEDRETURNINGREQUIRED); \
        part.code() = "return OR1K_ILLEGALINSTRUCTIONEXCEPTION;";                           \
    }
Definition at line 126 of file OR1KArch.h.
Function Documentation
getOR1200Timing()
etiss::Plugin* getOR1200Timing (etiss::Configuration &)
Definition at line 45 of file OR1200Timing.cpp.
References etiss::instr::Instruction::addCallback(), etiss::DataSheetAccurateTiming::addRule(), etiss::cfg(), etiss::CodePart::code(), etiss::Configuration::get(), etiss::CodePart::getAffectedRegisters(), etiss::CodePart::INITIALREQUIRED, etiss::CodeSet::prepend(), and etiss::toString().
translate_fpu()
void translate_fpu (const etiss::uint32 instr, etiss::CodeSet & ret)
translates floating point instructions
See also
OR1KArch_fpu.cpp
Definition at line 84 of file OR1KArch_fpu.cpp.
References etiss::CodeSet::append(), etiss::CodePart::code(), fpu_append_exceptioncode(), etiss::CodePart::INITIALREQUIRED, and OR1KArch_translateInvalidInstruction.
Variable Documentation
OR32
etiss::instr::InstructionClass OR32
ORBIS32_I
etiss::instr::InstructionGroup ORBIS32_I
ORBIS32_II
etiss::instr::InstructionGroup ORBIS32_II
ORFPX32
etiss::instr::InstructionGroup ORFPX32
Processor_OR1K
etiss::instr::InstructionCollection Processor_OR1K
Referenced by OR1KArch::initInstrSet().