ETISS 0.8.0: /home/runner/work/etiss/etiss/ArchImpl/OR1K/OR1KArch_fpu.cpp File Reference
OR1KArch_fpu.cpp File Reference
#include "OR1KArch.h"
#include "etiss/jit/fpu/softfloat.h"
Functions
void OR1KArch_apply_fpu_flags (OR1K *cpu, unsigned flags)
void fpu_append_exceptioncode (etiss::CodeSet &ret)
void translate_fpu (const etiss::uint32 instr, etiss::CodeSet &ret)
translates floating point instructions
Function Documentation
fpu_append_exceptioncode()
void fpu_append_exceptioncode (etiss::CodeSet & ret)
Definition at line 74 of file OR1KArch_fpu.cpp.
References etiss::CodeSet::append(), etiss::CodePart::APPENDEDRETURNINGREQUIRED, and etiss::CodePart::code().
Referenced by translate_fpu().
OR1KArch_apply_fpu_flags()
void OR1KArch_apply_fpu_flags (OR1K * cpu, unsigned flags)
Definition at line 48 of file OR1KArch_fpu.cpp.
References float_flag_divbyzero, float_flag_inexact, float_flag_invalid, float_flag_overflow, float_flag_underflow, OR1K::FPCSR, OR1K_FPCSR_DZF, OR1K_FPCSR_IVF, OR1K_FPCSR_IXF, OR1K_FPCSR_OVF, and OR1K_FPCSR_UNF.
translate_fpu()
void translate_fpu (const etiss::uint32 instr, etiss::CodeSet & ret)
translates floating point instructions
See also
OR1KArch_fpu.cpp
Definition at line 84 of file OR1KArch_fpu.cpp.
References etiss::CodeSet::append(), etiss::CodePart::code(), fpu_append_exceptioncode(), etiss::CodePart::INITIALREQUIRED, and OR1KArch_translateInvalidInstruction.