ETISS 0.8.0: /home/runner/work/etiss/etiss/ArchImpl/OR1K/ORBIS32_I.cpp File Reference
ORBIS32_I.cpp File Reference
#include "OR1KArch.h"
#include <type_traits>
#include "OR1KCommonLocal.hpp"
Macros
#define NOP_NOP 0x0000 /* Normal nop instruction */
#define NOP_EXIT 0x0001 /* End of simulation */
#define NOP_REPORT 0x0002 /* Simple report */
#define NOP_PUTC 0x0004 /* JPB: Simputc instruction */
#define NOP_CNT_RESET 0x0005 /* Reset statistics counters */
#define NOP_GET_TICKS 0x0006 /* JPB: Get # ticks running */
#define NOP_GET_PS 0x0007 /* JPB: Get picosecs/cycle */
#define NOP_REPORT_FIRST 0x0400 /* Report with number */
#define NOP_REPORT_LAST 0x03ff /* Report with number */
Functions
static void l_addsubX (std::string in1, std::string in2, std::string out, CodeSet &codeset, bool add, bool cy)
template<char op>
static bool simple_op_rDAB (BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic)
template<char op, bool sig>
static bool simple_op_rDAI (BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic)
template<bool right, bool sig, bool imm>
static bool shift (BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic)
template<typename T , bool swap = (ETISS_ENDIANNESS != ETISS_BIG_ENDIAN)>
static bool loadinstr (BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic)
template<typename T , bool swap = (ETISS_ENDIANNESS != ETISS_BIG_ENDIAN)>
static bool storeinstr (BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic)
Variables
InstructionGroup ORBIS32_I ("ORBIS32_I", 32)
static InstructionDefinition l_add (ORBIS32_I, "l.add", parse_i32("6x38 15x0 1x0 2x0 4x0 4x0"), parse_i32("6xFF 15x0 1x0 2xF 4x0 4xF"), [](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { l_addsubX(reg[ra.read(ba)], reg[rb.read(ba)], reg[rd.read(ba)], cs, true, false);update_pc< false, false >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_addc (ORBIS32_I, "l.addc", parse_i32("6x38 15x0 1x0 2x0 4x0 4x1"), parse_i32("6xFF 15x0 1x0 2xF 4x0 4xF"), [](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { l_addsubX(reg[ra.read(ba)], reg[rb.read(ba)], reg[rd.read(ba)], cs, true, true);update_pc< false, false >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_addi (ORBIS32_I, "l.addi", parse_i32("6x27 10x0 16x0"), parse_i32("6xFF 10x0 16x0"), [](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { l_addsubX(reg[ra.read(ba)], toString((int16_t) immediate.read(ba)), reg[rd.read(ba)], cs, true, false);update_pc< false, false >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAI< true >)
static InstructionDefinition l_addic (ORBIS32_I, "l.addic", parse_i32("6x28 10x0 16x0"), parse_i32("6xFF 10x0 16x0"), [](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { l_addsubX(reg[ra.read(ba)], toString((int16_t) immediate.read(ba)), reg[rd.read(ba)], cs, true, true);update_pc< false, false >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_and (ORBIS32_I, "l.and", parse_i32("6x38 15x0 1x0 2x0 4x0 4x3"), parse_i32("6xFF 15x0 1x0 2xF 4x0 4xF"), simple_op_rDAB<'&'>, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_andi (ORBIS32_I, "l.andi", parse_i32("6x29 10x0 16x0"), parse_i32("6xFF 10x0 16x0"), simple_op_rDAI<'&', false >, 0, or1k_asm_print_rDAI< false >)
static InstructionDefinition l_bf (ORBIS32_I, "l.bf", parse_i32("6x4 26x0"), parse_i32("6xFF 26x0"), [](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { std::stringstream ss;ss<< " if (*(((OR1K*)cpu)->SR) & OR1K_SR_F){";ss<< " ((OR1K*)cpu)->instructionPointer_delayed = (uint32_t)("<< ic.current_address_<< "ULL + "<<(uint32_t)(((int32_t)((int16_t) immediate.read(ba)))<< 2)<< "ULL);";ss<< " }else{";ss<< " ((OR1K*)cpu)->instructionPointer_delayed = (uint32_t)("<< ic.current_address_<< "ULL + 8);";ss<< "}";CodePart &cp=cs.append(CodePart::INITIALREQUIRED);cp.getRegisterDependencies().add("SR", 32, OR1K_SR_F);cp.code()=ss.str();update_pc< true, true >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_bnf (ORBIS32_I, "l.bnf", parse_i32("6x3 26x0"), parse_i32("6xFF 26x0"), [](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { std::stringstream ss;ss<< " if ((*(((OR1K*)cpu)->SR) & OR1K_SR_F)==0){";ss<< " ((OR1K*)cpu)->instructionPointer_delayed = (uint32_t)("<< ic.current_address_<< "ULL + "<<(uint32_t)(((int32_t)((int16_t) immediate.read(ba)))<< 2)<< ");";ss<< " }else{";ss<< " ((OR1K*)cpu)->instructionPointer_delayed = (uint32_t)("<< ic.current_address_<< "ULL + 8);";ss<< "}";CodePart &cp=cs.append(CodePart::INITIALREQUIRED);cp.getRegisterDependencies().add("SR", 32, OR1K_SR_F);cp.code()=ss.str();update_pc< true, true >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_j (ORBIS32_I, "l.j", parse_i32("6x0 26x0"), parse_i32("6xFF 26x0"), [](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { uint32_t jaddr=(uint32_t)(ic.current_address_+((((int32_t) limmediate.read(ba))<< 6) >> 4));std::stringstream ss;ss<< " ((OR1K*)cpu)->instructionPointer_delayed = (uint32_t)"+toString(jaddr)+"ULL;";CodePart &cp=cs.append(CodePart::INITIALREQUIRED);cp.code()=ss.str();update_pc< true, true >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_jal (ORBIS32_I, "l.jal", parse_i32("6x1 26x0"), parse_i32("6xFF 26x0"), [](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { uint32_t jaddr=(uint32_t)(ic.current_address_+((((int32_t) limmediate.read(ba))<< 6) >> 4));std::stringstream ss;ss<< " ((OR1K*)cpu)->instructionPointer_delayed = (uint32_t)"+toString(jaddr)+"ULL;";ss<< " ((OR1K*)cpu)->R[9] = "+toString(ic.current_address_+8)+";";CodePart &cp=cs.append(CodePart::INITIALREQUIRED);cp.code()=ss.str();update_pc< true, true >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_jalr (ORBIS32_I, "l.jalr", parse_i32("6x12 26x0"), parse_i32("6xFF 26x0"), [](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { std::stringstream ss;ss<< " ((OR1K*)cpu)->instructionPointer_delayed = (uint32_t)("<< reg[rb.read(ba)]<< ");";ss<< " ((OR1K*)cpu)->R[9] = "+toString(ic.current_address_+8)+";";CodePart &cp=cs.append(CodePart::INITIALREQUIRED);cp.getRegisterDependencies().add(reg_name[rb.read(ba)], 32);cp.code()=ss.str();update_pc< true, true >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_jr (ORBIS32_I, "l.jr", parse_i32("6x11 26x0"), parse_i32("6xFF 26x0"), [](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { std::stringstream ss;ss<< " ((OR1K*)cpu)->instructionPointer_delayed = (uint32_t)("<< reg[rb.read(ba)]<< ");";CodePart &cp=cs.append(CodePart::INITIALREQUIRED);cp.getRegisterDependencies().add(reg_name[rb.read(ba)], 32);cp.code()=ss.str();update_pc< true, true >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_lbs (ORBIS32_I, "l.lbs", parse_i32("6x24 26x0"), parse_i32("6xFF 26x0"), loadinstr< int8_t >, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_lbz (ORBIS32_I, "l.lbz", parse_i32("6x23 26x0"), parse_i32("6xFF 26x0"), loadinstr< uint8_t >, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_lhs (ORBIS32_I, "l.lhs", parse_i32("6x26 26x0"), parse_i32("6xFF 26x0"), loadinstr< int16_t >, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_lhz (ORBIS32_I, "l.lhz", parse_i32("6x25 26x0"), parse_i32("6xFF 26x0"), loadinstr< uint16_t >, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_lws (ORBIS32_I, "l.lws", parse_i32("6x22 26x0"), parse_i32("6xFF 26x0"), loadinstr< int32_t >, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_lwz (ORBIS32_I, "l.lwz", parse_i32("6x21 26x0"), parse_i32("6xFF 26x0"), loadinstr< int32_t >, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_mfspr (ORBIS32_I, "l.mfspr", parse_i32("6x2d 26x0"), parse_i32("6xFF 26x0"), [](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { CodePart &cp=cs.append(CodePart::INITIALREQUIRED);cp.code()=std::string(reg[rd.read(ba)])+" = OR1KArch_mfspr((OR1K*)cpu,"+reg[ra.read(ba)]+"|"+toString(immediate.read(ba))+");";update_pc< false, false >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAI< false >)
static InstructionDefinition l_movhi (ORBIS32_I, "l.movhi", parse_i32("6x6 5x0 4x0 1x0 16x0"), parse_i32("6xFF 5x0 4x0 1xF 16x0"), [](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { CodePart &cp=cs.append(CodePart::INITIALREQUIRED);cp.code()=std::string(reg[rd.read(ba)])+" = (etiss_uint32) "+toString(((uint32_t) immediate.read(ba))<< 16)+";";update_pc< false, false >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAI< false >)
static InstructionDefinition l_mtspr (ORBIS32_I, "l.mtspr", parse_i32("6x30 26x0"), parse_i32("6xFF 26x0"), [](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { CodePart &cp=cs.append(CodePart::INITIALREQUIRED);cp.getRegisterDependencies().add(reg_name[ra.read(ba)], 32);cp.getRegisterDependencies().add(reg_name[rb.read(ba)], 32);BitArrayRange immp1(25, 21);BitArrayRange immp2(10, 0);cp.code()=std::string("OR1KArch_mtspr((OR1K*)cpu,")+reg[ra.read(ba)]+"|"+toString((immp1.read(ba)<< 11)|immp2.read(ba))+", "+reg[rb.read(ba)]+");";update_pc< false, false >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAI< false >)
static BitArrayRange l_nop_param (23, 0)
static InstructionDefinition l_nop (ORBIS32_I, "l.nop", parse_i32("8x15 24x0"), parse_i32("8xFF 24x0"), [](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { uint32_t nopcode=l_nop_param.read(ba);if(nopcode !=NOP_NOP) { if(nopcode==NOP_EXIT) { cs.append(CodePart::APPENDEDRETURNINGREQUIRED).code()="return ETISS_RETURNCODE_CPUFINISHED ;";} if(nopcode==NOP_REPORT) { cs.append(CodePart::INITIALREQUIRED).code()=std::string("OR1K_report((uint32_t)")+reg[3]+");";} if(nopcode==NOP_PUTC) { cs.append(CodePart::INITIALREQUIRED).code()=std::string("OR1K_printchar((char)")+reg[3]+");";} if(nopcode==NOP_GET_PS) { cs.append(CodePart::INITIALREQUIRED).code()=std::string(reg[11])+" = (etiss_uint32) (cpu->cpuCycleTime_ps);";} } update_pc< false, false >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_or (ORBIS32_I, "l.or", parse_i32("6x38 15x0 1x0 2x0 4x0 4x4"), parse_i32("6xFF 15x0 1x0 2xF 4x0 4xF"), simple_op_rDAB<'|'>, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_ori (ORBIS32_I, "l.ori", parse_i32("6x2a 10x0 16x0"), parse_i32("6xFF 10x0 16x0"), simple_op_rDAI<'|', false >, 0, or1k_asm_print_rDAI< false >)
static InstructionDefinition l_rfe (ORBIS32_I, "l.rfe", parse_i32("6x9 26x0"), parse_i32("6xFF 26x0"), [](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { std::stringstream ss;ss<< " ((OR1K*)cpu)->instructionPointer_delayed = ((OR1K*)cpu)->EPCR_16[0];\n";ss<< " *((OR1K*)cpu)->SR = ((OR1K*)cpu)->ESR_16[0];";CodePart &cp=cs.append(CodePart::INITIALREQUIRED);cp.getRegisterDependencies().add(reg_name[rb.read(ba)], 32);cp.code()=ss.str();update_pc< true, false >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_sb (ORBIS32_I, "l.sb", parse_i32("6x36 26x0"), parse_i32("6xFF 26x0"), storeinstr< int8_t >, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_sfeq (ORBIS32_I, "l.sfeq", parse_i32("11x720 21x0"), parse_i32("11xFFF 21x0"), l_sf< true, false, '=', '='>, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_sfges (ORBIS32_I, "l.sfges", parse_i32("11x72b 21x0"), parse_i32("11xFFF 21x0"), l_sf< true, false, '>', '='>, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_sfgeu (ORBIS32_I, "l.sfgeu", parse_i32("11x723 21x0"), parse_i32("11xFFF 21x0"), l_sf< false, false, '>', '='>, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_sfgts (ORBIS32_I, "l.sfgts", parse_i32("11x72a 21x0"), parse_i32("11xFFF 21x0"), l_sf< true, false, '>'>, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_sfgtu (ORBIS32_I, "l.sfgtu", parse_i32("11x722 21x0"), parse_i32("11xFFF 21x0"), l_sf< false, false, '>'>, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_sfles (ORBIS32_I, "l.sfles", parse_i32("11x72d 21x0"), parse_i32("11xFFF 21x0"), l_sf< true, false, '<', '='>, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_sfleu (ORBIS32_I, "l.sfleu", parse_i32("11x725 21x0"), parse_i32("11xFFF 21x0"), l_sf< false, false, '<', '='>, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_sflts (ORBIS32_I, "l.sflts", parse_i32("11x72c 21x0"), parse_i32("11xFFF 21x0"), l_sf< true, false, '<'>, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_sfltu (ORBIS32_I, "l.sfltu", parse_i32("11x724 21x0"), parse_i32("11xFFF 21x0"), l_sf< false, false, '<'>, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_sfne (ORBIS32_I, "l.sfne", parse_i32("11x721 21x0"), parse_i32("11xFFF 21x0"), l_sf< true, false, '!', '='>, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_sh (ORBIS32_I, "l.sh", parse_i32("6x37 26x0"), parse_i32("6xFF 26x0"), storeinstr< int16_t >, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_sll (ORBIS32_I, "l.sll", parse_i32("6x38 15x0 1x0 4x0 2x0 4x8"), parse_i32("6xFF 15x0 1x0 4xF 2x0 4xF"), shift< false, false, false >, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_slli (ORBIS32_I, "l.slli", parse_i32("6x2e 10x0 8x0 2x0 6x0"), parse_i32("6xFF 10x0 8x0 2xF 6x0"), shift< false, false, true >, 0, or1k_asm_print_rDAI< false >)
static InstructionDefinition l_sra (ORBIS32_I, "l.sra", parse_i32("6x38 15x0 1x0 4x2 2x0 4x8"), parse_i32("6xFF 15x0 1x0 4xF 2x0 4xF"), shift< true, true, false >, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_srai (ORBIS32_I, "l.srai", parse_i32("6x2e 10x0 8x0 2x2 6x0"), parse_i32("6xFF 10x0 8x0 2xF 6x0"), shift< true, true, true >, 0, or1k_asm_print_rDAI< false >)
static InstructionDefinition l_srl (ORBIS32_I, "l.srl", parse_i32("6x38 15x0 1x0 4x1 2x0 4x8"), parse_i32("6xFF 15x0 1x0 4xF 2x0 4xF"), shift< true, false, false >, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_srli (ORBIS32_I, "l.srli", parse_i32("6x2e 10x0 8x0 2x1 6x0"), parse_i32("6xFF 10x0 8x0 2xF 6x0"), shift< true, false, true >, 0, or1k_asm_print_rDAI< false >)
static InstructionDefinition l_sub (ORBIS32_I, "l.sub", parse_i32("6x38 15x0 1x0 2x0 4x0 4x2"), parse_i32("6xFF 15x0 1x0 2xF 4x0 4xF"), [](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { l_addsubX(std::string("(((OR1K*)cpu)->R[")+toString(ra.read(ba))+"])", std::string("(((OR1K*)cpu)->R[")+toString(rb.read(ba))+"])", std::string("(((OR1K*)cpu)->R[")+toString(rd.read(ba))+"])", cs, false, false);update_pc< false, false >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_sw (ORBIS32_I, "l.sw", parse_i32("6x35 26x0"), parse_i32("6xFF 26x0"), storeinstr< int32_t >, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_sys (ORBIS32_I, "l.sys", parse_i32("16x2000 16x0"), parse_i32("16xFFFF 16x0"), [](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { cs.append(CodePart("return OR1K_SYSTEMCALLEXCEPTION +"+toString(immediate.read(ba) &0x0000FFFF)+";"), CodePart::APPENDEDRETURNINGREQUIRED);update_pc< true, false >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_xor (ORBIS32_I, "l.xor", parse_i32("6x38 15x0 1x0 2x0 4x0 4x5"), parse_i32("6xFF 15x0 1x0 2xF 4x0 4xF"), simple_op_rDAB<'^'>, 0, or1k_asm_print_rDAB)
static InstructionDefinition l_xori (ORBIS32_I, "l.xori", parse_i32("6x2b 10x0 16x0"), parse_i32("6xFF 10x0 16x0"), simple_op_rDAI<'^', true >, 0, or1k_asm_print_rDAI< true >)
Macro Definition Documentation
NOP_CNT_RESET
#define NOP_CNT_RESET 0x0005 /* Reset statistics counters */
Definition at line 695 of file ORBIS32_I.cpp.
NOP_EXIT
#define NOP_EXIT 0x0001 /* End of simulation */
Definition at line 691 of file ORBIS32_I.cpp.
NOP_GET_PS
#define NOP_GET_PS 0x0007 /* JPB: Get picosecs/cycle */
Definition at line 697 of file ORBIS32_I.cpp.
NOP_GET_TICKS
#define NOP_GET_TICKS 0x0006 /* JPB: Get # ticks running */
Definition at line 696 of file ORBIS32_I.cpp.
NOP_NOP
#define NOP_NOP 0x0000 /* Normal nop instruction */
Definition at line 690 of file ORBIS32_I.cpp.
NOP_PUTC
#define NOP_PUTC 0x0004 /* JPB: Simputc instruction */
Definition at line 694 of file ORBIS32_I.cpp.
NOP_REPORT
#define NOP_REPORT 0x0002 /* Simple report */
Definition at line 692 of file ORBIS32_I.cpp.
NOP_REPORT_FIRST
#define NOP_REPORT_FIRST 0x0400 /* Report with number */
Definition at line 698 of file ORBIS32_I.cpp.
NOP_REPORT_LAST
#define NOP_REPORT_LAST 0x03ff /* Report with number */
Definition at line 699 of file ORBIS32_I.cpp.
Function Documentation
l_addsubX()
static void l_addsubX (std::string in1, std::string in2, std::string out, CodeSet & codeset, bool add, bool cy) static
Definition at line 48 of file ORBIS32_I.cpp.
References etiss::RegisterSet::add(), etiss::CodeSet::append(), etiss::CodePart::getAffectedRegisters(), etiss::CodePart::getCode(), etiss::CodePart::getRegisterDependencies(), OR1K_SR_CY, and OR1K_SR_OV.
loadinstr()
template<typename T , bool swap = (ETISS_ENDIANNESS != ETISS_BIG_ENDIAN)> static bool loadinstr (BitArray & ba, etiss::CodeSet & cs, InstructionContext & ic) static
Definition at line 156 of file ORBIS32_I.cpp.
References etiss::RegisterSet::add(), etiss::CodeSet::append(), etiss::CodePart::code(), etiss::CodePart::getAffectedRegisters(), etiss::CodePart::getRegisterDependencies(), immediate, ra, rd, etiss::instr::BitArrayRange::read(), reg, reg_name, and swap().
shift()
template<bool right, bool sig, bool imm> static bool shift (BitArray & ba, etiss::CodeSet & cs, InstructionContext & ic) static
Definition at line 137 of file ORBIS32_I.cpp.
References etiss::RegisterSet::add(), etiss::CodeSet::append(), etiss::CodePart::code(), etiss::CodePart::getAffectedRegisters(), etiss::CodePart::getRegisterDependencies(), immediate, ra, rb, rd, etiss::instr::BitArrayRange::read(), reg, reg_name, and etiss::toString().
Referenced by __bool2mask().
simple_op_rDAB()
template<char op> static bool simple_op_rDAB (BitArray & ba, etiss::CodeSet & cs, InstructionContext & ic) static
Definition at line 104 of file ORBIS32_I.cpp.
References etiss::RegisterSet::add(), etiss::CodeSet::append(), etiss::CodePart::code(), etiss::CodePart::getAffectedRegisters(), etiss::CodePart::getRegisterDependencies(), ra, rb, rd, etiss::instr::BitArrayRange::read(), reg, and reg_name.
simple_op_rDAI()
template<char op, bool sig> static bool simple_op_rDAI (BitArray & ba, etiss::CodeSet & cs, InstructionContext & ic) static
Definition at line 120 of file ORBIS32_I.cpp.
References etiss::RegisterSet::add(), etiss::CodeSet::append(), etiss::CodePart::code(), etiss::CodePart::getAffectedRegisters(), etiss::CodePart::getRegisterDependencies(), immediate, ra, rd, etiss::instr::BitArrayRange::read(), reg, reg_name, and etiss::toString().
storeinstr()
template<typename T , bool swap = (ETISS_ENDIANNESS != ETISS_BIG_ENDIAN)> static bool storeinstr (BitArray & ba, etiss::CodeSet & cs, InstructionContext & ic) static
Definition at line 206 of file ORBIS32_I.cpp.
References etiss::CodeSet::append(), ra, rb, rd, etiss::instr::BitArrayRange::read(), reg, reg_name, swap(), and etiss::toString().
Variable Documentation
l_add
InstructionDefinition l_add(ORBIS32_I, "l.add", parse_i32("6x38 15x0 1x0 2x0 4x0 4x0"), parse_i32("6xFF 15x0 1x0 2xF 4x0 4xF"),[](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { l_addsubX(reg[ra.read(ba)], reg[rb.read(ba)], reg[rd.read(ba)], cs, true, false);update_pc< false, false >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAB) static
l_addc
InstructionDefinition l_addc(ORBIS32_I, "l.addc", parse_i32("6x38 15x0 1x0 2x0 4x0 4x1"), parse_i32("6xFF 15x0 1x0 2xF 4x0 4xF"),[](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { l_addsubX(reg[ra.read(ba)], reg[rb.read(ba)], reg[rd.read(ba)], cs, true, true);update_pc< false, false >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAB) static
l_addi
InstructionDefinition l_addi(ORBIS32_I, "l.addi", parse_i32("6x27 10x0 16x0"), parse_i32("6xFF 10x0 16x0"),[](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { l_addsubX(reg[ra.read(ba)], toString((int16_t) immediate.read(ba)), reg[rd.read(ba)], cs, true, false);update_pc< false, false >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAI< true >) static
l_addic
InstructionDefinition l_addic(ORBIS32_I, "l.addic", parse_i32("6x28 10x0 16x0"), parse_i32("6xFF 10x0 16x0"),[](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { l_addsubX(reg[ra.read(ba)], toString((int16_t) immediate.read(ba)), reg[rd.read(ba)], cs, true, true);update_pc< false, false >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAB) static
l_and
InstructionDefinition l_and(ORBIS32_I, "l.and", parse_i32("6x38 15x0 1x0 2x0 4x0 4x3"), parse_i32("6xFF 15x0 1x0 2xF 4x0 4xF"), simple_op_rDAB<'&'>, 0, or1k_asm_print_rDAB) static
l_andi
InstructionDefinition l_andi(ORBIS32_I, "l.andi", parse_i32("6x29 10x0 16x0"), parse_i32("6xFF 10x0 16x0"), simple_op_rDAI<'&', false >, 0, or1k_asm_print_rDAI< false >) static
l_bf
InstructionDefinition l_bf(ORBIS32_I, "l.bf", parse_i32("6x4 26x0"), parse_i32("6xFF 26x0"),[](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { std::stringstream ss;ss<< " if (*(((OR1K*)cpu)->SR) & OR1K_SR_F){";ss<< " ((OR1K*)cpu)->instructionPointer_delayed = (uint32_t)("<< ic.current_address_<< "ULL + "<<(uint32_t)(((int32_t)((int16_t) immediate.read(ba)))<< 2)<< "ULL);";ss<< " }else{";ss<< " ((OR1K*)cpu)->instructionPointer_delayed = (uint32_t)("<< ic.current_address_<< "ULL + 8);";ss<< "}";CodePart &cp=cs.append(CodePart::INITIALREQUIRED);cp.getRegisterDependencies().add("SR", 32, OR1K_SR_F);cp.code()=ss.str();update_pc< true, true >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAB) static
l_bnf
InstructionDefinition l_bnf(ORBIS32_I, "l.bnf", parse_i32("6x3 26x0"), parse_i32("6xFF 26x0"),[](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { std::stringstream ss;ss<< " if ((*(((OR1K*)cpu)->SR) & OR1K_SR_F)==0){";ss<< " ((OR1K*)cpu)->instructionPointer_delayed = (uint32_t)("<< ic.current_address_<< "ULL + "<<(uint32_t)(((int32_t)((int16_t) immediate.read(ba)))<< 2)<< ");";ss<< " }else{";ss<< " ((OR1K*)cpu)->instructionPointer_delayed = (uint32_t)("<< ic.current_address_<< "ULL + 8);";ss<< "}";CodePart &cp=cs.append(CodePart::INITIALREQUIRED);cp.getRegisterDependencies().add("SR", 32, OR1K_SR_F);cp.code()=ss.str();update_pc< true, true >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAB) static
l_j
InstructionDefinition l_j(ORBIS32_I, "l.j", parse_i32("6x0 26x0"), parse_i32("6xFF 26x0"),[](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { uint32_t jaddr=(uint32_t)(ic.current_address_+((((int32_t) limmediate.read(ba))<< 6) >> 4));std::stringstream ss;ss<< " ((OR1K*)cpu)->instructionPointer_delayed = (uint32_t)"+toString(jaddr)+"ULL;";CodePart &cp=cs.append(CodePart::INITIALREQUIRED);cp.code()=ss.str();update_pc< true, true >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAB) static
l_jal
InstructionDefinition l_jal(ORBIS32_I, "l.jal", parse_i32("6x1 26x0"), parse_i32("6xFF 26x0"),[](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { uint32_t jaddr=(uint32_t)(ic.current_address_+((((int32_t) limmediate.read(ba))<< 6) >> 4));std::stringstream ss;ss<< " ((OR1K*)cpu)->instructionPointer_delayed = (uint32_t)"+toString(jaddr)+"ULL;";ss<< " ((OR1K*)cpu)->R[9] = "+toString(ic.current_address_+8)+";";CodePart &cp=cs.append(CodePart::INITIALREQUIRED);cp.code()=ss.str();update_pc< true, true >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAB) static
l_jalr
InstructionDefinition l_jalr(ORBIS32_I, "l.jalr", parse_i32("6x12 26x0"), parse_i32("6xFF 26x0"),[](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { std::stringstream ss;ss<< " ((OR1K*)cpu)->instructionPointer_delayed = (uint32_t)("<< reg[rb.read(ba)]<< ");";ss<< " ((OR1K*)cpu)->R[9] = "+toString(ic.current_address_+8)+";";CodePart &cp=cs.append(CodePart::INITIALREQUIRED);cp.getRegisterDependencies().add(reg_name[rb.read(ba)], 32);cp.code()=ss.str();update_pc< true, true >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAB) static
l_jr
InstructionDefinition l_jr(ORBIS32_I, "l.jr", parse_i32("6x11 26x0"), parse_i32("6xFF 26x0"),[](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { std::stringstream ss;ss<< " ((OR1K*)cpu)->instructionPointer_delayed = (uint32_t)("<< reg[rb.read(ba)]<< ");";CodePart &cp=cs.append(CodePart::INITIALREQUIRED);cp.getRegisterDependencies().add(reg_name[rb.read(ba)], 32);cp.code()=ss.str();update_pc< true, true >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAB) static
l_lbs
InstructionDefinition l_lbs(ORBIS32_I, "l.lbs", parse_i32("6x24 26x0"), parse_i32("6xFF 26x0"), loadinstr< int8_t >, 0, or1k_asm_print_rDAB) static
l_lbz
InstructionDefinition l_lbz(ORBIS32_I, "l.lbz", parse_i32("6x23 26x0"), parse_i32("6xFF 26x0"), loadinstr< uint8_t >, 0, or1k_asm_print_rDAB) static
l_lhs
InstructionDefinition l_lhs(ORBIS32_I, "l.lhs", parse_i32("6x26 26x0"), parse_i32("6xFF 26x0"), loadinstr< int16_t >, 0, or1k_asm_print_rDAB) static
l_lhz
InstructionDefinition l_lhz(ORBIS32_I, "l.lhz", parse_i32("6x25 26x0"), parse_i32("6xFF 26x0"), loadinstr< uint16_t >, 0, or1k_asm_print_rDAB) static
l_lws
InstructionDefinition l_lws(ORBIS32_I, "l.lws", parse_i32("6x22 26x0"), parse_i32("6xFF 26x0"), loadinstr< int32_t >, 0, or1k_asm_print_rDAB) static
l_lwz
InstructionDefinition l_lwz(ORBIS32_I, "l.lwz", parse_i32("6x21 26x0"), parse_i32("6xFF 26x0"), loadinstr< int32_t >, 0, or1k_asm_print_rDAB) static
l_mfspr
InstructionDefinition l_mfspr(ORBIS32_I, "l.mfspr", parse_i32("6x2d 26x0"), parse_i32("6xFF 26x0"),[](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { CodePart &cp=cs.append(CodePart::INITIALREQUIRED); cp.code()=std::string(reg[rd.read(ba)])+" = OR1KArch_mfspr((OR1K*)cpu,"+reg[ra.read(ba)]+"|"+toString(immediate.read(ba))+");";update_pc< false, false >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAI< false >) static
l_movhi
InstructionDefinition l_movhi(ORBIS32_I, "l.movhi", parse_i32("6x6 5x0 4x0 1x0 16x0"), parse_i32("6xFF 5x0 4x0 1xF 16x0"),[](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { CodePart &cp=cs.append(CodePart::INITIALREQUIRED);cp.code()=std::string(reg[rd.read(ba)])+" = (etiss_uint32) "+toString(((uint32_t) immediate.read(ba))<< 16)+";";update_pc< false, false >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAI< false >) static
l_mtspr
InstructionDefinition l_mtspr(ORBIS32_I, "l.mtspr", parse_i32("6x30 26x0"), parse_i32("6xFF 26x0"),[](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { CodePart &cp=cs.append(CodePart::INITIALREQUIRED); cp.getRegisterDependencies().add(reg_name[ra.read(ba)], 32);cp.getRegisterDependencies().add(reg_name[rb.read(ba)], 32);BitArrayRange immp1(25, 21);BitArrayRange immp2(10, 0);cp.code()=std::string("OR1KArch_mtspr((OR1K*)cpu,")+reg[ra.read(ba)]+"|"+toString((immp1.read(ba)<< 11)|immp2.read(ba))+", "+reg[rb.read(ba)]+");";update_pc< false, false >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAI< false >) static
l_nop
InstructionDefinition l_nop(ORBIS32_I, "l.nop", parse_i32("8x15 24x0"), parse_i32("8xFF 24x0"),[](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { uint32_t nopcode=l_nop_param.read(ba);if(nopcode !=NOP_NOP) { if(nopcode==NOP_EXIT) { cs.append(CodePart::APPENDEDRETURNINGREQUIRED).code()="return ETISS_RETURNCODE_CPUFINISHED ;";} if(nopcode==NOP_REPORT) { cs.append(CodePart::INITIALREQUIRED).code()=std::string("OR1K_report((uint32_t)")+reg[3]+");";} if(nopcode==NOP_PUTC) { cs.append(CodePart::INITIALREQUIRED).code()=std::string("OR1K_printchar((char)")+reg[3]+");";} if(nopcode==NOP_GET_PS) { cs.append(CodePart::INITIALREQUIRED).code()=std::string(reg[11])+" = (etiss_uint32) (cpu->cpuCycleTime_ps);";} } update_pc< false, false >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAB) static
l_nop_param
BitArrayRange l_nop_param(23, 0) static
l_or
InstructionDefinition l_or(ORBIS32_I, "l.or", parse_i32("6x38 15x0 1x0 2x0 4x0 4x4"), parse_i32("6xFF 15x0 1x0 2xF 4x0 4xF"), simple_op_rDAB<'|'>, 0, or1k_asm_print_rDAB) static
l_ori
InstructionDefinition l_ori(ORBIS32_I, "l.ori", parse_i32("6x2a 10x0 16x0"), parse_i32("6xFF 10x0 16x0"), simple_op_rDAI<'|', false >, 0, or1k_asm_print_rDAI< false >) static
l_rfe
InstructionDefinition l_rfe(ORBIS32_I, "l.rfe", parse_i32("6x9 26x0"), parse_i32("6xFF 26x0"),[](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { std::stringstream ss;ss<< " ((OR1K*)cpu)->instructionPointer_delayed = ((OR1K*)cpu)->EPCR_16[0];\n";ss<< " *((OR1K*)cpu)->SR = ((OR1K*)cpu)->ESR_16[0];";CodePart &cp=cs.append(CodePart::INITIALREQUIRED);cp.getRegisterDependencies().add(reg_name[rb.read(ba)], 32);cp.code()=ss.str();update_pc< true, false >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAB) static
l_sb
InstructionDefinition l_sb(ORBIS32_I, "l.sb", parse_i32("6x36 26x0"), parse_i32("6xFF 26x0"), storeinstr< int8_t >, 0, or1k_asm_print_rDAB) static
l_sfeq
InstructionDefinition l_sfeq(ORBIS32_I, "l.sfeq", parse_i32("11x720 21x0"), parse_i32("11xFFF 21x0"), l_sf< true, false, '=', '='>, 0, or1k_asm_print_rDAB) static
l_sfges
InstructionDefinition l_sfges(ORBIS32_I, "l.sfges", parse_i32("11x72b 21x0"), parse_i32("11xFFF 21x0"), l_sf< true, false, '>', '='>, 0, or1k_asm_print_rDAB) static
l_sfgeu
InstructionDefinition l_sfgeu(ORBIS32_I, "l.sfgeu", parse_i32("11x723 21x0"), parse_i32("11xFFF 21x0"), l_sf< false, false, '>', '='>, 0, or1k_asm_print_rDAB) static
l_sfgts
InstructionDefinition l_sfgts(ORBIS32_I, "l.sfgts", parse_i32("11x72a 21x0"), parse_i32("11xFFF 21x0"), l_sf< true, false, '>'>, 0, or1k_asm_print_rDAB) static
l_sfgtu
InstructionDefinition l_sfgtu(ORBIS32_I, "l.sfgtu", parse_i32("11x722 21x0"), parse_i32("11xFFF 21x0"), l_sf< false, false, '>'>, 0, or1k_asm_print_rDAB) static
l_sfles
InstructionDefinition l_sfles(ORBIS32_I, "l.sfles", parse_i32("11x72d 21x0"), parse_i32("11xFFF 21x0"), l_sf< true, false, '<', '='>, 0, or1k_asm_print_rDAB) static
l_sfleu
InstructionDefinition l_sfleu(ORBIS32_I, "l.sfleu", parse_i32("11x725 21x0"), parse_i32("11xFFF 21x0"), l_sf< false, false, '<', '='>, 0, or1k_asm_print_rDAB) static
l_sflts
InstructionDefinition l_sflts(ORBIS32_I, "l.sflts", parse_i32("11x72c 21x0"), parse_i32("11xFFF 21x0"), l_sf< true, false, '<'>, 0, or1k_asm_print_rDAB) static
l_sfltu
InstructionDefinition l_sfltu(ORBIS32_I, "l.sfltu", parse_i32("11x724 21x0"), parse_i32("11xFFF 21x0"), l_sf< false, false, '<'>, 0, or1k_asm_print_rDAB) static
l_sfne
InstructionDefinition l_sfne(ORBIS32_I, "l.sfne", parse_i32("11x721 21x0"), parse_i32("11xFFF 21x0"), l_sf< true, false, '!', '='>, 0, or1k_asm_print_rDAB) static
l_sh
InstructionDefinition l_sh(ORBIS32_I, "l.sh", parse_i32("6x37 26x0"), parse_i32("6xFF 26x0"), storeinstr< int16_t >, 0, or1k_asm_print_rDAB) static
l_sll
InstructionDefinition l_sll(ORBIS32_I, "l.sll", parse_i32("6x38 15x0 1x0 4x0 2x0 4x8"), parse_i32("6xFF 15x0 1x0 4xF 2x0 4xF"), shift< false, false, false >, 0, or1k_asm_print_rDAB) static
l_slli
InstructionDefinition l_slli(ORBIS32_I, "l.slli", parse_i32("6x2e 10x0 8x0 2x0 6x0"), parse_i32("6xFF 10x0 8x0 2xF 6x0"), shift< false, false, true >, 0, or1k_asm_print_rDAI< false >) static
l_sra
InstructionDefinition l_sra(ORBIS32_I, "l.sra", parse_i32("6x38 15x0 1x0 4x2 2x0 4x8"), parse_i32("6xFF 15x0 1x0 4xF 2x0 4xF"), shift< true, true, false >, 0, or1k_asm_print_rDAB) static
l_srai
InstructionDefinition l_srai(ORBIS32_I, "l.srai", parse_i32("6x2e 10x0 8x0 2x2 6x0"), parse_i32("6xFF 10x0 8x0 2xF 6x0"), shift< true, true, true >, 0, or1k_asm_print_rDAI< false >) static
l_srl
InstructionDefinition l_srl(ORBIS32_I, "l.srl", parse_i32("6x38 15x0 1x0 4x1 2x0 4x8"), parse_i32("6xFF 15x0 1x0 4xF 2x0 4xF"), shift< true, false, false >, 0, or1k_asm_print_rDAB) static
l_srli
InstructionDefinition l_srli(ORBIS32_I, "l.srli", parse_i32("6x2e 10x0 8x0 2x1 6x0"), parse_i32("6xFF 10x0 8x0 2xF 6x0"), shift< true, false, true >, 0, or1k_asm_print_rDAI< false >) static
l_sub
InstructionDefinition l_sub(ORBIS32_I, "l.sub", parse_i32("6x38 15x0 1x0 2x0 4x0 4x2"), parse_i32("6xFF 15x0 1x0 2xF 4x0 4xF"),[](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { l_addsubX(std::string("(((OR1K*)cpu)->R[")+toString(ra.read(ba))+"])", std::string("(((OR1K*)cpu)->R[")+toString(rb.read(ba))+"])", std::string("(((OR1K*)cpu)->R[")+toString(rd.read(ba))+"])", cs, false, false);update_pc< false, false >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAB) static
l_sw
InstructionDefinition l_sw(ORBIS32_I, "l.sw", parse_i32("6x35 26x0"), parse_i32("6xFF 26x0"), storeinstr< int32_t >, 0, or1k_asm_print_rDAB) static
l_sys
InstructionDefinition l_sys(ORBIS32_I, "l.sys", parse_i32("16x2000 16x0"), parse_i32("16xFFFF 16x0"),[](BitArray &ba, etiss::CodeSet &cs, InstructionContext &ic) { cs.append(CodePart("return OR1K_SYSTEMCALLEXCEPTION +"+ toString(immediate.read(ba) &0x0000FFFF)+";"), CodePart::APPENDEDRETURNINGREQUIRED);update_pc< true, false >(ba, cs, ic);return true;}, 0, or1k_asm_print_rDAB) static
l_xor
InstructionDefinition l_xor(ORBIS32_I, "l.xor", parse_i32("6x38 15x0 1x0 2x0 4x0 4x5"), parse_i32("6xFF 15x0 1x0 2xF 4x0 4xF"), simple_op_rDAB<'^'>, 0, or1k_asm_print_rDAB) static
l_xori
InstructionDefinition l_xori(ORBIS32_I, "l.xori", parse_i32("6x2b 10x0 16x0"), parse_i32("6xFF 10x0 16x0"), simple_op_rDAI<'^', true >, 0, or1k_asm_print_rDAI< true >) static
ORBIS32_I
InstructionGroup ORBIS32_I("ORBIS32_I", 32)