ETISS 0.8.0: xpath_query_impl Struct Reference
xpath_query_impl Struct Reference
Public Member Functions
xpath_query_impl ()
Static Public Member Functions
static xpath_query_impl * create ()
static void destroy (void *ptr)
Public Attributes
xpath_ast_node * root
xpath_allocator alloc
xpath_memory_block block
Detailed Description
Definition at line 10548 of file pugixml.cpp.
Constructor & Destructor Documentation
xpath_query_impl()
xpath_query_impl::xpath_query_impl () inline
Definition at line 10569 of file pugixml.cpp.
References block, and xpath_memory_block::next.
Referenced by create().
Member Function Documentation
create()
static xpath_query_impl* xpath_query_impl::create () inline static
Definition at line 10550 of file pugixml.cpp.
References xml_memory_management_function_storage< T >::allocate, and xpath_query_impl().
destroy()
static void xpath_query_impl::destroy (void * ptr) inline static
Definition at line 10557 of file pugixml.cpp.
References alloc, xml_memory_management_function_storage< T >::deallocate, and xpath_allocator::release().
Member Data Documentation
alloc
xpath_allocator xpath_query_impl::alloc
Definition at line 10572 of file pugixml.cpp.
Referenced by destroy().
block
xpath_memory_block xpath_query_impl::block
Definition at line 10573 of file pugixml.cpp.
Referenced by xpath_query_impl().
root
xpath_ast_node* xpath_query_impl::root
Definition at line 10571 of file pugixml.cpp.
Referenced by evaluate_string_impl().
The documentation for this struct was generated from the following file:
/home/runner/work/etiss/etiss/src/fault/xml/pugixml.cpp