ETISS 0.8.0: gap Struct Reference
gap Struct Reference
Public Member Functions
gap ()
void push (char_t *&s, size_t count)
char_t * flush (char_t *s)
Public Attributes
char_t * end
size_t size
Detailed Description
Definition at line 1749 of file pugixml.cpp.
Constructor & Destructor Documentation
gap()
gap::gap () inline
Definition at line 1754 of file pugixml.cpp.
Member Function Documentation
flush()
char_t* gap::flush (char_t * s) inline
Definition at line 1775 of file pugixml.cpp.
References end, s, and size.
Referenced by strconv_pcdata_impl< opt_trim, opt_eol, opt_escape >::parse(), strconv_attribute_impl< opt_escape >::parse_eol(), strconv_attribute_impl< opt_escape >::parse_simple(), strconv_attribute_impl< opt_escape >::parse_wconv(), strconv_attribute_impl< opt_escape >::parse_wnorm(), strconv_cdata(), and strconv_comment().
push()
void gap::push (char_t *& s, size_t count) inline
Definition at line 1758 of file pugixml.cpp.
References end, s, and size.
Referenced by strconv_pcdata_impl< opt_trim, opt_eol, opt_escape >::parse(), strconv_attribute_impl< opt_escape >::parse_eol(), strconv_attribute_impl< opt_escape >::parse_wconv(), strconv_attribute_impl< opt_escape >::parse_wnorm(), strconv_cdata(), strconv_comment(), and strconv_escape().
Member Data Documentation
end
char_t* gap::end
Definition at line 1751 of file pugixml.cpp.
Referenced by flush(), and push().
size
size_t gap::size
Definition at line 1752 of file pugixml.cpp.
Referenced by flush(), and push().
The documentation for this struct was generated from the following file:
/home/runner/work/etiss/etiss/src/fault/xml/pugixml.cpp