ETISS 0.8.0: namespace_uri_predicate Struct Reference
namespace_uri_predicate Struct Reference
Public Member Functions
namespace_uri_predicate (const char_t *name)
bool operator() (const xml_attribute &a) const
Public Attributes
const char_t * prefix
size_t prefix_length
Detailed Description
Definition at line 7403 of file pugixml.cpp.
Constructor & Destructor Documentation
namespace_uri_predicate()
namespace_uri_predicate::namespace_uri_predicate (const char_t * name) inline
Definition at line 7408 of file pugixml.cpp.
References find_char(), name, prefix, and prefix_length.
Member Function Documentation
operator()()
bool namespace_uri_predicate::operator() (const xml_attribute & a) const inline
Definition at line 7416 of file pugixml.cpp.
References name, prefix, prefix_length, PUGIXML_TEXT, starts_with(), and strequalrange().
Member Data Documentation
prefix
const char_t* namespace_uri_predicate::prefix
Definition at line 7405 of file pugixml.cpp.
Referenced by namespace_uri(), namespace_uri_predicate(), and operator()().
prefix_length
size_t namespace_uri_predicate::prefix_length
Definition at line 7406 of file pugixml.cpp.
Referenced by namespace_uri_predicate(), and operator()().
The documentation for this struct was generated from the following file:
/home/runner/work/etiss/etiss/src/fault/xml/pugixml.cpp