ETISS 0.8.0: xpath_parser::binary_op_t Struct Reference
xpath_parser::binary_op_t Struct Reference
Public Member Functions
binary_op_t ()
binary_op_t (ast_type_t asttype_, xpath_value_type rettype_, int precedence_)
Static Public Member Functions
static binary_op_t parse (xpath_lexer &lexer)
Public Attributes
ast_type_t asttype
xpath_value_type rettype
int precedence
Detailed Description
Definition at line 10399 of file pugixml.cpp.
Constructor & Destructor Documentation
binary_op_t() [1/2]
xpath_parser::binary_op_t::binary_op_t () inline
Definition at line 10405 of file pugixml.cpp.
Referenced by parse().
binary_op_t() [2/2]
xpath_parser::binary_op_t::binary_op_t (ast_type_t asttype_, xpath_value_type rettype_, int precedence_) inline
Definition at line 10407 of file pugixml.cpp.
Member Function Documentation
parse()
static binary_op_t xpath_parser::binary_op_t::parse (xpath_lexer & lexer) inline static
Definition at line 10412 of file pugixml.cpp.
References ast_op_add, ast_op_and, ast_op_divide, ast_op_equal, ast_op_greater, ast_op_greater_or_equal, ast_op_less, ast_op_less_or_equal, ast_op_mod, ast_op_multiply, ast_op_not_equal, ast_op_or, ast_op_subtract, ast_op_union, binary_op_t(), xpath_lexer::contents(), xpath_lexer::current(), lex_equal, lex_greater, lex_greater_or_equal, lex_less, lex_less_or_equal, lex_minus, lex_multiply, lex_not_equal, lex_plus, lex_string, lex_union, PUGIXML_TEXT, pugi::xpath_type_boolean, pugi::xpath_type_node_set, and pugi::xpath_type_number.
Referenced by xpath_parser::parse_expression_rec().
Member Data Documentation
asttype
ast_type_t xpath_parser::binary_op_t::asttype
Definition at line 10401 of file pugixml.cpp.
Referenced by xpath_parser::parse_expression_rec().
precedence
int xpath_parser::binary_op_t::precedence
Definition at line 10403 of file pugixml.cpp.
Referenced by xpath_parser::parse_expression_rec().
rettype
xpath_value_type xpath_parser::binary_op_t::rettype
Definition at line 10402 of file pugixml.cpp.
Referenced by xpath_parser::parse_expression_rec().
The documentation for this struct was generated from the following file:
/home/runner/work/etiss/etiss/src/fault/xml/pugixml.cpp