ETISS 0.8.0: utf_decoder< Traits, opt_swap > Struct Template Reference
utf_decoder< Traits, opt_swap > Struct Template Reference
Static Public Member Functions
static Traits::value_type decode_utf8_block (const uint8_t *data, size_t size, typename Traits::value_type result)
static Traits::value_type decode_utf16_block (const uint16_t *data, size_t size, typename Traits::value_type result)
static Traits::value_type decode_utf32_block (const uint32_t *data, size_t size, typename Traits::value_type result)
static Traits::value_type decode_latin1_block (const uint8_t *data, size_t size, typename Traits::value_type result)
static Traits::value_type decode_wchar_block_impl (const uint16_t *data, size_t size, typename Traits::value_type result)
static Traits::value_type decode_wchar_block_impl (const uint32_t *data, size_t size, typename Traits::value_type result)
static Traits::value_type decode_wchar_block (const wchar_t *data, size_t size, typename Traits::value_type result)
Detailed Description
template<typename Traits, typename opt_swap = opt_false>
struct utf_decoder< Traits, opt_swap >
Definition at line 930 of file pugixml.cpp.
Member Function Documentation
decode_latin1_block()
template<typename Traits , typename opt_swap = opt_false> static Traits::value_type utf_decoder< Traits, opt_swap >::decode_latin1_block (const uint8_t * data, size_t size, typename Traits::value_type result) inline static
Definition at line 1071 of file pugixml.cpp.
Referenced by convert_buffer_latin1().
decode_utf16_block()
template<typename Traits , typename opt_swap = opt_false> static Traits::value_type utf_decoder< Traits, opt_swap >::decode_utf16_block (const uint16_t * data, size_t size, typename Traits::value_type result) inline static
Definition at line 1000 of file pugixml.cpp.
References endian_swap().
Referenced by convert_buffer_utf16(), and utf_decoder< Traits, opt_swap >::decode_wchar_block_impl().
decode_utf32_block()
template<typename Traits , typename opt_swap = opt_false> static Traits::value_type utf_decoder< Traits, opt_swap >::decode_utf32_block (const uint32_t * data, size_t size, typename Traits::value_type result) inline static
Definition at line 1045 of file pugixml.cpp.
References endian_swap().
Referenced by convert_buffer_utf32(), and utf_decoder< Traits, opt_swap >::decode_wchar_block_impl().
decode_utf8_block()
template<typename Traits , typename opt_swap = opt_false> static Traits::value_type utf_decoder< Traits, opt_swap >::decode_utf8_block (const uint8_t * data, size_t size, typename Traits::value_type result) inline static
Definition at line 932 of file pugixml.cpp.
Referenced by as_wide_impl(), and convert_buffer_output().
decode_wchar_block()
template<typename Traits , typename opt_swap = opt_false> static Traits::value_type utf_decoder< Traits, opt_swap >::decode_wchar_block (const wchar_t * data, size_t size, typename Traits::value_type result) inline static
Definition at line 1094 of file pugixml.cpp.
References utf_decoder< Traits, opt_swap >::decode_wchar_block_impl().
Referenced by as_utf8_begin(), and as_utf8_end().
decode_wchar_block_impl() [1/2]
template<typename Traits , typename opt_swap = opt_false> static Traits::value_type utf_decoder< Traits, opt_swap >::decode_wchar_block_impl (const uint16_t * data, size_t size, typename Traits::value_type result) inline static
Definition at line 1082 of file pugixml.cpp.
References utf_decoder< Traits, opt_swap >::decode_utf16_block().
Referenced by utf_decoder< Traits, opt_swap >::decode_wchar_block().
decode_wchar_block_impl() [2/2]
template<typename Traits , typename opt_swap = opt_false> static Traits::value_type utf_decoder< Traits, opt_swap >::decode_wchar_block_impl (const uint32_t * data, size_t size, typename Traits::value_type result) inline static
Definition at line 1088 of file pugixml.cpp.
References utf_decoder< Traits, opt_swap >::decode_utf32_block().
The documentation for this struct was generated from the following file:
/home/runner/work/etiss/etiss/src/fault/xml/pugixml.cpp