ETISS 0.8.0: xml_parser Struct Reference
xml_parser Struct Reference
Public Member Functions
xml_parser (const xml_allocator &alloc_)
char_t * parse_doctype_primitive (char_t *s)
char_t * parse_doctype_ignore (char_t *s)
char_t * parse_doctype_group (char_t *s, char_t endch, bool toplevel)
char_t * parse_exclamation (char_t *s, xml_node_struct *cursor, unsigned int optmsk, char_t endch)
char_t * parse_question (char_t *s, xml_node_struct *&ref_cursor, unsigned int optmsk, char_t endch)
char_t * parse_tree (char_t *s, xml_node_struct *root, unsigned int optmsk, char_t endch)
Static Public Member Functions
static char_t * parse_skip_bom (char_t *s)
static bool has_element_node_siblings (xml_node_struct *node)
static xml_parse_result parse (char_t *buffer, size_t length, xml_document_struct *xmldoc, xml_node_struct *root, unsigned int optmsk)
Public Attributes
xml_allocator alloc
char_t * error_offset
xml_parse_status error_status
Detailed Description
Definition at line 2302 of file pugixml.cpp.
Constructor & Destructor Documentation
xml_parser()
xml_parser::xml_parser (const xml_allocator & alloc_) inline
Definition at line 2348 of file pugixml.cpp.
Member Function Documentation
has_element_node_siblings()
static bool xml_parser::has_element_node_siblings (xml_node_struct * node) inline static
Definition at line 2966 of file pugixml.cpp.
References pugi::node_element, and xml_memory_page_type_mask.
Referenced by parse().
parse()
static xml_parse_result xml_parser::parse (char_t * buffer, size_t length, xml_document_struct * xmldoc, xml_node_struct * root, unsigned int optmsk) inline static
Definition at line 2980 of file pugixml.cpp.
References alloc, error_offset, error_status, has_element_node_siblings(), length(), make_parse_result(), pugi::parse_fragment, parse_skip_bom(), parse_tree(), PUGI__OPTSET, pugi::status_no_document_element, pugi::status_ok, and pugi::status_unrecognized_tag.
parse_doctype_group()
char_t* xml_parser::parse_doctype_group (char_t * s, char_t endch, bool toplevel) inline
Definition at line 2423 of file pugixml.cpp.
References parse_doctype_ignore(), parse_doctype_primitive(), PUGI__THROW_ERROR, s, and pugi::status_bad_doctype.
Referenced by parse_exclamation().
parse_doctype_ignore()
char_t* xml_parser::parse_doctype_ignore (char_t * s) inline
Definition at line 2395 of file pugixml.cpp.
References PUGI__THROW_ERROR, s, and pugi::status_bad_doctype.
Referenced by parse_doctype_group().
parse_doctype_primitive()
char_t* xml_parser::parse_doctype_primitive (char_t * s) inline
Definition at line 2357 of file pugixml.cpp.
References PUGI__SCANFOR, PUGI__THROW_ERROR, s, and pugi::status_bad_doctype.
Referenced by parse_doctype_group().
parse_exclamation()
char_t* xml_parser::parse_exclamation (char_t * s, xml_node_struct * cursor, unsigned int optmsk, char_t endch) inline
Definition at line 2472 of file pugixml.cpp.
References ct_space, ENDSWITH, pugi::node_cdata, pugi::node_comment, pugi::node_doctype, pugi::parse_cdata, pugi::parse_comments, pugi::parse_doctype, parse_doctype_group(), pugi::parse_eol, PUGI__CHECK_ERROR, PUGI__IS_CHARTYPE, PUGI__OPTSET, PUGI__POPNODE, PUGI__PUSHNODE, PUGI__SCANFOR, PUGI__THROW_ERROR, s, pugi::status_bad_cdata, pugi::status_bad_comment, pugi::status_bad_doctype, pugi::status_unrecognized_tag, strconv_cdata(), and strconv_comment().
Referenced by parse_tree().
parse_question()
char_t* xml_parser::parse_question (char_t * s, xml_node_struct *& ref_cursor, unsigned int optmsk, char_t endch) inline
Definition at line 2595 of file pugixml.cpp.
References ct_space, ct_start_symbol, ct_symbol, ENDSWITH, pugi::node_declaration, pugi::node_pi, pugi::parse_declaration, pugi::parse_pi, PUGI__CHECK_ERROR, PUGI__ENDSEG, PUGI__IS_CHARTYPE, PUGI__OPTSET, PUGI__POPNODE, PUGI__PUSHNODE, PUGI__SCANFOR, PUGI__SCANWHILE, PUGI__SKIPWS, PUGI__THROW_ERROR, s, and pugi::status_bad_pi.
Referenced by parse_tree().
parse_skip_bom()
static char_t* xml_parser::parse_skip_bom (char_t * s) inline static
Definition at line 2960 of file pugixml.cpp.
References s.
Referenced by parse().
parse_tree()
char_t* xml_parser::parse_tree (char_t * s, xml_node_struct * root, unsigned int optmsk, char_t endch) inline
Definition at line 2694 of file pugixml.cpp.
References alloc, append_attribute_ll(), ct_space, ct_start_symbol, ct_symbol, ENDSWITH, get_strconv_attribute(), get_strconv_pcdata(), name, pugi::node_declaration, pugi::node_element, pugi::node_pcdata, parse_exclamation(), pugi::parse_fragment, parse_question(), pugi::parse_trim_pcdata, pugi::parse_ws_pcdata, pugi::parse_ws_pcdata_single, PUGI__CHECK_ERROR, PUGI__ENDSEG, PUGI__IS_CHARTYPE, PUGI__OPTSET, PUGI__POPNODE, PUGI__PUSHNODE, PUGI__SCANFOR, PUGI__SCANWHILE, PUGI__SKIPWS, PUGI__THROW_ERROR, s, pugi::status_bad_attribute, pugi::status_bad_end_element, pugi::status_bad_pi, pugi::status_bad_start_element, pugi::status_end_element_mismatch, pugi::status_out_of_memory, pugi::status_unrecognized_tag, and xml_memory_page_type_mask.
Referenced by parse().
Member Data Documentation
alloc
xml_allocator xml_parser::alloc
Definition at line 2304 of file pugixml.cpp.
Referenced by parse(), and parse_tree().
error_offset
char_t* xml_parser::error_offset
Definition at line 2305 of file pugixml.cpp.
Referenced by parse().
error_status
xml_parse_status xml_parser::error_status
Definition at line 2306 of file pugixml.cpp.
Referenced by parse().
The documentation for this struct was generated from the following file:
/home/runner/work/etiss/etiss/src/fault/xml/pugixml.cpp