ETISS 0.8.0: etiss::DataSheetAccurateTiming::Rule Struct Reference
etiss::DataSheetAccurateTiming::Rule Struct Reference
Public Attributes
std::function< bool(uint32_t)> mode
std::function< bool(unsigned)> width
std::function< bool(etiss::instr::Instruction &)> instr
std::function< void(etiss::instr::Instruction &)> handler
Detailed Description
Definition at line 69 of file Timing.h.
Member Data Documentation
handler
std::function< void(etiss::instr::Instruction &)> etiss::DataSheetAccurateTiming::Rule::handler
Definition at line 74 of file Timing.h.
Referenced by etiss::DataSheetAccurateTiming::addRule().
instr
std::function< bool(etiss::instr::Instruction &)> etiss::DataSheetAccurateTiming::Rule::instr
Definition at line 73 of file Timing.h.
Referenced by etiss::DataSheetAccurateTiming::addRule().
mode
std::function< bool(uint32_t)> etiss::DataSheetAccurateTiming::Rule::mode
Definition at line 71 of file Timing.h.
Referenced by etiss::DataSheetAccurateTiming::addRule(), and etiss::DataSheetAccurateTiming::initInstrSet().
width
std::function< bool(unsigned)> etiss::DataSheetAccurateTiming::Rule::width
Definition at line 72 of file Timing.h.
Referenced by etiss::DataSheetAccurateTiming::addRule().
The documentation for this struct was generated from the following file:
include/etiss/Timing.h