ETISS 0.8.0: xml_stream_chunk< T > Struct Template Reference
xml_stream_chunk< T > Struct Template Reference
Public Member Functions
xml_stream_chunk ()
Static Public Member Functions
static xml_stream_chunk * create ()
static void destroy (void *ptr)
Public Attributes
xml_stream_chunk * next
size_t size
T data [xml_memory_page_size/sizeof(T)]
Detailed Description
template<typename T>
struct xml_stream_chunk< T >
Definition at line 4009 of file pugixml.cpp.
Constructor & Destructor Documentation
xml_stream_chunk()
template<typename T > xml_stream_chunk< T >::xml_stream_chunk () inline
Definition at line 4031 of file pugixml.cpp.
Referenced by xml_stream_chunk< T >::create().
Member Function Documentation
create()
template<typename T > static xml_stream_chunk* xml_stream_chunk< T >::create () inline static
Definition at line 4011 of file pugixml.cpp.
References xml_memory_management_function_storage< T >::allocate, and xml_stream_chunk< T >::xml_stream_chunk().
Referenced by load_stream_data_noseek().
destroy()
template<typename T > static void xml_stream_chunk< T >::destroy (void * ptr) inline static
Definition at line 4018 of file pugixml.cpp.
References xml_memory_management_function_storage< T >::deallocate, and xml_stream_chunk< T >::next.
Member Data Documentation
data
template<typename T > T xml_stream_chunk< T >::data[xml_memory_page_size/sizeof(T)]
Definition at line 4036 of file pugixml.cpp.
Referenced by load_stream_data_noseek().
next
template<typename T > xml_stream_chunk* xml_stream_chunk< T >::next
Definition at line 4033 of file pugixml.cpp.
Referenced by xml_stream_chunk< T >::destroy(), and load_stream_data_noseek().
size
template<typename T > size_t xml_stream_chunk< T >::size
Definition at line 4034 of file pugixml.cpp.
Referenced by load_stream_data_noseek().
The documentation for this struct was generated from the following file:
/home/runner/work/etiss/etiss/src/fault/xml/pugixml.cpp