ETISS 0.8.0: SI_GenericNoCase< SI_CHAR > Struct Template Reference
SI_GenericNoCase< SI_CHAR > Struct Template Reference
Generic ASCII case-insensitive less than comparison.
#include <SimpleIni.h>
Public Member Functions
SI_CHAR locase (SI_CHAR ch) const
bool operator() (const SI_CHAR *pLeft, const SI_CHAR *pRight) const
SI_CHAR locase (SI_CHAR ch) const
bool operator() (const SI_CHAR *pLeft, const SI_CHAR *pRight) const
Detailed Description
template<class SI_CHAR>
struct SI_GenericNoCase< SI_CHAR >
Generic ASCII case-insensitive less than comparison.
This class returns numerically ordered ASCII case-insensitive text for all possible sizes and types of SI_CHAR. It is not safe for MBCS text comparison where ASCII A-Z characters are used in the encoding of multi-byte characters.
Definition at line 2634 of file SimpleIni.h.
Member Function Documentation
locase() [1/2]
template<class SI_CHAR > SI_CHAR SI_GenericNoCase< SI_CHAR >::locase (SI_CHAR ch) const inline
Definition at line 2636 of file SimpleIni.h.
Referenced by SI_GenericNoCase< SI_CHAR >::operator()().
locase() [2/2]
template<class SI_CHAR > SI_CHAR SI_GenericNoCase< SI_CHAR >::locase (SI_CHAR ch) const inline
Definition at line 2636 of file SimpleIni.h.
operator()() [1/2]
template<class SI_CHAR > bool SI_GenericNoCase< SI_CHAR >::operator() (const SI_CHAR * pLeft, const SI_CHAR * pRight) const inline
Definition at line 2637 of file SimpleIni.h.
References SI_GenericNoCase< SI_CHAR >::locase().
operator()() [2/2]
template<class SI_CHAR > bool SI_GenericNoCase< SI_CHAR >::operator() (const SI_CHAR * pLeft, const SI_CHAR * pRight) const inline
Definition at line 2637 of file SimpleIni.h.
References SI_GenericNoCase< SI_CHAR >::locase().
The documentation for this struct was generated from the following file:
include/etiss/IntegratedLibrary/SimpleIni/SimpleIni.h