ETISS 0.8.0: utf16_writer Struct Reference
utf16_writer Struct Reference
Public Types
typedef uint16_t * value_type
Static Public Member Functions
static value_type low (value_type result, uint32_t ch)
static value_type high (value_type result, uint32_t ch)
static value_type any (value_type result, uint32_t ch)
Detailed Description
Definition at line 823 of file pugixml.cpp.
Member Typedef Documentation
value_type
typedef uint16_t* utf16_writer::value_type
Definition at line 825 of file pugixml.cpp.
Member Function Documentation
any()
static value_type utf16_writer::any (value_type result, uint32_t ch) inline static
Definition at line 845 of file pugixml.cpp.
References high(), and low().
high()
static value_type utf16_writer::high (value_type result, uint32_t ch) inline static
Definition at line 834 of file pugixml.cpp.
Referenced by any().
low()
static value_type utf16_writer::low (value_type result, uint32_t ch) inline static
Definition at line 827 of file pugixml.cpp.
Referenced by any().
The documentation for this struct was generated from the following file:
/home/runner/work/etiss/etiss/src/fault/xml/pugixml.cpp