ETISS 0.8.0: strconv_pcdata_impl< opt_trim, opt_eol, opt_escape > Struct Template Reference
strconv_pcdata_impl< opt_trim, opt_eol, opt_escape > Struct Template Reference
Static Public Member Functions
static char_t * parse (char_t *s)
Detailed Description
template<typename opt_trim, typename opt_eol, typename opt_escape>
struct strconv_pcdata_impl< opt_trim, opt_eol, opt_escape >
Definition at line 2000 of file pugixml.cpp.
Member Function Documentation
parse()
template<typename opt_trim , typename opt_eol , typename opt_escape > static char_t* strconv_pcdata_impl< opt_trim, opt_eol, opt_escape >::parse (char_t * s) inline static
Definition at line 2002 of file pugixml.cpp.
References ct_parse_pcdata, ct_space, gap::flush(), PUGI__IS_CHARTYPE, gap::push(), s, and strconv_escape().
The documentation for this struct was generated from the following file:
/home/runner/work/etiss/etiss/src/fault/xml/pugixml.cpp