ETISS 0.8.0: /home/runner/work/etiss/etiss/src/System.cpp File Reference
System.cpp File Reference
implements etiss/System.h. manly consists of the implementation of std::shared_ptr<ETISS_System> etiss::wrap(etiss::System * sys)
#include <stdlib.h>
#include "etiss/System.h"
Namespaces
etiss
Page Table Entry (PTE) defines the composition of Page Frame Number (PFN) and relavant flags.
Functions
static etiss_int32 system_call_iread (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint32 length)
static etiss_int32 system_call_iwrite (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
static etiss_int32 system_call_dread (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
static etiss_int32 system_call_dwrite (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
static etiss_int32 system_call_dbg_read (void *handle, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
static etiss_int32 system_call_dbg_write (void *handle, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
static void system_call_syncTime (void *handle, ETISS_CPU *cpu)
int ETISS_System_isvalid (ETISS_System *sys)
etiss::int32 etiss::dbg_print (etiss::uint32 reg)
Detailed Description
implements etiss/System.h. manly consists of the implementation of std::shared_ptr<ETISS_System> etiss::wrap(etiss::System * sys)
Copyright
Copyright 2018 Infineon Technologies AG
This file is part of ETISS tool, see https://github.com/tum-ei-eda/etiss.
The initial version of this software has been created with the funding support by the German Federal
Ministry of Education and Research (BMBF) in the project EffektiV under grant 01IS13022.
Redistribution and use in source and binary forms, with or without modification, are permitted
provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and
the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions
and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse
or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
Author
Marc Greim marc..nosp@m.grei.nosp@m.m@myt.nosp@m.um.d.nosp@m.e, Chair of Electronic Design Automation, TUM
Date
November 5, 2014
Version
0.1
Definition in file System.cpp.
Function Documentation
ETISS_System_isvalid()
int ETISS_System_isvalid (ETISS_System * sys)
Definition at line 120 of file System.cpp.
References ETISS_System::dread, ETISS_System::dwrite, ETISS_System::iread, ETISS_System::iwrite, and ETISS_System::syncTime.
Referenced by etiss::CPUCore::execute().
system_call_dbg_read()
static etiss_int32 system_call_dbg_read (void * handle, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length) static
Definition at line 79 of file System.cpp.
References length().
Referenced by etiss::wrap().
system_call_dbg_write()
static etiss_int32 system_call_dbg_write (void * handle, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length) static
Definition at line 84 of file System.cpp.
References length().
Referenced by etiss::wrap().
system_call_dread()
static etiss_int32 system_call_dread (void * handle, ETISS_CPU * cpu, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length) static
Definition at line 68 of file System.cpp.
References length().
Referenced by etiss::wrap().
system_call_dwrite()
static etiss_int32 system_call_dwrite (void * handle, ETISS_CPU * cpu, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length) static
Definition at line 73 of file System.cpp.
References length().
Referenced by etiss::wrap().
system_call_iread()
static etiss_int32 system_call_iread (void * handle, ETISS_CPU * cpu, etiss_uint64 addr, etiss_uint32 length) static
Definition at line 58 of file System.cpp.
References length().
Referenced by etiss::wrap().
system_call_iwrite()
static etiss_int32 system_call_iwrite (void * handle, ETISS_CPU * cpu, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length) static
Definition at line 62 of file System.cpp.
References length().
Referenced by etiss::wrap().
system_call_syncTime()
static void system_call_syncTime (void * handle, ETISS_CPU * cpu) static
Definition at line 89 of file System.cpp.
Referenced by etiss::wrap().