ETISS 0.8.0: include/jit/clang_stdlib/tgmath.h File Reference
tgmath.h File Reference
#include <math.h>
#include <complex.h>
Macros
#define _TG_ATTRSp __attribute__((__overloadable__))
#define _TG_ATTRS __attribute__((__overloadable__, __always_inline__))
#define __tg_promote1(__x) (__typeof__(__tg_promote(__x)))
#define __tg_promote2(__x, __y)
#define __tg_promote3(__x, __y, __z)
#define acos(__x) __tg_acos(__tg_promote1((__x))(__x))
#define asin(__x) __tg_asin(__tg_promote1((__x))(__x))
#define atan(__x) __tg_atan(__tg_promote1((__x))(__x))
#define acosh(__x) __tg_acosh(__tg_promote1((__x))(__x))
#define asinh(__x) __tg_asinh(__tg_promote1((__x))(__x))
#define atanh(__x) __tg_atanh(__tg_promote1((__x))(__x))
#define cos(__x) __tg_cos(__tg_promote1((__x))(__x))
#define sin(__x) __tg_sin(__tg_promote1((__x))(__x))
#define tan(__x) __tg_tan(__tg_promote1((__x))(__x))
#define cosh(__x) __tg_cosh(__tg_promote1((__x))(__x))
#define sinh(__x) __tg_sinh(__tg_promote1((__x))(__x))
#define tanh(__x) __tg_tanh(__tg_promote1((__x))(__x))
#define exp(__x) __tg_exp(__tg_promote1((__x))(__x))
#define log(__x) __tg_log(__tg_promote1((__x))(__x))
#define pow(__x, __y)
#define sqrt(__x) __tg_sqrt(__tg_promote1((__x))(__x))
#define fabs(__x) __tg_fabs(__tg_promote1((__x))(__x))
#define atan2(__x, __y)
#define cbrt(__x) __tg_cbrt(__tg_promote1((__x))(__x))
#define ceil(__x) __tg_ceil(__tg_promote1((__x))(__x))
#define copysign(__x, __y)
#define erf(__x) __tg_erf(__tg_promote1((__x))(__x))
#define erfc(__x) __tg_erfc(__tg_promote1((__x))(__x))
#define exp2(__x) __tg_exp2(__tg_promote1((__x))(__x))
#define expm1(__x) __tg_expm1(__tg_promote1((__x))(__x))
#define fdim(__x, __y)
#define floor(__x) __tg_floor(__tg_promote1((__x))(__x))
#define fma(__x, __y, __z)
#define fmax(__x, __y)
#define fmin(__x, __y)
#define fmod(__x, __y)
#define frexp(__x, __y) __tg_frexp(__tg_promote1((__x))(__x), __y)
#define hypot(__x, __y)
#define ilogb(__x) __tg_ilogb(__tg_promote1((__x))(__x))
#define ldexp(__x, __y) __tg_ldexp(__tg_promote1((__x))(__x), __y)
#define lgamma(__x) __tg_lgamma(__tg_promote1((__x))(__x))
#define llrint(__x) __tg_llrint(__tg_promote1((__x))(__x))
#define llround(__x) __tg_llround(__tg_promote1((__x))(__x))
#define log10(__x) __tg_log10(__tg_promote1((__x))(__x))
#define log1p(__x) __tg_log1p(__tg_promote1((__x))(__x))
#define log2(__x) __tg_log2(__tg_promote1((__x))(__x))
#define logb(__x) __tg_logb(__tg_promote1((__x))(__x))
#define lrint(__x) __tg_lrint(__tg_promote1((__x))(__x))
#define lround(__x) __tg_lround(__tg_promote1((__x))(__x))
#define nearbyint(__x) __tg_nearbyint(__tg_promote1((__x))(__x))
#define nextafter(__x, __y)
#define nexttoward(__x, __y) __tg_nexttoward(__tg_promote1((__x))(__x), (__y))
#define remainder(__x, __y)
#define remquo(__x, __y, __z)
#define rint(__x) __tg_rint(__tg_promote1((__x))(__x))
#define round(__x) __tg_round(__tg_promote1((__x))(__x))
#define scalbn(__x, __y) __tg_scalbn(__tg_promote1((__x))(__x), __y)
#define scalbln(__x, __y) __tg_scalbln(__tg_promote1((__x))(__x), __y)
#define tgamma(__x) __tg_tgamma(__tg_promote1((__x))(__x))
#define trunc(__x) __tg_trunc(__tg_promote1((__x))(__x))
#define carg(__x) __tg_carg(__tg_promote1((__x))(__x))
#define cimag(__x) __tg_cimag(__tg_promote1((__x))(__x))
#define conj(__x) __tg_conj(__tg_promote1((__x))(__x))
#define cproj(__x) __tg_cproj(__tg_promote1((__x))(__x))
#define creal(__x) __tg_creal(__tg_promote1((__x))(__x))
Typedefs
typedef void _Argument_type_is_not_arithmetic
Functions
static _Argument_type_is_not_arithmetic __tg_promote (...) __attribute__((__unavailable__
static double _TG_ATTRSp __tg_promote (int)
static double _TG_ATTRSp __tg_promote (unsigned int)
static double _TG_ATTRSp __tg_promote (long)
static double _TG_ATTRSp __tg_promote (unsigned long)
static double _TG_ATTRSp __tg_promote (long long)
static double _TG_ATTRSp __tg_promote (unsigned long long)
static float _TG_ATTRSp __tg_promote (float)
static double _TG_ATTRSp __tg_promote (double)
static long double _TG_ATTRSp __tg_promote (long double)
static float _TG_ATTRS __tg_acos (float __x)
static double _TG_ATTRS __tg_acos (double __x)
static long double _TG_ATTRS __tg_acos (long double __x)
static float _Complex _TG_ATTRS __tg_acos (float _Complex __x)
static double _Complex _TG_ATTRS __tg_acos (double _Complex __x)
static long double _Complex _TG_ATTRS __tg_acos (long double _Complex __x)
static float _TG_ATTRS __tg_asin (float __x)
static double _TG_ATTRS __tg_asin (double __x)
static long double _TG_ATTRS __tg_asin (long double __x)
static float _Complex _TG_ATTRS __tg_asin (float _Complex __x)
static double _Complex _TG_ATTRS __tg_asin (double _Complex __x)
static long double _Complex _TG_ATTRS __tg_asin (long double _Complex __x)
static float _TG_ATTRS __tg_atan (float __x)
static double _TG_ATTRS __tg_atan (double __x)
static long double _TG_ATTRS __tg_atan (long double __x)
static float _Complex _TG_ATTRS __tg_atan (float _Complex __x)
static double _Complex _TG_ATTRS __tg_atan (double _Complex __x)
static long double _Complex _TG_ATTRS __tg_atan (long double _Complex __x)
static float _TG_ATTRS __tg_acosh (float __x)
static double _TG_ATTRS __tg_acosh (double __x)
static long double _TG_ATTRS __tg_acosh (long double __x)
static float _Complex _TG_ATTRS __tg_acosh (float _Complex __x)
static double _Complex _TG_ATTRS __tg_acosh (double _Complex __x)
static long double _Complex _TG_ATTRS __tg_acosh (long double _Complex __x)
static float _TG_ATTRS __tg_asinh (float __x)
static double _TG_ATTRS __tg_asinh (double __x)
static long double _TG_ATTRS __tg_asinh (long double __x)
static float _Complex _TG_ATTRS __tg_asinh (float _Complex __x)
static double _Complex _TG_ATTRS __tg_asinh (double _Complex __x)
static long double _Complex _TG_ATTRS __tg_asinh (long double _Complex __x)
static float _TG_ATTRS __tg_atanh (float __x)
static double _TG_ATTRS __tg_atanh (double __x)
static long double _TG_ATTRS __tg_atanh (long double __x)
static float _Complex _TG_ATTRS __tg_atanh (float _Complex __x)
static double _Complex _TG_ATTRS __tg_atanh (double _Complex __x)
static long double _Complex _TG_ATTRS __tg_atanh (long double _Complex __x)
static float _TG_ATTRS __tg_cos (float __x)
static double _TG_ATTRS __tg_cos (double __x)
static long double _TG_ATTRS __tg_cos (long double __x)
static float _Complex _TG_ATTRS __tg_cos (float _Complex __x)
static double _Complex _TG_ATTRS __tg_cos (double _Complex __x)
static long double _Complex _TG_ATTRS __tg_cos (long double _Complex __x)
static float _TG_ATTRS __tg_sin (float __x)
static double _TG_ATTRS __tg_sin (double __x)
static long double _TG_ATTRS __tg_sin (long double __x)
static float _Complex _TG_ATTRS __tg_sin (float _Complex __x)
static double _Complex _TG_ATTRS __tg_sin (double _Complex __x)
static long double _Complex _TG_ATTRS __tg_sin (long double _Complex __x)
static float _TG_ATTRS __tg_tan (float __x)
static double _TG_ATTRS __tg_tan (double __x)
static long double _TG_ATTRS __tg_tan (long double __x)
static float _Complex _TG_ATTRS __tg_tan (float _Complex __x)
static double _Complex _TG_ATTRS __tg_tan (double _Complex __x)
static long double _Complex _TG_ATTRS __tg_tan (long double _Complex __x)
static float _TG_ATTRS __tg_cosh (float __x)
static double _TG_ATTRS __tg_cosh (double __x)
static long double _TG_ATTRS __tg_cosh (long double __x)
static float _Complex _TG_ATTRS __tg_cosh (float _Complex __x)
static double _Complex _TG_ATTRS __tg_cosh (double _Complex __x)
static long double _Complex _TG_ATTRS __tg_cosh (long double _Complex __x)
static float _TG_ATTRS __tg_sinh (float __x)
static double _TG_ATTRS __tg_sinh (double __x)
static long double _TG_ATTRS __tg_sinh (long double __x)
static float _Complex _TG_ATTRS __tg_sinh (float _Complex __x)
static double _Complex _TG_ATTRS __tg_sinh (double _Complex __x)
static long double _Complex _TG_ATTRS __tg_sinh (long double _Complex __x)
static float _TG_ATTRS __tg_tanh (float __x)
static double _TG_ATTRS __tg_tanh (double __x)
static long double _TG_ATTRS __tg_tanh (long double __x)
static float _Complex _TG_ATTRS __tg_tanh (float _Complex __x)
static double _Complex _TG_ATTRS __tg_tanh (double _Complex __x)
static long double _Complex _TG_ATTRS __tg_tanh (long double _Complex __x)
static float _TG_ATTRS __tg_exp (float __x)
static double _TG_ATTRS __tg_exp (double __x)
static long double _TG_ATTRS __tg_exp (long double __x)
static float _Complex _TG_ATTRS __tg_exp (float _Complex __x)
static double _Complex _TG_ATTRS __tg_exp (double _Complex __x)
static long double _Complex _TG_ATTRS __tg_exp (long double _Complex __x)
static float _TG_ATTRS __tg_log (float __x)
static double _TG_ATTRS __tg_log (double __x)
static long double _TG_ATTRS __tg_log (long double __x)
static float _Complex _TG_ATTRS __tg_log (float _Complex __x)
static double _Complex _TG_ATTRS __tg_log (double _Complex __x)
static long double _Complex _TG_ATTRS __tg_log (long double _Complex __x)
static float _TG_ATTRS __tg_pow (float __x, float __y)
static double _TG_ATTRS __tg_pow (double __x, double __y)
static long double _TG_ATTRS __tg_pow (long double __x, long double __y)
static float _Complex _TG_ATTRS __tg_pow (float _Complex __x, float _Complex __y)
static double _Complex _TG_ATTRS __tg_pow (double _Complex __x, double _Complex __y)
static long double _Complex _TG_ATTRS __tg_pow (long double _Complex __x, long double _Complex __y)
static float _TG_ATTRS __tg_sqrt (float __x)
static double _TG_ATTRS __tg_sqrt (double __x)
static long double _TG_ATTRS __tg_sqrt (long double __x)
static float _Complex _TG_ATTRS __tg_sqrt (float _Complex __x)
static double _Complex _TG_ATTRS __tg_sqrt (double _Complex __x)
static long double _Complex _TG_ATTRS __tg_sqrt (long double _Complex __x)
static float _TG_ATTRS __tg_fabs (float __x)
static double _TG_ATTRS __tg_fabs (double __x)
static long double _TG_ATTRS __tg_fabs (long double __x)
static float _TG_ATTRS __tg_fabs (float _Complex __x)
static double _TG_ATTRS __tg_fabs (double _Complex __x)
static long double _TG_ATTRS __tg_fabs (long double _Complex __x)
static float _TG_ATTRS __tg_atan2 (float __x, float __y)
static double _TG_ATTRS __tg_atan2 (double __x, double __y)
static long double _TG_ATTRS __tg_atan2 (long double __x, long double __y)
static float _TG_ATTRS __tg_cbrt (float __x)
static double _TG_ATTRS __tg_cbrt (double __x)
static long double _TG_ATTRS __tg_cbrt (long double __x)
static float _TG_ATTRS __tg_ceil (float __x)
static double _TG_ATTRS __tg_ceil (double __x)
static long double _TG_ATTRS __tg_ceil (long double __x)
static float _TG_ATTRS __tg_copysign (float __x, float __y)
static double _TG_ATTRS __tg_copysign (double __x, double __y)
static long double _TG_ATTRS __tg_copysign (long double __x, long double __y)
static float _TG_ATTRS __tg_erf (float __x)
static double _TG_ATTRS __tg_erf (double __x)
static long double _TG_ATTRS __tg_erf (long double __x)
static float _TG_ATTRS __tg_erfc (float __x)
static double _TG_ATTRS __tg_erfc (double __x)
static long double _TG_ATTRS __tg_erfc (long double __x)
static float _TG_ATTRS __tg_exp2 (float __x)
static double _TG_ATTRS __tg_exp2 (double __x)
static long double _TG_ATTRS __tg_exp2 (long double __x)
static float _TG_ATTRS __tg_expm1 (float __x)
static double _TG_ATTRS __tg_expm1 (double __x)
static long double _TG_ATTRS __tg_expm1 (long double __x)
static float _TG_ATTRS __tg_fdim (float __x, float __y)
static double _TG_ATTRS __tg_fdim (double __x, double __y)
static long double _TG_ATTRS __tg_fdim (long double __x, long double __y)
static float _TG_ATTRS __tg_floor (float __x)
static double _TG_ATTRS __tg_floor (double __x)
static long double _TG_ATTRS __tg_floor (long double __x)
static float _TG_ATTRS __tg_fma (float __x, float __y, float __z)
static double _TG_ATTRS __tg_fma (double __x, double __y, double __z)
static long double _TG_ATTRS __tg_fma (long double __x, long double __y, long double __z)
static float _TG_ATTRS __tg_fmax (float __x, float __y)
static double _TG_ATTRS __tg_fmax (double __x, double __y)
static long double _TG_ATTRS __tg_fmax (long double __x, long double __y)
static float _TG_ATTRS __tg_fmin (float __x, float __y)
static double _TG_ATTRS __tg_fmin (double __x, double __y)
static long double _TG_ATTRS __tg_fmin (long double __x, long double __y)
static float _TG_ATTRS __tg_fmod (float __x, float __y)
static double _TG_ATTRS __tg_fmod (double __x, double __y)
static long double _TG_ATTRS __tg_fmod (long double __x, long double __y)
static float _TG_ATTRS __tg_frexp (float __x, int *__y)
static double _TG_ATTRS __tg_frexp (double __x, int *__y)
static long double _TG_ATTRS __tg_frexp (long double __x, int *__y)
static float _TG_ATTRS __tg_hypot (float __x, float __y)
static double _TG_ATTRS __tg_hypot (double __x, double __y)
static long double _TG_ATTRS __tg_hypot (long double __x, long double __y)
static int _TG_ATTRS __tg_ilogb (float __x)
static int _TG_ATTRS __tg_ilogb (double __x)
static int _TG_ATTRS __tg_ilogb (long double __x)
static float _TG_ATTRS __tg_ldexp (float __x, int __y)
static double _TG_ATTRS __tg_ldexp (double __x, int __y)
static long double _TG_ATTRS __tg_ldexp (long double __x, int __y)
static float _TG_ATTRS __tg_lgamma (float __x)
static double _TG_ATTRS __tg_lgamma (double __x)
static long double _TG_ATTRS __tg_lgamma (long double __x)
static long long _TG_ATTRS __tg_llrint (float __x)
static long long _TG_ATTRS __tg_llrint (double __x)
static long long _TG_ATTRS __tg_llrint (long double __x)
static long long _TG_ATTRS __tg_llround (float __x)
static long long _TG_ATTRS __tg_llround (double __x)
static long long _TG_ATTRS __tg_llround (long double __x)
static float _TG_ATTRS __tg_log10 (float __x)
static double _TG_ATTRS __tg_log10 (double __x)
static long double _TG_ATTRS __tg_log10 (long double __x)
static float _TG_ATTRS __tg_log1p (float __x)
static double _TG_ATTRS __tg_log1p (double __x)
static long double _TG_ATTRS __tg_log1p (long double __x)
static float _TG_ATTRS __tg_log2 (float __x)
static double _TG_ATTRS __tg_log2 (double __x)
static long double _TG_ATTRS __tg_log2 (long double __x)
static float _TG_ATTRS __tg_logb (float __x)
static double _TG_ATTRS __tg_logb (double __x)
static long double _TG_ATTRS __tg_logb (long double __x)
static long _TG_ATTRS __tg_lrint (float __x)
static long _TG_ATTRS __tg_lrint (double __x)
static long _TG_ATTRS __tg_lrint (long double __x)
static long _TG_ATTRS __tg_lround (float __x)
static long _TG_ATTRS __tg_lround (double __x)
static long _TG_ATTRS __tg_lround (long double __x)
static float _TG_ATTRS __tg_nearbyint (float __x)
static double _TG_ATTRS __tg_nearbyint (double __x)
static long double _TG_ATTRS __tg_nearbyint (long double __x)
static float _TG_ATTRS __tg_nextafter (float __x, float __y)
static double _TG_ATTRS __tg_nextafter (double __x, double __y)
static long double _TG_ATTRS __tg_nextafter (long double __x, long double __y)
static float _TG_ATTRS __tg_nexttoward (float __x, long double __y)
static double _TG_ATTRS __tg_nexttoward (double __x, long double __y)
static long double _TG_ATTRS __tg_nexttoward (long double __x, long double __y)
static float _TG_ATTRS __tg_remainder (float __x, float __y)
static double _TG_ATTRS __tg_remainder (double __x, double __y)
static long double _TG_ATTRS __tg_remainder (long double __x, long double __y)
static float _TG_ATTRS __tg_remquo (float __x, float __y, int *__z)
static double _TG_ATTRS __tg_remquo (double __x, double __y, int *__z)
static long double _TG_ATTRS __tg_remquo (long double __x, long double __y, int *__z)
static float _TG_ATTRS __tg_rint (float __x)
static double _TG_ATTRS __tg_rint (double __x)
static long double _TG_ATTRS __tg_rint (long double __x)
static float _TG_ATTRS __tg_round (float __x)
static double _TG_ATTRS __tg_round (double __x)
static long double _TG_ATTRS __tg_round (long double __x)
static float _TG_ATTRS __tg_scalbn (float __x, int __y)
static double _TG_ATTRS __tg_scalbn (double __x, int __y)
static long double _TG_ATTRS __tg_scalbn (long double __x, int __y)
static float _TG_ATTRS __tg_scalbln (float __x, long __y)
static double _TG_ATTRS __tg_scalbln (double __x, long __y)
static long double _TG_ATTRS __tg_scalbln (long double __x, long __y)
static float _TG_ATTRS __tg_tgamma (float __x)
static double _TG_ATTRS __tg_tgamma (double __x)
static long double _TG_ATTRS __tg_tgamma (long double __x)
static float _TG_ATTRS __tg_trunc (float __x)
static double _TG_ATTRS __tg_trunc (double __x)
static long double _TG_ATTRS __tg_trunc (long double __x)
static float _TG_ATTRS __tg_carg (float __x)
static double _TG_ATTRS __tg_carg (double __x)
static long double _TG_ATTRS __tg_carg (long double __x)
static float _TG_ATTRS __tg_carg (float _Complex __x)
static double _TG_ATTRS __tg_carg (double _Complex __x)
static long double _TG_ATTRS __tg_carg (long double _Complex __x)
static float _TG_ATTRS __tg_cimag (float __x)
static double _TG_ATTRS __tg_cimag (double __x)
static long double _TG_ATTRS __tg_cimag (long double __x)
static float _TG_ATTRS __tg_cimag (float _Complex __x)
static double _TG_ATTRS __tg_cimag (double _Complex __x)
static long double _TG_ATTRS __tg_cimag (long double _Complex __x)
static float _Complex _TG_ATTRS __tg_conj (float __x)
static double _Complex _TG_ATTRS __tg_conj (double __x)
static long double _Complex _TG_ATTRS __tg_conj (long double __x)
static float _Complex _TG_ATTRS __tg_conj (float _Complex __x)
static double _Complex _TG_ATTRS __tg_conj (double _Complex __x)
static long double _Complex _TG_ATTRS __tg_conj (long double _Complex __x)
static float _Complex _TG_ATTRS __tg_cproj (float __x)
static double _Complex _TG_ATTRS __tg_cproj (double __x)
static long double _Complex _TG_ATTRS __tg_cproj (long double __x)
static float _Complex _TG_ATTRS __tg_cproj (float _Complex __x)
static double _Complex _TG_ATTRS __tg_cproj (double _Complex __x)
static long double _Complex _TG_ATTRS __tg_cproj (long double _Complex __x)
static float _TG_ATTRS __tg_creal (float __x)
static double _TG_ATTRS __tg_creal (double __x)
static long double _TG_ATTRS __tg_creal (long double __x)
static float _TG_ATTRS __tg_creal (float _Complex __x)
static double _TG_ATTRS __tg_creal (double _Complex __x)
static long double _TG_ATTRS __tg_creal (long double _Complex __x)
Variables
static _Argument_type_is_not_arithmetic __overloadable__
Macro Definition Documentation
__tg_promote1
#define __tg_promote1 (__x) (__typeof__(__tg_promote(__x)))
Definition at line 49 of file tgmath.h.
__tg_promote2
#define __tg_promote2 (__x, __y)
Value:
                                                 (__typeof__(__tg_promote(__x) + \
                                                 __tg_promote(__y)))
Definition at line 50 of file tgmath.h.
__tg_promote3
#define __tg_promote3 (__x, __y, __z)
Value:
                                                 (__typeof__(__tg_promote(__x) + \
                                                 __tg_promote(__y) + \
                                                 __tg_promote(__z)))
Definition at line 52 of file tgmath.h.
_TG_ATTRS
#define _TG_ATTRS __attribute__((__overloadable__, __always_inline__))
Definition at line 29 of file tgmath.h.
_TG_ATTRSp
#define _TG_ATTRSp __attribute__((__overloadable__))
Definition at line 28 of file tgmath.h.
acos
#define acos (__x) __tg_acos(__tg_promote1((__x))(__x))
Definition at line 83 of file tgmath.h.
acosh
#define acosh (__x) __tg_acosh(__tg_promote1((__x))(__x))
Definition at line 170 of file tgmath.h.
asin
#define asin (__x) __tg_asin(__tg_promote1((__x))(__x))
Definition at line 112 of file tgmath.h.
asinh
#define asinh (__x) __tg_asinh(__tg_promote1((__x))(__x))
Definition at line 199 of file tgmath.h.
atan
#define atan (__x) __tg_atan(__tg_promote1((__x))(__x))
Definition at line 141 of file tgmath.h.
atan2
#define atan2 (__x, __y)
Value:
                                   __tg_atan2(__tg_promote2((__x), (__y))(__x), \
                                   __tg_promote2((__x), (__y))(__y))
Definition at line 566 of file tgmath.h.
atanh
#define atanh (__x) __tg_atanh(__tg_promote1((__x))(__x))
Definition at line 228 of file tgmath.h.
carg
#define carg (__x) __tg_carg(__tg_promote1((__x))(__x))
Definition at line 1245 of file tgmath.h.
cbrt
#define cbrt (__x) __tg_cbrt(__tg_promote1((__x))(__x))
Definition at line 584 of file tgmath.h.
ceil
#define ceil (__x) __tg_ceil(__tg_promote1((__x))(__x))
Definition at line 601 of file tgmath.h.
cimag
#define cimag (__x) __tg_cimag(__tg_promote1((__x))(__x))
Definition at line 1274 of file tgmath.h.
conj
#define conj (__x) __tg_conj(__tg_promote1((__x))(__x))
Definition at line 1303 of file tgmath.h.
copysign
#define copysign (__x, __y)
Value:
                                         __tg_copysign(__tg_promote2((__x), (__y))(__x), \
                                         __tg_promote2((__x), (__y))(__y))
Definition at line 618 of file tgmath.h.
cos
#define cos (__x) __tg_cos(__tg_promote1((__x))(__x))
Definition at line 257 of file tgmath.h.
cosh
#define cosh (__x) __tg_cosh(__tg_promote1((__x))(__x))
Definition at line 344 of file tgmath.h.
cproj
#define cproj (__x) __tg_cproj(__tg_promote1((__x))(__x))
Definition at line 1332 of file tgmath.h.
creal
#define creal (__x) __tg_creal(__tg_promote1((__x))(__x))
Definition at line 1361 of file tgmath.h.
erf
#define erf (__x) __tg_erf(__tg_promote1((__x))(__x))
Definition at line 636 of file tgmath.h.
erfc
#define erfc (__x) __tg_erfc(__tg_promote1((__x))(__x))
Definition at line 653 of file tgmath.h.
exp
#define exp (__x) __tg_exp(__tg_promote1((__x))(__x))
Definition at line 431 of file tgmath.h.
exp2
#define exp2 (__x) __tg_exp2(__tg_promote1((__x))(__x))
Definition at line 670 of file tgmath.h.
expm1
#define expm1 (__x) __tg_expm1(__tg_promote1((__x))(__x))
Definition at line 687 of file tgmath.h.
fabs
#define fabs (__x) __tg_fabs(__tg_promote1((__x))(__x))
Definition at line 549 of file tgmath.h.
fdim
#define fdim (__x, __y)
Value:
                                 __tg_fdim(__tg_promote2((__x), (__y))(__x), \
                                 __tg_promote2((__x), (__y))(__y))
Definition at line 704 of file tgmath.h.
floor
#define floor (__x) __tg_floor(__tg_promote1((__x))(__x))
Definition at line 722 of file tgmath.h.
fma
#define fma (__x, __y, __z)
Value:
        __tg_fma(__tg_promote3((__x), (__y), (__z))(__x), \
                 __tg_promote3((__x), (__y), (__z))(__y), \
                 __tg_promote3((__x), (__y), (__z))(__z))
Definition at line 742 of file tgmath.h.
fmax
#define fmax (__x, __y)
Value:
                                 __tg_fmax(__tg_promote2((__x), (__y))(__x), \
                                 __tg_promote2((__x), (__y))(__y))
Definition at line 762 of file tgmath.h.
fmin
#define fmin (__x, __y)
Value:
                                 __tg_fmin(__tg_promote2((__x), (__y))(__x), \
                                 __tg_promote2((__x), (__y))(__y))
Definition at line 780 of file tgmath.h.
fmod
#define fmod (__x, __y)
Value:
                                 __tg_fmod(__tg_promote2((__x), (__y))(__x), \
                                 __tg_promote2((__x), (__y))(__y))
Definition at line 798 of file tgmath.h.
frexp
#define frexp (__x, __y) __tg_frexp(__tg_promote1((__x))(__x), __y)
Definition at line 816 of file tgmath.h.
hypot
#define hypot (__x, __y)
Value:
                                   __tg_hypot(__tg_promote2((__x), (__y))(__x), \
                                   __tg_promote2((__x), (__y))(__y))
Definition at line 833 of file tgmath.h.
ilogb
#define ilogb (__x) __tg_ilogb(__tg_promote1((__x))(__x))
Definition at line 851 of file tgmath.h.
ldexp
#define ldexp (__x, __y) __tg_ldexp(__tg_promote1((__x))(__x), __y)
Definition at line 868 of file tgmath.h.
lgamma
#define lgamma (__x) __tg_lgamma(__tg_promote1((__x))(__x))
Definition at line 885 of file tgmath.h.
llrint
#define llrint (__x) __tg_llrint(__tg_promote1((__x))(__x))
Definition at line 902 of file tgmath.h.
llround
#define llround (__x) __tg_llround(__tg_promote1((__x))(__x))
Definition at line 919 of file tgmath.h.
log
#define log (__x) __tg_log(__tg_promote1((__x))(__x))
Definition at line 460 of file tgmath.h.
log10
#define log10 (__x) __tg_log10(__tg_promote1((__x))(__x))
Definition at line 936 of file tgmath.h.
log1p
#define log1p (__x) __tg_log1p(__tg_promote1((__x))(__x))
Definition at line 953 of file tgmath.h.
log2
#define log2 (__x) __tg_log2(__tg_promote1((__x))(__x))
Definition at line 970 of file tgmath.h.
logb
#define logb (__x) __tg_logb(__tg_promote1((__x))(__x))
Definition at line 987 of file tgmath.h.
lrint
#define lrint (__x) __tg_lrint(__tg_promote1((__x))(__x))
Definition at line 1004 of file tgmath.h.
lround
#define lround (__x) __tg_lround(__tg_promote1((__x))(__x))
Definition at line 1021 of file tgmath.h.
nearbyint
#define nearbyint (__x) __tg_nearbyint(__tg_promote1((__x))(__x))
Definition at line 1038 of file tgmath.h.
nextafter
#define nextafter (__x, __y)
Value:
                                           __tg_nextafter(__tg_promote2((__x), (__y))(__x), \
                                           __tg_promote2((__x), (__y))(__y))
Definition at line 1055 of file tgmath.h.
nexttoward
#define nexttoward (__x, __y) __tg_nexttoward(__tg_promote1((__x))(__x), (__y))
Definition at line 1073 of file tgmath.h.
pow
#define pow (__x, __y)
Value:
                               __tg_pow(__tg_promote2((__x), (__y))(__x), \
                               __tg_promote2((__x), (__y))(__y))
Definition at line 490 of file tgmath.h.
remainder
#define remainder (__x, __y)
Value:
                                           __tg_remainder(__tg_promote2((__x), (__y))(__x), \
                                           __tg_promote2((__x), (__y))(__y))
Definition at line 1090 of file tgmath.h.
remquo
#define remquo (__x, __y, __z)
Value:
        __tg_remquo(__tg_promote2((__x), (__y))(__x), \
                    __tg_promote2((__x), (__y))(__y), \
                    (__z))
Definition at line 1111 of file tgmath.h.
rint
#define rint (__x) __tg_rint(__tg_promote1((__x))(__x))
Definition at line 1131 of file tgmath.h.
round
#define round (__x) __tg_round(__tg_promote1((__x))(__x))
Definition at line 1148 of file tgmath.h.
scalbln
#define scalbln (__x, __y) __tg_scalbln(__tg_promote1((__x))(__x), __y)
Definition at line 1182 of file tgmath.h.
scalbn
#define scalbn (__x, __y) __tg_scalbn(__tg_promote1((__x))(__x), __y)
Definition at line 1165 of file tgmath.h.
sin
#define sin (__x) __tg_sin(__tg_promote1((__x))(__x))
Definition at line 286 of file tgmath.h.
sinh
#define sinh (__x) __tg_sinh(__tg_promote1((__x))(__x))
Definition at line 373 of file tgmath.h.
sqrt
#define sqrt (__x) __tg_sqrt(__tg_promote1((__x))(__x))
Definition at line 520 of file tgmath.h.
tan
#define tan (__x) __tg_tan(__tg_promote1((__x))(__x))
Definition at line 315 of file tgmath.h.
tanh
#define tanh (__x) __tg_tanh(__tg_promote1((__x))(__x))
Definition at line 402 of file tgmath.h.
tgamma
#define tgamma (__x) __tg_tgamma(__tg_promote1((__x))(__x))
Definition at line 1199 of file tgmath.h.
trunc
#define trunc (__x) __tg_trunc(__tg_promote1((__x))(__x))
Definition at line 1216 of file tgmath.h.
Typedef Documentation
_Argument_type_is_not_arithmetic
typedef void _Argument_type_is_not_arithmetic
Definition at line 33 of file tgmath.h.
Function Documentation
__tg_acos() [1/6]
static double _TG_ATTRS __tg_acos (double __x) static
Definition at line 64 of file tgmath.h.
References __x, and acos.
__tg_acos() [2/6]
static double _Complex _TG_ATTRS __tg_acos (double _Complex __x) static
Definition at line 76 of file tgmath.h.
References __x.
__tg_acos() [3/6]
static float _TG_ATTRS __tg_acos (float __x) static
Definition at line 60 of file tgmath.h.
References __x, and acosf().
__tg_acos() [4/6]
static float _Complex _TG_ATTRS __tg_acos (float _Complex __x) static
Definition at line 72 of file tgmath.h.
References __x.
__tg_acos() [5/6]
static long double _TG_ATTRS __tg_acos (long double __x) static
Definition at line 68 of file tgmath.h.
References __x.
__tg_acos() [6/6]
static long double _Complex _TG_ATTRS __tg_acos (long double _Complex __x) static
Definition at line 80 of file tgmath.h.
References __x.
__tg_acosh() [1/6]
static double _TG_ATTRS __tg_acosh (double __x) static
Definition at line 151 of file tgmath.h.
References __x, and acosh.
__tg_acosh() [2/6]
static double _Complex _TG_ATTRS __tg_acosh (double _Complex __x) static
Definition at line 163 of file tgmath.h.
References __x.
__tg_acosh() [3/6]
static float _TG_ATTRS __tg_acosh (float __x) static
Definition at line 147 of file tgmath.h.
References __x, and acoshf().
__tg_acosh() [4/6]
static float _Complex _TG_ATTRS __tg_acosh (float _Complex __x) static
Definition at line 159 of file tgmath.h.
References __x.
__tg_acosh() [5/6]
static long double _TG_ATTRS __tg_acosh (long double __x) static
Definition at line 155 of file tgmath.h.
References __x.
__tg_acosh() [6/6]
static long double _Complex _TG_ATTRS __tg_acosh (long double _Complex __x) static
Definition at line 167 of file tgmath.h.
References __x.
__tg_asin() [1/6]
static double _TG_ATTRS __tg_asin (double __x) static
Definition at line 93 of file tgmath.h.
References __x, and asin.
__tg_asin() [2/6]
static double _Complex _TG_ATTRS __tg_asin (double _Complex __x) static
Definition at line 105 of file tgmath.h.
References __x.
__tg_asin() [3/6]
static float _TG_ATTRS __tg_asin (float __x) static
Definition at line 89 of file tgmath.h.
References __x, and asinf().
__tg_asin() [4/6]
static float _Complex _TG_ATTRS __tg_asin (float _Complex __x) static
Definition at line 101 of file tgmath.h.
References __x.
__tg_asin() [5/6]
static long double _TG_ATTRS __tg_asin (long double __x) static
Definition at line 97 of file tgmath.h.
References __x.
__tg_asin() [6/6]
static long double _Complex _TG_ATTRS __tg_asin (long double _Complex __x) static
Definition at line 109 of file tgmath.h.
References __x.
__tg_asinh() [1/6]
static double _TG_ATTRS __tg_asinh (double __x) static
Definition at line 180 of file tgmath.h.
References __x, and asinh.
__tg_asinh() [2/6]
static double _Complex _TG_ATTRS __tg_asinh (double _Complex __x) static
Definition at line 192 of file tgmath.h.
References __x.
__tg_asinh() [3/6]
static float _TG_ATTRS __tg_asinh (float __x) static
Definition at line 176 of file tgmath.h.
References __x, and asinhf().
__tg_asinh() [4/6]
static float _Complex _TG_ATTRS __tg_asinh (float _Complex __x) static
Definition at line 188 of file tgmath.h.
References __x.
__tg_asinh() [5/6]
static long double _TG_ATTRS __tg_asinh (long double __x) static
Definition at line 184 of file tgmath.h.
References __x.
__tg_asinh() [6/6]
static long double _Complex _TG_ATTRS __tg_asinh (long double _Complex __x) static
Definition at line 196 of file tgmath.h.
References __x.
__tg_atan() [1/6]
static double _TG_ATTRS __tg_atan (double __x) static
Definition at line 122 of file tgmath.h.
References __x, and atan.
__tg_atan() [2/6]
static double _Complex _TG_ATTRS __tg_atan (double _Complex __x) static
Definition at line 134 of file tgmath.h.
References __x.
__tg_atan() [3/6]
static float _TG_ATTRS __tg_atan (float __x) static
Definition at line 118 of file tgmath.h.
References __x, and atanf().
__tg_atan() [4/6]
static float _Complex _TG_ATTRS __tg_atan (float _Complex __x) static
Definition at line 130 of file tgmath.h.
References __x.
__tg_atan() [5/6]
static long double _TG_ATTRS __tg_atan (long double __x) static
Definition at line 126 of file tgmath.h.
References __x.
__tg_atan() [6/6]
static long double _Complex _TG_ATTRS __tg_atan (long double _Complex __x) static
Definition at line 138 of file tgmath.h.
References __x.
__tg_atan2() [1/3]
static double _TG_ATTRS __tg_atan2 (double __x, double __y) static
Definition at line 559 of file tgmath.h.
References __x, __y, and atan2.
__tg_atan2() [2/3]
static float _TG_ATTRS __tg_atan2 (float __x, float __y) static
Definition at line 555 of file tgmath.h.
References __x, __y, and atan2f().
__tg_atan2() [3/3]
static long double _TG_ATTRS __tg_atan2 (long double __x, long double __y) static
Definition at line 563 of file tgmath.h.
References __x, and __y.
__tg_atanh() [1/6]
static double _TG_ATTRS __tg_atanh (double __x) static
Definition at line 209 of file tgmath.h.
References __x, and atanh.
__tg_atanh() [2/6]
static double _Complex _TG_ATTRS __tg_atanh (double _Complex __x) static
Definition at line 221 of file tgmath.h.
References __x.
__tg_atanh() [3/6]
static float _TG_ATTRS __tg_atanh (float __x) static
Definition at line 205 of file tgmath.h.
References __x, and atanhf().
__tg_atanh() [4/6]
static float _Complex _TG_ATTRS __tg_atanh (float _Complex __x) static
Definition at line 217 of file tgmath.h.
References __x.
__tg_atanh() [5/6]
static long double _TG_ATTRS __tg_atanh (long double __x) static
Definition at line 213 of file tgmath.h.
References __x.
__tg_atanh() [6/6]
static long double _Complex _TG_ATTRS __tg_atanh (long double _Complex __x) static
Definition at line 225 of file tgmath.h.
References __x.
__tg_carg() [1/6]
static double _TG_ATTRS __tg_carg (double __x) static
Definition at line 1226 of file tgmath.h.
References __x, and atan2.
__tg_carg() [2/6]
static double _TG_ATTRS __tg_carg (double _Complex __x) static
Definition at line 1238 of file tgmath.h.
References __x, and carg.
__tg_carg() [3/6]
static float _TG_ATTRS __tg_carg (float __x) static
Definition at line 1222 of file tgmath.h.
References __x, and atan2f().
__tg_carg() [4/6]
static float _TG_ATTRS __tg_carg (float _Complex __x) static
Definition at line 1234 of file tgmath.h.
References __x.
__tg_carg() [5/6]
static long double _TG_ATTRS __tg_carg (long double __x) static
Definition at line 1230 of file tgmath.h.
References __x.
__tg_carg() [6/6]
static long double _TG_ATTRS __tg_carg (long double _Complex __x) static
Definition at line 1242 of file tgmath.h.
References __x.
__tg_cbrt() [1/3]
static double _TG_ATTRS __tg_cbrt (double __x) static
Definition at line 577 of file tgmath.h.
References __x, and cbrt.
__tg_cbrt() [2/3]
static float _TG_ATTRS __tg_cbrt (float __x) static
Definition at line 573 of file tgmath.h.
References __x, and cbrtf().
__tg_cbrt() [3/3]
static long double _TG_ATTRS __tg_cbrt (long double __x) static
Definition at line 581 of file tgmath.h.
References __x.
__tg_ceil() [1/3]
static double _TG_ATTRS __tg_ceil (double __x) static
Definition at line 594 of file tgmath.h.
References __x, and ceil.
__tg_ceil() [2/3]
static float _TG_ATTRS __tg_ceil (float __x) static
Definition at line 590 of file tgmath.h.
References __x, and ceilf().
__tg_ceil() [3/3]
static long double _TG_ATTRS __tg_ceil (long double __x) static
Definition at line 598 of file tgmath.h.
References __x.
__tg_cimag() [1/6]
static double _TG_ATTRS __tg_cimag (double __x) static
Definition at line 1255 of file tgmath.h.
__tg_cimag() [2/6]
static double _TG_ATTRS __tg_cimag (double _Complex __x) static
Definition at line 1267 of file tgmath.h.
References __x, and cimag.
__tg_cimag() [3/6]
static float _TG_ATTRS __tg_cimag (float __x) static
Definition at line 1251 of file tgmath.h.
__tg_cimag() [4/6]
static float _TG_ATTRS __tg_cimag (float _Complex __x) static
Definition at line 1263 of file tgmath.h.
References __x.
__tg_cimag() [5/6]
static long double _TG_ATTRS __tg_cimag (long double __x) static
Definition at line 1259 of file tgmath.h.
__tg_cimag() [6/6]
static long double _TG_ATTRS __tg_cimag (long double _Complex __x) static
Definition at line 1271 of file tgmath.h.
References __x.
__tg_conj() [1/6]
static double _Complex _TG_ATTRS __tg_conj (double __x) static
Definition at line 1284 of file tgmath.h.
References __x.
__tg_conj() [2/6]
static double _Complex _TG_ATTRS __tg_conj (double _Complex __x) static
Definition at line 1296 of file tgmath.h.
References __x, and conj.
__tg_conj() [3/6]
static float _Complex _TG_ATTRS __tg_conj (float __x) static
Definition at line 1280 of file tgmath.h.
References __x.
__tg_conj() [4/6]
static float _Complex _TG_ATTRS __tg_conj (float _Complex __x) static
Definition at line 1292 of file tgmath.h.
References __x.
__tg_conj() [5/6]
static long double _Complex _TG_ATTRS __tg_conj (long double __x) static
Definition at line 1288 of file tgmath.h.
References __x.
__tg_conj() [6/6]
static long double _Complex _TG_ATTRS __tg_conj (long double _Complex __x) static
Definition at line 1300 of file tgmath.h.
References __x.
__tg_copysign() [1/3]
static double _TG_ATTRS __tg_copysign (double __x, double __y) static
Definition at line 611 of file tgmath.h.
References __x, __y, and copysign.
__tg_copysign() [2/3]
static float _TG_ATTRS __tg_copysign (float __x, float __y) static
Definition at line 607 of file tgmath.h.
References __x, __y, and copysignf().
__tg_copysign() [3/3]
static long double _TG_ATTRS __tg_copysign (long double __x, long double __y) static
Definition at line 615 of file tgmath.h.
References __x, and __y.
__tg_cos() [1/6]
static double _TG_ATTRS __tg_cos (double __x) static
Definition at line 238 of file tgmath.h.
References __x, and cos.
__tg_cos() [2/6]
static double _Complex _TG_ATTRS __tg_cos (double _Complex __x) static
Definition at line 250 of file tgmath.h.
References __x.
__tg_cos() [3/6]
static float _TG_ATTRS __tg_cos (float __x) static
Definition at line 234 of file tgmath.h.
References __x, and cosf().
__tg_cos() [4/6]
static float _Complex _TG_ATTRS __tg_cos (float _Complex __x) static
Definition at line 246 of file tgmath.h.
References __x.
__tg_cos() [5/6]
static long double _TG_ATTRS __tg_cos (long double __x) static
Definition at line 242 of file tgmath.h.
References __x.
__tg_cos() [6/6]
static long double _Complex _TG_ATTRS __tg_cos (long double _Complex __x) static
Definition at line 254 of file tgmath.h.
References __x.
__tg_cosh() [1/6]
static double _TG_ATTRS __tg_cosh (double __x) static
Definition at line 325 of file tgmath.h.
References __x, and cosh.
__tg_cosh() [2/6]
static double _Complex _TG_ATTRS __tg_cosh (double _Complex __x) static
Definition at line 337 of file tgmath.h.
References __x.
__tg_cosh() [3/6]
static float _TG_ATTRS __tg_cosh (float __x) static
Definition at line 321 of file tgmath.h.
References __x, and coshf().
__tg_cosh() [4/6]
static float _Complex _TG_ATTRS __tg_cosh (float _Complex __x) static
Definition at line 333 of file tgmath.h.
References __x.
__tg_cosh() [5/6]
static long double _TG_ATTRS __tg_cosh (long double __x) static
Definition at line 329 of file tgmath.h.
References __x.
__tg_cosh() [6/6]
static long double _Complex _TG_ATTRS __tg_cosh (long double _Complex __x) static
Definition at line 341 of file tgmath.h.
References __x.
__tg_cproj() [1/6]
static double _Complex _TG_ATTRS __tg_cproj (double __x) static
Definition at line 1313 of file tgmath.h.
References __x, and cproj.
__tg_cproj() [2/6]
static double _Complex _TG_ATTRS __tg_cproj (double _Complex __x) static
Definition at line 1325 of file tgmath.h.
References __x, and cproj.
__tg_cproj() [3/6]
static float _Complex _TG_ATTRS __tg_cproj (float __x) static
Definition at line 1309 of file tgmath.h.
References __x.
__tg_cproj() [4/6]
static float _Complex _TG_ATTRS __tg_cproj (float _Complex __x) static
Definition at line 1321 of file tgmath.h.
References __x.
__tg_cproj() [5/6]
static long double _Complex _TG_ATTRS __tg_cproj (long double __x) static
Definition at line 1317 of file tgmath.h.
References __x.
__tg_cproj() [6/6]
static long double _Complex _TG_ATTRS __tg_cproj (long double _Complex __x) static
Definition at line 1329 of file tgmath.h.
References __x.
__tg_creal() [1/6]
static double _TG_ATTRS __tg_creal (double __x) static
Definition at line 1342 of file tgmath.h.
References __x.
__tg_creal() [2/6]
static double _TG_ATTRS __tg_creal (double _Complex __x) static
Definition at line 1354 of file tgmath.h.
References __x, and creal.
__tg_creal() [3/6]
static float _TG_ATTRS __tg_creal (float __x) static
Definition at line 1338 of file tgmath.h.
References __x.
__tg_creal() [4/6]
static float _TG_ATTRS __tg_creal (float _Complex __x) static
Definition at line 1350 of file tgmath.h.
References __x.
__tg_creal() [5/6]
static long double _TG_ATTRS __tg_creal (long double __x) static
Definition at line 1346 of file tgmath.h.
References __x.
__tg_creal() [6/6]
static long double _TG_ATTRS __tg_creal (long double _Complex __x) static
Definition at line 1358 of file tgmath.h.
References __x.
__tg_erf() [1/3]
static double _TG_ATTRS __tg_erf (double __x) static
Definition at line 629 of file tgmath.h.
References __x, and erf.
__tg_erf() [2/3]
static float _TG_ATTRS __tg_erf (float __x) static
Definition at line 625 of file tgmath.h.
References __x, and erff().
__tg_erf() [3/3]
static long double _TG_ATTRS __tg_erf (long double __x) static
Definition at line 633 of file tgmath.h.
References __x.
__tg_erfc() [1/3]
static double _TG_ATTRS __tg_erfc (double __x) static
Definition at line 646 of file tgmath.h.
References __x, and erfc.
__tg_erfc() [2/3]
static float _TG_ATTRS __tg_erfc (float __x) static
Definition at line 642 of file tgmath.h.
References __x, and erfcf().
__tg_erfc() [3/3]
static long double _TG_ATTRS __tg_erfc (long double __x) static
Definition at line 650 of file tgmath.h.
References __x.
__tg_exp() [1/6]
static double _TG_ATTRS __tg_exp (double __x) static
Definition at line 412 of file tgmath.h.
References __x, and exp.
__tg_exp() [2/6]
static double _Complex _TG_ATTRS __tg_exp (double _Complex __x) static
Definition at line 424 of file tgmath.h.
References __x.
__tg_exp() [3/6]
static float _TG_ATTRS __tg_exp (float __x) static
Definition at line 408 of file tgmath.h.
References __x, and expf().
__tg_exp() [4/6]
static float _Complex _TG_ATTRS __tg_exp (float _Complex __x) static
Definition at line 420 of file tgmath.h.
References __x.
__tg_exp() [5/6]
static long double _TG_ATTRS __tg_exp (long double __x) static
Definition at line 416 of file tgmath.h.
References __x.
__tg_exp() [6/6]
static long double _Complex _TG_ATTRS __tg_exp (long double _Complex __x) static
Definition at line 428 of file tgmath.h.
References __x.
__tg_exp2() [1/3]
static double _TG_ATTRS __tg_exp2 (double __x) static
Definition at line 663 of file tgmath.h.
References __x, and exp2.
__tg_exp2() [2/3]
static float _TG_ATTRS __tg_exp2 (float __x) static
Definition at line 659 of file tgmath.h.
References __x, and exp2f().
__tg_exp2() [3/3]
static long double _TG_ATTRS __tg_exp2 (long double __x) static
Definition at line 667 of file tgmath.h.
References __x.
__tg_expm1() [1/3]
static double _TG_ATTRS __tg_expm1 (double __x) static
Definition at line 680 of file tgmath.h.
References __x, and expm1.
__tg_expm1() [2/3]
static float _TG_ATTRS __tg_expm1 (float __x) static
Definition at line 676 of file tgmath.h.
References __x, and expm1f().
__tg_expm1() [3/3]
static long double _TG_ATTRS __tg_expm1 (long double __x) static
Definition at line 684 of file tgmath.h.
References __x.
__tg_fabs() [1/6]
static double _TG_ATTRS __tg_fabs (double __x) static
Definition at line 530 of file tgmath.h.
References __x, and fabs.
__tg_fabs() [2/6]
static double _TG_ATTRS __tg_fabs (double _Complex __x) static
Definition at line 542 of file tgmath.h.
References __x.
__tg_fabs() [3/6]
static float _TG_ATTRS __tg_fabs (float __x) static
Definition at line 526 of file tgmath.h.
References __x, and fabsf().
__tg_fabs() [4/6]
static float _TG_ATTRS __tg_fabs (float _Complex __x) static
Definition at line 538 of file tgmath.h.
References __x.
__tg_fabs() [5/6]
static long double _TG_ATTRS __tg_fabs (long double __x) static
Definition at line 534 of file tgmath.h.
References __x.
__tg_fabs() [6/6]
static long double _TG_ATTRS __tg_fabs (long double _Complex __x) static
Definition at line 546 of file tgmath.h.
References __x.
__tg_fdim() [1/3]
static double _TG_ATTRS __tg_fdim (double __x, double __y) static
Definition at line 697 of file tgmath.h.
References __x, __y, and fdim.
__tg_fdim() [2/3]
static float _TG_ATTRS __tg_fdim (float __x, float __y) static
Definition at line 693 of file tgmath.h.
References __x, __y, and fdimf().
__tg_fdim() [3/3]
static long double _TG_ATTRS __tg_fdim (long double __x, long double __y) static
Definition at line 701 of file tgmath.h.
References __x, and __y.
__tg_floor() [1/3]
static double _TG_ATTRS __tg_floor (double __x) static
Definition at line 715 of file tgmath.h.
References __x, and floor.
__tg_floor() [2/3]
static float _TG_ATTRS __tg_floor (float __x) static
Definition at line 711 of file tgmath.h.
References __x, and floorf().
__tg_floor() [3/3]
static long double _TG_ATTRS __tg_floor (long double __x) static
Definition at line 719 of file tgmath.h.
References __x.
__tg_fma() [1/3]
static double _TG_ATTRS __tg_fma (double __x, double __y, double __z) static
Definition at line 733 of file tgmath.h.
References __x, __y, and fma.
__tg_fma() [2/3]
static float _TG_ATTRS __tg_fma (float __x, float __y, float __z) static
Definition at line 728 of file tgmath.h.
References __x, __y, and fmaf().
__tg_fma() [3/3]
static long double _TG_ATTRS __tg_fma (long double __x, long double __y, long double __z) static
Definition at line 738 of file tgmath.h.
References __x, and __y.
__tg_fmax() [1/3]
static double _TG_ATTRS __tg_fmax (double __x, double __y) static
Definition at line 755 of file tgmath.h.
References __x, __y, and fmax.
__tg_fmax() [2/3]
static float _TG_ATTRS __tg_fmax (float __x, float __y) static
Definition at line 751 of file tgmath.h.
References __x, __y, and fmaxf().
__tg_fmax() [3/3]
static long double _TG_ATTRS __tg_fmax (long double __x, long double __y) static
Definition at line 759 of file tgmath.h.
References __x, and __y.
__tg_fmin() [1/3]
static double _TG_ATTRS __tg_fmin (double __x, double __y) static
Definition at line 773 of file tgmath.h.
References __x, __y, and fmin.
__tg_fmin() [2/3]
static float _TG_ATTRS __tg_fmin (float __x, float __y) static
Definition at line 769 of file tgmath.h.
References __x, __y, and fminf().
__tg_fmin() [3/3]
static long double _TG_ATTRS __tg_fmin (long double __x, long double __y) static
Definition at line 777 of file tgmath.h.
References __x, and __y.
__tg_fmod() [1/3]
static double _TG_ATTRS __tg_fmod (double __x, double __y) static
Definition at line 791 of file tgmath.h.
References __x, __y, and fmod.
__tg_fmod() [2/3]
static float _TG_ATTRS __tg_fmod (float __x, float __y) static
Definition at line 787 of file tgmath.h.
References __x, __y, and fmodf().
__tg_fmod() [3/3]
static long double _TG_ATTRS __tg_fmod (long double __x, long double __y) static
Definition at line 795 of file tgmath.h.
References __x, and __y.
__tg_frexp() [1/3]
static double _TG_ATTRS __tg_frexp (double __x, int * __y) static
Definition at line 809 of file tgmath.h.
References __x, __y, and frexp.
__tg_frexp() [2/3]
static float _TG_ATTRS __tg_frexp (float __x, int * __y) static
Definition at line 805 of file tgmath.h.
References __x, __y, and frexpf().
__tg_frexp() [3/3]
static long double _TG_ATTRS __tg_frexp (long double __x, int * __y) static
Definition at line 813 of file tgmath.h.
References __x, and __y.
__tg_hypot() [1/3]
static double _TG_ATTRS __tg_hypot (double __x, double __y) static
Definition at line 826 of file tgmath.h.
References __x, __y, and hypot.
__tg_hypot() [2/3]
static float _TG_ATTRS __tg_hypot (float __x, float __y) static
Definition at line 822 of file tgmath.h.
References __x, __y, and hypotf().
__tg_hypot() [3/3]
static long double _TG_ATTRS __tg_hypot (long double __x, long double __y) static
Definition at line 830 of file tgmath.h.
References __x, and __y.
__tg_ilogb() [1/3]
static int _TG_ATTRS __tg_ilogb (double __x) static
Definition at line 844 of file tgmath.h.
References __x, and ilogb.
__tg_ilogb() [2/3]
static int _TG_ATTRS __tg_ilogb (float __x) static
Definition at line 840 of file tgmath.h.
References __x, and ilogbf().
__tg_ilogb() [3/3]
static int _TG_ATTRS __tg_ilogb (long double __x) static
Definition at line 848 of file tgmath.h.
References __x.
__tg_ldexp() [1/3]
static double _TG_ATTRS __tg_ldexp (double __x, int __y) static
Definition at line 861 of file tgmath.h.
References __x, __y, and ldexp.
__tg_ldexp() [2/3]
static float _TG_ATTRS __tg_ldexp (float __x, int __y) static
Definition at line 857 of file tgmath.h.
References __x, __y, and ldexpf().
__tg_ldexp() [3/3]
static long double _TG_ATTRS __tg_ldexp (long double __x, int __y) static
Definition at line 865 of file tgmath.h.
References __x, and __y.
__tg_lgamma() [1/3]
static double _TG_ATTRS __tg_lgamma (double __x) static
Definition at line 878 of file tgmath.h.
References __x, and lgamma.
__tg_lgamma() [2/3]
static float _TG_ATTRS __tg_lgamma (float __x) static
Definition at line 874 of file tgmath.h.
References __x, and lgammaf().
__tg_lgamma() [3/3]
static long double _TG_ATTRS __tg_lgamma (long double __x) static
Definition at line 882 of file tgmath.h.
References __x.
__tg_llrint() [1/3]
static long long _TG_ATTRS __tg_llrint (double __x) static
Definition at line 895 of file tgmath.h.
References __x, and llrint.
__tg_llrint() [2/3]
static long long _TG_ATTRS __tg_llrint (float __x) static
Definition at line 891 of file tgmath.h.
References __x, and llrintf().
__tg_llrint() [3/3]
static long long _TG_ATTRS __tg_llrint (long double __x) static
Definition at line 899 of file tgmath.h.
References __x.
__tg_llround() [1/3]
static long long _TG_ATTRS __tg_llround (double __x) static
Definition at line 912 of file tgmath.h.
References __x, and llround.
__tg_llround() [2/3]
static long long _TG_ATTRS __tg_llround (float __x) static
Definition at line 908 of file tgmath.h.
References __x, and llroundf().
__tg_llround() [3/3]
static long long _TG_ATTRS __tg_llround (long double __x) static
Definition at line 916 of file tgmath.h.
References __x.
__tg_log() [1/6]
static double _TG_ATTRS __tg_log (double __x) static
Definition at line 441 of file tgmath.h.
References __x, and log.
__tg_log() [2/6]
static double _Complex _TG_ATTRS __tg_log (double _Complex __x) static
Definition at line 453 of file tgmath.h.
References __x.
__tg_log() [3/6]
static float _TG_ATTRS __tg_log (float __x) static
Definition at line 437 of file tgmath.h.
References __x, and logf().
__tg_log() [4/6]
static float _Complex _TG_ATTRS __tg_log (float _Complex __x) static
Definition at line 449 of file tgmath.h.
References __x.
__tg_log() [5/6]
static long double _TG_ATTRS __tg_log (long double __x) static
Definition at line 445 of file tgmath.h.
References __x.
__tg_log() [6/6]
static long double _Complex _TG_ATTRS __tg_log (long double _Complex __x) static
Definition at line 457 of file tgmath.h.
References __x.
__tg_log10() [1/3]
static double _TG_ATTRS __tg_log10 (double __x) static
Definition at line 929 of file tgmath.h.
References __x, and log10.
__tg_log10() [2/3]
static float _TG_ATTRS __tg_log10 (float __x) static
Definition at line 925 of file tgmath.h.
References __x, and log10f().
__tg_log10() [3/3]
static long double _TG_ATTRS __tg_log10 (long double __x) static
Definition at line 933 of file tgmath.h.
References __x.
__tg_log1p() [1/3]
static double _TG_ATTRS __tg_log1p (double __x) static
Definition at line 946 of file tgmath.h.
References __x, and log1p.
__tg_log1p() [2/3]
static float _TG_ATTRS __tg_log1p (float __x) static
Definition at line 942 of file tgmath.h.
References __x, and log1pf().
__tg_log1p() [3/3]
static long double _TG_ATTRS __tg_log1p (long double __x) static
Definition at line 950 of file tgmath.h.
References __x.
__tg_log2() [1/3]
static double _TG_ATTRS __tg_log2 (double __x) static
Definition at line 963 of file tgmath.h.
References __x, and log2.
__tg_log2() [2/3]
static float _TG_ATTRS __tg_log2 (float __x) static
Definition at line 959 of file tgmath.h.
References __x, and log2f().
__tg_log2() [3/3]
static long double _TG_ATTRS __tg_log2 (long double __x) static
Definition at line 967 of file tgmath.h.
References __x.
__tg_logb() [1/3]
static double _TG_ATTRS __tg_logb (double __x) static
Definition at line 980 of file tgmath.h.
References __x, and logb.
__tg_logb() [2/3]
static float _TG_ATTRS __tg_logb (float __x) static
Definition at line 976 of file tgmath.h.
References __x, and logbf().
__tg_logb() [3/3]
static long double _TG_ATTRS __tg_logb (long double __x) static
Definition at line 984 of file tgmath.h.
References __x.
__tg_lrint() [1/3]
static long _TG_ATTRS __tg_lrint (double __x) static
Definition at line 997 of file tgmath.h.
References __x, and lrint.
__tg_lrint() [2/3]
static long _TG_ATTRS __tg_lrint (float __x) static
Definition at line 993 of file tgmath.h.
References __x, and lrintf().
__tg_lrint() [3/3]
static long _TG_ATTRS __tg_lrint (long double __x) static
Definition at line 1001 of file tgmath.h.
References __x.
__tg_lround() [1/3]
static long _TG_ATTRS __tg_lround (double __x) static
Definition at line 1014 of file tgmath.h.
References __x, and lround.
__tg_lround() [2/3]
static long _TG_ATTRS __tg_lround (float __x) static
Definition at line 1010 of file tgmath.h.
References __x, and lroundf().
__tg_lround() [3/3]
static long _TG_ATTRS __tg_lround (long double __x) static
Definition at line 1018 of file tgmath.h.
References __x.
__tg_nearbyint() [1/3]
static double _TG_ATTRS __tg_nearbyint (double __x) static
Definition at line 1031 of file tgmath.h.
References __x, and nearbyint.
__tg_nearbyint() [2/3]
static float _TG_ATTRS __tg_nearbyint (float __x) static
Definition at line 1027 of file tgmath.h.
References __x, and nearbyintf().
__tg_nearbyint() [3/3]
static long double _TG_ATTRS __tg_nearbyint (long double __x) static
Definition at line 1035 of file tgmath.h.
References __x.
__tg_nextafter() [1/3]
static double _TG_ATTRS __tg_nextafter (double __x, double __y) static
Definition at line 1048 of file tgmath.h.
References __x, __y, and nextafter.
__tg_nextafter() [2/3]
static float _TG_ATTRS __tg_nextafter (float __x, float __y) static
Definition at line 1044 of file tgmath.h.
References __x, __y, and nextafterf().
__tg_nextafter() [3/3]
static long double _TG_ATTRS __tg_nextafter (long double __x, long double __y) static
Definition at line 1052 of file tgmath.h.
References __x, and __y.
__tg_nexttoward() [1/3]
static double _TG_ATTRS __tg_nexttoward (double __x, long double __y) static
Definition at line 1066 of file tgmath.h.
References __x, __y, and nexttoward.
__tg_nexttoward() [2/3]
static float _TG_ATTRS __tg_nexttoward (float __x, long double __y) static
Definition at line 1062 of file tgmath.h.
References __x, and __y.
__tg_nexttoward() [3/3]
static long double _TG_ATTRS __tg_nexttoward (long double __x, long double __y) static
Definition at line 1070 of file tgmath.h.
References __x, and __y.
__tg_pow() [1/6]
static double _TG_ATTRS __tg_pow (double __x, double __y) static
Definition at line 470 of file tgmath.h.
References __x, __y, and pow.
__tg_pow() [2/6]
static double _Complex _TG_ATTRS __tg_pow (double _Complex __x, double _Complex __y) static
Definition at line 482 of file tgmath.h.
References __x, and __y.
__tg_pow() [3/6]
static float _TG_ATTRS __tg_pow (float __x, float __y) static
Definition at line 466 of file tgmath.h.
References __x, __y, and powf().
__tg_pow() [4/6]
static float _Complex _TG_ATTRS __tg_pow (float _Complex __x, float _Complex __y) static
Definition at line 478 of file tgmath.h.
References __x, and __y.
__tg_pow() [5/6]
static long double _TG_ATTRS __tg_pow (long double __x, long double __y) static
Definition at line 474 of file tgmath.h.
References __x, and __y.
__tg_pow() [6/6]
static long double _Complex _TG_ATTRS __tg_pow (long double _Complex __x, long double _Complex __y) static
Definition at line 486 of file tgmath.h.
References __x, and __y.
__tg_promote() [1/10]
static _Argument_type_is_not_arithmetic __tg_promote (...) static
__tg_promote() [2/10]
static double _Complex _TG_ATTRSp __tg_promote (double) static
__tg_promote() [3/10]
static float _Complex _TG_ATTRSp __tg_promote (float) static
__tg_promote() [4/10]
static double _TG_ATTRSp __tg_promote (int) static
__tg_promote() [5/10]
static long double _Complex _TG_ATTRSp __tg_promote (long double) static
__tg_promote() [6/10]
static double _TG_ATTRSp __tg_promote (long long) static
__tg_promote() [7/10]
static double _TG_ATTRSp __tg_promote (long) static
__tg_promote() [8/10]
static double _TG_ATTRSp __tg_promote (unsigned int) static
__tg_promote() [9/10]
static double _TG_ATTRSp __tg_promote (unsigned long long) static
__tg_promote() [10/10]
static double _TG_ATTRSp __tg_promote (unsigned long) static
__tg_remainder() [1/3]
static double _TG_ATTRS __tg_remainder (double __x, double __y) static
Definition at line 1083 of file tgmath.h.
References __x, __y, and remainder.
__tg_remainder() [2/3]
static float _TG_ATTRS __tg_remainder (float __x, float __y) static
Definition at line 1079 of file tgmath.h.
References __x, __y, and remainderf().
__tg_remainder() [3/3]
static long double _TG_ATTRS __tg_remainder (long double __x, long double __y) static
Definition at line 1087 of file tgmath.h.
References __x, and __y.
__tg_remquo() [1/3]
static double _TG_ATTRS __tg_remquo (double __x, double __y, int * __z) static
Definition at line 1102 of file tgmath.h.
References __x, __y, and remquo.
__tg_remquo() [2/3]
static float _TG_ATTRS __tg_remquo (float __x, float __y, int * __z) static
Definition at line 1097 of file tgmath.h.
References __x, __y, and remquof().
__tg_remquo() [3/3]
static long double _TG_ATTRS __tg_remquo (long double __x, long double __y, int * __z) static
Definition at line 1107 of file tgmath.h.
References __x, and __y.
__tg_rint() [1/3]
static double _TG_ATTRS __tg_rint (double __x) static
Definition at line 1124 of file tgmath.h.
References __x, and rint.
__tg_rint() [2/3]
static float _TG_ATTRS __tg_rint (float __x) static
Definition at line 1120 of file tgmath.h.
References __x, and rintf().
__tg_rint() [3/3]
static long double _TG_ATTRS __tg_rint (long double __x) static
Definition at line 1128 of file tgmath.h.
References __x.
__tg_round() [1/3]
static double _TG_ATTRS __tg_round (double __x) static
Definition at line 1141 of file tgmath.h.
References __x, and round.
__tg_round() [2/3]
static float _TG_ATTRS __tg_round (float __x) static
Definition at line 1137 of file tgmath.h.
References __x, and roundf().
__tg_round() [3/3]
static long double _TG_ATTRS __tg_round (long double __x) static
Definition at line 1145 of file tgmath.h.
References __x.
__tg_scalbln() [1/3]
static double _TG_ATTRS __tg_scalbln (double __x, long __y) static
Definition at line 1175 of file tgmath.h.
References __x, __y, and scalbln.
__tg_scalbln() [2/3]
static float _TG_ATTRS __tg_scalbln (float __x, long __y) static
Definition at line 1171 of file tgmath.h.
References __x, __y, and scalblnf().
__tg_scalbln() [3/3]
static long double _TG_ATTRS __tg_scalbln (long double __x, long __y) static
Definition at line 1179 of file tgmath.h.
References __x, and __y.
__tg_scalbn() [1/3]
static double _TG_ATTRS __tg_scalbn (double __x, int __y) static
Definition at line 1158 of file tgmath.h.
References __x, __y, and scalbn.
__tg_scalbn() [2/3]
static float _TG_ATTRS __tg_scalbn (float __x, int __y) static
Definition at line 1154 of file tgmath.h.
References __x, __y, and scalbnf().
__tg_scalbn() [3/3]
static long double _TG_ATTRS __tg_scalbn (long double __x, int __y) static
Definition at line 1162 of file tgmath.h.
References __x, and __y.
__tg_sin() [1/6]
static double _TG_ATTRS __tg_sin (double __x) static
Definition at line 267 of file tgmath.h.
References __x, and sin.
__tg_sin() [2/6]
static double _Complex _TG_ATTRS __tg_sin (double _Complex __x) static
Definition at line 279 of file tgmath.h.
References __x.
__tg_sin() [3/6]
static float _TG_ATTRS __tg_sin (float __x) static
Definition at line 263 of file tgmath.h.
References __x, and sinf().
__tg_sin() [4/6]
static float _Complex _TG_ATTRS __tg_sin (float _Complex __x) static
Definition at line 275 of file tgmath.h.
References __x.
__tg_sin() [5/6]
static long double _TG_ATTRS __tg_sin (long double __x) static
Definition at line 271 of file tgmath.h.
References __x.
__tg_sin() [6/6]
static long double _Complex _TG_ATTRS __tg_sin (long double _Complex __x) static
Definition at line 283 of file tgmath.h.
References __x.
__tg_sinh() [1/6]
static double _TG_ATTRS __tg_sinh (double __x) static
Definition at line 354 of file tgmath.h.
References __x, and sinh.
__tg_sinh() [2/6]
static double _Complex _TG_ATTRS __tg_sinh (double _Complex __x) static
Definition at line 366 of file tgmath.h.
References __x.
__tg_sinh() [3/6]
static float _TG_ATTRS __tg_sinh (float __x) static
Definition at line 350 of file tgmath.h.
References __x, and sinhf().
__tg_sinh() [4/6]
static float _Complex _TG_ATTRS __tg_sinh (float _Complex __x) static
Definition at line 362 of file tgmath.h.
References __x.
__tg_sinh() [5/6]
static long double _TG_ATTRS __tg_sinh (long double __x) static
Definition at line 358 of file tgmath.h.
References __x.
__tg_sinh() [6/6]
static long double _Complex _TG_ATTRS __tg_sinh (long double _Complex __x) static
Definition at line 370 of file tgmath.h.
References __x.
__tg_sqrt() [1/6]
static double _TG_ATTRS __tg_sqrt (double __x) static
Definition at line 501 of file tgmath.h.
References __x, and sqrt.
__tg_sqrt() [2/6]
static double _Complex _TG_ATTRS __tg_sqrt (double _Complex __x) static
Definition at line 513 of file tgmath.h.
References __x.
__tg_sqrt() [3/6]
static float _TG_ATTRS __tg_sqrt (float __x) static
Definition at line 497 of file tgmath.h.
References __x, and sqrtf().
__tg_sqrt() [4/6]
static float _Complex _TG_ATTRS __tg_sqrt (float _Complex __x) static
Definition at line 509 of file tgmath.h.
References __x.
__tg_sqrt() [5/6]
static long double _TG_ATTRS __tg_sqrt (long double __x) static
Definition at line 505 of file tgmath.h.
References __x.
__tg_sqrt() [6/6]
static long double _Complex _TG_ATTRS __tg_sqrt (long double _Complex __x) static
Definition at line 517 of file tgmath.h.
References __x.
__tg_tan() [1/6]
static double _TG_ATTRS __tg_tan (double __x) static
Definition at line 296 of file tgmath.h.
References __x, and tan.
__tg_tan() [2/6]
static double _Complex _TG_ATTRS __tg_tan (double _Complex __x) static
Definition at line 308 of file tgmath.h.
References __x.
__tg_tan() [3/6]
static float _TG_ATTRS __tg_tan (float __x) static
Definition at line 292 of file tgmath.h.
References __x, and tanf().
__tg_tan() [4/6]
static float _Complex _TG_ATTRS __tg_tan (float _Complex __x) static
Definition at line 304 of file tgmath.h.
References __x.
__tg_tan() [5/6]
static long double _TG_ATTRS __tg_tan (long double __x) static
Definition at line 300 of file tgmath.h.
References __x.
__tg_tan() [6/6]
static long double _Complex _TG_ATTRS __tg_tan (long double _Complex __x) static
Definition at line 312 of file tgmath.h.
References __x.
__tg_tanh() [1/6]
static double _TG_ATTRS __tg_tanh (double __x) static
Definition at line 383 of file tgmath.h.
References __x, and tanh.
__tg_tanh() [2/6]
static double _Complex _TG_ATTRS __tg_tanh (double _Complex __x) static
Definition at line 395 of file tgmath.h.
References __x.
__tg_tanh() [3/6]
static float _TG_ATTRS __tg_tanh (float __x) static
Definition at line 379 of file tgmath.h.
References __x, and tanhf().
__tg_tanh() [4/6]
static float _Complex _TG_ATTRS __tg_tanh (float _Complex __x) static
Definition at line 391 of file tgmath.h.
References __x.
__tg_tanh() [5/6]
static long double _TG_ATTRS __tg_tanh (long double __x) static
Definition at line 387 of file tgmath.h.
References __x.
__tg_tanh() [6/6]
static long double _Complex _TG_ATTRS __tg_tanh (long double _Complex __x) static
Definition at line 399 of file tgmath.h.
References __x.
__tg_tgamma() [1/3]
static double _TG_ATTRS __tg_tgamma (double __x) static
Definition at line 1192 of file tgmath.h.
References __x, and tgamma.
__tg_tgamma() [2/3]
static float _TG_ATTRS __tg_tgamma (float __x) static
Definition at line 1188 of file tgmath.h.
References __x, and tgammaf().
__tg_tgamma() [3/3]
static long double _TG_ATTRS __tg_tgamma (long double __x) static
Definition at line 1196 of file tgmath.h.
References __x.
__tg_trunc() [1/3]
static double _TG_ATTRS __tg_trunc (double __x) static
Definition at line 1209 of file tgmath.h.
References __x, and trunc.
__tg_trunc() [2/3]
static float _TG_ATTRS __tg_trunc (float __x) static
Definition at line 1205 of file tgmath.h.
References __x, and truncf().
__tg_trunc() [3/3]
static long double _TG_ATTRS __tg_trunc (long double __x) static
Definition at line 1213 of file tgmath.h.
References __x.
Variable Documentation
__overloadable__
_Argument_type_is_not_arithmetic __overloadable__
Definition at line 35 of file tgmath.h.