ETISS 0.8.0: /home/runner/work/etiss/etiss/src/fpu/timesoftfloat.c File Reference
timesoftfloat.c File Reference
implemments a softfloat benchmark
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <stdio.h>
#include <time.h>
#include "etiss/fpu/milieu.h"
#include "etiss/jit/fpu/softfloat.h"
Enumerations
enum { minIterations = 1000 }
enum { numInputs_int32 = 32 }
enum { numInputs_int64 = 32 }
enum { numInputs_float32 = 32 }
enum { numInputs_float64 = 32 }
enum {
INT32_TO_FLOAT32 = 1, INT32_TO_FLOAT64, INT64_TO_FLOAT32, INT64_TO_FLOAT64,
FLOAT32_TO_INT32, FLOAT32_TO_INT32_ROUND_TO_ZERO, FLOAT32_TO_INT64, FLOAT32_TO_INT64_ROUND_TO_ZERO,
FLOAT32_TO_FLOAT64, FLOAT32_ROUND_TO_INT, FLOAT32_ADD, FLOAT32_SUB,
FLOAT32_MUL, FLOAT32_DIV, FLOAT32_REM, FLOAT32_SQRT,
FLOAT32_EQ, FLOAT32_LE, FLOAT32_LT, FLOAT32_EQ_SIGNALING,
FLOAT32_LE_QUIET, FLOAT32_LT_QUIET, FLOAT64_TO_INT32, FLOAT64_TO_INT32_ROUND_TO_ZERO,
FLOAT64_TO_INT64, FLOAT64_TO_INT64_ROUND_TO_ZERO, FLOAT64_TO_FLOAT32, FLOAT64_ROUND_TO_INT,
FLOAT64_ADD, FLOAT64_SUB, FLOAT64_MUL, FLOAT64_DIV,
FLOAT64_REM, FLOAT64_SQRT, FLOAT64_EQ, FLOAT64_LE,
FLOAT64_LT, FLOAT64_EQ_SIGNALING, FLOAT64_LE_QUIET, FLOAT64_LT_QUIET,
NUM_FUNCTIONS
}
enum {
ROUND_NEAREST_EVEN = 1, ROUND_TO_ZERO, ROUND_DOWN, ROUND_UP,
NUM_ROUNDINGMODES
}
enum { TININESS_BEFORE_ROUNDING = 1, TININESS_AFTER_ROUNDING, NUM_TININESSMODES }
Functions
static void fail (const char *message,...)
static void reportTime (int32 count, long clocks)
static void time_a_int32_z_float32 (float32 function(int32, unsigned *))
static void time_a_int32_z_float64 (float64 function(int32))
static void time_a_int64_z_float32 (float32 function(int64, unsigned *))
static void time_a_int64_z_float64 (float64 function(int64, unsigned *))
static void time_a_float32_z_int32 (int32 function(float32, unsigned *))
static void time_a_float32_z_int64 (int64 function(float32, unsigned *))
static void time_a_float32_z_float64 (float64 function(float32, unsigned *))
static void time_az_float32 (float32 function(float32, unsigned *))
static void time_ab_float32_z_flag (flag function(float32, float32, unsigned *))
static void time_abz_float32 (float32 function(float32, float32, unsigned *))
static void time_az_float32_pos (float32 function(float32, unsigned *))
static void time_a_float64_z_int32 (int32 function(float64, unsigned *))
static void time_a_float64_z_int64 (int64 function(float64, unsigned *))
static void time_a_float64_z_float32 (float32 function(float64, unsigned *))
static void time_az_float64 (float64 function(float64, unsigned *))
static void time_ab_float64_z_flag (flag function(float64, float64, unsigned *))
static void time_abz_float64 (float64 function(float64, float64, unsigned *))
static void time_az_float64_pos (float64 function(float64, unsigned *))
static void timeFunctionVariety (uint8 functionCode, int8 roundingPrecision, int8 roundingMode, int8 tininessMode)
static void timeFunction (uint8 functionCode, int8 roundingPrecisionIn, int8 roundingModeIn, int8 tininessModeIn)
main (int argc, char **argv)
Variables
static char * functionName
static char * roundingPrecisionName
static char * roundingModeName
static char * tininessModeName
static const int32 inputs_int32 [numInputs_int32]
static const int64 inputs_int64 [numInputs_int64]
static const float32 inputs_float32 [numInputs_float32]
static const float32 inputs_float32_pos [numInputs_float32]
static const float64 inputs_float64 [numInputs_float64]
static const float64 inputs_float64_pos [numInputs_float64]
struct {
char * name
int8 numInputs
flag roundingPrecision
flag roundingMode
flag tininessMode
flag tininessModeAtReducedPrecision
} functions [NUM_FUNCTIONS]
Detailed Description
implemments a softfloat benchmark
Copyright
This C source file is part of the SoftFloat IEC/IEEE Floating-point Arithmetic Package, Release 2b.
Written by John R. Hauser.
THIS SOFTWARE IS DISTRIBUTED AS IS, FOR FREE.  Although reasonable effort has
been made to avoid it, THIS SOFTWARE MAY CONTAIN FAULTS THAT WILL AT TIMES
RESULT IN INCORRECT BEHAVIOR.  USE OF THIS SOFTWARE IS RESTRICTED TO PERSONS
AND ORGANIZATIONS WHO CAN AND WILL TAKE FULL RESPONSIBILITY FOR ALL LOSSES,
COSTS, OR OTHER PROBLEMS THEY INCUR DUE TO THE SOFTWARE, AND WHO FURTHERMORE
EFFECTIVELY INDEMNIFY THE AUTHOR, JOHN HAUSER, (possibly via similar legal
warning) AGAINST ALL LOSSES, COSTS, OR OTHER PROBLEMS INCURRED BY THEIR
CUSTOMERS AND CLIENTS DUE TO THE SOFTWARE.
Derivative works are acceptable, even for commercial purposes, so long as
(1) the source code for the derivative work includes prominent notice that
the work is derivative, and (2) the source code includes prominent notice with
these four paragraphs for those parts of this code that are retained.
Definition in file timesoftfloat.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
minIterations
Definition at line 42 of file timesoftfloat.c.
anonymous enum
anonymous enum
Enumerator
numInputs_int32
Definition at line 87 of file timesoftfloat.c.
anonymous enum
anonymous enum
Enumerator
numInputs_int64
Definition at line 219 of file timesoftfloat.c.
anonymous enum
anonymous enum
Enumerator
numInputs_float32
Definition at line 376 of file timesoftfloat.c.
anonymous enum
anonymous enum
Enumerator
numInputs_float64
Definition at line 676 of file timesoftfloat.c.
anonymous enum
anonymous enum
Enumerator
INT32_TO_FLOAT32
INT32_TO_FLOAT64
INT64_TO_FLOAT32
INT64_TO_FLOAT64
FLOAT32_TO_INT32
FLOAT32_TO_INT32_ROUND_TO_ZERO
FLOAT32_TO_INT64
FLOAT32_TO_INT64_ROUND_TO_ZERO
FLOAT32_TO_FLOAT64
FLOAT32_ROUND_TO_INT
FLOAT32_ADD
FLOAT32_SUB
FLOAT32_MUL
FLOAT32_DIV
FLOAT32_REM
FLOAT32_SQRT
FLOAT32_EQ
FLOAT32_LE
FLOAT32_LT
FLOAT32_EQ_SIGNALING
FLOAT32_LE_QUIET
FLOAT32_LT_QUIET
FLOAT64_TO_INT32
FLOAT64_TO_INT32_ROUND_TO_ZERO
FLOAT64_TO_INT64
FLOAT64_TO_INT64_ROUND_TO_ZERO
FLOAT64_TO_FLOAT32
FLOAT64_ROUND_TO_INT
FLOAT64_ADD
FLOAT64_SUB
FLOAT64_MUL
FLOAT64_DIV
FLOAT64_REM
FLOAT64_SQRT
FLOAT64_EQ
FLOAT64_LE
FLOAT64_LT
FLOAT64_EQ_SIGNALING
FLOAT64_LE_QUIET
FLOAT64_LT_QUIET
NUM_FUNCTIONS
Definition at line 1814 of file timesoftfloat.c.
anonymous enum
anonymous enum
Enumerator
ROUND_NEAREST_EVEN
ROUND_TO_ZERO
ROUND_DOWN
ROUND_UP
NUM_ROUNDINGMODES
Definition at line 2051 of file timesoftfloat.c.
anonymous enum
anonymous enum
Enumerator
TININESS_BEFORE_ROUNDING
TININESS_AFTER_ROUNDING
NUM_TININESSMODES
Definition at line 2058 of file timesoftfloat.c.
Function Documentation
fail()
static void fail (const char * message, ...) static
Definition at line 46 of file timesoftfloat.c.
References va_end, and va_start.
Referenced by main().
main()
main (int argc, char ** argv)
Definition at line 2494 of file timesoftfloat.c.
References endif(), fail(), FALSE, functions, name, NUM_FUNCTIONS, numInputs, ROUND_DOWN, ROUND_NEAREST_EVEN, ROUND_TO_ZERO, ROUND_UP, roundingMode, roundingPrecision, timeFunction(), TININESS_AFTER_ROUNDING, TININESS_BEFORE_ROUNDING, tininessMode, and TRUE.
reportTime()
static void reportTime (int32 count, long clocks) static
Definition at line 62 of file timesoftfloat.c.
References functionName, printf(), roundingModeName, roundingPrecisionName, and tininessModeName.
Referenced by time_a_float32_z_float64(), time_a_float32_z_int32(), time_a_float32_z_int64(), time_a_float64_z_float32(), time_a_float64_z_int32(), time_a_float64_z_int64(), time_a_int32_z_float32(), time_a_int32_z_float64(), time_a_int64_z_float32(), time_a_int64_z_float64(), time_ab_float32_z_flag(), time_ab_float64_z_flag(), time_abz_float32(), time_abz_float64(), time_az_float32(), time_az_float32_pos(), time_az_float64(), and time_az_float64_pos().
time_a_float32_z_float64()
static void time_a_float32_z_float64 (float64 functionfloat32,unsigned *) static
Definition at line 447 of file timesoftfloat.c.
References clock(), inputs_float32, minIterations, numInputs_float32, and reportTime().
Referenced by timeFunctionVariety().
time_a_float32_z_int32()
static void time_a_float32_z_int32 (int32 functionfloat32,unsigned *) static
Definition at line 391 of file timesoftfloat.c.
References clock(), inputs_float32, minIterations, numInputs_float32, and reportTime().
Referenced by timeFunctionVariety().
time_a_float32_z_int64()
static void time_a_float32_z_int64 (int64 functionfloat32,unsigned *) static
Definition at line 419 of file timesoftfloat.c.
References clock(), inputs_float32, minIterations, numInputs_float32, and reportTime().
Referenced by timeFunctionVariety().
time_a_float64_z_float32()
static void time_a_float64_z_float32 (float32 functionfloat64,unsigned *) static
Definition at line 771 of file timesoftfloat.c.
References clock(), inputs_float64, minIterations, numInputs_float64, and reportTime().
Referenced by timeFunctionVariety().
time_a_float64_z_int32()
static void time_a_float64_z_int32 (int32 functionfloat64,unsigned *) static
Definition at line 715 of file timesoftfloat.c.
References clock(), inputs_float64, minIterations, numInputs_float64, and reportTime().
Referenced by timeFunctionVariety().
time_a_float64_z_int64()
static void time_a_float64_z_int64 (int64 functionfloat64,unsigned *) static
Definition at line 743 of file timesoftfloat.c.
References clock(), inputs_float64, minIterations, numInputs_float64, and reportTime().
Referenced by timeFunctionVariety().
time_a_int32_z_float32()
static void time_a_int32_z_float32 (float32 functionint32,unsigned *) static
Definition at line 102 of file timesoftfloat.c.
References clock(), inputs_int32, minIterations, numInputs_int32, and reportTime().
Referenced by timeFunctionVariety().
time_a_int32_z_float64()
static void time_a_int32_z_float64 (float64 functionint32) static
Definition at line 130 of file timesoftfloat.c.
References clock(), inputs_int32, minIterations, numInputs_int32, and reportTime().
Referenced by timeFunctionVariety().
time_a_int64_z_float32()
static void time_a_int64_z_float32 (float32 functionint64, unsigned *) static
Definition at line 258 of file timesoftfloat.c.
References clock(), inputs_int64, minIterations, numInputs_int64, and reportTime().
Referenced by timeFunctionVariety().
time_a_int64_z_float64()
static void time_a_int64_z_float64 (float64 functionint64,unsigned *) static
Definition at line 286 of file timesoftfloat.c.
References clock(), inputs_int64, minIterations, numInputs_int64, and reportTime().
Referenced by timeFunctionVariety().
time_ab_float32_z_flag()
static void time_ab_float32_z_flag (flag functionfloat32, float32,unsigned *) static
Definition at line 565 of file timesoftfloat.c.
References clock(), inputs_float32, minIterations, numInputs_float32, and reportTime().
Referenced by timeFunctionVariety().
time_ab_float64_z_flag()
static void time_ab_float64_z_flag (flag functionfloat64, float64,unsigned *) static
Definition at line 889 of file timesoftfloat.c.
References clock(), inputs_float64, minIterations, numInputs_float64, and reportTime().
Referenced by timeFunctionVariety().
time_abz_float32()
static void time_abz_float32 (float32 functionfloat32, float32,unsigned *) static
Definition at line 601 of file timesoftfloat.c.
References clock(), inputs_float32, minIterations, numInputs_float32, and reportTime().
Referenced by timeFunctionVariety().
time_abz_float64()
static void time_abz_float64 (float64 functionfloat64, float64,unsigned *) static
Definition at line 925 of file timesoftfloat.c.
References clock(), inputs_float64, minIterations, numInputs_float64, and reportTime().
Referenced by timeFunctionVariety().
time_az_float32()
static void time_az_float32 (float32 functionfloat32,unsigned *) static
Definition at line 537 of file timesoftfloat.c.
References clock(), inputs_float32, minIterations, numInputs_float32, and reportTime().
Referenced by timeFunctionVariety().
time_az_float32_pos()
static void time_az_float32_pos (float32 functionfloat32,unsigned *) static
Definition at line 648 of file timesoftfloat.c.
References clock(), inputs_float32_pos, minIterations, numInputs_float32, and reportTime().
Referenced by timeFunctionVariety().
time_az_float64()
static void time_az_float64 (float64 functionfloat64,unsigned *) static
Definition at line 861 of file timesoftfloat.c.
References clock(), inputs_float64, minIterations, numInputs_float64, and reportTime().
Referenced by timeFunctionVariety().
time_az_float64_pos()
static void time_az_float64_pos (float64 functionfloat64,unsigned *) static
Definition at line 996 of file timesoftfloat.c.
References clock(), inputs_float64_pos, minIterations, numInputs_float64, and reportTime().
Referenced by timeFunctionVariety().
timeFunction()
static void timeFunction (uint8 functionCode, int8 roundingPrecisionIn, int8 roundingModeIn, int8 tininessModeIn) static
Definition at line 2423 of file timesoftfloat.c.
References functions, NUM_ROUNDINGMODES, NUM_TININESSMODES, roundingMode, roundingPrecision, timeFunctionVariety(), tininessMode, and tininessModeAtReducedPrecision.
Referenced by main().
timeFunctionVariety()
static void timeFunctionVariety (uint8 functionCode, int8 roundingPrecision, int8 roundingMode, int8 tininessMode) static
Definition at line 2065 of file timesoftfloat.c.
References float32_add(), FLOAT32_ADD, float32_div(), FLOAT32_DIV, float32_eq(), FLOAT32_EQ, float32_eq_signaling(), FLOAT32_EQ_SIGNALING, float32_le(), FLOAT32_LE, float32_le_quiet(), FLOAT32_LE_QUIET, float32_lt(), FLOAT32_LT, float32_lt_quiet(), FLOAT32_LT_QUIET, float32_mul(), FLOAT32_MUL, float32_rem(), FLOAT32_REM, float32_round_to_int(), FLOAT32_ROUND_TO_INT, float32_sqrt(), FLOAT32_SQRT, float32_sub(), FLOAT32_SUB, float32_to_float64(), FLOAT32_TO_FLOAT64, float32_to_int32(), FLOAT32_TO_INT32, float32_to_int32_round_to_zero(), FLOAT32_TO_INT32_ROUND_TO_ZERO, float32_to_int64(), FLOAT32_TO_INT64, float32_to_int64_round_to_zero(), FLOAT32_TO_INT64_ROUND_TO_ZERO, float64_add(), FLOAT64_ADD, float64_div(), FLOAT64_DIV, float64_eq(), FLOAT64_EQ, float64_eq_signaling(), FLOAT64_EQ_SIGNALING, float64_le(), FLOAT64_LE, float64_le_quiet(), FLOAT64_LE_QUIET, float64_lt(), FLOAT64_LT, float64_lt_quiet(), FLOAT64_LT_QUIET, float64_mul(), FLOAT64_MUL, float64_rem(), FLOAT64_REM, float64_round_to_int(), FLOAT64_ROUND_TO_INT, float64_sqrt(), FLOAT64_SQRT, float64_sub(), FLOAT64_SUB, float64_to_float32(), FLOAT64_TO_FLOAT32, float64_to_int32(), FLOAT64_TO_INT32, float64_to_int32_round_to_zero(), FLOAT64_TO_INT32_ROUND_TO_ZERO, float64_to_int64(), FLOAT64_TO_INT64, float64_to_int64_round_to_zero(), FLOAT64_TO_INT64_ROUND_TO_ZERO, float_detect_tininess, float_round_down, float_round_nearest_even, float_round_to_zero, float_round_up, float_rounding_mode, float_tininess_after_rounding, float_tininess_before_rounding, functionName, functions, int32_to_float32(), INT32_TO_FLOAT32, int32_to_float64(), INT32_TO_FLOAT64, int64_to_float32(), INT64_TO_FLOAT32, int64_to_float64(), INT64_TO_FLOAT64, ROUND_DOWN, ROUND_NEAREST_EVEN, ROUND_TO_ZERO, ROUND_UP, roundingMode, roundingModeName, roundingPrecision, roundingPrecisionName, time_a_float32_z_float64(), time_a_float32_z_int32(), time_a_float32_z_int64(), time_a_float64_z_float32(), time_a_float64_z_int32(), time_a_float64_z_int64(), time_a_int32_z_float32(), time_a_int32_z_float64(), time_a_int64_z_float32(), time_a_int64_z_float64(), time_ab_float32_z_flag(), time_ab_float64_z_flag(), time_abz_float32(), time_abz_float64(), time_az_float32(), time_az_float32_pos(), time_az_float64(), time_az_float64_pos(), TININESS_AFTER_ROUNDING, TININESS_BEFORE_ROUNDING, tininessMode, and tininessModeName.
Referenced by timeFunction().
Variable Documentation
functionName
char* functionName static
Definition at line 59 of file timesoftfloat.c.
Referenced by reportTime(), and timeFunctionVariety().
functions
struct { ... } functions[ NUM_FUNCTIONS ]
Referenced by main(), timeFunction(), and timeFunctionVariety().
inputs_float32
const float32 inputs_float32[numInputs_float32] static
Initial value:
= {
    0x4EFA0000, 0xC1D0B328, 0x80000000, 0x3E69A31E,
    0xAF803EFF, 0x3F800000, 0x17BF8000, 0xE74A301A,
    0x4E010003, 0x7EE3C75D, 0xBD803FE0, 0xBFFEFF00,
    0x7981F800, 0x431FFFFC, 0xC100C000, 0x3D87EFFF,
    0x4103FEFE, 0xBC000007, 0xBF01F7FF, 0x4E6C6B5C,
    0xC187FFFE, 0xC58B9F13, 0x4F88007F, 0xDF004007,
    0xB7FFD7FE, 0x7E8001FB, 0x46EFFBFF, 0x31C10000,
    0xDB428661, 0x33F89B1F, 0xA3BFEFFF, 0x537BFFBE
}
Definition at line 380 of file timesoftfloat.c.
Referenced by time_a_float32_z_float64(), time_a_float32_z_int32(), time_a_float32_z_int64(), time_ab_float32_z_flag(), time_abz_float32(), and time_az_float32().
inputs_float32_pos
const float32 inputs_float32_pos[numInputs_float32] static
Initial value:
= {
    0x4EFA0000, 0x41D0B328, 0x00000000, 0x3E69A31E,
    0x2F803EFF, 0x3F800000, 0x17BF8000, 0x674A301A,
    0x4E010003, 0x7EE3C75D, 0x3D803FE0, 0x3FFEFF00,
    0x7981F800, 0x431FFFFC, 0x4100C000, 0x3D87EFFF,
    0x4103FEFE, 0x3C000007, 0x3F01F7FF, 0x4E6C6B5C,
    0x4187FFFE, 0x458B9F13, 0x4F88007F, 0x5F004007,
    0x37FFD7FE, 0x7E8001FB, 0x46EFFBFF, 0x31C10000,
    0x5B428661, 0x33F89B1F, 0x23BFEFFF, 0x537BFFBE
}
Definition at line 637 of file timesoftfloat.c.
Referenced by time_az_float32_pos().
inputs_float64
const float64 inputs_float64[numInputs_float64] static
Definition at line 680 of file timesoftfloat.c.
Referenced by time_a_float64_z_float32(), time_a_float64_z_int32(), time_a_float64_z_int64(), time_ab_float64_z_flag(), time_abz_float64(), and time_az_float64().
inputs_float64_pos
const float64 inputs_float64_pos[numInputs_float64] static
Definition at line 961 of file timesoftfloat.c.
Referenced by time_az_float64_pos().
inputs_int32
const int32 inputs_int32[numInputs_int32] static
Initial value:
= {
    0xFFFFBB79, 0x405CF80F, 0x00000000, 0xFFFFFD04,
    0xFFF20002, 0x0C8EF795, 0xF00011FF, 0x000006CA,
    0x00009BFE, 0xFF4862E3, 0x9FFFEFFE, 0xFFFFFFB7,
    0x0BFF7FFF, 0x0000F37A, 0x0011DFFE, 0x00000006,
    0xFFF02006, 0xFFFFF7D1, 0x10200003, 0xDE8DF765,
    0x00003E02, 0x000019E8, 0x0008FFFE, 0xFFFFFB5C,
    0xFFDF7FFE, 0x07C42FBF, 0x0FFFE3FF, 0x040B9F13,
    0xBFFFFFF8, 0x0001BF56, 0x000017F6, 0x000A908A
}
Definition at line 91 of file timesoftfloat.c.
Referenced by time_a_int32_z_float32(), and time_a_int32_z_float64().
inputs_int64
const int64 inputs_int64[numInputs_int64] static
Definition at line 223 of file timesoftfloat.c.
Referenced by time_a_int64_z_float32(), and time_a_int64_z_float64().
name
char* name
Definition at line 1931 of file timesoftfloat.c.
Referenced by etiss::RegisterSet::add(), pugi::xpath_variable_set::add(), etiss::mm::PTEFormat::AddBitField(), etiss::VirtualStruct::addField(), etiss::mm::PTEFormatBuilder::AddFlag(), etiss::VirtualStruct::allocateFromC(), OR1KTimer::changedRegister(), etiss::mm::PTE::ClearFlagByName(), etiss::instr::InstructionSet::create(), etiss::instr::VariableInstructionSet::create(), etiss::instr::ModedInstructionSet::create(), etiss::interfaces::Dot::createE(), etiss::interfaces::Dot::createG(), etiss::interfaces::Dot::createN(), etiss::interfaces::VCD::declare(), etiss::interfaces::dot::VariableDependencyGraph::declare(), etiss::interfaces::dot::ValueOperationTraceGraph::defineNode(), etiss::interfaces::dot::ValueOperationTraceGraphStreamer::defineNode(), etiss::mm::PTE::Dump(), etiss::mm::PTEFormat::DumpBitFild(), etiss::VirtualStruct::fastFieldAccessPtr(), pugi::xpath_variable_set::find(), findLibs(), etiss::VirtualStruct::findName(), etiss::VirtualStruct::findPrettyName(), etiss::VirtualStruct::findStruct(), etiss::interfaces::dot::ValueOperationTraceGraph::flush(), pugi::xpath_variable_set::get(), etiss::mm::PTE::GetByName(), etiss::getCPUArch(), TCCJIT::getFunction(), GCCJIT::getFunction(), etiss::LLVMJIT::getFunction(), etiss::fault::Injector::getInjectorPath(), etiss::getJIT(), etiss::GetModuleByName(), etiss::getPlugin(), etiss::CPUCore::getPlugin(), etiss::VirtualStruct::getSubInjector(), etiss::VirtualStruct::listSubInjectors(), etiss::loadLibrary(), local_name(), main(), etiss::VirtualStruct::mountStruct(), IntegratedLibrary::nameCPUArch(), IntegratedLibrary::nameJIT(), IntegratedLibrary::namePlugin(), namespace_uri_predicate::namespace_uri_predicate(), new_xpath_variable(), node_output(), etiss::instr::InstructionSet::open(), etiss::instr::VariableInstructionSet::open(), etiss::instr::ModedInstructionSet::open(), etiss::LibraryInterface::openSharedLibrary(), namespace_uri_predicate::operator()(), xpath_parser::parse_axis_name(), xpath_parser::parse_function(), xpath_parser::parse_node_test_type(), xpath_parser::parse_primary_expression(), xml_parser::parse_tree(), etiss::parseName(), etiss::interfaces::Dot::pcreateN(), pugi::xpath_variable_set::set(), etiss::interfaces::dot::ValueOperationTraceGraphStreamer::Node::setAttr(), etiss::Plugin::setCorrespondingCPUCoreName(), etiss::mm::PTE::SetFlagByName(), xpath_ast_node::step_push(), etiss::instr::InstructionContext::ufield(), and LegacyRegisterDevicePluginListener::write().
numInputs
int8 numInputs
Definition at line 1932 of file timesoftfloat.c.
Referenced by main().
roundingMode
flag roundingMode
Definition at line 1933 of file timesoftfloat.c.
Referenced by float32_round_to_int(), float64_round_to_int(), main(), roundAndPackFloat32(), roundAndPackFloat64(), roundAndPackInt32(), roundAndPackInt64(), timeFunction(), and timeFunctionVariety().
roundingModeName
char * roundingModeName static
Definition at line 60 of file timesoftfloat.c.
Referenced by reportTime(), and timeFunctionVariety().
roundingPrecision
flag roundingPrecision
Definition at line 1933 of file timesoftfloat.c.
Referenced by main(), timeFunction(), and timeFunctionVariety().
roundingPrecisionName
char* roundingPrecisionName static
Definition at line 60 of file timesoftfloat.c.
Referenced by reportTime(), and timeFunctionVariety().
tininessMode
flag tininessMode
Definition at line 1934 of file timesoftfloat.c.
Referenced by main(), timeFunction(), and timeFunctionVariety().
tininessModeAtReducedPrecision
flag tininessModeAtReducedPrecision
Definition at line 1934 of file timesoftfloat.c.
Referenced by timeFunction().
tininessModeName
char * tininessModeName static
Definition at line 60 of file timesoftfloat.c.
Referenced by reportTime(), and timeFunctionVariety().