# Generated on Thu, 06 Aug 2026 12:56:16 +0200.
#
# This file contains the CMake build info for the RV32IMACFDV_zvl128b core architecture.

PROJECT(RV32IMACFDV_zvl128b)
FIND_PACKAGE(ETISS)

SET(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE)
SET(CMAKE_INSTALL_RPATH "\$ORIGIN/../../include/jit/etiss/jit")

ADD_LIBRARY(${PROJECT_NAME} SHARED
	RV32IMACFDV_zvl128bArch.cpp
	RV32IMACFDV_zvl128bArchLib.cpp
	RV32IMACFDV_zvl128bArchSpecificImp.cpp
	RV32IMACFDV_zvl128bFuncs.c
	RV32IMACFDV_zvl128bInstr.cpp
	RV32IMACFDV_zvl128b_RV32IInstr.cpp
	RV32IMACFDV_zvl128b_RV32ICInstr.cpp
	RV32IMACFDV_zvl128b_RV32MInstr.cpp
	RV32IMACFDV_zvl128b_RVZve32xInstr.cpp
	RV32IMACFDV_zvl128b_RVZve64xInstr.cpp
	RV32IMACFDV_zvl128b_RV32FInstr.cpp
	RV32IMACFDV_zvl128b_RVZve32fInstr.cpp
	RV32IMACFDV_zvl128b_RV32FCInstr.cpp
	RV32IMACFDV_zvl128b_ZifenceiInstr.cpp
	RV32IMACFDV_zvl128b_tum_csrInstr.cpp
	RV32IMACFDV_zvl128b_tum_retInstr.cpp
	RV32IMACFDV_zvl128b_RV32AInstr.cpp
	RV32IMACFDV_zvl128b_tum_rvaInstr.cpp
	RV32IMACFDV_zvl128b_tum_semihostingInstr.cpp
)

IF(ETISS_BINARY_DIR)
	ADD_CUSTOM_COMMAND(
		TARGET ${PROJECT_NAME} POST_BUILD
		COMMAND ${CMAKE_COMMAND} -E copy
			"${CMAKE_CURRENT_LIST_DIR}/${PROJECT_NAME}Funcs.h"
			"${ETISS_BINARY_DIR}/include/jit/Arch/${PROJECT_NAME}"
	)
ENDIF()
INSTALL(FILES "${CMAKE_CURRENT_LIST_DIR}/${PROJECT_NAME}Funcs.h" DESTINATION "include/jit/Arch/${PROJECT_NAME}")

# handle gdbserver xml files
IF(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/xml")
	ADD_CUSTOM_TARGET(copy_${PROJECT_NAME}_xml ALL
		COMMAND ${CMAKE_COMMAND} -E make_directory
			"${CMAKE_CURRENT_LIST_DIR}/xml"
		COMMAND ${CMAKE_COMMAND} -E copy_directory
			"${CMAKE_CURRENT_LIST_DIR}/xml"
			"${ETISS_BINARY_DIR}/xml/${PROJECT_NAME}"
	)
	ADD_DEPENDENCIES(${PROJECT_NAME} copy_${PROJECT_NAME}_xml)
	INSTALL(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/xml/ DESTINATION xml/${PROJECT_NAME})
ENDIF()

ETISSPluginArch(${PROJECT_NAME})
